// ============================================================================
// Bab-ul-Fatah — Prisma Database Seeder v2.0
// ============================================================================
// Reads catalog-seed.json or catalog-raw.json (generated by the Darussalam
// scraper) and safely injects all data into the database using relational
// upserts. Idempotent: can be run multiple times without creating duplicates.
//
// SEED STRATEGY:
//   1. Admin user — upsert by email (always seeded, never duplicated)
//   2. Categories — upsert by slug (auto-created from pipeline data)
//   3. Authors    — upsert by name  (auto-created from pipeline data)
//   4. Products   — upsert by slug  (created with full data, updated for sync)
//   5. Images     — ALL images per product (skip-if-exists by productId + url)
// ============================================================================

import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// ─── ESM-compatible __dirname ────────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ─── Types ────────────────────────────────────────────────────────────────────

/** Shape of a single product inside catalog-seed.json (v2: multi-image support) */
interface CatalogProduct {
  title: string;
  slug: string;
  description: string;
  price: number;
  stock: number;
  sku: string;
  language: string;
  imageUrl: string;           // Primary image (backward compat)
  images?: string[];          // ALL images array (v2)
  categoryBreadcrumbs: string[];
  authorName: string | null;
  source?: string;
  extractedAt?: string;
}

/** Shape of the catalog JSON file (with metadata wrapper) */
interface CatalogSeed {
  _meta: {
    generatedAt: string;
    pipelineVersion: string;
    totalProducts: number;
    categories: string[];
    categoryHierarchies: string[][];
    languages: string[];
    source?: string;
  };
  products: CatalogProduct[];
}

// ─── Valid Language enum values from Prisma schema ────────────────────────────

const VALID_LANGUAGES = new Set([
  "URDU",
  "ARABIC",
  "ENGLISH",
  "PUNJABI",
  "SPANISH",
]);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function safeLanguage(raw: string): "URDU" | "ARABIC" | "ENGLISH" | "PUNJABI" | "SPANISH" {
  const upper = raw.toUpperCase().trim();
  if (VALID_LANGUAGES.has(upper)) {
    return upper as "URDU" | "ARABIC" | "ENGLISH" | "PUNJABI" | "SPANISH";
  }
  return "URDU";
}

/**
 * Resolve the absolute path to catalog JSON file.
 * Tries catalog-raw.json first (fresh scrape), then catalog-seed.json (legacy).
 */
function resolveCatalogPath(): string {
  const projectRoot = path.resolve(__dirname, "..");
  const rawPath = path.join(projectRoot, "catalog-raw.json");
  const seedPath = path.join(projectRoot, "catalog-seed.json");

  if (fs.existsSync(rawPath)) {
    console.log(`📂 Using catalog: ${rawPath} (fresh scrape)`);
    return rawPath;
  }
  console.log(`📂 Using catalog: ${seedPath} (legacy)`);
  return seedPath;
}

// ─── Seed Metrics ─────────────────────────────────────────────────────────────

interface SeedMetrics {
  categoriesCreated: number;
  categoriesSkipped: number;
  maxNestingDepth: number;
  authorsCreated: number;
  authorsSkipped: number;
  productsCreated: number;
  productsUpdated: number;
  imagesCreated: number;
  imagesSkipped: number;
  errors: number;
}

function emptyMetrics(): SeedMetrics {
  return {
    categoriesCreated: 0,
    categoriesSkipped: 0,
    maxNestingDepth: 0,
    authorsCreated: 0,
    authorsSkipped: 0,
    productsCreated: 0,
    productsUpdated: 0,
    imagesCreated: 0,
    imagesSkipped: 0,
    errors: 0,
  };
}

// ─── Main Seed Function ───────────────────────────────────────────────────────

async function main() {
  const m = emptyMetrics();
  const startTime = Date.now();

  console.log("");
  console.log("═".repeat(60));
  console.log("  Bab-ul-Fatah — Database Seeder v2.0 (Multi-Image)");
  console.log("═".repeat(60));
  console.log("");

  // ════════════════════════════════════════════════════════════════
  //  PHASE 0: ADMIN USER
  // ════════════════════════════════════════════════════════════════
  const adminEmail = "admin@babulfatah.com";
  const adminPassword = "admin123";

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      password: await bcrypt.hash(adminPassword, 10),
      role: "ADMIN",
    },
  });

  if (admin.createdAt === admin.updatedAt) {
    console.log(`✅ Admin user created: ${adminEmail}`);
  } else {
    console.log(`ℹ️  Admin user exists: ${adminEmail}`);
  }

  // ════════════════════════════════════════════════════════════════
  //  PHASE 1: FILE INGESTION
  // ════════════════════════════════════════════════════════════════
  const catalogPath = resolveCatalogPath();

  if (!fs.existsSync(catalogPath)) {
    console.error(`❌ Catalog file not found at ${catalogPath}`);
    console.error("   Run the scraper first: node scripts/scrape-darussalam.js");
    process.exit(1);
  }

  const rawJson = fs.readFileSync(catalogPath, "utf-8");
  const catalog: CatalogSeed = JSON.parse(rawJson);

  const { products } = catalog;
  const totalProducts = products.length;

  console.log(`📊 Catalog loaded: ${totalProducts} products`);
  console.log(`   Pipeline version: ${catalog._meta.pipelineVersion}`);
  console.log(`   Generated at: ${catalog._meta.generatedAt}`);
  console.log(`   Source: ${catalog._meta.source || "unknown"}`);
  console.log(`   Categories: ${catalog._meta.categories.length} unique`);
  console.log(`   Languages: ${catalog._meta.languages.join(", ")}`);

  // Count total images
  const totalImages = products.reduce((sum, p) => {
    const imgCount = (p.images?.length || 0);
    return sum + (imgCount > 0 ? imgCount : (p.imageUrl ? 1 : 0));
  }, 0);
  console.log(`   Total images: ${totalImages}`);
  console.log("");

  // ════════════════════════════════════════════════════════════════
  //  PHASE 2: RELATIONAL UPSERTING
  // ════════════════════════════════════════════════════════════════
  console.log("── Phase 2: Upserting Categories & Authors ──");
  console.log("");

  // ── Category Cache (slug → DB id) ──
  const categoryIdCache: Map<string, string> = new Map();

  // ── Author Cache (name → DB id) ──
  const authorIdCache: Map<string, string> = new Map();

  // Pre-collect all unique authors from the catalog
  const uniqueAuthors = new Set<string>();

  // ── Collect all category breadcrumb hierarchies ──
  const allBreadcrumbs: string[][] = [];
  for (const product of products) {
    if (product.categoryBreadcrumbs && product.categoryBreadcrumbs.length > 0) {
      allBreadcrumbs.push(product.categoryBreadcrumbs);
    }
    if (product.authorName) uniqueAuthors.add(product.authorName);
  }

  // Deduplicate hierarchies to avoid repeated processing
  const uniqueHierarchies = [...new Set(allBreadcrumbs.map(h => JSON.stringify(h)))].map(h => JSON.parse(h));
  console.log(`   Unique category hierarchies: ${uniqueHierarchies.length}`);
  console.log(`   Unique authors: ${uniqueAuthors.size}`);
  console.log("");

  // ── Upsert Nested Category Hierarchy ──
  async function upsertCategoryChain(
    breadcrumbs: string[],
    parentCategorySlug: string | null,
    parentCategoryId: string | null,
    depth: number
  ): Promise<string> {
    if (depth >= breadcrumbs.length) {
      return parentCategoryId!;
    }

    const categoryName = breadcrumbs[depth];
    const categorySlug = categoryName
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s\-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || `cat-${depth}`;

    const cacheKey = `${categorySlug}|${parentCategoryId || "root"}`;

    if (categoryIdCache.has(cacheKey)) {
      return upsertCategoryChain(breadcrumbs, categorySlug, categoryIdCache.get(cacheKey)!, depth + 1);
    }

    const displayName = categoryName
      .split(" ")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ");

    // ── Upsert Category ──
    // Prisma's findUnique/upsert with compound key doesn't accept null parentId.
    // Handle root (null parentId) and nested separately.

    let category;

    if (parentCategoryId === null) {
      // Root level: use findFirst + upsert pattern
      const existing = await prisma.category.findFirst({
        where: { slug: categorySlug, parentId: null },
      });

      if (existing) {
        category = await prisma.category.update({
          where: { id: existing.id },
          data: { name: displayName },
        });
        m.categoriesSkipped++;
      } else {
        category = await prisma.category.create({
          data: { name: displayName, slug: categorySlug, parentId: null },
        });
        m.categoriesCreated++;
        if (depth + 1 > m.maxNestingDepth) m.maxNestingDepth = depth + 1;
        console.log(`  ✅ Category: ${displayName} (ROOT)`);
      }
    } else {
      // Nested level: use compound unique
      const existing = await prisma.category.findUnique({
        where: { slug_parentId: { slug: categorySlug, parentId: parentCategoryId } },
      });

      if (existing) {
        category = await prisma.category.update({
          where: { id: existing.id },
          data: { name: displayName },
        });
        m.categoriesSkipped++;
      } else {
        category = await prisma.category.create({
          data: { name: displayName, slug: categorySlug, parentId: parentCategoryId },
        });
        m.categoriesCreated++;
        if (depth + 1 > m.maxNestingDepth) m.maxNestingDepth = depth + 1;
        const indent = "  ".repeat(depth + 1);
        console.log(`${indent}✅ Category: ${displayName}`);
      }
    }

    categoryIdCache.set(cacheKey, category.id);

    return upsertCategoryChain(breadcrumbs, categorySlug, category.id, depth + 1);
  }

  // Process all unique breadcrumb hierarchies
  for (const breadcrumbs of uniqueHierarchies) {
    const deepestId = await upsertCategoryChain(breadcrumbs, null, null, 0);
    const pathKey = breadcrumbs.map((b) =>
      b.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80)
    ).join("/");
    categoryIdCache.set(pathKey, deepestId);
  }

  console.log("");

  // ── Upsert Authors ──
  for (const name of uniqueAuthors) {
    const existing = await prisma.author.findFirst({ where: { name } });

    let authorId: string;
    if (existing) {
      authorId = existing.id;
      m.authorsSkipped++;
    } else {
      const created = await prisma.author.create({ data: { name } });
      authorId = created.id;
      m.authorsCreated++;
      console.log(`  ✅ Author: ${name}`);
    }

    authorIdCache.set(name, authorId);
  }

  console.log("");
  console.log(`   Authors: ${m.authorsCreated} created, ${m.authorsSkipped} existing`);
  console.log("");

  // ════════════════════════════════════════════════════════════════
  //  PHASE 3: PRODUCT & IMAGE INJECTION
  // ════════════════════════════════════════════════════════════════
  console.log("── Phase 3: Injecting Products & Images ──");
  console.log("");

  // Pre-build a batch of existing slugs for faster lookup
  const existingSlugs = new Set(
    (await prisma.product.findMany({ select: { slug: true } })).map(p => p.slug)
  );

  for (let i = 0; i < totalProducts; i++) {
    const product = products[i];
    const progress = `[${String(i + 1).padStart(4, "0")}/${totalProducts}]`;

    try {
      // ── Resolve Foreign Keys ──
      const breadcrumbSlugPath = product.categoryBreadcrumbs
        .map((b) =>
          b.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80)
        )
        .join("/");

      const categoryId = categoryIdCache.get(breadcrumbSlugPath);
      if (!categoryId) {
        console.log(`  ⚠️  ${progress} SKIP "${product.title}" — category not resolved`);
        m.errors++;
        continue;
      }

      const authorId = product.authorName
        ? authorIdCache.get(product.authorName) ?? null
        : null;

      // ── Handle SKU uniqueness ──
      let finalSku = product.sku;
      if (finalSku) {
        const suffix = product.slug.slice(-3).replace(/[^a-z0-9]/g, "");
        finalSku = `${finalSku}-${suffix}`;
      }

      // ── Upsert Product ──
      const language = safeLanguage(product.language);
      const productExists = existingSlugs.has(product.slug);

      const upserted = await prisma.product.upsert({
        where: { slug: product.slug },
        update: {
          title: product.title,
          description: product.description,
          price: product.price,
          stock: product.stock,
          language,
          categoryId,
          authorId,
          ...(finalSku ? { sku: finalSku } : {}),
        },
        create: {
          title: product.title,
          slug: product.slug,
          description: product.description,
          price: product.price,
          stock: product.stock,
          language,
          categoryId,
          authorId,
          ...(finalSku ? { sku: finalSku } : {}),
        },
      });

      if (!productExists) {
        existingSlugs.add(product.slug);
        m.productsCreated++;
      } else {
        m.productsUpdated++;
      }

      // Progress logging (every 50 products)
      if ((i + 1) % 50 === 0 || i === 0) {
        const action = productExists ? "🔄 Updated" : "✅ Created";
        console.log(`  ${action} ${progress}: ${product.title.slice(0, 60)}`);
      }

      // ── Multi-Image Injection ──
      // Collect all image URLs: prefer images array, fall back to imageUrl
      const allImageUrls: string[] = [];

      if (product.images && product.images.length > 0) {
        // v2: multi-image array
        for (const imgUrl of product.images) {
          if (imgUrl && imgUrl.startsWith("http")) {
            allImageUrls.push(imgUrl);
          }
        }
      } else if (product.imageUrl) {
        // v1 fallback: single imageUrl
        if (product.imageUrl.startsWith("http")) {
          allImageUrls.push(product.imageUrl);
        }
      }

      // Deduplicate URLs for this product
      const uniqueUrls = [...new Set(allImageUrls)];

      // Batch insert images (using createMany for efficiency)
      for (const imgUrl of uniqueUrls) {
        // Check existence — use a simple findFirst for dedup
        const existingImage = await prisma.image.findFirst({
          where: { productId: upserted.id, url: imgUrl },
          select: { id: true },
        });

        if (!existingImage) {
          await prisma.image.create({
            data: {
              url: imgUrl,
              altText: product.title,
              productId: upserted.id,
            },
          });
          m.imagesCreated++;
        } else {
          m.imagesSkipped++;
        }
      }
    } catch (err) {
      m.errors++;
      // Only log first 10 errors to avoid spam
      if (m.errors <= 10) {
        console.log(`  ❌ ${progress} ERROR on "${product.title.slice(0, 40)}": ${(err as Error).message.slice(0, 100)}`);
      }
    }
  }

  // ════════════════════════════════════════════════════════════════
  //  SUMMARY
  // ════════════════════════════════════════════════════════════════
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  console.log("");
  console.log("═".repeat(60));
  console.log("  SEED COMPLETE");
  console.log("═".repeat(60));
  console.log(`  Categories created  : ${m.categoriesCreated}`);
  console.log(`  Categories skipped  : ${m.categoriesSkipped}`);
  console.log(`  Max nesting depth   : ${m.maxNestingDepth} levels`);
  console.log(`  Authors created     : ${m.authorsCreated}`);
  console.log(`  Authors skipped     : ${m.authorsSkipped}`);
  console.log(`  Products created    : ${m.productsCreated}`);
  console.log(`  Products updated    : ${m.productsUpdated}`);
  console.log(`  Images linked       : ${m.imagesCreated}`);
  console.log(`  Images skipped      : ${m.imagesSkipped}`);
  if (m.errors > 0) {
    console.log(`  ⚠️  Errors            : ${m.errors}`);
  }
  console.log(`  Total products      : ${m.productsCreated + m.productsUpdated}`);
  console.log(`  Elapsed             : ${elapsed}s`);
  console.log("═".repeat(60));
  console.log("");

  if (m.errors > 0) {
    console.log(`⚠️  Completed with ${m.errors} error(s). Review the output above.`);
  } else {
    console.log("✅ All data injected successfully. No errors.");
  }
}

// ─── Execution with Safety Wrapper ────────────────────────────────────────────

const prisma = new PrismaClient();

main()
  .catch((e) => {
    console.error("");
    console.error("═══════════════════════════════════════════════");
    console.error("  SEED FAILED — Unhandled Exception");
    console.error("═══════════════════════════════════════════════");
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
