const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "anokha-safar",
    description: `Anokha Safar is an Urdu-language Islamic book whose title translates to "A Unique Journey," presenting a narrative that takes readers through an extraordinary account drawn from Islamic history or moral teaching. Written in clear and accessible Urdu prose, this book is designed to engage readers who enjoy Islamic storytelling that combines factual historical context with literary flair. The author weaves together events and lessons in a manner that holds the reader's attention while conveying meaningful Islamic values and principles that remain relevant to contemporary life.

The narrative structure of Anokha Safar follows a journey — either literal or metaphorical — that introduces the reader to significant episodes from Islamic tradition. The book is written in a style that appeals to a broad Urdu readership, including young adults, families reading together, and individuals who prefer narrative-based Islamic literature over purely academic or jurisprudential works. The language used is standard literary Urdu, avoiding overly complex vocabulary while maintaining the dignity and eloquence expected of Islamic literature. This balance makes the book suitable for readers with moderate Urdu proficiency as well as those who are fully fluent.

The physical book is produced in a standard paperback or hardback format commonly used for Urdu Islamic titles. The pages are printed on quality paper that supports clear readability of the Urdu text in Nastaliq or Naskh script, depending on the typesetting chosen by the publisher. The cover design typically features thematic artwork or calligraphy that reflects the content. The binding is sturdy enough to withstand regular reading and handling. Anokha Safar serves as both an entertaining read and an educational resource, making it a suitable addition to home Islamic libraries, madrasah reading lists, and community library collections where Urdu-language Islamic books are valued.`,
    metaDescription: "Anokha Safar is a unique Urdu Islamic book presenting an engaging narrative journey. Written in clear Urdu for families, youth, and general readers."
  },
  {
    slug: "anokha-sakhi",
    description: `Anokha Sakhi is an Urdu-language Islamic book whose title means "A Unique Story" or "An Extraordinary Tale." This book belongs to the popular genre of Islamic storytelling in Urdu literature, where significant events, moral lessons, and historical accounts are presented in a narrative format that makes them accessible and engaging for a wide range of readers. The book draws upon authentic Islamic sources to construct its narrative, ensuring that the stories it tells are grounded in verified traditions and historical records rather than fictional embellishments.

The content of Anokha Sakhi focuses on recounting remarkable incidents from Islamic history that carry lasting moral and spiritual lessons. The author has selected stories that demonstrate key Islamic values such as patience, trust in Allah, justice, compassion, courage, and steadfastness in faith. Each story is presented with enough historical context for the reader to understand the circumstances and significance of the events being described, while the narrative pacing keeps the account lively and absorbing. The writing style is engaging but never sacrifices accuracy for dramatic effect, maintaining the scholarly integrity that readers expect from Islamic literature.

The book is printed in standard Urdu script on quality paper, with clear typesetting that makes reading comfortable even during extended sessions. The cover design typically incorporates Islamic artistic elements that hint at the content within. The physical production follows the conventions of Urdu Islamic publishing, with a binding style suited to regular use. Anokha Sakhi is popular among Urdu-speaking families who read Islamic books together at home, among madrasah teachers who use stories to supplement their lessons, and among individual readers who find narrative-based Islamic content more engaging than purely academic texts. It makes a meaningful gift for Urdu-speaking Muslims of various age groups and is commonly found in home libraries, Islamic bookstores, and community lending libraries throughout Pakistan and among Urdu-speaking communities worldwide.`,
    metaDescription: "Anokha Sakhi is an Urdu Islamic book presenting extraordinary stories from Islamic history. Engaging narrative teaching patience, faith, and moral values."
  },
  {
    slug: "anokhay-mehmaan-qissa-syedna-ishaq-silsila-qasas-ul-anbiya-830",
    description: `Anokhay Mehmaan (Qissa Syedna Ishaq) Silsila Qasas ul Anbiya 8/30 is the eighth installment in the extensive Silsila Qasas ul Anbiya (Series of Stories of the Prophets), a comprehensive Urdu-language collection that narrates the life stories of all the prophets mentioned in the Quran and authentic Islamic traditions. This particular volume is dedicated to the story of Prophet Ishaq (Isaac), peace be upon him, with the title "Anokhay Mehmaan" meaning "The Unique Guests" — a reference to the remarkable incident when angels visited Prophet Ibrahim and his wife in the form of human guests, bringing the glad tidings of Ishaq's birth.

The book presents the complete narrative of Prophet Ishaq's life based on Quranic accounts and verified hadith literature. It covers the background of his miraculous birth to elderly parents Ibrahim and Sarah, the fulfillment of Allah's promise to Ibrahim regarding his progeny, Ishaq's role as a prophet and the continuation of the Abrahamic line of prophethood, and the key events and lessons associated with his life and mission. The author provides contextual information that helps readers understand the geographical, social, and spiritual setting in which these events took place, making the narrative more vivid and relatable. The story of Ishaq is told in a style that highlights themes of divine promise, patience in old age, gratitude for Allah's blessings, and the continuity of the prophetic mission across generations.

As volume 8 of a 30-volume series, this book maintains the consistent formatting and presentation style established in the earlier volumes. The series is designed so that each volume can be read independently while also forming a coherent chronological narrative when read as a complete set. The Urdu prose is clear and engaging, suitable for readers of various ages including teenagers and adults. The physical book is produced in a standard format with readable print, durable binding, and a cover design that identifies it as part of the Qasas ul Anbiya series. This volume, like the others in the series, is widely used in madrasahs, Islamic schools, and home libraries for both educational and recreational reading about the lives of Allah's prophets.`,
    metaDescription: "Anokhay Mehmaan is volume 8 of Silsila Qasas ul Anbiya covering Prophet Ishaq's story. Urdu narration of the miraculous birth and prophetic mission."
  },
  {
    slug: "anokhi-khushkhabri-qissa-syedna-zakariyya-silsila-qasas-ul-anbiya-2730",
    description: `Anokhi Khushkhabri (Qissa Syedna Zakariyya) Silsila Qasas ul Anbiya 27/30 is the twenty-seventh volume of the Silsila Qasas ul Anbiya series, a monumental 30-volume Urdu collection narrating the stories of all the prophets. This volume is dedicated to Prophet Zakariyya (Zechariah), peace be upon him, with the title "Anokhi Khushkhabri" meaning "The Unique Good News" — referring to the angelic announcement to Zakariyya that he would be blessed with a son, Prophet Yahya (John the Baptist), despite his old age and his wife's barrenness.

The book provides a comprehensive account of Prophet Zakariyya's life drawn from the Quran, particularly Surah Maryam and Surah Al-Anbiya, and from authenticated hadith sources. It covers his role as a caretaker of Maryam (Mary) in the sanctuary of Jerusalem, his earnest supplication to Allah for righteous offspring, the miraculous news delivered by the angels, the birth and upbringing of Yahya, and Zakariyya's steadfastness in his prophetic mission despite facing opposition from his community. The author presents these events with careful attention to the Quranic text, providing relevant verse references and explanatory notes that help the reader understand the deeper significance of each episode. The narrative also explores the themes of divine response to sincere supplication, the power of Allah to overcome natural limitations, and the rewards of patience and unwavering faith.

As volume 27 of the 30-part series, this book arrives near the conclusion of the comprehensive prophetic history. The writing maintains the same accessible yet scholarly Urdu prose that characterizes the entire series, making it suitable for readers ranging from young adults to senior scholars. The physical production includes clear Urdu typesetting, quality paper for extended reading, and a cover design consistent with the series branding. This volume is particularly valued for its treatment of dua (supplication) as a central theme, making it a source of inspiration for readers facing personal challenges or hoping for Allah's blessings in their own lives. It is commonly used in madrasah curricula, Islamic study circles, and home reading environments.`,
    metaDescription: "Anokhi Khushkhabri is volume 27 of Qasas ul Anbiya covering Prophet Zakariyya. Urdu account of his dua, miracles, and the birth of Prophet Yahya."
  },
  {
    slug: "aqwam-e-aalam-kay-adyan-o-mazahib",
    description: `Aqwam e Aalam Kay Adyan o Mazahib is an Urdu-language reference book that provides a comprehensive survey of the religions and belief systems followed by different nations and peoples throughout the world. The title translates to "The Religions and Sects of the World's Nations," indicating its scope as a broad comparative study of global religious traditions. This book serves as an important academic resource for Urdu-speaking students of comparative religion, Islamic scholars, daee (those engaged in Islamic outreach), and general readers who wish to understand the beliefs and practices of other faiths from an informed Islamic perspective.

The book systematically covers the major world religions including Judaism, Christianity, Hinduism, Buddhism, Sikhism, Zoroastrianism, and various other belief systems, examining each one's foundational beliefs, scriptures, key figures, rituals, denominations, and historical development. For each religion, the author presents factual information about what its followers believe and practice, drawing upon established academic sources and the original texts of those religions. The Islamic perspective on each faith is also addressed, with references to relevant Quranic verses and hadith where Islam has commented on or interacted with other religious traditions. The book also covers various sects and sub-denominations within major religions, providing a detailed picture of the diversity within each faith tradition.

The treatment is scholarly and objective in tone, presenting information about other religions in a manner that is factually accurate and respectful while maintaining the Islamic worldview. This approach makes the book useful for Muslims who engage in interfaith dialogue, participate in dawah activities, or simply want to be well-informed about the beliefs of their neighbors and colleagues. The book is printed in a standard reference format with clear Urdu typesetting, organized chapters for each religion, and likely includes an index or table of contents for easy navigation. The binding and paper quality are designed to withstand regular consultation as a reference work. It is commonly used in Islamic seminaries (darul ulooms), universities with Islamic studies departments, and by individual scholars and students who need a reliable Urdu-language reference on world religions.`,
    metaDescription: "Aqwam e Aalam Kay Adyan o Mazahib is a comprehensive Urdu reference on world religions and sects. Scholarly comparative study from an Islamic perspective."
  },
  {
    slug: "aqziya-tul-khulafa-ur-rashideen-2-vols-set",
    description: `Aqziya tul Khulafa ur Rashideen is a two-volume Urdu set that compiles the judicial cases, legal decisions, and court proceedings of the four Rightly Guided Caliphs — Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, and Ali ibn Abi Talib, may Allah be pleased with them all. The title translates to "The Judicial Cases of the Rightly Guided Caliphs," making it a specialized legal and historical reference that documents how the earliest leaders of the Muslim community administered justice and resolved disputes according to Islamic law.

The two volumes systematically organize the cases handled by each caliph during their respective periods of leadership. Each case is presented with the relevant historical context, the facts of the dispute, the legal reasoning applied by the caliph, the verdict rendered, and the basis in Quranic injunctions, prophetic tradition, or juristic principles (ijtihad) that supported the decision. The cases cover a wide range of legal areas including property disputes, criminal matters, family law, inheritance, contractual disagreements, and governance issues. The documentation provides readers with a practical understanding of how Islamic law was applied in real-world situations during the formative period of the Islamic state, offering insights that are directly relevant to contemporary Islamic jurisprudence.

The work draws upon authenticated historical sources including the classical works of seerah, early Islamic history, and the judicial writings of classical scholars. The Urdu text is written in a scholarly register that is accessible to students of Islamic law and general readers with an interest in Islamic legal history. Each volume is separately bound, and the two-volume set is typically sold together as a complete reference package. The physical production includes clear typesetting with appropriate formatting for legal texts, quality paper, and durable binding suitable for a reference work that will be consulted repeatedly. This set is widely used in Islamic seminaries, law colleges with Islamic law departments, and by researchers and students of Islamic jurisprudence who want to study the practical application of Shariah during the period of the Khulafa ur Rashideen. It also serves as a valuable resource for qadis (Islamic judges) and legal practitioners who reference historical precedents in their work.`,
    metaDescription: "Aqziya tul Khulafa ur Rashideen is a 2-volume Urdu set of judicial cases of the four Rightly Guided Caliphs. Key Islamic legal history reference."
  },
  {
    slug: "aqziya-tur-rasool-allah-2-vols-set",
    description: `Aqziya tur Rasool Allah is a comprehensive two-volume Urdu compilation that documents the judicial cases, legal verdicts, and dispute resolution methods employed by Prophet Muhammad (peace be upon him) during his lifetime as the head of the Muslim community in Madinah. The title means "The Judicial Cases of the Messenger of Allah," and it represents one of the most important primary sources for understanding how Islamic law was practically applied by the Prophet himself — the ultimate interpreter of divine guidance and the highest judicial authority in Islam.

The two volumes meticulously record the cases that came before the Prophet for adjudication, organized by category or by chronological order. Each case entry typically includes the historical context, the parties involved, the nature of the dispute, the arguments presented, the questions the Prophet asked, the evidence he considered, his ruling or judgment, and the Islamic legal principles derived from his decision. The cases span the full spectrum of legal matters including criminal justice, civil disputes, commercial transactions, property rights, family law, inheritance, interpersonal conflicts, and matters of governance and treaty obligations. The author has drawn these accounts from the most reliable sources of hadith and seerah, cross-referencing multiple narrations where available to present the most accurate version of each case.

For students and scholars of Islamic jurisprudence (fiqh), this work is invaluable because the Prophet's judicial decisions form the primary basis for Islamic legal methodology. Every major school of Islamic law ultimately traces its rulings back to the practice and judgments of the Prophet. The Urdu text is written in clear, scholarly prose with appropriate referencing to hadith sources. The two-volume set is produced with quality paper, clear typesetting, and durable hardback binding designed for repeated reference use. It is an essential holding for Islamic seminaries, law schools, research libraries, and the personal collections of Islamic legal scholars and students. The set also holds broader appeal for any Muslim interested in understanding the Prophet's role as a judge and the foundational principles of Islamic justice as they were established and demonstrated during his lifetime.`,
    metaDescription: "Aqziya tur Rasool Allah is a 2-volume Urdu compilation of the Prophet's judicial cases. Primary source for Islamic legal methodology and jurisprudence."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu",
    description: `Ar Raheeq Al Makhtum (Urdu) is the Urdu translation of one of the most celebrated and widely read books on the life of Prophet Muhammad (peace be upon him). The original Arabic work, titled "Ar-Raheeq Al-Makhtum" (The Sealed Nectar), was authored by Safiur Rahman Mubarakpuri and was awarded first prize by the Rabitat al-Alam al-Islami (Muslim World League) in a worldwide competition for seerah writing. This Urdu edition makes this authoritative biography accessible to the vast Urdu-speaking Muslim population across Pakistan, India, Bangladesh, and diaspora communities worldwide.

The book provides a comprehensive and chronologically organized account of the Prophet's life from before his birth — including the background of his ancestors from Prophet Ibrahim through Hashim and Abdul Muttalib — through his childhood, youth, prophethood, the Makkan period of persecution and struggle, the migration to Madinah, the establishment of the Islamic state, the various battles and treaties, the conquest of Makkah, the farewell pilgrimage, and his illness and passing. The author carefully distinguishes between authenticated reports from reliable sources and weaker narrations, providing source references for the information presented. This scholarly approach has made Ar-Raheeq Al-Makhtum a trusted reference work in Islamic educational institutions around the world.

The Urdu translation faithfully conveys the content and scholarly rigor of the original Arabic while using clear, readable Urdu prose that is accessible to readers with moderate to advanced Urdu proficiency. The book is organized into clearly defined chapters and sections, making it easy to navigate to specific periods or events in the Prophet's life. The physical edition is produced in a standard book format with quality paper, clear typesetting of the Urdu text, and a durable cover. It is commonly used as a textbook in madrasahs and Islamic schools for seerah study, as a reference for khutbah (sermon) preparation, and as a personal reading book for families and individuals who want to deepen their knowledge and love of the Prophet. The Urdu edition of Ar-Raheeq Al-Makhtum remains one of the most commonly recommended seerah books in Urdu-speaking Islamic circles.`,
    metaDescription: "Ar Raheeq Al Makhtum Urdu is the authoritative Urdu translation of the award-winning seerah by Mubarakpuri. Complete Prophet's biography in clear Urdu."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu-aala-quality",
    description: `Ar Raheeq Al Makhtum (Urdu) Aala Quality is the premium edition of the celebrated Urdu translation of Safiur Rahman Mubarakpuri's award-winning biography of Prophet Muhammad (peace be upon him). The "Aala Quality" (superior quality) designation indicates that this edition uses enhanced production materials including superior paper stock, higher-resolution printing, and more refined cover and binding compared to the standard edition. This premium version is intended for readers who want a more durable and aesthetically pleasing copy of this essential seerah text — whether for personal library collections, gift-giving, or institutional use where presentation quality matters.

The content of this Aala Quality edition is identical to the standard Urdu translation of Ar-Raheeq Al-Makhtum, covering the complete biography of the Prophet from the history of his ancestors through his birth, prophethood, the Makkan and Madinan periods, military campaigns, treaties, the Farewell Hajj, and his passing. What distinguishes this edition is the physical production quality. The paper used is typically a heavier, whiter, and more opaque stock that provides a superior reading experience with no text show-through and a premium feel under the fingers. The printing is sharper and more consistent, with the Urdu Nastaliq or Naskh script rendered at higher resolution for maximum clarity. The cover often features a more elaborate design with superior finishing — potentially including gold or silver foil stamping, embossed elements, or a laminated finish with enhanced durability.

The binding of the Aala Quality edition is reinforced to provide longevity, using techniques and materials that ensure the book withstands years of regular use and handling without the spine cracking or pages becoming loose. This makes it particularly suitable as a lifelong reference book and a treasured gift for weddings, graduations, Eid occasions, and other special events. The book is widely purchased by individuals building premium home Islamic libraries, by Islamic institutions that want to display quality editions in their collections, and by those who prefer to give gifts that are both meaningful and beautifully produced. Despite the enhanced production quality, the content maintains the same scholarly standards that earned the original Arabic work its international acclaim and first-place award from the Muslim World League.`,
    metaDescription: "Ar Raheeq Al Makhtum Urdu Aala Quality is the premium edition with superior paper, printing, and binding. A gift-worthy Urdu seerah of Prophet Muhammad."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu-big",
    description: `Ar Raheeq Al Makhtum (Urdu) Big is the large-format edition of the Urdu translation of Safiur Rahman Mubarakpuri's acclaimed biography of Prophet Muhammad (peace be upon him). This oversized edition is specifically designed for readers who benefit from larger text, including elderly individuals, people with visual impairments, Islamic teachers who use the book for classroom instruction, and imams and khateebs who read from it during sermons and lectures. The larger physical dimensions of the book translate directly to larger printed text, making every word easier to read without eye strain.

The content in this big format edition is the same comprehensive seerah that has made Ar-Raheeq Al-Makhtum the most widely read and trusted biography of the Prophet in the Muslim world. The book covers the Prophet's entire life journey in meticulous detail, from the lineage of his forefathers through the major events of his prophetic mission, organized chronologically with clear chapter divisions. Each significant event is presented with its historical context, relevant Quranic verses, and references to authenticated hadith sources. The scholarly methodology of the original author is preserved in this Urdu translation, with weak narrations identified and strong sources prioritized throughout.

The large format provides practical advantages beyond just text size. In classroom settings, a teacher can place the big edition on a desk and read from it while students follow along in their own standard-sized copies. During Friday khutbahs or Islamic lectures, speakers can reference the book more easily when it is placed on the mimbar or lectern. For elderly readers at home, the larger text reduces fatigue during extended reading sessions and allows them to continue their study of the Prophet's life without depending on others for assistance. The binding of the big edition is reinforced to handle the additional weight and size of the larger pages, using a sturdy spine construction and durable cover materials. The paper quality is selected for opacity and durability at the larger format. This edition is a popular choice for mosque libraries, Islamic school classrooms, madrasah teacher reference collections, and home libraries where multiple family members, including elderly members, regularly read and study seerah together.`,
    metaDescription: "Ar Raheeq Al Makhtum Urdu Big is the large-format edition with enlarged text. Ideal for elderly readers, teachers, imams, and classroom seerah study."
  },
  {
    slug: "ar-raheeq-al-makhtum-10x15",
    description: `Ar-Raheeq Al-Makhtum 10x15 is a specific format edition of the renowned biography of Prophet Muhammad (peace be upon him) produced in the 10x15 inch page size. This medium-to-large format occupies a practical middle ground between standard book sizes and oversized reference editions, offering enhanced readability compared to smaller formats while remaining manageable enough for regular handling and reading. The 10x15 designation makes it easy for buyers to identify this specific size variant, which is important for institutional purchasers and individuals who have a preferred format for their reference books.

The content of this 10x15 edition is the complete and unabridged Ar-Raheeq Al-Makhtum by Safiur Rahman Mubarakpuri, the award-winning seerah that has become the standard biography of the Prophet in Islamic educational institutions worldwide. The book systematically covers the Prophet's life from pre-Islamic Arabia and the lineage of the Hashimi family through every major phase of his prophetic mission. The chronological organization, thorough referencing of hadith sources, and the author's practice of distinguishing between authentic and weak narrations make this work a reliable scholarly resource. The 10x15 format is well-suited to this type of reference material, as the larger page size allows for comfortable text formatting with adequate margins, clear paragraph separation, and well-organized chapter headings that facilitate quick navigation to specific topics.

The 10x15 format is commonly preferred by Islamic institutions including madrasahs, darul ulooms, and Islamic universities where this book serves as a core textbook for seerah courses. The larger page size makes it practical for teachers to hold up and reference during classroom instruction, and the enhanced readability reduces eye strain during the extended study sessions that seerah coursework typically requires. The physical production includes quality paper, durable binding appropriate for the page size, and a cover design that reflects the scholarly importance of the text. Individual buyers who prefer a more spacious reading format also gravitate toward the 10x15 edition for their personal libraries. This edition maintains the same high scholarly standards as all other format variants of Ar-Raheeq Al-Makhtum, making it a dependable choice for anyone seeking an authoritative and well-produced biography of the Prophet in a medium-large format.`,
    metaDescription: "Ar-Raheeq Al-Makhtum 10x15 is a medium-large format of the award-winning Prophet's biography. Enhanced readability for students and institutional use."
  },
  {
    slug: "arabic-learn-the-easy-way",
    description: `Arabic Learn the Easy Way is an instructional book designed to teach Arabic language fundamentals to Urdu-speaking students through a simplified and accessible methodology. The book addresses one of the most common challenges faced by non-Arab Muslims: learning enough Arabic to understand Quranic text, perform daily prayers with comprehension, and engage with basic Islamic literature in its original language. By leveraging the shared vocabulary and grammatical structures between Urdu and Arabic, this book aims to make the learning process more intuitive and efficient than traditional Arabic language textbooks.

The book is structured as a progressive course that begins with the Arabic alphabet, vowel marks (harakat), and basic letter recognition, then advances through word formation, sentence construction, basic grammar rules, and vocabulary building. Each lesson introduces new concepts in small, manageable increments, reinforcing previous material through exercises and practice activities. The teaching methodology emphasizes pattern recognition and memorization of common word forms, which are approaches that work well for Urdu-speaking students who are already familiar with the Perso-Arabic script. The book includes vocabulary lists organized by common themes, verb conjugation tables, grammar rule summaries, and practice exercises that test reading comprehension and basic writing skills.

The physical book is produced in a standard educational format with clear typesetting for both the Arabic examples and the Urdu instructional text. The layout is designed to be student-friendly, with sufficient spacing between lines, clearly distinguished sections for new material versus review exercises, and a clean visual hierarchy that guides the reader through each lesson. The binding is designed to lay relatively flat when opened, which is important for a workbook-style text that students will write in or reference frequently. This book is widely used in madrasahs, Islamic schools, home-schooling environments, and self-study programs where Urdu-speaking Muslims want to develop a functional understanding of Arabic. It is particularly valued for its practical focus on the vocabulary and structures most relevant to Quranic understanding and daily Islamic practice, rather than attempting to teach a broad academic Arabic curriculum that may not align with the immediate needs of most Muslim learners.`,
    metaDescription: "Arabic Learn the Easy Way teaches Arabic to Urdu speakers through a simplified method. Progressive lessons on alphabet, grammar, and Quranic vocabulary."
  },
  {
    slug: "arkan-e-islam-o-imaan-new-edition",
    description: `Arkan-e-Islam-o-Imaan (New Edition) is an updated and revised Urdu-language book that provides a detailed explanation of the pillars of Islam (Arkan-e-Islam) and the pillars of faith (Arkan-e-Imaan). The title directly identifies its subject matter: the five pillars of Islam (Shahadah, Salah, Zakat, Sawm, and Hajj) and the six articles of faith (belief in Allah, His angels, His books, His messengers, the Day of Judgment, and divine predestination). The "New Edition" designation indicates that this version has been revised, updated, and potentially expanded compared to earlier printings, incorporating clarifications, additional references, and improvements based on reader and scholar feedback.

For each pillar of Islam, the book provides a thorough explanation that covers the religious basis (daleel) from the Quran and Sunnah, the detailed conditions and requirements for proper fulfillment, common errors and misconceptions, and practical guidance for performing each obligation correctly. The section on Salah (prayer), for example, would cover the prerequisites of wudu and cleanliness, the times and rakat of each prayer, the proper postures and recitations, and the factors that invalidate the prayer. Similarly, the section on Hajj would detail each step of the pilgrimage rites, the obligations of the pilgrim, and the common mistakes that people make during the journey.

The pillars of faith (Imaan) section explores each article of belief with theological depth appropriate for a general Urdu readership. The discussion of Allah's attributes, the nature of angels, the contents of revealed books, the characteristics of prophets, the realities of the Hereafter, and the concept of qadr are all addressed using Quranic evidence and sound hadith references. The Urdu prose is scholarly yet accessible, making complex theological concepts understandable to readers without advanced formal training in Islamic studies. The new edition's physical production features updated typesetting, improved layout, and quality binding. It is commonly used in madrasah curricula, Islamic school textbooks, study circle materials, and home libraries where families want a reliable reference on the fundamentals of Islamic belief and practice.`,
    metaDescription: "Arkan-e-Islam-o-Imaan New Edition explains the five pillars of Islam and six articles of faith. Revised Urdu reference with Quranic and hadith evidence."
  },
  {
    slug: "as-shukar-gratitude",
    description: `As Shukar Gratitude is an Islamic book that explores the concept of gratitude (shukar) as a central theme in Islamic teachings. The book examines how gratitude toward Allah operates as both an act of worship and a means of spiritual elevation, drawing upon Quranic verses, prophetic hadith, and the insights of classical Islamic scholars to present a comprehensive treatment of this essential Islamic virtue. The bilingual or thematic title suggests the book addresses gratitude from multiple angles, making it relevant to readers seeking to strengthen their relationship with Allah through thankfulness.

The content systematically covers what gratitude means in the Islamic context — distinguishing it from mere verbal expression of thanks to encompass a holistic state of the heart, tongue, and limbs. The book explores how gratitude is mentioned in the Quran as a quality of the righteous and a distinguishing characteristic of the believers, citing specific verses that command gratitude, describe its rewards, and warn against its opposite, ingratitude (kufr). Relevant hadith from Prophet Muhammad (peace be upon him) are presented throughout, including narrations about the Prophet's own gratitude in times of ease and hardship, his guidance on expressing thanks to Allah, and his warnings about the consequences of ungratefulness. The author likely also incorporates the writings and reflections of early Islamic scholars such as Imam al-Ghazali, Ibn al-Qayyim, and others who wrote extensively on spiritual matters.

The book provides practical guidance on how to cultivate gratitude in daily life, covering topics such as recognizing Allah's blessings in health, family, sustenance, safety, and faith; expressing gratitude through worship, charity, and good character; maintaining gratitude during trials and difficulties; and overcoming the spiritual diseases of complaining, dissatisfaction, and envy that undermine a grateful heart. The physical production follows standard book publishing conventions with clear typesetting, quality paper, and durable binding. This book is suitable for individual reading and reflection, for use in Islamic study circles and halaqah programs, as supplementary reading in madrasah courses on Islamic spirituality and ethics, and as a thoughtful gift for Muslims seeking to enhance their spiritual practice through the cultivation of gratitude toward their Creator.`,
    metaDescription: "As Shukar Gratitude explores thankfulness through Quranic verses, hadith, and scholarly insights. Practical guidance for cultivating gratitude daily."
  },
  {
    slug: "asaan-tarjuma-quran-e-kareem",
    description: `Asaan Tarjuma Quran e Kareem is an Urdu translation of the Holy Quran specifically designed for ease of understanding. The title includes the phrase "aam fahm aur aasan" (commonly understood and easy), which explicitly states the book's core objective: to present the meaning of the Quran in Urdu that is simple enough for any reader to comprehend, regardless of their level of education or familiarity with classical Arabic or formal Urdu literature. This edition addresses a significant need in the Urdu-speaking Muslim community, where many people recite the Quran regularly but do not fully understand the meaning of what they are reciting.

The translation methodology employed in this edition prioritizes clarity and accessibility over the linguistic complexity of classical Urdu translations. Each verse is rendered in straightforward, contemporary Urdu that captures the essential meaning without requiring the reader to consult dictionaries or tafsir commentaries. Difficult concepts and archaic expressions are avoided in favor of vocabulary and sentence structures that are commonly used in everyday Urdu. The translation aims to convey what each verse means in its immediate context, allowing readers to follow the flow of the Quranic message as they read through each surah. This approach makes the Quran accessible to a broader audience including young students, new Muslims learning Urdu, elderly readers, and individuals who never received formal Islamic education but want to understand Allah's word.

The physical book typically follows the standard Quran format with the Arabic text on each page alongside or above the Urdu translation. The typesetting is designed to clearly distinguish between the Arabic original and the Urdu translation, making it easy for readers to refer between the two. The paper quality and printing ensure legibility of both scripts. The binding is designed for durability given that this is a book many readers will use daily for recitation with understanding. This translation is widely used in homes, mosques, madrasahs for introductory Quran understanding courses, and in dawah contexts where new Muslims or less-educated community members need an accessible Quran translation. Its popularity stems from the genuine need it fulfills: making the message of the Quran understandable to every Urdu-speaking Muslim, regardless of their educational background.`,
    metaDescription: "Asaan Tarjuma Quran e Kareem offers an easy Urdu translation for understanding. Contemporary Urdu making Quran accessible to all readers."
  },
  {
    slug: "asaan-tarjuma-quran-mufti-taqi-usmani",
    description: `Asaan Tarjuma Quran Mufti Taqi Usmani is the simplified Urdu translation of the Holy Quran prepared by one of the most respected contemporary Islamic scholars, Mufti Muhammad Taqi Usmani. This translation is a companion or simplified version derived from Mufti Taqi Usmani's more detailed and scholarly Urdu translation and tafsir work. The "asaan" (easy) designation indicates that this edition has been specifically prepared to make the Quranic message accessible to ordinary readers who may not have the background to engage with complex scholarly translations.

Mufti Taqi Usmani is recognized globally as an authority on Islamic jurisprudence, Quranic sciences, and hadith. His expertise lends this simplified translation a credibility and reliability that set it apart from other easy translations by lesser-known authors. Even in its simplified form, this translation maintains strict adherence to the principles of accurate Quranic rendering — avoiding interpretations that contradict established tafsir methodology, refraining from commentary that is speculative, and ensuring that the Urdu text faithfully conveys the meaning established by classical mufassirun (Quranic exegetes). The simplification is achieved through using clear, modern Urdu vocabulary and sentence structures rather than by altering the underlying meaning or taking interpretive liberties.

The translation is formatted in the standard bilingual Quran layout, with the Arabic text prominently displayed and the Urdu translation positioned for easy cross-reference on each page. The typesetting is clean and well-organized, with clear visual distinction between the Arabic original and the Urdu rendering. The physical production uses quality paper and durable binding suitable for a book that will be read daily by many users. This edition is particularly popular among Pakistani and South Asian Muslim communities who hold Mufti Taqi Usmani in high regard and who want a translation they can trust implicitly. It is widely used in homes for daily recitation with understanding, in mosques and Islamic centers, in madrasahs for courses on Quran comprehension, and as a preferred translation for dawah and educational programs. The Mufti Taqi Usmani name on the cover provides assurance of scholarly rigor even in this simplified format, making it a first choice for many Urdu-speaking Muslims seeking a reliable and easy-to-understand Quran translation.`,
    metaDescription: "Asaan Tarjuma Quran by Mufti Taqi Usmani is a simplified Urdu Quran translation. A trusted easy-to-understand rendering by a leading Islamic scholar."
  },
  {
    slug: "ashab-e-badr",
    description: `Ashab-e-Badr is an Urdu-language book that provides detailed biographical accounts of the participants in the Battle of Badr, the first major military engagement fought by the Muslim community under the leadership of Prophet Muhammad (peace be upon him) in the year 2 AH (624 CE). The Battle of Badr holds a position of unparalleled significance in Islamic history, and the Muslims who participated in it — numbering 313 against a much larger Makkan army — are regarded as some of the most distinguished companions of the Prophet. This book documents their lives, backgrounds, and contributions to Islam before, during, and after this pivotal battle.

The book presents individual or grouped biographical sketches of the Sahabah (companions) who fought at Badr, including both the Muhajirun (emigrants from Makkah) and the Ansar (helpers from Madinah). For each companion, the book covers their pre-Islamic background, their conversion to Islam, the hardships they endured, their role in the Battle of Badr specifically, and their subsequent contributions to the Muslim community. The accounts draw upon authenticated hadith sources, classical works of seerah and tabaqat (biographical dictionaries), and the historical records preserved by early Muslim scholars. The book also provides context about the battle itself — the circumstances that led to it, the strategic situation, the course of the fighting, and its aftermath and significance.

The participants of Badr hold a special status in Islam, and the Prophet specifically mentioned them with honor. Understanding who these individuals were, what they sacrificed, and how they conducted themselves provides Muslims with inspirational role models and a deeper appreciation of the early history of Islam. The book serves as both a historical reference and a source of spiritual inspiration. The Urdu text is written in an engaging narrative style that makes these historical accounts vivid and memorable. The physical production includes clear typesetting, quality paper, and durable binding suitable for a reference book. Ashab-e-Badr is commonly used in madrasah seerah courses, Islamic study circles, and by individual readers who want to learn about the remarkable men and women who stood with the Prophet at Islam's most critical hour.`,
    metaDescription: "Ashab-e-Badr is an Urdu book documenting the 313 companions who fought at Badr. Biographical accounts and historical context of the pivotal battle."
  },
  {
    slug: "ashra-mubashra-ki-zindagiyon-ke-sunehre-waqiaat",
    description: `Ashra Mubashra ki Zindagiyon ke Sunehre Waqiaat is an Urdu book that presents the golden events and stories from the lives of the Ashra Mubashra — the ten companions of Prophet Muhammad (peace be upon him) who were given the glad tidings of Paradise during their lifetimes. The title translates roughly to "Golden Events from the Lives of the Ten Promised Paradise." The Ashra Mubashra include Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, Ali ibn Abi Talib, Talhah, Zubayr, Abdur Rahman ibn Awf, Sad ibn Abi Waqqas, Said ibn Zayd, and Abu Ubaidah ibn al-Jarrah, may Allah be pleased with them all.

The book focuses on presenting inspiring and instructive incidents (waqiaat) from the lives of each of these ten companions rather than offering comprehensive biographies. The "sunehre" (golden) descriptor in the title reflects the author's intent to highlight the most memorable, morally significant, and spiritually uplifting episodes that demonstrate the exceptional character, faith, sacrifices, and virtues of these companions. Each story is selected to illustrate specific Islamic values — the unwavering faith of Abu Bakr, the justice of Umar, the generosity of Uthman, the courage of Ali, and the distinctive qualities of each of the remaining companions. The events range from their early conversions to Islam and the sacrifices they made, to incidents during the Prophet's lifetime that showcase their character, to events after the Prophet's passing that demonstrate their continued commitment to Islam.

The narrative style is engaging and accessible, making these historical accounts vivid and relatable to contemporary Urdu readers. The author has drawn upon authentic sources including hadith collections, seerah literature, and the classical tabaqat works to ensure accuracy. The book is organized by companion, with each section covering the most significant stories associated with that individual. The physical production uses clear Urdu typesetting on quality paper with a durable binding. This book is popular for family reading, madrasah supplementary reading, Islamic study circles, and individual spiritual enrichment. Learning about the lives of the Ashra Mubashra provides Muslims with concrete examples of how the Prophet's companions translated Islamic teachings into lived reality, offering timeless lessons in faith, character, and devotion.`,
    metaDescription: "Ashra Mubashra ki Zindagiyon ke Sunehre Waqiaat presents golden stories from the ten companions promised Paradise. Inspiring Urdu narratives of faith."
  },
  {
    slug: "ashra-zil-hajja-eid-ul-adha-aur-qurbani",
    description: `Ashra Zil Hajja - Eid ul Adha aur Qurbani is a comprehensive Urdu guidebook that covers the first ten days of Dhul Hijjah, the festival of Eid ul Adha, and the rituals and rulings related to qurbani (animal sacrifice). These three interconnected topics form one of the most significant periods in the Islamic calendar, and this book provides detailed practical and religious guidance for Muslims who want to observe these occasions correctly and earn maximum spiritual reward.

The section on Ashra Zil Hijja (the first ten days of Dhul Hijjah) explains why these days are considered among the most blessed in the Islamic year. The book cites the hadith in which the Prophet Muhammad (peace be upon him) stated that no good deeds performed in these ten days are more beloved to Allah than those performed at any other time. The author outlines the specific virtues of these days, the recommended acts of worship (fasting, dhikr, dua, charity, and recitation of the Quran), and provides a practical day-by-day guide for making the most of this spiritual opportunity. The significance of the Day of Arafah, which falls on the 9th of Dhul Hijjah, is given particular attention with detailed guidance on fasting, supplication, and the spiritual benefits of this day.

The section on Eid ul Adha covers the rulings related to the Eid prayer including its timing, the method of performance, the khutbah (sermon), and the sunnah acts associated with the day. The qurbani section provides comprehensive guidance on the obligation and recommendations of animal sacrifice, including the conditions that make qurbani obligatory versus recommended, the types of animals that can be sacrificed, the minimum age and quality requirements for the animal, the proper method of slaughtering according to Islamic guidelines, the distribution of meat, and common questions and misunderstandings about qurbani. The book addresses both the Hanafi perspective and other schools of thought where relevant. The physical production uses clear Urdu typesetting with organized sections, making it easy to find specific rulings. This book is an essential reference for Muslim households during the Dhul Hijjah season, and is widely consulted by families, imams, and Islamic organizations in Pakistan and Urdu-speaking communities.`,
    metaDescription: "Ashra Zil Hajja Eid ul Adha aur Qurbani is a comprehensive Urdu guide to the blessed ten days of Dhul Hijjah, Eid prayers, and qurbani rituals and rulings."
  },
  {
    slug: "asmad-surma-large",
    description: `Asmad Surma (Large) is a generously sized container of traditional Islamic surma (kohl or kajal) used for applying to the eyes. Surma has been a part of Islamic and South Asian cultural tradition for centuries, valued both for its cosmetic purpose of enhancing eye appearance and for the perceived health benefits associated with natural eye care. The "Asmad" brand name identifies this particular product line, and the "Large" designation indicates that this container holds a greater quantity of surma compared to standard-sized packages, making it a longer-lasting and more economical choice for regular users.

The surma contained in this large pack is typically made from a traditional formulation that uses natural mineral-based ingredients. Traditional surma preparations often include substances such as antimony sulfide (ithmid), galena, or other naturally occurring minerals that have been used for eye application across many cultures throughout history. The formulation follows traditional methods of preparation that have been passed down through generations, with the mineral ingredients ground to an extremely fine powder consistency that allows smooth, even application along the inner rim of the eyelids. The fine texture ensures that the surma adheres well and provides a dark, defined line that frames the eyes.

The large container is designed for practical daily use and extended storage. The packaging typically features a sturdy jar or tube with a secure closure that prevents the fine surma powder from spilling or being exposed to moisture and contaminants. The container size provides enough product for weeks or months of regular use, depending on the frequency of application. Many users apply surma as part of their daily grooming routine, following the sunnah practice of the Prophet Muhammad (peace be upon him) who used to apply surma (kohl) to his eyes. Some users also believe that natural surma provides protective benefits for eye health, including strengthening the eyelashes, soothing the eyes, and providing relief from eye strain and irritation caused by dust and screen exposure. This large pack is a practical choice for families, regular users, and those who want to stock up on a quality surma product. It is also commonly purchased during Ramadan and Eid seasons as a gift item or for personal use during special occasions.`,
    metaDescription: "Asmad Surma Large is a generously sized traditional kohl for eye application. Natural mineral formulation following the sunnah, ideal for regular users."
  }
];

async function main() {
  let count = 0;
  let fails = [];
  for (const item of updates) {
    try {
      await prisma.product.update({
        where: { slug: item.slug },
        data: {
          description: item.description,
          metaDescription: item.metaDescription
        }
      });
      count++;
      console.log('OK:', item.slug);
    } catch (e) {
      console.log('SKIP:', item.slug, e.message.substring(0, 80));
      fails.push(item.slug);
    }
  }
  console.log(`\nUpdated: ${count}/${updates.length}`);
  if (fails.length) console.log('Failed:', fails.join(', '));
}

main().then(() => prisma.$disconnect()).catch(e => { console.error(e); prisma.$disconnect(); });
