const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "muhammad-nasir-udin-albaani",
    description: `Sheikh Muhammad Nasir ud-Din al-Albani (1914–1999) stands as one of the most influential hadith scholars of the twentieth century, whose impact on contemporary Islamic scholarship continues to shape how Muslims approach the verification and application of Prophetic traditions. This biography traces the remarkable journey of a man who, without formal institutional training in the traditional Islamic seminary system, rose to become the foremost hadith specialist of his generation through sheer dedication, rigorous methodology, and an encyclopedic command of the hadith corpus.

The book begins with al-Albani's early life in Damascus, where his father's work as a watchmaker provided the family with a modest living while instilling in young Muhammad a strong work ethic and love for knowledge. His initial encounters with Islamic texts came through independent reading and study, and it was his偶然 discovery of a printed edition of a hadith collection that ignited the passion that would define his life's work. Without access to the chain of scholars that traditionally transmitted hadith knowledge, al-Albani developed his expertise through direct engagement with the manuscript sources—the original books of hadith, the biographical dictionaries of narrators, and the methodological treatises of classical hadith scholars.

The biography chronicles al-Albani's methodological contributions in detail, explaining how he applied the classical principles of hadith criticism—developed by scholars like Imam Ahmad, al-Bukhari, Muslim, Ibn Hajar, and al-Dhahabi—to the evaluation of contemporary hadith collections. His work on grading the narrations in collections that had not been systematically evaluated, such as Sunan al-Tirmidhi, Sunan Abu Dawud, and al-Mundhiri's Mukhtasar Sahih Muslim, represented a massive scholarly undertaking that filled a significant gap in hadith scholarship. The book discusses both the widespread appreciation for al-Albani's meticulous work and the scholarly debates that some of his rulings generated.

The later sections cover al-Albani's professorship at the Islamic University of Madinah, his move to Jordan, and his prolific output of scholarly works that number in the dozens. His views on matters of fiqh, aqidah, and methodology are discussed with attention to how they influenced broader Islamic movements and scholarship. The biography provides a balanced portrait, acknowledging both his towering contributions and the controversies that accompanied his career, offering readers a nuanced understanding of a scholar whose legacy continues to provoke discussion in Islamic academic circles.`,
    metaDescription: "Biography of hadith scholar Sheikh al-Albani tracing his self-directed scholarly journey, methodological contributions, and lasting influence on Islam."
  },
  {
    slug: "muhammad-peace-be-upon-him-the-greatest",
    description: `Assessments of historical greatness typically measure individuals against the achievements of their contemporaries or against the specific domain in which they operated. When the life of Prophet Muhammad (peace be upon him) is examined through multiple dimensions of greatness—moral, intellectual, political, social, and spiritual—the cumulative case for his unique status in human history becomes compelling. This book constructs a multi-faceted argument for the Prophet's greatness by examining evidence from Islamic sources, historical analysis, and the testimony of non-Muslim scholars and thinkers who have studied his life.

The moral dimension receives extensive treatment. The book presents the Prophet's ethical standards—his honesty, which earned him the title Al-Amin even among his opponents before his prophethood; his forgiveness of those who persecuted and tried to kill him; his consistent treatment of the weak, the poor, and the marginalized; and his refusal to retaliate against personal insults—as evidence of a moral character that has few parallels in recorded history. Specific incidents, documented in authenticated hadith and early Islamic histories, are cited to illustrate each quality rather than relying on vague generalizations.

The intellectual and legislative dimension highlights the Prophet's role in transforming a society marked by tribal warfare, female infanticide, and unchecked exploitation into one governed by a comprehensive legal and ethical framework. The Quranic legislation delivered through him addressed everything from property rights and inheritance to international relations and environmental ethics, accomplishing in twenty-three years what most legal systems require centuries to develop. The book argues that this legislative productivity, combined with the internal coherence of the legal framework, points to a source of guidance beyond human capacity.

The political and social dimension examines the Prophet's success as a state-builder. From a persecuted minority in Makka to the leader of a unified, multi-tribal state in Madinah, his political career demonstrated strategic acumen, diplomatic skill, and the ability to forge unity among previously warring factions. The book presents this transformation as one of the most remarkable political achievements in history, accomplished without the military, financial, or institutional advantages that typically accompany such transformations. Non-Muslim historians and philosophers who have acknowledged the Prophet's greatness—including figures from Michael Hart to Thomas Carlyle—are quoted, providing external validation for the book's central thesis.`,
    metaDescription: "Analysis of Prophet Muhammad's greatness examining moral character, legislative achievements, and political leadership with scholarly testimony."
  },
  {
    slug: "muhammad-sabar-o-shukar-ky-paykary-azam",
    description: `Sabar aur shukar—patience and gratitude—dono husn-e-akhliaq ke aise raaste hain jin se Nabi Karim Sallallahu Alaihi Wasallam ke jazbe ko samajhne ka waasta milta hai. Yeh Urdu kitaab in dono azeem sifaton ko Nabi Pak ki zindagi ke maqamat se jod kar bayan karti hai taake parhne walon ko yeh samajh aaye ke kis tarah unke sabar ne mushkilon ko aasan banaya aur unka shukar ne barkat ka zariya bana diya.

Sabar ke bab mein kitaab ne Makki daur ke musibaton ko tafseeli tor par bayan kiya hai. Quraish ki ladai, Taif ka waqia, shaheed hone walay sahba khabron ka aana, aur hijrat ki musibat—in tamaam waqiat mein Nabi Karim ka sabar aik misaal hai jo parhne walon ke dil ko hilata hai. Lekin yeh sabar majboori ka nahi tha—yeh aik aisi halat-e-dil thi jismein azaab aur aalaa se aankhen nahi pharti thi aur kisi bhi haal mein Allah ki razamandi qabool ki jati thi. Kitaab ne faisla karne wale waqt ke sabar ko bhi ahemiyat di hai jahan Nabi Pak ne Hudaibiya ka sulah qabool kiya jab kuch sahba is se naraz the—in waqiay ne sabar ke ehkaam ko aik naya aur amali pahlu diya.

Shukar ke hisse mein kitaab ne bataya hai ke Nabi Karim Sallallahu Alaihi Wasallam itna zyada shukar guzar the ke unke pair zameen par nishar nahi hote the. Choti cheezon par bhi unka shukar ada karna—ek katora pani pilne par, thandi hawa ka jhonka milne par, bachon ko dekh kar khushi ka izhar karne par—yeh tamam kitaab mein ahem waqiat ke tor par bayan kiye gaye hain. Kitaab ne yeh bhi samjhaya hai ke unka shukar sirf zuban ka nahi tha balke dil ka, jism ka, aur amal ka shukar tha jo unki zindagi ke har lamhe mein zahir hota tha.

Dono sifaton ka taluq musalman ki aam zindagi se zabardasti jod kar kitaab ne yeh nateeja nikala hai ke sabar aur shukar musalman ke liye sirf akhlaqi sifat nahi hain balke zindagi ke har mushkil waqt ka hal hain. Kitaab ke aakhir mein amali mashwariye di gaye hain jo parhne wale apni zindagi mein istemal kar sakte hain aur is tarah Nabi Karim ke in paykar-e-azam sifaton ko apne character ka hissa bana sakte hain.`,
    metaDescription: "Urdu book on Prophet Muhammad's exemplary patience and gratitude with detailed accounts of Makkan hardships, Hudaybiyyah, and daily expressions of thanks."
  },
  {
    slug: "muhammad-saw-kay-shab-o-roz-kay-masnoon-amaal",
    description: `Nabi Pak Muhammad Sallallahu Alaihi Wasallam ki zindagi ka har pal hedayat ka zariya hai aur unka dainik rutina musalman ke liye ek behtareen nuskha hai. Yeh Urdu kitaab un tamam masnoon amalon ko mukammal tafseeli bayan ke sath samaghne ka kaam karti hai jo Nabi Pak ne apne shab-o-roz ki ghuzisht mein kiye. Kitaab ka maqsad yeh hai ke musalman apni daini zindagi ko Nabi Pak ke amali nuskhe ke mutabiq banayein aur is tarah unki barakat se mustafaid ho sakein.

Subah utne ke waqt se lekar raat ko sone tak tamam waqt ke masnoon amaal tafseeli tor par bayan kiye gaye hain. Subah utne ke baad miswak karna, hath dhone ka tarika, wuzu ka masnoon tariqa, aur subah ki namaz ke baad ki azkar—yeh tamam aise amaal hain jo rozana ki zindagi ka hissa ban sakte hain aur un par amal karne se rozaana ki barkat mein izafa hota hai. Kitaab ne har amal ke liye hadith ka Hawala bhi diya hai taake parhne wale ko yaqeen ho jaye ke yeh amal Mustanad hain.

Dainik namazon ke baad ki azkar, nashte ke waqt ki sunnat, khanay ka masnoon tariqa, ghar se nikalne aur ghar mein dakhil hone ki duaein, bazaar jaane ka tariqa, aur mulaqat ka adab—yeh tamam amaal aise hain jo musalman rozana karta hai lekin aksar unhe masnoon tariqay se nahi karta. Kitaab ne in tamaam amalon ka sahih tariqa bataya hai aur un par amal karne ke fazeelat ka bhi zikr kiya hai.

Sham ki waqt ki ghuzisht ke masnoon amaal bhi bhi tafseeli tor par majood hain. Maghrib ke baad ki azkar, isha ki namaz ke baad ki duaein, raat ko sone se pehle ki masnoon amaal—jaise khaayali satar par pani chhirna, ayat-ul-kursi padhna, aur surah Mulk tilawat karna—yeh tamam kitaab mein majood hain. Kitaab ke akhir mein aik nisf marji hai jahan tamam amalon ke baray mein mukhtasar tafseel di gayi hai jo parhne walon ko yad rakhne mein madad deti hai. Yeh kitaab ghar mein rakh kar har roz parhne ke liye aik qeemti maujooda hai jo zindagi ko bilkul Nabi Pak ke nuskhe par bana deta hai.`,
    metaDescription: "Urdu guide to the Prophet's daily Sunnah acts from morning to night with hadith references, covering supplications, prayer, meals, and sleep etiquettes."
  },
  {
    slug: "muhammad-the-beloved-of-allah",
    description: `The love that Islam accords to Prophet Muhammad (peace be upon him) occupies a unique position in the faith's theological framework. It is not merely an emotional attachment but a required component of belief—hadith literature records the Prophet stating that none among his followers truly believes until he is dearer to them than their own parents, children, and all of humanity. Muhammad: The Beloved of Allah examines the theological, historical, and spiritual dimensions of this profound love, providing readers with a comprehensive understanding of why the Prophet holds this elevated status and how Muslims are meant to express it.

The book begins by establishing the theological basis for the Prophet's beloved status. Quranic verses that address the Prophet directly—with terms of endearment, reminders of Allah's special favor upon him, and commands to the believers regarding their conduct toward him—are analyzed in depth. The verse addressing him as "a mercy to the worlds" and the verse requiring believers to send blessings upon him receive particular attention, with classical tafsir sources cited to illuminate the full meaning of these divine expressions of love and honor.

The historical dimension explores how the Prophet's beloved status manifested in the lives of those who knew him personally. The Companions' devotion to him was not abstract or theoretical—it expressed itself in their willingness to sacrifice their lives, wealth, and comfort for his cause, their anxiety to please him, and their grief when he was displeased. The book presents specific accounts from the lives of Abu Bakr, Umar, Ali, the Ansar, the women of the Muslim community, and even the children of Madinah, each illustrating a different facet of genuine love for the Prophet.

The book carefully distinguishes between the legitimate, Islamically sanctioned expression of love for the Prophet and practices that may be culturally rooted but fall outside the boundaries of Islamic teaching. This balanced approach ensures that readers can cultivate genuine love for the Prophet in a manner consistent with the Quran and Sunnah, without falling into either neglect or excess. For Muslims seeking to strengthen their connection to the Prophet and for non-Muslims curious about this central aspect of Islamic devotion, the book provides a thorough, well-sourced, and spiritually enriching treatment of the subject.`,
    metaDescription: "Comprehensive examination of the Prophet Muhammad's beloved status in Islam through Quranic analysis, Companion accounts, and balanced devotional theology."
  },
  {
    slug: "muhammad-the-leader-the-messenger",
    description: `Leadership and messengership define the two primary dimensions of Prophet Muhammad's (peace be upon him) mission, and understanding how these roles interacted and reinforced each other is essential for grasping the full significance of his historical achievement. Muhammad: The Leader, The Messenger examines the Prophet's career through this dual lens, showing how his divine commission as Allah's messenger shaped his approach to leadership, and how his leadership responsibilities provided the practical arena in which his prophetic mission was fulfilled.

The messenger dimension of the Prophet's role involved receiving, preserving, and transmitting divine revelation—the Quran—and demonstrating its application through his own conduct. The book analyzes how the Prophet fulfilled this role with absolute fidelity, never adding to or subtracting from the revelation, never compromising its message under pressure, and dedicating every moment of his twenty-three-year prophetic career to the task of conveying Allah's guidance to humanity. The challenges he faced as a messenger—ridicule, persecution, physical harm, betrayal, and warfare—are documented with reference to authenticated sources, showing how his response to each challenge was guided by divine instruction rather than personal preference.

The leadership dimension is examined through the specific contexts in which the Prophet exercised authority. His leadership of the Muslim community in Makka during the years of persecution demonstrated patient, strategic leadership under severe constraint. His leadership during the Madinan period—establishing a state, negotiating treaties, commanding armies, appointing governors, adjudicating disputes, and managing a diverse population of Muslims, Jews, and pagan Arabs—required a breadth of leadership skills that few historical figures have matched. The book analyzes specific leadership decisions and their outcomes, drawing lessons about strategic thinking, crisis management, team building, and organizational development.

The interaction between the two roles is the book's most original contribution. It shows how the Prophet's leadership was always subordinate to his messengership—he led not by personal ambition or political calculation but by divine mandate, and every leadership decision was ultimately a response to revelation or an extension of revealed principles. This subordination is what prevented his leadership from degenerating into tyranny and what gives his example enduring relevance for leaders in any field who seek to combine effectiveness with ethical integrity.`,
    metaDescription: "Dual analysis of Prophet Muhammad as divine messenger and leader, examining how revelation guided his governance, military, and community leadership roles."
  },
  {
    slug: "mukhtar-al-nahv-arabic-grammar",
    description: `Arabic grammar, the science of nahw, forms the backbone of Quranic interpretation, hadith understanding, and advanced Islamic scholarship. Mukhtar al-Nahv presents the essential rules of Arabic grammar in a structured, pedagogically sound format that serves students at multiple levels—from beginners encountering Arabic grammar for the first time to intermediate students consolidating their knowledge and advanced students seeking a concise reference work.

The book follows the traditional Arabic grammar curriculum, beginning with the classification of words into noun, verb, and particle—the three categories that underpin all subsequent grammatical analysis. It then progresses through the core concepts of nahw: the case system (raf, nasb, jarr, and jazm), the declension and parsing of nouns, the conjugation and parsing of verbs, the function of particles in sentence construction, and the rules governing subject-predicate agreement, adjective-noun agreement, and the various types of verbal sentences and nominal sentences. Each concept is explained with clear definitions, illustrative examples from both classical Arabic literature and the Quran, and practice exercises that test comprehension and application.

What distinguishes Mukhtar al-Nahv from other Arabic grammar textbooks is its balanced approach to detail. Some textbooks overwhelm students with exhaustive coverage of every minor rule and exception, while others simplify so drastically that students are unprepared for the complexity of actual Arabic texts. This book navigates between these extremes by covering all essential rules thoroughly while deferring rare exceptions and highly specialized constructions to advanced study. The result is a textbook that genuinely prepares students to engage with Arabic texts without requiring years of preliminary study.

The pedagogical features include chapter summaries that recapitulate the key rules covered, vocabulary lists of grammatical terms with their Arabic equivalents, and progressively challenging exercises that build from simple identification tasks to full sentence parsing and analysis. For students at Islamic seminaries, universities, and independent study programs, Mukhtar al-Nahv provides a reliable and efficient pathway to Arabic grammatical competence—the essential foundation upon which all further Islamic studies depend.`,
    metaDescription: "Arabic grammar textbook covering essential nahw rules with Quranic examples and exercises for beginner to intermediate level students."
  },
  {
    slug: "mukhtasar-bayan-ul-quran-by-dr-israr-ahmed",
    description: `Dr. Israr Ahmed's Bayan ul Quran stands as one of the most comprehensive Urdu tafsir works of the modern era, presenting a detailed verse-by-verse commentary that emphasizes the Quran's message of social justice, spiritual revival, and the establishment of divine governance. The Mukhtasar—or abridged—edition distills the essential content of this monumental work into a more accessible format, allowing readers to benefit from Dr. Israr Ahmed's distinctive exegetical approach without committing to the full multi-volume set.

Dr. Israr Ahmed's tafsir methodology is characterized by its emphasis on what he termed the "central theme" of the Quran: the declaration of Allah's lordship, the affirmation of prophethood, and the establishment of the system of divine sovereignty (nizam-e-rububiyyat). He argued that understanding each verse in light of this central theme reveals connections and meanings that might be missed by more atomistic approaches to Quranic interpretation. This abridged edition preserves this thematic emphasis while condensing the detailed discussions that characterize the full work.

The commentary pays particular attention to the social and political implications of Quranic teachings. Dr. Israr Ahmed was known for his conviction that the Quran's message is not limited to individual piety but extends to the transformation of social structures, economic systems, and political governance. Passages dealing with economic justice, the rights of the poor, the prohibition of usury, and the responsibilities of those in authority receive extensive commentary that connects the text to contemporary challenges facing Muslim societies.

The abridgment process has retained the most essential elements of each section's commentary while reducing repetitive material and secondary discussions. Key Quranic verses and their interpretations are preserved in full, with the abridgment focusing on streamlining rather than simplifying. Readers who find the complete Bayan ul Quran too voluminous for their needs will find that this mukhtasar edition delivers the core message and methodology in a format suited to regular reading and reference. For students of Dr. Israr Ahmed's thought, for study circles discussing contemporary Quranic interpretation, and for Urdu-speaking readers seeking a tafsir that connects classical scholarship with modern concerns, this abridged edition provides a valuable and accessible resource.`,
    metaDescription: "Abridged Urdu tafsir by Dr. Israr Ahmed distilling his thematic Quran commentary emphasizing social justice, divine governance, and spiritual revival."
  },
  {
    slug: "mukhtasar-riyad-us-saliheen-urdu",
    description: `Riyad us-Saliheen by Imam al-Nawawi ranks among the most widely read hadith collections in the Muslim world, valued for its practical focus on virtues, manners, and righteous conduct rather than purely legal rulings. This Urdu mukhtasar—or abridged—edition makes the essential content of this beloved collection accessible to readers who want the benefit of al-Nawawi's careful hadith selection without working through the complete unabridged text.

The abridgment process has focused on retaining the most impactful and frequently referenced narrations from each chapter while reducing the total number of entries. Chapters covering the pillars of Islam, the virtues of various good deeds, the etiquettes of eating, sleeping, dressing, and social interaction, and the descriptions of Paradise and Hell are all represented, with the most instructive and well-authenticated narrations given priority. The result is a concise yet comprehensive collection that captures the spiritual and practical essence of the original.

The Urdu translation and abridgment have been executed with attention to both accuracy and readability. The hadith text is presented in a clear Urdu rendering that preserves the meaning of the Arabic original, and the explanatory notes that accompany each hadith help readers understand the context and application of the narration. Where the original Riyad us-Saliheen includes commentary by al-Nawawi or later scholars, the most essential explanatory points have been retained.

This edition serves multiple audiences effectively. For Urdu-speaking families, it provides a household hadith reference that family members of varying levels of religious knowledge can consult and benefit from. For students at madrasahs and Islamic schools, it serves as a supplementary hadith text that complements more formal jurisprudential studies with practical Prophetic guidance. For individuals who perform daily or weekly reading of hadith as a spiritual practice, the abridged format supports consistent reading without the commitment required by the full collection. The compact size also makes it suitable for carrying during travel, enabling readers to maintain their hadith reading practice while away from home.`,
    metaDescription: "Abridged Urdu edition of Riyad us-Saliheen preserving essential hadith on virtues, manners, and worship in a concise, accessible format for daily reading."
  },
  {
    slug: "mukhtasar-sahih-al-bukhari-2-vols-imported",
    description: `Sahih al-Bukhari holds the preeminent position among hadith collections in Sunni Islam, and the task of creating an abridged version that preserves its scholarly value while reducing its considerable length requires exceptional editorial judgment. This imported two-volume mukhtasar of Sahih al-Bukhari presents a carefully curated selection of the most essential narrations from Imam al-Bukhari's masterwork, chosen for their significance in establishing Islamic beliefs, practices, and legal principles.

The abridgment follows the established chapter structure of Sahih al-Bukhari, maintaining the organizational framework that has made the original work a model of scholarly organization. Books on faith, knowledge, prayer, pilgrimage, charity, fasting, marriage, trade, and the virtues of the Companions are all represented, with narrations selected for their authenticity, clarity, and practical relevance. The editorial team has prioritized narrations that are most frequently cited by scholars in their legal reasoning, most commonly referenced in sermons and lectures, and most directly applicable to the daily religious practice of Muslims.

This imported edition distinguishes itself through its production quality. The printing, binding, and paper quality reflect the standards associated with imported Islamic publications, which typically feature clearer typography, more durable covers, and higher-quality paper than many locally produced editions. For readers who value the physical quality of their reference books, this imported edition offers a superior reading experience that supports years of regular use and reference.

The two-volume format divides the abridged text into manageable portions. The first volume typically covers the chapters on faith, purification, prayer, and funeral rites, while the second volume addresses pilgrimage, fasting, charity, marriage, commerce, and the remaining subjects. This division supports both sequential reading and topic-based reference. Scholars, students, and general readers who find the complete nine-volume Sahih al-Bukhari impractical for regular use will find that this abridged two-volume imported edition delivers the most essential content in a format that is both physically manageable and intellectually substantive. It serves as an excellent compromise between the comprehensive detail of the full collection and the brevity of single-volume summaries.`,
    metaDescription: "Imported two-volume abridged Sahih al-Bukhari with premium production quality and preserved chapter structure for scholarly reference."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
