const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "talbees-e-iblees",
    description: `Talbees-e-Iblees, meaning "The Deception of Iblees," is a significant Urdu work that examines the methods, strategies, and tactics employed by Satan in his relentless effort to lead human beings away from the straight path of Islam. The title is drawn from the Quranic concept of talbees, which refers to the act of disguising falsehood as truth or presenting evil in an attractive and deceptive wrapper. Iblees, the Arabic name for Satan, is portrayed in Islamic theology not merely as a tempter who whispers evil suggestions, but as a sophisticated strategist who adapts his approach to different individuals and circumstances, making his deceptions difficult to recognize and resist.

The book systematically categorizes the various forms of deception that Satan employs, drawing upon Quranic verses, authentic hadith, and the exegetical works of classical scholars to construct a comprehensive picture of the enemy's methods. The author discusses how Iblees exploits human weaknesses such as procrastination in good deeds, excessive hope in Allah's forgiveness, following desires under the guise of personal freedom, and the gradual escalation from minor sins to major ones. The book examines how Satan operates through false interpretations of religious texts, through the encouragement of innovation in religious practice, through sowing discord among Muslims, and through the promotion of moral relativism. Each category of deception is illustrated with concrete examples drawn from Islamic history and contemporary Muslim society.

One of the most valuable aspects of this work is its balanced approach to the topic. While thoroughly exposing Satan's methods, the book does not cultivate paranoia or despair but consistently directs the reader toward the Islamic means of protection and spiritual defense. The Quranic remedies for Satan's influence are discussed in detail, including seeking refuge in Allah, maintaining the five daily prayers, regular recitation of the Quran, fasting, supplication, and the company of righteous people. The author emphasizes that Satan's power is limited and that his deceptions can only succeed when a person neglects the spiritual protections that Islam provides. Written in clear and engaging Urdu that combines scholarly rigor with accessible prose, Talbees-e-Iblees serves as both a warning and a guide, equipping readers with the knowledge needed to recognize spiritual deception and the practical tools to defend against it. This book is valuable for Islamic studies students, teachers, imams who deliver Friday sermons, and all Muslims who wish to understand the nature of spiritual struggle in Islam.`,
    metaDescription: "Talbees-e-Iblees is a comprehensive Urdu book exposing Satan's deceptive strategies against Muslims, with Quranic remedies for spiritual protection."
  },
  {
    slug: "taleemat-quran-majeed",
    description: `Taleemat Quran Majeed, translating to "The Teachings of the Noble Quran," is a structured Urdu-language work that presents the major themes, commands, and guidance contained within the Holy Quran in an organized and accessible format. Rather than following the traditional verse-by-verse or surah-by-surah approach of conventional tafseer works, this book arranges the Quranic teachings according to topical categories, allowing readers to quickly locate all Quranic guidance related to a specific subject. This thematic organization makes it an invaluable reference tool for anyone who needs to understand what the Quran says about a particular topic without having to search through multiple volumes of tafseer.

The book covers an extensive range of subjects, including the fundamental articles of Islamic faith such as belief in Allah, His angels, His books, His messengers, the Day of Judgment, and divine predestination. Each topic is addressed by presenting the relevant Quranic verses with brief explanatory notes that contextualize the verses and explain their practical implications. The section on worship practices covers the Quranic foundations of prayer, fasting, charity, pilgrimage, and other acts of devotion. The moral and ethical teachings of the Quran are organized under headings such as honesty, patience, gratitude, humility, justice, kindness to parents, and the rights of neighbors. Social matters including marriage, family life, business transactions, inheritance, and governance are similarly treated with relevant Quranic citations and explanatory commentary.

The author's approach is characterized by a commitment to presenting the Quranic teachings directly, allowing the Quran to speak for itself to the greatest extent possible. The explanatory notes serve to connect related verses, clarify linguistic nuances, and provide historical context where necessary, but they avoid extensive philosophical speculation or sectarian interpretation. This approach makes the book suitable for a wide readership, regardless of their particular school of thought or level of religious education. The Urdu language used is clear and straightforward, accessible to educated readers without specialized training in Islamic studies while remaining precise enough to satisfy more scholarly readers. Taleemat Quran Majeed is particularly useful as a reference for Friday khutbah preparation, for Islamic school teachers who need to present Quranic teachings on specific topics, for da'wah workers who field questions about Islam, and for individual readers who want to develop a systematic understanding of what the Quran teaches across its full range of subjects.`,
    metaDescription: "Taleemat Quran Majeed is a topical Urdu reference organizing the Quran's teachings by subject, covering faith, worship, ethics, and social guidance."
  },
  {
    slug: "talha-in-the-mosque",
    description: `Talha in the Mosque is an English-language children's storybook that introduces young readers to the mosque environment and the etiquette of congregational prayer through the experiences of a relatable young character named Talha. The story follows Talha as he visits the mosque, either for the first time or in a context that allows the narrative to explore various aspects of mosque life and the proper behavior expected within the house of Allah. Through Talha's observations and interactions, children learn about the significance of the mosque in Islam, the proper way to enter and behave inside the mosque, and the spiritual atmosphere that pervades this sacred space.

The narrative is structured to naturally incorporate key lessons about mosque etiquette without feeling didactic or preachy. As Talha moves through the mosque, the story addresses practical matters such as removing shoes before entering, performing two rakah of tahiyyat al-masjid (greeting the prayer of the mosque), speaking softly and avoiding play that disturbs other worshippers, showing respect to the imam and elders, and the importance of arriving early for congregational prayer to earn the reward of the first rows. The book also introduces children to the physical features of a mosque, such as the mihrab, the minbar, the prayer mats, and the area for wudu, explaining the purpose and significance of each element.

The English prose is written at a level appropriate for young children, using simple sentences, a warm and friendly tone, and vocabulary that is accessible without being condescending. The storytelling approach allows children to absorb the lessons naturally by identifying with Talha and his experience, rather than feeling that they are being instructed directly. The book is suitable for reading aloud to younger children who are not yet independent readers, and the straightforward language makes it accessible to early readers as well. Parents and teachers who want to prepare children for their first visits to the mosque, reinforce good mosque behavior in children who already attend regularly, or simply introduce the concept of the mosque as a special place of worship will find this book to be a gentle and effective teaching tool. The story format makes the lessons memorable, and children are likely to recall Talha's example when they find themselves in similar situations in their own mosque experiences.`,
    metaDescription: "Talha in the Mosque is an English children's story teaching mosque etiquette and congregational prayer manners through a boy's first visit experience."
  },
  {
    slug: "talhah-bin-ubaidullah-ra-the-living-martyr",
    description: `Talhah Bin Ubaidullah (R.A): The Living Martyr is an English-language biography of one of the ten companions of the Prophet Muhammad who were given the glad tidings of Paradise during their lifetimes. The title "The Living Martyr" refers to a remarkable incident at the Battle of Uhud in which Talhah sustained numerous wounds while defending the Prophet Muhammad from attack, losing fingers and sustaining injuries so severe that the Prophet himself described him as one who had already earned his place in Paradise through his sacrifice. Yet Talhah survived those wounds and lived for many years afterward, earning the unique distinction of being called a martyr while still alive.

The biography traces Talhah's life from his youth in the Quraysh tribe of Makkah, through his early acceptance of Islam, which brought him persecution and hardship at the hands of his own community. The book details his migration to Madinah, his participation in the major battles of the early Islamic period, and his extensive contributions to the Muslim community both during the Prophet's lifetime and in the decades that followed. Talhah was known for his exceptional generosity, his business acumen, and his deep commitment to the welfare of the Muslim community, often using his considerable wealth to support the poor and fund military expeditions.

The author draws upon authentic historical sources including hadith collections, the major works of sirah (prophetic biography), and the biographical dictionaries of the early scholars to construct a detailed and reliable account of Talhah's life. The narrative covers not only his military exploits and acts of heroism but also his character traits, his family life, his relationships with other companions, and his role in the critical events that shaped the early Muslim community. The period following the death of the Prophet Muhammad, including Talhah's involvement in the events that led to the Battle of the Camel, is treated with scholarly objectivity and sensitivity, acknowledging the complexity of the historical situation without diminishing respect for any of the companions involved. This biography is written in clear English that makes the material accessible to general readers while maintaining academic rigor. It serves as a valuable resource for anyone interested in early Islamic history, the lives of the companions, and the practical lessons that can be drawn from their examples of faith, courage, and sacrifice.`,
    metaDescription: "An English biography of Talhah bin Ubaidullah (R.A.), the companion known as the Living Martyr, from early Islam through the Battle of Uhud."
  },
  {
    slug: "talimat-e-quran",
    description: `Talimat-e-Quran, meaning "Teachings of the Quran," is a distinct Urdu work on Quranic instruction that differs from similarly titled books through its emphasis on practical application and educational methodology. While many books present the Quran's teachings in a reference format, this work approaches the subject from a pedagogical perspective, asking not only what the Quran teaches but how those teachings can most effectively be communicated to and internalized by Muslims at different levels of education and engagement with the faith. The book addresses both the content of Quranic instruction and the methods by which that instruction should be delivered, making it a resource that serves both teachers and students.

The book's treatment of Quranic teachings is organized into progressive levels, beginning with the foundational concepts that every Muslim should know and advancing to more detailed and nuanced discussions suitable for advanced students. The introductory sections cover the basic pillars of faith, the essential obligations of worship, and the fundamental moral principles that the Quran establishes. These are presented with the relevant Quranic verses cited in Arabic along with their Urdu translations and concise explanatory notes. The intermediate sections explore more complex topics such as the Quranic approach to social justice, economic ethics, family law, and the responsibilities of leadership. The advanced sections address theological questions, the relationship between reason and revelation, and the Quranic worldview regarding the purpose of human existence.

What distinguishes this book from other works on Quranic teachings is its consistent attention to educational methodology. After presenting the content of each topic, the author discusses strategies for teaching that topic effectively, identifies common misunderstandings that students may develop, and suggests practical exercises and discussion questions that teachers can use to deepen understanding. The book also includes guidance on how to approach teaching the Quran to different age groups, how to address contemporary questions and challenges that students may raise, and how to create a learning environment that fosters genuine engagement with the Quranic text rather than superficial memorization of information. Written in well-structured Urdu that combines academic precision with practical clarity, Talimat-e-Quran is particularly valuable for madrasah teachers, Islamic school educators, Sunday school instructors, and parents who take an active role in their children's religious education. It can also serve as a self-study guide for motivated individual learners who want a systematic and practical understanding of the Quran's teachings.`,
    metaDescription: "Talimat-e-Quran is a pedagogical Urdu work presenting Quranic teachings at progressive levels with practical strategies for teachers and self-learners."
  },
  {
    slug: "tamheedi-qaidah-art-card",
    description: `Tamheedi Qaidah on art card stock is an introductory Quran reading primer designed for young children and beginning learners who are taking their first steps toward reading the Arabic script of the Holy Quran. The term "tamheedi" means introductory or preparatory, and this qaidah fulfills that role by systematically teaching the Arabic alphabet, the various forms of each letter, the vowel marks (harakat), the letter combinations (shaddah, tanween, and others), and the basic reading rules that form the foundation of Quranic literacy. The art card stock on which this edition is printed provides enhanced durability and a premium feel compared to standard paper editions, ensuring that the qaidah withstands the handling that young learners naturally subject their study materials to.

The pedagogical sequence of this qaidah follows the traditional method that has proven effective in madrasahs and homes across the Muslim world for generations, while incorporating some modern improvements in layout and visual design. The book begins with individual letters, teaching the name, shape, and pronunciation of each letter of the Arabic alphabet. It then progresses to the different positional forms of each letter (initial, medial, final, and isolated), which is essential because Arabic letters change shape depending on their position within a word. The vowel marks are introduced next, starting with fatha, kasra, and damma, followed by sukoon, tanween, and shaddah. Each new concept is introduced with clear examples and ample practice exercises that allow the learner to consolidate their understanding before moving to the next topic.

The art card paper used in this edition offers several practical advantages. Its thickness prevents pages from tearing easily, a common problem with standard paper qaidahs used by young children. The smooth, coated surface allows for clean erasure if a child practices writing on the pages with a pencil, and it resists the moisture damage that can occur from frequent handling. The printing quality is enhanced by the art card surface, with crisp letterforms and clear vowel marks that are easy for young eyes to distinguish. The color coding used to highlight different types of letters and vowel marks is rendered more vividly on the art card stock. This qaidah is ideally suited for use in formal classroom settings, where the durability of art card ensures that a single copy can serve multiple students over successive academic years, as well as for home use by parents who are teaching their children to read the Quran. Its systematic approach and durable construction make it a reliable foundation for the first critical stage of Quranic education.`,
    metaDescription: "Tamheedi Qaidah on durable art card stock teaches Arabic alphabet and Quran reading basics with clear letterforms and ample practice exercises."
  },
  {
    slug: "taqarab-ilallah",
    description: `Taqarab Ilallah, meaning "Drawing Near to Allah," is a spiritual work written to guide Muslims along the path of developing a closer, more intimate relationship with their Creator. The book addresses the fundamental human yearning for divine proximity, a yearning that Islam not only acknowledges but actively cultivates through its prescribed acts of worship, its ethical teachings, and its spiritual disciplines. The title itself encapsulates the book's central thesis: that nearness to Allah is not an abstract philosophical concept but an achievable reality that every Muslim can work toward through the means that Allah Himself has prescribed.

The book explores the various dimensions of drawing near to Allah, beginning with the foundational requirement of correct belief and sincere intention. The author discusses how the obligatory acts of worship, particularly the five daily prayers, fasting, charity, and pilgrimage, serve as the primary vehicles for drawing near to Allah when they are performed with genuine devotion and understanding. Beyond the obligatory acts, the book addresses the voluntary deeds that the Prophet Muhammad described as means to earn Allah's love, including the nawafil prayers, voluntary fasting, particularly on Mondays and Thursdays and during the middle three days of each lunar month, and consistent engagement in dhikr (remembrance of Allah).

The spiritual dimension of Taqarab Ilallah is its most distinctive feature. The author discusses the inner states that accompany genuine nearness to Allah, including humility, consciousness of Allah's presence (khushu), gratitude, patience in adversity, and contentment with Allah's decree. The book addresses the obstacles that prevent people from drawing near to Allah, such as excessive attachment to worldly matters, spiritual laziness, and the diseases of the heart including envy, pride, and ostentation. Each obstacle is discussed along with its remedy, drawn from the Quran and the prophetic tradition. The book may incorporate Arabic text, Urdu commentary, or a combination of both, depending on the specific edition. Its treatment of spiritual development is grounded in the methodology of the righteous predecessors, avoiding the excesses of both rigid legalism and uninhibited mysticism. This work is recommended for Muslims at all stages of spiritual development, from those who are just beginning to take their faith seriously to those who are already advanced in their practice and seeking deeper levels of connection with Allah.`,
    metaDescription: "Taqarab Ilallah guides Muslims toward divine proximity through worship, spiritual discipline, and purification of the heart based on Quran and Sunnah."
  },
  {
    slug: "taqdeer-kay-masail",
    description: `Taqdeer Kay Masail is a comprehensive Urdu-language work that addresses the complex and frequently misunderstood subject of divine predestination (taqdeer) in Islamic theology. The question of how human free will relates to Allah's absolute knowledge and power has been discussed by Muslim scholars since the earliest centuries of Islam, and this book provides a thorough, well-referenced treatment of the subject that is accessible to educated Urdu readers without specialized training in theology. The book is organized to address both the theoretical foundations of the Islamic understanding of taqdeer and the practical questions that arise in people's daily lives regarding destiny, fate, and human agency.

The book begins by establishing the conceptual framework within which the Islamic understanding of taqdeer must be understood. It discusses the key terms and concepts: qadar (divine decree), qadaa (divine execution), mashiyyah (divine will), and iradah (divine intention), explaining how these concepts relate to each other and how they collectively describe the Islamic understanding of the relationship between divine sovereignty and human responsibility. The author draws upon relevant Quranic verses and hadith to construct a coherent picture that affirms both Allah's complete control over all events and the genuine responsibility of human beings for their choices and actions. The middle path between the extremes of jabr (compulsion, which denies human free will) and qadar (absolute human autonomy, which limits divine power) is established through textual evidence and rational argumentation.

The practical sections of the book address the questions that Muslims most commonly ask about taqdeer. These include the relationship between taqdeer and supplication (if everything is already decreed, does dua change anything?), the role of taqdeer in illness and healing, the question of why evil and suffering exist if Allah is All-Powerful and All-Wise, the extent to which a person's destiny can be changed through good deeds, and how to maintain motivation for worship and self-improvement while believing in divine predestination. The book also addresses specific issues such as the relationship between taqdeer and marriage, career choices, and major life decisions. Each question is answered with reference to the relevant textual evidence and the opinions of classical scholars, presented in clear, reasoned Urdu prose. This book is valuable for anyone who has struggled with questions about fate and free will, for Islamic studies students who need a systematic treatment of the subject, and for teachers and imams who field questions about taqdeer from their communities.`,
    metaDescription: "Taqdeer Kay Masail is a thorough Urdu treatment of Islamic predestination addressing divine decree, free will, and suffering with scholarly evidence."
  },
  {
    slug: "taqwiyat-al-imaan-17x24-darsi",
    description: `Taqwiyat al Imaan in this 17x24 centimeter darsi (educational) edition is the foundational work of Shah Ismail Shaheed, one of the most influential reformist scholars of the Indian subcontinent, presented in a format specifically designed for classroom use in Islamic educational institutions. The 17x24 size is a standard textbook format in South Asian madrasahs and Islamic schools, providing a page area that accommodates both the Arabic text and its Urdu commentary while remaining manageable for students to handle in a classroom setting. The darsi designation indicates that this edition includes pedagogical features such as clear section headings, structured lesson divisions, and possibly study questions or explanatory notes that facilitate systematic classroom instruction.

Shah Ismail Shaheed composed Taqwiyat al Imaan in the early nineteenth century as a response to the widespread religious deviations he observed among the Muslims of his time. The book's title means "Strengthening of Faith," and its central purpose is to call Muslims back to the pure monotheistic creed of Islam as understood by the Prophet Muhammad and his companions, stripping away the innovations, superstitious practices, and shirk (associating partners with Allah) that had accumulated in popular religious practice over the centuries. The book addresses specific practices that the author identified as contravening the principle of tawheed, including seeking intercession from the dead, making vows to other than Allah, wearing amulets and charms for protection, and attributing supernatural knowledge or power to human beings.

The darsi edition presents this content in a format that supports structured classroom study. The text is divided into clearly marked lessons or chapters, each addressing a specific aspect of the creed and the corresponding deviations. The Arabic source material is presented alongside the Urdu translation and commentary in a layout that allows students to follow both texts simultaneously. The explanatory notes address vocabulary, grammatical constructions, and theological concepts that students might find challenging, and the lesson structure allows teachers to plan their instruction systematically. The 17x24 format provides adequate space for marginal notes, highlighting, and other annotations that students typically add during their studies. This edition is specifically recommended for madrasahs, Islamic seminaries, and Islamic schools that include the study of aqeedah (Islamic creed) in their curriculum, as well as for individual students who are studying Taqwiyat al Imaan as part of their formal Islamic education and benefit from the structured format.`,
    metaDescription: "A 17x24 cm educational edition of Shah Ismail Shaheed's Taqwiyat al Imaan, formatted for madrasah classroom study of Islamic creed and monotheism."
  },
  {
    slug: "taqwiyat-ul-imaan-14x21",
    description: `Taqwiyat-ul-Imaan in this 14x21 centimeter edition presents Shah Ismail Shaheed's influential work on Islamic creed in a compact, portable format that is suitable for personal reading, study circles, and general distribution. The 14x21 size is one of the most common book formats in Urdu publishing, offering a balance between readability and portability that makes it convenient for readers to carry the book with them and read it during commutes, breaks, or quiet moments throughout the day. This particular edition focuses on the core text and its essential commentary, presenting Shah Ismail Shaheed's arguments for pure tawheed in a concise and accessible format.

Shah Ismail Shaheed wrote Taqwiyat-ul-Imaan as a revivalist text aimed at restoring the pristine monotheistic creed of Islam among the Muslims of the Indian subcontinent. The book systematically addresses the various forms of shirk and religious innovation that had become prevalent, including the veneration of saints and shrines, the seeking of intercession from those who have passed away, the use of charms and amulets as substitutes for reliance upon Allah, and the attribution of divine qualities to human beings. For each deviation, Shah Ismail Shaheed presents the evidences from the Quran and authentic hadith that establish the correct Islamic position, demonstrating that the practices he criticizes are not marginal issues but fundamental violations of the core principle of Islam: the oneness of Allah.

This 14x21 edition is particularly well-suited for individual readers who want to study Taqwiyat-ul-Imaan at their own pace. The smaller format makes it a practical book for daily reading, and the text is laid out in clear Urdu prose that does not require the guidance of a teacher to understand, though the book certainly benefits from scholarly explanation. Many readers use this edition for personal spiritual development, reading it section by section and reflecting on the extent to which the issues Shah Ismail Shaheed addresses are relevant to their own beliefs and practices. It is also commonly used in halqah (study circle) settings, where a group reads and discusses the text together, benefiting from collective understanding and discussion. The 14x21 format is economical, making it suitable for mass distribution in da'wah contexts. Libraries, Islamic centers, and individuals who want a personal copy of this seminal work in a convenient size will find this edition to be practical and well-produced.`,
    metaDescription: "Taqwiyat-ul-Imaan in portable 14x21 cm format presents Shah Ismail Shaheed's classic Urdu text on Islamic monotheism and creed for personal study."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
