const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "tafsir-ibn-kathir-english-10-vols-set",
    description: `Tafsir Ibn Kathir in this ten-volume English translation represents the most comprehensive English-language edition of Hafiz Imaduddin Ismail bin Kathir's celebrated Quranic commentary available today. The decision to present the complete tafseer in ten volumes rather than condensing it into fewer reflects a commitment to preserving the full scope and detail of Ibn Kathir's scholarship. His original Arabic work is extensive, drawing upon the entire range of classical tafseer literature, hadith collections, and historical sources, and this English translation dedicates sufficient space to convey that comprehensiveness without the significant omissions that a more condensed format would require.

Ibn Kathir's tafseer methodology is rooted in the principles established by his teacher, the renowned scholar Ibn Taymiyyah, which prioritize interpreting the Quran through the Quran itself as the primary source, followed by authentic hadith of the Prophet Muhammad, then by the reports of the companions and the generation that followed them. This methodology produces a commentary that is firmly grounded in the earliest and most reliable understanding of Quranic meanings. The English translation faithfully conveys this approach, presenting the hadith citations, companion reports, and historical narratives that Ibn Kathir includes alongside his interpretive commentary. The translators have worked to render both the technical scholarly content and the historical narrative portions into clear, readable English that serves both academic and general readerships.

The ten volumes are organized to distribute the complete Quranic commentary evenly, with each volume covering a defined section of the Quranic text. This organization supports both sequential reading and quick reference, as readers can locate the volume containing a specific surah and consult it directly. Each volume includes the Arabic text of the relevant Quranic passages alongside the English translation and commentary, allowing readers who know some Arabic to follow the original text. The extensive introductory material in the early volumes discusses Ibn Kathir's life, his scholarly credentials, his methodology, and the historical context in which he composed his tafseer. For English-speaking Muslims, Islamic studies students, academic researchers, and librarians, this ten-volume set is the definitive English edition of one of the most important works in the Islamic exegetical tradition. It serves as both a primary study text for systematic Quranic study and an authoritative reference work for scholarly research.`,
    metaDescription: "The definitive 10-volume English translation of Tafsir Ibn Kathir, providing the complete classical commentary with hadith and historical context."
  },
  {
    slug: "tafsir-kalimaat-al-quran-14x21",
    description: `Tafsir Kalimaat al Quran presents a word-by-word analytical approach to Quranic interpretation, focusing on the linguistic composition and meaning of individual words and phrases within each verse. This 14x21 centimeter edition provides the complete tafseer in a medium-sized format that balances readability with manageable dimensions for home study and classroom use. The word-by-word methodology distinguishes this tafseer from verse-by-verse commentaries by directing the reader's attention to the building blocks of Quranic expression, helping develop a deeper appreciation for the precision and beauty of the Quranic Arabic language.

The analytical approach of Tafsir Kalimaat al Quran addresses each verse by breaking it down into its constituent words and phrases, explaining the meaning and grammatical function of each component before synthesizing these individual elements into a complete understanding of the verse. This methodology is particularly valuable for readers who are studying Arabic alongside their Quranic studies, as it reinforces vocabulary, grammar, and sentence structure while simultaneously building Quranic understanding. For readers who already have Arabic proficiency, the word-by-word analysis reveals nuances of meaning that might be overlooked in a verse-by-verse reading that treats each verse as a unitary statement.

The 14x21 format is one of the most practical sizes for a comprehensive tafseer, offering a page area large enough for clear typography and a well-organized layout, while remaining portable enough for regular use in various settings. The Arabic text is presented with full vowel marks, and the word-by-word analysis is formatted in a way that makes it easy to follow the correspondence between each Arabic word and its explanation. The complete tafseer covers every surah of the Quran, with introductory material for each chapter that provides context and thematic overview. This edition is especially recommended for students enrolled in Arabic language programs within Islamic educational institutions, self-taught Arabic learners who wish to apply their language skills to Quran study, and teachers who want a tafseer that supports linguistic instruction alongside religious content. The word-by-word approach also makes this tafseer useful for translators and researchers who need precise understanding of individual Quranic terms and their interpretive range within the classical exegetical tradition.`,
    metaDescription: "A 14x21 cm word-by-word Quranic tafseer analyzing individual Arabic terms and phrases, ideal for Arabic learners and students of Quranic linguistics."
  },
  {
    slug: "taharat-kay-masail",
    description: `Taharat kay Masail, meaning Issues of Purification, is a comprehensive Urdu-language reference work that addresses the Islamic legal rulings related to ritual purity and cleanliness. Taharat, the state of physical and ritual purity, is a foundational requirement for several acts of worship in Islam, most notably the five daily prayers, touching the Quran, and performing the pilgrimage. The correct understanding and practice of taharat rulings is therefore essential for every Muslim, and this book provides a thorough, well-organized guide to the subject that draws upon the major schools of Islamic jurisprudence while giving particular attention to the Hanafi school, which is predominant in South Asian Muslim communities.

The book is systematically organized to address every aspect of taharat in a logical progression. It begins with the most fundamental requirement, wudu (ablution), explaining the obligatory acts, the sunnah acts, the recommended practices, and the things that nullify wudu. Each ruling is supported by references to the relevant Quranic verses and authentic hadith, along with the opinions of the major classical jurists. The discussion of ghusl (ritual bathing) follows a similar structure, covering the situations that require ghusl, the obligatory and recommended components of the ritual, and common questions and scenarios that arise in practice. The book also addresses tayammum (dry ablution), which becomes necessary when water is unavailable or its use would cause harm.

Beyond the major rituals, Taharat kay Masail covers a range of related topics that are frequently the subject of questions and confusion among Muslims. These include the rulings related to various types of impurities and how to purify items contaminated by them, the specific regulations regarding menstrual bleeding and postnatal bleeding, the rules governing the impurities of dogs and pigs and their traces, and the etiquette of using the lavatory according to Islamic teaching. The book also addresses modern situations that classical texts may not have explicitly covered, providing guidance based on the general principles of Islamic jurisprudence. Written in clear, accessible Urdu, this book serves as both a practical reference for daily life and a study text for students of Islamic jurisprudence. Its question-and-answer format in certain sections makes it easy to find specific rulings quickly.`,
    metaDescription: "A comprehensive Urdu reference on Islamic purification covering wudu, ghusl, tayammum, and impurity laws with hadith references and Hanafi jurisprudence."
  },
  {
    slug: "taharat-ke-masail-kitab-ut-tahara",
    description: `Taharat ke Masail under the subtitle Kitab-ut-Tahara (The Book of Purification) provides a focused, textually grounded study of Islamic purity laws that distinguishes itself from other Urdu works on the same subject through its emphasis on direct engagement with the primary source texts. While many books on taharat present rulings in a simplified question-and-answer format, this work takes a more academic approach by connecting each ruling to its evidential basis in the Quran, the authentic hadith collections, and the classical juristic literature. This approach gives the reader not only a knowledge of what the rulings are but also an understanding of why these rulings exist and how they were derived by the scholars of Islamic law.

The book follows a structured progression through the major topics of taharat, beginning with the definition and significance of ritual purity in Islamic theology before moving to the specific rulings. The section on wudu provides a detailed analysis of each component of the ablution ritual, discussing the evidences for the obligatory nature of each act, the different scholarly opinions regarding certain elements, and the practical implications of these differences. The discussion of ghusl similarly covers all scenarios requiring ritual bathing, with particular attention to the linguistic meanings of the relevant Quranic verses and hadith texts that form the basis of the rulings.

Kitab-ut-Tahara also addresses topics that are often treated superficially in more introductory works on the subject. The discussion of najasah (impurity) includes a detailed analysis of the different types of impurities recognized in Islamic law, the methods for purifying items contaminated by different types of impurity, and the specific rulings related to modern materials and situations that were not directly addressed by classical texts. The section on istihadha (non-menstrual bleeding) and its differentiation from haidh (menstruation) and nifas (postnatal bleeding) is treated with particular thoroughness, as this is an area where many Muslims lack clarity. The book includes extensive footnotes and references that allow readers to verify the sources and pursue further study. For Islamic studies students, scholars, and serious readers who want a deeper understanding of taharat rulings beyond basic practical guidance, this book provides a comprehensive and intellectually satisfying treatment of the subject.`,
    metaDescription: "Kitab-ut-Tahara is a source-based Urdu study of Islamic purification laws, connecting each ruling to Quranic and hadith evidence with scholarly analysis."
  },
  {
    slug: "tahzib-al-bidayah-wal-nihaya-5-vol-arabic",
    description: `Tahzib Al Bidayah wal Nihaya is an abridged Arabic edition of Ibn Kathir's monumental historical work Al-Bidayah wal Nihaya (The Beginning and the End), which is widely regarded as one of the most comprehensive histories of the world written from an Islamic perspective. The complete Al-Bidayah wal Nihaya spans many volumes and covers the entire scope of human history from the creation of the heavens and the earth through the lives of the prophets, the era of the Prophet Muhammad, the rightly guided caliphs, the Umayyad and Abbasid dynasties, and extending into the author's own time. This five-volume abridgment distills the essential content of the larger work into a more manageable format while preserving the scholarly rigor and narrative quality that have made Ibn Kathir's history an indispensable reference in Islamic scholarship.

The Tahzib (refinement or abridgment) has been carefully prepared to retain the most historically significant and spiritually beneficial portions of the original text. The sections dealing with the stories of the prophets, drawn primarily from authentic Quranic and hadith sources, are preserved in their essential details, providing readers with a reliable account of prophetic history filtered through Ibn Kathir's critical evaluation of source materials. The life of the Prophet Muhammad receives extensive treatment, as it does in the original, covering the major events of his mission with attention to both historical accuracy and spiritual lessons. The history of the rightly guided caliphs and the early Muslim community is similarly preserved with sufficient detail to serve as a reliable historical reference.

The five-volume Arabic format makes this work accessible to Arabic-speaking readers and students of the language who wish to engage with classical Islamic historiography in its original language. Ibn Kathir's Arabic prose is clear and relatively straightforward compared to some other classical historians, making his work suitable for intermediate and advanced students of Arabic as well as native speakers. This abridged edition is particularly recommended for Islamic educational institutions that want to include classical Islamic history in their curriculum but cannot accommodate the many volumes of the complete work. Libraries, scholars, and individual readers who value the historical and educational content of Al-Bidayah wal Nihaya but need a more compact format will find this five-volume Tahzib to be an excellent solution that preserves the essence of Ibn Kathir's masterwork.`,
    metaDescription: "A 5-volume Arabic abridgment of Ibn Kathir's Al-Bidayah wal Nihaya, covering prophetic history and early Islamic civilization in a scholarly format."
  },
  {
    slug: "taiseer-al-quran-4-volume-set-computerized-darussalam",
    description: `Taiseer al Quran in this four-volume computerized edition published by Darussalam presents a comprehensive Quranic commentary that benefits from modern typesetting technology to deliver exceptionally clean and readable Arabic text alongside its interpretive content. The term "computerized" in the title refers to the digital typesetting process used in producing this edition, which represents a significant advancement over the traditional manual typesetting methods used in earlier Quranic publications. The result is a tafseer where every Arabic letter, vowel mark, and punctuation symbol is rendered with consistent precision and clarity throughout all four volumes.

The commentary content of Taiseer al Quran provides verse-by-verse interpretation of the complete Quranic text, drawing upon the major classical tafseer sources and presenting the interpretations in a clear, structured format. Each surah is preceded by an introduction that discusses its name, period of revelation, central themes, and relationship to preceding and succeeding surahs. The commentary addresses linguistic matters, explains obscure vocabulary, provides historical context for verses related to specific events, and draws out practical lessons and spiritual benefits. The interpretive approach is grounded in the methodology of the righteous predecessors, prioritizing interpretations supported by authentic textual evidence over speculative or philosophical reasoning.

Darussalam's reputation for quality Islamic publications is evident in the physical production of this set. The computerized typesetting ensures uniform text quality across all four volumes, with the Arabic script rendered in a clear, standardized naskh style that is widely regarded as the most readable for extended study. The paper quality is consistent with Darussalam's usual standards, providing good opacity to minimize show-through and a surface that supports clear printing. The binding of each volume is designed for durability, allowing the books to withstand the frequent use that a multi-volume tafseer naturally receives. The four-volume organization distributes the complete commentary into manageable sections that correspond to natural divisions in the Quranic text, making it practical for sequential study as well as reference use. This edition is suitable for Islamic libraries, educational institutions, and individual readers who appreciate the enhanced readability and consistent quality that computerized typesetting provides.`,
    metaDescription: "A 4-volume computerized Darussalam edition of Taiseer al Quran with digitally typeset Arabic text and comprehensive verse-by-verse commentary."
  },
  {
    slug: "taiseerul-allaam-shrah-umdatul-ahkaam-2-vols-set",
    description: `Taiseerul Allaam Sharh Umdatul Ahkaam is a two-volume Urdu commentary on Umdatul Ahkaam, one of the most widely studied compilations of hadith related to Islamic jurisprudence. Umdatul Ahkaam, originally compiled by the eminent scholar Abdul Ghani al-Maqdisi, selects hadith from the major collections of Bukhari and Muslim that are directly relevant to practical legal rulings, making it an essential text for students of Islamic law. This detailed Urdu sharh (explanation) by the author of Taiseerul Allaam unpacks each hadith with linguistic analysis, contextual background, and jurisprudential discussion that illuminates the legal principles derived from the prophetic traditions.

The two-volume structure allows sufficient space for the detailed treatment that each hadith in Umdatul Ahkaam deserves. The original work organizes hadith according to the chapters of Islamic jurisprudence, covering purification, prayer, fasting, charity, pilgrimage, marriage, divorce, commerce, criminal law, and other areas of practical Muslim life. For each hadith, the sharh provides the complete text in Arabic along with its Urdu translation, followed by an analysis that addresses multiple dimensions. The linguistic discussion explains the meaning of key Arabic words and phrases, identifying any terms that carry specific technical meanings within the jurisprudential context. The biographical notes on the narrators establish the chain of transmission and its reliability.

The jurisprudential discussion represents the most substantial portion of the commentary. For each hadith, the author examines the legal ruling or rulings that scholars have derived from it, presents the major scholarly opinions from the different schools of Islamic law, analyzes the evidence and reasoning behind each position, and indicates which opinion he considers most strongly supported. This comparative approach gives readers a comprehensive understanding of how a single prophetic tradition can be understood in multiple ways by qualified jurists, and it equips students with the analytical tools needed to engage with Islamic legal reasoning. The Urdu prose of the sharh is scholarly yet accessible, written for students who have some background in Islamic studies but may not be specialists in hadith or jurisprudence. This two-volume set is a valuable resource for madrasah students, Islamic university students, and self-learners who wish to deepen their understanding of how hadith serves as a primary source of Islamic law.`,
    metaDescription: "A 2-volume Urdu sharh of Umdatul Ahkaam providing detailed hadith analysis, linguistic discussion, and comparative jurisprudence from Bukhari and Muslim."
  },
  {
    slug: "tajalliyat-e-nabuwwat-new-edition-17x24",
    description: `Tajalliyat-e-Nabuwwat, meaning Manifestations of Prophethood, is a significant Urdu work that examines the concept of prophethood in Islam through a comprehensive study of its theological foundations, historical manifestations, and evidential basis. This new edition in the 17x24 centimeter format presents an updated and refined version of the original text, benefiting from additional research, revised arguments, and enhanced production quality that reflect the ongoing scholarly engagement with this vital subject. The question of prophethood lies at the very heart of Islamic belief, and this work addresses it with the thoroughness and intellectual rigor that such a foundational topic demands.

The book is organized into several major sections that collectively provide a complete picture of the Islamic understanding of prophethood. The opening sections establish the theological framework, discussing the necessity of prophethood for human guidance, the characteristics that define a true prophet, and the relationship between prophethood and other means of acquiring knowledge such as reason and sensory experience. The author draws upon both revelation and rational argumentation to demonstrate why prophethood is not merely a matter of faith but a logically defensible concept that addresses a genuine human need for divine guidance.

The historical sections of the book examine the manifestations of prophethood throughout human history, beginning with Adam and proceeding through the major prophets mentioned in the Quran. Each prophetic figure is discussed in terms of the specific message they brought, the challenges they faced from their communities, and the miracles that authenticated their claim to divine commission. The life of the Prophet Muhammad receives the most extensive treatment, with detailed discussion of the evidences for his prophethood including the miraculous nature of the Quran, the prophecies he made that were subsequently fulfilled, his character and conduct, and the impact of his message on human civilization. The new edition incorporates additional material responding to contemporary objections and questions about prophethood, making it relevant to modern readers who encounter skeptical arguments in academic and public discourse. The 17x24 format with its enhanced readability makes this substantial work more comfortable to study and reference over extended periods.`,
    metaDescription: "A new 17x24 cm Urdu edition of Tajalliyat-e-Nabuwwat examining prophethood through theology, historical evidence, and rational argumentation."
  },
  {
    slug: "tajweed-juz-ammah-30th-part",
    description: `Tajweed Juz Ammah is a specialized guide to the rules of Quranic recitation as applied specifically to the 30th part of the Quran, which contains the final 37 surahs from An-Naba to An-Nas. This focused approach to tajweed instruction has significant pedagogical advantages, as the 30th juz contains the surahs that most Muslims first learn to recite and continue to recite throughout their lives in daily prayers. By concentrating the tajweed instruction on these familiar surahs, this guide allows learners to immediately apply the rules they are studying to the recitation they already perform regularly, creating a direct connection between theoretical knowledge and practical application.

The book covers all the essential tajweed rules that apply within the 30th juz, including the correct pronunciation of Arabic letters with their various points of articulation, the rules governing noon sakina and tanween, the rules of meem sakina, the rules of mudood (prolongation) for the various types of elongated vowels, the characteristics of letters that affect their sound and quality, the rules regarding stopping and starting, and the various types of waqf (pausing) that affect meaning. Each rule is explained clearly in accessible language, supported by examples drawn directly from the surahs of the 30th juz so that the reader can see exactly how each rule functions within the actual text of the Quran.

The pedagogical structure of the book progresses from foundational concepts to more advanced rules, building the learner's competence incrementally. The early sections focus on the points of articulation and the basic characteristics of Arabic letters, which form the foundation of correct recitation. Subsequent sections address progressively more complex rules, with each new concept building upon what has already been covered. The examples from the 30th juz are marked with color coding or visual indicators that highlight the specific rule being demonstrated, making it easy for the reader to identify the application of each rule within the Quranic text. This focused tajweed guide is ideal for Quran teachers who want to introduce tajweed rules to their students using the familiar surahs of Juz Amma, for self-learners who want to improve the quality of their daily prayer recitation, and for hafiz students who need to ensure that their memorization of the 30th juz is accompanied by correct application of tajweed rules.`,
    metaDescription: "A focused tajweed guide for the 30th juz (Juz Ammah), teaching Quranic recitation rules with practical examples from the most frequently recited surahs."
  },
  {
    slug: "tajweed-ul-quran",
    description: `Tajweed ul Quran is a comprehensive guide to the science of Quranic recitation that covers the complete system of tajweed rules governing the proper pronunciation and recitation of the Holy Quran. Unlike specialized guides that focus on individual juz or surahs, this book provides the full theoretical framework and practical instruction needed to recite the entire Quran correctly, from the first verse of Al-Fatiha to the last verse of An-Nas. It serves as both a textbook for formal tajweed instruction and a reference manual for readers who wish to verify or refine specific aspects of their recitation.

The book is systematically organized to cover every major category of tajweed rules in a logical progression. It begins with the foundational concepts: the definition and importance of tajweed, the obligation of reciting the Quran with proper rules, and the categories of error in recitation. The section on the points of articulation of Arabic letters, known as makharij al-huruf, provides detailed descriptions of the exact oral positions from which each letter is produced, along with practical exercises for developing the ability to produce each letter from its correct point. The section on the characteristics of letters, sifaat al-huruf, addresses the intrinsic qualities that distinguish each letter and affect its sound when combined with adjacent letters.

The subsequent sections cover the specific rules that govern the interaction between letters in continuous recitation. The rules of noon sakina and tanween are treated with thoroughness, covering each of the four possible manifestations: izhar, idghaam, iqlaab, and ikhfaa. The rules of meem sakina, including ikhfaa shafawi, idghaam shafawi, and izhaar shafawi, are similarly detailed. The rules of mudood address the various types of vowel prolongation, including the natural prolongation, the required prolongation, the permissible prolongation, and the connecting prolongation, each with its specific duration and conditions. Additional sections cover the rules of noon and meem mushaddadah, the rules of laam of the divine name, the rules regarding the letter ra, the rules of qalqalah, the characteristics of the letters of idghaam, the rules of stopping and starting, and the etiquette of Quranic recitation. Throughout the book, examples from the Quran illustrate each rule in context. This comprehensive guide is an essential resource for anyone who teaches, studies, or practices the art of Quranic recitation.`,
    metaDescription: "A comprehensive guide to tajweed rules for Quranic recitation, covering articulation, letter characteristics, and recitation etiquette."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
