const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "tafsir-ahsanul-bayan-vol-2-english",
    description: `Volume 2 of the Tafsir Ahsanul Bayan English edition continues the comprehensive verse-by-verse commentary of the Quranic text in clear, contemporary English prose. This volume covers a substantial portion of the middle sections of the Quran, corresponding to the surahs that follow the opening juz and extend into the central chapters of the Book. These middle surahs contain some of the most legally and theologically dense material in the entire Quran, including detailed provisions for family law, inheritance, criminal justice, and interfaith relations, making this volume particularly important for readers who wish to understand the practical legal implications of Quranic guidance.

The commentary in this volume addresses the complex legislative passages with scholarly precision while remaining accessible to readers who do not have formal training in Islamic jurisprudence. The translators have included explanatory notes that clarify legal terminology and provide context for rulings that may seem unfamiliar to contemporary English-speaking readers. The historical narratives found in these surahs, including accounts of the prophets Musa, Ibrahim, and other messengers, are treated with attention to both their narrative details and their theological and moral lessons. The volume also covers the verses related to the Battle of Uhud and other events from the Madinan period, providing the historical background necessary for understanding the Quranic guidance that was revealed in response to specific situations.

For readers who are building their Tafsir Ahsanul Bayan collection volume by volume, this second installment is essential for maintaining the continuity of their Quranic study program. The volume is self-contained in the sense that its introduction and commentary provide sufficient context for the surahs it covers, but it is designed to function as part of the complete five-volume set where the full scope of the tafseer's methodology and cross-referencing becomes most apparent. The quality of printing and binding is consistent with the other volumes in the set, ensuring a uniform appearance on the shelf and comparable durability through regular use. Students enrolled in structured Quranic study programs will find this volume corresponds to the middle portion of their curriculum, while individual readers can use it as a standalone reference for the specific surahs it covers.`,
    metaDescription: "Volume 2 of Tafsir Ahsanul Bayan in English, covering the middle Quranic surahs with detailed commentary on legal rulings and prophetic narratives."
  },
  {
    slug: "tafsir-ahsanul-bayan-vol-3-english",
    description: `Volume 3 of the Tafsir Ahsanul Bayan English translation continues the systematic commentary through the next section of the Quranic text, building upon the foundation established in the first two volumes. This installment covers surahs that include some of the most theologically significant passages in the Quran, addressing themes such as the nature of faith, the relationship between divine decree and human responsibility, the characteristics of the righteous, and the signs of Allah in the natural world. The English commentary maintains the clear, accessible style that characterizes the entire set while providing the depth of analysis that serious Quranic study demands.

The surahs covered in this volume include chapters that address both individual spiritual development and the collective responsibilities of the Muslim community. The commentary examines the Quranic teachings on patience during trials, the importance of gratitude for divine blessings, the proper attitude toward wealth and material possessions, and the ethical standards that should govern interpersonal relationships. The prophetic narratives in these sections, including stories of prophets such as Nuh, Lut, and Shu'aib, are analyzed for their moral and theological implications rather than treated merely as historical accounts. The commentary draws connections between the experiences of these ancient prophets and the challenges facing contemporary Muslims, highlighting the timeless relevance of Quranic guidance.

The translation quality in this third volume reflects the accumulated experience of the translation team, with increasingly refined English prose that captures both the meaning and the rhetorical impact of the original Urdu commentary. Technical terms related to Islamic theology and jurisprudence are either explained in context or translated into English equivalents that accurately convey their meaning. The volume includes the standard features of the set, including surah introductions, contextual notes, and cross-references to related passages elsewhere in the Quran. For readers who are collecting the complete set, this volume is a crucial bridge between the middle and later sections of the Quran. It is also valuable as a standalone reference for anyone studying the specific surahs contained within its pages, whether in a formal educational setting or through independent study at home.`,
    metaDescription: "Volume 3 of Tafsir Ahsanul Bayan in English, covering key middle surahs with commentary on faith, divine signs, prophetic stories, and ethical guidance."
  },
  {
    slug: "tafsir-ahsanul-bayan-vol-4-english",
    description: `Volume 4 of the Tafsir Ahsanul Bayan English edition advances the comprehensive commentary into the later sections of the Quran, where the surahs become progressively shorter and theologically more concentrated. These surahs, many of which were revealed during the Makkan period, contain some of the most powerful and rhetorically compelling passages in the entire Quran. The commentary in this volume addresses the dense theological content of these shorter chapters, where themes of divine oneness, the reality of the afterlife, the truth of prophethood, and the consequences of rejecting divine guidance are presented with extraordinary rhetorical intensity and concision.

The English commentary in this volume pays particular attention to the literary qualities of the Quranic text, explaining the rhetorical devices, linguistic structures, and stylistic features that make these surahs among the most impactful in the entire Book. The shorter surahs often employ vivid imagery, dramatic contrasts, and direct addresses that create a powerful effect on the listener, and the commentary helps English-speaking readers appreciate these literary qualities even through the medium of translation. The historical context of the Makkan revelations is provided in detail, helping readers understand the social and religious environment in which these surahs were first delivered and the specific objections and arguments of the Makkan pagans that the Quran was addressing.

This volume also covers surahs that contain legal provisions and communal instructions that were revealed during the Madinan period, providing commentary that explains the practical implications of these verses for Muslim life and community organization. The balance between the passionate theological rhetoric of the Makkan surahs and the practical legal guidance of the Madinan passages creates a reading experience that reflects the full range of Quranic discourse. As with the other volumes in this set, the translation maintains a commitment to accuracy without sacrificing readability, making the profound content of these surahs accessible to English-speaking readers regardless of their prior familiarity with Islamic studies. This volume is an essential component of the complete five-volume set and a valuable standalone resource for readers focusing on the later portions of the Quran.`,
    metaDescription: "Volume 4 of Tafsir Ahsanul Bayan in English, analyzing the shorter, theologically intense later surahs with attention to rhetoric and legal guidance."
  },
  {
    slug: "tafsir-ahsanul-bayan-vol-5-english",
    description: `Volume 5, the final installment of the Tafsir Ahsanul Bayan English edition, brings the comprehensive commentary to its conclusion by covering the remaining surahs of the Quran. This volume includes the very last chapters of the Book, many of which are among the most beloved and frequently recited passages in the Muslim world. Surahs such as Al-Mulk, Al-Qalam, Al-Haaqqah, Al-Ma'arij, and the concluding surahs from Al-Falaq to An-Nas are covered with the same thorough, accessible English commentary that has characterized the entire five-volume set. For many readers, this final volume will be the most personally meaningful, as it contains the surahs that form a regular part of daily prayers and devotional practices.

The commentary on these concluding surahs pays particular attention to their devotional and spiritual dimensions. Many of the shorter surahs at the end of the Quran are recited not only in obligatory prayers but also in supplications, funeral prayers, and various religious observances, and understanding their meanings significantly enhances the quality of these devotional acts. The English commentary explains the context and full meaning of each verse, allowing readers to move beyond rote recitation to informed, conscious engagement with the words they are pronouncing. The powerful descriptions of the Day of Judgment found in these surahs, the vivid portrayals of paradise and hellfire, and the moving calls to faith and moral accountability are all discussed with appropriate depth and sensitivity.

As the concluding volume of the set, this installment also includes any supplementary material that rounds out the complete tafseer, such as indexes, glossaries, or thematic guides that help readers navigate the entire five-volume work. The completion of all five volumes provides the English-speaking reader with a comprehensive Quranic commentary that covers every verse of the Book, from Al-Fatiha to An-Nas, in consistent, accessible English prose. This final volume ensures that the reader's journey through the Quran, guided by the Tafsir Ahsanul Bayan, reaches its proper conclusion with the same quality of scholarship and clarity that has marked the preceding installments. For anyone seeking a complete English tafseer, acquiring all five volumes is essential, and this final piece completes the collection.`,
    metaDescription: "The final volume 5 of Tafsir Ahsanul Bayan in English, covering the concluding surahs with commentary on their devotional and spiritual significance."
  },
  {
    slug: "tafsir-al-quran-30th-parah-new-edition",
    description: `The 30th para, also known as Juz Amma, contains the last 37 surahs of the Holy Quran and is the section most Muslims first learn to recite as children and most frequently encounter in their daily prayers. This new edition of Tafsir al Quran focused specifically on the 30th para provides a fresh, updated commentary on these beloved chapters that reflects recent scholarship and addresses the needs of contemporary readers. The 30th para contains some of the shortest yet most theologically powerful surahs in the entire Quran, and a focused tafseer of this section allows for a more detailed treatment of each chapter than a general tafseer that must distribute its attention across the entire Book.

The new edition incorporates improvements over previous printings, which may include updated translations of specific verses, expanded commentary on passages that readers had found unclear, additional contextual information based on recent research, and enhanced formatting that improves the reading experience. The Arabic text of the 30th para is presented with full vowel marks and tajweed notation, supporting correct recitation alongside meaningful understanding. The commentary follows each verse with clear explanations of its meaning, context, and implications, written in language that is accessible to readers at various levels of Islamic knowledge.

This focused tafseer of the 30th para serves several important practical purposes. For new Muslims and young students who are beginning their engagement with Quranic commentary, starting with the 30th para is natural because these are the surahs they already know by heart. Understanding the meanings of verses they recite daily transforms their prayer experience from mechanical repetition into conscious worship. For more advanced students, a dedicated commentary on the 30th para allows for deeper engagement with the concentrated theological content of these shorter surahs than would be possible in a general tafseer. The new edition's improvements ensure that readers receive the most current and refined presentation of this important commentary. Whether used for personal study, classroom instruction, or group discussion in mosque study circles, this focused tafseer of the 30th para is a valuable resource for any Muslim seeking to deepen their understanding of the chapters they recite most frequently.`,
    metaDescription: "A new edition tafseer focused on the 30th para (Juz Amma), providing updated commentary on the most frequently recited surahs for daily prayer."
  },
  {
    slug: "tafsir-as-sadi-parts-1-2-3",
    description: `Tafsir As-Sa'di by Shaykh Abdur Rahman bin Nasir as-Sa'di is among the most highly regarded contemporary Quranic commentaries, valued for its clarity, moderation, and faithfulness to the methodology of the righteous predecessors. This edition covers Parts 1, 2, and 3 of the Quran, corresponding to the opening three juz that begin with Surah Al-Fatiha and extend through the early portions of Surah Al-Baqarah and into the beginning of Aal-e-Imran. These opening sections of the Quran contain foundational material that establishes the core principles of Islamic belief, law, and guidance, making this focused commentary particularly significant for readers seeking a solid grounding in Quranic understanding.

The three opening juz of the Quran contain some of the most essential and comprehensive guidance in the entire Book. Surah Al-Fatiha summarizes the entire message of the Quran in seven verses. Surah Al-Baqarah, the longest chapter, covers an extraordinary range of topics including the nature of faith, the characteristics of believers and hypocrites, the stories of the Israelites, legal rulings on fasting, pilgrimage, and financial transactions, the change of qiblah, and the foundational principles of Islamic jurisprudence. Shaykh as-Sa'di's commentary addresses each of these topics with a clarity and concision that makes complex matters understandable without oversimplification.

The methodology of Tafsir As-Sa'di is distinguished by its balanced approach. The Shaykh avoids the extreme of providing only transmitted interpretations without explanation, and the opposite extreme of relying primarily on personal reasoning. He presents the established meanings of each verse based on authentic sources, explains them in clear Arabic prose, and draws out practical lessons and spiritual benefits that connect the Quranic text to the reader's lived experience. His language is straightforward and free from unnecessary rhetorical embellishment, which has made his tafseer popular among both scholars and general readers. This edition covering Parts 1 through 3 is ideal for readers who want to focus their study on the opening sections of the Quran, whether in a structured study program that progresses through the Quran juz by juz, or as part of a classroom curriculum that dedicates a semester or term to the opening chapters.`,
    metaDescription: "Parts 1-2-3 of Tafsir As-Sa'di covering Al-Fatiha and early Al-Baqarah, offering clear balanced commentary on the foundational opening of the Quran."
  },
  {
    slug: "tafsir-as-sadi-parts-28-29-30",
    description: `This edition of Tafsir As-Sa'di covers Parts 28, 29, and 30 of the Quran, encompassing the concluding juz of the Holy Book. These final three sections contain the shorter surahs that are most frequently recited in daily prayers, making this focused commentary particularly relevant to the devotional life of every Muslim. The 30th juz, known as Juz Amma, is the portion that most Muslims learn first in childhood and recite most often throughout their lives, while the 28th and 29th juz contain surahs of increasing length and depth that serve as a transition between the longer middle chapters and the concise concluding surahs.

Shaykh as-Sa'di's commentary on these concluding sections demonstrates the same clarity and methodological rigor that characterizes his tafseer of the earlier portions of the Quran. His approach to the shorter surahs is particularly effective because he recognizes that the brevity of these chapters actually demands more careful interpretation rather than less. Each word and phrase in the shorter surahs carries concentrated meaning, and Shaykh as-Sa'di unpacks this meaning with precision, explaining the implications of each statement for the believer's understanding of theology, morality, and the afterlife. His commentary on Surah Al-Mulk, for instance, addresses both the detailed descriptions of divine creation that demonstrate Allah's power and the terrifying descriptions of punishment that serve as warnings to those who reject guidance.

The sections covering the 28th and 29th juz include surahs such as Al-Mujadila, Al-Hashr, Al-Mumtahanah, As-Saff, Al-Jumu'ah, Al-Munafiqun, At-Taghabun, At-Talaq, At-Tahrim, Al-Mulk, Al-Qalam, and others. These surahs address a mix of communal guidelines, moral instructions, theological affirmations, and descriptions of the hereafter. Shaykh as-Sa'di's commentary provides the historical context for each surah, explains the linguistic nuances of key terms, and draws out the practical lessons that make these ancient revelations relevant to contemporary Muslim life. This edition is an excellent choice for readers who have already studied the earlier parts of the Quran and wish to focus their attention on the concluding sections, or for those who specifically want to deepen their understanding of the surahs they recite in their daily prayers.`,
    metaDescription: "Parts 28-29-30 of Tafsir As-Sa'di covering the Quran's concluding juz, providing detailed commentary on frequently recited surahs for daily prayer."
  },
  {
    slug: "tafsir-as-sadi-3-vol",
    description: `The complete three-volume set of Tafsir As-Sa'di by Shaykh Abdur Rahman bin Nasir as-Sa'di provides the entire Quranic commentary in a compact, well-organized format that covers every verse of the Holy Quran from Al-Fatiha to An-Nas. While the individual parts editions allow focused study of specific juz, this three-volume complete set gives readers the full scope of Shaykh as-Sa'di's celebrated tafseer in its entirety, enabling systematic study of the complete Quran with consistent commentary from a single authoritative voice throughout.

Shaykh as-Sa'di's tafseer has earned its prominent place in contemporary Islamic scholarship through a distinctive methodology that combines several key strengths. First, he adheres closely to the principles of the righteous predecessors, interpreting the Quran primarily through the Quran itself, then through authentic hadith, then through the understanding of the companions and early scholars. Second, his Arabic prose is exceptionally clear and accessible, written in a style that educated readers can understand without needing specialized training in classical Arabic or Islamic sciences. Third, his commentary consistently draws out practical and spiritual lessons from each passage, connecting the text to the reader's faith, worship, and daily conduct. This combination of methodological soundness, linguistic clarity, and practical relevance explains why Tafsir As-Sa'di has become one of the most widely studied and recommended contemporary tafseer works.

The three-volume format is more compact than many multi-volume tafseer sets, reflecting the relative concision of Shaykh as-Sa'di's approach. He does not engage in lengthy scholarly debates or cite extensive chains of narration for every point, but instead presents the most authoritative interpretation of each verse in a direct and efficient manner. This concision makes the complete set more manageable for readers who wish to study the entire tafseer systematically, as the reading load per volume is reasonable and the prose flows naturally from verse to verse. The set is suitable for both individual study and as a teaching resource in Islamic educational institutions. Many scholars recommend Tafsir As-Sa'di as the ideal first complete tafseer for students who have progressed beyond basic Quran reading and are ready to engage with a comprehensive commentary. This three-volume complete set ensures that readers have the full resource available for reference whenever they encounter a verse they wish to understand more deeply.`,
    metaDescription: "The complete 3-volume Tafsir As-Sa'di covering the entire Quran, combining sound methodology with clear Arabic prose and practical spiritual lessons."
  },
  {
    slug: "tafsir-ibn-e-kathir-6-vol-set-urdu",
    description: `Tafsir Ibn Kathir, the monumental Quranic commentary by the renowned Syrian scholar Hafiz Imaduddin Ismail bin Kathir, is available in this complete six-volume Urdu translation that makes one of the most important works of classical Islamic exegesis accessible to Urdu-speaking readers. The Arabic original of Tafsir Ibn Kathir has served as a primary reference for Quranic interpretation for over seven centuries, and this Urdu translation brings its comprehensive scholarship to the vast Urdu-speaking Muslim population across South Asia and the global diaspora.

The six-volume format provides adequate space for the extensive content that characterizes Ibn Kathir's approach to tafseer. His methodology, which prioritizes interpretation through the Quran itself, then through authentic prophetic traditions, then through the reports of the companions and their successors, produces a commentary that is rich in historical detail, hadith citations, and contextual information. The Urdu translation faithfully conveys this richness, preserving the chains of narration, the multiple reports related to each verse, and the scholarly discussions that make Tafsir Ibn Kathir such a comprehensive resource. The translators have employed a formal register of Urdu that is appropriate for religious and scholarly content while remaining accessible to educated readers who may not have specialized training in Islamic studies.

This complete six-volume Urdu set covers every surah of the Quran from Al-Fatiha to An-Nas, with extensive introductions to each chapter covering its name, period of revelation, virtues, and central themes. The commentary addresses each verse with thoroughness that reflects Ibn Kathir's encyclopedic knowledge of the Quranic sciences, hadith literature, and Islamic history. His extensive citation of hadith, with full chains of narration and authentication commentary, provides readers with a valuable resource for hadith study alongside tafseer. The reports from the companions and early scholars give insight into how the first generations of Muslims understood the Quranic text. For Urdu-speaking scholars, students, and serious readers, this six-volume set is an essential component of any Islamic library. It serves as both a primary study text for systematic Quranic study and a reference work for researching specific verses, topics, or hadith related to Quranic interpretation.`,
    metaDescription: "A 6-volume Urdu translation of Tafsir Ibn Kathir, the classical Quranic commentary, presenting authentic hadith, companion reports, and historical context."
  },
  {
    slug: "tafsir-ibn-kathir-abridged-30th-part",
    description: `This abridged edition of Tafsir Ibn Kathir focuses exclusively on the 30th part of the Quran, commonly known as Juz Amma, which contains the final 37 surahs from Surah An-Naba to Surah An-Nas. By concentrating on this single juz, the abridgers have been able to present the essential commentary of Ibn Kathir on these frequently recited surahs in a compact, focused volume that is practical for daily use. The 30th juz contains the surahs that most Muslims recite in their daily prayers, making this focused tafseer particularly relevant to the everyday devotional life of the Muslim community.

The abridgement process has distilled Ibn Kathir's characteristic methodology into a more concise presentation while preserving the core strengths of his approach. The commentary retains the essential interpretive framework of interpreting the Quran through the Quran itself, authentic hadith, and the reports of the early Muslim community. The extensive chains of narration that characterize the complete Tafsir Ibn Kathir have been condensed, with the commentary focusing on the meanings and lessons derived from the most authentic reports rather than documenting every available narration chain. This approach makes the commentary more accessible to general readers who want to understand the meanings of these surahs without engaging with the full scholarly apparatus of the complete multi-volume work.

The 30th juz contains surahs of extraordinary theological power despite their relative brevity. Surah An-Naba describes the Day of Judgment with vivid imagery. Surah An-Nazi'at and Abasa address themes of resurrection and moral responsibility. Surah At-Takwir and Al-Infitar present dramatic descriptions of cosmic upheaval. Surah Al-Mulk, known as the protector from the punishment of the grave, is studied in detail with its descriptions of divine creation and power. The concluding surahs from Al-Falaq to An-Nas, which focus on seeking divine protection, receive focused commentary that explains their significance and proper usage. This abridged volume is ideal for readers who want the scholarly reliability of Tafsir Ibn Kathir applied specifically to the surahs they encounter most frequently in their daily worship, presented in a format that is compact enough for regular use and reference.`,
    metaDescription: "An abridged Tafsir Ibn Kathir focused on the 30th juz (Juz Amma), providing concise scholarly commentary on the 37 surahs most recited in daily prayer."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
