const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "basic-principles-of-islam",
    description: `Basic Principles of Islam is an English-language introductory text that presents the foundational beliefs, practices, and ethical framework of Islam in a clear, systematic, and reader-friendly format designed for English-speaking audiences — including new Muslims, non-Muslims seeking to understand Islam, Muslim youth educated in English-medium schools, and anyone who wants a concise yet comprehensive overview of what Islam teaches and requires from its followers. The book is structured around three core pillars of Islamic life: Imaan (faith/belief), Islam (practice/worship), and Ihsan (excellence in worship and character) — the three-dimensional framework established by the famous hadith of Jibreel (AS) where the Angel Gabriel visited the Prophet (ﷺ) in the form of a man and asked him about Islam, Imaan, and Ihsan, and the Prophet's (ﷺ) answers became the definitive summary of the religion's essential teachings.

The Imaan section covers the six articles of Islamic faith with clarity and depth appropriate for an introductory text — belief in Allah as the one, unique Creator with no partners, associates, or equals; belief in the angels as Allah's created beings who carry out His commands; belief in the divinely revealed books including the Torah (Tawrat), Psalms (Zabur), Gospel (Injeel), and the final revelation the Quran; belief in all the prophets and messengers from Adam through Muhammad (ﷺ); belief in the Day of Judgment and the accountability that follows; and belief in divine predestination (Qadr) while affirming human free will and responsibility. Each article of faith is explained with supporting Quranic verses and hadith, and common misconceptions are addressed — such as the misconception that Muslims worship Muhammad (ﷺ), the confusion between divine predestination and fatalism, and the question of how Muslims view Jesus (AS) and Christianity.

The Islam section provides practical, step-by-step guidance for the five pillars — Shahadah (the declaration of faith and what it truly means to bear witness), Salah (the five daily prayers with illustrated instructions covering wudu, the prayer movements, and the recitations), Zakat (the obligation of charitable giving with calculation examples), Sawm (fasting during Ramadan with its rules, exemptions, and spiritual benefits), and Hajj (the pilgrimage to Makkah with an overview of each ritual). The Ihsan section addresses the often-neglected third dimension of Islamic practice — the internal state of consciousness, sincerity, and spiritual excellence that should accompany external acts of worship. It covers topics such as the importance of intention (niyyah), the concept of muraqabah (awareness that Allah is watching), the cultivation of good character traits (akhlāq) including honesty, patience, gratitude, humility, generosity, and forgiveness, and the role of the heart in Islamic spirituality. The book concludes with a chapter on contemporary challenges facing Muslims — including Islamophobia, the challenge of living as a religious minority, the balance between modernity and tradition, and the importance of representing Islam positively through personal conduct. For Pakistani readers educated in English-medium institutions, for students in international schools, and for dawah workers who need a clear introductory text to share with interested non-Muslims, Basic Principles of Islam provides an excellent, well-organized, and intellectually honest presentation of the religion's essential teachings.`,
    metaDescription: "Basic Principles of Islam — clear English guide to Islamic faith, worship, and character. Ideal for new Muslims and English-medium students. Buy online."
  },
  {
    slug: "be-patient-and-paradise-will-be-yours",
    description: `Be Patient and Paradise Will Be Yours is an inspirational and deeply moving English-language book that explores the Islamic concept of sabr (patience) as one of the most meritorious and divinely rewarded qualities a believer can possess. The title itself draws upon one of the most comforting promises in the Quran — "Indeed, the patient will be given their reward without account" (Az-Zumar 39:10) — a verse that assures believers that those who endure hardship with patience and faith will receive their Paradise as an immeasurable, uncounted reward from Allah. In a world where suffering, loss, illness, financial difficulty, and emotional pain are inevitable realities for every human being, this book offers the Islamic perspective that transforms patience from a passive, resigned endurance into an active, spiritually powerful worship that carries profound meaning, purpose, and eternal reward.

The book is organized into thematic chapters that address different dimensions of patience. The first dimension covers patience in obedience (sabr ala al-ta'ah) — the patience required to consistently perform acts of worship, maintain good habits, resist temptations, and stay on the straight path despite challenges and distractions. The second covers patience in refraining from sin (sabr 'an al-ma'siyah) — the patience needed to control desires, avoid haram, lower the gaze, guard the tongue, and resist social pressure toward wrongdoing. The third and perhaps most challenging dimension covers patience in affliction (sabr 'ala al-bala') — the patience required when facing illness, bereavement, financial loss, relationship difficulties, persecution, and other forms of hardship that Allah tests His servants with. Each dimension is explored through Quranic verses, hadith of the Prophet (ﷺ), stories of the prophets and companions who demonstrated extraordinary patience, and practical guidance for developing patience as a character trait.

The book's emotional power comes from its unflinching engagement with real human suffering — it does not offer superficial platitudes or deny the reality of pain. Instead, it acknowledges that some tests are devastatingly difficult, that grief is natural and even necessary, and that even the greatest prophets experienced moments of anguish. The story of Prophet Ayyub (AS), who endured the loss of his wealth, his children, and his health yet continued to praise Allah, is presented not as a distant legend but as a relatable human story of faith under extreme pressure. The story of Prophet Yaqub (AS), who grieved so deeply for his lost son Yusuf that he went blind from weeping, yet never lost faith in Allah's plan, is analyzed for its profound lessons about the compatibility of grief and faith. The story of the Prophet (ﷺ) losing his infant son Ibrahim, weeping at his graveside, yet saying "The eyes shed tears and the heart grieves, but we say nothing except what pleases our Lord" demonstrates that patience does not mean feeling nothing — it means choosing faith despite feeling everything. For Pakistani readers navigating the challenges of daily life — economic uncertainty, health issues, family struggles, and the general difficulties of modern existence — this book provides both the spiritual framework and the emotional sustenance to face every trial with sabr, dignity, and unwavering trust in Allah's wisdom and mercy.`,
    metaDescription: "Be Patient and Paradise Will Be Yours — Islamic book on Sabr (patience) with Quranic promises and Prophetic examples. Transform suffering into worship. Buy online."
  },
  {
    slug: "bearing-true-witness-of-islam",
    description: `Bearing True Witness of Islam is a comprehensive English-language guide that explores what it truly means to be a Muslim — not merely in name or cultural identity, but in the fullest, most authentic sense of the term — based on the Quran, the Sunnah of Prophet Muhammad (ﷺ), and the practice of the early Muslim community (the Salaf). The book's title refers to the Shahadah, the testimony of faith ("I bear witness that there is no god but Allah and I bear witness that Muhammad is His messenger"), and argues that this declaration is not simply a one-time statement recited at conversion but a living commitment that must be actively demonstrated through every aspect of a Muslim's life — their beliefs, their worship, their character, their relationships, their work, their consumption, and their engagement with society. The book challenges the complacency that often develops among born Muslims who inherit Islam as a cultural identity without personally verifying, understanding, and implementing its teachings.

The book is structured around the concept of "witnessing" — exploring what a Muslim is testifying to when they recite the Shahadah and what that testimony demands in practical terms. The first half of the Shahadah ("La ilaha illallah") is unpacked chapter by chapter, examining what it means to truly believe that there is no deity worthy of worship except Allah — exploring implications for theology (the rejection of all forms of shirk), for worship (directing all acts of devotion to Allah alone), for law and governance (recognizing Allah as the ultimate legislator), for trust and reliance (tawakkul), and for love (prioritizing love of Allah above all other attachments). The second half of the Shahadah ("Muhammadur rasulullah") is similarly examined — exploring what it means to truly bear witness that Muhammad is Allah's messenger, including the obligation to follow his example in every aspect of life, to love him more than oneself, to accept his rulings as binding, to prefer his guidance over personal opinions, and to defend his honor against slander and misrepresentation.

The book addresses contemporary challenges to authentic Islamic witness — including the dilution of Islamic practice through cultural accretions that have no basis in the Quran and Sunnah, the pressure to compromise Islamic principles for social acceptance, the challenge of maintaining Islamic identity in secular environments, the rise of extreme interpretations that distort Islam's image, and the need for Muslims to represent their faith through excellence in every field of human endeavor. The author provides practical guidance for self-audit — helping readers honestly assess whether their daily lives truly "bear witness" to the Islamic values they profess. The book is particularly valuable for Pakistani Muslims working in multinational environments, studying abroad, or engaging with non-Muslim colleagues and friends — providing them with the knowledge, confidence, and practical framework to represent Islam authentically through both their words and their actions. At Rs.1,650, this substantial hardcover volume represents a serious investment in understanding and living one's faith more deeply and consistently.`,
    metaDescription: "Bearing True Witness of Islam — deep exploration of Shahadah and authentic Muslim identity. Quranic, Sunnah-based guide for living Islam fully. Buy online."
  },
  {
    slug: "before-you-pray",
    description: `Before You Pray is a focused, practical English-language guide that addresses the essential preparations, conditions, and inner dimensions that must be understood and fulfilled before a Muslim's prayer (salah) can be considered valid and spiritually meaningful. While many prayer guides focus exclusively on the physical movements and Arabic recitations of the prayer itself, this book takes the critically important approach of addressing everything that must happen before the prayer begins — because the Prophet Muhammad (ﷺ) taught that the quality of the prayer is directly dependent on the quality of the preparation that precedes it. A prayer offered with proper preparation carries spiritual weight and brings genuine peace to the heart, while a prayer offered hastily and without preparation — even if mechanically correct — fails to achieve its intended purpose of connecting the worshipper with their Creator.

The book begins with the conditions (shurut) of prayer — the prerequisites that must be met before the prayer can even begin. These include being Muslim, being in a state of mental sanity, reaching the age of puberty (though children are encouraged to practice), being in a state of ritual purity (taharah) through wudu or ghusl, having removed all physical impurities (najasa) from one's body, clothing, and prayer place, covering the awrah (the minimum required area of the body that must be covered), facing the qiblah (the direction of the Ka'bah in Makkah), and ensuring the prayer time has entered. Each condition is explained with clear, practical guidance — the wudu section, for instance, provides a step-by-step illustrated guide with the specific du'as to recite at each step, common mistakes to avoid, and the things that break wudu. The section on purity of clothing and prayer place addresses practical issues like blood stains, animal hair, and the impurity of dogs — topics that frequently cause confusion but are essential for prayer validity.

Beyond the external conditions, the book dedicates significant attention to the internal preparation that transforms prayer from a physical exercise into a spiritual experience. The section on khushu' (concentration, humility, and presence of heart in prayer) explores why most Muslims struggle with distracted prayers and provides practical strategies for achieving greater focus — including preparing the heart through pre-prayer du'a, choosing a quiet and clean prayer space, avoiding praying when hungry or excessively tired, understanding the meaning of the Arabic recitations, and the powerful technique of praying as if it is one's last prayer. The book also covers the importance of salah times, the method of determining them accurately, and the serious sin of intentionally delaying prayers beyond their prescribed times. Special sections address common scenarios that affect prayer preparation — praying at work, praying in public spaces, praying while traveling, and praying when unwell. For new Muslims, for young people learning to establish their prayer practice, and for anyone whose prayer has become mechanical and spiritually dry, Before You Pray provides the essential knowledge and practical tools to transform the daily prayer from a reluctant obligation into a cherished, spiritually enriching encounter with Allah.`,
    metaDescription: "Before You Pray — English guide to prayer preparation. Wudu, purity, khushu', conditions of valid Salah. Practical for new Muslims. Buy online at Bab-ul-Fatah."
  },
  {
    slug: "behno-k-lye-tohfa",
    description: `Behno K Liye Tohfa (A Gift for Sisters) is a compact, affordable Urdu booklet specifically written for Muslim women and girls, covering a curated collection of essential Islamic knowledge, supplications, and practical guidance that every Muslim sister should have at her fingertips. The title "Tohfa" (gift) reflects the author's intention of presenting this knowledge as a precious offering — recognizing that Islamic knowledge is among the greatest gifts one Muslim can give to another. The booklet is designed to be carried in a purse or handbag, kept on a nightstand, or shared among female family members and friends, providing quick access to essential du'as, Islamic rulings relevant to women's daily lives, and inspirational reminders that nourish the soul throughout the day.

The booklet opens with the essential daily adhkar (remembrances) — the morning and evening supplications, the du'as before sleeping and upon waking, and the dhikr for various daily activities — presented in Arabic with Urdu translation and clear instructions on when and how many times each should be recited. The prayer section covers the specific prayer-related rulings most relevant to women — including the method of performing salah during menstruation and post-natal bleeding, the rules for making up missed fasts, the recommended times for voluntary prayers, and the du'as that the Prophet (ﷺ) specifically recommended for women. The booklet also includes a collection of du'as for specific needs — du'as for marriage, du'as for conception and healthy pregnancy, du'as for the well-being of children and family, du'as for protection from envy and evil eye, and du'as for success in exams and career.

The practical advice section addresses common questions and challenges that Muslim women in Pakistan encounter daily — including guidance on Islamic dress code (hijab) and how to maintain it in various social contexts, the Islamic etiquette of interacting with non-mahram men (including workplace interactions), the importance of seeking knowledge as a religious obligation for both men and women, the balance between household responsibilities and personal spiritual development, and the rights and responsibilities of wives in Islamic marriage. The booklet draws upon authentic hadith of the Prophet (ﷺ), including narrations specifically addressed to women — such as his advice to his wives, his encouragement of women's education (the famous hadith "Seeking knowledge is an obligation upon every Muslim" applies equally to women), and his praise for the righteous women of the early Muslim community. At just Rs.150, this booklet is among the most affordable Islamic resources available, making it an ideal gift for female relatives, friends, classmates, and colleagues. Many mosques and Islamic centers in Pakistan distribute this booklet during women's gatherings, Ramadan programs, and educational seminars. Its small size, practical content, and affordable price make Behno K Liye Tohfa a must-have companion for every Muslim woman and girl in Pakistan.`,
    metaDescription: "Behno K Liye Tohfa — essential Islamic gift booklet for Muslim women. Du'as, prayer guidance, hijab advice, women's rulings. Affordable Urdu booklet."
  },
  {
    slug: "behtreen-zaad-e-rah-taqwa",
    description: `Behtreen Zaad-e-Rah — Taqwa (The Best Provision for the Journey: God-Consciousness) is a concise, spiritually potent Urdu booklet that focuses exclusively on the Islamic concept of taqwa — consciousness of Allah, fear of His displeasure, and the constant awareness that He is watching — which the Quran identifies as the most valuable provision a person can carry on their journey through this life toward the eternal hereafter. The title's metaphor of taqwa as "provision" (zaad) for the "journey" (rah) of life draws upon the Quranic verse: "And take provision, but indeed the best provision is taqwa" (Al-Baqarah 2:197) — a verse revealed in the context of Hajj, where pilgrims were reminded that while physical provisions for the journey are necessary, the spiritual provision of taqwa is infinitely more important because it sustains the soul not just through the pilgrimage but through every moment of existence until death.

The booklet defines taqwa through multiple lenses — as the protective shield between a believer and Allah's punishment, as the internal compass that guides moral decision-making in moments of solitude when no one is watching, as the quality that distinguishes the people of Paradise from the people of Hellfire, and as the standard by which Allah measures a person's true worth (as stated in the Quran: "Indeed, the most noble of you in the sight of Allah is the most righteous of you" — Al-Hujurat 49:13). The author explores how taqwa manifests in practical daily life — in a businessman who refuses to cheat even when no inspector is watching, in a student who does not copy even when the teacher is not looking, in a government employee who does not accept bribes even when everyone around him does, in a young person who lowers their gaze and guards their modesty even when society normalizes immodesty, and in a homemaker who manages the household with honesty, patience, and gratitude even when unrecognized and underappreciated.

The booklet draws upon the Quran's extensive discussion of taqwa — which appears in over 250 verses — to demonstrate its centrality to the Islamic message. Specific Quranic verses are analyzed to show the multifaceted rewards promised to the muttaqun (those who possess taqwa): Allah's love (Aali Imran 3:76), Allah's friendship (Al-Jathiyah 45:19), ease in all affairs (At-Talaq 65:4), a way out from every difficulty (At-Talaq 65:2-3), provisions from unexpected sources (At-Talaq 65:3), success in this world and the next (Al-A'raf 7:96), and entry into Paradise (Al-A'raf 7:96). The hadith section includes the Prophet's (ﷺ) guidance on cultivating taqwa — including his advice to Ibn Abbas: "Be mindful of Allah, and He will be mindful of you; be mindful of Allah, and you will find Him before you." The booklet is short enough to be read in a single sitting, yet profound enough to transform the reader's perspective on life's purpose and priorities. For Pakistani Muslims at every stage of spiritual development — whether beginners just learning about their faith or seasoned practitioners seeking to deepen their taqwa — this booklet provides a powerful, concentrated dose of spiritual guidance that can be revisited again and again for renewed inspiration and motivation.`,
    metaDescription: "Behtreen Zaad-e-Rah Taqwa — Urdu booklet on the power of God-consciousness. Quranic rewards of Taqwa, practical daily application. Buy online at Bab-ul-Fatah."
  },
  {
    slug: "beti-ki-shan-o-azmat",
    description: `Beti Ki Shan-o-Azmat (The Status and Dignity of the Daughter) is a profoundly important Urdu book that addresses the Islamic perspective on daughters — their rights, their status, their dignity, and the extraordinary rewards promised to parents who raise them with love, care, and Islamic education. This book is specifically written for the Pakistani context, where cultural practices related to daughters often contradict Islamic teachings — including the preference for sons over daughters, the practice of treating daughters as a financial burden, the concept of dowry that makes daughters feel unwanted, and the lingering influence of pre-Islamic customs that Islam came to abolish. The book draws a clear, uncompromising line between cultural practice and Islamic commandment, demonstrating that in Islam, the birth of a daughter is not merely a tolerable event but a cause for celebration, a source of divine blessing, and an opportunity for the parents to earn immense spiritual reward.

The book's foundation is the Quranic condemnation of the pre-Islamic practice of female infanticide — "And when one of them is informed of [the birth of] a female, his face becomes dark, and he suppresses grief. He hides himself from the people because of the ill of which he has been informed. Should he keep it in humiliation or bury it in the ground? Unquestionably, evil is what they decide" (An-Nahl 16:58-59) — and the Prophet's (ﷺ) radical reversal of this attitude. The hadith evidence presented includes the narration where the Prophet (ﷺ) said: "Whoever has three daughters and is patient with them, feeds them, gives them drink, and clothes them from his wealth, they will be a shield for him from the Fire on the Day of Judgment." Another narration states: "Whoever is tested with daughters and treats them well, they will be a veil for him from the Fire." The book also includes the famous story of the man who came to the Prophet (ﷺ) complaining about his daughter, and the Prophet (ﷺ) rebuked him, saying that daughters are a "fragrant flower from Paradise."

The practical section of the book addresses the rights of daughters in Islam — including the right to life (a right Islam established fourteen centuries ago that many cultures still struggle to guarantee), the right to education (the Prophet ﷺ explicitly encouraged the education of both sons and daughters), the right to inheritance (a daughter receives half the share of a son, which is her independent right, not the father's to distribute at his discretion), the right to choose her husband (the Prophet ﷺ taught that a woman cannot be married without her consent), and the right to be treated with the same love and affection as sons. The book also addresses contemporary challenges — including the impact of ultrasound technology and sex-selective practices, the financial pressures of dowry, the social stigma attached to families with only daughters, and the need for systemic change in how Pakistani society values its girls. For parents expecting a daughter, for families with daughters, and for anyone who wishes to understand and promote the Islamic perspective on the status and dignity of women, Beti Ki Shan-o-Azmat provides a thorough, well-referenced, and emotionally compelling resource that challenges cultural prejudices and restores the Islamic honor that belongs to every daughter.`,
    metaDescription: "Beti Ki Shan-o-Azmat — Islamic book on the status, rights, and dignity of daughters. Quranic and hadith evidence against gender discrimination. Buy online at Bab-ul-Fatah."
  },
  {
    slug: "better-muslim-pack",
    description: `The Better Muslim Pack is a thoughtfully curated collection of essential Islamic books and resources bundled together to provide a comprehensive foundation of Islamic knowledge for individuals and families who wish to improve their understanding and practice of Islam. This all-in-one package has been assembled by the editorial team at Bab-ul-Fatah based on their understanding of the most commonly needed Islamic resources — drawing from customer feedback, educator recommendations, and scholarly consensus on the foundational texts that every Muslim household should possess. The pack represents exceptional value, offering multiple books at a combined price significantly lower than purchasing each item individually, making it the most cost-effective way to build a basic Islamic home library.

The pack typically includes a selection of essential Islamic texts covering the core areas of Islamic knowledge — prayer guidance (including detailed instructions for performing salah correctly with proper wudu and recitations), a collection of daily adhkar and du'as for every occasion, a basic Seerah book covering the life of Prophet Muhammad (ﷺ), a hadith collection for daily reading and guidance, a book on Islamic character and manners (akhlāq), and possibly additional resources such as an introductory book on Islamic beliefs (aqeedah), a Quran translation or commentary excerpt, and a practical guide to common Islamic questions and answers. Each book in the pack is selected for its accuracy, readability, and practical usefulness — avoiding overly academic texts that gather dust on shelves in favor of books that will actually be read, referenced, and benefited from on a daily basis.

The Better Muslim Pack is designed to serve multiple purposes and audiences. For new Muslims, it provides the essential knowledge needed to begin practicing Islam confidently — answering the "what do I do now?" question with a curated set of resources that cover all the basics. For Muslim families, it creates a shared library that parents and children can both benefit from — with age-appropriate content that the whole family can engage with. For students and young professionals who have gaps in their Islamic education, the pack fills those gaps efficiently without requiring them to identify and purchase each resource individually. For dawah workers and community leaders, the pack serves as a ready-made gift set that can be given to new Muslims, distributed during educational programs, or used as prizes in Islamic knowledge competitions. The Rs.2,750 price point makes this comprehensive package accessible to middle-income Pakistani families, and the premium packaging ensures that it makes an impressive gift when presented at occasions such as Eid, Ramadan, weddings, and graduations. By bundling these essential resources together, the Better Muslim Pack removes the decision fatigue that often prevents people from building their Islamic library — providing a single, comprehensive solution that addresses the most important areas of Islamic knowledge and practice.`,
    metaDescription: "Better Muslim Pack — curated collection of essential Islamic books for home library. Salah guide, du'as, Seerah, hadith, akhlaq. Best value bundle. Order online."
  },
  {
    slug: "beyond-mere-christianity",
    description: `Beyond Mere Christianity is an English-language Islamic apologetics work that engages directly with Christian theology and apologetics, providing Muslim readers — particularly those living in Christian-majority countries or working in multicultural environments — with the knowledge, arguments, and evidence needed to understand Christian beliefs from an Islamic perspective and to respond intelligently to Christian missionary claims about the nature of God, the mission of Jesus, and the supposed corruption of the Islamic message. The book's title is a deliberate reference to C.S. Lewis's famous apologetics work "Mere Christianity," signaling that this book aims to go "beyond" the standard Christian apologetics framework by examining the foundational assumptions of Christian theology through the lens of the Quran, the Bible itself, and rational analysis.

The book is organized around the key theological differences between Islam and Christianity, examining each point with scholarly rigor while maintaining an accessible, reader-friendly style. The chapter on the nature of God addresses the doctrine of the Trinity — presenting the Islamic monotheistic (tawhid) perspective while also demonstrating how the concept of God's absolute oneness is more consistent with the Old Testament, with Jesus's own statements (such as "The Lord our God, the Lord is one" in Mark 12:29), and with rational philosophical arguments for divine unity. The chapter on Jesus examines the Islamic view of Jesus (AS) as a prophet, messenger, and Messiah — not as God or the Son of God — and analyzes the biblical passages that Christians cite as evidence for Jesus's divinity, showing how these same passages can be understood in a way that is consistent with Jesus's prophetic mission and does not require a Trinitarian interpretation.

The chapter on the crucifixion presents the Islamic perspective (based on Quran 4:157 — "They did not kill him, nor did they crucify him; but [another] was made to resemble him to them") while also examining the historical and textual evidence within the Bible itself that casts doubt on the traditional crucifixion narrative — including inconsistencies between the four Gospel accounts, the absence of the crucifixion from the earliest Christian writings, and the Jewish perspective on the event. The chapter on Paul examines the historical role of Paul of Tarsus in transforming the original monotheistic teachings of Jesus into the Trinitarian theology that became mainstream Christianity — arguing that much of what distinguishes Christianity from Judaism and Islam came not from Jesus himself but from Paul's theological innovations. The book also addresses common missionary arguments used against Islam — including claims about the Quran's supposed borrowings from Jewish and Christian sources, allegations about the Prophet Muhammad's (ﷺ) character, and the claim that the Bible is more historically reliable than the Quran. Each argument is addressed with evidence, logic, and respectful scholarly engagement. For Pakistani Muslims studying at Christian missionary schools, working in international environments, or engaging in interfaith dialogue, Beyond Mere Christianity provides the intellectual tools to represent their faith confidently and respond to Christian claims with knowledge and sophistication.`,
    metaDescription: "Beyond Mere Christianity — Islamic response to Christian theology and apologetics. Trinity, crucifixion, Paul, interfaith dialogue. English scholarly work. Buy online."
  },
  {
    slug: "brass-handle-rehal-7-inch",
    description: `Brass Handle Rehal — 7 Inch is a beautifully crafted Quran stand (rehal/x-shaped book holder) featuring ornamental brass handles that combines traditional Islamic craftsmanship with practical functionality, providing a stable and elegant platform for reading the Holy Quran, Islamic books, and other religious texts during prayer, study, or recitation sessions. The rehal has been an essential accessory in Muslim households, mosques, and madrasahs for centuries — its folding X-shape design allowing it to hold books open at any page angle while taking up minimal space when stored. This particular 7-inch model is sized for standard Quran editions commonly used in Pakistani homes and mosques, with the brass handle detail adding a touch of artistic elegance that elevates it from a purely functional item to a decorative piece worthy of display even when not in use.

The rehal's frame is constructed from quality wood — typically sheesham (rosewood) or mango wood, known for their durability and natural beauty — with brass handles fitted at the fold points that serve both as decorative accents and as practical carrying handles that make it easy to transport the rehal between rooms or to the mosque. The brass is polished to a warm golden shine that complements both traditional and contemporary interior decor styles, and develops a pleasing patina over years of use that adds character and vintage appeal. The wooden surfaces may feature traditional Islamic geometric patterns or floral motifs carved or etched into the wood — decorative elements that reflect the rich heritage of Islamic artisanal craftsmanship while adding grip for the book pages. The folding mechanism uses sturdy brass hinges that allow the rehal to open and close smoothly, and the angled reading surface provides optimal viewing angles that reduce neck strain during extended reading sessions.

This 7-inch rehal is the most versatile size in the rehal family — compact enough for a bedside table, a personal study desk, or even a prayer mat during daily Quran recitation, yet large enough to hold most standard Quran editions (15-line and 16-line formats commonly used in Pakistan) without the book overhanging or feeling unstable. The rehal's weight is balanced to prevent tipping even when heavy reference books are placed on it, and the angled surface includes a small ledge or lip at the bottom edge that prevents the book from sliding forward. For elderly readers who find it difficult to hold a heavy Quran for extended periods, this rehal provides essential support that makes daily Quran reading comfortable and accessible. For students at Islamic schools and madrasahs, the rehal is a required accessory that protects both the book (by preventing the spine from cracking when the book is laid flat) and the reader (by maintaining a comfortable ergonomic posture). The rehal also makes an excellent gift — particularly for new Muslims receiving their first Quran, for weddings and housewarmings, and for Ramadan when many Muslims increase their Quran reading. At Rs.600, this brass-handled rehal offers outstanding value for a product that combines functional utility with artistic beauty and will serve its owner faithfully for many years.`,
    metaDescription: "Brass Handle Rehal 7-inch — elegant wooden Quran stand with brass accents. Folding X-design, holds standard Quran sizes. Perfect gift. Buy online."
  }
];

async function main() {
  let updated = 0, failed = 0;
  for (const item of updates) {
    try {
      const result = await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log(`✅ Updated: ${result.title} (${result.slug})`);
      updated++;
    } catch (err) {
      console.log(`❌ Failed: ${item.slug} — ${err.message}`);
      failed++;
    }
  }
  console.log(`\nBatch R3F complete: ${updated} updated, ${failed} failed`);
}

main().then(() => prisma.$disconnect());
