const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "namaz-e-nabvi-sc-12x17",
    description: `Namaz-e-Nabvi in soft cover 12x17 format is a thoughtfully produced edition of the authoritative prayer guide that presents the complete methodology of the Prophet Muhammad's prayer in a practical and accessible binding. The 12x17 dimensions provide a generous reading area that makes the Arabic text, Urdu transliteration, and commentary comfortably legible without requiring the larger institutional formats. The soft cover binding keeps the overall weight manageable, making this edition easy to handle during study sessions and convenient for transport to madrasah classes, study circles, or the mosque. The content offers a position-by-position walkthrough of the entire prayer, beginning with the prerequisites of purification, proper covering, and facing the Qiblah, and proceeding through each stage from the opening Takbir to the final Salam. Every obligatory act is clearly distinguished from sunnah and mustahabb actions, allowing readers to develop a nuanced understanding of what is essential versus what enhances the prayer. The Arabic recitations for each position are presented in a traditional Naskh font with full tashkeel or vowel marks, and each is accompanied by Urdu transliteration using widely recognised conventions that help readers pronounce the Arabic correctly even if they have not formally studied the language. The Urdu translation of each recitation is rendered in clear, contemporary language that avoids archaic expressions and communicates the meaning of the supplications effectively to modern readers. Footnotes throughout the text address common questions, resolve apparent contradictions between hadith narrations, and provide additional context from classical fiqh sources. The book includes chapters on the Friday prayer, Eid prayers, funeral prayer, prayer during travel, prayer of the sick person, and the night prayer or Tahajjud. Quick-reference tables summarise the rakat structure for each of the five daily prayers. The soft cover 12x17 format has become particularly popular in madrasah settings where students need a readable textbook that is also affordable and lightweight. The paper quality is chosen to withstand regular use while keeping the production cost reasonable for bulk educational purchases. This edition serves well as both a primary instructional text and a personal reference for anyone seeking to align their prayer practice with the authenticated Prophetic method.`,
    metaDescription: "Namaz-e-Nabvi SC 12x17 is a softcover Urdu prayer guide with Arabic text, transliteration, and commentary covering all prayer types in a readable format."
  },
  {
    slug: "naqashi-pattern-calligraphy-book",
    description: `Naqashi Pattern Calligraphy Book is a specialised instructional resource designed for artists, students, and enthusiasts of Islamic geometric patterns and Arabic calligraphy who wish to develop their skills in the traditional decorative arts. The book provides a structured curriculum that begins with the fundamental principles of Islamic geometric design, introducing the grid systems, compass techniques, and proportional relationships that underpin the intricate patterns found in mosques, madrasahs, and palaces across the Islamic world. Readers are guided step-by-step through the construction of basic geometric shapes such as six-pointed stars, eight-pointed stars, and interlocking polygons, before progressing to more complex compositions that combine multiple geometric elements into cohesive, symmetrical designs. Each pattern is presented with detailed construction diagrams that show the precise sequence of compass and ruler operations required to reproduce the design accurately. Alongside the geometric content, the book includes dedicated sections on Arabic calligraphy, covering the major scripts including Naskh, Thuluth, and Riqa, with practice pages that allow readers to develop their lettering technique. The calligraphy instruction addresses stroke order, letter proportion, spacing between characters, and the principles of composition that govern the arrangement of calligraphic text within geometric frames. A valuable feature of this book is its inclusion of historical context for each pattern type, tracing the evolution of specific designs across different regions and periods of Islamic art history. This contextual knowledge enriches the creative process by helping artists understand the cultural and spiritual significance of the patterns they are learning to create. The book also addresses the practical considerations of working with different media including ink on paper, brushwork on ceramics, and engraving on metal or wood. Colour theory as applied to Islamic pattern design is discussed, with guidance on traditional colour palettes and their symbolic associations in Islamic art. Practice grids and template pages are provided throughout the book, allowing readers to work directly within its pages. This book is recommended for students enrolled in Islamic art programmes, self-taught artists exploring geometric design, and anyone with an appreciation for the mathematical beauty and spiritual depth of Islamic decorative traditions.`,
    metaDescription: "Naqashi Pattern Calligraphy Book teaches Islamic geometric design and Arabic calligraphy through step-by-step diagrams and practice pages."
  },
  {
    slug: "nau-molood-kay-ahkam-o-masail-aur-islami-naam",
    description: `Nau Molood kay Ahkam o Masail Aur Islami Naam is a comprehensive Urdu-language guide that addresses two closely related topics of great importance to Muslim families: the Islamic rulings and practical matters concerning newborns, and the guidance on choosing appropriate Islamic names. The book begins with the religious obligations and recommended practices that apply from the moment of a child's birth, including the adhan recited in the newborn's ear, the tahneek or rubbing of a softened date on the baby's palate, the aqiqah sacrifice, the shaving of the newborn's head on the seventh day, and the naming ceremony. Each practice is explained with reference to authentic hadith sources, and the author provides clear guidance on the obligations, the sunnah muakkadah, and the culturally practised customs that do not carry specific religious weight. The book addresses common questions that arise in modern medical contexts, such as the timing of circumcision, the ruling on vaccines administered at birth, and the Islamic perspective on various obstetric procedures. A significant portion of the text is dedicated to the comprehensive topic of Islamic naming, beginning with the hadith that establishes the importance of choosing a good name and the categories of names that are recommended, permissible, and prohibited in Islam. The author provides an extensive curated list of names for boys and girls, each accompanied by its Arabic spelling, Urdu pronunciation, meaning, and the notable Muslim figures who bore that name throughout history. The book discusses the ruling on names that carry meanings of shirk or servitude to other than Allah, the permissibility of non-Arabic names, and the guidance on names that express inappropriate or negative meanings. Practical advice is offered for parents navigating the naming process in multicultural contexts where family traditions, cultural expectations, and Islamic guidance may sometimes conflict. The book also covers the rulings related to changing one's name if the original name carries an Islamically problematic meaning. Throughout the text, the author maintains a balance between scholarly precision and practical accessibility, making this an essential reference for expectant parents, grandparents, and Islamic community workers who assist families during the childbirth period. The inclusion of an alphabetical name index at the end allows quick reference for parents considering specific names.`,
    metaDescription: "Nau Molood kay Ahkam o Masail Aur Islami Naam is an Urdu guide on newborn rulings and choosing meaningful Islamic names with hadith references."
  },
  {
    slug: "need-of-creed-series-the-last-day-beyond-death",
    description: `The Need of Creed Series volume focusing on the Last Day Beyond Death is a scholarly English-language work that provides a detailed and evidence-based examination of Islamic eschatology. Part of a broader series dedicated to clarifying the articles of Islamic faith, this volume concentrates specifically on the events and realities that follow death, drawing exclusively upon the authentic texts of the Quran and the established hadith collections to construct a comprehensive picture of what the Islamic tradition teaches about the afterlife. The book begins with the experience of the soul at the moment of death, discussing the Quranic descriptions of how the angels extract the soul and the distinction made between the treatment of the souls of the righteous and the souls of the disbelievers. It then proceeds to a detailed treatment of the Barzakh or the intermediate state between death and the Day of Judgement, covering the questioning in the grave by the two angels Munkar and Nakir, the bliss or punishment experienced in the grave, and the nature of this intermediate existence as described in the primary sources. The volume then addresses the major signs of the Last Day as narrated in authentic hadith, including the appearance of the Dajjal, the return of Isa ibn Maryam, the emergence of Gog and Magog, the rising of the sun from the west, and the blowing of the trumpet. The Day of Judgement itself is covered in extensive detail, including the gathering of creation, the weighing of deeds, the intercession of the prophets and righteous, the bridging of the Sirat, and the ultimate destinations of Paradise and Hellfire. Each topic is supported by specific Quranic verses and authenticated hadith narrations, with full references provided for verification. The author takes care to distinguish between definitively established texts and those that are classified as hasan or weak, ensuring that readers can distinguish between core creedal beliefs and narrations of lesser certitude. The writing style is academic yet accessible, making this volume suitable for both serious students of Islamic theology and educated general readers who wish to understand what Islam teaches about the afterlife. A comprehensive index and glossary of Arabic terms support the reader's navigation through this substantial theological work.`,
    metaDescription: "Need of Creed Series: The Last Day Beyond Death is a scholarly English examination of Islamic eschatology covering death and the Day of Judgement."
  },
  {
    slug: "neekio-ko-mata-deny-waly-amaal",
    description: `Neekio ko Mata Deny Waly Amaal is an important Urdu-language book that identifies and discusses the various actions, habits, and behaviours that can diminish or nullify the reward of good deeds in Islam. The title, which translates roughly to Deeds that Waste Good Deeds, addresses a concern that is central to every practicing Muslim: the possibility that one's acts of worship and charity might be undermined by accompanying sins, insincerity, or violations of Islamic principles. The book draws upon Quranic verses and authentic hadith to establish that good deeds are indeed vulnerable to being cancelled or reduced in weight by specific contradictory actions, and that a Muslim must be vigilant about protecting the integrity of their worship through awareness of these factors. The author organises the book around categories of nullifying actions, beginning with the most serious: shirk or associating partners with Allah, which the Quran explicitly states renders all deeds worthless. Subsequent chapters address lesser but still significant threats to the preservation of good deeds, including showing off or riya in acts of worship, arrogance or kibr that corrupts the intention behind good actions, harming others while simultaneously performing acts of devotion, and the failure to fulfil the rights of people while focusing exclusively on the rights of Allah. The book discusses how sins committed between acts of worship can erase the accumulated reward of those worship acts, citing the hadith in which the Prophet compared sins that follow good deeds to a person who carries a burning torch that eventually burns everything around it. Each category of nullifying action is illustrated with real-life scenarios that make the abstract concepts tangible and relatable for readers. The author also provides a hopeful counterbalance by discussing the means of restoring and protecting one's good deeds, including sincere repentance, consistent istighfar, and the maintenance of sincere intention. The Urdu prose is clear and direct, avoiding excessive technical terminology while maintaining the scholarly depth that the subject demands. This book is recommended for anyone who wishes to develop a more holistic understanding of how Islamic teachings view the relationship between good deeds, sins, and the ultimate accounting on the Day of Judgement.`,
    metaDescription: "Neekio ko Mata Deny Waly Amaal explores actions that diminish good deeds in Islam, offering Quranic and hadith guidance on protecting worship."
  },
  {
    slug: "new-bismillah-calligraphy",
    description: `New Bismillah Calligraphy is a beautifully crafted piece of Islamic wall art that presents the sacred invocation Bismillah ir-Rahman ir-Rahim in a contemporary calligraphic design. The Bismillah, meaning In the Name of Allah, the Most Gracious, the Most Merciful, holds a position of extraordinary importance in Islam as the verse with which almost every surah of the Quran begins and the phrase that Muslims recite before undertaking virtually any action throughout their daily lives. This calligraphy piece renders the Bismillah in a modern artistic style that bridges traditional Arabic calligraphic principles with current design aesthetics, resulting in a work that feels simultaneously timeless and contemporary. The script chosen for this piece is a refined Thuluth variant, characterised by its flowing curves, balanced proportions, and the elegant interplay between thick and thin strokes that gives Thuluth its distinctive visual rhythm. Each letter of the Bismillah has been carefully composed to ensure both aesthetic beauty and orthographic accuracy, respecting the established rules of Arabic calligraphy while allowing for artistic interpretation in the flourishes and extensions that give the piece its decorative character. The standard edition is produced on high-quality art paper or card stock that provides a smooth, non-reflective surface ideal for displaying the calligraphy under various lighting conditions. The print quality captures the fine details of the original calligraphic work, preserving the subtle variations in ink density and stroke width that are characteristic of hand-rendered calligraphy. The colour scheme uses a classic combination of dark calligraphic text against a neutral background, allowing the beauty of the script to command attention without visual competition from ornamental elements. This piece is suited for display in a wide range of indoor settings including living rooms, bedrooms, studies, offices, classrooms, and prayer rooms. It also serves as a meaningful gift for occasions such as housewarmings, graduations, Eid celebrations, and the beginning of Ramadan. The clean design appeals to a broad aesthetic sensibility, making it appropriate for both traditional and contemporary interior decor styles. The frame-ready dimensions allow for easy mounting in standard-sized frames.`,
    metaDescription: "New Bismillah Calligraphy presents the sacred opening phrase in refined Thuluth script on premium art paper for homes and educational spaces."
  },
  {
    slug: "new-bismillah-calligraphy-golden",
    description: `New Bismillah Calligraphy in the Golden edition elevates the sacred invocation of Bismillah ir-Rahman ir-Rahim through the use of a luxurious golden finish that imparts a sense of reverence and sophistication to this essential Islamic phrase. The golden variant shares the same masterful calligraphic composition as the standard edition but distinguishes itself through the application of metallic gold tones that catch and reflect light, creating a dynamic visual effect that shifts subtly depending on the angle of illumination and the time of day. The use of gold in Islamic art carries deep historical and spiritual significance, recalling the gilded manuscripts, illuminated Quran pages, and gold-leaf architectural ornamentation that have been hallmarks of Islamic artistic tradition for centuries. In this calligraphy piece, the golden script stands out prominently against its background, creating a focal point that naturally draws the eye and establishes a centrepiece within any room. The calligraphic rendering follows the Thuluth tradition with its characteristic sweeping curves, proportional letterforms, and rhythmic alternation between bold and delicate strokes. The golden finish is applied using advanced printing techniques that replicate the depth and luminosity of genuine gold leaf, achieving a result that has a premium appearance far exceeding what standard metallic inks can produce. The background is carefully chosen to complement the gold tones, providing sufficient contrast to ensure legibility while maintaining the overall sense of elegance that the golden theme demands. The production process uses archival-quality materials that resist fading and discolouration over time, ensuring that the gold tones retain their brilliance through years of display. This golden edition is particularly well suited for display in formal spaces such as reception areas, conference rooms, guest living rooms, and the main prayer areas of homes and institutions. It also holds special significance as a gift for important life events including weddings, housewarmings, and milestone religious occasions. The premium finish positions this piece as a collectible item for those who appreciate fine Islamic art and calligraphy. Frame-ready sizing ensures straightforward mounting in standard or custom frames that complement the golden aesthetic.`,
    metaDescription: "New Bismillah Calligraphy Golden edition features the sacred invocation in metallic gold tones on archival material, ideal for formal Islamic wall art."
  },
  {
    slug: "nifah-tul-ahadith-darsi",
    description: `Nifah Tul Ahadith Darsi is an academic hadith compilation specifically designed for use in educational institutions and structured learning environments. Unlike general hadith collections that are organised for personal reading or scholarly reference, this Darsi or academic edition is structured as a teaching text with pedagogical features that support both instructors and students in the systematic study of Prophetic traditions. The book selects hadith that cover the essential themes of Islamic knowledge, including faith and creed, the pillars of Islam, moral conduct, social responsibilities, worship practices, and spiritual development. Each hadith is presented with its complete Arabic text in a clear, vowelled script, followed by the Urdu translation and a detailed commentary that explains the vocabulary, context, and practical implications of the narration. The commentary draws upon established hadith exegesis works, including the explanations of classical scholars, to provide layers of understanding that accommodate readers at different levels of expertise. Footnotes provide biographical information about the narrators mentioned in the hadith chains, helping students develop familiarity with the major figures of hadith transmission. The Darsi format includes several features specifically designed for classroom use: chapter introductions that outline the learning objectives for each section, review questions at the end of each chapter that test comprehension and encourage critical thinking, vocabulary lists that highlight key Arabic terms with their Urdu equivalents, and suggested discussion topics that instructors can use to facilitate classroom dialogue. The book also includes brief introductions to the science of hadith, covering the classification of narrations as Sahih, Hasan, and Daif, the criteria used by hadith scholars to evaluate the authenticity of narrations, and the major collections of hadith and their distinguishing characteristics. This foundational knowledge equips students with the analytical framework needed to approach hadith literature with appropriate scholarly rigour. The selection and arrangement of hadith follows a curriculum-based approach, ensuring that students encounter the most essential narrations early in their studies and build toward more complex topics as they progress. This compilation is widely adopted in madrasahs, Islamic schools, and adult education programmes where hadith is taught as a formal subject requiring structured instruction and assessment.`,
    metaDescription: "Nifah Tul Ahadith Darsi is a structured Urdu hadith textbook with Arabic text, commentary, and narrator biographies for Islamic educational institutions."
  },
  {
    slug: "nijat-yafta-kon",
    description: `Nijat Yafta Kon, meaning Who Will Be Saved, is a thought-provoking Urdu-language book that addresses one of the most fundamental questions in Islamic theology: the criteria for salvation and the qualities that distinguish those who will attain success in the afterlife from those who will not. The book approaches this weighty subject with a balance of scholarly depth and accessible language, making complex theological concepts understandable to readers who may not have formal training in Islamic studies. Drawing primarily upon the Quran and authentic hadith, the author constructs a comprehensive picture of the Islamic understanding of salvation that encompasses belief, actions, divine mercy, and the interplay between human effort and God's grace. The opening chapters establish the Quranic framework of salvation, discussing the concepts of Iman or faith, Amaal al-Salihah or righteous deeds, and the rejection of shirk as the foundational requirements for success in the hereafter. The book then examines in detail the specific qualities that the Quran and Sunnah identify as characteristics of the saved, including sincerity of faith, consistency in worship, avoidance of major sins, quickness in repentance, fulfilment of the rights of others, and adherence to the Prophetic guidance in all matters of religion. A dedicated chapter addresses the common misconceptions about salvation in Islam, clarifying the middle path between the extremes of absolute assurance and complete despair. The author discusses the role of divine mercy, the intercession of the Prophet Muhammad, peace be upon him, and the various categories of people who will receive Allah's forgiveness despite their shortcomings. The book also tackles difficult questions such as the fate of those who have never received the message of Islam, the status of children who die before the age of accountability, and the circumstances under which a Muslim's sins might be forgiven through other means besides formal repentance. Throughout the text, the author maintains a tone that encourages hope without complacency, reminding readers that while Allah's mercy is vast, it should not be taken as a licence for carelessness in matters of faith and practice. This book is suitable for general readers, study circles, and anyone seeking clarity on what Islam teaches about salvation and the path to eternal success.`,
    metaDescription: "Nijat Yafta Kon explores Islamic salvation criteria through Quranic and hadith evidence, balancing divine mercy with righteous action in Urdu."
  },
  {
    slug: "nikkah-kay-masail",
    description: `Nikkah Kay Masail is a comprehensive Urdu-language reference book that addresses the Islamic rulings, practical procedures, and common questions related to marriage in Islam. The book provides detailed guidance on every aspect of the marriage process from the initial selection of a spouse through the wedding ceremony and into the establishment of a stable marital household. Written in a clear question-and-answer format that allows readers to locate specific information quickly, this book serves as an essential resource for individuals approaching marriage, parents arranging marriages for their children, and community leaders who are frequently called upon to advise on marital matters. The book opens with the foundational rulings on marriage in Islam, including the Quranic basis for marriage as a solemn covenant, the classification of marriage as sunnah muakkadah or an emphasised Prophetic practice, and the conditions that must be met for a marriage contract to be considered valid. Subsequent chapters address the specific requirements for a valid nikah including the consent of both parties, the presence of witnesses, the payment of mahr, and the role of the wali or guardian. The book provides detailed guidance on the mahr, discussing its minimum amount, the different forms it can take, the wisdom behind this obligation, and the ruling on its forfeiture. Practical chapters cover the procedure for conducting the nikah ceremony, including the khutbah or sermon that should precede the contract, the offer and acceptance formula, and the documentation requirements. The book also addresses contemporary issues that frequently arise in Muslim communities, including the ruling on court marriages versus religious marriages, the validity of marriages conducted online or by proxy, inter-caste and inter-cultural marriages, and the Islamic perspective on various wedding customs and celebrations. A substantial section is dedicated to the rights and responsibilities of both spouses within the marriage, covering financial obligations, the right to maintenance, the right to kind treatment, intimacy-related rulings, and the principles of conflict resolution within a Muslim household. The book discusses the grounds for and procedure of talaq or divorce, khula or the wife's request for dissolution, and the waiting period of iddah. Appendices include sample nikah contracts and a glossary of marriage-related Islamic terminology. This reference is widely used by imams, marriage counsellors, and Muslim families navigating the practical and religious dimensions of marriage.`,
    metaDescription: "Nikkah Kay Masail is a comprehensive Urdu Q&A guide on Islamic marriage rulings, covering nikah procedures, mahr, and spousal rights."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
