const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "tajwidi-para-2-qudrat-ullah-co",
    description: `Tajwidi Para 2 from Qudrat Ullah Company is a dedicated tajweed-formatted edition of the second juz of the Holy Quran, designed to make the rules of correct Quranic recitation visible and accessible to readers of all proficiency levels. This individual para format is particularly valuable for students who are working through the Quran systematically, allowing them to focus their tajweed study on one section at a time rather than carrying the complete mus-haf. The second para, beginning with Surah Al-Baqarah verse 142 and extending through Surah Al-Baqarah verse 252, contains some of the most frequently recited passages of the Quran, including the verses about changing the qiblah, the renewal of the covenant with the children of Israel, and the testing of Ibrahim.

Qudrat Ullah Company has established a strong reputation for producing quality Quran publications, and this tajwidi para reflects their commitment to both scholarly accuracy and practical usability. The tajweed markings are applied using a color-coded system that identifies the specific rules applicable to each letter and word, making it possible for readers to learn and reinforce their tajweed knowledge simply by reading the text. Rules such as idghaam, ikhfaa, iqlaab, izhaar, ghunnah, qalqalah, and the various categories of mudood are each assigned distinct colors or symbols, so the reader can immediately see which rule governs any given letter combination without needing to consult a separate tajweed reference.

The Arabic text is printed in a clear, well-spaced naskh script with full vowel marks and tajweed annotations that do not compromise the readability of the base text. The paper quality supports the color printing without bleeding or smudging, ensuring that the tajweed indicators remain clear over extended use. This single para format is lightweight and portable, making it convenient for students to carry to Quran classes, hifz sessions, or for personal revision. Teachers of tajweed frequently recommend individual para editions like this one because they allow students to concentrate on mastering the recitation of one section before moving on to the next. For anyone studying tajweed formally or independently, this second para from Qudrat Ullah Company provides an excellent study tool that combines the authentic Uthmani script with clear, accurate tajweed markings.`,
    metaDescription: "Tajwidi Para 2 by Qudrat Ullah Company with color-coded tajweed markings for the second juz of the Holy Quran in clear naskh script."
  },
  {
    slug: "tajwidi-para-set-qudrat-ullah-sc",
    description: `The complete Tajwidi Para Set from Qudrat Ullah Company in soft cover binding provides all thirty para of the Holy Quran in a dedicated tajweed-format edition, enabling readers to study and recite the entire Quran with clearly marked rules of proper recitation. This soft cover edition offers a practical and economical solution for individuals and institutions that want a full set of tajweed-marked paras without the additional cost and weight of hard cover binding. The set comprises thirty individually bound booklets, each containing one juz of the Quran with comprehensive tajweed annotations, allowing for focused study of each section while collectively covering the complete Quranic text.

The color-coded tajweed system employed in this set is consistent across all thirty paras, which is essential for effective learning, as readers develop familiarity with the color scheme and can apply it automatically as they progress from one para to the next. Each tajweed rule is assigned a specific color that appears whenever that rule applies to a letter or group of letters in the text. The rules covered include the full range of tajweed science: noon sakina and tanween rules (izhaar, idghaam, iqlaab, ikhfaa), meem sakina rules, mudood in all their categories, qalqalah, the rules of laam shamseeyah and laam qamareeyah, and the rules of stopping and starting. The color coding makes these rules immediately visible without requiring the reader to recall them from memory or consult a separate reference.

The soft cover binding keeps each para lightweight and flexible, which is particularly advantageous for students who need to carry specific paras to classes or study circles. The individual para format also distributes the Quranic text into manageable study units, supporting both sequential study programs and selective review of particular sections. Qudrat Ullah Company's printing quality ensures that the Arabic script is crisp, the vowel marks are clear, and the color coding is consistent and legible. This complete set is ideal for madrasahs and Islamic schools that use the para-by-para teaching method, for Quran study circles where participants focus on specific sections, and for individual readers who prefer the convenience and focus of single-para booklets. Having all thirty paras available in this format means that readers can always have the section they are currently studying in a compact, tajweed-annotated edition.`,
    metaDescription: "Complete 30-para tajweed Quran set in soft cover by Qudrat Ullah Company with consistent color-coded recitation rules across all juz."
  },
  {
    slug: "talaq-kay-masail",
    description: `Talaq Kay Masail is a focused Urdu-language reference work that addresses the Islamic legal rulings concerning divorce, one of the most consequential and frequently misunderstood areas of Muslim family law. The book provides comprehensive coverage of the topic, drawing upon the Quran, authentic hadith, and the established jurisprudence of the Hanafi school while also referencing relevant opinions from other schools of Islamic law where they contribute to a fuller understanding of the subject. Given the sensitivity and lifelong impact of divorce proceedings, this book aims to equip Muslims with accurate knowledge that can prevent both the careless use of divorce and the erroneous assumption that a divorce has occurred when it has not.

The book addresses the fundamental concepts that underpin the Islamic understanding of divorce, beginning with the definition and classification of divorce in Islamic law. It distinguishes between the different types of talaq: talaq-e-sunnah, which follows the prophetic method and is revocable during the waiting period, and talaq-e-bid'ah, which is an innovated form that, while contentious among scholars, has significant legal implications. The conditions under which each type occurs, the specific wording required or sufficient to establish a divorce, and the distinction between explicit and ambiguous pronouncements are all discussed with reference to classical and contemporary scholarly opinions.

Substantial sections of the book deal with the practical consequences of divorce, including the iddah (waiting period) that a divorced woman must observe, its duration under different circumstances, and the rights and obligations of both spouses during this period. The book covers matters of financial maintenance, housing arrangements, and the custody and guardianship of children resulting from the marriage. It also addresses khula (the woman's right to initiate dissolution), faskh-e-nikah (judicial annulment), and the rulings related to revocation of divorce during the iddah period. The author handles contemporary issues such as divorce pronounced through written messages, divorce in emotional states, the effect of conditional divorce statements, and the interaction of Islamic divorce law with modern legal systems. Written in clear and methodical Urdu, Talaq Kay Masail serves as an essential reference for scholars, students of Islamic law, qadis and muftis who issue legal verdicts, and educated Muslims who wish to understand their rights and responsibilities in this critical area of personal law.`,
    metaDescription: "A comprehensive Urdu reference on Islamic divorce law covering talaq types, iddah, khula, child custody, and contemporary divorce issues."
  },
  {
    slug: "talbeena-ajwa",
    description: `Talbeena with Ajwa date flavor brings together two significant sunnah foods into a single nourishing preparation that carries deep roots in Islamic tradition. Talbeena itself is a barley-based porridge that the Prophet Muhammad specifically recommended for the sick and grieving, describing it as a preparation that soothes the heart and relieves sorrow. Ajwa dates, grown in the blessed city of Madinah, hold a special status in Islamic tradition as well, with the Prophet identifying them as among the best of dates and recommending them for their protective and healing properties. The combination of these two sunnah foods creates a product that is both spiritually meaningful and nutritionally beneficial.

Barley, the primary ingredient in talbeena, is a whole grain that provides sustained energy through its complex carbohydrate content, along with dietary fiber that supports healthy digestion and gut function. It contains beta-glucan, a soluble fiber associated with cardiovascular health and blood sugar regulation. The addition of Ajwa date paste introduces natural sweetness along with a concentrated source of potassium, magnesium, iron, and B vitamins. Ajwa dates are particularly noted for their soft, almost melt-in-the-mouth texture and their rich, complex flavor with notes of caramel and dark fruit, which distinguishes them from other date varieties.

This Ajwa-flavored talbeena is prepared as a dry mix that can be easily reconstituted with warm water, milk, or a combination of both, depending on personal preference and dietary requirements. The preparation process is straightforward: the mix is stirred into hot liquid and allowed to thicken for a few minutes, producing a warm, comforting porridge with the distinctive taste of Ajwa dates woven throughout. The natural sweetness from the date paste means that additional sweetener is generally unnecessary, making it a wholesome option for those who wish to reduce refined sugar intake. This talbeena variant is suitable for breakfast, as a light evening meal, or as a restorative food during illness or recovery. Its combination of whole grain nutrition and sunnah significance makes it a meaningful addition to the diet of any Muslim household seeking to incorporate the prophetic dietary recommendations into daily life.`,
    metaDescription: "Talbeena with Ajwa date flavor combines two sunnah foods — barley porridge and Madinah Ajwa dates — into a nutritious, easy-to-prepare meal."
  },
  {
    slug: "talbeena-chocolate",
    description: `Talbeena in chocolate flavor offers a modern and appealing twist on the traditional sunnah food of barley porridge, making the prophetic dietary practice accessible and enjoyable for family members who might be hesitant about plain grain-based preparations. The Prophet Muhammad recommended talbeena, a preparation made from barley flour, as a comforting and healing food, and this chocolate-flavored adaptation preserves the nutritional core of the original while adding a flavor profile that is universally popular, especially among children and younger family members.

The nutritional foundation of this talbeena remains authentic barley, which provides complex carbohydrates for sustained energy release, significant amounts of dietary fiber for digestive health, and a range of essential minerals including selenium, manganese, and phosphorus. Barley's beta-glucan content contributes to cardiovascular wellness and helps maintain healthy cholesterol levels. The chocolate flavor component is achieved through the inclusion of cocoa, which itself carries nutritional benefits including antioxidants known as flavonoids, iron, magnesium, and a modest amount of caffeine that can provide a gentle, natural energy boost. The cocoa is balanced with natural sweeteners to create a pleasant chocolate taste without overwhelming the subtle, nutty flavor of the barley base.

Preparing this chocolate talbeena is simple and quick, requiring only the addition of hot milk or water to the prepared mix, with stirring until the desired consistency is reached. The result is a warm, creamy porridge with a rich chocolate aroma and taste that makes it feel like a treat rather than a health food. This makes it an effective vehicle for introducing the sunnah of consuming barley into households where family members might resist more traditional preparations. Children who might turn away from plain barley porridge are often enthusiastic about the chocolate version, allowing parents to provide the nutritional and spiritual benefits of talbeena in a form that children actually enjoy. The chocolate flavor also works well as a comforting evening snack or a warming breakfast during colder months, providing both the physical nourishment of whole grain barley and the emotional comfort that chocolate-flavored foods universally deliver.`,
    metaDescription: "Chocolate-flavored talbeena blends sunnah barley porridge with cocoa for a nutritious, comforting meal that appeals to children and adults alike."
  },
  {
    slug: "talbeena-kulfa",
    description: `Talbeena with kulfa flavor draws upon one of the most beloved traditional dessert traditions in South Asian Muslim culture, combining the nutritional wisdom of the prophetic sunnah with the rich, creamy taste profile that has made kulfa a cherished treat across generations. Kulfa, the traditional South Asian ice cream known for its dense texture and aromatic spice infusions, typically features notes of cardamom, saffron, pistachio, and rose water. This talbeena variant captures those distinctive kulfa flavors and incorporates them into the barley-based porridge that the Prophet Muhammad recommended for its healing and comforting properties.

The barley base of this talbeena provides the same nutritional benefits found in all authentic talbeena preparations: complex carbohydrates that deliver steady energy, beta-glucan fiber that supports heart health and digestion, and a complement of B vitamins and essential minerals. The kulfa flavoring adds the characteristic warmth of cardamom, the subtle luxury of saffron, and the fragrant sweetness of rose water, creating a taste experience that evokes the festive atmosphere of Eid gatherings and family celebrations while delivering wholesome everyday nutrition. The inclusion of these traditional flavorings also carries its own nutritional dimension, as cardamom is recognized for its digestive and anti-inflammatory properties, saffron contains compounds that support mood and cognitive function, and rose water has been used in traditional medicine for its calming effects.

This kulfa-flavored talbeena is prepared by adding the mix to warm milk or water, stirring until smooth, and allowing it to rest briefly to achieve the proper consistency. The prepared porridge develops a beautiful aroma as the cardamom and rose water notes are released by the heat, filling the kitchen with a fragrance that signals comfort and nourishment. It can be served warm for immediate enjoyment or allowed to cool slightly for those who prefer a thicker, more pudding-like consistency. The kulfa flavor makes this talbeena particularly appealing as a special occasion food during Ramadan evenings, as a treat for guests, or as a memorable way to introduce the sunnah of barley consumption to family and friends who might be unfamiliar with talbeena. It bridges the gap between traditional prophetic nutrition and the rich culinary heritage of Muslim South Asia.`,
    metaDescription: "Kulfa-flavored talbeena combines sunnah barley porridge with cardamom, saffron, and rose water flavors inspired by traditional South Asian dessert."
  },
  {
    slug: "talbeena-mango",
    description: `Talbeena with mango flavor introduces the tropical sweetness of one of the world's most popular fruits into the time-honored sunnah preparation of barley porridge. Mango holds special cultural significance in South Asian Muslim communities, where the arrival of mango season is celebrated with enthusiasm and the fruit features prominently in both everyday meals and festive occasions. This talbeena variant captures the essence of ripe, fragrant mango and weaves it into the wholesome barley base that the Prophet Muhammad recommended for its soothing and restorative properties.

The nutritional profile of this mango-flavored talbeena combines the well-documented health benefits of barley with the vitamin-rich contribution of mango. Barley provides sustained energy through its complex carbohydrates, supports digestive health through its fiber content, and contributes minerals such as selenium and phosphorus. Mango adds a significant dose of vitamin C, which supports immune function and enhances the body's absorption of the iron present in barley. Mango also provides vitamin A, which is essential for eye health and skin integrity, along with folate and various antioxidants that help protect cells from oxidative stress. The natural fruit sugars in mango provide sweetness without the need for refined sugars, making this talbeena variant a source of natural, whole-food sweetness.

The preparation follows the same simple process as other talbeena varieties: the dry mix is combined with warm milk or water and stirred until it reaches a smooth, porridge-like consistency. The mango flavor is most pronounced when the talbeena is prepared with milk, which complements the fruit flavor and adds protein and calcium to the meal. As the hot liquid hydrates the mix, the aroma of mango is released, creating an inviting and appetizing experience. This variant is particularly well-suited as a summer breakfast, when the bright, fruity flavor of mango pairs naturally with warm weather, though it remains enjoyable year-round as a nutritious and flavorful start to the day or a comforting evening meal. The mango flavor also makes this talbeena an excellent choice for children's meals, as the familiar and universally appealing taste of mango encourages young family members to embrace this sunnah food as part of their regular diet.`,
    metaDescription: "Mango-flavored talbeena blends sunnah barley with tropical mango, providing vitamin C, fiber, and natural sweetness in an easy-to-prepare porridge."
  },
  {
    slug: "talbeena-special",
    description: `Talbeena Special represents the premium tier of the talbeena product line, formulated with an enhanced blend of ingredients that maximizes both the nutritional value and the sensory experience of this sunnah barley preparation. The Prophet Muhammad recommended talbeena as a food that brings comfort to the heart and body, and this special edition honors that tradition by using carefully selected barley flour along with additional wholesome ingredients that complement and elevate the base recipe. The "special" designation reflects a higher concentration of beneficial ingredients and a more refined production process that results in a smoother texture and richer flavor compared to standard talbeena varieties.

The ingredient profile of Talbeena Special includes premium quality barley flour that has been finely milled for a smoother mouthfeel, combined with a carefully calibrated blend of complementary components. These may include premium dried fruits such as raisins and dates, nuts such as almonds and walnuts that contribute healthy fats and additional protein, and natural flavorings that create a complex, satisfying taste profile without relying on artificial additives. The inclusion of multiple nutrient-dense ingredients means that each serving of Talbeena Special delivers a broader spectrum of vitamins, minerals, and beneficial compounds than a plain barley preparation alone would provide.

The nutritional advantages of this enhanced formulation are significant. Barley provides the foundational complex carbohydrates and beta-glucan fiber, while the added nuts contribute omega-3 fatty acids, vitamin E, and additional minerals. Dried fruits bring concentrated sources of iron, potassium, and antioxidants. Together, these ingredients create a meal that provides sustained energy, supports cardiovascular health, aids digestion, and helps maintain stable blood sugar levels. The preparation remains straightforward, requiring only the addition of hot milk or water and a few minutes of stirring. The resulting porridge has a richer, more complex flavor and a more satisfying texture than basic talbeena, with visible pieces of fruit and nut that add both taste and visual appeal. This special edition is intended for those who wish to experience talbeena at its finest, whether as a daily nutritional supplement, a restorative food during recovery from illness, or a premium sunnah food for special occasions and gift-giving.`,
    metaDescription: "Talbeena Special is a premium sunnah barley porridge enriched with dried fruits and nuts for enhanced nutrition, richer flavor, and smoother texture."
  },
  {
    slug: "talbeena-strawberry",
    description: `Talbeena with strawberry flavor brings the bright, fruity character of one of the most widely enjoyed berries into the traditional sunnah preparation of barley-based porridge. Strawberries are recognized for their vibrant red color, their sweet-tart flavor profile, and their impressive nutritional credentials, particularly their high vitamin C content and antioxidant concentration. This talbeena variant merges the wholesome, comforting qualities of the barley base recommended by the Prophet Muhammad with the cheerful and appetizing flavor of strawberry, creating a preparation that is both spiritually grounded and sensorially appealing.

The barley foundation of this talbeena delivers the core nutritional benefits that make all talbeena preparations valuable: complex carbohydrates for sustained energy, beta-glucan soluble fiber for cardiovascular and digestive health, and essential minerals including manganese, selenium, and phosphorus. The strawberry flavor component contributes vitamin C at levels that significantly enhance the overall nutritional value of each serving, along with manganese, folate, and a class of antioxidants called anthocyanins that are responsible for the berry's red pigment and are associated with various health benefits including anti-inflammatory effects and cellular protection.

This strawberry-flavored talbeena is formulated as a dry mix that is simple to prepare by adding hot milk or water and stirring to the desired consistency. The strawberry flavor is most fully expressed when prepared with milk, which adds its own nutritional contribution of protein and calcium while creating a creamy base that complements the berry notes. As the mix hydrates, it develops a pleasant pinkish hue and releases a fruity aroma that makes the talbeena feel like an indulgent treat rather than a purely functional food. This visual and aromatic appeal makes it an effective introduction to the sunnah of barley consumption for family members who might be reluctant to try less visually exciting preparations. The strawberry flavor works especially well as a breakfast item, where its bright, cheerful character provides an uplifting start to the day, and it is also popular as an evening snack during Ramadan, when its light yet satisfying nature makes it suitable for the pre-dawn suhoor meal or the post-iftar period. Children are typically enthusiastic about this flavor, making it easier for parents to establish the sunnah of talbeena consumption as a regular family practice.`,
    metaDescription: "Strawberry-flavored talbeena combines sunnah barley porridge with fruity strawberry taste, rich in vitamin C, antioxidants, and beta-glucan fiber."
  },
  {
    slug: "talbeena-without-sugar",
    description: `Talbeena Without Sugar provides all the nutritional and sunnah benefits of traditional barley-based talbeena in a formulation that contains no added sugar, making it suitable for individuals who need to monitor their blood sugar levels, those following low-sugar dietary protocols, or anyone who prefers the natural, unadulterated taste of whole grain barley. The Prophet Muhammad recommended talbeena for its healing and comforting properties, and this unsweetened version allows consumers to experience the preparation in its most authentic and straightforward form, with the natural, mildly nutty flavor of barley as the primary taste.

Barley itself contains natural complex carbohydrates and a modest amount of natural sugars that are released slowly during digestion, providing energy without the rapid blood sugar spikes associated with refined sugars. The beta-glucan fiber in barley is particularly relevant for this sugar-free formulation, as research has demonstrated that beta-glucan helps moderate the post-meal rise in blood glucose levels, making barley an inherently blood-sugar-friendly grain. This means that even without added sweeteners, talbeena provides a satisfying and energizing meal that supports stable blood sugar rather than destabilizing it. The absence of added sugar also means fewer total calories per serving, which may be relevant for individuals managing their weight alongside their blood sugar.

This sugar-free talbeena can be prepared with water for the most austere preparation, or with milk for added protein, calcium, and a naturally creamy texture that provides its own subtle sweetness from lactose. Consumers who desire some sweetness without refined sugar can customize each serving by adding honey, which is itself a sunnah food, or by including fresh or dried fruits such as dates, raisins, or bananas, which provide natural sweetness along with additional nutrients. The versatility of this unsweetened base makes it suitable for both sweet and savory adaptations. Some consumers prepare it with a pinch of salt and serve it alongside savory dishes, while others add spices like cinnamon or cardamom to create an aromatic, naturally flavored porridge. This flexibility makes Talbeena Without Sugar the most adaptable variant in the product line, suitable for diabetics, individuals on ketogenic or low-carbohydrate dietary approaches, health-conscious consumers who avoid added sugars, and anyone who values the authentic taste of whole barley as a foundation for their own creative preparations.`,
    metaDescription: "Sugar-free talbeena offers authentic sunnah barley porridge with beta-glucan fiber and natural complex carbohydrates for blood sugar-conscious diets."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
