const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const descriptions = [
  {
    slug: "the-valley-came-alive",
    description: `The Valley Came Alive, originally authored by the eminent historian and exegete Hafiz Imaduddin Ibn Kathir, is a celebrated English-language work that brings to life the stories of the Prophets and their righteous communities as narrated in the Holy Quran. Drawing extensively from classical Islamic sources including the Quran itself, authenticated hadith collections, and the celebrated histories of earlier scholars such as Ibn Ishaq and Al-Tabari, Ibn Kathir weaves together a compelling narrative that covers the lives of Prophets Adam, Nuh, Ibrahim, Musa, Isa, and Muhammad (peace be upon them all), along with accounts of the righteous people who preceded and followed them. What distinguishes this work from other prophetic biographies is its meticulous adherence to authentic narrations and its refusal to include weak or fabricated Israelite traditions (Isra'iliyyat) that have crept into less careful works. Each prophetic story is presented not merely as historical narrative but as a source of spiritual guidance, demonstrating how the lessons of patience, faith, steadfastness, and complete trust in Allah remain profoundly relevant for Muslims living in any era. The English translation preserves the scholarly rigor and literary beauty of the original Arabic, making this invaluable heritage accessible to readers who may not read classical Arabic texts. Published by Darussalam, this edition features careful footnoting, cross-referencing of Quranic verses and hadith, and a comprehensive index that makes it a practical reference for students of Islamic knowledge. Whether used for personal study, family reading, or academic research, The Valley Came Alive stands as one of the most reliable and beautifully presented English works on prophetic history available today. Available now at Bab-ul-Fatah for Rs. 3,500 with delivery across Pakistan.`,
    metaDescription: "Buy The Valley Came Alive by Ibn Kathir — authentic English stories of the Prophets from Quran & Hadith. Order online at Bab-ul-Fatah Pakistan."
  },
  {
    slug: "brass-jaali-rehal-8-inch",
    description: `This exquisitely crafted Brass Jaali Rehal, standing at a compact 8 inches, is a beautifully designed Quran stand that combines traditional Islamic artistry with everyday practicality. Made from high-quality solid brass with an intricate jaali (lattice-cut) pattern, this rehal showcases the kind of ornamental metalwork that has been practiced in the Indian subcontinent for generations, particularly in the brass-working traditions of Moradabad and Delhi. The jaali design is not merely decorative — the open lattice pattern allows air circulation around the Holy Quran, helping to preserve the pages while adding an elegant visual dimension to your prayer space. At 8 inches in size, this rehal is ideally suited for standard-sized Quran editions (14x21 cm format), holding the book at a comfortable reading angle that reduces neck and back strain during extended recitation sessions. The weight of the solid brass construction provides excellent stability, preventing the stand from tipping over even on smooth surfaces, while four small rubberized or felt pads on the base protect your furniture from scratches. The brass finish develops a beautiful natural patina over time, or can be polished to maintain its original golden sheen. This rehal serves as both a functional worship accessory and a striking decorative piece that enhances the Islamic character of any room — be it a prayer area, living room, study, or office. It also makes a thoughtful and culturally significant gift for weddings, housewarmings, Ramadan, or Eid occasions. Available at Bab-ul-Fatah for Rs. 750, delivered across Pakistan.`,
    metaDescription: "Brass Jaali Rehal 8-inch Quran stand with intricate lattice design. Premium quality, perfect gift. Order online at Bab-ul-Fatah Pakistan."
  },
  {
    slug: "auratu-par-haram-magar-kiya",
    description: `Auratu par Haram magar Kiya? is a thought-provoking Urdu-language book that addresses one of the most frequently discussed topics in contemporary Islamic discourse — the rulings and boundaries concerning women in Islam. Written with scholarly authority and pastoral sensitivity, this book methodically examines what is genuinely prohibited for women according to the authentic sources of Islamic law (the Quran and verified Sunnah) while distinguishing these clear prohibitions from the many cultural restrictions and customary practices that have been incorrectly attributed to Islam over the centuries. The author systematically goes through key areas of women's life — including worship, social interaction, education, employment, travel, inheritance, marriage, and personal conduct — presenting the textual evidence from the primary sources before arriving at well-reasoned conclusions. A particularly valuable aspect of this work is how it separates established Shariah rulings from regional cultural norms that vary across Pakistan, India, the Arab world, and other Muslim-majority societies. Many practices that are assumed to be Islamic requirements are shown to be cultural innovations with no basis in authentic religious texts, while genuine Islamic rulings are explained with their wisdom and context. This approach empowers female readers to understand their actual rights and obligations in Islam, free from the burdens of cultural baggage, while also helping male readers correct common misconceptions. The Urdu prose is accessible enough for general readers while maintaining the scholarly precision expected of a serious Islamic text. This book is especially recommended for Islamic study circles, women's educational gatherings, and anyone seeking clarity on gender-related rulings in Islam. Available at Bab-ul-Fatah for Rs. 900.`,
    metaDescription: "Auratu par Haram magar Kiya — Urdu book on women's rulings in Islam. Separates Shariah from cultural practices. Order at Bab-ul-Fatah."
  },
  {
    slug: "islamic-dress-code-for-women",
    description: `Islamic Dress Code for Women, published by Darussalam, is a concise yet comprehensive guide that addresses the Islamic requirements and principles governing women's clothing and modesty (hijab). Grounded entirely in evidence from the Holy Quran and authenticated hadith of the Prophet Muhammad (peace be upon him), this booklet provides clear, unambiguous guidance on what constitutes proper Islamic dress for women, the wisdom behind these prescriptions, and common questions that arise in modern contexts. The book examines the relevant Quranic verses — particularly Surah An-Nur (24:31) and Surah Al-Ahzab (33:59) — with their classical exegetical explanations, along with the detailed hadith narrations from Sahih Al-Bukhari and Sahih Muslim that define the specific requirements of the female hijab. Topics covered include the definition of the awrah (parts of the body that must be covered), the conditions that make clothing Islamically acceptable, rulings on different types of garments including the niqab (face veil), guidelines for clothing in different situations (prayer, public, at home, among other women), and practical advice for Muslim women navigating modern fashion choices while maintaining Islamic modesty standards. The text also addresses contemporary debates around hijab with balanced scholarly arguments, helping readers form informed opinions based on evidence rather than emotional arguments. At just Rs. 450, this affordably priced booklet from Darussalam's respected publishing house makes an excellent resource for dawah purposes, women's study groups, new Muslims learning about Islamic practices, and parents educating their daughters about Islamic modesty. Available at Bab-ul-Fatah with delivery throughout Pakistan.`,
    metaDescription: "Islamic Dress Code for Women by Darussalam — Quran & Hadith based guide on hijab and modesty. Rs.450. Order at Bab-ul-Fatah Pakistan."
  },
  {
    slug: "suraj-kahaani",
    description: `Suraj Kahaani is a charming Urdu children's storybook that captures the imagination of young readers through an engaging narrative centered around the theme of the sun (suraj). Written specifically for Muslim children, this book uses storytelling as a vehicle for conveying Islamic values, moral lessons, and an appreciation for Allah's creation. The storybook format is particularly effective for children aged 4 to 10, as it presents Islamic concepts through relatable characters and situations rather than dry didactic instruction. The narrative style keeps children engaged while subtly weaving in lessons about gratitude to Allah, the wonders of the natural world as signs of divine creation (ayatullah), kindness to others, honesty, and the importance of daily Islamic practices such as prayer and remembering Allah. The Urdu language used is simple enough for young readers to follow independently or for parents to read aloud during bedtime storytelling sessions — a practice highly encouraged in Islamic tradition for building children's moral character and love for their faith. Illustrated children's books like Suraj Kahaani play a crucial role in Islamic home education, supplementing formal religious schooling by making Islamic learning an enjoyable and anticipated part of daily life rather than a chore. At only Rs. 400, this affordable title makes it easy for parents to build a small library of Islamic storybooks that their children will love returning to again and again. It also makes an excellent gift for children on Eid, birthdays, or as a reward for Quran memorization milestones. Order your copy from Bab-ul-Fatah with fast delivery across Pakistan.`,
    metaDescription: "Suraj Kahaani — Urdu Islamic storybook for children teaching moral values through engaging narrative. Ages 4-10. Order at Bab-ul-Fatah."
  },
  {
    slug: "ar-raheeq-al-makhtum-arabic",
    description: `Ar-Raheeq Al-Makhtum (The Sealed Nectar), authored by the distinguished scholar Safiur Rahman Mubarakpuri, is universally recognized as one of the most authoritative and beautifully written biographies of the Prophet Muhammad (peace be upon him) in the Arabic language. This particular edition presents the text in its original Arabic, making it accessible to readers proficient in classical Arabic who wish to engage directly with the scholarly prose that earned this work first prize in an international Seerah writing competition organized by the Rabitat al-Alam al-Islami (Muslim World League) in Makkah. The biography covers the complete life of the Prophet — from his noble lineage and birth in Mecca through the revelation of the Quran, the persecution of Muslims, the migration to Madinah, the establishment of the Islamic state, the major battles and treaties, the Farewell Pilgrimage, and his passing — with meticulous attention to chronological accuracy and source verification. Mubarakpuri's methodology strictly relies on narrations graded as authentic (sahih) or hasan (good) by the hadith scholars, carefully avoiding weak or fabricated reports that have found their way into less rigorous seerah works. The Arabic prose is known for its elegance and clarity, reflecting the author's deep mastery of the language while remaining accessible to educated Arabic readers. Scholars and students of Islamic studies across the Arab world regard Ar-Raheeq Al-Makhtum as an essential reference work, and it is widely used in Islamic universities, madrasas, and study circles as a primary seerah textbook. At Rs. 935, this Arabic edition offers exceptional value for such a respected scholarly work. Available at Bab-ul-Fatah with delivery throughout Pakistan.`,
    metaDescription: "Ar-Raheeq Al-Makhtum Arabic — prize-winning Seerah of Prophet Muhammad by Mubarakpuri. Original Arabic text. Order at Bab-ul-Fatah."
  },
  {
    slug: "questions-answers-on-the-mothers-of-the-believers",
    description: `Questions & Answers on the Mothers of the Believers is an informative English-language book that adopts a unique and highly effective Q&A format to explore the lives, virtues, and contributions of the wives of the Prophet Muhammad (peace be upon him) — the esteemed Mothers of the Believers (Ummahat al-Mu'minin). Each of the Prophet's wives, including Khadijah bint Khuwaylid, Aisha bint Abi Bakr, Hafsa bint Umar, Umm Salama, Zainab bint Jahsh, and others (may Allah be pleased with them all), is presented through a series of carefully researched questions and well-sourced answers that cover their backgrounds, marriages to the Prophet, their unique characteristics and virtues, their scholarly contributions to Islam, and their roles in preserving and transmitting the prophetic tradition. The Q&A format makes this book particularly engaging and easy to navigate, allowing readers to quickly find specific information about any of the Mothers of the Believers without having to read through lengthy continuous narrative. Each answer is supported by references to authentic hadith sources and classical Islamic scholarship, giving readers confidence in the accuracy of the information presented. The book addresses many common questions that Muslims have about the Prophet's marital life — including questions about the number of his wives, the reasons for each marriage, their relative ages, and their relationships with one another — with scholarly objectivity and sensitivity. This work serves as an excellent resource for Islamic study circles, women's educational programs, new Muslims seeking to understand this important aspect of prophetic history, and anyone interested in the significant role that these remarkable women played in early Islamic society. Available at Bab-ul-Fatah for Rs. 790 with delivery across Pakistan.`,
    metaDescription: "Questions & Answers on Mothers of the Believers — Q&A format exploring lives of Prophet's wives. Well-researched English book. Order Bab-ul-Fatah."
  },
  {
    slug: "rooh-azab-e-qabar-aur-sama-e-mauta",
    description: `Rooh Azab e Qabar Aur Sama e Mauta is a spiritually significant Urdu-language book by the renowned Islamic scholar and spiritual guide Abdul Rehman Kilani that addresses two of the most profound and unavoidable aspects of human existence — the experience of death (sama-e-maut) and the trials of the grave (azab-e-qabar). Drawing upon authenticated narrations from the Quran, Sahih Al-Bukhari, Sahih Muslim, and other reliable hadith collections, this book provides a detailed yet accessible account of what happens when a soul departs from the body, the questioning by the angels Munkar and Nakir, the conditions of the grave for the righteous versus the disobedient, and how one's actions in this worldly life directly determine their experience in the barzakh (the intermediate state between death and the Day of Judgment). Abdul Rehman Kilani is known for his ability to present complex theological and eschatological topics in a manner that touches the heart while remaining firmly grounded in authentic Islamic sources. His writing style in this work is particularly effective because it balances the awe-inspiring descriptions of the grave's realities with messages of hope and mercy for those who live according to Islamic principles. The book also includes practical guidance on what Muslims can do during their lifetime to prepare for a peaceful transition and a blessed experience in the grave — including regular remembrance of death, consistent performance of prayers, charity, maintaining family ties, and seeking Allah's forgiveness. This slim volume at Rs. 300 is an accessible spiritual read that serves as a powerful reminder of our ultimate destination. Available at Bab-ul-Fatah with nationwide delivery in Pakistan.`,
    metaDescription: "Rooh Azab e Qabar Aur Sama e Mauta by Abdul Rehman Kilani — Urdu book on death and grave trials from authentic Hadith. Order Bab-ul-Fatah."
  },
  {
    slug: "tafsir-ibn-e-kathir-6-vol-set-urdu",
    description: `Tafsir Ibn-e-Kathir (6 Volume Set) in Urdu is one of the most prestigious and comprehensive Quranic exegesis collections available in the Urdu language, presenting the monumental work of the great historian and exegete Hafiz Imaduddin Ismail Ibn Kathir (d. 774 AH) in an accessible Urdu translation. Originally composed in Arabic under the title "Tafsir al-Quran al-Azim," this tafsir is widely regarded as the most reliable and widely-studied Quranic commentary that prioritizes explanation through authentic hadith narrations and narrations from the Prophet's Companions and their successors (tafsir bil-ma'thur). This six-volume Urdu edition, published by Darussalam, covers the entire Quran from Surah Al-Fatiha to Surah An-Nas, providing for each verse its context of revelation (asbab al-nuzool), explanation of difficult vocabulary, relevant hadith narrations that elucidate the verse's meaning, references to related ayat elsewhere in the Quran, and occasional scholarly commentary on matters of fiqh (jurisprudence), aqeedah (theology), and historical context. Ibn Kathir's methodology is distinguished by his strict adherence to authentic narrations and his conscious rejection of weak or fabricated Israelite reports (Isra'iliyyat) that mar many lesser tafsir works. The Urdu translation renders the scholarly Arabic into clear, flowing prose that maintains the academic precision of the original while being comprehensible to educated Urdu readers. This six-volume set, with its durable hardcover binding and quality printing, represents a significant investment at Rs. 20,000 but serves as a lifelong reference for serious students of Quranic studies, Islamic scholars, imams, and anyone who wishes to understand the Quran at a profoundly deeper level. Available at Bab-ul-Fatah with careful packaging and delivery across Pakistan.`,
    metaDescription: "Tafsir Ibn-e-Kathir complete 6-volume Urdu set by Darussalam. Premium hardcover, authentic Quranic commentary. Order at Bab-ul-Fatah."
  },
  {
    slug: "khawateen-aur-ramadan-ul-mubarak",
    description: `Khawateen Aur Ramadan ul Mubarak, authored by Abu Ans Hussain Bin Ali, is a dedicated Urdu guide specifically written to help Muslim women maximize the spiritual benefits of the blessed month of Ramadan while practically managing their unique responsibilities and challenges during this intensive period of worship. This focused guide recognizes that women often face distinct situations during Ramadan — including managing household iftar and suhoor preparations, caring for children while trying to perform taraweeh prayers, dealing with the physical demands of fasting during pregnancy or menstruation, and maintaining their daily household duties alongside increased worship — and provides tailored, practical guidance for each of these scenarios. The book covers essential topics including the fiqh (rulings) of fasting specific to women — such as making up missed fasts, the fiqh of fasting during pregnancy and nursing, and the special exemptions granted to women — along with spiritual advice on how to make the most of Laylat al-Qadr, strategies for Quran recitation that fit into a busy woman's schedule, and suggested daily routines that balance worship with family responsibilities. The author draws upon authentic hadith sources and the guidance of classical scholars to present rulings that are both reliable and practically applicable. Particularly valuable are the chapters on involving children in Ramadan activities, making family iftar and suhoor spiritually meaningful occasions, and maintaining marital harmony during the physically demanding fasting days. At just Rs. 390, this affordable guide makes an excellent Ramadan preparation resource for individual reading, women's study circles, or as a thoughtful gift to distribute among female family members and friends before the holy month begins. Available at Bab-ul-Fatah with delivery throughout Pakistan.`,
    metaDescription: "Khawateen Aur Ramadan ul Mubarak — Urdu guide for women on fasting rulings, worship tips, and managing Ramadan. Rs.390 at Bab-ul-Fatah."
  },
  {
    slug: "kalma-e-tayyaba-stainless-steel",
    description: `This Kalma-e-Tayyaba wall art piece, crafted from premium-grade stainless steel, is a stunning Islamic home decor item that proclaims the foundational declaration of Islamic faith — the Kalma Tayyaba (La ilaha illallah Muhammadur Rasulullah) — in an elegant, contemporary metallic design. The stainless steel construction ensures exceptional durability and longevity, resisting tarnishing, rusting, and fading far better than painted or wooden alternatives, making it suitable for long-term display in any room of the house including areas with higher humidity such as bathrooms or kitchens. The polished or brushed steel finish creates a sophisticated, modern aesthetic that complements a wide range of interior design styles — from minimalist and contemporary to traditional and eclectic — while the Arabic calligraphy is rendered with careful attention to proper letter formation and artistic proportions that honor the sanctity of the words. Measuring a generous display size, this piece commands attention on any wall and serves as a constant visual reminder of the core Islamic belief in the oneness of Allah and the prophethood of Muhammad (peace be upon him). The stainless steel material also gives this piece a subtle reflective quality that catches and plays with ambient lighting, adding visual depth to your wall. Installation is straightforward, typically requiring just two or three nails or screws depending on the size, and the relatively lightweight construction means it can be hung on most wall types without special anchors. This Kalma-e-Tayyaba piece makes an exceptional gift for housewarmings, weddings, Ramadan, Eid, or any occasion where a meaningful Islamic present would be appreciated. Available at Bab-ul-Fatah for Rs. 3,490 with secure packaging and delivery across Pakistan.`,
    metaDescription: "Kalma-e-Tayyaba stainless steel Islamic wall art — premium metal calligraphy decor. Durable, modern design. Order at Bab-ul-Fatah Pakistan."
  },
  {
    slug: "need-of-creed-series-the-last-day-beyond-death",
    description: `The Need of Creed Series: The Last Day Beyond Death is an English-language book from Darussalam's acclaimed "Need of Creed" (Darurat al-Aqidah) series that focuses specifically on Islamic eschatology — the events and realities that follow death according to authentic Islamic teachings. This volume provides a detailed, evidence-based account of what Islam teaches about the Day of Judgment (Yawm al-Qiyamah), the signs preceding it, the resurrection of the dead, the gathering of all creation for divine reckoning, the weighing of deeds (Mizan), the bridge over Hell (Sirat), the intercession (Shafa'ah), and the final destinations of Paradise (Jannah) and Hellfire (Jahannam). Each topic is thoroughly supported with evidence from the Quran and authenticated hadith narrations, primarily from Sahih Al-Bukhari and Sahih Muslim, along with relevant scholarly commentary from classical Islamic theologians. The "Need of Creed" series is specifically designed to present Islamic theology (aqeedah) in a manner that is both academically rigorous and accessible to general English-speaking readers, and this volume on the Last Day is particularly important because belief in the Hereafter is one of the six pillars of Islamic faith without which a person's belief is considered incomplete. The book also addresses contemporary misconceptions about the afterlife and provides reasoned responses to common doubts and questions raised by skeptics. The clear English prose and systematic presentation make this work suitable for individual study, Islamic school curricula, dawah conversations, and study group discussions. At Rs. 350, this affordable volume makes essential knowledge about the afterlife accessible to everyone. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Need of Creed: The Last Day Beyond Death — Islamic eschatology from Quran & Hadith. Signs of Qiyamah, Afterlife explained. Order Bab-ul-Fatah."
  },
  {
    slug: "islam-mein-bunyaadi-haqooq",
    description: `Islam mein Bunyaadi Haqooq (Fundamental Rights in Islam) is a compact and affordable Urdu booklet that systematically presents the comprehensive framework of rights and responsibilities that Islam establishes for individuals and society. Published by Darussalam, this booklet covers the rights that Islam guarantees to every human being — including the right to life, dignity, property, freedom of religion, justice, and equality before the law — while also detailing the specific mutual rights between various relationships such as husband and wife, parents and children, siblings, neighbors, employers and employees, and rulers and citizens. The book draws its content directly from the primary sources of Islamic law — the Holy Quran and the authenticated hadith of the Prophet Muhammad (peace be upon him) — presenting each right with its textual evidence so that readers can verify the information themselves. What makes this work particularly valuable is its demonstration that many of the rights commonly attributed to modern Western legal and human rights frameworks were in fact established by Islam over fourteen centuries ago. The rights of women, laborers, prisoners of war, religious minorities, and animals are all addressed with specific textual references, providing a comprehensive picture of Islam's progressive and humanitarian legal vision. The Urdu prose is straightforward and concise, making this booklet accessible to readers of all educational backgrounds. At only Rs. 180, it represents the most affordable entry point into Darussalam's catalog and serves as an excellent dawah tool for introducing Islam's comprehensive rights framework to both Muslims and non-Muslims. Ideal for mass distribution in mosques, schools, and community centers. Available at Bab-ul-Fatah with delivery throughout Pakistan.`,
    metaDescription: "Islam mein Bunyaadi Haqooq — Urdu booklet on fundamental rights in Islam for all relations. Quran & Hadith based. Just Rs.180 at Bab-ul-Fatah."
  },
  {
    slug: "excellence-of-patience-and-gratefulness",
    description: `Excellence of Patience and Gratefulness is a significant English-language Islamic book that provides a thorough scholarly examination of two of the most important spiritual qualities in Islam — patience (sabr) and gratefulness (shukr). This comprehensive work, published in a high-quality hardcover edition, draws upon the Holy Quran, authenticated collections of prophetic hadith, and the classical works of Islamic scholars to present a complete understanding of what patience and gratitude truly mean in the Islamic context, how they are interconnected, and how cultivating these qualities transforms every aspect of a Muslim's life. The book meticulously categorizes the different types of patience mentioned in Islamic sources — patience in obeying Allah, patience in refraining from sin, and patience in accepting Allah's decree (including illness, loss, hardship, and adversity) — with numerous Quranic verses and hadith narrations illustrating each category. Similarly, the discussion of gratefulness goes far beyond a simple admonition to say "Alhamdulillah," exploring how true gratitude involves recognizing every blessing as a gift from Allah, using those blessings in ways that please the Giver, and maintaining a grateful heart even during difficult times. The text is enriched with inspiring stories from the lives of the Prophets, the Companions of the Prophet Muhammad (peace be upon him), the righteous predecessors (Salaf al-Saliheen), and the great scholars of Islamic history, demonstrating how these spiritual giants practically embodied patience and gratitude in their own lives. At Rs. 3,500, this hardcover edition offers substantial scholarly content that serves as both a personal spiritual development guide and a valuable reference for Islamic study circles and academic research. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Excellence of Patience and Gratefulness — comprehensive English book on Sabr & Shukr from Quran & Hadith. Hardcover. Order at Bab-ul-Fatah."
  },
  {
    slug: "imam-ahmed-bin-hanbal-ki-zindgi-kay-sunhery-waqyat",
    description: `Imam Ahmed bin Hanbal ki Zindgi kay Sunhery Waqyat (Golden Events from the Life of Imam Ahmad bin Hanbal) is a captivating Urdu biography that brings to life the extraordinary story of one of Islam's most revered scholars and the founder of the Hanbali school of Islamic jurisprudence. Published by Darussalam Pakistan, this book focuses on the most remarkable and inspiring episodes (sunhery waqyat — golden events) from Imam Ahmad's life, presenting them in an engaging narrative style that makes scholarly history accessible and emotionally moving for general Urdu readers. The biography covers the key phases of Imam Ahmad's life — from his birth in Baghdad in 164 AH, his rigorous pursuit of knowledge under the greatest scholars of his time including Imam Al-Shafi'i, his legendary memory that allowed him to memorize over a million hadith narrations, and most dramatically, his unwavering stand during the mihnah (inquisition) when he was imprisoned and tortured for refusing to accept the state-sponsored theological position that the Quran was created. His steadfastness during this trial became one of the most celebrated examples of scholarly courage and principled resistance in Islamic history. The book also highlights his personal piety, his detachment from worldly wealth despite being one of the most sought-after scholars of his era, his devotion to night prayers and recitation of the Quran, and his deep compassion for the poor and suffering. His monumental work, the Musnad Ahmad (one of the largest hadith collections ever compiled), is discussed in the context of his lifelong dedication to preserving the prophetic tradition. This biography at Rs. 2,500 inspires readers with the example of a scholar who placed truth above comfort, faith above position, and divine pleasure above everything else. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Imam Ahmad bin Hanbal ki Zindgi kay Sunhery Waqyat — Urdu biography of the great Imam's life, trials, and scholarship. Order at Bab-ul-Fatah."
  }
];

async function main() {
  let updated = 0;
  for (const item of descriptions) {
    try {
      await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log('Updated:', item.slug);
      updated++;
    } catch (e) {
      console.error('FAILED:', item.slug, e.message);
    }
  }
  await prisma.$disconnect();
  console.log(`\nDone: ${updated}/15 products updated`);
}

main().catch(console.error);
