const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "the-beautiful-names-attributes-of-allah",
    description: `The Beautiful Names and Attributes of Allah is a comprehensive English-language reference work that provides detailed explanations of the names and attributes (asmaa was-sifaat) by which Allah has revealed Himself in the Quran and through the authentic sayings of the Prophet Muhammad. The study of Allah's names and attributes occupies a central position in Islamic theology, as a correct understanding of who Allah is forms the foundation of all worship, spiritual development, and moral conduct in Islam. This book undertakes a thorough examination of this vital subject, making the classical scholarship on asmaa was-sifaat available to English-speaking Muslims who may not have direct access to the Arabic-language source materials.

The book examines each of Allah's names individually, discussing the linguistic meaning of the name in Arabic, the theological implications of the attribute it describes, and the practical effects that believing in this attribute should have on a Muslim's thinking and behavior. For names such as Ar-Rahman (The Most Merciful) and Ar-Raheem (The Especially Merciful), the book explores the nuances that distinguish these related attributes and discusses how a correct understanding of divine mercy should influence a Muslim's relationship with Allah and with fellow human beings. For names such as Al-Aleem (The All-Knowing), the book discusses the scope and implications of divine knowledge, including what it means for Allah's knowledge to encompass all things past, present, and future, and how this belief should affect a Muslim's sense of accountability and trust in Allah's wisdom.

The book addresses the methodological principles that govern the correct understanding of Allah's names and attributes, following the approach of the righteous predecessors (salaf al-salih) in affirming what Allah has affirmed for Himself without distortion, denial, or likening to creation. The author explains the four principles established by the early scholars: affirming the names and attributes as they have been mentioned in the texts, understanding them in their apparent meaning without imposing figurative interpretations, acknowledging that the reality of how these attributes are is beyond human comprehension, and refraining from drawing comparisons between Allah's attributes and the attributes of created beings. The book also addresses common misconceptions and errors related to asmaa was-sifaat, including the tendency to over-allegorize divine attributes, the error of anthropomorphism, and the balance between hope and fear that proper knowledge of Allah's names should produce. This work serves as a valuable reference for students of Islamic theology, for imams and teachers who need a reliable English source for explaining Allah's names, and for individual Muslims who want to deepen their understanding of their Creator through a systematic study of His most beautiful names.`,
    metaDescription: "A comprehensive English reference on Allah's names and attributes with theological analysis and the methodology of the righteous predecessors."
  },
  {
    slug: "the-beautiful-names-of-allah",
    description: `The Beautiful Names of Allah is a focused English-language study that approaches the subject of asmaa was-sifaat through a devotional and contemplative lens, emphasizing the spiritual benefits of knowing and reflecting upon Allah's names. While scholarly works on the subject tend to emphasize theological precision and the refutation of errors, this book prioritizes the experiential dimension of engaging with the divine names, guiding readers toward a deeper emotional and spiritual connection with Allah that emerges from understanding what His names reveal about His nature and His relationship with His creation. The approach makes this book complementary to more technical theological treatments of the same subject.

The book is structured around the well-known hadith in which the Prophet Muhammad stated that Allah has ninety-nine names, and whoever enumerates them will enter Paradise. For each name, the book provides not only the linguistic meaning and theological significance but also a contemplative reflection designed to help the reader internalize the meaning and allow it to transform their consciousness. The reflections address questions such as how awareness of Allah as Al-Hakeem (The All-Wise) should change the way a person responds to life's difficulties, how knowing Allah as Al-Qareeb (The Near) should affect one's experience of loneliness or despair, and how understanding Allah as Ash-Shakoor (The Appreciative) should influence a person's attitude toward their own deeds and accomplishments.

The book differs from other works on asmaa was-sifaat through its incorporation of practical spiritual exercises. For each name, the author suggests specific supplications that incorporate the name, reflections that can be used in daily meditation, and behavioral changes that logically flow from believing in the attribute described. For example, the section on Ar-Razzaq (The Provider) includes not only an explanation of divine provision but also practical guidance on how to overcome anxiety about sustenance through trust in Allah and concurrent practical effort. The book also includes a section on the relationship between Allah's names and the human spiritual journey, discussing how different names are particularly relevant at different stages of spiritual development. The English prose is warm and accessible, written for a general Muslim readership without requiring specialized theological background. This book is ideal for readers who want to combine knowledge of Allah's names with a practical spiritual practice, for study circles that focus on spiritual development, and as a gift for new Muslims, young people, or anyone who is beginning their journey into a deeper understanding of Islamic spirituality. The devotional approach makes it suitable for daily reading and reflection, with each name's treatment designed to be read and contemplated in a single sitting.`,
    metaDescription: "A devotional English guide to Allah's ninety-nine names emphasizing spiritual reflection and practical transformation through divine attributes."
  },
  {
    slug: "the-biography-of-abu-bakr-as-siddeeq-ra",
    description: `The Biography of Abu Bakr As-Siddeeq (R.A) is an English-language account of the life of the first caliph of Islam, the closest companion of the Prophet Muhammad, and one of the most revered figures in Islamic history. Abu Bakr's title "As-Siddeeq" (The Truthful) was given to him in recognition of his immediate and unwavering acceptance of the Prophet's account of the Night Journey (Isra and Miraj), when even some Muslims initially doubted the event. This biography traces his life from his birth in Makkah into the respected Quraysh tribe, through his early acceptance of Islam, his decades of companionship with the Prophet, his brief but enormously consequential caliphate, and his death.

The book provides detailed coverage of Abu Bakr's role during the Makkan period of Islam, including his use of his considerable wealth to support the Muslim community, his manumission of enslaved Muslims, the physical persecution he endured, his migration alongside the Prophet to Madinah, and his presence at all the major events of the prophetic era. His relationship with the Prophet Muhammad is examined thoroughly, drawing upon hadith narrations that reveal the depth of their friendship, the Prophet's trust in Abu Bakr's judgment, and the Prophet's indication that Abu Bakr was his chosen successor. The book also covers Abu Bakr's family life, his business career, and his personal character traits, including his humility, his compassion, his decisive nature, and his exceptional memory of the Quran.

The section on Abu Bakr's caliphate, which lasted approximately two years from 632 to 634 CE, receives extensive treatment, as the events of this period had a profound and lasting impact on the course of Islamic history. The book covers the challenges Abu Bakr faced immediately upon assuming leadership, including the wave of apostasy (ridda wars) that threatened to dissolve the Islamic state, the refusal of certain tribes to pay zakat, and the emergence of false prophets claiming divine revelation. Abu Bakr's decisive response to these crises, his insistence on fighting those who separated prayer from zakat despite the counsel of senior companions to show leniency, and his ultimate success in preserving the unity and integrity of the Islamic state are all documented in detail. The book also covers his initiation of the campaign to compile the Quran into a single written volume, a decision of incalculable significance for the preservation of Islamic scripture. The biography draws upon authentic historical sources and is written in clear English that makes the material accessible to general readers, students of Islamic history, and anyone who wishes to understand the life and legacy of the man whom the Prophet Muhammad described as his most beloved companion.`,
    metaDescription: "An English biography of Abu Bakr As-Siddeeq (R.A) covering his life from early Islam through his caliphate, the Ridda wars, and Quran compilation."
  },
  {
    slug: "the-biography-of-ali-ibn-abi-talib-ra-2-vol-set",
    description: `The Biography of Ali Ibn Abi Talib (R.A) in this two-volume set provides a comprehensive English account of one of the most important and multifaceted figures in Islamic history. Ali ibn Abi Talib was the cousin and son-in-law of the Prophet Muhammad, the fourth Rightly Guided Caliph, a towering scholar of Islamic jurisprudence, a renowned warrior, and a figure of immense spiritual significance. The two-volume format allows the full scope of Ali's remarkable life to be treated with the thoroughness it deserves, dedicating sufficient space to each major phase and aspect of his career without the compression that a single volume would require.

The first volume covers Ali's early life, beginning with his birth inside the Kaabah (a distinction unique to him among all human beings), his upbringing in the Prophet's household from a young age, and his status as one of the earliest converts to Islam. The volume provides detailed coverage of his participation in all the major battles of the prophetic era, where he distinguished himself as a warrior of extraordinary courage and skill. His marriage to the Prophet's daughter Fatimah, his family life, and his role within the Muslim community during the caliphates of Abu Bakr, Umar, and Uthman are all thoroughly documented. The first volume also addresses Ali's renowned scholarship, his contributions to the development of Islamic jurisprudence, and the collection of his sermons, letters, and sayings that form the Nahj al-Balagha, one of the masterpieces of Arabic prose.

The second volume is devoted primarily to Ali's caliphate, one of the most complex and consequential periods in Islamic history. The events surrounding his succession following Uthman's assassination, the challenges posed by Muawiyah ibn Abi Sufyan, the Battle of the Camel involving Aisha, Talhah, and Zubayr, the Battle of Siffin, and the emergence of the Kharijite movement are all treated with scholarly rigor and narrative skill. The author draws upon multiple historical sources to present a balanced account of these contested events, acknowledging the complexity of the situation and the sincerity of the various parties while maintaining commitment to historical accuracy. The volume concludes with Ali's assassination and its aftermath, including the brief caliphate of his son Hasan. Throughout both volumes, the author provides contextual analysis that helps readers understand the political, social, and theological dimensions of the events described. The English prose is scholarly yet accessible, supported by references to primary sources including hadith collections, historical chronicles, and early biographical works. This two-volume set is an essential reference for serious students of Islamic history, for researchers studying early Islamic political development, and for general readers who want a thorough and balanced understanding of one of the most significant figures in human history.`,
    metaDescription: "A 2-volume English biography of Ali ibn Abi Talib (R.A) covering his life, caliphate, battles, scholarship, and assassination with scholarly analysis."
  },
  {
    slug: "the-biography-of-imam-abu-dawood",
    description: `The Biography of Imam Abu Dawood is an English-language account of the life and scholarly contributions of Imam Abu Dawood Sulayman ibn al-Ash'ath al-Azdi as-Sijistani, one of the most prominent scholars of hadith in Islamic history and the compiler of Sunan Abi Dawood, one of the six canonical hadith collections in Sunni Islam. Imam Abu Dawood's work has been an indispensable reference for Islamic jurisprudence for over twelve centuries, consulted by scholars and jurists across all schools of Islamic law to determine the legal rulings derived from the prophetic tradition. This biography provides English-speaking readers with a detailed portrait of the man behind this monumental compilation.

The book traces Imam Abu Dawood's life from his birth in Sijistan (a region in present-day eastern Iran and southwestern Afghanistan) through his extensive educational journey, which took him across the Muslim world in pursuit of hadith knowledge. His travels to Makkah, Madinah, Basrah, Kufah, Baghdad, Damascus, and other centers of Islamic scholarship are documented, along with his studies under the most eminent hadith scholars of his generation. The book provides information about his teachers, numbering in the hundreds, and his own students, who included some of the most important scholars of the subsequent generation. His methodology in compiling Sunan Abi Dawood is examined in detail, explaining how he selected hadith for inclusion based on their relevance to jurisprudential rulings and his rigorous standards for evaluating the reliability of narrators.

The biography also covers Imam Abu Dawood's personal character and scholarly ethics, which earned him the respect of his contemporaries and subsequent generations. His humility, his devotion to worship, his scrupulousness in reporting hadith, and his willingness to acknowledge the limitations of his own work are all documented through reports from his students and contemporaries. The book discusses the distinctive features of Sunan Abi Dawood that set it apart from the other canonical collections, including its organization by legal topics, the inclusion of hadith that illuminate the reasoning behind legal rulings, and Imam Abu Dawood's practice of mentioning the various opinions of scholars regarding the implications of each hadith. The historical context of hadith scholarship in the third century of Islam is discussed, providing readers with an understanding of the intellectual environment in which Imam Abu Dawood worked. Written in clear English with appropriate scholarly apparatus including references to Arabic source materials, this biography serves as an introduction to the life and work of a scholar whose contributions continue to shape Islamic legal thought and practice in every Muslim community around the world.`,
    metaDescription: "An English biography of Imam Abu Dawood tracing his scholarly journey, hadith compilation methodology, and the enduring significance of Sunan Abi Dawood."
  },
  {
    slug: "the-biography-of-imam-ahmad-bin-hanbal-ra",
    description: `The Biography of Imam Ahmad bin Hanbal (R.A) is an English-language account of the life of Ahmad ibn Hanbal, one of the most important and revered scholars in the history of Islam and the founder of the Hanbali school of Islamic jurisprudence. Imam Ahmad's life story is remarkable not only for his intellectual achievements but for the extraordinary personal trials he endured for his commitment to orthodox Islamic belief during the mihna (inquisition) instituted by the Abbasid caliph al-Ma'mun, who sought to impose the Mu'tazilite theological position that the Quran was created. Imam Ahmad's steadfast refusal to accept this position, despite years of imprisonment and flogging, established him as one of the greatest defenders of traditional Sunni theology and earned him a permanent place of honor in Islamic history.

The book traces Imam Ahmad's early life in Baghdad, his extensive pursuit of hadith knowledge that took him to Kufah, Basrah, the Hijaz, Yemen, and Syria, and his studies under the most prominent scholars of his era. The sheer scale of his hadith scholarship is conveyed through the documentation of his teachers, estimated at over three hundred, and his students, who included many of the leading scholars of the next generation. The book provides detailed information about his compilation of the Musnad, one of the largest hadith collections ever assembled, containing approximately thirty thousand hadith arranged according to the narrator who reported them from the Prophet Muhammad.

The section on the mihna is the emotional and spiritual center of the biography. The book provides a detailed account of the theological controversy that led to the inquisition, the caliphal attempts to compel Imam Ahmad's compliance, the support he received from ordinary Muslims during his imprisonment, his eventual vindication, and the lasting impact of his resistance on the development of Sunni theology. The book also covers Imam Ahmad's contributions to Islamic jurisprudence, his distinctive legal methodology that prioritized hadith evidence over analogical reasoning, and the development of the Hanbali school after his death. His personal character, including his ascetic lifestyle, his devotion to worship, his compassion for the poor, and his rigorous personal standards, is documented through reports from his students and contemporaries. The English prose brings this extraordinary life to vividness while maintaining scholarly precision, making this biography accessible to general readers and valuable for students and researchers of Islamic intellectual history.`,
    metaDescription: "An English biography of Imam Ahmad bin Hanbal (R.A) covering his hadith scholarship, the mihna trial, and the Hanbali school's founding."
  },
  {
    slug: "the-biography-of-imam-at-tirmidhi",
    description: `The Biography of Imam At-Tirmidhi is an English-language account of the life of Muhammad ibn Isa ibn Sawrah at-Tirmidhi, the compiler of Jami at-Tirmidhi, one of the six canonical hadith collections in Sunni Islam. Imam at-Tirmidhi's collection holds a unique position among the canonical works because of its distinctive focus on the jurisprudential implications of hadith and its systematic grading of narrations based on their authenticity, making it one of the most practically useful references for Islamic legal scholarship. This biography provides English-speaking readers with insight into the life, methodology, and lasting contributions of this important scholar.

The book traces Imam at-Tirmidhi's origins in Termez (in present-day Uzbekistan), his extensive travels in pursuit of hadith knowledge, and his studies under the major scholars of his generation in Khurasan, Iraq, and the Hijaz. His teachers included Imam al-Bukhari, under whom he studied for an extended period, and numerous other prominent hadith masters. The biography documents his scholarly credentials, the scope of his hadith narrations, and the recognition he received from his contemporaries, who acknowledged his exceptional memory, his analytical precision, and his deep understanding of the jurisprudential implications of the narrations he collected.

The central section of the biography examines the distinctive characteristics of Jami at-Tirmidhi that distinguish it from the other canonical collections. Imam at-Tirmidhi's methodology of grading hadith as sahih (authentic), hasan (good), or da'if (weak) was more systematic and explicit than that of most of his contemporaries, and the book explains his criteria for each grade and provides examples of his grading decisions. His practice of identifying which legal ruling each hadith supports, and of noting the different opinions of scholars regarding the implications of each narration, makes Jami at-Tirmidhi particularly valuable for jurists. The book also discusses the companion work that Imam at-Tirmidhi compiled on the characteristics and defects of hadith narrators, titled al-'Ilal as-Saghir, which demonstrates his deep expertise in the science of narrator evaluation. The biography covers Imam at-Tirmidhi's personal character, including reports of his generosity, his physical afflictions, and his eventual death. His legacy as a hadith scholar whose work continues to be cited in every discussion of Islamic jurisprudence is assessed, providing readers with an understanding of why Jami at-Tirmidhi earned its place among the six canonical collections. Written in accessible English with references to primary Arabic sources, this biography serves students, scholars, and general readers interested in the scholarly tradition that preserved the prophetic heritage.`,
    metaDescription: "An English biography of Imam at-Tirmidhi covering his hadith grading methodology and Jami at-Tirmidhi's jurisprudential focus and scholarly legacy."
  },
  {
    slug: "the-biography-of-imam-az-zuhri",
    description: `The Biography of Imam Az-Zuhri is an English-language account of the life of Muhammad ibn Muslim ibn Ubaydullah ibn Shihab az-Zuhri, one of the most important scholars of the generation following the companions of the Prophet Muhammad (the tabi'in) and a pivotal figure in the development of Islamic hadith scholarship, Islamic jurisprudence, and Islamic historiography. Imam az-Zuhri's significance in Islamic intellectual history is difficult to overstate, as he served as a crucial bridge between the companion generation and the scholarly tradition that followed, transmitting an enormous body of knowledge from the companions to the scholars who would compile the great canonical works of Islam.

The book traces Imam az-Zuhri's life in Madinah, where he was born into a family of the Quraysh tribe and grew up in the city of the Prophet during a period when many companions were still alive. His extraordinary access to companion narrations, his prodigious memory, and his dedicated pursuit of knowledge from an early age made him the preeminent hadith scholar of his generation. The biography documents his studies under numerous companions and senior tabi'in, his network of students who would themselves become leading scholars, and his role as an authoritative reference for hadith, fiqh, and historical knowledge throughout the Muslim world. The book provides specific information about his teachers and students, highlighting the remarkable scholarly chain that connects the prophetic era to the great compilations of the third century.

The book examines Imam az-Zuhri's scholarly methodology and his contributions to the development of the various Islamic sciences. In hadith, he played a critical role in establishing the systematic collection and verification of prophetic narrations, transitioning the discipline from an informal practice of sharing individual narrations to a structured science with rigorous standards. In fiqh, his legal opinions were widely respected and cited, and the book discusses his approach to deriving rulings from the primary texts. In historiography, his works on the prophetic biography and early Islamic history were among the first systematic treatments of these subjects and served as source material for later historians including Ibn Ishaq and Ibn Hisham. The biography also discusses the criticism and praise that Imam az-Zuhri received, addressing the nuanced scholarly discussion about his practice of writing hadith versus relying on memory, and providing a balanced assessment of his scholarly standing. The English prose makes this complex material accessible to readers who may not have a background in Islamic studies while maintaining the academic rigor appropriate to a scholarly biography. This book is valuable for understanding the transmission of Islamic knowledge across generations and the foundational role that scholars like az-Zuhri played in preserving the religious heritage of Islam.`,
    metaDescription: "An English biography of Imam az-Zuhri, the pivotal tabi'i scholar who bridged the companion generation to later hadith and fiqh traditions."
  },
  {
    slug: "the-biography-of-imam-bukhaaree",
    description: `The Biography of Imam Bukhaaree is an English-language account of the life of Muhammad ibn Ismail ibn Ibrahim al-Bukhari, the compiler of Sahih al-Bukhari, the most authoritative collection of hadith in Sunni Islam and one of the most revered books in the entire Muslim literary tradition. Imam al-Bukhari's work is considered the most authentic book after the Quran, and his personal story is inseparable from the monumental achievement that bears his name. This biography provides a comprehensive portrait of the scholar whose dedication to the preservation of authentic prophetic traditions set standards of scholarly rigor that continue to define Islamic hadith science.

The book traces Imam al-Bukhari's birth in Bukhara (in present-day Uzbekistan), the remarkable signs of his intellectual giftedness that were apparent from early childhood, including the famous account of his going blind as a child and regaining his sight after his mother's prayers, and the beginnings of his hadith studies while still a young boy. The biography documents his extensive travels across the Muslim world, including trips to Makkah, Madinah, Basrah, Kufah, Baghdad, Syria, Egypt, and Nishapur, during which he studied under more than a thousand sheikhs and collected over six hundred thousand narrations. From this vast collection, he selected approximately seven thousand two hundred and seventy-five hadith (counting repetitions) that met his extraordinarily stringent criteria for inclusion in Sahih al-Bukhari.

The biography provides detailed analysis of Imam al-Bukhari's methodology in evaluating hadith authenticity, which was more rigorous than that of any other compiler. His standards for narrator reliability, his meticulous verification of the accuracy of each narration chain, his practice of requiring a personal meeting between each pair of adjacent narrators in a chain, and his other exacting criteria are all explained with examples that illustrate how his methodology worked in practice. The book also covers the writing process of Sahih al-Bukhari, which spanned sixteen years and involved the revision and refinement of the text through multiple drafts, with Imam al-Bukhari performing two rak'ah of prayer and seeking divine guidance before writing each hadith. The biography addresses the controversies that arose during his lifetime, including the debate about the creation of the Quran and his eventual departure from Nishapur, his final years, and his death. His personal character, including his asceticism, his generosity, his devotion to worship, and his humility despite his unparalleled scholarly achievements, is documented through reports from his students and contemporaries. The English prose conveys both the scholarly significance and the human dimension of this extraordinary life, making this biography a valuable resource for anyone who wishes to understand the scholar behind Islam's most important hadith collection.`,
    metaDescription: "An English biography of Imam al-Bukhari detailing his compilation of Sahih al-Bukhari, his rigorous hadith authentication, and scholarly life."
  },
  {
    slug: "the-biography-of-imam-ibn-majah-ra",
    description: `The Biography of Imam Ibn Majah (R.A) is an English-language account of the life of Muhammad ibn Yazid ibn Majah al-Rab'i al-Qazwini, the compiler of Sunan Ibn Majah, which is recognized as one of the six canonical hadith collections in Sunni Islam. While the other five canonical collections were established relatively early in Islamic scholarship, Sunan Ibn Majah was the last to be incorporated into the canonical set, with scholars over successive generations debating its inclusion before reaching a consensus that it deserved canonical status alongside the other five. This biography provides English-speaking readers with a thorough understanding of the scholar and his work.

The book traces Imam Ibn Majah's origins in Qazvin (in present-day Iran), his extensive educational journey across the Muslim world in pursuit of hadith knowledge, and his studies under the prominent scholars of his generation in regions including Khurasan, Iraq, the Hijaz, Syria, and Egypt. His network of teachers was exceptionally broad, numbering over four hundred sheikhs, and the biography documents his studies under several of the most important hadith scholars of the third Islamic century, including many who were themselves direct students of the leading scholars of the preceding generation. The breadth of his scholarly connections ensured that his collection drew upon the widest possible range of authentic narrations.

The central section of the biography examines Sunan Ibn Majah in detail, discussing its distinctive characteristics and the reasons for its eventual acceptance into the canonical set. Imam Ibn Majah organized his collection according to chapters of Islamic jurisprudence, making it particularly useful for jurists who needed to locate hadith relevant to specific legal topics. The book discusses Imam Ibn Majah's criteria for selecting and grading hadith, noting that while his standards were somewhat less restrictive than those of Imam al-Bukhari and Imam Muslim, the vast majority of narrations in his collection are authentic, with scholars identifying relatively few weak narrations. The biography also addresses the interesting feature of Sunan Ibn Majah that sets it apart from the other sunan collections: its inclusion of chapters on topics such as zuhd (asceticism), aqeedah (creed), and tafsir (Quranic interpretation) that go beyond the purely legal focus of the typical sunan work. The book covers Imam Ibn Majah's personal character, his scholarly reputation among his contemporaries, his other literary works beyond the Sunan, and his death. The scholarly debate about the canonical status of his collection is treated in detail, with arguments from both sides presented before the final consensus in favor of inclusion is explained. Written in clear English with references to Arabic sources, this biography provides a valuable introduction to a scholar whose work, though sometimes overshadowed by the other five canonical collections, has been an indispensable reference for Islamic scholarship for over a millennium.`,
    metaDescription: "An English biography of Imam Ibn Majah (R.A) covering his scholarly journey and Sunan Ibn Majah's jurisprudential organization and canonical status."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
