const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "madinah-arabic-reader-3",
    description: `Madinah Arabic Reader Book 3 represents a significant milestone in the widely respected Madinah Arabic series, designed to take students who have already completed the first two volumes to an intermediate level of Arabic proficiency. Building on the foundational vocabulary and grammar introduced in Books 1 and 2, this third volume introduces more complex sentence structures, advanced verb forms, and a substantially expanded vocabulary that enables learners to engage with Arabic texts of moderate difficulty. The book is structured around carefully graded lessons that progressively challenge students while reinforcing previously learned material through review exercises and contextual application.

One of the distinguishing features of Book 3 is its systematic approach to teaching Arabic grammar in a practical, accessible manner. Rather than overwhelming students with abstract grammatical theory, the lessons present rules organically through reading passages and conversational exercises that reflect everyday situations. Students encounter increasingly sophisticated passages that draw from Islamic themes, daily life scenarios, and cultural contexts, making the learning process both meaningful and engaging. The vocabulary introduced at this stage prepares learners to understand a wider range of Arabic content, including simplified classical texts and contemporary writings.

The exercises in Madinah Arabic Reader 3 are designed to develop all four language skills — reading, writing, listening comprehension, and speaking. Each chapter includes reading comprehension questions, vocabulary drills, sentence construction activities, and translation exercises that bridge the gap between passive understanding and active usage. The methodology follows the proven Madinah approach of teaching Arabic through Arabic, minimizing reliance on the student's native language and encouraging direct thinking in Arabic. This immersion-style technique has been remarkably effective for students of diverse linguistic backgrounds, whether they are studying Arabic for understanding the Quran, pursuing Islamic studies, or developing academic proficiency in the language. Teachers and self-learners alike appreciate the clear layout, logical progression, and the way each lesson builds naturally upon the last, creating a solid framework for continued advancement through the remaining volumes of this comprehensive series.`,
    metaDescription: "Madinah Arabic Reader Book 3 builds intermediate Arabic skills with advanced grammar, vocabulary, and reading exercises using the proven Madinah method."
  },
  {
    slug: "madinah-arabic-reader-6",
    description: `Madinah Arabic Reader Book 6 is an advanced-level textbook that pushes students toward near-fluency in classical Arabic, serving as one of the later volumes in the acclaimed Madinah Arabic series. At this stage of the curriculum, learners are expected to have already mastered the fundamentals presented in the earlier books, and Book 6 introduces them to the nuances and subtleties of Arabic that distinguish competent readers from truly proficient ones. The volume delves deeply into advanced grammatical constructs including complex conditional sentences, detailed treatments of verb forms and their derivatives, and sophisticated uses of particles that are essential for understanding classical Islamic texts.

The reading passages in Book 6 are drawn from a rich variety of sources, including excerpts from classical Arabic literature, historical accounts, and Islamic scholarly works. These passages are carefully selected to expose students to the authentic style and eloquence of classical Arabic while remaining accessible through the structured vocabulary support provided in each lesson. Students at this level begin to appreciate the rhetorical devices, metaphorical language, and stylistic conventions that characterize formal Arabic writing. This exposure is invaluable for anyone planning to read the Tafsir of the Quran, classical Hadith collections, or works of Islamic jurisprudence in their original language.

Each chapter in Madinah Arabic Reader 6 includes comprehensive exercises that test comprehension, reinforce grammar points, and develop the ability to express complex ideas in written Arabic. The exercises progress from controlled practice activities to more open-ended tasks that require students to apply their knowledge creatively. Translation exercises in this volume are particularly demanding, requiring students to move fluidly between Arabic and their native language while preserving meaning and tone. The book also places increased emphasis on morphological analysis, helping students understand how Arabic words are formed from root letters and patterns — a skill that is fundamental to independent vocabulary building and text analysis. For serious students of Arabic seeking to achieve genuine proficiency, Book 6 represents a crucial bridge between intermediate studies and advanced engagement with the Arabic language in its most refined forms.`,
    metaDescription: "Madinah Arabic Reader Book 6 is an advanced Arabic textbook covering complex grammar, classical passages, and rhetorical skills for near-fluency."
  },
  {
    slug: "madinah-arabic-reader-4",
    description: `Madinah Arabic Reader Book 4 continues the structured progression of the Madinah Arabic series, guiding students from the intermediate foundation established in Book 3 into more sophisticated territory. This volume marks a transitional stage where learners begin to engage with Arabic texts that are noticeably more complex in both grammar and vocabulary, preparing them for the advanced levels that follow. The carefully designed curriculum ensures that students consolidate their existing knowledge while being gently introduced to new concepts that expand their communicative and comprehension abilities.

Book 4 places a strong emphasis on developing the student's ability to understand and construct multi-clause sentences, introducing a range of conjunctions, relative clauses, and sentence connectors that are essential for fluent Arabic expression. The grammar lessons at this stage cover topics such as the various forms of the verbal noun (masdar), passive voice constructions, and the finer points of noun-adjective agreement in complex phrases. These grammatical concepts are not presented in isolation but are woven into reading passages and exercises that demonstrate their natural usage in context, making them easier to internalize and apply.

The reading material in Madinah Arabic Reader 4 draws from Islamic themes, moral stories, and descriptive passages that expose students to a broader range of Arabic vocabulary and expression styles. Each lesson includes detailed vocabulary lists with contextual meanings, ensuring that students learn words in the way they are actually used rather than as isolated dictionary entries. The exercises are varied and thorough, encompassing reading comprehension, grammar drills, sentence transformation tasks, and translation work that builds both accuracy and confidence. A particular strength of Book 4 is its approach to building reading stamina — the passages gradually increase in length, training students to maintain focus and comprehension across longer texts. This skill is essential for anyone who plans to read Islamic books, Quranic exegesis, or Hadith literature in Arabic. The book maintains the series' signature approach of teaching Arabic through Arabic, which continues to yield excellent results for students committed to mastering the language.`,
    metaDescription: "Madinah Arabic Reader Book 4 strengthens intermediate Arabic with complex grammar, multi-clause sentences, and expanded vocabulary through themed readings."
  },
  {
    slug: "madinah-arabic-reader-7",
    description: `Madinah Arabic Reader Book 7 stands among the most advanced volumes in the renowned Madinah Arabic series, crafted for students who have demonstrated strong proficiency through the previous six levels and are now ready to engage with Arabic at a near-academic level. This textbook assumes a solid command of Arabic grammar fundamentals and focuses on refining the student's ability to comprehend, analyze, and produce sophisticated Arabic text. The curriculum at this level is designed to bridge the gap between language learning and genuine literary engagement with classical and modern Arabic works.

The reading selections in Book 7 are notably more demanding than those in earlier volumes, featuring extended passages from classical Arabic prose, historical narratives, and scholarly Islamic texts. Students encounter the rich stylistic traditions of Arabic literature, including its characteristic use of parallelism, elaborate description, and rhetorical elegance. These readings are accompanied by detailed annotations that explain unfamiliar vocabulary, grammatical structures, and contextual references, allowing students to build their analytical skills while expanding their linguistic repertoire. The texts have been chosen not only for their linguistic value but also for their content, which often touches on Islamic history, ethics, and intellectual heritage.

Grammar instruction in Madinah Arabic Reader 7 moves beyond rule identification to focus on stylistic and rhetorical application. Students learn how skilled Arabic writers use grammatical structures creatively to achieve specific effects — emphasis, modulation of tone, rhetorical questioning, and elegant variation. Advanced topics such as the stylistic use of verb tenses for rhetorical purposes, sophisticated nominal sentence patterns, and the finer points of number and gender agreement in complex constructions are treated in depth. The exercises at this level require genuine analytical thinking, including textual analysis, comparative translation, and composition tasks that challenge students to express nuanced ideas in elegant Arabic. Book 7 serves as an essential resource for advanced students who aspire to read Islamic scholarly literature, classical Quranic commentaries, and works of Arabic heritage in their original language with genuine understanding and appreciation.`,
    metaDescription: "Madinah Arabic Reader Book 7 offers advanced Arabic instruction with classical texts, rhetorical analysis, and literary engagement for proficient learners."
  },
  {
    slug: "madinah-arabic-reader-8-only-1-book",
    description: `Madinah Arabic Reader Book 8 is the culminating volume of the celebrated Madinah Arabic series, representing the pinnacle of the curriculum's structured approach to teaching classical Arabic. This single comprehensive book consolidates and refines everything students have learned throughout the previous seven volumes, pushing them toward a level of Arabic proficiency that enables confident engagement with authentic classical texts. As the final installment, Book 8 is designed to ensure that learners complete the series with the skills needed to independently read, understand, and appreciate Arabic literature and Islamic scholarly works.

The reading material in Book 8 is drawn from the finest traditions of classical Arabic prose and poetry, presenting students with texts that reflect the full beauty and complexity of the language. These selections include passages from renowned Islamic scholars, historical chronicles, and literary masterpieces that have shaped Arabic intellectual heritage for centuries. Each passage is accompanied by thorough linguistic analysis, covering vocabulary in context, grammatical commentary, and stylistic notes that help students appreciate the artistry of the original text. The readings are deliberately challenging, requiring students to apply all the grammatical knowledge, vocabulary, and analytical skills they have accumulated throughout the series.

Book 8 also serves as a comprehensive review and consolidation tool, revisiting key grammatical concepts from the entire series and presenting them in the context of advanced texts. Advanced topics such as the intricate rules of Arabic numbers, the complexities of conditional structures in classical rhetoric, and the nuanced uses of particles receive detailed treatment. The exercises in this final volume are designed to prepare students for independent study, including extended translation projects, analytical writing assignments, and text-critical tasks that mirror the kind of work expected in formal Arabic studies programs. Students who successfully complete Book 8 of the Madinah Arabic Reader series will possess a robust foundation in classical Arabic that opens the door to direct engagement with the Quran, Hadith literature, Tafsir, Fiqh, and the broader Islamic intellectual tradition in its original linguistic medium.`,
    metaDescription: "Madinah Arabic Reader Book 8 completes the series with advanced classical Arabic texts, grammar review, and scholarly literary analysis skills."
  },
  {
    slug: "maeeshat-o-tijarat-ka-islami-ahkam",
    description: `Maeeshat-o-Tijarat Ka Islami Ahkam is a comprehensive Urdu-language book that addresses the Islamic rulings and principles governing business, trade, and economic activity. In an era where commercial transactions have become increasingly complex, this book serves as an essential guide for Muslims who wish to conduct their financial affairs in strict accordance with Shariah law. The text draws upon the primary sources of Islamic jurisprudence — the Quran, the Sunnah of Prophet Muhammad (peace be upon him), and the established rulings of classical Islamic scholars — to provide clear, practical guidance on a wide range of economic matters.

The book covers fundamental concepts of Islamic economics including the prohibition of Riba (interest and usury), the requirements for valid business contracts, the rules governing partnerships and joint ventures, and the Islamic perspective on various forms of trade. It addresses contemporary business scenarios alongside traditional commercial practices, making it relevant to modern readers while remaining firmly rooted in classical Fiqh methodology. Topics such as Islamic banking principles, halal and haram forms of investment, the ethics of trade and fair dealing, and the rights and responsibilities of buyers and sellers are explored in thorough detail with reference to specific Quranic verses and authenticated Hadith.

Maeeshat-o-Tijarat Ka Islami Ahkam also devotes significant attention to the moral and ethical dimensions of commerce in Islam. The book emphasizes that Islamic business is not merely about avoiding prohibited transactions but about conducting all economic activity with honesty, transparency, and a consciousness of divine accountability. It discusses the Islamic concept of Halal earnings, the importance of fulfilling contractual obligations, the prohibition of fraud and deception in trade, and the social responsibilities that accompany wealth. The author presents the material in a clear, organized manner that makes complex juristic concepts accessible to readers without specialized training in Islamic law. This book is an invaluable resource for business owners, professionals, students of Islamic studies, and anyone seeking to align their financial life with the teachings of Islam, offering practical solutions to real-world economic challenges within the framework of Shariah compliance.`,
    metaDescription: "Maeeshat-o-Tijarat Ka Islami Ahkam is a comprehensive Urdu book on Islamic rulings for business, trade, and halal economic practices based on Shariah."
  },
  {
    slug: "mafroor-larkiyon-ka-nikkah-aur-hamari-adalatien",
    description: `Mafroor Larkiyon Ka Nikkah Aur Hamari Adalatien is an important Urdu book that tackles one of the most pressing social issues facing Muslim communities — the marriage of orphan girls and the role of Islamic courts in safeguarding their rights. Written with deep sensitivity and scholarly rigor, this work examines the Islamic legal framework surrounding the marriage of orphaned women, highlighting both the protections that Shariah provides and the practical challenges that arise in their implementation within contemporary judicial systems.

The book opens by establishing the Quranic and Prophetic foundations for the rights of orphans in Islam, citing specific verses from Surah Al-Baqarah and Surah An-Nisa that address the guardianship, property rights, and marriage of orphan girls. The author explains how Islam elevated the status of orphans at a time when they were among the most vulnerable members of society, granting them specific legal protections that were revolutionary for their time. The text then transitions to a detailed examination of the conditions and requirements for the valid marriage of orphan girls under Islamic law, including the role of the Wali (guardian), the requirement of consent, the question of Mahr (dowry), and the prevention of exploitation.

A significant portion of the book is devoted to analyzing the functioning of Islamic courts and the Pakistani judicial system in particular regarding cases involving orphan girls' marriages. The author documents real cases, identifies systemic issues that lead to the violation of orphan girls' rights, and proposes practical solutions grounded in Islamic jurisprudence. The discussion covers topics such as the misuse of guardianship, forced marriages disguised as religious obligations, the misappropriation of orphan property, and the gaps between Islamic legal ideals and their practical enforcement. Mafroor Larkiyon Ka Nikkah Aur Hamari Adalatien also addresses the responsibilities of society at large — scholars, judges, community leaders, and ordinary citizens — in ensuring that orphan girls receive the protection and dignity that Islam guarantees them. This book serves as both a scholarly reference and a call to action for justice and compassion.`,
    metaDescription: "Mafroor Larkiyon Ka Nikkah Aur Hamari Adalatien addresses the Islamic legal rights of orphan girls in marriage and the role of courts in protecting them."
  },
  {
    slug: "maghrib-se-isha-tak",
    description: `Maghrib Se Isha Tak is a spiritually enriching Urdu book that focuses on the blessed time period between the Maghrib and Isha prayers — a window of time that holds special significance in Islamic tradition. This book illuminates the virtues, spiritual practices, and recommended acts of worship that Muslims can engage in during this daily interval, transforming what many might consider a routine gap between prayers into a meaningful opportunity for spiritual growth and divine proximity.

The author draws upon authentic Hadith literature and the practices of the righteous predecessors (Salaf us-Saliheen) to highlight the unique blessings associated with this time of day. According to Prophetic traditions, the time between Maghrib and Isha is one of the moments when supplications are readily accepted, making it an ideal period for dua and personal reflection. The book explores this concept in depth, citing specific narrations about the opening of the gates of heaven during this time and the encouragement to seize this opportunity for seeking Allah's forgiveness and blessings.

Maghrib Se Isha Tak provides practical guidance on how to make the most of this precious time. The book discusses the recommendation of performing the Awwabin prayer (the voluntary prayer between Maghrib and Isha), engaging in dhikr (remembrance of Allah), reciting the Quran, making dua, and reflecting on the day's deeds. The author also addresses the importance of not wasting this time in idle pursuits or worldly distractions, presenting the Islamic perspective on time management and the value of every moment in a believer's life. Each chapter combines spiritual insight with practical advice, making the content accessible to readers of all levels of religious knowledge. The book also includes discussions on the virtues of the Maghrib prayer itself, the significance of breaking the fast at the proper time, and the wisdom behind the timing of the Isha prayer in Islamic jurisprudence. For anyone seeking to add depth and purpose to their daily worship routine, Maghrib Se Isha Tak offers a beautiful and practical guide to transforming this daily interval into a source of ongoing spiritual benefit.`,
    metaDescription: "Maghrib Se Isha Tak is a Urdu spiritual guide exploring the virtues, worship, and blessings of the time between Maghrib and Isha prayers in Islam."
  },
  {
    slug: "magroor-qoam",
    description: `Magroor Qoam is a thought-provoking Urdu book that examines the stories of arrogant nations mentioned in the Quran — civilizations that were destroyed due to their pride, disobedience, and rejection of divine guidance. The title, which translates to "Arrogant Nations," sets the tone for a work that serves as both a historical account and a moral warning, drawing lessons from the fate of ancient peoples who considered themselves invincible only to be humbled by Allah's punishment.

The book provides detailed narratives of several civilizations described in the Quran, including the people of Aad, Thamud, the people of Lut, the nation of Shuaib, and Pharaoh's Egypt. For each nation, the author presents the Quranic account alongside relevant Hadith literature and historical context, painting a vivid picture of how these societies rose to power, became corrupted by arrogance and injustice, received warnings from Allah's prophets, and ultimately faced divine retribution. The stories are told with a narrative quality that makes them engaging to read while maintaining scholarly accuracy and adherence to authentic Islamic sources.

What distinguishes Magroor Qoam from a simple retelling of Quranic stories is its analytical approach to understanding the patterns of arrogance and its consequences. The author identifies common characteristics among these destroyed nations — the elevation of material wealth over spiritual values, the oppression of the weak, the rejection of truth in favor of tradition and power, and the refusal to heed warnings from messengers of Allah. These patterns are then related to contemporary human behavior, encouraging readers to reflect on how the lessons of the past apply to individuals and societies today. The book emphasizes that arrogance (kibr) is not merely a historical phenomenon but a persistent human failing that continues to invite divine displeasure. Magroor Qoam also discusses the concept of humility in Islam and how cultivating this quality serves as a protection against the spiritual diseases that led to the downfall of these ancient civilizations. This work is valuable for anyone interested in Quranic studies, Islamic history, or the moral lessons embedded in the stories of the prophets and their peoples.`,
    metaDescription: "Magroor Qoam explores the Quranic stories of arrogant nations destroyed by Allah, drawing moral lessons on pride, humility, and divine justice."
  },
  {
    slug: "malka-e-aliya",
    description: `Malka-e-Aliya is a notable Urdu historical and biographical book that presents the life and legacy of a significant figure in Islamic history. The title, meaning "The Exalted Queen" or "The Noble Queen," suggests a work focused on a woman of remarkable stature, and the book delivers a detailed account that combines historical narrative with biographical insight. Written in an engaging Urdu literary style, the book brings its subject to life through meticulous research and compelling storytelling.

The book traces the complete life journey of its central figure, from her early upbringing and formative influences to her rise to prominence and her lasting impact on the Muslim community. The author pays careful attention to the historical context in which the subject lived, providing readers with a thorough understanding of the political, social, and cultural dynamics of the era. This contextual approach allows readers to appreciate not only the personal qualities of the figure but also the challenges she faced and the circumstances that shaped her decisions and contributions.

Malka-e-Aliya is distinguished by its balanced approach to historical biography. Rather than uncritical praise or dry factual enumeration, the book presents a nuanced portrait that acknowledges the complexities of its subject's life while highlighting the qualities that made her truly remarkable. The author draws upon primary historical sources, contemporary accounts, and scholarly research to construct a narrative that is both informative and engaging. The prose style reflects the best traditions of Urdu biographical writing, combining literary elegance with scholarly precision. Readers will find detailed discussions of the subject's character, her intellectual and spiritual contributions, her relationships with key figures of her time, and the institutions or movements she influenced. The book also explores the broader significance of her legacy, examining how her example continued to inspire subsequent generations of Muslims. Whether read as historical scholarship, literary biography, or inspirational reading, Malka-e-Aliya offers a rich and rewarding experience that deepens the reader's understanding of Islamic history and the remarkable individuals who have shaped it. The work stands as a testament to the important role that women have played throughout Islamic civilization.`,
    metaDescription: "Malka-e-Aliya is a comprehensive Urdu biographical book presenting the life, legacy, and historical significance of a noble figure in Islamic history."
  }
];

async function main() {
  for (const item of updates) {
    const result = await prisma.product.update({
      where: { slug: item.slug },
      data: {
        description: item.description,
        metaDescription: item.metaDescription
      }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done - updated", updates.length, "products");
}

main().then(() => prisma.$disconnect());
