const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "golden-stories-of-accepted-prayers",
    description: `Golden Stories of Accepted Prayers is a spiritually uplifting collection that compiles authentic accounts of prayers (Duas) that were answered by Allah in remarkable and often unexpected ways. Drawing from the rich Islamic tradition of documenting Divine responses to sincere supplications, this book brings together stories from the Quran, the life of the Prophet Muhammad (peace be upon him), the Sahabah, the Tabi'een, and righteous Muslims throughout history up to the contemporary era. These narratives serve to strengthen the reader's conviction in the power of Dua and to inspire a deeper, more consistent practice of calling upon Allah in all circumstances.

The book is systematically organized into categories that reflect different types of prayers and the contexts in which they were made. Chapters cover prayers made during extreme hardship, supplications for guidance at life's crossroads, Duas of the terminally ill who experienced miraculous recoveries, prayers of parents for their wayward children, and the powerful invocations of scholars who sought knowledge from Allah and received it in abundance. Each story is presented with its complete chain of narration where available, along with a discussion of the lessons to be derived from that particular answered prayer. The accounts include the famous story of Prophet Ayyub (Job) whose patience through prolonged illness was rewarded with complete healing, the Dua of Prophet Yunus (Jonah) from the belly of the whale, and numerous less well-known but equally inspiring incidents from Islamic history.

Beyond the stories themselves, the author provides a comprehensive framework for making Dua that maximizes the likelihood of acceptance. This includes the optimal times for supplication according to the Sunnah, the etiquette and manner of making Dua, the importance of persistence and never losing hope in Allah's mercy, and the common mistakes that prevent Duas from being answered. The book addresses sensitive questions such as why some prayers seem to go unanswered, explaining the Islamic concept that Allah responds to every Dua in one of three ways — by granting what is asked, by preventing a greater harm, or by reserving the reward for the Hereafter. A special chapter is dedicated to the Duas of the Prophet (peace be upon him) that are proven to be most readily accepted, providing readers with a practical toolkit of powerful supplications they can incorporate into their daily worship. This book is an invaluable resource for anyone going through difficult times, anyone who wishes to strengthen their relationship with Allah through Dua, and anyone interested in the inspirational history of Divine response to human supplication.`,
    metaDescription: `A spiritually uplifting collection of authentic stories of answered prayers from Quran, Hadith, and Islamic history. Learn the art of making Duas that get accepted.`
  },
  {
    slug: "golden-stories-of-sayyida-khadijah-ra",
    description: `Golden Stories of Sayyida Khadijah (R.A) is a dedicated biography that celebrates the life and legacy of Khadijah bint Khuwaylid, the first wife of Prophet Muhammad (peace be upon him) and the first person to accept Islam. Often referred to as Ameerat al-Quraish (Princess of Quraish) and Tahira (The Pure One), Khadijah's life exemplifies the highest ideals of faith, courage, loyalty, and devotion. This comprehensive work traces her journey from a highly successful businesswoman in pre-Islamic Makkah — one of the wealthiest and most respected women of her time — to becoming the pillar of support upon which the early Islamic message was built.

The book presents a vivid portrait of Khadijah's character through well-documented accounts. Readers will discover how she conducted one of the largest trade caravans in Arabia, managing an enterprise that rivaled those of the most prominent male merchants of Quraish. The narrative details her famous employment of the young Muhammad (peace be upon him), whose reputation for honesty (Al-Amin) led her to propose marriage — a remarkable event that speaks volumes about her confidence and agency in a society dominated by male authority. The book explores the depth of her support for the Prophet after the first revelation in the Cave of Hira, when he returned home trembling and fearful, and she responded with the immortal words of comfort and affirmation that earned her a unique place in Islamic history.

The biography dedicates extensive coverage to Khadijah's sacrifices during the three-year boycott of Banu Hashim, when the Muslim community was isolated in a valley outside Makkah and faced near-starvation. Her wealth was depleted to sustain the believers during this ordeal, and she passed away shortly after the boycott was lifted — a loss that the Prophet described as the most painful of his life. The book also examines her role as a mother to Fatimah az-Zahra, who became one of the most revered women in Islamic history, and the profound influence her character had on the development of early Muslim society. Special attention is given to the Quranic and Prophetic praises for Khadijah, including the Hadith where Angel Jibreel conveyed Allah's greetings to her and the glad tidings of a palace in Paradise made of pearls. The book includes a detailed discussion of the lessons modern Muslim women can draw from Khadijah's example — balancing professional success with spiritual devotion, providing unwavering support to one's spouse, maintaining dignity under pressure, and investing one's resources in noble causes. Written with scholarly rigor and emotional sensitivity, this biography ensures that the legacy of Islam's first believer continues to inspire new generations.`,
    metaDescription: `Comprehensive biography of Sayyida Khadijah (R.A), Islam's first believer. Discover her remarkable life as a businesswoman, supporter of the Prophet, and pillar of early Islam.`
  },
  {
    slug: "golden-stories-of-umar-ibn-al-khattaab-ra",
    description: `Golden Stories of Umar Ibn Al-Khattaab (R.A) is a masterful biography of Islam's second Caliph, one of the most powerful and transformative figures in human history. Umar ibn al-Khattaab's journey from a fierce opponent of Islam who once resolved to assassinate the Prophet Muhammad (peace be upon him) to becoming one of its greatest champions represents one of the most dramatic conversions in religious history. This book chronicles every major phase of his extraordinary life — his days as a wrestler and poet in pre-Islamic Makkah, his dramatic embrace of Islam, his instrumental role in strengthening the Muslim community during the Prophet's lifetime, and his decade-long caliphate that expanded Islamic governance across two continents while setting standards of justice that remain unmatched.

The biography is filled with gripping narratives that reveal Umar's larger-than-life personality. Readers will encounter the story of his conversion, triggered by reading the opening verses of Surah Ta-Ha that his sister had secretly obtained, and how his Islam struck terror into the hearts of the Quraysh. The book details his unique role as the Prophet's father-in-law (through the marriage of his daughter Hafsa), his participation in all major battles including Badr, Uhud, and the Trench, and his refusal to accept any position of authority after the Prophet's death until Abu Bakr nominated him as his successor. The chapters on his caliphate are particularly rich, covering his revolutionary system of governance that included the establishment of the Islamic calendar, the creation of a judicial system with independent judges, the introduction of a welfare state through the Bayt al-Mal (public treasury), and his pioneering policies on environmental conservation, urban planning, and military organization.

What distinguishes this biography is its balanced portrayal that shows both Umar's strength and his tenderness. The book presents his famous nighttime patrols of Madinah in disguise — personally investigating the needs of his subjects — alongside his emotional displays of humility, including weeping during Friday sermons and his declaration before the conquered people of Jerusalem that Muslims would guarantee the safety of their lives, property, and places of worship. The author draws from the most reliable historical sources including the works of Ibn Kathir, at-Tabari, and the authenticated Hadith collections, providing source references for every major claim. Each chapter concludes with a reflection on how Umar's example applies to modern challenges in Muslim leadership, governance, and personal conduct. The book includes maps of the territories governed during Umar's caliphate, genealogical charts, a detailed timeline, and an extensive bibliography. It is essential reading for anyone who wishes to understand the foundations of Islamic civilization and the qualities that made Umar one of the greatest rulers in history.`,
    metaDescription: `Definitive biography of Caliph Umar ibn al-Khattaab (R.A) — from fierce opponent to transformative Islamic ruler. Sourced from authenticated Hadith and classical histories.`
  },
  {
    slug: "golden-words-for-the-successful-life",
    description: `Golden Words for the Successful Life is a motivational Islamic self-help book that presents timeless wisdom for achieving true success — defined not merely in material terms but as a comprehensive state of spiritual fulfillment, emotional well-being, social harmony, and eventual salvation in the Hereafter. This book compiles the most powerful and practical advice from the Quran, the Prophetic traditions, and the writings of Islamic scholars throughout the centuries, organizing them into a clear framework that readers can immediately apply to their daily lives. The title reflects the Islamic belief that the "golden words" of divine guidance are more precious than any worldly treasure.

The book is structured around eight pillars of Islamic success: faith (Iman) as the foundation, knowledge (Ilm) as the guiding light, action (Amal) as the vehicle, patience (Sabr) as the fuel, gratitude (Shukr) as the accelerator, sincerity (Ikhlas) as the compass, brotherhood (Ukhuwwah) as the support system, and reliance on Allah (Tawakkul) as the ultimate source of strength. Each pillar is explored in a dedicated chapter that begins with relevant Quranic verses and Hadith, followed by practical explanations, real-life examples from the lives of the Sahabah and contemporary Muslims, and actionable exercises that help readers incorporate these principles into their routines. The writing style is engaging and conversational, avoiding the dry, academic tone that often characterizes Islamic literature, making it accessible to young adults and professionals who may not have extensive background in Islamic studies.

A unique feature of this book is its integration of modern self-development concepts with Islamic wisdom. The author draws parallels between contemporary psychological research on happiness, productivity, and resilience and the teachings that Islam has offered for over 1,400 years. Chapters on time management, for instance, connect the Islamic concept of time as an Amanah (trust) with modern productivity frameworks. The section on emotional intelligence references the Prophet's exemplary management of emotions while connecting it to current psychological understanding. The book includes practical tools such as a daily success checklist based on the Sunnah, a weekly self-assessment questionnaire, and a monthly reflection journal template — all designed to help readers track their progress toward living a more purposeful, Islamically-grounded life. Special attention is given to common modern challenges including social media addiction, career anxiety, relationship difficulties, and the struggle to maintain religious commitment in a secular environment. This book serves as an excellent gift for graduates, young professionals, and anyone at a crossroads in life seeking both worldly achievement and spiritual fulfillment.`,
    metaDescription: `Islamic self-help guide combining Quranic wisdom, Prophetic advice, and modern productivity techniques. 8 pillars for achieving spiritual and worldly success.`
  },
  {
    slug: "goodword-english-arabic-dictionary-8x12",
    description: `The Goodword English-Arabic Dictionary (8x12) is a comprehensive bilingual reference tool designed to facilitate the learning and understanding of both English and Arabic languages. Published by Goodword Books, one of the most respected names in Islamic and Arabic educational publishing, this dictionary is an essential resource for students of Arabic language, Islamic studies, professionals working in Arab countries, and anyone with an interest in bridging the linguistic gap between English and Arabic. The 8x12 inch format provides a generous page size that ensures readability and comfortable use during extended study sessions.

This dictionary contains an extensive vocabulary covering general English and Arabic terms along with specialized vocabulary relevant to Islamic studies, the Quran, Hadith literature, and Arab cultural contexts. Each entry provides the English word, its Arabic equivalent in both script and transliteration, pronunciation guide, part of speech identification, and contextual usage examples. Where applicable, entries also include common idioms, phrases, and compound expressions that demonstrate how the word is used in real communication. The Arabic entries are presented in clear, well-formed Naskh script that is easy to read even for intermediate-level Arabic learners. The dictionary employs an intuitive alphabetical ordering system with helpful cross-references between related words.

Beyond basic vocabulary, this dictionary includes several valuable supplementary sections. These include a guide to Arabic pronunciation with vowel markings (Tashkeel), a table of Arabic verb conjugation patterns, a list of common Arabic abbreviations, and a section on the 99 Names of Allah (Asma ul Husna) with their English meanings. The appendix also features a quick reference guide to Islamic terminology that frequently appears in English-Arabic communication but is not found in standard dictionaries. The durable hardcover binding and quality paper ensure this dictionary withstands frequent use in classrooms, offices, and homes. The 8x12 format strikes an ideal balance between portability and comprehensive content — large enough to include detailed entries yet practical enough to carry in a backpack or briefcase. Whether you are a university student studying Arabic, a Muslim seeking to understand the language of the Quran more deeply, a translator working between English and Arabic, or a professional preparing for an assignment in an Arabic-speaking country, this Goodword dictionary is an indispensable companion that will serve you for years to come.`,
    metaDescription: `Comprehensive English-Arabic bilingual dictionary in 8x12 format. Includes Quranic terms, verb conjugation guides, pronunciation tables, and 99 Names of Allah.`
  },
  {
    slug: "great-women-of-islam",
    description: `Great Women of Islam is an inspiring anthology that chronicles the lives and contributions of the most remarkable women in Islamic history. This comprehensive work goes far beyond the commonly known biographies of the Prophet's wives and daughters to include scholars, warriors, poets, philanthropists, and community leaders whose achievements shaped Islamic civilization across centuries and continents. From the battlefields of early Islam to the lecture halls of medieval universities, from the courts of Andalusia to the markets of Baghdad, this book demonstrates that Muslim women have always been active, influential, and indispensable contributors to the Islamic project.

The book opens with detailed biographies of the women of the Prophet's household — Khadijah, Ayesha, Fatimah, Umm Salamah, and others — but quickly expands its scope to encompass lesser-known but equally significant figures. Readers will meet Nusayba bint Ka'b (Umm Amarah), the warrior woman who fought alongside the Prophet at Uhud and protected him with her own body; Fatimah al-Fihri, who founded the world's first university in Fez, Morocco; Rabia al-Adawiyya, the legendary mystic whose poetry on divine love continues to move hearts; and Lubna of Cordoba, the 10th-century Andalusian intellectual who served as the palace scribe and was renowned for her mathematical brilliance. The book also profiles women scholars like Ayesha bint Abdulrahman (known as the Shaykhah of her time) and the female Hadith scholars who taught in the great mosques of Damascus, Cairo, and Baghdad.

Each biography is meticulously researched using authentic Islamic sources and is presented with attention to both historical accuracy and narrative engagement. The author places each woman's achievements within their proper historical and social context, explaining the specific challenges they faced and how their Islamic faith empowered them to overcome societal limitations. The book includes a comprehensive analysis of the Quranic framework for women's rights and dignity, the Prophet's teachings on gender equity, and the historical evolution of women's roles in Muslim societies. Special chapters address common misconceptions about women in Islam, providing evidence-based responses to critics. The writing is scholarly yet accessible, suitable for both academic use and general readership. Extensive footnotes, a bibliography, and a detailed index make this a valuable reference work. This book is essential reading for Muslim women seeking inspiring role models, men who wish to understand the proper Islamic perspective on women's capabilities, students of Islamic history, and anyone interested in the untold stories of women who changed the world through their faith, intellect, and courage.`,
    metaDescription: `Inspiring anthology of remarkable Muslim women throughout history — scholars, warriors, poets, and leaders. Authentic biographies with Quranic framework for women's rights.`
  },
  {
    slug: "green-muslim-the-true-custodians-of-the-earth",
    description: `Green Muslim: The True Custodians of the Earth is a groundbreaking book that establishes the Islamic theological and ethical foundation for environmental stewardship. In an era where climate change and ecological degradation represent existential threats to humanity, this book demonstrates that Islam offers a comprehensive environmental philosophy that predates the modern environmental movement by over 1,400 years. Drawing upon Quranic verses, Prophetic Hadith, and the works of classical Islamic scholars, the author builds a compelling case that environmental conservation is not merely a secular concern but a fundamental religious obligation for every Muslim.

The book begins with a thorough examination of the Quranic concept of Khilafah (stewardship) — the idea that humans are appointed by Allah as caretakers of the Earth, not its owners or exploiters. This theological foundation is supported by over fifty Quranic verses and numerous authenticated Hadith that address topics including water conservation, animal welfare, land preservation, and the prohibition of waste (Israf). The Prophet Muhammad (peace be upon him) established water conservation zones (Hima) around Madinah, prohibited the unnecessary cutting of trees even during wartime, expressed compassion for all living creatures including insects, and taught his companions to use resources sparingly — all practices that align perfectly with modern environmental science.

The book then transitions from theology to practical action, providing Muslims with a comprehensive guide to reducing their environmental footprint in ways that are consistent with Islamic values. Chapters cover sustainable consumption, reducing food waste, adopting eco-friendly transportation, conserving water during Wudu and Ghusl, choosing halal and ethically sourced products, and creating green homes and mosques. The author provides practical checklists, product recommendations, and lifestyle modifications that readers can implement immediately. Special sections address the environmental responsibilities of businesses, governments, and Islamic institutions, arguing that Islamic finance principles inherently promote sustainable economic models. The book also explores the contributions of Muslim civilizations to agricultural science, water engineering, and urban planning — contributions that Europe later adopted during the Renaissance. Case studies from contemporary Muslim communities around the world demonstrate how Islamic environmental values are being translated into practical conservation projects. This book is essential reading for environmentally conscious Muslims, Islamic studies students, scholars of religion and ecology, and anyone interested in the intersection of faith and environmental action.`,
    metaDescription: `Groundbreaking Islamic environmental guide establishing the Quranic foundation for eco-stewardship. Practical tips for green living aligned with Islamic values and Prophetic traditions.`
  },
  {
    slug: "guidelines-for-raising-children",
    description: `Guidelines for Raising Children is a comprehensive Islamic parenting manual that provides parents and caregivers with a complete framework for raising righteous, confident, and well-adjusted Muslim children. This essential reference book draws upon the Quranic guidance, the Prophetic method of child-rearing, the wisdom of the Sahabah in raising the next generation of Muslims, and the insights of classical Islamic scholars on child psychology and moral development. Written in a clear, practical style, this book addresses every stage of a child's development from infancy through adolescence, offering age-specific advice that parents can implement immediately.

The book opens with the Islamic perspective on the blessing of children and the immense responsibility that parenthood entails. It establishes the foundational principle that every child is born with an innate inclination toward truth (Fitrah) and that a parent's primary role is to nurture and protect this natural disposition rather than imposing faith upon a blank slate. The early childhood section covers topics including the Sunnah practices for welcoming a newborn (Adhan, Tahneek, Aqiqah), breastfeeding according to Islamic guidance, the importance of gentle discipline versus punishment, and how to introduce basic Islamic concepts like Tawheed and the names of Allah through play and storytelling. The middle childhood chapters address formal Islamic education, Quran memorization strategies, managing screen time, dealing with peer pressure, and developing good character traits through positive reinforcement.

The adolescent section tackles the most challenging phase of parenting with practical, Islamically-grounded advice on maintaining open communication, addressing questions about faith and identity, managing exposure to un-Islamic content, preparing for marriage, and the delicate balance between granting independence and maintaining parental guidance. Throughout the book, the author emphasizes the importance of parents being role models — children learn more from what their parents do than what they say. The book includes chapters on raising daughters with confidence and dignity, raising sons with responsibility and emotional intelligence, handling special needs children with Islamic compassion, dealing with rebellious teenagers without severing family bonds, and the critical role of both fathers and mothers in the parenting process. Each chapter concludes with "Action Points" — specific, measurable steps parents can take that week. The book also addresses contemporary challenges including social media, bullying, mental health, and the unique pressures facing Muslim children growing up as minorities in non-Muslim societies. Supplemented with authentic Hadith references, a recommended reading list for children of different ages, and emergency guidance for handling crisis situations, this book is an indispensable resource for every Muslim household.`,
    metaDescription: `Comprehensive Islamic parenting guide from infancy to adolescence. Quranic and Prophetic child-rearing wisdom with practical tips for modern challenges like social media and identity.`
  },
  {
    slug: "gumshuda-pialah",
    description: `Gumshuda Pialah (The Lost Bowl) is an engaging Urdu storybook that uses a charming narrative to impart valuable Islamic and moral lessons to young readers. Part of the growing genre of Islamic children's literature, this book combines an entertaining storyline with gentle moral instruction, making it an ideal read for children aged 5 to 10 years. The story revolves around a young protagonist who loses a cherished bowl and embarks on a journey to find it, encountering various characters and situations along the way that teach important life lessons about honesty, responsibility, patience, gratitude, and trust in Allah's plan.

The narrative structure of Gumshuda Pialah is carefully designed to maintain a child's interest while progressively introducing deeper moral concepts. Each chapter presents a new character or situation that the protagonist must navigate, and through these encounters, themes such as the importance of seeking help from others, the virtue of admitting mistakes, the blessing of contentment with what Allah has provided, and the power of prayer (Dua) in resolving difficulties are woven naturally into the storyline. The author avoids heavy-handed moralizing, instead allowing the story itself to demonstrate the consequences of good and bad choices in a way that young minds can easily grasp and remember.

The book is illustrated with colorful, culturally appropriate artwork that brings the story to life and helps visual learners engage with the narrative. The illustrations depict Islamic settings and incorporate subtle Islamic visual elements such as Arabic calligraphy in background details and characters engaged in Islamic practices like making Dua and eating with the right hand. The Urdu text is written in simple, clear language appropriate for the target age group, with vowel marks (Harakat) on difficult words to help young readers develop their Urdu literacy skills. Parents and teachers will appreciate the discussion questions included at the end of each chapter, which encourage children to reflect on the story's lessons and relate them to their own experiences. A glossary of difficult Urdu words and an English translation of key moral lessons are provided for bilingual families. This book is an excellent addition to any home library, Islamic school classroom, or weekend Madrasah reading program, and makes a wonderful gift for children during Eid, Ramadan, or any occasion that celebrates learning and moral development.`,
    metaDescription: `Engaging Urdu children's storybook teaching honesty, patience, gratitude, and trust in Allah. Illustrated with colorful artwork, ideal for ages 5-10.`
  },
  {
    slug: "gunahon-ko-dho-dalny-waly-amal",
    description: `Gunahon Ko Dho Dalny Waly Amal (Acts That Erase Sins) is a profoundly reassuring and spiritually uplifting Islamic book in Urdu that addresses one of the most common concerns among believers — how to seek forgiveness for past sins and attain spiritual purification. Based entirely on authentic Quranic verses and verified Hadith, this book catalogues the specific actions, deeds, and practices that the Prophet Muhammad (peace be upon him) guaranteed would erase sins — both minor and, under certain conditions, major transgressions. The book serves as a spiritual manual of hope, reminding readers that no matter how far a person may have strayed, the door of Allah's forgiveness remains wide open through specific Sunnah acts and righteous deeds.

The book is organized into clearly defined chapters, each dedicated to a particular category of sin-erasing actions. These include the comprehensive explanation of Tawbah (repentance) as the greatest sin-eraser, the significance of Wudu (ablution) and its purifying effects on both body and soul, the five daily prayers and how each one erases sins committed between prayers, the Friday (Jumu'ah) prayer as a weekly spiritual cleanse, fasting — particularly the Day of Arafah, Ashura, and the six fasts of Shawwal — as expiation for past wrongdoing, and the spiritual purification achieved through Hajj and Umrah. Additional chapters cover the sin-erasing power of charity (Sadaqah), the remembrance of Allah (Dhikr), seeking forgiveness in the last third of the night (Tahajjud), and the intercession of trials and hardships that a believer endures with patience.

A particularly valuable section of this book addresses the conditions for the acceptance of Tawbah, explaining the four essential components identified by Islamic scholars: immediate cessation of the sin, sincere remorse, firm intention never to repeat the act, and where applicable, restoring the rights of those who were wronged. The author also addresses common misconceptions about forgiveness, clarifying that major sins require specific repentance while minor sins are erased through routine acts of worship. The book includes the famous Hadith of the Prophet (peace be upon him) about the seventy recorded sins being forgiven through a single Wudu, the Hadith about the five daily prayers serving as expiation, and the authenticated narration about the fasting of Ramadan and the following six days of Shawwal being equivalent to fasting the entire year. Written in clear, accessible Urdu with all Hadith references properly documented, this book provides both comfort and practical guidance for any Muslim who wishes to cleanse their spiritual record and draw closer to Allah through His boundless mercy.`,
    metaDescription: `Urdu Islamic book cataloguing authentic Sunnah acts that erase sins — from prayer and fasting to repentance and Dhikr. A spiritual manual of hope and purification.`
  }
];

async function main() {
  for (const item of updates) {
    try {
      const result = await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log(`✅ Updated: ${item.slug}`);
    } catch (error) {
      console.error(`❌ Error updating ${item.slug}: ${error.message}`);
    }
  }
  console.log("\n✅ Batch R5B complete — 10 products updated");
}

main().then(() => prisma.$disconnect());
