const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "veiling-and-unveiling",
    description: `Veiling and Unveiling is an English-language book that provides a thorough examination of the Islamic practice of hijab (veiling) and the contemporary debates that surround it, presenting the Islamic position with clarity, scholarly rigor, and sensitivity to the complexity of the modern context. The book addresses one of the most visible and controversial aspects of Islamic practice — the requirement for Muslim women to cover their bodies and hair in the presence of non-mahram men — by grounding its discussion in the primary sources of Islam and examining the various arguments that have been advanced both for and against the practice.

The book begins by establishing the Quranic basis for the Islamic dress code. The verses in Surah An-Nur and Surah Al-Ahzab that prescribe the covering of the believing women are analyzed in detail, with attention to their linguistic structure, their historical context (asbab al-nuzul), and the classical tafseer explanations that have been offered by scholars across the centuries. The distinction between the general command to lower the gaze and guard modesty (addressed to both men and women) and the specific command to draw the khimar (head covering) over the chest and to wear the jilbab (outer garment) is carefully drawn. The book demonstrates that the Quranic requirement for hijab is not a vague recommendation but a specific and binding command that has been understood consistently by the classical scholars of Islam.

The hadith evidence for hijab is presented systematically, including the narrations that describe how the female companions implemented the Quranic command, the hadith that specify which parts of a woman's body may be displayed, and the hadith that warn against the consequences of abandoning the hijab. The book addresses the common objections that critics raise against these narrations, providing scholarly responses that demonstrate the authenticity and applicability of the relevant hadith to the contemporary context.

The "unveiling" dimension of the book addresses the historical and ideological forces that have driven the removal of hijab in various Muslim societies. The book traces the history of forced unveiling in countries such as Turkey, Iran (under the Pahlavi dynasty), Tunisia, and Algeria, showing how colonial powers and secular nationalist movements used the removal of hijab as a symbol of modernization and progress. The book also examines the contemporary feminist arguments against hijab, engaging with them respectfully while demonstrating that many of these arguments are based on misunderstandings of what hijab actually means in Islamic theology and practice.

The book provides a nuanced discussion of the different perspectives that exist within the Muslim scholarly community regarding the precise requirements of hijab, acknowledging areas of legitimate difference of opinion while maintaining the basic obligation. The distinction between the hijab (head and body covering) and the niqab (face veil) is explained, with the different scholarly positions on the face veil discussed. The book also addresses the situation of Muslim women living in non-Muslim societies, where the decision to wear hijab may have social, professional, and legal consequences that need to be weighed in light of Islamic principles.

The practical section of the book provides guidance for women who are considering adopting hijab, women who already wear hijab and want to strengthen their understanding and practice, and men who want to fulfill their responsibility of supporting and protecting their female relatives in the observance of hijab. The spiritual dimensions of hijab — including its relationship to taqwa (God-consciousness), its function as an act of obedience to Allah, and its role in defining a woman's identity in relation to her Creator rather than to societal expectations — are emphasized as the primary motivations for observance. Veiling and Unveiling is written in clear, academic English that makes it suitable for Muslim women seeking to understand their obligation, for scholars studying gender in Islam, and for non-Muslims who want an informed perspective on this widely misunderstood practice.`,
    metaDescription: "An English examination of Islamic hijab presenting Quranic and hadith evidence, historical unveiling, scholarly positions, and practical guidance."
  },
  {
    slug: "wa-iyyaka-nastain-medium",
    description: `Wa Iyyaka Nasta'in (Medium) is a medium-sized dua book that provides a carefully selected collection of supplications (duas) drawn from the Quran and the authentic Sunnah of Prophet Muhammad. The title comes from the opening verse of Surah Al-Fatiha — "You alone we worship, and You alone we ask for help" — reflecting the book's purpose as a tool for directing the believer's requests and needs toward Allah, the only One who has the power to grant them. This medium-format edition is designed for regular daily use, offering enough content to cover a wide range of situations while remaining portable enough to be carried in a bag or kept on a bedside table.

The book organizes the duas into practical categories that correspond to the different situations and needs that a person encounters in their daily life. The morning and evening adhkar (remembrances) are presented at the beginning, as the Prophet specifically recommended beginning and ending each day with the remembrance of Allah for protection and blessing. The duas for the five daily prayers — including the dua before wudu, the dua after wudu, the adhan and iqamah responses, the dua al-istiftah (opening supplication of prayer), the dua for ruku and sujud, and the supplications for the tashahhud and the final salam — are provided with Arabic text, transliteration, and translation.

The daily life section includes duas for waking up and going to sleep, for entering and leaving the home, for entering and leaving the mosque, for before and after eating and drinking, for wearing new clothes, for traveling, for visiting the sick, for attending a funeral, and for numerous other common situations. Each dua is presented with its source reference — the specific hadith collection and number from which it is taken — allowing the reader to verify its authenticity. The Arabic text is written in a clear, large font that makes it easy to read, and the transliteration uses a system that allows readers who are not proficient in Arabic to pronounce the words correctly.

The spiritual needs section includes duas for seeking forgiveness (istighfar), for expressing gratitude (shukr), for asking for guidance (istikhara), for protection from harm and evil, for relief from anxiety and distress, for success in this world and the next, and for the well-being of family members and the Muslim community. The duas of the prophets — drawn from the Quranic narratives — are included as models of how the greatest servants of Allah communicated with their Lord. The book also includes the famous dua of the Prophet Ibrahim, the dua of Prophet Ayyub during his illness, the dua of Prophet Yunus from the belly of the whale, and the dua of Prophet Musa before his encounter with Pharaoh.

The medium-format edition distinguishes itself from the small and large editions in the market by its balanced approach to content selection and physical design. It contains more duas than a pocket-sized edition while remaining more focused and portable than a comprehensive reference work. The binding is designed for durability, allowing the book to withstand regular use without falling apart. The pages are made from quality paper that can endure repeated handling. Wa Iyyaka Nasta'in (Medium) is suitable for daily use at home, in the mosque, during travel, and in the workplace, providing Muslims with a reliable and accessible collection of duas for every occasion.`,
    metaDescription: "A medium-format dua collection with authentic supplications for daily prayers, morning and evening adhkar, travel, and spiritual needs."
  },
  {
    slug: "wa-iyyaka-nastain-small",
    description: `Wa Iyyaka Nasta'in (Small) is a compact, pocket-sized dua book that provides an essential selection of the most important supplications from the Quran and the authentic Sunnah, designed for Muslims who want a portable reference that they can carry with them at all times. Like the medium-format edition, the title is derived from Surah Al-Fatiha — "You alone we worship, and You alone we ask for help" — and the small format is specifically engineered for convenience and portability, making it possible to have a collection of authentic duas available whenever the need arises.

The small format necessitates a more selective approach to content compared to the medium and large editions. The duas included in this compact version represent the essential core that every Muslim should know and use regularly. The selection process prioritizes duas that the Prophet himself recited most frequently and those that he specifically recommended to his companions. The morning and evening adhkar form the backbone of the collection, as these are the duas that the Prophet emphasized most strongly, describing them as sufficient for anyone who recites them. The duas for before and after eating, for entering and leaving the home, for sleeping and waking, and for before and after using the restroom are included as the basic daily duas that every Muslim should memorize and practice.

The prayer section includes the essential duas of salah — the dua al-istiftah, the dua for ruku, the duas for the two sujuds, the tashahhud, and the dua for the final sitting before the salam. These are the duas that are needed most frequently, as they are recited in every unit of every obligatory and voluntary prayer. The book also includes the dua of qunut for the witr prayer and the duas for the Eid prayer, providing coverage for the essential situations that a practicing Muslim encounters in their regular worship.

The spiritual supplications section includes the most important duas for seeking forgiveness, the dua of istikhara for seeking Allah's guidance in decisions, the dua for protection from harm, the dua for relief from difficulty, and the dua for the deceased. The short but powerful duas from the Quran — including Ayat al-Kursi, the last two verses of Surah Al-Baqarah, and the three quls (Al-Ikhlas, Al-Falaq, and An-Nas) — are included as the most essential daily recitations that the Prophet recommended for protection and blessing.

The physical design of the small edition prioritizes portability and durability. The book is sized to fit comfortably in a pocket, a small purse, or the glove compartment of a car. Despite its small size, the Arabic text is printed in a font that is large enough to be readable, and the transliteration is included for those who need assistance with pronunciation. The binding is flexible yet sturdy, designed to withstand being carried and opened repeatedly without the pages falling out. The cover material is resistant to wear and moisture, protecting the book from the daily handling that a pocket-sized reference inevitably receives.

Wa Iyyaka Nasta'in (Small) is particularly suitable for travelers, students, and busy professionals who may not have space to carry a larger dua collection but who want to maintain a regular practice of making dua throughout their day. It also serves as an excellent introduction to the dua literature for new Muslims and for young people who are learning the basic supplications. The small format can also be given as a gift alongside larger Islamic books, serving as a companion volume that the recipient can use for their daily dua practice while the larger books address more comprehensive topics. Despite its compact size, this edition maintains the same standard of content authenticity and scholarly sourcing that characterizes the larger editions in the series.`,
    metaDescription: "A pocket-sized dua book with essential daily supplications for salah, morning and evening adhkar, meals, travel, and personal protection."
  },
  {
    slug: "waaldain-ka-ehtsaab",
    description: `Waaldain ka Ehtsaab is a Urdu-language book that addresses the serious topic of a child's accountability before Allah regarding their treatment of their parents, arguing that the rights of parents in Islam are among the most weighty obligations that a person carries and that the neglect of these rights is one of the most commonly overlooked sins in the Muslim community. The word "ehtsaab" in the title carries the meaning of accountability, reckoning, and careful consideration, and the book asks its readers to take a serious and honest account of how they are treating their parents — and how Allah will hold them accountable for that treatment on the Day of Judgment.

The book begins by establishing the Quranic basis for the rights of parents, citing the numerous verses in which Allah commands kindness, respect, and obedience to parents — often immediately after commanding worship of Himself, indicating the gravity of this obligation in the Islamic framework. The verse in Surah Al-Isra in which Allah says "Your Lord has decreed that you worship none but Him and that you be kind to parents" receives detailed treatment, with each component of the command analyzed for its linguistic implications and practical requirements. The Quranic statements about the mother's suffering during pregnancy, childbirth, and nursing are discussed as evidence of the magnitude of the debt that children owe to their parents.

The hadith literature on the rights and status of parents is presented extensively, including the hadith in which the Prophet identified the mother's pleasure as the path to Allah's pleasure and the mother's displeasure as the path to Allah's displeasure. The hadith in which a man asked the Prophet about who was most deserving of his good companionship, and the Prophet replied "Your mother" three times before saying "Your father" on the fourth, is analyzed for its implications about the relative weight of the mother's and father's rights. The hadith warning against the severity of the punishment for one who dishonors their parents, and the hadith stating that the major sins include disobeying parents, are cited as evidence of the seriousness of this obligation.

The book distinguishes between the basic obligations that every child owes to their parents — including financial support if needed, physical care in old age, respectful speech and behavior, and obedience in matters that do not contradict Islamic law — and the higher levels of excellence (ihsan) that the Prophet encouraged, including seeking their counsel, honoring their friends, praying for them after their death, and maintaining the ties of kinship that they established during their lifetime. The book argues that many Muslims fulfill the basic obligations but neglect the higher levels of ihsan, and that achieving ihsan toward parents is a distinguishing characteristic of the righteous believer.

The section on accountability (ehtsaab) is the most impactful part of the book. It asks readers to honestly evaluate their treatment of their parents against the Islamic standard, pointing out the common ways in which children fail their parents — including speaking to them harshly, showing impatience with their physical limitations, prioritizing work or social life over spending time with them, and neglecting their emotional needs. The book describes the scenes of the Day of Judgment in which parents will confront their children and demand their rights, drawing upon the relevant hadith to create a vivid picture of the accountability that awaits. Waaldain ka Ehtsaab is written in direct and emotionally powerful Urdu that is designed to move the reader to immediate action in improving their relationship with their parents before it is too late.`,
    metaDescription: "A powerful Urdu book on a child's accountability to parents before Allah, citing Quranic and hadith evidence on parental rights and consequences."
  },
  {
    slug: "waaldein",
    description: `Waaldein is a comprehensive Urdu-language book that provides detailed guidance on the Islamic concept of parent-child relationships, covering both the rights of parents over their children and the responsibilities of parents toward their children. The book recognizes that the parent-child relationship in Islam is a two-way obligation: children owe their parents obedience, respect, and care, while parents owe their children proper upbringing, education, financial support, and moral guidance. This comprehensive approach makes the book valuable for readers in both roles — as children who need to fulfill their obligations to their parents, and as parents who want to raise their children according to Islamic principles.

The book begins with the foundational Islamic principle that parents occupy a status second only to Allah and His Messenger in terms of the respect and obedience they are owed. The Quranic verses and prophetic hadith that establish this status are presented with commentary, showing how the Islamic reverence for parents is rooted not merely in cultural tradition but in explicit divine command. The book explains that the obligation to honor parents extends beyond their lifetime through the maintenance of their legacy, the honoring of their friends, and the fulfillment of any promises or commitments they made during their lives.

The section on the rights of parents provides a detailed treatment of the specific obligations that children owe. Financial support, physical care during illness and old age, respectful and gentle speech, seeking their advice in important matters, visiting them regularly, including them in family events, praying for their forgiveness and well-being, and avoiding anything that causes them sadness or distress are all discussed as specific obligations that Islam requires from every Muslim child. The book addresses common questions about the limits of parental obedience, explaining that obedience to parents is required in all matters except those that involve disobedience to Allah.

The section on the responsibilities of parents is equally comprehensive. The Islamic obligation to choose a good name for the child, to perform the aqiqah, to circumcise male children, to provide proper religious education, to teach the child the Quran and the basics of Islamic faith and practice, to protect the child from harmful influences, to provide for the child's physical needs, and to treat all children equitably are all discussed as binding obligations. The book emphasizes the hadith in which the Prophet described every child as being born in a state of fitrah (natural purity) and attributed the child's subsequent religious identity to the parents, placing the primary responsibility for the child's spiritual development squarely on the parents' shoulders.

The practical guidance section addresses the real-world challenges of parent-child relationships in the modern context. Generational differences in cultural expectations, the challenge of maintaining Islamic values in a secular society, the situation of parents and children who live in different countries, the care of elderly parents, and the resolution of conflicts between parents and adult children are all discussed with sensitivity and practical advice. The book draws upon the examples of the companions and their treatment of their parents, and of the Prophet's own treatment of his children and grandchildren, as models of the ideal parent-child relationship. Waaldein is written in clear, accessible Urdu and is suitable for readers of all ages who want to understand and fulfill their obligations within this most important of human relationships.`,
    metaDescription: "A comprehensive Urdu guide on Islamic parent-child relationships covering parental rights, obligations, upbringing, and practical family advice."
  },
  {
    slug: "wafa-ka-paikar",
    description: `Wafa Ka Paikar, meaning "Symbol of Loyalty" or "Exemplar of Faithfulness," is a Urdu-language book that explores the Islamic concept of loyalty (wafa) through biographical accounts, Quranic analysis, and practical guidance, presenting loyalty as one of the most important moral virtues in Islam. The book argues that loyalty — to Allah, to the Prophet, to one's word and commitments, to family, to friends, and to the community — is a thread that runs through the entire fabric of Islamic morality and that its cultivation is essential for both personal spiritual development and the health of the Muslim community.

The book begins with the most fundamental dimension of loyalty: loyalty to Allah. The Quranic verses that describe the believers as those who are loyal and true to their covenant with Allah are analyzed, and the concept of bay'ah (pledge of allegiance) — both the general bay'ah that every Muslim makes through the shahadah and the specific bay'ah that the companions made to the Prophet — is discussed as the primary expression of loyalty in Islam. The book explains that loyalty to Allah is not merely a verbal declaration but a lived commitment that manifests in obedience to His commands, avoidance of His prohibitions, patience with His decrees, and sincerity in all acts of worship. The consequences of disloyalty to Allah — including the loss of faith, the weakening of moral character, and the exposure to spiritual harm — are discussed as warnings.

The section on loyalty to the Prophet Muhammad examines what it means to be loyal to the Prophet after his death. The book argues that loyalty to the Prophet is expressed through following his Sunnah, loving him more than one's own self, defending his honor against those who seek to undermine it, and supporting his mission of conveying Islam to humanity. The examples of the companions who demonstrated extraordinary loyalty to the Prophet — including Abu Bakr's unwavering support during the most difficult moments, Umar's devotion, Ali's sacrifice, and the loyalty of the women companions such as Khadijah, Sumayyah, and Asma bint Abi Bakr — are narrated as historical models of prophetic loyalty.

The section on loyalty in human relationships covers the Islamic principles governing loyalty between spouses, between parents and children, between friends, and between members of the Muslim community. The concept of the covenant (mithaq) that underlies every significant human relationship in Islam is discussed, showing how marriage, friendship, and community membership are all understood in Islam as binding commitments that create mutual obligations of loyalty, support, and honesty. The book provides guidance on how to maintain loyalty in an era of easy disconnection and broken commitments, arguing that the Islamic virtue of wafa requires Muslims to resist the modern tendency toward transactional and disposable relationships.

The biographical section of the book presents the stories of historical Muslim figures who exemplified the virtue of loyalty in extraordinary ways. The loyalty of Abu Bakr to the Prophet, the loyalty of Bilal to Islam despite severe persecution, the loyalty of the Muslims of Madinah to their Meccan guests during the Hijrah, and the loyalty of Muslim historical figures to their principles and communities under the most challenging circumstances are all narrated as sources of inspiration. Wafa Ka Paikar is written in eloquent Urdu that combines scholarly depth with literary beauty, making it an engaging and inspiring read for anyone who values the virtue of loyalty and wants to strengthen this quality in their own character.`,
    metaDescription: "A Urdu book on the Islamic virtue of loyalty covering faithfulness to Allah, the Prophet, family, friends, and community through biographical stories."
  },
  {
    slug: "walqalam-wama-yasturun",
    description: `Walqalam wama Yasturun is a Urdu-language book whose title is drawn directly from the Quranic verse in Surah Al-Qalam: "Nun. By the pen and what they write." This verse, which is one of the oaths that Allah swears by in the Quran, serves as the foundation for a book that explores the Islamic perspective on writing, knowledge, documentation, and the power of the written word. The book examines what the Quran and the Sunnah teach about the importance of writing, the responsibility that comes with the ability to write, and the role that writing has played in the preservation and transmission of Islamic knowledge throughout history.

The book begins with a detailed analysis of the Quranic verse from which it takes its title. The significance of Allah swearing by the pen — an inanimate object — is discussed with reference to the classical tafseer literature, which explains that the oath by the pen highlights the immense importance of writing, knowledge, and documentation in the divine scheme. The relationship between this verse and other Quranic verses that mention writing — including the verses about the Preserved Tablet (Lawh al-Mahfuz), the revelation of the Quran in writing, and the recording of human deeds by the angels — is explored to build a comprehensive picture of the Quranic view of writing as a divinely ordained tool for knowledge preservation and divine communication.

The section on the Prophetic encouragement of writing documents the numerous hadith in which the Prophet Muhammad valued the written word. The Prophet's designation of scribes to record Quranic revelation, his instruction to write treaties and agreements, his encouragement of recording knowledge, and his statement that the first thing created by Allah was the pen are all discussed as evidence of the importance of writing in the prophetic framework. The book explains how the early Muslim community's commitment to writing — as opposed to the primarily oral cultures that surrounded them — was instrumental in the preservation of the Quran, the hadith, and the vast corpus of Islamic scholarship that was produced in the first centuries of Islam.

The historical section traces the development of writing and book production in the Muslim civilization. The establishment of the first libraries, the development of Arabic calligraphy as both an art form and a means of preserving sacred texts, the paper-making industry that Muslim scholars established, the translation movement that brought the knowledge of ancient civilizations into Arabic, and the system of ijazah (certification) that ensured the accuracy of textual transmission are all documented as chapters in the story of how the Muslim civilization used the pen to build one of the most productive intellectual traditions in human history.

The contemporary section addresses the role of writing in the modern Muslim world, including the challenges and opportunities created by digital technology. The responsibility of Muslim writers, journalists, bloggers, and social media users to use the power of the written word responsibly is discussed with reference to Islamic principles. The book warns against the misuse of writing for spreading falsehood, creating division, or promoting harmful ideas, while encouraging the use of writing for education, spiritual guidance, and the promotion of truth and justice. Walqalam wama Yasturun is written in scholarly yet accessible Urdu that makes it suitable for readers interested in Islamic intellectual history, for students and scholars, and for anyone who wants to understand the Islamic perspective on the power and responsibility of writing.`,
    metaDescription: "A Urdu book exploring the Islamic perspective on writing, knowledge, and documentation based on the Quranic oath by the pen and history."
  },
  {
    slug: "waqiyah-maeraj-aur-uus-kai-mushahidaat",
    description: `Waqiyah Maeraj Aur uus Kai Mushahidaat, meaning "The Event of Miraj and Its Observations," is a detailed Urdu-language account of the Night Journey and Ascension (Isra and Mi'raj) — the extraordinary event in which Prophet Muhammad was transported from Makkah to Jerusalem and then ascended through the heavens to the presence of Allah. The book provides a comprehensive treatment of this pivotal event, drawing upon the Quranic account, the extensive hadith literature, and the classical scholarly commentaries to present a vivid and detailed narrative that captures both the external events of the journey and the profound spiritual experiences that accompanied them.

The book begins by establishing the factual basis of the Isra and Mi'raj through the Quranic references and the authentic hadith narrations. The Quranic verse at the beginning of Surah Al-Isra that mentions the transportation of the Prophet from the Sacred Mosque to the Farthest Mosque is analyzed with its linguistic nuances and contextual background. The hadith of the Mi'raj, which the Prophet narrated to the companions and which has been transmitted through multiple chains of narration, is presented in a comprehensive version that includes the details of the journey from Makkah to Jerusalem, the leadership of the prophets in prayer at Al-Aqsa, and the ascension through the seven heavens. The book addresses the common questions about the nature of this journey — whether it was physical or spiritual, whether it occurred during sleep or while awake — with reference to the scholarly consensus and the evidences that support each position.

The narrative of the journey through the seven heavens forms the most detailed and dramatic section of the book. The Prophet's encounter with Prophet Adam in the first heaven, with Prophet Isa and Prophet Yahya in the second, with Prophet Yusuf in the third, with Prophet Idris in the fourth, with Prophet Harun in the fifth, with Prophet Musa in the sixth, and with Prophet Ibrahim in the seventh is narrated for each heaven, along with the specific observations that the Prophet made at each level. The descriptions of Paradise and Hellfire that the Prophet witnessed during his journey are presented with the vivid detail found in the hadith, giving readers a sense of what the Prophet saw and experienced.

The section on the divine encounter at Sidrat al-Muntaha (the Lote Tree of the Utmost Boundary) describes the point beyond which no creation had previously passed, where the Prophet received the command for the five daily prayers and experienced the closest proximity to Allah that any human being has ever attained. The dialogue between Allah and the Prophet, the original prescription of fifty daily prayers, and the intercession of Prophet Musa that reduced the number to five are narrated as they appear in the hadith, with commentary on the theological and spiritual implications of each element.

The mushahidaat (observations) section of the book analyzes what the Mi'raj reveals about the unseen world, the structure of the heavens, the reality of the hereafter, and the special status of Prophet Muhammad among all the messengers of Allah. The book argues that the Mi'raj was not merely a miracle intended to demonstrate the Prophet's special status but a journey with profound theological and spiritual content that expands the believer's understanding of the reality that lies beyond the physical world. The practical lessons that Muslims should draw from the Mi'raj — including the importance of the five daily prayers, the reality of the unseen, and the special love that Allah has for His Prophet — are summarized in a concluding section. Waqiyah Maeraj Aur uus Kai Mushahidaat is written in narrative Urdu that is both scholarly and emotionally engaging, making this extraordinary event accessible and meaningful for contemporary readers.`,
    metaDescription: "A detailed Urdu account of the Prophet's Night Journey and Ascension covering the seven heavens and the gift of five daily prayers."
  },
  {
    slug: "wasiyati",
    description: `Wasiyati, meaning "My Will" or "My Advice," is a personal and reflective Urdu-language book that takes the form of a spiritual testament — a document of advice, guidance, and wisdom that the author addresses to their readers as a sincere expression of what they consider to be the most important lessons they have learned from a lifetime of religious study, spiritual practice, and observation of human experience. The book belongs to the rich Islamic literary tradition of wasiyyah (will, advice, and testament), in which scholars, spiritual guides, and experienced believers have distilled their wisdom into concise and impactful works that serve as spiritual legacies for future generations.

The book opens with the author's reflection on the brevity and uncertainty of human life, establishing the urgency of the advice that follows. The Quranic verses and hadith that describe life as a fleeting shadow, a brief enjoyment, and a test whose results will be experienced in the eternal hereafter are cited as the foundation for the author's approach. The book argues that the most valuable thing a person can leave behind is not wealth or property but sound advice rooted in Islamic knowledge and sincere concern for others' wellbeing. The format of the wasiyyah — a direct address from the author to the reader — creates an intimate and personal tone that distinguishes this book from conventional Islamic educational works.

The first and most central piece of advice concerns the correction of one's relationship with Allah. The author emphasizes the importance of sincerity (ikhlas) in all acts of worship, warning against the subtle forms of showing off (riya) that can corrupt even the most externally pious-looking deeds. The obligation of fulfilling the five daily prayers with concentration and humility, the importance of regular Quran recitation, the practice of seeking forgiveness (istighfar) and giving thanks (shukr), and the cultivation of constant awareness of Allah's presence (muraqabah) are presented as the essential practices of a healthy spiritual life. The author draws upon the examples of the pious predecessors to show how these practices transform a person's inner state.

The second major piece of advice concerns the treatment of other people. The author discusses the importance of fulfilling the rights of parents, maintaining family ties, treating neighbors with kindness, honoring the rights of spouses and children, and being honest and fair in all dealings. The book addresses the common spiritual diseases that damage human relationships — including jealousy (hasad), backbiting (ghibah), slander (buhtan), and anger — and provides guidance on how to recognize and cure these diseases. The author argues that a person's religion is not complete until they wish for others what they wish for themselves.

The third piece of advice concerns preparation for death and the hereafter. The author discusses the importance of writing a proper Islamic will, settling debts, seeking forgiveness from those one has wronged, and maintaining a regular practice of reflecting on death as a means of prioritizing one's life correctly. The book describes the process of death and the events that follow according to the authentic Islamic sources, not to frighten the reader but to motivate sincere preparation for the inevitable meeting with Allah.

The book concludes with dua — supplications that the author makes for the reader's guidance, forgiveness, and success in both this life and the next. The warmth and sincerity of these final prayers reflect the genuine concern that permeates the entire work. Wasiyati is written in eloquent and accessible Urdu that makes its advice applicable to readers from all walks of life, and it serves as both a practical spiritual guide and a model of the Islamic tradition of sincere advice (nasihah) that is considered one of the highest forms of worship.`,
    metaDescription: "A reflective Urdu spiritual testament offering sincere advice on sincerity in worship, human relations, disease of the heart, and the hereafter."
  },
  {
    slug: "what-a-muslim-should-believe",
    description: `What a Muslim Should Believe is an English-language book that provides a clear, systematic, and accessible exposition of the core beliefs of Islam — the articles of faith (arkan al-iman) that every Muslim is required to know, understand, and accept as fundamental to their identity as a believer. The book is designed for Muslims who want to ensure that their understanding of Islamic theology is correct and complete, for new Muslims who are learning the fundamentals of their new faith, and for non-Muslims who want an accurate and authoritative account of what Muslims actually believe.

The book follows the classical framework of the six articles of faith as established in the famous hadith of Jibril, in which the Prophet defined iman (faith) as belief in Allah, His angels, His revealed books, His messengers, the Day of Judgment, and divine decree (qadar) — both the good and the evil thereof. Each article of faith is treated in a dedicated chapter that covers its definition, its textual basis in the Quran and Sunnah, its theological implications, and the common misconceptions or errors that people sometimes fall into regarding it.

The chapter on belief in Allah is the most extensive, reflecting the centrality of tawheed (divine oneness) to the Islamic belief system. The book explains the three categories of tawheed — the oneness of Allah's lordship, the oneness of His worship, and the oneness of His names and attributes — with clarity and precision. The Islamic understanding of Allah's attributes is discussed, showing how Islam affirms the attributes that Allah has described Himself with in the Quran and that the Prophet has ascribed to Him in the hadith, without distorting their meanings, denying them, asking how they are, or likening them to the attributes of created things. The common errors of shirk (associating partners with Allah) are identified and explained, helping readers recognize and avoid forms of polytheism that may be subtle or culturally normalized.

The chapter on the angels explains who the angels are, their nature as beings created from light who do not disobey Allah, the specific roles assigned to major angels (Jibril, Mika'il, Israfil, Azrael, and the angels who record human deeds), and the relationship between the angelic realm and the human world. The chapters on the revealed books and the messengers provide overviews of the scriptures that Allah revealed to humanity (the Torah, the Psalms, the Gospel, and the Quran) and the major prophets, with emphasis on the finality of Prophet Muhammad's messengership and the abrogation of previous scriptures by the Quran.

The chapter on the Day of Judgment provides a comprehensive description of what Islam teaches about the end of the world, the resurrection, the accounting of deeds, the weighing on the scales, the crossing of the bridge over the Hellfire, and the ultimate destinations of Paradise and Hellfire. The chapter on divine decree (qadar) addresses one of the most intellectually challenging aspects of Islamic theology, explaining the relationship between Allah's prior knowledge and decree and human free will and choice. The book presents the mainstream Sunni position on this topic while acknowledging its complexity and providing practical guidance on how to approach this belief in a way that strengthens rather than undermines faith. What a Muslim Should Believe is written in clear, jargon-free English that makes theological concepts accessible without oversimplifying them, and it serves as a reliable reference for anyone who wants to understand the essential creed of Islam.`,
    metaDescription: "An English exposition of Islamic creed covering belief in Allah, angels, revealed books, prophets, the Day of Judgment, and divine decree."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
