const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "fazail-e-sahaba",
    description: `Fazail-e-Sahaba (Virtues of the Companions) is one of the most beloved and widely read Urdu-language Islamic books in the Indian subcontinent, compiled by the renowned Hadith scholar Maulana Muhammad Zakariyya Kandhlvi (1898–1982), who served as a prominent teacher at Saharanpur's Mazahir-ul-Uloom for decades. This celebrated work forms part of the famous "Fazail" series alongside Fazail-e-Amaal and Fazail-e-Sadaqat, and has been instrumental in nurturing deep love and reverence for the Prophet's (ﷺ) companions among millions of Urdu-speaking Muslims across Pakistan, India, Bangladesh, and the diaspora. The book draws exclusively from authentic hadith sources — primarily Sahih Al-Bukhari, Sahih Muslim, Sunan At-Tirmidhi, and other canonical collections — to present the extraordinary qualities, sacrifices, and spiritual ranks of the Sahaba (may Allah be pleased with them all).

The book is organized thematically, with chapters dedicated to the virtues of specific companions and groups of companions. Readers encounter detailed accounts of Abu Bakr as-Siddiq's unwavering faith and generosity, Umar ibn al-Khattab's justice and strength of character, Uthman ibn Affan's modesty and contributions to the Quran's compilation, and Ali ibn Abi Talib's knowledge and bravery. Separate chapters celebrate the merits of the mothers of the believers (the Prophet's wives), the ten companions promised Paradise, the participants in the Battle of Badr, the participants in the pledge of Ridwan at Hudaybiyah, the early converts to Islam, and the scholars among the companions. Each narration is presented with its full chain of authority and source reference, maintaining the scholarly rigor that Maulana Zakariyya was known for throughout his distinguished career as a hadith master.

What makes Fazail-e-Sahaba particularly impactful is its emotional and spiritual approach — rather than presenting dry historical facts, the book narrates the hadith in a style that moves the heart and inspires the reader to develop genuine love for those who sacrificed everything for Islam. The stories of the companions' sacrifices during persecution in Makkah, their bravery on the battlefields, their generosity in poverty, their devotion in worship, and their unwavering loyalty to the Prophet (ﷺ) serve as timeless role models for Muslims of every generation. At Rs.460, this affordable paperback remains one of the most commonly gifted Islamic books in Pakistani households, regularly studied in halaqah circles, Islamic schools, and Tablighi Jamaat gatherings throughout the Urdu-speaking world.`,
    metaDescription: "Fazail-e-Sahaba by Maulana Zakariyya Kandhlvi — authentic hadith-based virtues of the Prophet's companions in Urdu. Inspirational stories of the Sahaba."
  },
  {
    slug: "fazl-ul-baari",
    description: `Fazl-ul-Baari is a significant Urdu commentary on Sahih Al-Bukhari that occupies a respected place in the library of hadith scholarship accessible to Urdu-speaking audiences. Where Arabic commentaries like Fath al-Bari by Ibn Hajar al-Asqalani remain inaccessible to most Urdu readers, Fazl-ul-Baari bridges this gap by providing scholarly explanations of Bukhari's hadith in clear, fluent Urdu. The title "Fazl-ul-Baari" (The Grace of the Creator) reflects the author's recognition that understanding the Prophet's (ﷺ) traditions is itself a divine blessing granted to the seeker of knowledge. This work serves as an essential companion for anyone studying Sahih Al-Bukhari in Urdu — whether in formal madrasah settings, private study circles, or individual reading.

The commentary addresses the key challenges that readers face when approaching Sahih Al-Bukhari directly. Imam Bukhari's methodology of using chapter titles (tarajim) to convey fiqh rulings means that much of the scholarly content is embedded in headings rather than in the hadith text itself. Fazl-ul-Baari unpacks these subtle chapter headings, explaining the fiqh positions that Imam Bukhari intended to convey through his selection and arrangement of hadith. The commentary also explains obscure vocabulary, clarifies ambiguous chains of narration, resolves apparent contradictions between different hadith, and provides historical context for the events and personalities mentioned in the narrations. Where multiple scholarly interpretations exist for a particular hadith, the commentary presents the major positions with their supporting arguments, allowing readers to understand the breadth of Islamic scholarly tradition.

The work also addresses contemporary relevance by connecting the hadith teachings to modern Muslim life — explaining how the Prophet's (ﷺ) guidance on commerce, social relations, worship, ethics, and governance applies to the challenges facing Muslims today. The Urdu prose is accessible enough for intermediate students yet sufficiently scholarly to satisfy advanced readers. The commentary includes cross-references to related hadith in other collections, references to relevant Quranic verses, and citations from major Arabic commentaries — making it a genuine gateway to the broader hadith literature for Urdu-speaking students. At Rs.700, Fazl-ul-Baari is an invaluable resource for madrasah students, Islamic university scholars, imams, and serious students of hadith who want to deepen their understanding of Sahih Al-Bukhari in their native language.`,
    metaDescription: "Fazl-ul-Baari — Urdu commentary on Sahih Al-Bukhari. Explains chapter titles, fiqh rulings, and hadith context. Essential hadith study resource. Buy at Bab-ul-Fatah."
  },
  {
    slug: "fikr-o-aqeedah-ki-gumrahiyan-aur-siraat-e-mustaqeem-k-taqazay",
    description: `Fikr-o-Aqeedah ki Gumrahiyan aur Siraat-e-Mustaqeem ke Taqazay (Deviation in Thought and Belief and the Demands of the Straight Path) is a thought-provoking Urdu theological work that tackles one of the most pressing challenges facing contemporary Muslims — the intellectual and ideological confusion that has led many believers away from orthodox Islamic theology toward various forms of deviation, whether in the form of extreme literalism, excessive rationalism, sectarian prejudice, or wholesale adoption of Western philosophical frameworks incompatible with Islamic revelation. Priced at Rs.570, this book serves as both a diagnostic tool that identifies the roots of theological deviation and a prescriptive guide that outlines what orthodox Islamic belief requires from Muslims living in the modern world.

The book begins with a systematic analysis of the major categories of ideological deviation (gumrahiyan) affecting Muslim thought today. It examines how the uncritical adoption of Western secular philosophy has led some Muslims to question fundamental Islamic beliefs — the existence of angels, the reality of Jinn, the authenticity of revelation, and the finality of Prophethood. It critiques the extreme rationalist approach that attempts to subordinate revelation to human reason, showing how this methodology inevitably leads to either abandoning Islamic positions or distorting them beyond recognition. At the same time, the book addresses the opposite extreme — an uncritical, anti-intellectual approach to religion that rejects any analysis or explanation of Islamic beliefs, reducing faith to a set of unexamined slogans vulnerable to intellectual challenge.

The second half of the book articulates the "demands of the straight path" (Siraat-e-Mustaqeem ke Taqazay) — what authentic Islamic belief requires from Muslims in terms of intellectual engagement, spiritual development, and practical implementation. This section covers the Islamic approach to knowledge acquisition, the proper relationship between reason and revelation, the methodology for understanding ambiguous Quranic verses and hadith, the Islamic stance on sectarian differences, and the ethical and behavioral requirements that flow from correct belief. The author argues that true Islamic orthodoxy is not narrow-mindedness but a balanced, comprehensive approach that embraces intellectual rigor while maintaining submission to divine guidance. The book is particularly relevant for university students, young professionals, and educators who encounter ideological challenges in academic and professional settings. For Pakistani readers navigating the complex intellectual landscape of the modern world, this book provides a scholarly, well-reasoned, and practically actionable framework for maintaining sound Islamic belief while engaging constructively with contemporary ideas and challenges.`,
    metaDescription: "Fikr-o-Aqeedah ki Gumrahiyan — Urdu book on theological deviations and the demands of the Straight Path. Intellectual challenges to Islamic belief addressed."
  },
  {
    slug: "finger-counter-1pc-islamic-tasbeeh",
    description: `This Finger Counter (1Pc) — Islamic Tasbeeh is a practical, modern digital device designed to help Muslims maintain accurate counts during their daily dhikr (remembrance of Allah), tasbeeh recitations, and various forms of worship that require keeping track of repetitions. Priced at Rs.900, this single-piece finger counter represents a significant upgrade over traditional prayer beads (misbaha) for those who prefer a more discreet, efficient, and accurate counting method. The device slips comfortably onto the index finger and uses a simple mechanical click mechanism — each press of the thumb advances the digital counter by one, allowing the user to maintain their count without diverting attention from their recitation.

The design of this finger counter is specifically tailored for Islamic worship contexts. Unlike smartphone counting apps that can be distracting and inappropriate during prayer or dhikr, this dedicated device requires no screen interaction, produces no sound, and maintains a low profile that does not attract attention in mosques, during congregational prayers, or in public settings. The device is lightweight, durable, and comfortable enough for extended use — whether during the daily recitation of morning and evening adhkar, the performance of taraweeh prayers during Ramadan, or the extended dhikr sessions preferred by many spiritual practitioners. The digital display provides a clear, easily readable count that resets to zero with a simple mechanism, eliminating the uncertainty that can sometimes occur with traditional bead counting.

This finger counter is particularly useful for several categories of worship. For those performing the daily recommended tasbeeh of 33, 33, and 33 after each obligatory prayer (SubhanAllah 33 times, Alhamdulillah 33 times, Allahu Akbar 33 times), the counter ensures perfect accuracy without breaking concentration. For those who have set themselves specific daily dhikr targets — such as 100 times Istighfar, 100 times Salawat on the Prophet (ﷺ), or the recitation of specific formulas recommended by spiritual guides — the counter provides reliable tracking. For Quran students counting their daily recitation pages, for Hajj and Umrah pilgrims tracking their circumambulations or Sa'i rounds, and for anyone who finds traditional bead counting cumbersome or imprecise, this digital finger counter offers a practical, affordable, and reliable alternative. The device is also an excellent gift for elderly Muslims who may find small prayer beads difficult to manipulate, and for young Muslims who are building their daily worship habits and benefit from the motivational feedback of a visible counter.`,
    metaDescription: "Digital Finger Counter Tasbeeh — modern Islamic dhikr counting device. Lightweight, discreet, accurate. Ideal for daily adhkar and tasbeeh. Buy online Pakistan."
  },
  {
    slug: "fiqh-according-to-quran-sunnah-2vol",
    description: `FIQH ACCORDING TO QURAN & SUNNAH — 2 Volume Set is a comprehensive English-language work of Islamic jurisprudence that derives its rulings directly from the primary sources of Islamic law — the Quran and the authentic Sunnah of Prophet Muhammad (ﷺ) — presenting a methodology of fiqh that prioritizes textual evidence over customary practice, regional tradition, or the opinions of individual scholars. Priced at Rs.7,550 for the complete two-volume set, this work represents a significant scholarly effort to make Islamic legal reasoning accessible to English-speaking Muslims while grounding every ruling in verifiable evidence from the revealed texts.

The two-volume set covers the complete spectrum of Islamic ritual and practical law. The first volume addresses purification (taharah) in exhaustive detail — the types of water, the rulings on impurities, ablution (wudu), ritual bath (ghusl), dry ablution (tayammum), menstruation and post-natal bleeding, and the rulings related to toilets and bathroom etiquette. It then covers the prayer (salah) comprehensively — the times of prayer, the conditions and prerequisites, the obligatory elements, the recommended acts, the descriptions of each obligatory and voluntary prayer, the Friday prayer, the Eid prayers, the funeral prayer, and the prayer during travel, illness, fear, and other special circumstances. Volume two covers the remaining pillars of Islam — fasting (sawm) with all its rules and exemptions, Zakat with detailed calculation methods for different types of wealth, and Hajj and Umrah with step-by-step instructions for every ritual. The volume also covers marriage, divorce, food and drink regulations, clothing and adornment, trade and business transactions, inheritance, and the Islamic code of conduct.

What distinguishes this work from many other English fiqh books is its consistent evidential methodology. Every ruling is supported by references to specific Quranic verses and authenticated hadith, with full citations of the hadith sources and assessments of their authenticity. When scholars differ on an issue, the work presents the major positions with their evidence and indicates which position is best supported by the texts. This approach empowers English-speaking Muslims to understand not just what the ruling is but why the ruling is what it is — enabling them to engage with Islamic law as informed participants rather than passive recipients of culturally transmitted practices. The two-volume hardcover set is designed for durability, with clear typography, generous margins for notes, and comprehensive indices that make it a practical reference tool for daily use. For Islamic schools offering English-medium fiqh courses, for Muslim families building their home libraries, and for anyone seeking a reliable, evidence-based English guide to Islamic practice, this two-volume set provides an outstanding scholarly resource.`,
    metaDescription: "Fiqh According to Quran & Sunnah 2-Vol Set — comprehensive English Islamic jurisprudence. Evidence-based rulings on Salah, fasting, Zakat, Hajj. Premium hardcover."
  },
  {
    slug: "fiqh-kitab-o-sunnat",
    description: `Fiqh Kitab-o-Sunnat (Jurisprudence of the Book and the Sunnah) is a substantial Urdu-language reference work on Islamic jurisprudence that systematically presents Islamic legal rulings derived directly from the Quran and the authenticated Prophetic traditions. Priced at Rs.3,500, this comprehensive volume serves as an authoritative fiqh manual for Urdu-speaking scholars, students, and serious practitioners who want access to Islamic legal rulings grounded in primary textual evidence rather than filtered through any single school of jurisprudence (madhhab). The work reflects the growing trend in contemporary Islamic scholarship toward evidence-based fiqh that respects the classical schools while encouraging direct engagement with the source texts.

The book's scope is remarkably comprehensive, covering every major area of Islamic law that a Muslim encounters in daily life. The purification section addresses every conceivable scenario related to taharah — the classification of waters, the types of impurities and their removal, the detailed rulings of wudu and ghusl, the special cases of tayammum, the rulings for women regarding menstruation, istihadha, and nifas, and the fiqh of najasa (ritual impurity) in clothing, buildings, and food. The prayer section is equally exhaustive, covering the obligatory prayers with detailed descriptions of every rak'ah, the supererogatory prayers (rawatib, tahajjud, duha, awabin), the congregational prayer, the Friday sermon and prayer, Eid prayers, funeral prayers, the prayer of the traveler and the sick, the prayer during fear, and the prayer of the eclipse and Istisqa. Each ruling is accompanied by the relevant Quranic verse or hadith evidence with full chain references.

Beyond ritual worship, Fiqh Kitab-o-Sunnat covers the full spectrum of Islamic muamalat (social transactions) — including the detailed fiqh of marriage (nikah) from the proposal through the contract, mahr, rights and obligations of spouses, and the various forms of divorce (talaq, khula, faskh). The book addresses business transactions (buyu'), interest (riba) and its modern manifestations, endowments (waqf), inheritance (mirath) with calculation examples, food and clothing regulations, medical ethics, and the Islamic code of social conduct. The Zakat section provides detailed guidance on calculating Zakat for various types of wealth — gold, silver, cash, livestock, agricultural produce, and business inventory — making it a practical financial planning tool as well as a religious reference. The fasting section covers the fiqh of Ramadan fasting, voluntary fasting, expiatory fasting, and the various exemptions and accommodations. For Pakistani scholars, madrasah teachers, mosque imams, and educated Muslims who want a reliable, evidence-based Urdu fiqh reference, this book provides comprehensive coverage with the scholarly rigor that its important subject matter demands.`,
    metaDescription: "Fiqh Kitab-o-Sunnat — comprehensive Urdu jurisprudence based on Quran and Sunnah. Evidence-based rulings on worship, marriage, business, Zakat. Authoritative reference."
  },
  {
    slug: "fiqhi-ihkam-o-masail-2-vol-set",
    description: `Fiqhi Ihkam o Masail (2 Volume Set) is an ambitious Urdu-language publication that presents a systematic collection of Islamic legal rulings (masail) along with their underlying legal principles and maxims (ihkam) — providing readers not just with answers to specific fiqh questions but with the intellectual framework needed to understand how Islamic jurisprudence operates as a coherent legal system. Priced at Rs.4,500 for the complete two-volume set, this work bridges the gap between practical fiqh manuals (which provide rulings without explaining the reasoning) and theoretical usul al-fiqh texts (which explain methodology without addressing specific cases) — making it an invaluable resource for advanced students and scholars of Islamic law.

The two volumes are organized to guide the reader progressively from legal principles to their practical applications. Volume One establishes the foundational legal maxims (al-qawa'id al-fiqhiyyah) that govern Islamic jurisprudence — principles such as "matters are judged by their objectives," "certainty is not removed by doubt," "harm must be removed," "hardship begets facility," and "custom is authoritative." For each legal maxim, the book provides its textual basis in the Quran and Sunnah, explains its scope and limitations, illustrates its application through specific case examples, and discusses scholarly differences regarding its interpretation. This foundation enables readers to understand why specific rulings exist and how new cases can be analyzed using these established principles. The volume then applies these principles to the major areas of worship — purification and prayer — showing how the legal maxims operate in practice.

Volume Two extends the application of legal principles to the remaining areas of Islamic law — fasting, Zakat, Hajj, marriage, divorce, business transactions, food regulations, criminal law, and contemporary issues. The "masail" (specific legal questions) section of each chapter addresses the detailed questions that arise in daily Muslim life — questions that are rarely covered in general fiqh books but that practitioners encounter regularly. The book includes chapters on modern financial instruments (Islamic banking products, insurance, investment), medical ethics (organ donation, IVF, euthanasia), technology-related rulings (social media, digital transactions, cryptocurrency), and other contemporary issues — showing how the classical legal maxims provide a robust framework for addressing challenges that the early jurists could not have imagined. For Pakistani madrasah students studying for their fiqh examinations, for Islamic scholars issuing fatwas, and for educated Muslims who want to understand the reasoning behind Islamic rulings rather than simply memorizing them, this two-volume set provides the comprehensive, principled, and contemporary fiqh reference that Urdu Islamic scholarship urgently needs.`,
    metaDescription: "Fiqhi Ihkam o Masail 2-Vol Set — Urdu fiqh with legal maxims and contemporary rulings. Worship, transactions, modern issues. Advanced Islamic jurisprudence."
  },
  {
    slug: "five-pillars-of-islam-box-of-5-books-for-kids",
    description: `Five Pillars of Islam — Box of 5 Books for Kids is a beautifully designed children's educational set that introduces the foundational acts of Islamic worship to young Muslim readers in an engaging, age-appropriate, and visually appealing format. Priced at Rs.2,500, this boxed set contains five individual books — each dedicated to one of the five pillars of Islam: Shahadah (the declaration of faith), Salah (prayer), Zakat (charity), Sawm (fasting), and Hajj (pilgrimage). The set is specifically designed for children aged 4 to 10, making it an ideal resource for Muslim families, Islamic schools, weekend schools, and madrasah kindergarten programs throughout Pakistan and beyond.

Each book in the set is crafted to communicate its pillar's meaning, significance, and practical aspects through child-friendly language, colorful illustrations, relatable characters, and interactive elements. The Shahadah book explains what Muslims believe in simple terms — the oneness of Allah and the role of Prophet Muhammad (ﷺ) as the final messenger — using stories and analogies that young children can understand. The Salah book introduces the five daily prayers, explaining what each prayer is called, when it is performed, how many units (rak'at) it contains, and the basic movements and recitations — with illustrations showing children performing each posture correctly. The Zakat book teaches children about generosity, sharing, and the Islamic obligation to help those in need — using stories about children who share their toys, food, and savings with less fortunate members of their community. The Sawm book introduces Ramadan fasting in a sensitive, age-appropriate way — explaining why Muslims fast, how fasting makes us grateful and empathetic, and what children can do to participate in Ramadan even before they reach the age of fasting. The Hajj book takes children on a virtual pilgrimage to Makkah, explaining the Ka'bah, the rituals of Hajj, the story of Prophet Ibrahim (AS), and the joy of Eid al-Adha.

The production quality of this box set reflects its premium positioning — each book features durable cardstock pages that withstand young hands, vibrant full-color illustrations by Muslim artists, clear Urdu text in a child-friendly font, and a sturdy storage box that keeps the collection organized. The books include simple du'as related to each pillar, quiz questions that test comprehension, and activities (coloring, matching, tracing) that reinforce learning through engagement. Parents consistently report that this set has helped their children develop genuine enthusiasm for Islamic worship — children who complete the set are often found reminding their parents about prayer times, asking about Zakat calculations, and expressing excitement about fasting in Ramadan. For any Muslim family seeking to give their children a joyful, thorough, and visually beautiful introduction to Islam's five pillars, this boxed set delivers an outstanding educational experience.`,
    metaDescription: "Five Pillars of Islam Box Set — 5 colorful kids' books on Shahadah, Salah, Zakat, Sawm, Hajj. Ages 4-10. Premium illustrations. Gift set for Muslim children."
  },
  {
    slug: "flex-aaina-seerat-un-nabi-saw",
    description: `Flex Aaina Seerat un Nabi S.A.W is a distinctive decorative and educational product that combines the functionality of a flexible mirror with an elegant presentation of the Seerah (biography) of Prophet Muhammad (ﷺ) — creating a unique Islamic wall piece that serves both as a practical household item and as a constant spiritual reminder. Priced at Rs.1,000, this flex mirror is designed to be displayed in homes, Islamic schools, mosques, offices, and educational institutions where the Seerah of the Prophet (ﷺ) is celebrated and the daily reminder of his noble character can inspire better conduct in everyone who sees it.

The product features a high-quality flexible mirror surface surrounded by printed Seerah content that highlights key events and qualities from the life of the Prophet (ﷺ). The Seerah presentation includes important dates from the Prophet's (ﷺ) life, selected hadith about his character and conduct, and brief descriptions of major milestones — from his birth in Makkah and his first revelation in the Cave of Hira through his migration to Madinah, the establishment of the Islamic state, the treaties and battles, the conquest of Makkah, and his farewell pilgrimage. The design is produced on flexible, durable material that can be easily mounted on walls without special hardware — adhering to flat surfaces through its flex properties while maintaining the reflective quality of a functional mirror.

This product fills a unique niche in the Islamic household goods market by merging practical utility with spiritual education. A mirror is something that family members look into multiple times daily — and by surrounding this everyday item with reminders of the Prophet's (ﷺ) noble character, the product transforms a mundane activity into an opportunity for spiritual reflection. The Seerah content is carefully selected to be appropriate for all audiences — including children who are learning about the Prophet's (ﷺ) life for the first time. The visual design uses Islamic artistic elements — geometric patterns, calligraphic borders, and a color scheme that complements both traditional and contemporary home decor. The flex material is waterproof and easy to clean, making it suitable for bathrooms, bedrooms, and hallways. For Muslim families looking to create an Islamically enriched home environment, for Islamic school administrators seeking educational wall decor, or for anyone searching for a meaningful Islamic gift that combines beauty, utility, and spiritual value, this Flex Aaina Seerat un Nabi S.A.W provides a genuinely unique product that serves its purpose beautifully.`,
    metaDescription: "Flex Aaina Seerat un Nabi S.A.W — Islamic flex mirror with Seerah content. Decorative wall piece, functional mirror, spiritual reminder. Ideal home decor. Buy online."
  },
  {
    slug: "flower-rehal-7-inch",
    description: `Flower Rehal — 7 Inch is an elegant wooden book rest (rehal) featuring an intricately carved floral design that combines traditional Islamic craftsmanship with practical functionality for daily Quran reading and study. Priced at Rs.600, this compact rehal is perfectly sized for the most common Quran formats — medium-sized pocket Qurans, standard Mushaf editions, and most Urdu and English Islamic books. The 7-inch dimension refers to the width when the rehal is open and in use, making it a space-efficient choice for smaller prayer areas, bedside tables, office desks, and travel bags.

The flower design carved into the wooden panels reflects the rich tradition of Islamic decorative arts — where floral motifs have been used for centuries to adorn mosques, manuscripts, and household items as an expression of the beauty that Allah has placed in creation. The carving is done by skilled craftsmen who preserve the techniques passed down through generations of Pakistani woodworkers, ensuring that each rehal carries the warmth and authenticity of handcrafted traditional art. The wood is treated and polished to a smooth, durable finish that protects against moisture and wear while showcasing the natural grain patterns that make each piece unique.

Despite its compact size, this 7-inch rehal is engineered for stability and durability. The folding X-frame design allows it to open and close smoothly, and the angled reading surface holds books securely at a comfortable reading angle that reduces neck and eye strain during extended study sessions. The rehal elevates the Quran from flat surfaces — a practice that reflects the honor and respect Muslims accord to the Book of Allah. The compact folded size makes it easy to carry in a bag alongside the Quran, allowing users to set up a proper reading station wherever they go — at home, in the mosque, at the office, during travel, or in the park. For daily Quran readers who prefer a smaller, more portable rehal, for students who need a desktop book stand for their Islamic studies, and for anyone who appreciates the beauty of traditional Islamic craftsmanship, this Flower Rehal 7-inch delivers excellent quality, beautiful design, and practical utility at an accessible price point.`,
    metaDescription: "Flower Rehal 7 Inch — carved wooden Quran book rest with floral design. Compact, portable, handcrafted. Perfect for daily Quran reading. Buy online at Bab-ul-Fatah."
  },
  {
    slug: "flower-rehal-8-inch",
    description: `Flower Rehal — 8 Inch is a beautifully crafted wooden book stand featuring an elaborate floral carving pattern that serves as both a functional Quran holder and an attractive piece of Islamic home decor. Priced at Rs.750, this 8-inch rehal is the most popular size for standard household use — accommodating the full range of commonly used Quran formats including the standard Pakistani 16-line or 13-line Mushaf, larger deluxe Quran editions, hadith collections, tafseer volumes, and most Islamic reference books. The additional inch of width compared to the 7-inch model provides noticeably more stability and surface area, making it the preferred choice for regular daily use.

The floral carving that gives this rehal its name is executed with meticulous attention to detail — featuring intertwining vine and leaf patterns that flow across the front panels in a composition that is both symmetrical and organically flowing, reflecting the Islamic aesthetic principle of combining mathematical precision with natural beauty. The carving depth creates subtle shadows that change with the ambient light, giving the rehal a dynamic visual quality that makes it a conversation piece in any room. The wood finish is hand-applied using traditional techniques that enhance the natural grain while providing protection against the humidity and temperature variations common in Pakistani homes.

The 8-inch Flower Rehal is built for years of regular use. The hardwood construction provides the weight needed to prevent tipping when large, heavy books are placed on it, while the precision-engineered folding mechanism ensures smooth operation over thousands of open-close cycles. The reading angle is calibrated to the optimum for extended Quran study — reducing fatigue for the neck, shoulders, and eyes by positioning the text at a natural downward viewing angle. When folded, the rehal's slim profile allows it to be stored in a bookshelf, drawer, or beside the prayer mat without taking up excessive space. The rehal is equally at home in a dedicated prayer room, a living room, a bedroom, or a study — its beauty enhancing any space where Quran reading takes place. For families who read the Quran together daily, for students of Islamic knowledge who spend hours with open books, and for anyone who values both the functional and aesthetic dimensions of Islamic household items, this Flower Rehal 8-inch represents the ideal balance of size, stability, beauty, and craftsmanship.`,
    metaDescription: "Flower Rehal 8 Inch — handcrafted wooden Quran stand with floral carving. Standard size for all Mushaf formats. Durable hardwood, elegant home decor. Buy online."
  },
  {
    slug: "for-the-seekers-of-truth-set",
    description: `For the Seekers of Truth (Set) is a curated collection of English-language Islamic books designed to provide intellectually rigorous, spiritually enriching, and practically useful guidance for those who are seriously seeking to understand Islam at a deeper level — whether they are born Muslims looking to strengthen their knowledge, new Muslims navigating their faith journey, or inquisitive non-Muslims conducting an honest investigation of Islam's claims. Priced at Rs.3,050 for the complete set, this collection represents exceptional value for readers who want a comprehensive library of high-quality Islamic literature without purchasing individual titles at significantly higher combined costs.

The set is carefully curated to cover the major dimensions of Islamic knowledge that a truth-seeker needs to explore. The collection includes works on Islamic theology and philosophy — addressing the fundamental questions that every thinking person must grapple with: Does God exist? What is the purpose of life? Why does suffering exist? What happens after death? How do we know the Quran is authentic? What evidence supports the Prophethood of Muhammad (ﷺ)? These foundational questions are addressed with intellectual depth, academic rigor, and respectful acknowledgment of alternative viewpoints. The set also includes works on the practical aspects of Islam — how to pray, how to fast, how to perform Hajj, how to conduct oneself in daily life according to Islamic principles — providing not just theoretical knowledge but actionable guidance for living as a Muslim.

Additional volumes in the set address the spiritual dimension of Islam — the inner purification of the heart, the development of good character, the cultivation of a meaningful relationship with Allah through prayer, dhikr, and contemplation. These spiritual works balance the intellectual content of the set, ensuring that the seeker's journey encompasses both the mind and the heart. The set may also include biographical works — the life of Prophet Muhammad (ﷺ) and the lives of his companions — providing historical context and inspirational role models. Each book in the set is produced with high-quality binding, clear typography, and professional formatting that reflects the seriousness of its content. For Islamic dawah organizations seeking a comprehensive gift set for new Muslims, for libraries building their Islamic collections, for university students studying Islam academically, and for any individual who approaches Islam with the genuine, open-minded curiosity that the title "Seekers of Truth" implies, this set provides a well-rounded, intellectually satisfying, and spiritually nourishing introduction to the world's fastest-growing religion.`,
    metaDescription: "For the Seekers of Truth Set — curated English Islamic book collection on theology, practice, and spirituality. Ideal for new Muslims and serious seekers. Premium set."
  },
  {
    slug: "fortress-of-muslim-pocket-size",
    description: `Fortress of Muslim — Pocket Size is the Urdu edition of the famous supplication compilation "Hisn al-Muslim" (Fortress of the Muslim), presented in a compact, ultra-portable format that fits easily into a pocket, purse, or small bag. Priced at just Rs.320, this pocket-sized dua collection is one of the most affordable and practical Islamic books available — making it an ideal daily companion for every Muslim who wants to maintain a consistent practice of making du'a (supplication) throughout the day. The title "Fortress of the Muslim" reflects the concept that sincere supplication to Allah serves as a spiritual fortress — protecting the believer from anxiety, evil, difficulty, and every form of harm through the power of divine connection.

This compilation draws its du'as exclusively from the authentic Quran and verified hadith of Prophet Muhammad (ﷺ), organized chronologically to follow the Muslim's daily routine — from the du'as for waking up and using the bathroom, through the du'as for eating, drinking, dressing, traveling, entering and leaving the home and mosque, to the du'as for sleeping and other nighttime remembrances. The chronological organization makes it easy to find the appropriate du'a for any situation without searching through an index. Each du'a is presented with its full Arabic text, Urdu translation, and the source reference from the hadith collections — allowing readers to understand what they are reciting while maintaining confidence in its authenticity.

The pocket-size format is specifically designed for maximum portability and daily utility. The compact dimensions allow the book to be carried everywhere — in a pocket during the workday, in a purse during shopping trips, in a travel bag during journeys, and on the bedside table at night. The durable cover and binding are designed to withstand the wear and tear of constant carrying, and the paper quality ensures that the text remains clear and readable even after extended use. This edition includes the most essential du'as that every Muslim should know — the morning and evening adhkar, the du'as before and after eating, the du'a for entering and leaving the mosque, the du'a for seeking forgiveness (Sayyid al-Istighfar), the du'a for anxiety and sorrow, the du'a before sleeping, the du'a after the final tashahhud in prayer, and many more. For students, workers, travelers, homemakers, and anyone who wants to transform ordinary moments throughout the day into opportunities for spiritual connection, this pocket Fortress of Muslim is an indispensable daily companion.`,
    metaDescription: "Fortress of Muslim Pocket Size — Urdu dua collection from authentic Quran and hadith. Chronological daily du'as. Ultra-portable, affordable. Essential Islamic companion."
  },
  {
    slug: "fortress-of-the-muslim-english-translation-of-hisn-ul-muslim",
    description: `Fortress of the Muslim — English Translation of Hisn ul Muslim is the complete English rendering of the most widely used supplication collection in the contemporary Muslim world, originally compiled by Sa'id bin Ali bin Wahf al-Qahtani. Priced at Rs.800, this English edition makes the comprehensive dua collection accessible to the global English-speaking Muslim community — including millions of Muslims in Pakistan who prefer reading Islamic content in English, new Muslims and converts who are building their daily worship vocabulary, and Muslim families where English is the primary language of instruction and communication.

The compilation organizes approximately 267 du'as (supplications) into clear categories following the Muslim's daily routine — making it easy to find the appropriate du'a for any situation. The book covers du'as for waking up, for wearing new clothing, for entering and leaving the bathroom, for eating and drinking, for traveling, for entering and leaving the home and mosque, for beginning and ending every action, for the morning and evening adhkar, for prayer (including du'a al-qunut and the tashahhud), for seeking forgiveness, for protection from harm, for illness and healing, for anxiety and sorrow, for gratitude and contentment, for visiting the sick, for attending funerals, and for sleeping. Each du'a is presented in its original Arabic text alongside a clear, accurate English translation and the hadith source reference — enabling readers to recite in Arabic while understanding the full meaning of what they are saying to Allah.

The English translation maintains the spiritual depth and literary beauty of the Arabic originals while using language that is accessible to readers with varying levels of English proficiency. The transliteration of Arabic du'as is provided for readers who are still learning Arabic pronunciation — ensuring that even beginners can recite the du'as correctly. The book includes a detailed introduction that explains the Islamic concept of du'a, the etiquette of making supplication, the conditions for acceptance, and the common mistakes that reduce the effectiveness of du'a — providing readers with a thorough understanding of why, how, and when to supplicate. The compilation has earned the trust of scholars worldwide due to its strict adherence to authentic sources — every du'a included is verified to originate from the Quran or from authentic hadith of the Prophet (ﷺ), with fabricated or weak narrations explicitly excluded. For English-medium Islamic schools, for mosque libraries, for dawah organizations, and for every individual Muslim seeking to enrich their daily life with the Prophetic supplications, this Fortress of the Muslim English edition is an essential reference and daily companion.`,
    metaDescription: "Fortress of the Muslim English — Hisn ul Muslim translation. 267 authentic daily du'as with Arabic text, English meaning, and hadith references. Essential Islamic reference."
  },
  {
    slug: "fragrance-free-vaseline-for-hajj-o-umrah",
    description: `Fragrance Free Vaseline for Hajj o Umrah is a specialized personal care product designed specifically to meet the requirements of pilgrims performing Hajj or Umrah while in the state of Ihram — the sacred state of consecration that imposes strict restrictions on the pilgrim's behavior, clothing, and grooming. Priced at just Rs.100, this fragrance-free petroleum jelly addresses a very specific but critically important need: male pilgrims in Ihram are prohibited from wearing sewn clothing, covering their heads, and using any product that contains added fragrance — including perfumed soaps, scented lotions, aftershave, cologne, and most commercial moisturizers and lip balms that contain fragrance additives. Violating these restrictions incurs a penalty (damm) that requires either a sheep sacrifice, fasting for three days, or feeding six poor people.

The Pakistan climate, combined with the physical demands of Hajj and Umrah — walking long distances between holy sites, standing for hours in crowded conditions, enduring the intense heat of the Arabian desert — makes skin and lip care an absolute necessity rather than a luxury. Cracked lips, dry skin, chafing, and irritation from sun exposure are common complaints among pilgrims, and these conditions can become severe enough to distract from worship and diminish the spiritual experience. This fragrance-free Vaseline provides essential moisturizing and protective benefits without any added scent — making it fully permissible for use during Ihram. The product can be applied to dry lips, cracked heels, irritated skin, and areas prone to chafing without violating the Ihram restrictions.

The small, travel-friendly size is specifically designed for the Hajj and Umrah journey — fitting easily into a pilgrim's belt bag, waist pouch, or pocket alongside other essential items like a misbaha, prayer cap, and Quran. The compact size also complies with airline liquid restrictions for carry-on luggage. The product is equally useful after Ihram is completed — during the remaining days in Makkah and Madinah when pilgrims may want to use moisturizer without carrying multiple personal care products. Many experienced Hajj guides and tour operators in Pakistan recommend this fragrance-free Vaseline as a must-have item on every pilgrim's packing list, and it is commonly stocked by Hajj and Umrah travel agencies as part of their pre-departure kits. At Rs.100, this small investment can make a significant difference in a pilgrim's physical comfort during one of the most important spiritual journeys of their lifetime.`,
    metaDescription: "Fragrance Free Vaseline for Hajj Umrah — unscented moisturizer permissible in Ihram. Prevents dry lips and skin during pilgrimage. Travel-size, affordable. Essential packing item."
  },
  {
    slug: "from-asr-to-maghrib",
    description: `From Asr to Maghrib is a delightful children's Islamic book that captures the precious time between the Asr (afternoon) and Maghrib (sunset) prayers — a period rich with spiritual significance, family warmth, and daily transition. Priced at just Rs.175, this affordable paperback is part of a popular series of children's Islamic storybooks that frame daily life activities within an Islamic context, helping young Muslim children understand that every moment of their day can be connected to Allah's guidance and the example of Prophet Muhammad (ﷺ). The book is designed for children aged 4 to 8 and uses simple Urdu text with engaging illustrations to create a reading experience that children genuinely enjoy.

The story follows a young Muslim child through the hours between Asr and Maghrib — beginning with the peaceful atmosphere after the Asr prayer as the afternoon light softens and the household prepares for the transition to evening. The narrative weaves in Islamic teachings naturally — the child helps their mother prepare iftar during Ramadan, or assists their father in the garden while discussing Allah's creation, or sits with their grandmother listening to stories of the Prophet (ﷺ) and his companions. The book emphasizes the importance of this time period in Islamic tradition — the Prophet (ﷺ) encouraged supplication (du'a) during the time between Asr and Maghrib, and this period is mentioned in hadith as a time when prayers are answered. The approaching Maghrib call to prayer (adhan) creates a sense of anticipation and spiritual excitement that the book captures beautifully.

The illustrations depict familiar Pakistani household scenes — the courtyard, the kitchen, the veranda — making the story immediately relatable for Pakistani Muslim children. The family dynamics portrayed in the book reflect Islamic values — respect for elders, kindness to siblings, gratitude for food, and the peaceful rhythm of a household structured around prayer times. The book also introduces simple du'as that children can learn and recite during this time — the du'a between Asr and Maghrib, the du'a for the evening, and the du'a for parents. Parents and teachers report that this book helps children develop a positive, natural relationship with the daily prayer schedule — rather than seeing prayers as interruptions to their activities, children begin to see the prayer-based structure of the day as a source of comfort, security, and joy. For families building their children's Islamic library, for Islamic school teachers looking for engaging classroom reading material, and for anyone who wants to give a young Muslim child an enjoyable introduction to the beauty of living an Islamically structured daily life, this book is an excellent, affordable choice.`,
    metaDescription: "From Asr to Maghrib — Urdu children's Islamic storybook about the time between afternoon and sunset prayers. Family warmth, du'as, relatable Pakistani scenes. Ages 4-8."
  },
  {
    slug: "from-assembly-to-classroom",
    description: `From Assembly to Classroom is an engaging children's Islamic storybook that follows a young Muslim student's morning journey from the school assembly ground into the classroom — transforming a routine educational experience into an opportunity for Islamic learning and character development. Priced at Rs.175, this affordable paperback is part of a beloved series that helps Pakistani Muslim children see their everyday school experiences through an Islamic lens, building the understanding that Islam guides every aspect of life — including how a student behaves in school.

The story begins with the morning school assembly — a familiar experience for every Pakistani schoolchild — but views it through an Islamic framework. The protagonist stands respectfully during the assembly, recites the national anthem and the school prayer with sincerity, listens attentively to the principal's address, and demonstrates the Islamic qualities of discipline, respect, and attentiveness. The book then follows the child into the classroom, where Islamic values continue to guide their behavior — raising their hand before speaking, being kind to classmates, treating the teacher with respect (a concept deeply rooted in Islamic tradition where teachers are honored as spiritual parents), taking care of school property, and approaching their studies with the enthusiasm and diligence that Islam encourages for the pursuit of knowledge.

The narrative naturally introduces relevant Islamic teachings — the Prophet's (ﷺ) emphasis on seeking knowledge from the cradle to the grave, the hadith about the superiority of the learned over the ignorant, the Quranic encouragement to read and reflect, and the Islamic perspective on good manners (adab) in social settings like classrooms. The book also addresses common school situations from an Islamic perspective — how to respond when a classmate is unkind (with patience and forgiveness), how to handle the temptation to cheat (with honesty and trust in Allah), how to share supplies with classmates (with generosity), and how to balance schoolwork with prayer times (with time management). The illustrations show diverse Pakistani school environments — including both coeducational and gender-segregated settings — making the book relevant for children across different school systems. For school administrators looking for values-based supplementary reading material, for parents who want to reinforce Islamic manners alongside their children's formal education, and for young readers who enjoy stories about school life with moral lessons, this book provides an entertaining, educational, and Islamically enriching reading experience.`,
    metaDescription: "From Assembly to Classroom — Islamic children's storybook about school life. Respect, honesty, kindness in classroom settings. Pakistani school context. Ages 4-8. Buy online."
  },
  {
    slug: "from-breakfast-to-school",
    description: `From Breakfast to School is a charming Urdu children's book that narrates the familiar morning routine of a young Muslim family — from the moment the child wakes up and sits down for breakfast to the time they leave for school — embedding Islamic values, du'as, and etiquettes into every step of this daily journey. Priced at Rs.175, this paperback is part of a well-loved series of Islamic children's books that transforms ordinary daily activities into meaningful Islamic learning experiences for children aged 3 to 7.

The book opens with the child waking up to the sound of the Fajr adhan (or their mother's gentle wake-up call), teaching the du'a for waking up and the importance of beginning the day by thanking Allah for the blessing of a new morning. The breakfast table becomes a classroom for Islamic manners — the family recites "Bismillah" before eating, eats with the right hand, sits properly, does not waste food, says "Alhamdulillah" after finishing, and thanks the mother (or father) who prepared the meal. The book emphasizes the Islamic teaching about gratitude for food and the prohibition of wasting — a lesson that resonates deeply in Pakistani culture where food is both a blessing and a communal experience. The preparation for school — brushing teeth (following the Prophet's ﷺ emphasis on oral hygiene through the miswak), getting dressed (with the du'a for wearing new or clean clothes), packing the school bag (with responsibility and organization), and saying goodbye to parents (with the du'a for leaving the home and the respectful kiss of the parents' hands) — each step is accompanied by the appropriate du'a and the underlying Islamic value it represents.

The illustrations depict a warm, loving Pakistani Muslim family going about their morning routine in a setting that children will immediately recognize — the breakfast table with parathas and chai, the school uniform hanging ready, the father reading Quran or praying Fajr, the mother preparing tiffin boxes with love and care. This cultural authenticity makes the book particularly effective for Pakistani children, who see their own lives reflected in its pages. The book also addresses the common morning challenges that families face — the child who doesn't want to get out of bed, the rushed breakfast, the forgotten homework — and shows how Islamic values of patience, discipline, and preparation help navigate these challenges gracefully. For parents looking to build Islamic du'a practice into their children's morning routine, for preschool and kindergarten teachers introducing Islamic manners to young learners, and for anyone who wants to give a young child an enjoyable book that makes their daily routine feel special and meaningful, this affordable paperback delivers exceptional value and educational impact.`,
    metaDescription: "From Breakfast to School — Urdu kids' Islamic book on morning routines. Du'as for waking, eating, dressing, leaving home. Pakistani family setting. Ages 3-7. Affordable."
  },
  {
    slug: "from-fajar-to-morning",
    description: `From Fajar to Morning is a beautifully illustrated Urdu children's storybook that captures the magical, spiritually rich hours between the Fajr (dawn) prayer and the full brightness of morning — a time that holds special significance in Islamic tradition as the beginning of a new day, a fresh start blessed by Allah's mercy. Priced at Rs.175, this paperback is part of a comprehensive series that helps children see their entire day as an opportunity for worship, gratitude, and good character, with each book focusing on a specific time period and the Islamic activities associated with it.

The story begins in the pre-dawn darkness, as the melodious Fajr adhan calls the family to prayer. The child wakes up with excitement — perhaps it's Ramadan and the family is eating sehri together before the fast begins, or perhaps it's a regular day and the child is learning to pray Fajr with their parent. The book describes the beauty of the Fajr prayer experience — the peacefulness of the mosque in the early morning, the soft light of dawn appearing on the horizon, the recitation of the Quran in the quiet hours before the world awakens. The narrative emphasizes the special spiritual status of the Fajr prayer in Islam — the Prophet (ﷺ) said that whoever prays the two Fajr rak'at will be under Allah's protection for the entire day, and the Quran specifically mentions the dawn prayer and its spiritual witnesses: "And the Quran of dawn — indeed, the witnesses of the dawn are attended by angels."

As morning light gradually fills the sky, the book transitions to the morning adhkar (remembrances) — the du'as and dhikr that the Prophet (ﷺ) recommended reciting in the early morning. The child learns to say "SubhanAllahi wa bihamdihi" and the morning du'as for protection, gratitude, and guidance. The story also explores the natural world awakening at dawn — the birds singing, the flowers opening, the light spreading — connecting these natural phenomena to Allah's power and creativity in a way that builds a child's sense of awe and wonder at creation. The book shows the family engaging in different morning activities — the father going to the mosque for Fajr congregation, the mother making breakfast, older siblings getting ready for school — all within the framework of Islamic values and daily worship. For families who want their children to develop a love for Fajr prayer and the peaceful beauty of early morning spiritual practice, this book provides a gentle, age-appropriate, and visually engaging introduction that makes the pre-dawn hours feel special and inviting rather than difficult and dark.`,
    metaDescription: "From Fajar to Morning — Urdu children's story about dawn prayer and morning adhkar. Fajr blessings, sunrise du'as. Peaceful early morning Islamic routine. Ages 3-7."
  },
  {
    slug: "from-maghrib-to-isha",
    description: `From Maghrib to Isha is a heartwarming Urdu children's book that explores the evening hours between the Maghrib (sunset) and Isha (night) prayers — a time of transition from the day's activities to the peacefulness of night, filled with family togetherness, gratitude, and spiritual reflection. Priced at Rs.175, this affordable paperback is part of a popular series of Islamic children's storybooks that follow a child's daily routine through an Islamic framework, helping young readers understand how every moment of their day connects to their faith and to Allah's guidance.

The story opens as the Maghrib adhan echoes through the neighborhood at sunset, calling the family to break their fast during Ramadan or to pause their evening activities for prayer on regular days. The book captures the beautiful transition that occurs at Maghrib — the sky's colors changing, the family gathering for prayer and then for the evening meal, the sense of completion and gratitude that accompanies the end of another day blessed by Allah. The narrative emphasizes the Prophet's (ﷺ) teaching about the special virtue of Maghrib and Isha prayers, and the hadith about the angels that attend these prayer times. The book also includes the du'as specific to Maghrib — the du'a for breaking the fast, the du'a said after Maghrib prayer, and the evening adhkar that protect the believer through the night.

The period between Maghrib and Isha is portrayed as a precious family time in the book — the family eats together, shares stories about their day, reads Quran together, and children play before the Isha prayer. The book shows the evening meal as an opportunity for Islamic manners — reciting Bismillah, eating together from a shared plate (as the Prophet ﷺ recommended), not criticizing food, and thanking the person who prepared the meal. The narrative also addresses the challenge of children who want to stay up late — gently guiding them toward the Islamic value of sleeping early (after Isha) and waking up early (for Fajr), as the Prophet (ﷺ) recommended. The approach to Isha prayer is depicted with warmth and tranquility — the family performing wudu together, praying in congregation, and then reciting the evening du'as before settling into bed. The illustrations show cozy Pakistani household scenes — the courtyard lit by electric light or candlelight, the family gathered on the charpoy or dastarkhwan, the neighborhood mosque visible in the background. For families who want their children to associate the evening hours with warmth, family, and worship rather than with television and distraction, this book provides a gentle, persuasive, and thoroughly enjoyable model of an Islamically structured evening routine.`,
    metaDescription: "From Maghrib to Isha — Urdu children's story about evening prayers and family time. Iftar, evening adhkar, bedtime du'as. Pakistani home setting. Ages 3-7. Buy online."
  },
  {
    slug: "from-monogamy-to-polygyny",
    description: `From Monogamy to Polygyny is a scholarly English-language book that provides a comprehensive, evidence-based examination of the Islamic ruling on polygyny — a topic that generates intense debate, misunderstanding, and emotional controversy both within Muslim communities and in the broader public discourse. Priced at Rs.2,250, this book approaches the subject with the academic rigor and scholarly balance that its complexity demands, avoiding both the apologetic minimization favored by some Muslim writers and the hostile caricature promoted by critics of Islam. Instead, it presents polygyny as it actually appears in the Quranic text, the Prophetic practice, the classical scholarly tradition, and the lived experience of Muslim communities throughout history.

The book begins with a thorough analysis of the Quranic verses related to polygyny — particularly Surah An-Nisa (4:3), which establishes the foundational conditions for polygyny in Islam: justice among wives, the ability to provide for multiple households, and the legitimate social circumstances that may warrant an additional marriage. The author provides a detailed linguistic analysis of key terms in the verse, examining how classical exegetes (mufassirun) from different schools of thought understood and interpreted these conditions. The book then examines the Prophetic practice — Prophet Muhammad's (ﷺ) own marriages, the marriages of his companions, and the hadith that establish the legal framework for polygyny — showing how the practice was regulated, restricted, and contextualized rather than being either mandated or prohibited.

A significant portion of the book is devoted to the social and historical context in which polygyny was practiced and regulated in Islamic civilization — addressing the practical realities of pre-modern societies where women outnumbered men due to warfare, the economic vulnerability of widows and orphans, the absence of state welfare systems, and the social stigma attached to unmarried women. The book argues that understanding this historical context is essential for evaluating the relevance of polygyny in modern societies where these conditions may or may not apply. The author also addresses the common objections to polygyny — including arguments about gender equality, emotional justice, and the rights of the first wife — providing Islamic responses that are both intellectually rigorous and practically honest, acknowledging the real challenges that polygyny can create while demonstrating that these challenges do not invalidate the ruling itself. The book includes testimonies from women in polygynous marriages, statistical data on polygyny rates in Muslim countries, and a comparative analysis of how different legal systems regulate or prohibit the practice. For Muslim couples considering polygyny, for scholars researching Islamic family law, for students of comparative religion, and for anyone who wants an informed, balanced, and comprehensive treatment of this sensitive topic, this book provides the authoritative reference that the subject requires.`,
    metaDescription: "From Monogamy to Polygyny — scholarly English book on Islamic polygyny. Quranic analysis, historical context, women's testimonies. Balanced, evidence-based. Buy online."
  },
  {
    slug: "from-school-to-home",
    description: `From School to Home is a delightful Urdu children's storybook that follows a young Muslim student's journey from the end of the school day back to the comfort and warmth of home — embedding Islamic values, etiquettes, and du'as into the familiar afternoon routine that millions of Pakistani schoolchildren experience every day. Priced at Rs.175, this affordable paperback completes the daily cycle portrayed in the series, showing children how Islamic manners and gratitude extend from the structured school environment into the family home.

The story begins as the final school bell rings and the child gathers their belongings — teaching the Islamic value of organization, responsibility, and gratitude for the blessing of education. The journey home from school is depicted as an opportunity for practicing Islamic manners — the child greets neighbors respectfully, helps a younger sibling carry their bag, avoids littering (reflecting the Islamic teaching about keeping public spaces clean), and recites the du'a for returning home as they approach their door. The book emphasizes the Prophet's (ﷺ) teaching about greeting others with "Assalamu Alaikum" and the importance of maintaining good character even when tired after a long school day.

The homecoming scene is the emotional heart of the book — the child is greeted by their mother (or grandmother) with a warm smile, fresh snacks, and the question "How was your day?" The book shows the Islamic etiquette of entering the home (greeting with salam, seeking permission if the door is closed), taking off shoes properly, washing up before eating, and sharing stories about the school day with family. The afternoon period between returning from school and Asr prayer is portrayed as a time for both rest and productivity — the child has a snack, completes homework (reflecting the Islamic emphasis on fulfilling one's duties and acquiring knowledge), helps with small household tasks, and prepares for the Asr prayer. The book also addresses common after-school challenges — the temptation to watch television instead of studying, the tiredness that makes children cranky, conflicts with siblings over shared space — and shows how Islamic values of patience, time management, and kindness help resolve these situations. For Pakistani families looking for quality Islamic children's literature that reflects their children's actual daily experience, this book provides a relatable, enjoyable, and morally enriching story that children will want to read again and again.`,
    metaDescription: "From School to Home — Urdu kids' story about returning home from school. Islamic manners, du'as, family warmth. Homework, snacks, Asr preparation. Ages 3-7. Affordable."
  },
  {
    slug: "fun-with-arabic-alphabet",
    description: `Fun with Arabic Alphabet is an engaging, activity-based educational book designed to teach young children the Arabic alphabet (alif-ba-ta) in a way that is enjoyable, interactive, and effective — transforming what could be a dry memorization exercise into a playful learning adventure. Priced at Rs.560, this colorful paperback is specifically created for children who are beginning their journey into Quranic Arabic, whether they are attending formal Quran classes, being homeschooled by their parents, or simply developing early literacy skills in an Islamic educational context. The book is suitable for children aged 3 to 7 and requires no prior knowledge of Arabic.

The book employs multiple pedagogical strategies to make Arabic letter learning both fun and effective. Each letter is introduced through a combination of visual recognition, tracing practice, coloring activities, and association techniques. The visual component presents each letter in its isolated, initial, medial, and final forms — the four positions in which Arabic letters appear — using large, clear fonts with directional arrows showing the correct stroke order for writing. The tracing section provides dotted outlines of each letter that children can trace with a pencil, building the fine motor skills and muscle memory needed for independent writing. The coloring pages feature the letters embedded within pictures of objects whose names begin with those letters (alif for arnab/rabbit, ba for batta/duck, ta for tuffaha/apple), creating memorable visual associations that reinforce learning.

Beyond basic letter recognition and writing, Fun with Arabic Alphabet introduces children to the concept of letter sounds (makharij — the points of articulation in the mouth and throat where each Arabic letter is produced). Simple, child-friendly descriptions explain where each letter sound comes from — "the letter ba comes from your lips," "the letter kha comes from deep in your throat" — laying the foundation for proper Quranic pronunciation. The book also introduces the concept of vowel marks (fatha, damma, kasra, sukun) in a simplified, age-appropriate way, along with basic letter combinations that form simple words. Each section includes a "review challenge" — a simple quiz or matching activity that tests the child's retention of previously learned letters, providing parents and teachers with a built-in assessment tool. The book includes a completion certificate at the end that can be filled in with the child's name and dated, giving young learners a tangible sense of achievement. For Pakistani parents beginning their children's Quran education, for Islamic preschool and kindergarten teachers, and for anyone looking for a high-quality, enjoyable Arabic alphabet book, this publication delivers exceptional educational value in a format that children genuinely love.`,
    metaDescription: "Fun with Arabic Alphabet — activity-based Arabic letter learning for kids. Tracing, coloring, sounds, vowel marks. Ages 3-7. Quranic pronunciation foundation. Buy online."
  },
  {
    slug: "furqan-visits-fez",
    description: `Furqan Visits Fez is a charming children's storybook that takes young readers on an exciting virtual journey to the historic city of Fez in Morocco — one of the most culturally rich and Islamically significant cities in the world, home to the University of Al-Qarawiyyin (the oldest continuously operating university in the world), the famous tanneries, the ancient medina, and a living tradition of Islamic scholarship and craftsmanship. Priced at Rs.650, this illustrated paperback combines adventure storytelling with cultural and Islamic education, exposing Pakistani Muslim children to the rich diversity of the global Muslim Ummah while entertaining them with a genuinely engaging narrative.

The story follows a young boy named Furqan (whose name itself means "criterion" — the ability to distinguish truth from falsehood, reflecting the Quranic title) as he travels to Fez, possibly with his family on vacation or as part of an educational trip. Through Furqan's eyes, young readers explore the narrow, winding streets of the Fez medina — a UNESCO World Heritage Site that has remained largely unchanged for centuries. Furqan visits the Al-Qarawiyyin Mosque and University, learning about the great scholars who studied there — including the famous historian Ibn Khaldun and the philosopher Ibn Rushd — and discovering that Morocco has been a center of Islamic learning for over a thousand years. He watches skilled craftsmen at work in the traditional workshops, learning about the Islamic art of calligraphy, geometric pattern design, leather work, and zellige tile-making.

The book weaves Islamic values naturally into the adventure narrative — Furqan practices good manners with the Moroccan people he meets, makes du'a before and during the journey, appreciates the diversity of Muslim cultures while recognizing the unity of the Ummah, and develops a sense of connection to the global Muslim community that extends beyond his own country and culture. The story also includes historical information about Morocco's Islamic heritage — the story of the Idrisid dynasty that founded Fez, the role of Moroccan scholars in preserving and transmitting Islamic knowledge, and the significance of Fez as a spiritual center of Sufi tradition. The illustrations capture the distinctive beauty of Moroccan Islamic architecture — the ornate doorways, the mosaic fountains, the green-tiled roofs, the bustling souks — providing children with visual exposure to an Islamic aesthetic that is different from the South Asian Islamic architecture they see at home. For families who want to broaden their children's understanding of Muslim civilization, for Islamic schools teaching world geography and history, and for young readers who love adventure stories with educational content, Furqan Visits Fez provides a memorable, enriching, and visually beautiful reading experience.`,
    metaDescription: "Furqan Visits Fez — children's Islamic adventure story set in Morocco. Al-Qarawiyyin University, Islamic heritage, cultural diversity. Illustrated. Ages 5-10. Buy online."
  },
  {
    slug: "gardan-na-jhuki-jin-kay-zulam-kay-agay",
    description: `Gardan Na Jhuki Jin Kay Zulam Kay Agay (Never Bow Before Those Who Commit Injustice) is a powerful Urdu book that addresses one of the most important moral and political principles in Islam — the obligation to stand firm against injustice, oppression, and tyranny regardless of the personal cost, and the prohibition against submitting to or legitimizing unjust rulers and systems. Priced at Rs.460, this book draws upon Islamic history, Quranic guidance, and the Prophetic tradition to present a compelling case for why Muslims must maintain their moral courage and never compromise their principles in the face of unjust authority.

The book's title is inspired by the Islamic principle that ultimate submission belongs to Allah alone — and that no human being, regardless of their power, wealth, or position, has the right to demand the kind of submission that creates injustice or enables oppression. The book examines this principle through the lens of Islamic history, presenting the stories of prophets, companions, and righteous Muslims who faced tyrants with courage and refused to bow to unjust demands. The story of Prophet Musa (AS) confronting Pharaoh — the archetypal narrative of faith confronting tyranny in the Quran — is analyzed in detail, showing how Musa's refusal to submit to Pharaoh's false claims of divinity established a permanent template for Muslim resistance to unjust authority. The story of Prophet Ibrahim (AS) breaking the idols and facing Nimrud's fire, the story of the companions standing against corrupt rulers during the early Caliphate, and the stories of Muslim scholars throughout history who were imprisoned, exiled, or even killed for speaking truth to power — all are presented as evidence of Islam's uncompromising stance against injustice.

The book also addresses the contemporary relevance of this principle, examining how Muslims today should respond to various forms of injustice — political tyranny, economic exploitation, social discrimination, and the oppression of weak and vulnerable populations. The author argues that Islam does not advocate either passive acceptance or violent rebellion as the only options — but rather provides a framework for principled resistance that combines moral courage with strategic wisdom, drawing on the Quranic principle of enjoining good and forbidding evil (al-amr bi'l-ma'ruf wa'l-nahy 'an al-munkar). The book addresses the common justifications that tyrants use to demand obedience — the claim that obedience to authority is a religious obligation, the argument that challenging the status quo creates fitna (tribulation), and the suggestion that patience in the face of injustice is more virtuous than resistance — and provides Islamic counterarguments to each. For Pakistani readers navigating a complex political and social landscape, for students of Islamic political thought, and for anyone who believes that the fight against injustice is a religious obligation, this book provides the intellectual ammunition and spiritual motivation needed to stand firm.`,
    metaDescription: "Gardan Na Jhuki Jin Kay Zulam Kay Agay — Urdu book on Islamic resistance to injustice. Prophetic examples, moral courage, contemporary relevance. Thought-provoking. Buy online."
  },
  {
    slug: "gems-and-jewels",
    description: `Gems and Jewels is a premium English-language collection of wisdom sayings, inspirational anecdotes, and profound observations drawn from the rich heritage of Islamic scholarship, spirituality, and history. Priced at Rs.2,550, this beautifully produced hardcover gathers some of the most precious insights from the Islamic tradition — the "gems and jewels" of wisdom that great Muslim scholars, mystics, and thinkers have refined and polished over fourteen centuries of intellectual and spiritual endeavor. The book is designed to be both a reference work that readers return to repeatedly and a beautiful gift that communicates the depth and beauty of Islamic wisdom to recipients of any faith background.

The collection is organized into thematic chapters that address the major dimensions of human experience — wisdom and knowledge, patience and perseverance, gratitude and contentment, love and compassion, justice and fairness, humility and modesty, courage and determination, forgiveness and mercy, death and the afterlife, and the relationship between the human being and the Creator. Each chapter presents a curated selection of sayings, stories, and reflections from a diverse range of Islamic sources — the Quran (with relevant verses and their contexts), the hadith of Prophet Muhammad (ﷺ) (including many lesser-known but profoundly moving narrations), the wisdom of the Rightly Guided Caliphs, the insights of the early Muslim scholars and ascetics, the poetry of Rumi, Hafiz, and other Muslim poets, and the observations of contemporary Muslim thinkers. The diversity of sources ensures that the book captures the full breadth and depth of Islamic wisdom — from the legally precise rulings of the jurists to the ecstatic utterances of the mystics, from the political philosophy of the caliphs to the personal devotion of the ordinary believer.

What makes this collection particularly valuable is its accessibility — each gem of wisdom is presented in a standalone format that can be read in a few minutes, making the book perfect for daily reflection, bedside reading, or quick inspiration between tasks. The selections are not merely quoted but are accompanied by brief contextual commentary that explains their origin, meaning, and practical application — transforming ancient wisdom into immediately useful guidance for modern life. The production quality matches the premium content — the hardcover binding features elegant design elements, the paper is thick and cream-colored, the typography is refined, and the overall aesthetic communicates the seriousness and beauty of its subject matter. For readers who enjoy the aphoristic wisdom tradition, for families building a home library of Islamic classics, for dawah organizations seeking a beautiful gift for new Muslims, and for anyone who appreciates the timeless quality of genuine wisdom expressed in clear, powerful language, Gems and Jewels is a treasure that yields new insights with every reading.`,
    metaDescription: "Gems and Jewels — premium English collection of Islamic wisdom. Prophetic sayings, scholarly insights, mystical poetry. Beautiful hardcover, inspirational daily reading."
  },
  {
    slug: "getting-the-best-out-of-al-hajj-pilgrimage",
    description: `Getting the Best Out of Al-Hajj (Pilgrimage) is a comprehensive, practical English-language guide designed to help Muslim pilgrims prepare for, perform, and maximize the spiritual benefits of the Hajj — the fifth pillar of Islam and one of the most demanding, transformative experiences in a Muslim's lifetime. Priced at Rs.3,550, this premium guidebook reflects the understanding that while millions of Muslims perform Hajj each year, relatively few achieve the spiritual transformation that the pilgrimage is designed to produce — not because the Hajj lacks spiritual power, but because most pilgrims arrive physically prepared but spiritually and intellectually underprepared for the experience that awaits them.

The book is structured as a complete journey companion, covering every phase of the Hajj experience. The pre-Hajj preparation section addresses the practical preparations (passport, visa, vaccinations, packing, transportation arrangements) alongside the essential spiritual preparations (repentance, settling debts, seeking forgiveness from those wronged, learning the rites, making intentions, and building the physical stamina needed for the demanding physical rituals). The section on Ihram provides detailed guidance on entering the state of consecration — the specific du'as and intentions, the restrictions that apply, the permitted and prohibited actions, and the common mistakes that invalidate Ihram. The core Hajj rituals are presented in a clear, step-by-step format with diagrams and illustrations — the Tawaf (circumambulation of the Ka'bah) with the specific du'as for each circuit, the Sa'i (running between Safa and Marwah) with its historical context, the Day of Arafah with its unparalleled spiritual significance, the night at Muzdalifah, the stoning of the Jamaraat, the animal sacrifice, the shaving/cutting of hair, and the Tawaf al-Ifadah.

What distinguishes this guide from standard Hajj manuals is its emphasis on the "inner dimension" of the pilgrimage — the spiritual states, mental attitudes, and heart conditions that transform the physical rituals from mere mechanical actions into profound acts of worship. The book explains how each external ritual corresponds to an internal reality — how Tawaf represents the believer's perpetual movement around the center of their existence (Allah), how Sa'i represents the struggle of life between hope (Safa) and patience (Marwah), how Arafah represents the Day of Judgment, and how the stoning represents the rejection of temptation. The book also provides practical tips for managing the physical challenges of Hajj — the heat, the crowds, the fatigue, the limited facilities — with specific strategies for staying hydrated, protecting against sun exposure, maintaining personal hygiene, and managing health conditions. The post-Hajj section covers the Tawaf al-Wada (farewell circumambulation), the visit to Madinah, and the lifelong changes that should result from a successful Hajj experience. For Pakistani pilgrims planning their once-in-a-lifetime journey, for Hajj group leaders seeking a comprehensive reference for their groups, and for anyone who wants to ensure that their Hajj investment — both financial and spiritual — produces the maximum possible return, this guide provides the complete preparation, execution, and reflection framework needed for a truly transformative pilgrimage.`,
    metaDescription: "Getting the Best Out of Al-Hajj — comprehensive English Hajj guide. Step-by-step rituals, spiritual preparation, practical tips. Premium hardcover. Essential pilgrimage companion."
  },
  {
    slug: "ghaar-ka-raaz",
    description: `Ghaar Ka Raaz (The Secret of the Cave) is an exciting Urdu children's adventure story that draws upon one of the most dramatic and spiritually significant episodes in Islamic history — the migration of Prophet Muhammad (ﷺ) and his companion Abu Bakr as-Siddiq (RA) from Makkah to Madinah, and their miraculous shelter in the Cave of Thawr during the most dangerous phase of their journey when the Quraysh were actively searching for them with the intention of killing the Prophet (ﷺ). Priced at Rs.300, this affordable paperback adapts this powerful historical narrative into an age-appropriate adventure story that children find thrilling while absorbing foundational Islamic lessons about trust in Allah, courage in the face of danger, and the value of true friendship and loyalty.

The story is narrated in a way that builds suspense and excitement — the secret departure from Makkah under cover of darkness, the journey through the desert mountains south of Makkah, the discovery of the Cave of Thawr and the decision to hide there, the arrival of the Quraysh search party at the very mouth of the cave, the famous moment when Abu Bakr (RA) whispered his fear and the Prophet (ﷺ) responded with the immortal words of reassurance: "Do not grieve, indeed Allah is with us," the spider's web that appeared across the cave entrance and the dove's nest that materialized — the natural phenomena that Islamic tradition holds were miracles arranged by Allah to conceal the cave from the searchers, and the eventual safe emergence from the cave to continue the journey to Madinah. Each element of the story is presented with appropriate dramatic tension while maintaining historical and religious accuracy.

Beyond the adventure narrative, the book weaves in important moral and spiritual lessons that children can apply to their own lives. The trust that Prophet Muhammad (ﷺ) placed in Abu Bakr (RA) — choosing him as his sole companion for the most dangerous journey of his life — teaches children about the value of choosing good friends and being worthy of trust. Abu Bakr's (RA) willingness to sacrifice everything — his wealth, his safety, his family — for the sake of protecting the Prophet (ﷺ) demonstrates the meaning of true loyalty and devotion. The Prophet's (ﷺ) calm confidence in Allah's protection despite the overwhelming danger models the Islamic virtue of tawakkul (complete trust in Allah) that children can practice when they face their own (admittedly smaller) fears and challenges. The cave miracles — the spider, the dove, the rocks — teach children that Allah can use the smallest, most insignificant things to protect those who trust in Him. For Pakistani parents and teachers who want to introduce children to the Seerah through engaging, story-based learning, this book provides an excellent blend of adventure, education, and Islamic moral instruction.`,
    metaDescription: "Ghaar Ka Raaz — Urdu children's story of Prophet Muhammad's migration and the Cave of Thawr. Adventure, courage, trust in Allah. Ages 5-10. Inspirational Seerah."
  },
  {
    slug: "ghair-islami-tehwar-tareekh-haqaiq-mashahidat",
    description: `Ghair Islami Tehwar: Tareekh, Haqaiq, Mashahidat (Non-Islamic Festivals: History, Facts, and Observations) is an informative Urdu book that provides a detailed, scholarly examination of the various non-Islamic festivals and celebrations that have become increasingly visible and influential in Muslim-majority societies — particularly in Pakistan, where Western cultural imports, Hindu religious festivals, and secular commercial celebrations have become significant social phenomena that require clear Islamic guidance. Priced at Rs.500, this book serves as a comprehensive reference for Muslims who want to understand the origins, meanings, and Islamic rulings related to festivals such as Valentine's Day, Halloween, Christmas, New Year celebrations, Holi, Diwali, birthdays, and other cultural observances that are not part of the Islamic calendar.

The book approaches each festival systematically, providing three categories of information for each: Tareekh (History) traces the origin and evolution of the festival — when and where it began, how it developed over time, and what its original religious or cultural significance was. Haqaiq (Facts) presents the objective reality of how the festival is celebrated today — its commercial dimensions, its social functions, its impact on family and community values, and the specific practices associated with it. Mashahidat (Observations) provides an Islamic analysis and critique — examining the festival from the perspective of Islamic theology and jurisprudence, identifying elements that conflict with Islamic teachings, and assessing the degree of participation that is or is not permissible for Muslims. This three-part analysis for each festival gives readers the comprehensive information they need to make informed decisions about their own participation and to guide their families and communities appropriately.

The book distinguishes between different categories of non-Islamic festivals — religious festivals of other faiths (Christmas, Diwali, Holi), secular cultural celebrations (New Year, Valentine's Day, Halloween), and commercial celebrations (Mother's Day, Father's Day, Black Friday). For each category, the book presents the relevant Quranic principles, hadith guidance, and scholarly opinions that establish the Islamic ruling on Muslim participation. The book also addresses the common arguments used to justify participation in non-Islamic festivals — "it's just cultural, not religious," "it promotes social harmony," "the children feel left out," "everyone does it" — and provides thoughtful Islamic responses to each argument. The book is not written in a harsh or condemnatory tone but rather in a scholarly, educational tone that respects the reader's intelligence while clearly communicating the Islamic position. For Pakistani Muslim families navigating the increasing presence of non-Islamic celebrations in their social environment, for Islamic school teachers addressing students' questions about these festivals, for scholars issuing fatwas on cultural participation, and for anyone who wants a well-researched, balanced, and Islamically grounded analysis of non-Islamic festivals, this book provides the comprehensive reference that the community needs.`,
    metaDescription: "Ghair Islami Tehwar — Urdu book on non-Islamic festivals. History, facts, Islamic rulings on Valentine's Day, Halloween, Christmas, others. Scholarly guidance. Buy online."
  },
  {
    slug: "gham-na-kren-dont-be-sad",
    description: `Gham Na Kren... (Don't Be Sad) is the Urdu translation of the internationally bestselling Islamic book "La Tahzan" (Don't Be Sad) by the renowned Saudi scholar Dr. A'idh al-Qarni — a book that has brought comfort, hope, and practical spiritual guidance to millions of Muslims worldwide who are struggling with sadness, anxiety, grief, disappointment, and the various emotional challenges of modern life. Priced at Rs.1,800, this Urdu edition makes the transformative message of the original Arabic work accessible to the vast Urdu-speaking Muslim population in Pakistan, India, Bangladesh, and the global diaspora — addressing a critical need in a region where mental health awareness is growing but culturally appropriate Islamic guidance on emotional well-being remains scarce.

The book's central thesis is both simple and profound — that sadness and despair are not the natural state of a believer, that Islam provides comprehensive tools for overcoming emotional difficulties, and that true happiness is achievable through the practical application of Islamic principles rather than through the materialistic, pleasure-seeking approaches promoted by modern secular culture. Dr. al-Qarni draws upon the Quran, the hadith of Prophet Muhammad (ﷺ), the wisdom of the early Muslim scholars, and insights from Islamic psychology to present a holistic approach to emotional well-being that addresses the root causes of sadness rather than merely suppressing its symptoms.

The book is organized into short, focused chapters that each address a specific cause of sadness and its Islamic remedy. Chapters address topics such as: the relationship between faith and emotional resilience, how to handle grief over loss (death of loved ones, financial loss, loss of status), how to overcome the anxiety of uncertainty about the future, how to deal with betrayal and broken relationships, how to find meaning and purpose in suffering, how to combat negative thinking and self-doubt, how to develop gratitude as an antidote to sadness, the healing power of dhikr (remembrance of Allah), the role of prayer and supplication in emotional healing, the importance of positive companionship, the need for physical health and proper sleep in maintaining emotional balance, and the Islamic perspective on clinical depression and when to seek professional help. Each chapter combines spiritual guidance with practical advice — making the book not just inspirational but genuinely useful for readers who are actively struggling with emotional challenges.

The Urdu translation maintains the warmth, empathy, and practical orientation of the original Arabic text while using language that resonates naturally with Urdu-speaking readers. The translator has ensured that the hadith references and scholarly quotations are accurately rendered while remaining accessible to readers without advanced Islamic education. The book's tone is consistently compassionate — Dr. al-Qarni writes as a caring counselor rather than a distant scholar, sharing his own experiences with sadness and the techniques he found effective in overcoming them. For anyone in Pakistan who is going through a difficult period, for counselors and therapists seeking an Islamic framework for emotional support, and for families looking for a gift that communicates genuine care and practical spiritual help, this Urdu translation of Don't Be Sad provides a message of hope, healing, and resilient faith that has already changed millions of lives worldwide.`,
    metaDescription: "Gham Na Kren (Don't Be Sad) — Urdu translation of Dr. al-Qarni's bestselling book on overcoming sadness through Islam. Quranic healing, practical advice. Rs.1800."
  }
];

async function main() {
  let updated = 0, failed = 0;
  for (const item of updates) {
    try {
      await prisma.product.update({ where:{slug:item.slug}, data:{description:item.description, metaDescription:item.metaDescription} });
      console.log(`✅ Updated: ${item.slug}`);
      updated++;
    } catch (err) { console.log(`❌ Failed: ${item.slug} — ${err.message}`); failed++; }
  }
  console.log(`\nBatch R4H-R4J complete: ${updated} updated, ${failed} failed`);
}
main().then(() => prisma.$disconnect());
