const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "mukhtasar-sahih-al-bukhari-2-volume-set",
    description: `An abridged Sahih al-Bukhari serves a practical need that the complete collection, spanning approximately seven to nine volumes depending on the edition, cannot efficiently fulfill. This local two-volume mukhtasar provides a streamlined selection of narrations from the most authentic hadith collection in Islamic literature, designed for readers who need reliable access to Bukhari's essential content without navigating its full extensive corpus. The abridgment prioritizes the hadith most frequently cited in scholarly discourse, most directly relevant to daily religious practice, and most instructive for understanding the foundational principles of Islam.

The selection criteria for this abridgment reflect a practical editorial philosophy. Narrations that appear in multiple chapters of the original—indicating their relevance across multiple topics—are given priority. Hadith that establish legal rulings accepted by all four schools of Sunni jurisprudence receive emphasis, as do narrations that articulate core theological positions and ethical principles. The compiler has also retained narrations that provide historical context for Quranic verses and events in the Prophet's life, recognizing that Sahih al-Bukhari functions not only as a legal reference but as a historical document of immense value.

The two-volume format represents a practical compromise between accessibility and comprehensiveness. A single-volume abridgment would require such aggressive condensation that much of the richness of Bukhari's work would be lost, while the full multi-volume set presents a barrier to regular reading and reference for all but dedicated scholars. Two volumes allow sufficient space for the hadith text, essential chains of narration, and brief explanatory notes while remaining portable enough for use in study circles, classrooms, and home libraries.

This local edition is produced with considerations of cost and availability that make it more accessible than imported alternatives. The binding is sturdy enough for regular reference use, and the typography is clear and readable. For madrasah students who need a Bukhari reference for their hadith studies, for imams preparing Friday sermons, for families building their Islamic library on a budget, and for individual readers who have committed to reading Bukhari but find the full set daunting, this two-volume mukhtasar delivers the essential content of Islam's most revered hadith collection in a practical, accessible format.`,
    metaDescription: "Local two-volume abridged Sahih al-Bukhari offering essential narrations with practical selection criteria for students, imams, and home library reference."
  },
  {
    slug: "mukhtasar-sahih-bukhari-large-urdu",
    description: `The large-format Urdu edition of Mukhtasar Sahih al-Bukhari caters specifically to readers who benefit from generous typography and spacious page layout. For elderly readers, for those with visual impairments, and for anyone who finds standard-sized print fatiguing during extended reading sessions, this large-format edition removes a physical barrier to engaging with the most authentic hadith collection in Islamic literature. The expanded page size allows for a larger typeface, more generous line spacing, and wider margins for those who wish to annotate the text.

The content presents the abridged selection of Sahih al-Bukhari's narrations in clear Urdu translation. Each hadith is rendered with attention to both literal accuracy and readability, avoiding the awkward phrasing that sometimes results from overly literal translation while remaining faithful to the meaning of the Arabic original. The chains of narration are included in transliterated form, allowing readers who know Arabic script but find Urdu more accessible to follow the isnad of each narration.

The large format also enhances the usability of the book in group settings. When used in a study circle, halaqah, or classroom, the larger text can be read from a distance, facilitating shared reading without requiring each participant to have their own copy. For imams and khateebs who read from the text during sermons or lectures, the large print reduces the likelihood of reading errors and allows for easier reference during delivery.

The abridged content covers the major themes of Sahih al-Bukhari: the book of revelation, the book of faith, the book of knowledge, the book of ablution, the book of prayer, the book of the Friday prayer, the book of the two Eid prayers, the book of funeral rites, the book of Zakat, the book of fasting, the book of pilgrimage, the book of marriage, the book of trade, and the book of manners. The selection reflects the hadith most essential for understanding Islamic practice and belief, distilled from the complete collection into a manageable volume. For Urdu-speaking households where multiple generations read together, for elderly scholars and students, and for institutions serving visually diverse populations, this large Urdu edition of Mukhtasar Sahih Bukhari fills an important need with both its content and its physical design.`,
    metaDescription: "Large-print Urdu edition of abridged Sahih al-Bukhari with generous typography, suitable for elderly readers, study circles, and shared reading sessions."
  },
  {
    slug: "mukhtasar-sahih-muslim-arabic",
    description: `Sahih Muslim, the second of the two most authoritative hadith collections in Sunni Islam, holds a status that places it second only to Sahih al-Bukhari in terms of authenticity and scholarly acceptance. This Arabic mukhtasar—or abridged—edition provides readers with a curated selection of Imam Muslim ibn al-Hajjaj's narrations, presented entirely in the original Arabic language, making it an ideal resource for students and scholars who read and study hadith in their source language.

The abridgment methodology employed in this edition reflects a scholarly approach to condensation. Rather than simply removing hadith to reduce length, the compiler has identified narrations that overlap in content and retained the most complete or best-authenticated version of each report. Imam Muslim's practice of presenting multiple chains of narration for the same hadith—a feature that enhances the scholarly value of the complete collection—has been streamlined in this abridgment, with representative chains preserved while redundant repetitions are reduced. This approach maintains the authenticity and scholarly integrity of the collection while making it more manageable for regular study and reference.

The Arabic text is presented with clear vocalization (tashkeel) where necessary to ensure correct pronunciation and grammatical understanding. For students of Arabic who are building their reading proficiency, the vocalized text provides valuable support for understanding the grammatical structure of classical Arabic hadith language. The chapter headings and organizational structure of Imam Muslim's original work are preserved, allowing readers to navigate the collection by topic and to appreciate the logical framework that guided Muslim's editorial decisions.

This edition serves several distinct audiences. Students at Arabic-medium Islamic seminaries use it as a hadith textbook that introduces them to Imam Muslim's collection without requiring engagement with the full multi-volume work. Advanced readers of Arabic who wish to maintain their connection to the primary sources of Islamic knowledge find the abridged format more practical for daily reading than the complete collection. Scholars and researchers who need quick access to representative narrations from Sahih Muslim appreciate the efficiency of the abridged format for reference purposes. By presenting the abridgment entirely in Arabic, this edition preserves the linguistic richness and scholarly precision that translations inevitably attenuate.`,
    metaDescription: "Arabic abridged edition of Sahih Muslim with vocalized text, preserved chapter structure, and scholarly selection for seminary students."
  },
  {
    slug: "mukhtaser-riyad-us-saliheen-urdu",
    description: `Imam Yahya ibn Sharaf al-Nawawi's Riyad us-Saliheen has earned its reputation as one of the most beloved hadith collections in the Muslim world by focusing on the practical and spiritual dimensions of Prophetic guidance rather than complex legal discussions. This Urdu edition of the mukhtasar provides a different editorial approach from other available abridgments, with its own distinctive selection of narrations, translation style, and organizational format that sets it apart for readers who may already be familiar with other editions.

The translator and abridger of this edition has approached the task with a focus on making the hadith immediately applicable to the daily lives of Urdu-speaking readers. The selection of narrations emphasizes those that directly address situations and challenges common to contemporary Muslim households: family relationships, neighborly conduct, workplace ethics, financial dealings, and the routines of worship and remembrance. While the foundational narrations on faith, prayer, fasting, and pilgrimage are included, particular attention has been given to hadith concerning moral character, social responsibility, and the cultivation of positive habits.

The Urdu translation in this edition employs a style that balances formal religious vocabulary with accessible everyday language. Technical terms from hadith science and Islamic jurisprudence are explained where they first appear, reducing the need for external reference materials. The explanatory notes added by the editor provide context for narrations that might otherwise be misunderstood without knowledge of the historical circumstances in which they were recorded.

This edition's distinctive contribution lies in its practical orientation. Each chapter concludes with a brief summary of the key lessons derived from the narrations, helping readers translate the hadith text into actionable guidance. The summaries address common questions: What does this hadith teach us about our daily conduct? How can we implement this teaching in our current circumstances? What should we avoid based on this narration? For Urdu-speaking readers who want a hadith collection that functions as a practical guide to righteous living rather than a purely academic reference, this edition of Mukhtasar Riyad us Saliheen offers a uniquely useful and reader-friendly approach to engaging with the Prophetic heritage.`,
    metaDescription: "Distinctive Urdu abridged Riyad us Saliheen with practical focus, accessible translation, and chapter summaries for daily application."
  },
  {
    slug: "mukhtasir-tafseer-fath-ul-qadeer",
    description: `Tafsir Fath al-Qadir, authored by the renowned scholar Imam al-Shawkani, represents one of the most significant exegetical works in Islamic scholarly tradition. This mukhtasir—abridged—edition distills the essential content of this comprehensive tafsir into a more accessible format while preserving the distinctive methodological features that distinguish al-Shawkani's approach to Quranic interpretation.

Al-Shawkani's original tafsir is notable for its emphasis on linguistic analysis and its commitment to deriving rulings directly from the Quran and authentic hadith rather than deferring uncritically to the opinions of earlier scholars. He was associated with the tendency toward ijtihad—independent legal reasoning—and his tafsir reflects this orientation by frequently presenting evidence and arguments for positions that differ from those of the established schools of jurisprudence. This abridged edition retains the most important instances of this analytical approach, giving readers insight into al-Shawkani's method even in condensed form.

The abridgment covers all 114 surahs of the Quran, with the commentary on each verse reduced to its essential elements. Where al-Shawkani provides multiple opinions on a particular verse, the abridgment typically retains the opinion he favors along with his reasoning, while reducing or omitting the detailed refutation of opposing views that characterizes the full work. Linguistic notes explaining rare words, grammatical constructions, and rhetorical devices are preserved where they significantly affect the meaning of the verse. References to hadith that illuminate the meaning or context of verses are retained with their chains of transmission and authenticity assessments.

For students of tafsir who find the complete Fath al-Qadir too extensive for practical use, this abridged edition provides a viable alternative that captures the work's scholarly essence. The concise format makes it suitable for use alongside Quran recitation, allowing readers to consult the commentary verse by verse without losing their place or becoming bogged down in lengthy discussions. Scholars who already possess the complete work may find the abridgment useful as a quick-reference tool for locating key interpretive points without paging through the multi-volume original. The edition represents a thoughtful effort to make one of Islamic scholarship's important exegetical works more widely accessible without compromising its intellectual substance.`,
    metaDescription: "Abridged edition of al-Shawkani's Fath al-Qadir tafsir preserving linguistic analysis, hadith evidence, and juristic reasoning in concise format."
  },
  {
    slug: "mukhtasir-zaadul-maaad-arabic",
    description: `Ibn al-Qayyim al-Jawziyyah's Zad al-Ma'ad fi Hadi Khayr al-Ibad stands as one of the most comprehensive and meticulously researched works on the Prophet's biography and the rulings derived from it. This Arabic mukhtasir provides an abridged version of this monumental text, making its essential content accessible to a broader readership while maintaining the scholarly rigor that has made the full work a staple of Islamic seminary curricula for centuries.

The original Zad al-Ma'ad is organized according to the chronological phases of the Prophet's life, and within each phase, it examines the legal rulings, recommended practices, and spiritual lessons that can be derived from the Prophet's conduct. This abridgment preserves this organizational framework while condensing the detailed discussions that characterize the full text. The sections on the Prophet's purification, prayer, fasting, pilgrimage, charity, jihad, dealings with people, illness, death, and the Hereafter are all represented, with the most essential rulings and narrations retained from each section.

What makes Zad al-Ma'ad unique among Prophetic biographies is its systematic extraction of fiqh rulings from the Seerah. Rather than merely narrating events, Ibn al-Qayyim uses each event as a source for legal and spiritual guidance, showing how the Prophet's conduct in specific situations establishes general principles of Islamic practice. This abridged edition preserves the most important of these extracted rulings, allowing readers to benefit from Ibn al-Qayyim's characteristic method of connecting Seerah to fiqh even in condensed form.

The book's sections on medicine and healing—drawn from the Prophet's recommendations for treating various ailments—have generated particular interest among contemporary readers. Ibn al-Qayyim's discussion of Prophetic medicine (al-tibb al-nabawi) is presented with the author's characteristic combination of hadith citation, scholarly commentary, and practical recommendation. The abridgment retains the most significant entries from this section, covering topics such as the use of honey, cupping, dietary recommendations, and the spiritual dimension of healing.

Presented entirely in Arabic, this mukhtasir serves students of Islamic seminaries, researchers in Seerah studies, and Arabic-speaking readers who wish to engage directly with Ibn al-Qayyim's seminal work without committing to the multi-volume original. The abridgment maintains the scholarly apparatus—hadith citations, chains of transmission, and references to other scholarly works—that allows readers to verify the content and pursue further study.`,
    metaDescription: "Arabic abridgment of Ibn al-Qayyim's Zad al-Ma'ad covering Prophetic biography, extracted legal rulings, and Prophetic medicine with scholarly references."
  },
  {
    slug: "muntakhab-qurani-waqiat",
    description: `The Quran contains numerous narratives involving prophets, communities, and individuals whose stories carry timeless lessons for believers. Muntakhab Qurani Waqiat presents a curated selection of these Quranic stories and events, extracted directly from the Quranic text and presented in a narrative format that makes them accessible and engaging for readers who may find the dispersed references across multiple surahs difficult to piece together.

The book organizes the selected events thematically rather than following the Quran's own sequence, grouping related narratives together to facilitate comparative understanding. The stories of Prophet Nuh and the flood, Prophet Ibrahim and his trials, Prophet Musa and the confrontation with Pharaoh, Prophet Isa and his ministry, and Prophet Muhammad and the key events of his mission each receive dedicated sections. The book also covers the stories of communities that received divine guidance and then deviated—the people of Ad, Thamud, Lut, and Madyan—extracting the moral and spiritual lessons from each narrative.

Each story is presented with the relevant Quranic verses cited in full, ensuring that the narrative remains directly connected to its divine source. The compiler has woven the verses into a coherent narrative flow, filling contextual gaps with brief explanatory notes that help readers understand the sequence of events, the relationships between characters, and the significance of key details mentioned in the Quran. This approach preserves the integrity of the Quranic text while making the stories accessible as complete narratives rather than fragmented references scattered across different surahs.

The book serves multiple practical purposes. For parents and teachers, it provides material for storytelling sessions with children, introducing them to Quranic narratives in an age-appropriate format. For new Muslims and those unfamiliar with the Quran's narrative content, it offers an accessible entry point that provides a broad overview of the Quran's historical and moral teachings. For general readers, it serves as a reminder of the wisdom contained in these divinely revealed stories and their relevance to contemporary life. The selection reflects a balance between the most well-known Quranic stories and lesser-known events that carry equally powerful lessons, giving readers a comprehensive yet focused engagement with the Quran's narrative treasury.`,
    metaDescription: "Curated selection of Quranic stories presented as coherent narratives with cited verses, organized thematically for parents and general readers."
  },
  {
    slug: "muntakhab-seerat-e-mustafa",
    description: `The life of Prophet Muhammad (peace be upon him) has been documented in thousands of works across centuries of Islamic scholarship, ranging from brief summaries to multi-volume encyclopedic treatments. Muntakhab Seerat e Mustafa occupies the valuable middle ground between these extremes, presenting a selected account of the Prophet's life that balances comprehensiveness with readability, scholarly accuracy with narrative engagement, and historical detail with spiritual insight.

The word "muntakhab"—meaning "selected" or "chosen"—indicates the book's editorial approach. Rather than attempting to include every reported event from the Prophet's life, the compiler has selected the most significant, best-authenticated, and most instructive incidents, presenting them in a narrative flow that carries the reader through the major phases of the Prophet's mission. The Makkan period—from revelation through persecution to migration—receives thorough treatment, with particular attention to the formative events that shaped the early Muslim community's character and resolve.

The Madinan period is covered with equal care, addressing the establishment of the Islamic state, the major battles, the treaties and diplomatic engagements, the expansion of Islam among the Arab tribes, and the farewell pilgrimage. The book does not shy away from addressing the complex and sometimes controversial events of this period, presenting them with historical context and reference to the major sources of Seerah literature. The treatment of events like the Battle of Uhud, the expulsion of the Banu Qaynuqa, and the Treaty of Hudaybiyyah reflects the mainstream scholarly understanding while acknowledging different perspectives where they exist.

The spiritual dimension of the Seerah receives dedicated attention throughout the text. The Prophet's night journey and ascension (Isra and Mi'raj), his private worship and devotion, his personal interactions that reveal his character, and his final illness and passing are presented with a sensitivity that conveys both the historical facts and their spiritual significance. The book concludes with reflections on the Prophet's legacy and the enduring relevance of his example for Muslims in every era. Written in Urdu with a style that is both scholarly and engaging, this selected Seerah serves as an excellent introduction for readers new to the Prophet's biography and as a concise reference for those already familiar with the subject.`,
    metaDescription: "Selected Urdu biography of Prophet Muhammad covering Makkan and Madinan periods with scholarly accuracy and spiritual insight into key events."
  },
  {
    slug: "musalman-bachey-ke-sunehray-shab-o-roz",
    description: `Establishing a structured Islamic routine from an early age is one of the most valuable gifts parents can give their children. Musalman Bachey ke Sunehray Shab o Roz—written in Urdu—provides a comprehensive framework for Muslim children's daily routine, translating the Sunnah practices of the Prophet Muhammad (peace be upon him) into age-appropriate guidelines that children can understand, learn, and practice as part of their everyday lives.

The book structures the child's day from the moment of waking to the time of sleeping, assigning Sunnah-based practices to each phase of the daily cycle. Morning practices include waking up with the prescribed supplication, using the miswak, performing wudu, reciting the morning azkar, and beginning the day with a positive, grateful attitude. The book explains each practice in simple Urdu that children can comprehend, often using relatable comparisons and gentle encouragement rather than stern instruction.

The section on meals teaches children the Islamic etiquette of eating: beginning with Bismillah, eating with the right hand, eating from the portion closest to oneself, not wasting food, expressing gratitude after eating, and the specific supplications before and after meals. These lessons are presented as normal, positive behaviors that make a child a "good Muslim" rather than as burdensome obligations. The book recognizes that children learn best through positive reinforcement, association, and gentle repetition rather than through lectures and criticism.

Playtime, school time, and social interactions are also addressed through an Islamic lens. The book teaches children how to greet others with salam, how to respect elders, how to share with siblings and friends, how to handle disagreements without anger, and how to be helpful at home. These social Sunnahs are presented as practices that make a child beloved to Allah, to the Prophet, and to their parents—creating a positive feedback loop that encourages continued practice.

The evening and nighttime routine receives particular emphasis, as the habits formed before sleep tend to be the most deeply ingrained. The bedtime supplications, sleeping on the right side, reciting ayat-ul-kursi and the three quls, and waking for tahajjud when possible are presented as comforting, protective practices that bring Allah's blessings and angels' protection. For parents seeking to raise their children with a strong foundation in Islamic practice, and for children who are ready to learn about their faith through practical, daily actions, this book provides an engaging and comprehensive guide.`,
    metaDescription: "Urdu guide for Muslim children's daily Sunnah routine from waking to sleeping with mealtime etiquette, social manners, and bedtime supplications."
  },
  {
    slug: "musalman-bachon-kay-liye-dilchsp-ramzan-package",
    description: `Ramadan holds a special excitement for Muslim children who observe the fasting, prayers, and communal activities of the blessed month alongside their families. This Urdu-language Ramadan package for children—labeled "Dilchasp," meaning "interesting" or "fascinating"—has been assembled to make the month of Ramadan an engaging, educational, and spiritually enriching experience for young Muslims. Rather than treating Ramadan as a period of deprivation or boredom, the materials in this package present the month as a time of joy, learning, and growing closer to Allah.

The package typically includes a combination of storybooks, activity sheets, dua cards, and informational guides that together create a comprehensive Ramadan experience for children. The storybooks narrate the events of Ramadan in an age-appropriate manner—the revelation of the Quran during Laylat al-Qadr, the battles of Badr and the Conquest of Makkah that occurred during Ramadan, and the stories of the Prophet and his Companions during the fasting month. These narratives help children understand the historical and spiritual significance of Ramadan while keeping them entertained.

Activity components encourage active engagement with the month's themes. Coloring pages featuring Ramadan motifs, puzzles that teach Islamic concepts, tracking charts for daily prayers and Quran recitation, and spaces for recording good deeds all turn passive learning into active participation. Children who track their progress visually develop a sense of accomplishment that motivates continued effort throughout the month. The tracking and recording activities also help parents monitor their children's engagement and provide targeted encouragement where needed.

The dua cards included in the package teach children the essential supplications associated with Ramadan: the dua for breaking the fast, the dua for suhoor, the dua for Laylat al-Qadr, and daily azkar appropriate for the fasting month. The cards are designed for ease of use—large enough for children to read, durable enough to withstand daily handling, and organized for quick reference. The informational guides explain the rules of fasting in simple terms that children can understand, addressing common questions like whether young children should fast, what breaks the fast, and how to make the most of Ramadan's spiritual opportunities. For families looking to make their children's Ramadan experience meaningful and memorable, this package provides a complete toolkit.`,
    metaDescription: "Urdu Ramadan package for Muslim children featuring storybooks, activity sheets, dua cards, and tracking charts for an engaging fasting month."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
