const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "anokhay-mehmaan-qissa-syedna-ishaq-silsila-qasas-ul-anbiya-830",
    description: `Anokhay Mehmaan (Qissa Syedna Ishaq) is the eighth installment in the Silsila Qasas ul Anbiya series, a popular Urdu-language collection of books that narrates the stories of the Prophets in a format specifically designed for children and young readers. This particular volume focuses on the life of Prophet Ishaq (Isaac), peace be upon him, the son of Prophet Ibrahim (Abraham). The title "Anokhay Mehmaan" translates to "The Unique Guests," referring to the extraordinary visit of the angels who came to Prophet Ibrahim's household with the glad tidings of a righteous son, Ishaq, despite his parents' old age. The story addresses the miraculous nature of Ishaq's birth and the profound faith that both Ibrahim and his wife Sarah demonstrated upon receiving this news from Allah.

The Silsila Qasas ul Anbiya series is structured as a numbered collection of thirty individual booklets, each dedicated to a different prophet or a significant episode from prophetic history. Volume 8, covering Prophet Ishaq's story, places the narrative within its proper Quranic context by referencing the relevant verses from Surah Hud and Surah As-Saffat where the birth of Ishaq and his role as a forefather of the Children of Israel are mentioned. The storytelling approach used in this series balances historical accuracy with an engaging narrative style that keeps young readers interested while ensuring that the Islamic values embedded in each story — such as tawakkul (reliance on Allah), patience, gratitude, and the importance of righteous family life — come through clearly and memorably.

Written in simple, fluent Urdu, this booklet is accessible to children who are developing their reading skills, typically in the age range of 7 to 14 years. The language avoids overly complex vocabulary or dense theological discussions, instead focusing on the narrative elements that children can easily follow and relate to. Parents and teachers frequently use this series as bedtime reading material or as part of Islamic studies curricula in homes and weekend schools. The booklet format keeps each volume compact and manageable, allowing children to complete an entire story in one or two sittings. The Silsila Qasas ul Anbiya series as a whole provides a comprehensive introduction to prophetic history, and this eighth volume about Prophet Ishaq teaches children about the power of dua (supplication), Allah's ability to make the impossible possible, and the continuation of the prophetic lineage through Ishaq to the later prophets including Yaqub, Yusuf, Musa, and ultimately Isa (Jesus), peace be upon them all.`,
    metaDescription: "Anokhay Mehmaan tells Prophet Ishaq's story in Urdu for children. Part 8 of the Silsila Qasas ul Anbiya series on prophetic history."
  },
  {
    slug: "anokhi-khushkhabri-qissa-syedna-zakariyya-silsila-qasas-ul-anbiya-2730",
    description: `Anokhi Khushkhabri (Qissa Syedna Zakariyya) is the twenty-seventh volume in the Silsila Qasas ul Anbiya series, a well-known Urdu-language collection presenting the stories of the Prophets for younger audiences. This installment is dedicated to the life of Prophet Zakariyya (Zechariah), peace be upon him, and his supplication to Allah for a righteous offspring despite his old age and his wife's barrenness. The title "Anokhi Khushkhabri" translates to "The Unique Glad Tidings," referring to the angelic announcement that Zakariyya would be blessed with a son named Yahya (John), who would be a prophet of great character and piety. This story is drawn directly from the Quranic account in Surah Maryam and Surah Al-Anbiya, where Allah describes how Zakariyya, upon seeing Maryam receiving fresh provisions from Allah, was inspired to pray for a similar blessing for himself.

The narrative in this volume follows Prophet Zakariyya's journey from his role as the caretaker of Maryam (Mary), mother of Prophet Isa (Jesus), through his private supplication in the prayer niche, the miraculous good news delivered by the angels, and the subsequent birth and upbringing of Yahya. The book highlights several important themes: the power of sincere dua, Allah's mercy toward His servants who trust in Him, the concept of miracles in the prophetic tradition, and the qualities that made Yahya unique — including his wisdom, compassion, and his role as a confirmer of Isa's prophethood. The Silsila Qasas ul Anbiya series treats each prophet's story with reverence and scholarly grounding while adapting the language for a younger readership.

Written in clear and straightforward Urdu suitable for children aged 7 to 14, this booklet can be read independently by older children or enjoyed as a read-aloud story by parents and teachers. The narrative style is engaging without being dramatized beyond what Islamic scholarship permits, ensuring that the stories remain faithful to their Quranic and hadith sources. Teachers at Islamic schools and madrasahs often assign individual volumes from this series as supplementary reading, helping students connect with prophetic history in an age-appropriate way. As volume 27 of a 30-part series, this booklet arrives at a later point in the prophetic timeline, bridging the gap between the Bani Israel prophets and the coming of the final messenger. The story of Zakariyya and Yahya is particularly relevant for teaching children about patience in the face of personal hardship, trust in Allah's wisdom, and the importance of praying for righteous offspring.`,
    metaDescription: "Anokhi Khushkhabri narrates Prophet Zakariyya's story in Urdu for children. Volume 27 of Silsila Qasas ul Anbiya on prophetic history."
  },
  {
    slug: "aqwam-e-aalam-kay-adyan-o-mazahib",
    description: `Aqwam e Aalam Kay Adyan o Mazahib is a comprehensive Urdu-language reference work that surveys the major religions and belief systems of the world's nations and peoples. The title translates to "The Religions and Faiths of the Nations of the World," and the book serves as a systematic comparative study designed primarily for Urdu-speaking readers who want to understand what different faiths teach, how they originated, and how their beliefs compare with Islamic teachings. The book covers the major world religions including Hinduism, Buddhism, Judaism, Christianity, Zoroastrianism, Sikhism, Jainism, and various indigenous and animistic traditions, along with sectarian movements and offshoots that have emerged within and around these major traditions throughout history.

The approach taken in this book is scholarly and informational rather than polemical. Each religion is described in terms of its foundational beliefs, sacred texts, key historical figures, rituals and practices, theological frameworks, and the cultural contexts in which it developed. The author presents each belief system based on established academic sources and the primary texts of each religion, giving readers an accurate picture of what adherents actually believe rather than relying on secondhand caricatures or misrepresentations. For each religion discussed, the book traces its historical origins, identifies its major denominations or schools of thought, and explains its core tenets in language that is clear and accessible to a general Urdu readership. Where relevant, comparisons with Islamic positions are drawn, not to denigrate other faiths but to highlight where agreement and disagreement exist, which is valuable for Muslims engaged in interfaith dialogue or dawah work.

This reference work is particularly useful for Islamic scholars, students of comparative religion, madrasah graduates who need a broader understanding of world faiths, and Muslim professionals working in diverse or multicultural environments. It is also a valuable resource for anyone preparing for academic examinations in Islamic studies, as comparative religion is a standard component of many Islamic seminary and university curricula. The book's Urdu prose is formal and scholarly, reflecting the academic nature of the subject matter, while remaining accessible to educated readers who may not have specialized training in religious studies. The organization of the material follows a logical progression, typically starting with the oldest known belief systems and moving chronologically through to modern religious movements, allowing readers to trace the historical development of human religious thought. For dawah practitioners, understanding other faiths at this level of depth is essential for communicating the message of Islam effectively and addressing the questions and objections that people from different religious backgrounds may have.`,
    metaDescription: "Aqwam e Aalam Kay Adyan o Mazahib is a comprehensive Urdu survey of world religions and their beliefs. Essential comparative religion reference."
  },
  {
    slug: "aqziya-tul-khulafa-ur-rashideen-2-vols-set",
    description: `Aqziya tul Khulafa ur Rashideen is a two-volume Urdu collection that compiles the biographical accounts and judicial decisions (aqziya) of the four Rightly Guided Caliphs — Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, and Ali ibn Abi Talib, may Allah be pleased with them all. The word "aqziya" refers specifically to judicial rulings, court cases, and legal decisions, which means this work focuses not just on the general biographies of these companions but particularly on their roles as heads of state and chief justices of the early Islamic state. The two-volume format allows for an in-depth treatment of each caliphate, providing readers with detailed accounts of how Islamic law was applied during the formative decades of Muslim governance.

The first volume typically covers the caliphate of Abu Bakr as-Siddiq and Umar ibn al-Khattab, while the second volume addresses the caliphates of Uthman ibn Affan and Ali ibn Abi Talib. For each caliph, the book documents the major judicial cases they presided over, their approach to dispute resolution, their method of interpreting and applying Quranic injunctions and prophetic precedents, and the legal principles they established that continue to influence Islamic jurisprudence to this day. The cases discussed range from property disputes and inheritance questions to criminal matters, governance issues, and matters of international relations with non-Muslim states. Each case is presented with its background, the arguments of the parties involved, the reasoning of the caliph, and the final judgment — giving readers insight into the practical application of Islamic law at the highest level of government.

This two-volume set is a significant resource for students of Islamic law (fiqh), scholars researching the early history of Islamic governance, and anyone interested in understanding how the companions of the Prophet implemented the teachings of Islam in the context of running a state. The Urdu text presents these historical accounts in a narrative style that is rooted in classical Islamic sources including the works of early historians like Al-Waqidi, Al-Baladhuri, and Ibn Jarir al-Tabari, as well as hadith collections and fiqh literature. The book demonstrates the caliphs' commitment to justice, their accessibility to common citizens who brought their disputes for resolution, and their meticulous care in ensuring that rulings aligned with the Quran and Sunnah. It also reveals their human qualities — their humility, their willingness to consult others, and their refusal to claim infallibility. For judges, lawyers, muftis, and students of shariah, this set provides practical case studies in Islamic judicial methodology that are as instructive today as they were fourteen centuries ago.`,
    metaDescription: "Aqziya tul Khulafa ur Rashideen is a 2-volume Urdu set on the judicial rulings of the four Rightly Guided Caliphs. Essential Islamic law reference."
  },
  {
    slug: "aqziya-tur-rasool-allah-2-vols-set",
    description: `Aqziya tur Rasool Allah is a two-volume Urdu compilation that documents the judicial decisions, legal rulings, and dispute resolutions of Prophet Muhammad (peace be upon him) during his lifetime as the head of the Muslim community in Madinah. The term "aqziya" (plural of qaziyah) refers to court cases and legal judgments, making this work a specialized collection that focuses on the Prophet's role as a judge and legal authority rather than covering his entire biography. The two-volume set provides an organized and detailed presentation of cases that the Prophet personally adjudicated, offering readers a window into the practical application of Islamic law during the formative period of the Muslim state.

The cases compiled in these volumes are drawn from authenticated hadith sources, the major books of sirah (prophetic biography), and classical works of Islamic jurisprudence. Each case entry typically includes the nature of the dispute, the parties involved, the evidence presented, the Prophet's questioning and reasoning process, and his final ruling along with any relevant Quranic verses or prophetic statements that informed his decision. The disputes covered span a wide range of legal categories: financial transactions and contracts, inheritance and family law, criminal cases including theft and murder, property disputes between individuals and tribes, matters related to treaties and agreements with non-Muslim communities, and issues of public welfare and governance. The two-volume structure allows the compiler to present a substantial number of cases without sacrificing the level of detail that each one requires for proper understanding.

For students and scholars of Islamic jurisprudence, this two-volume set is an indispensable reference because the Prophet's judicial decisions constitute the primary source of Islamic legal methodology after the Quran itself. Every madhhab (school of Islamic law) traces its principles back to how the Prophet handled these cases, and understanding the original contexts helps resolve contemporary legal questions. The book is written in formal Urdu that maintains academic rigor while remaining accessible to readers with a reasonable command of the language. Judges, muftis, lawyers practicing in shariah courts, and advanced students in Islamic seminaries will find this collection particularly valuable as a practical supplement to theoretical fiqh texts. The work also serves as a historical document illustrating the justice system of early Islam — one that was characterized by equal access to justice for all, regardless of social status, tribal affiliation, or wealth, and where the Prophet himself sat on the ground alongside litigants to hear their cases. This emphasis on accessible, impartial justice is one of the most enduring lessons that emerges from studying the aqziya of the Messenger of Allah.`,
    metaDescription: "Aqziya tur Rasool Allah is a 2-volume Urdu compilation of Prophet Muhammad's judicial rulings. Essential reference for Islamic law students and scholars."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu",
    description: `Ar Raheeq Al Makhtum (Urdu) is the Urdu translation of one of the most celebrated and widely read books on the life of Prophet Muhammad (peace be upon him). Originally authored in Arabic by the eminent scholar Safiur Rahman Mubarakpuri under the full title "Al-Raheeq Al-Makhtum" (The Sealed Nectar), this book earned first prize in the Seerah writing competition organized by the Rabitat al-Alam al-Islami (Muslim World League) in Makkah al-Mukarramah, a distinction that speaks to its scholarly authority and literary quality. The Urdu translation brings this acclaimed work to the vast Urdu-speaking Muslim population across Pakistan, India, Bangladesh, and diaspora communities worldwide, making the comprehensive biography of the Prophet accessible in one of the most widely understood languages of the Muslim world.

The book provides a complete chronological account of the Prophet's life from his birth in Makkah through his childhood, his prophethood, the Makkan period of persecution and patience, the migration to Madinah, the establishment of the Islamic state, the major battles and treaties, the conquest of Makkah, the Farewell Pilgrimage, and his eventual passing. Each phase of the Prophet's life is documented with references to authentic hadith sources, classical historical works, and the Quran itself. The author's methodology is to present events in their proper historical sequence while drawing out the lessons, wisdom, and guidance that each event offers to Muslims in every era. The writing style is narrative and engaging, making complex historical events easy to follow without oversimplifying their significance.

This standard Urdu edition of Ar Raheeq Al Makhtum is printed in a regular book size with clear Urdu typography, making it suitable for personal reading, group study in halaqat (study circles), and as a textbook in Islamic schools and madrasahs. The book is organized into clearly defined chapters that correspond to major phases of the Prophet's life, and includes indexes and source references that aid further research. It has become a staple in Urdu-speaking Muslim households, commonly given as a gift on occasions such as Eid, Ramadan, and at Islamic book fairs. The Ar Raheeq Al Makhtum in Urdu occupies a unique position in the Urdu Islamic literary landscape — it is simultaneously a work of historical scholarship, a spiritual guide, and a literary masterpiece that inspires love and reverence for the Prophet while providing historically accurate information about his life and mission. Scholars recommend it as a starting point for anyone who wants to study the seerah seriously, and it continues to be one of the best-selling Islamic books in the Urdu language.`,
    metaDescription: "Ar Raheeq Al Makhtum (Urdu) is the acclaimed Urdu translation of Safiur Rahman Mubarakpuri's prize-winning seerah. Complete biography of Prophet Muhammad."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu-aala-quality",
    description: `Ar Raheeq Al Makhtum (Urdu) Aala Quality is the premium edition of the celebrated Urdu translation of Safiur Rahman Mubarakpuri's prize-winning biography of Prophet Muhammad (peace be upon him). The original Arabic work "Al-Raheeq Al-Makhtum" (The Sealed Nectar) won first prize in the international Seerah writing competition organized by the Muslim World League in Makkah, establishing it as one of the most authoritative and respected biographies of the Prophet in modern Islamic literature. This "Aala Quality" (premium quality) edition distinguishes itself from standard printings through the use of superior paper, enhanced printing techniques, and a more durable binding that is designed for readers who want a long-lasting, gift-worthy copy of this essential work.

The content of this premium edition is identical to the standard Urdu translation, covering the complete life of the Prophet from his birth to his passing, with detailed accounts of the Makkan period, the Hijrah, the establishment of the Islamic state in Madinah, the major military campaigns, treaties, and the social and legal framework that the Prophet established. What sets this Aala Quality edition apart is its physical production. The paper used is a higher-grade, thicker stock that resists yellowing and tearing, providing a superior reading experience that is easier on the eyes during extended study sessions. The printing quality is sharper, with crisper Urdu text that enhances readability and reduces eye fatigue. The binding is reinforced with stronger stitching and a more rigid cover construction that prevents the spine from cracking even after years of frequent use and handling.

The premium presentation of this edition makes it an ideal choice for gift-giving on significant occasions such as weddings, Eid celebrations, graduations from Islamic studies programs, and as a presentation copy for scholars and teachers. Many Islamic institutions and organizations select the Aala Quality edition for their library collections because the enhanced durability ensures the book will withstand years of use by multiple readers. The cover design of this premium edition is typically more elaborate than the standard version, often featuring foil stamping, embossed elements, or a leatherette finish that gives the book a distinguished appearance on any bookshelf. Despite its premium production, the content maintains the same scholarly rigor and accessibility that has made Ar Raheeq Al Makhtum the most recommended seerah book in the Urdu language. For readers who study the Prophet's life regularly — whether through structured courses, personal study plans, or teaching responsibilities — investing in the Aala Quality edition means having a reliable, durable reference that will serve them well for many years.`,
    metaDescription: "Ar Raheeq Al Makhtum Urdu Aala Quality is a premium edition of the prize-winning Prophet's biography. Superior paper and binding for lasting use."
  },
  {
    slug: "ar-raheeq-al-makhtum-urdu-big",
    description: `Ar Raheeq Al Makhtum (Urdu) Big is a large-format edition of the celebrated Urdu translation of Safiur Rahman Mubarakpuri's comprehensive biography of Prophet Muhammad (peace be upon him). The original Arabic work "Al-Raheeq Al-Makhtum" (The Sealed Nectar) holds the distinction of winning first prize in the Seerah writing competition held by the Muslim World League in Makkah, and its Urdu translation has become one of the most widely read Islamic books in the Urdu-speaking world. This big format edition provides the same complete, authoritative content in an enlarged physical size that enhances readability and makes the book more comfortable for extended study sessions.

The large format increases the page dimensions significantly compared to the standard edition, which means the Urdu text is printed in a larger font size with more generous line spacing and wider margins. This enhancement is particularly beneficial for several reader groups. Elderly readers who may find the smaller text of standard editions difficult to read without strain can use this big edition comfortably for extended periods. Quran teachers, Islamic studies instructors, and khateebs who reference the seerah during lectures and sermons benefit from the larger text, which is easier to read at a glance without having to hold the book close. Readers with visual impairments who do not require Braille but need enlarged print will find this format accessible. Additionally, the big format is preferred in group study settings where a teacher or discussion leader may want to place the book open on a table for multiple participants to read from.

The content covers the Prophet's entire life chronologically, from the lineage and birth of the Prophet through the Makkan period, the Hijrah to Madinah, the establishment of the Islamic state, major events including the battles of Badr, Uhud, and the Trench, the Treaty of Hudaybiyyah, the Conquest of Makkah, the Farewell Pilgrimage, and the Prophet's final illness and passing. The binding of the big format edition is reinforced to support the larger and heavier pages, with a sturdy spine that resists cracking even when the book is opened flat on a desk. The cover materials are chosen for durability to match the enhanced production quality. This large-format edition of Ar Raheeq Al Makhtum is commonly found in mosque libraries, Islamic school resource rooms, madrasah libraries, and the personal collections of scholars and teachers who value both the content and the enhanced readability that the bigger format provides.`,
    metaDescription: "Ar Raheeq Al Makhtum Urdu Big is a large-format edition of the prize-winning seerah. Enlarged text for comfortable reading in homes and mosques."
  },
  {
    slug: "ar-raheeq-al-makhtum-10x15",
    description: `Ar-Raheeq Al-Makhtum 10x15 is a specific dimensional variant of the renowned biography of Prophet Muhammad (peace be upon him) by Safiur Rahman Mubarakpuri. The "10x15" designation refers to the page dimensions, which typically indicate approximately 10 by 15 inches — a size that is significantly larger than standard book formats. This oversized edition presents the complete text of Al-Raheeq Al-Makhtum (The Sealed Nectar), the first-prize winning seerah from the Muslim World League competition in Makkah, in a format designed for maximum readability and visual impact, making it suitable for display, group reading, and reference in institutional settings.

The 10x15 large format serves several practical purposes in the context of Islamic education and scholarship. In classroom and lecture hall settings, teachers and lecturers who are discussing the Prophet's life can place this oversized book on a desk or easel where the text is visible to students seated at a distance, facilitating group reading and discussion. Mosque imams and khateebs who prepare sermons and religious talks based on seerah events find the large format easier to reference during preparation and consultation. Library and reference collections at Islamic seminaries, universities, and research institutions benefit from having a prominent, easily accessible copy that patrons can consult for research. The large pages also allow for clearer typography and more comfortable reading during extended study sessions, reducing eye strain compared to smaller editions.

The content within this 10x15 edition is the same comprehensive, chronologically organized biography that has made Ar-Raheeq Al-Makhtum the most recommended seerah book across the Muslim world. It covers the Prophet's lineage, birth, childhood, prophethood, the Makkan period of persecution, migration to Madinah, establishment of the Islamic state, the major battles, treaties, social reforms, the Conquest of Makkah, the Farewell Pilgrimage, and the Prophet's passing — all supported by authentic hadith references and classical historical sources. The binding of this oversized edition is specially reinforced to support the weight and dimensions of the large pages, with a robust spine construction and durable cover materials. The paper quality is chosen to match the premium format, providing good opacity and durability. This edition makes an impressive addition to any Islamic library or educational institution, combining scholarly content with a presentation format that honors the significance of the subject matter.`,
    metaDescription: "Ar-Raheeq Al-Makhtum 10x15 is an oversized edition of the prize-winning seerah. Large format for classrooms, mosques, and libraries."
  },
  {
    slug: "arabic-learn-the-easy-way",
    description: `Arabic Learn the Easy Way is an English-language instructional book designed to teach the fundamentals of Arabic language to non-Arabic speaking students, particularly those who are learning Arabic for the purpose of understanding the Quran and Islamic texts. The book adopts a simplified, step-by-step pedagogical approach that breaks down the complexities of Arabic grammar, vocabulary, and sentence structure into manageable lessons, making the language accessible to beginners who may have no prior exposure to Arabic beyond the ability to read the basic Arabic script. The title reflects the book's core methodology: presenting Arabic in a way that feels natural and intuitive rather than overwhelming.

The book typically begins with the Arabic alphabet and its various forms (initial, medial, and final positions), then progresses to vowel marks (harakat), basic vocabulary, simple sentence construction, and the foundational rules of Arabic grammar (nahw and sarf). Each lesson builds upon the previous one, reinforcing earlier concepts while introducing new material at a measured pace. The vocabulary selected for the early lessons is drawn heavily from words that appear frequently in the Quran and everyday Islamic discourse, ensuring that students begin to recognize familiar terms as they encounter them in their religious reading. Grammar rules are explained in clear English with abundant examples, and the relationship between Arabic root words and their derived forms is systematically introduced to help students understand how Arabic vocabulary works at a structural level.

This book is particularly popular among new Muslims who are beginning their journey into Islamic knowledge and need to develop their Arabic skills from scratch. It is also widely used in weekend Islamic schools, adult education programs at mosques, homeschooling curricula, and self-study contexts where students are working through the material independently. The format is designed for practical use, with exercises and review sections that allow students to test their understanding as they progress. Teachers appreciate the clear explanations and the logical sequencing that makes lesson planning straightforward. Unlike purely academic Arabic textbooks designed for university linguistics programs, this book maintains its focus on the kind of Arabic that Muslims actually need — the language of the Quran, hadith, supplications, and basic religious discourse. By the time a student completes this book, they should have a solid foundation in Arabic grammar and enough vocabulary to begin engaging with simplified Quranic texts and basic Islamic literature, making it an excellent stepping stone to more advanced Arabic study.`,
    metaDescription: "Arabic Learn the Easy Way teaches Arabic fundamentals in English for beginners. Quran-focused vocabulary and grammar for new Muslims and Islamic students."
  },
  {
    slug: "arkan-e-islam-o-imaan-new-edition",
    description: `Arkan-e-Islam-o-Imaan (New Edition) is an Urdu-language Islamic educational book that provides a comprehensive and updated treatment of the foundational pillars of Islam and the articles of faith. The title translates to "The Pillars of Islam and Faith," and the book systematically explains the five pillars of Islam — Shahadah (testimony of faith), Salat (prayer), Zakat (charity), Sawm (fasting), and Hajj (pilgrimage) — along with the six articles of Imaan (faith) — belief in Allah, His angels, His revealed books, His messengers, the Day of Judgment, and divine predestination (qadr). The "New Edition" designation indicates that this version has been revised, expanded, or updated from its previous printing to incorporate improvements in content, organization, or scholarly references.

For each pillar of Islam, the book provides detailed guidance covering the theological basis from the Quran and hadith, the specific rulings and conditions that must be met for the act of worship to be valid, common mistakes and misunderstandings that people should avoid, and practical instructions on how to properly perform each obligation. The section on Salat, for instance, covers the preconditions of prayer, the obligatory and recommended elements, how to perform the prayer step by step, and the supplications recited in each position. The Hajj section explains the rituals of each day in order, the specific obligations versus the recommended acts, and the common errors that pilgrims make. The Zakat section details the types of wealth upon which Zakat is obligatory, the minimum thresholds (nisab), and the calculation methods for different asset categories.

The articles of faith section goes beyond a simple listing to provide meaningful explanations of what each article entails in terms of belief and practice. The chapter on belief in Allah covers the concept of Tawheed in its three categories — Tawheed ar-Rububiyyah (Lordship), Tawheed al-Uluhiyyah (Worship), and Tawheed al-Asma was-Sifat (Names and Attributes). The discussion of belief in the angels explains their nature, categories, and specific roles assigned to major angels like Jibreel, Mikael, Israfeel, and Azrael. The book's language is instructional and accessible Urdu suitable for a wide readership, from madrasah students and Islamic school pupils to general readers who want to strengthen their understanding of the fundamentals. The revised edition often includes additional content, improved formatting with clearer headings and subheadings, updated references to hadith sources, and sometimes fatwas or scholarly opinions that address contemporary questions about the pillars.`,
    metaDescription: "Arkan-e-Islam-o-Imaan New Edition is a revised Urdu guide to the five pillars and six articles of faith. Detailed rulings and practical instructions."
  },
  {
    slug: "as-shukar-gratitude",
    description: `As Shukar Gratitude is an English-language Islamic book that explores the concept of gratitude (shukr) as a central theme in Islamic teachings and practice. The book examines gratitude from multiple angles — as an act of worship, as a moral virtue, as a source of spiritual contentment, and as a practical approach to navigating life's challenges with faith and resilience. Drawing primarily from the Quran and authentic hadith, the author presents a thorough treatment of what it means to be truly grateful to Allah and how this gratitude transforms a Muslim's relationship with their Creator, their perspective on worldly circumstances, and their overall sense of well-being.

The book systematically explores the Quranic verses that address gratitude, including Allah's statements about grateful believers being few in number, the promise of increased blessings for those who are thankful, and the contrast between gratitude (shukr) and ingratitude (kufr) as fundamentally opposed spiritual orientations. The hadith references include the Prophet's teachings about being grateful for health, the importance of expressing gratitude in words, actions, and heart, and the connection between gratitude and patience (sabr) as complementary responses to Allah's decrees. The author also addresses the common psychological and spiritual barriers to gratitude — such as comparison with others, focus on what is lacking rather than what has been given, and the tendency to take blessings for granted — and offers Islamic perspectives on overcoming these obstacles.

Written in clear, accessible English, As Shukar Gratitude is suitable for a broad readership including Muslims who want to deepen their spiritual practice, new Muslims learning about Islamic character development, youth and young adults navigating modern challenges to faith, and anyone interested in the Islamic perspective on positive psychology and well-being. The book bridges the gap between scholarly theology and practical self-improvement, making complex concepts understandable without oversimplifying them. The format typically includes chapter divisions that address different dimensions of gratitude, reflection questions or discussion points, and practical suggestions for cultivating a grateful mindset in daily life. This book serves as both a personal development guide and a spiritual resource, reminding readers that gratitude is not merely an emotion but an active, intentional practice that lies at the heart of a meaningful Islamic life. It is often recommended by Islamic counselors, teachers, and imams for individuals going through difficult circumstances who need to reframe their perspective through the lens of gratitude and trust in Allah.`,
    metaDescription: "As Shukar Gratitude explores the Islamic concept of gratitude through Quran and hadith. English guide to cultivating thankfulness as a spiritual practice."
  },
  {
    slug: "asaan-tarjuma-quran-e-kareem",
    description: `Asaan Tarjuma Quran e Kareem is an Urdu translation of the Holy Quran specifically prepared to be easy to understand (asaan) for general readers who may not have advanced scholarly training in Islamic sciences. The subtitle "Aam Fehm aur Asaan Tarjuma" confirms that the translation is designed for common comprehension, using straightforward Urdu vocabulary and sentence structures that make the meaning of the Quranic text accessible to anyone with basic literacy in Urdu. This translation addresses a genuine need in the Urdu-speaking Muslim world, where many readers want to understand the Quran's message but find traditional translations written in classical, scholarly Urdu difficult to follow.

The translation methodology employed in this edition prioritizes clarity and readability without sacrificing accuracy. The translator has chosen to render Quranic concepts using everyday Urdu expressions that carry the intended meaning clearly, avoiding the use of heavily Arabicized Persian-Urdu that characterizes many older Quran translations. When a Quranic term or concept requires explanation, brief parenthetical notes or inline clarifications are provided to help the reader understand the context or the specific meaning intended. The result is a translation that reads more like natural Urdu prose while remaining faithful to the original Arabic meaning. This approach makes it possible for readers — including women, children, elderly individuals, and those with limited formal education — to read the Quran with understanding and connect with its message in a personal way.

This edition of the Asaan Tarjuma includes the complete Arabic text alongside the Urdu translation, typically arranged with the Arabic on the right page and the Urdu on the left (or in a parallel column format), allowing readers to follow the original Arabic while consulting the translation for understanding. The Arabic text is printed in clear, well-formed calligraphy with complete diacritical marks for proper recitation. Surah headings provide essential information including the place of revelation (Makki or Madani), the number of verses, and the thematic focus of each surah. This translation is widely used in homes for daily recitation with understanding, in mosques for congregational study circles, in madrasahs as a supplementary text alongside traditional tafsir studies, and by new Muslims and reverts who are building their relationship with the Quran in the Urdu language. Its popularity stems from the fact that it genuinely fulfills its promise of making the Quran's message accessible to ordinary readers without requiring years of specialized study.`,
    metaDescription: "Asaan Tarjuma Quran e Kareem offers a clear, easy-to-understand Urdu translation of the Holy Quran. Designed for common readers seeking direct access."
  },
  {
    slug: "asaan-tarjuma-quran-mufti-taqi-usmani",
    description: `Asaan Tarjuma Quran by Mufti Taqi Usmani is an Urdu translation of the Holy Quran prepared by one of the most respected contemporary Islamic scholars, Mufti Muhammad Taqi Usmani. This translation is specifically designed to provide an easy-to-understand (asaan) rendering of the Quranic text in fluent, contemporary Urdu, making the message of the Quran accessible to a wide range of Urdu-speaking readers. Mufti Taqi Usmani is widely recognized for his deep expertise in Quranic exegesis, Islamic jurisprudence, and hadith sciences, having served as a judge on the Federal Shariat Court of Pakistan and as a teacher at Darul Uloom Karachi for decades. His scholarly credentials give this translation a level of authority and trust that few other translations can match.

The distinguishing feature of this translation is the balance it strikes between accuracy and readability. Many traditional Urdu translations, while accurate, use a highly Persianized and classical Urdu style that can be difficult for modern readers to follow. Mufti Taqi Usmani's approach is to use clear, contemporary Urdu that conveys the Quranic meaning precisely while remaining accessible to readers who may not have advanced training in Islamic studies. The vocabulary is chosen to reflect the actual meaning of the Arabic text rather than merely transliterating Arabic words into Urdu script, which is a common weakness of less carefully prepared translations. Where the Arabic text contains idioms, metaphors, or cultural references that a modern Urdu reader might not immediately understand, the translation provides the intended meaning clearly.

This edition typically presents the complete Arabic text of the Quran alongside the Urdu translation in a parallel format, with clear typography and well-organized page layouts. The Arabic text includes full vowelization (tashkeel) for proper recitation, and the surah headings provide contextual information. Many printings of this translation also include brief footnotes or marginal notes where Mufti Taqi Usmani clarifies particularly important or commonly misunderstood verses. This translation has become one of the most widely used Urdu Quran translations in the world, commonly found in homes, mosques, madrasahs, and Islamic centers throughout Pakistan, India, Bangladesh, and among Urdu-speaking diaspora communities. It is recommended by scholars and teachers as a reliable primary translation for daily recitation with understanding, and it serves as the basis for the English translation "The Noble Quran" that Mufti Taqi Usmani also supervised. Students, scholars, and general readers all benefit from the clarity and scholarly precision that characterize this work.`,
    metaDescription: "Asaan Tarjuma Quran by Mufti Taqi Usmani is an authoritative, clear Urdu Quran translation. Scholarly yet accessible for all readers of Urdu."
  },
  {
    slug: "ashab-e-badr",
    description: `Ashab-e-Badr is an Urdu-language book that provides detailed biographical accounts of the companions of Prophet Muhammad (peace be upon him) who participated in the Battle of Badr — the first major military engagement between the Muslims of Madinah and the Quraysh of Makkah, fought in the year 2 AH (624 CE). The Battle of Badr holds a unique and exalted position in Islamic history because it was a small, vastly outnumbered Muslim force of approximately 313 men who achieved a decisive victory against a much larger and better-equipped Makkan army of around 1,000 soldiers. The Quran itself refers to the participants of Badr with special honor, and the Prophet singled out each Badri companion as someone whose companionship was dear to him. Ashab-e-Badr documents the lives of these distinguished individuals in a comprehensive and scholarly manner.

The book covers each of the major participants of the Battle of Badr, including the Muhajirun (emigrants from Makkah) and the Ansar (helpers from Madinah), providing biographical information that covers their pre-Islamic background, their conversion to Islam, their migration to Madinah (for the Muhajirun), their role in the Battle of Badr specifically, and their subsequent contributions to the early Muslim community. The accounts are drawn from classical Islamic sources including Sahih al-Bukhari, Sahih Muslim, the books of sirah by Ibn Hisham and Ibn Ishaq, the biographical dictionaries of Ibn Sa'd (Al-Tabaqat al-Kubra), and the works of Ibn al-Athir and Ibn Kathir. The level of detail provided for each companion varies based on the available historical material, but the book makes a concerted effort to include every named participant of Badr for whom any biographical information exists.

This work is particularly valuable for several categories of readers. Students of Islamic history gain a vivid understanding of the human dimension of the Battle of Badr — not just the strategic and military aspects, but the individual stories of faith, courage, sacrifice, and commitment that each companion brought to that pivotal moment. Scholars of hadith benefit from knowing the biographical details of the Badri companions, as their status as participants in Badr gives their narrations special weight and authenticity. General readers seeking spiritual inspiration find in these accounts powerful examples of unwavering faith in Allah, selfless devotion to the Prophet's mission, and the personal qualities — bravery, generosity, loyalty, and piety — that characterized the earliest generation of Muslims. The book is written in scholarly Urdu with references to source material, making it a reliable reference work while remaining engaging enough for general reading. Ashab-e-Badr fills an important gap in Urdu Islamic literature by providing a dedicated, single-volume reference focused exclusively on the companions of this historically and spiritually significant battle.`,
    metaDescription: "Ashab-e-Badr is an Urdu biographical work on the companions who fought at the Battle of Badr. Detailed accounts from classical Islamic sources."
  },
  {
    slug: "ashra-mubashra-ki-zindagiyon-ke-sunehre-waqiaat",
    description: `Ashra Mubashra ki Zindagiyon ke Sunehre Waqiaat is an Urdu-language book that presents the golden events and incidents from the lives of the Ashra Mubashra — the ten companions of Prophet Muhammad (peace be upon him) who were given the glad tidings of Paradise during their lifetimes. The term "Ashra Mubashra" (the ten who were given good news) refers to Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, Ali ibn Abi Talib, Talhah ibn Ubaidullah, Zubayr ibn al-Awwam, Abdur Rahman ibn Awf, Sad ibn Abi Waqqas, Abu Ubaidah ibn al-Jarrah, and Sad ibn Zayd, may Allah be pleased with them all. These companions hold a special rank in Islamic history due to this specific distinction bestowed upon them by the Prophet, and this book collects the most noteworthy and inspiring incidents from their lives.

The title "Sunehre Waqiaat" (golden events) indicates the book's focus on narrating specific, memorable incidents from each companion's life rather than providing exhaustive chronological biographies. Each chapter or section is dedicated to one of the ten companions and presents a selection of well-authenticated stories that illustrate their character, their faith, their sacrifices for Islam, their relationship with the Prophet, and the qualities that earned them this unique distinction. The incidents include their conversion stories, their contributions during the Makkan and Madiani periods, their bravery in battle, their generosity in charity, their knowledge and wisdom, and their conduct as leaders and governors during the caliphate period. The stories are drawn from authentic hadith collections, classical works of sirah and tarikh, and the major biographical compilations of the companions.

Written in engaging and accessible Urdu, this book is designed to be both informative and spiritually uplifting. The narrative style brings each incident to life, allowing readers to visualize the events and connect emotionally with the experiences of these remarkable individuals. The book serves multiple audiences: general readers who want to increase their love for the companions and learn from their examples, students of Islamic history who need biographical information, teachers and khateebs who need material for lectures and sermons about the companions, and parents who want to share these stories with their children as part of their Islamic education. The Ashra Mubashra are often mentioned in Friday sermons and Islamic lectures, and having a dedicated book that collects their most inspiring stories in one volume is a valuable resource for anyone who wants to deepen their understanding of the first generation of Muslims. The book reinforces the Islamic principle that the companions of the Prophet are the best generation of this Ummah and that studying their lives is a means of increasing one's faith and following the Prophetic guidance to love and respect them.`,
    metaDescription: "Ashra Mubashra ki Zindagiyon ke Sunehre Waqiaat collects inspiring incidents from the ten companions promised Paradise. Engaging Urdu narratives."
  },
  {
    slug: "ashra-zil-hajja-eid-ul-adha-aur-qurbani",
    description: `Ashra Zil Hajja - Eid ul Adha aur Qurbani is an Urdu-language Islamic guide that provides comprehensive information about the first ten days of the Islamic month of Dhul Hijjah, the festival of Eid ul Adha, and the ritual of Qurbani (animal sacrifice). The title encompasses three interconnected subjects that are of central importance to Muslims during the Hajj season. The first ten days of Dhul Hijjah are considered among the most sacred days in the Islamic calendar — the Prophet Muhammad (peace be upon him) described them as the best days on which righteous deeds are most beloved to Allah. This book covers the virtues, recommended acts of worship, and specific rulings related to each of these three subjects in a single, organized volume.

The section on the Ashra Zil Hajja (the first ten days of Dhul Hijjah) details the special merits of these days as established in Quranic verses and authentic hadith, including the Prophet's statement that no days are more beloved to Allah for good deeds than these ten. The book lists and explains the recommended acts of worship during this period: fasting (particularly on the Day of Arafah for non-pilgrims), increased remembrance of Allah (dhikr and takbir), recitation of the Quran, charity, and voluntary prayers. The section provides the specific wordings for the takbirat that are recited after every obligatory prayer during these days, following the practice established by the companions and the early scholars.

The section on Eid ul Adha covers the rulings related to the Eid prayer — its timing, the method of performance, the khutbah (sermon), and the etiquettes of the Eid day. It addresses common questions about the Eid prayer, including its obligation status, whether women and children should attend, and the proper manner of traveling to and from the prayer venue. The Qurbani section provides detailed guidance on the obligation of sacrifice, including who is required to perform it, which animals are permissible, the minimum age and quality requirements for the sacrificial animal, the proper method of slaughter according to Islamic guidelines, how the meat should be distributed, and common mistakes to avoid. The book also addresses contemporary questions about Qurbani, such as the ruling on paying for Qurbani through organizations that perform it on one's behalf in other countries. Written in clear, instructional Urdu with references to Quran, hadith, and fiqh sources, this book is a practical guide that families consult annually as the Hajj season approaches. It is widely distributed in mosques and Islamic centers before Dhul Hijjah each year, and many families keep a copy at home as a permanent reference for their annual Qurbani preparation.`,
    metaDescription: "Ashra Zil Hajja - Eid ul Adha aur Qurbani is a complete Urdu guide to Dhul Hijjah, Eid prayer, and sacrifice rulings. Practical annual reference."
  },
  {
    slug: "asmad-surma-large",
    description: `Asmad Surma (Large) is a generous-sized container of traditional surma (kohl or kajal) produced under the Asmad brand, which is recognized in Pakistan and the wider South Asian market for its quality herbal and mineral-based eye care products. Surma has been used across the Muslim world for centuries as both a cosmetic product and a traditional eye remedy, with its use rooted in the prophetic tradition — Prophet Muhammad (peace be upon him) specifically recommended the use of surma (ithmid) for eye health. This large-size variant provides a substantial quantity of surma, making it a practical choice for regular users who prefer to purchase in larger, more economical sizes rather than frequently replacing smaller containers.

The Asmad Surma is formulated using traditional ingredients that have been used in Unani medicine and South Asian eye care practices for generations. The primary ingredient is typically ithmid (stibnite or antimony sulfide), which is the specific type of surma that the Prophet recommended, though some variants may include additional herbal components known for their cooling and soothing properties. The surma is finely ground to a smooth, powder-like consistency that can be easily applied to the inner rim of the eyelids using a thin applicator stick (salai), which is typically included with the packaging. The large container is designed with a secure lid that prevents the powder from spilling and keeps it protected from moisture and contamination, extending the product's shelf life significantly.

The large size of this Asmad Surma container makes it particularly suitable for household use where multiple family members share the same surma, as well as for individuals who use surma daily and prefer the convenience and value of a larger quantity. The container itself is typically made from a sturdy plastic or metal material with a tight-fitting cap, and its larger dimensions make it easier to handle and apply compared to the smaller pocket-sized surma tubes that are also available in the market. In Pakistani and South Asian culture, applying surma is a daily grooming practice for many people, and it is also commonly applied to newborns and young children as part of traditional child care. The Asmad brand has built a reputation for producing surma that is free from harmful additives and manufactured under quality-controlled conditions. Regular users of this product appreciate its smooth application, long-lasting dark color, and the cooling sensation it provides to the eyes. The large container size offers better value per gram compared to smaller variants and reduces the frequency of repurchasing, making it a practical staple item in many Muslim households.`,
    metaDescription: "Asmad Surma Large is a generous-sized traditional kohl container by the Asmad brand. Quality ithmid surma for daily eye care and cosmetic use."
  },
  {
    slug: "asr-se-maghrib-tak",
    description: `Asr Se Maghrib Tak is an Urdu-language Islamic book that focuses on the time period between the Asr (afternoon) and Maghrib (sunset) prayers — a window of time that holds particular spiritual significance in Islamic teachings. This period is associated with special opportunities for worship, supplication, and spiritual reflection, as it falls at the end of the day when a person can look back on their deeds and turn to Allah in repentance and gratitude before the day concludes. The book explores the various religious, spiritual, and practical dimensions of this time period, providing readers with guidance on how to make the most of these precious moments.

The book draws upon Quranic verses and authentic hadith to establish the significance of the Asr-to-Maghrib period. It references the Prophet's practice of making specific supplications during this time, the recommendation to wait in the mosque for the Maghrib prayer after having performed the Asr prayer (a practice known as "awaiting the prayer"), and the virtues of engaging in remembrance of Allah (dhikr), recitation of the Quran, and voluntary acts of worship during these hours. The book may also address the spiritual practice of istighfar (seeking forgiveness) during this time, as scholars have noted that the time between Asr and Maghrib is one of the times when supplications are particularly likely to be accepted.

Written in clear and accessible Urdu, Asr Se Maghrib Tak serves multiple purposes. For individuals looking to develop a more structured daily worship routine, it provides practical guidance on what acts of worship are most meritorious during this specific time window. For those interested in the spiritual life, it explores the deeper significance of transitional moments in the daily cycle and how Islam provides specific guidance for each phase of the day. The book may include sections on specific supplications (duas) recommended for this time, the etiquette of waiting for prayer in the mosque, the practice of reciting certain surahs or adhkar during this period, and the spiritual benefits of maintaining awareness of Allah as the day comes to a close. Teachers and imams may use this book as source material for talks and sermons about time management from an Islamic perspective and the importance of not letting the precious moments between prayers go to waste. The book reinforces the Islamic teaching that a Muslim's day should be punctuated by prayer and remembrance of Allah, with each period between prayers offering unique opportunities for spiritual growth and connection with the Creator.`,
    metaDescription: "Asr Se Maghrib Tak is an Urdu guide to the spiritual significance of the time between afternoon and sunset prayers. Daily worship and dhikr guidance."
  },
  {
    slug: "assalato-wassalam-ala-rasool-allah",
    description: `Assalato Wassalam Ala Rasool Allah is an Urdu-language book dedicated to the topic of sending blessings and salutations upon Prophet Muhammad (peace be upon him) — a practice known as salat ala an-Nabi or durud shareef. The title itself is a form of this very practice, translating to "Prayers and peace be upon the Messenger of Allah." The book provides a comprehensive treatment of the importance, virtues, and various forms of sending blessings upon the Prophet, drawing upon Quranic injunctions, authentic hadith, and the scholarly consensus of the Islamic tradition. This subject holds a central place in Muslim daily life, as sending salutations upon the Prophet is incorporated into the five daily prayers and is recommended at virtually every occasion in a Muslim's spiritual routine.

The book begins by establishing the Quranic basis for sending blessings upon the Prophet, primarily referencing the verse in Surah Al-Ahzab where Allah instructs the believers to send salat upon the Prophet just as Allah and His angels do, and promises that doing so brings Allah's mercy and blessings upon the sender tenfold. The hadith-based section documents the numerous statements of the Prophet about the virtues of this practice, including his declaration that whoever sends one blessing upon him will receive ten blessings from Allah, that the closest person to him on the Day of Judgment will be the one who sent the most blessings upon him, and that sending blessings is a means of having one's minor sins forgiven. The book then presents a curated collection of specific durood and salawat formulas that have been transmitted through authentic chains of narration, including the well-known durood Ibrahim that is recited in every sitting of the prayer, as well as less commonly known formulations that were taught by the Prophet or practiced by the companions and the early generations of Muslims.

The Urdu text explains each formulation with its full text, transliteration where helpful, the source from which it is derived, any special virtues or benefits associated with that particular wording, and the recommended occasions for its recitation. The book may also address scholarly discussions about the nature of salat ala an-Nabi — what exactly it means when Allah "sends salat" upon the Prophet versus what it means when the believers do so — drawing upon the explanations of classical scholars like Ibn al-Qayyim, Al-Qurtubi, and others. Written in scholarly yet accessible Urdu, this book serves as both a reference work and a devotional guide. It is used by individuals who want to increase their practice of sending blessings upon the Prophet, by teachers who want to educate their students about this important obligation, by imams preparing Friday sermons on the topic, and by study circles that focus on developing a deeper love and connection with the Messenger of Allah through the practice of salawat.`,
    metaDescription: "Assalato Wassalam Ala Rasool Allah is an Urdu guide to sending blessings on the Prophet. Quranic virtues, durood formulas, and scholarly insights."
  }
];

async function main() {
  let count = 0;
  let fails = [];
  for (const item of updates) {
    try {
      await prisma.product.update({
        where: { slug: item.slug },
        data: {
          description: item.description,
          metaDescription: item.metaDescription
        }
      });
      count++;
      console.log('OK:', item.slug);
    } catch (e) {
      console.log('SKIP:', item.slug, e.message.substring(0, 80));
      fails.push(item.slug);
    }
  }
  console.log(`\nUpdated: ${count}/${updates.length}`);
  if (fails.length) console.log('Failed:', fails.join(', '));
}

main().then(() => prisma.$disconnect()).catch(e => { console.error(e); prisma.$disconnect(); });
