const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "qisasul-ambiya-farsi",
    description: `Qisasul Ambiya in Farsi is a detailed retelling of the stories of the prophets as narrated in the Quran and authenticated hadith, presented in the Persian language for readers who are most comfortable reading in Farsi. The work traces the lives of the major prophets from Adam, peace be upon him, through the final messenger Muhammad, peace be upon him, covering each prophet's mission, the challenges they faced from their communities, the miracles Allah bestowed upon them, and the lessons their stories hold for believers across all generations. The Farsi rendering makes this collection particularly valuable for Persian-speaking communities in Iran, Afghanistan, Tajikistan, and the global diaspora who wish to pass down the prophetic narratives to their families in a language that resonates with their cultural and linguistic heritage. Each prophet's account is presented with careful attention to the Quranic source material, cross-referencing verses from multiple surahs to construct a complete and coherent narrative. The stories of Nuh and the great flood, Ibrahim and his trials including the breaking of the idols and the sacrifice of his son, Musa and his confrontation with Pharaoh, Isa and his miraculous birth and ministry, and Muhammad and his complete mission from Makkan persecution to Madinan establishment are all treated with scholarly diligence and narrative skill. The book also covers the stories of prophets whose narratives receive less extensive treatment in popular literature, including Hud, Salih, Lut, Shuayb, Ayyub, Yunus, Zakariyya, and Yahya, ensuring that readers gain a comprehensive understanding of the prophetic tradition in Islam. The Farsi prose style is literary yet accessible, making the book suitable for both adults and younger readers who have developed sufficient reading proficiency. Each chapter concludes with a reflection section that draws out the moral and spiritual lessons of the prophet's story, connecting the ancient narratives to the lived experience of contemporary Muslims. This edition is an important resource for Persian-speaking Muslim households, Islamic schools that use Farsi as a medium of instruction, and community libraries serving Farsi-speaking populations. It preserves the richness of the Quranic prophetic narratives while making them accessible in one of the world's great Islamic literary languages.`,
    metaDescription: "Qisasul Ambiya in Farsi retells the stories of the prophets from the Quran in Persian, covering each prophet's mission, miracles, and spiritual lessons."
  },
  {
    slug: "qiyam-ul-layl",
    description: `Qiyam ul Layl is a focused study of the Islamic practice of night prayer, commonly known as Tahajjud, that examines this act of worship from its foundational texts through its practical implementation and its profound spiritual benefits. The title itself means standing in prayer during the night, and the book systematically unpacks every dimension of this practice that has been cherished by the righteous throughout Islamic history. The author begins by establishing the Quranic basis for night prayer, citing verses from Surah al-Isra, Surah as-Sajdah, Surah az-Zumar, and Surah al-Muzzammil that directly address the obligation and merit of waking for prayer during the hours of darkness. These verses are analysed in their historical context, explaining when and why they were revealed and how the early Muslim community understood and implemented them. The book then turns to the extensive hadith literature on night prayer, documenting the Prophet Muhammad's own practice of Tahajjud, the specific supplications he recited during his night vigils, the different formats of night prayer he performed, and his encouragement of his companions to adopt this practice. A significant portion of the book is devoted to the practical methodology of Qiyam ul Layl, covering the optimal timing for night prayer, the recommended number of rakat, the surahs that the Prophet preferred to recite during Tahajjud, the manner of performing the prayer including the long bowings and prostrations that characterise this devotion, and the supplications of Witr that traditionally conclude the night prayer. The spiritual benefits section discusses how night prayer serves as a means of drawing closer to Allah, expiating sins, developing patience and steadfastness, cultivating sincerity, and preparing the soul for the challenges of the coming day. The book also addresses common obstacles that prevent people from establishing a regular night prayer routine, including physical tiredness, sleep inertia, and the demands of work and family life, offering practical strategies for overcoming these barriers based on the advice of classical scholars. The treatment draws upon the works of major Islamic scholars including Ibn al-Qayyim, Imam al-Ghazali, and Ibn Rajab al-Hanbali, whose writings on night prayer represent some of the most spiritually penetrating works in the Islamic literary tradition. This book is recommended for anyone who wishes to develop a deeper prayer life and experience the spiritual richness that the hours before dawn offer to the believing soul.`,
    metaDescription: "Qiyam ul Layl is a comprehensive study of the Islamic night prayer or Tahajjud, covering its Quranic basis, methodology, and spiritual benefits."
  },
  {
    slug: "qiyamat",
    description: `Qiyamat is an Urdu-language book that presents a detailed and authoritative account of the Day of Judgment as described in the Quran and the authentic hadith of the Prophet Muhammad, peace be upon him. The word Qiyamat itself refers to the Resurrection, the climactic event in Islamic eschatology when all of creation will be brought to an end and every human being who has ever lived will be raised from the dead to stand before Allah for final judgment. The author has compiled the Quranic descriptions of the events of the Last Day from across numerous surahs, weaving them into a chronological narrative that takes the reader from the first signs of the approaching Hour through the blowing of the trumpet, the physical destruction of the universe, the resurrection of the dead, the gathering of all creation on the Plain of Judgment, the presentation of each person's book of deeds, the weighing of deeds on the scales, the crossing of the bridge over Hell, and ultimately the entry of the righteous into Paradise and the consignment of the disobedient to their fate. The hadith material in the book provides additional details about the events of Qiyamat that supplement the Quranic descriptions, including the Prophet's accounts of what he witnessed during his night journey through the heavens, his descriptions of the physical appearance of Paradise and Hell, and his explanations of the specific questions that will be asked of each person in the grave and on the Day of Judgment. The book addresses common questions about the Day of Judgment, including the nature of intercession, the role of the Prophet Muhammad as a witness on that day, the fate of children who die before reaching the age of accountability, and the destiny of members of other religious communities. The Urdu prose is clear and descriptive, conveying the immense scale and solemnity of the events being described while maintaining a tone that motivates spiritual reflection rather than mere fear. A concluding section emphasises the practical implications of believing in Qiyamat, explaining how consciousness of the Day of Judgment should influence a person's daily conduct, their priorities in life, and their relationship with Allah. This book serves as both a scholarly reference on Islamic eschatology and a powerful reminder of the accountability that awaits every soul.`,
    metaDescription: "Qiyamat is an Urdu book detailing the Day of Judgment from Quran and hadith, covering resurrection, judgment, and the events of the Last Day."
  },
  {
    slug: "qiyamat-ka-bayan",
    description: `Qiyamat Ka Bayan is a distinct Urdu work on the subject of the Day of Judgment that approaches the topic through an explanatory and analytical framework, providing readers with a reasoned and thoroughly sourced account of what Islamic scripture teaches about the end of the world and the afterlife. The title translates to The Explanation of the Day of Judgment, signalling the author's intention to clarify and elucidate the sometimes complex and overwhelming descriptions found in the primary sources rather than merely collecting and presenting them. Where the standard approach to this topic tends to focus on the dramatic events of the Last Day in a largely chronological fashion, this book organises its material thematically, grouping related concepts together and building the reader's understanding incrementally from foundational principles to detailed descriptions. The book begins with the theological foundations of belief in the Hereafter, explaining why the Day of Judgment is a necessary component of Islamic theology and how it relates to other articles of faith including belief in Allah, His angels, His books, and His messengers. It then proceeds to examine the minor and major signs of the approaching Hour, devoting individual chapters to each category of signs and assessing their authenticity based on the grading of hadith scholars. The section on the events of Qiyamat itself is organised into stages: the death and decomposition of the physical body, the questioning in the grave, the blowing of the trumpet and the physical resurrection, the gathering for judgment, the intercession process, and the final dispatch to Paradise or Hell. A unique feature of this book is its comparative approach, noting where descriptions in the Quran and hadith complement each other and addressing apparent discrepancies with scholarly methodology. The book also includes a section on contemporary misconceptions about Qiyamat, responding to questions that arise in modern contexts about the scientific plausibility of resurrection, the fairness of being judged for deeds committed under circumstances beyond one's control, and the relationship between divine foreknowledge and human free will in the context of final judgment. The Urdu writing style is analytical yet accessible, making complex theological concepts understandable without oversimplifying them. This book is suited for readers who prefer a structured, reasoned approach to Islamic eschatology and for teachers and students of Islamic studies who need a well-organised reference work on the subject.`,
    metaDescription: "Qiyamat Ka Bayan is an Urdu book that explains the Day of Judgment thematically, covering signs of the Hour, resurrection, and theological foundations."
  },
  {
    slug: "questions-answers-on-biography-of-muhammad-part-i",
    description: `Questions and Answers on Biography of Muhammad Part I presents the life of the Prophet Muhammad, peace be upon him, in an accessible question-and-answer format that makes the study of Seerah engaging and straightforward for readers of all backgrounds and age groups. This first volume covers the foundational period of the Prophet's life, beginning with the background and history of the Arabs before Islam, the lineage and ancestry of the Prophet, the circumstances surrounding his birth, his childhood and upbringing, his youth and early character traits, and the events leading up to the first revelation. The Q&A format serves a distinct pedagogical purpose, allowing readers to absorb information in digestible portions and to test their understanding as they progress through the material. Each question addresses a specific aspect of the Prophet's life that readers commonly want to know about, ranging from factual inquiries about dates, names, and places to more analytical questions about the significance of certain events and the lessons they contain. The answers are drawn from authentic sources including the major Seerah works of Ibn Ishaq, Ibn Hisham, al-Waqidi, and later scholars, with careful attention to the authentication of hadith sources and the reconciliation of any conflicting reports. Topics covered in this first volume include the story of the Prophet's father Abdullah and his journey to Madinah, the death of his mother Aminah, his upbringing under his grandfather Abdul Muttalib and then his uncle Abu Talib, his participation in the resolution of the dispute over the placing of the Black Stone in the Kaabah, his marriage to Khadijah, his spiritual retreats to the Cave of Hira, the first revelation through the angel Jibreel, and the beginning of his mission to call people to Islam. The book also covers the early converts to Islam, the persecution faced by the Muslims in Makkah, and the migration of some Muslims to Abyssinia. Each answer is supported by references to original sources, allowing interested readers to pursue further study. This volume is particularly useful for students preparing for Islamic studies examinations, teachers developing lesson plans for Seerah classes, new Muslims learning about the Prophet's life for the first time, and anyone who appreciates the clarity and efficiency of the Q&A format for absorbing detailed historical and biographical information.`,
    metaDescription: "Questions & Answers on Biography of Muhammad Part I covers the Prophet's early life from birth through the first revelation in an engaging Q&A format."
  },
  {
    slug: "questions-answers-on-the-biography-of-muhammad-pbuh-2-vol",
    description: `Questions and Answers on the Biography of Muhammad, peace be upon him, in its complete two-volume set provides a comprehensive Q&A treatment of the entire Seerah from the pre-Islamic period through the Prophet's death and its immediate aftermath. The decision to present the Seerah in two volumes allows for a much more detailed and thorough coverage than a single volume could provide, with each major phase of the Prophet's life receiving the attention it deserves rather than being condensed for the sake of brevity. The two-volume structure also reflects the natural division of the Seerah into the Makkan and Madinan periods, with each volume addressing the unique characteristics, challenges, and developments of its respective era while maintaining the narrative thread that connects the Prophet's life into a coherent whole. The question-and-answer format that structures both volumes is particularly effective for a work of this scope, as it allows readers to navigate the extensive material by topic and to focus on the specific aspects of the Seerah that are most relevant to their interests or needs. The questions range across a broad spectrum, from basic factual inquiries about names, dates, locations, and chronology to more nuanced analytical questions about the Prophet's decision-making processes, the reasoning behind specific strategies and treaties, the dynamics of his relationships with various individuals and groups, and the legal and social reforms he implemented. The answers draw upon the full range of Seerah sources including classical works by Ibn Ishaq, Ibn Hisham, al-Tabari, and Ibn Kathir, as well as contemporary scholarly analyses that provide additional context and interpretation. The two-volume set covers topics including the complete timeline of revelations and their circumstances, the detailed accounts of all major battles including Badr, Uhud, and the Trench, the Treaty of Hudaybiyyah and its significance, the conquest of Makkah, the Farewell Pilgrimage, the Prophet's final illness and passing, and the immediate succession crisis that followed his death. Each answer includes source references for verification and further study. This two-volume set is an excellent resource for Islamic schools, Seerah study circles, mosque libraries, and individual readers who want a thorough and well-organised reference work on the Prophet's complete life that combines scholarly reliability with accessible presentation.`,
    metaDescription: "This 2-volume Q&A set on the Prophet Muhammad's biography covers the complete Seerah from Makkan period through Madinan era in thorough detail."
  },
  {
    slug: "questions-answers-on-the-mothers-of-the-believers",
    description: `Questions and Answers on the Mothers of the Believers is a dedicated study of the wives of the Prophet Muhammad, peace be upon him, presented in the familiar and accessible question-and-answer format that allows readers to learn about these remarkable women in a structured and engaging manner. The title Mothers of the Believers is the honorific title given to the Prophet's wives in the Quran itself, reflecting their elevated status in the Muslim community and the respect that all Muslims are obligated to show them. The book covers each of the Prophet's wives individually, providing detailed information about their backgrounds, their families of origin, the circumstances of their marriages to the Prophet, their contributions to Islamic society, their characters and personalities, and their lives after the Prophet's passing. The Q&A format ensures that a wide range of questions is addressed, from basic biographical facts such as the names and tribal affiliations of each wife to more nuanced inquiries about their roles in preserving and transmitting hadith, their involvement in political and social affairs of the early Muslim community, and the specific Quranic verses that were revealed in connection with events in their lives. The book gives detailed attention to Khadijah bint Khuwaylid, the Prophet's first wife and the first person to believe in his mission, whose support during the most difficult early years of Islam was indispensable. Aisha bint Abu Bakr receives extensive coverage as the wife who narrated the largest number of hadith and who played a significant role in the political life of the Muslim community after the Prophet's death. Hafsa bint Umar is discussed in relation to her role as the custodian of the first written compilation of the Quran. Umm Salamah, Sawdah, Zaynab bint Jahsh, Juwayriyyah, Umm Habibah, Safiyyah, Maymunah, and Rayhanah are each treated with the respect and scholarly diligence their positions deserve. The book addresses questions about the wisdom behind the Prophet's multiple marriages, the allegations that critics of Islam raise regarding these marriages, and the actual historical circumstances that explain each union. The writing style is informative and respectful throughout, providing readers with a balanced and authentic understanding of these women who played such central roles in Islamic history. This book is recommended for anyone interested in women's history in Islam, students of Seerah, and readers who wish to develop a deeper appreciation for the Mothers of the Believers.`,
    metaDescription: "This Q&A book on the Mothers of the Believers covers each of the Prophet's wives, their backgrounds, contributions, and roles in Islamic history."
  },
  {
    slug: "questions-answers-on-the-rightly-guided-caliphs",
    description: `Questions and Answers on the Rightly Guided Caliphs provides a comprehensive study of the four caliphs who succeeded the Prophet Muhammad, peace be upon him, as leaders of the Muslim community: Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, and Ali ibn Abi Talib. Known collectively as the Khulafa-e-Rashidun or the Rightly Guided Caliphs, these four men governed the rapidly expanding Muslim community during a period of approximately thirty years that set the precedents and established the principles of Islamic governance for all subsequent generations. The Q&A format makes this complex historical period accessible by breaking it down into specific questions that address the most important aspects of each caliph's life, character, and administration. For Abu Bakr, the book covers his close companionship with the Prophet, his role in the early Muslim community, his swift response to the apostasy wars that threatened to fragment the Islamic state after the Prophet's death, and his initiation of the project to compile the Quran into a single written volume. For Umar, the questions address his extraordinary personality and piety, his sweeping administrative reforms, his establishment of the Islamic calendar, his expansion of the Muslim territories, and his assassination. For Uthman, the book covers his role in standardising the written text of the Quran, his management of the expanding Islamic empire, the grievances that led to the fitnah or civil strife during his caliphate, and his martyrdom. For Ali, the questions explore his deep knowledge of Islam, his role as the Prophet's cousin and son-in-law, the challenges he faced during his caliphate including the battles of the Camel and Siffin, and his legacy in both Sunni and Shia traditions. The book also addresses questions about the order of succession, the method of selecting the caliphs, the concept of the rightly guided caliphate as a model for Islamic governance, and the differences between the governance of the Rashidun period and later caliphal dynasties. Each answer is sourced from authentic historical works including the histories of al-Tabari, the writings of Ibn Kathir, and the hadith collections. This book is an essential resource for students of Islamic history and anyone seeking to understand the foundational period of Islamic civilisation.`,
    metaDescription: "This Q&A book on the Rightly Guided Caliphs covers Abu Bakr, Umar, Uthman, and Ali in detail, their governance, reforms, and contributions to Islam."
  },
  {
    slug: "questions-and-answers-of-islam-part-2",
    description: `Questions and Answers of Islam Part 2 is the second instalment of a broader Islamic knowledge series that continues the systematic presentation of Islamic teachings in the proven question-and-answer format that characterises the collection. This second volume builds upon the foundational material covered in Part 1, advancing to more complex topics and addressing the questions that naturally arise as a person's understanding of Islam deepens. The book covers a wide range of subjects including advanced matters of Aqidah or creed, detailed rulings of Islamic jurisprudence or fiqh, the history of Islamic civilisation and its major scholarly figures, explanations of Quranic verses that require contextual understanding, clarifications of hadith that may seem difficult to interpret without proper knowledge, and responses to common misconceptions about Islam that Muslims encounter in their interactions with people of other faiths. The fiqh section of this volume addresses practical matters of worship and daily life that were not covered in the first part, including detailed discussions of the conditions and pillars of various acts of worship, the rulings related to financial transactions and business ethics, the Islamic perspective on contemporary social issues, and the principles of Islamic ethics that govern interpersonal relationships. The Aqidah section expands on the articles of faith, providing more detailed explanations of concepts such as divine predestination and human free will, the nature of Allah's attributes, the status of the companions of the Prophet, and the distinction between minor and major sins. Each question is answered with reference to the primary sources of Islam, namely the Quran and the authenticated hadith, supplemented by the interpretations of classical scholars and the consensus positions of the major schools of Islamic jurisprudence. The answers are written in clear language that avoids unnecessary technical jargon while maintaining scholarly accuracy, making the book accessible to readers who do not have formal training in Islamic studies. The Q&A format allows readers to use the book both as a sequential study text and as a quick reference for specific questions that may arise in their daily lives. This volume is particularly useful for students in Islamic educational institutions, converts to Islam who have completed basic introductory study, parents who want to answer their children's questions about Islamic teachings, and anyone committed to deepening their understanding of the faith beyond the fundamentals.`,
    metaDescription: "Questions and Answers of Islam Part 2 advances Islamic knowledge with detailed Q&A on fiqh, creed, Quranic interpretation, and contemporary issues."
  },
  {
    slug: "quran-17a-qk",
    description: `This Quran edition identified by the code 17A QK is a complete physical copy of the Holy Quran in the standard 15-line Hafs narration format that is widely used across South Asian and Middle Eastern Muslim communities. The 15-line per-page format has become one of the most recognisable and practical layouts for Quran publication, as it distributes the text across 604 pages in a manner that balances readability with portability, making it suitable for both regular reading and memorisation purposes. The Hafs an Asim narration, which is the most commonly recited qiraat or reading mode throughout the Muslim world, is the text used in this edition, ensuring that readers can use this copy for prayer recitation, memorisation revision, and teaching without any concern about variations in the recitation text. The publication quality of this edition reflects careful attention to the standards that govern Quran printing in Muslim communities: the text is printed with precision to avoid any errors in the sacred words, the script is clear and properly vowelled to facilitate correct pronunciation, the page layout follows the traditional 15-line arrangement that allows experienced readers to locate any passage quickly based on their memorisation of page positions, and the binding is designed to withstand regular use over an extended period. This edition includes the standard appendices found in South Asian Quran publications, including colour-coded tajweed markers that help readers apply the rules of proper Quranic recitation, indicators for the end of each juz or thirtieth portion, markers for the sajdah or prostration verses, and a quick reference guide to the surah names and their locations. The physical dimensions of this edition make it a practical choice for daily use, fitting comfortably on a bookshelf, a bedside table, or in a bag for travel to the mosque or elsewhere. The cover design is dignified and respectful, befitting the sacred nature of the text. This Quran copy is suitable for personal use, for placement in mosques and Islamic centres, and as a gift for occasions such as weddings, graduations, Ramadan, and Hajj. It serves the needs of both experienced Quran readers who require a reliable daily copy and newer Muslims who are building their first collection of Islamic texts.`,
    metaDescription: "This Quran 17A QK edition features the complete 15-line Hafs text with tajweed markers, suitable for daily reading, memorisation, and prayer."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
