const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "qurani-aur-islami-naamon-ki-dictionary",
    description: `Qurani Aur Islami Naamon Ki Dictionary is an Urdu-language reference work that serves as a comprehensive dictionary of Quranic and Islamic names and terminology, providing clear definitions, contextual explanations, and relevant details for hundreds of terms that Muslims encounter in their religious study and daily practice. The need for such a specialised dictionary arises from the fact that Islamic discourse, whether conducted in Urdu, Arabic, or English, is rich with technical terms, proper nouns, and phrases whose meanings are not immediately apparent to readers who have not received formal Islamic education. Many Muslims who read the Quran in Urdu translation, listen to Friday sermons, or study Islamic books encounter terms that they either partially understand or find completely unfamiliar, and the absence of a dedicated reference tool to look up these terms can impede their understanding and spiritual growth. This dictionary fills that gap by providing accessible definitions for the complete range of Islamic terminology. The entries include the names of all prophets mentioned in the Quran with their meanings and relevant background, the names of angels and their roles, the names of surahs with explanations of why each surah bears its particular name, the names of companions of the Prophet with brief biographical notes, key Islamic concepts such as Tawheed, Risalah, Akhirah, and their various dimensions, fiqh terminology related to prayer, fasting, charity, pilgrimage, and other acts of worship, theological terms that appear in discussions of creed and belief, and the names and attributes of Allah with explanations of their significance. Each entry provides the term in its original Arabic form alongside its Urdu rendering, the literal meaning of the word or name, and an explanation of its significance within the Islamic context. Where a term has multiple meanings or applications, these are distinguished clearly. The dictionary also includes cross-references that direct readers to related entries, enabling a deeper exploration of interconnected concepts. The compilation draws upon classical Arabic lexicons, tafsir works, hadith collections, and fiqh manuals to ensure that each definition is accurate and grounded in authentic Islamic scholarship. The Urdu language used in the definitions is clear and straightforward, avoiding the overly complex diction that can make some reference works inaccessible to general readers. This dictionary is an essential reference for students of Islamic studies at all levels, for parents who want to answer their children's questions about Islamic terms, for teachers preparing lessons, and for any Muslim who wishes to develop a more precise and informed understanding of the vocabulary of their faith.`,
    metaDescription: "This Urdu dictionary of Quranic and Islamic terminology provides clear definitions for hundreds of names, concepts, and terms used in Islamic texts."
  },
  {
    slug: "qurani-duaien-aur-wazaif-hard-cover",
    description: `Qurani Duaien Aur Wazaif in its hard cover edition is a substantial Urdu-language compilation of supplications drawn directly from the Quran along with prescribed spiritual practices and wazaif that Muslims can incorporate into their daily routines for spiritual benefit and divine blessing. The hard cover binding makes this edition particularly durable and suitable for long-term use, as the rigid cover protects the pages from damage even with frequent handling and the sturdy spine resists the cracking that softer bindings can develop over time. This format is especially valued by readers who consult their dua books daily, as the hard cover allows the book to stand upright on a shelf for easy access and provides a stable surface when the book is opened for reading during supplication. The book organises the Quranic supplications into logical categories that correspond to the different needs and situations that a Muslim encounters in life. Chapters are devoted to duas for morning and evening, duas for before and after eating, duas for entering and leaving the home, duas for travelling, duas for seeking forgiveness, duas for protection from harm, duas for health and healing, duas for financial well-being, duas for family matters including marriage and children, duas for success in this world and the hereafter, and many other categories that cover virtually every aspect of human experience. Each dua is presented with its complete Arabic text, its Urdu translation, and a transliteration where helpful, along with a reference to the specific Quranic verse from which it is taken. The wazaif section provides structured spiritual routines that combine specific Quranic verses, surahs, or phrases with recommended times and frequencies for their recitation. These wazaif are drawn from the practices of the righteous predecessors and authenticated scholars, providing readers with a framework for consistent spiritual engagement without resorting to the innovated or questionable practices that unfortunately circulate in some communities. The book includes guidance on the conditions and etiquette of making dua, the best times for supplication to be accepted, the importance of sincerity and persistence in dua, and the relationship between dua and righteous action. The Urdu commentary is thorough yet accessible, making this compilation suitable for both scholars and general readers. This hard cover edition is designed to be a lasting household reference, a book that will remain in use for years and may even be passed down through generations as a family's standard dua collection.`,
    metaDescription: "This hard cover Urdu book compiles Quranic duas and authenticated wazaif for daily spiritual practice, organised by life situation and need."
  },
  {
    slug: "qurani-duayen-aur-wazaif-soft-cover",
    description: `Qurani Duayen aur Wazaif in its soft cover edition presents the same comprehensive collection of Quranic supplications and spiritual practices as the hard cover version but in a lighter, more flexible binding that offers its own distinct advantages for certain types of use. The soft cover format makes this book noticeably lighter in weight and easier to carry, which is particularly valuable for readers who want to keep their dua collection with them throughout the day, whether in a bag, a car, or a desk drawer at work. Many Muslims prefer to have access to their dua book during the commute, at the office during lunch break prayers, or while travelling, and the soft cover's portability makes this possible without the bulk of a hardbound volume. The content of this edition is identical to the hard cover version in its comprehensiveness and organisational structure, covering the full range of Quranic duas organised by their relevance to different life situations and the complete wazaif section with its prescribed spiritual routines. The Arabic text of each dua is presented clearly with proper diacritical marks, accompanied by Urdu translation and references to the source verses in the Quran. The soft cover edition is also more affordable than the hard cover version, making it accessible to a wider range of readers and allowing families, Islamic schools, and organisations to acquire multiple copies for distribution. This edition is particularly well suited for personal daily use, for placement on a prayer mat or bedside table where a slimmer book is more convenient than a bulkier hardbound copy, and for inclusion in gift packages where the combination of comprehensive content with a more modest price point allows the giver to reach more recipients. The binding of this soft cover edition has been manufactured to a standard that, while not as rigid as hard cover, still provides adequate durability for regular use, with reinforced stitching that prevents pages from pulling loose during the frequent opening and closing that a daily dua book typically endures. For readers who alternate between a home reference copy and a portable copy, the soft cover edition serves as the ideal travel companion. This book remains a valuable resource for anyone seeking to enrich their spiritual life through the authentic supplications preserved in the Quran and the structured spiritual practices recommended by the scholarly tradition.`,
    metaDescription: "This soft cover edition of Quranic duas and wazaif offers the same comprehensive content in a lighter portable format for daily spiritual use."
  },
  {
    slug: "qurani-masnoon-duain-al-huda-large",
    description: `Qurani Masnoon Duain Al Huda in the large format is a generously sized compilation of authentic supplications from the Quran and the established Sunnah of the Prophet Muhammad, peace be upon him, produced under the Al Huda imprint which is recognised for its commitment to authentic Islamic scholarship and accessible presentation. The large format distinguishes this edition from smaller dua collections by providing a reading experience that is particularly comfortable for extended use, with a larger font size for the Arabic text, wider margins that give the pages a spacious and uncluttered appearance, and sufficient space between individual duas to allow the reader to focus on one supplication at a time without visual distraction. This format is especially beneficial for elderly readers who may find smaller print difficult to read, for new Muslims who are still learning Arabic script and need the larger characters to distinguish between similar-looking letters, for teachers and leaders who use the book for group supplication and need text that is visible from a slight distance, and for individuals who prefer a more premium and luxurious presentation of their dua collection. The content covers the complete spectrum of masnoon or authentically reported supplications, including the daily azkar that the Prophet recommended for morning and evening, the duas for all acts of worship including prayer, fasting, charity, and pilgrimage, the supplications for specific occasions such as eating, drinking, sleeping, waking, travelling, wearing new clothes, and entering and leaving the home, the duas for seeking forgiveness, protection, guidance, and blessings, and the prophetic supplications for moments of difficulty, anxiety, grief, and illness. Each dua is presented with its Arabic text in a clear, well-spaced font, followed by the Urdu translation and, where appropriate, notes on the context in which the Prophet taught this dua or the specific benefits associated with its recitation. The Al Huda editorial team has verified each dua against the major hadith collections to ensure authenticity, and any dua whose chain of narration is weak or disputed is clearly marked as such, maintaining the scholarly integrity that distinguishes this compilation from less rigorous dua books on the market. This large format edition is a premium choice for home libraries, mosque bookshelves, and as a distinguished gift for weddings, housewarmings, and religious occasions where the presentation quality of the gift matches the importance of the content.`,
    metaDescription: "This large format Al Huda dua collection features authentic Quranic and Sunnah supplications in large print, ideal for home and mosque use."
  },
  {
    slug: "qurani-masnoon-duain-al-huda-small",
    description: `Qurani Masnoon Duain Al Huda in the small format is a compact and portable edition of the same authentically compiled collection of Quranic and prophetic supplications, designed for readers who need a dua reference that fits easily into their pocket, purse, or daily bag. The small format is the direct counterpart to the large edition in the same Al Huda series, containing the same comprehensive selection of masnoon supplications and maintaining the same standards of hadith authentication and scholarly accuracy, but presented in a reduced physical size that prioritises portability and convenience. The font size and page layout have been adjusted to suit the smaller dimensions while maintaining sufficient legibility for comfortable reading under normal conditions. The compact size makes this edition particularly suitable for a specific set of use cases that the larger format cannot serve as effectively: carrying the dua book during travel, keeping it at a workplace desk where space is limited, slipping it into a child's school bag so they have access to their daily azkar, using it as a personal reference during mosque prayers when a larger book would be conspicuous or inconvenient, and maintaining a copy in the car for dua during commutes. Despite its smaller size, this edition retains the complete organisational structure of the full collection, with supplications categorised by their purpose and occasion so that readers can quickly locate the appropriate dua for any situation. The Arabic text of each dua is properly vowelled and clearly printed, with the Urdu translation following each entry. The hadith references are included, though in a more condensed format to accommodate the reduced page size. The binding of the small edition is designed for durability in portable conditions, with a flexible yet protective cover that resists the bending, scratching, and general wear that a frequently carried book inevitably experiences. Many readers keep one copy of the large edition at home for leisurely study and reference, and a copy of this small edition with them during the day for quick consultation. This dual-format approach ensures that authentic masnoon supplications are always accessible regardless of the reader's location or circumstances. The small format also makes this edition a practical choice for bulk distribution at Islamic events, school enrolments, and community programmes where cost and portability are both important considerations.`,
    metaDescription: "This small format Al Huda dua book offers the same authentic supplications in a pocket-sized edition, perfect for travel and daily carry."
  },
  {
    slug: "qurani-qaidah-14x21",
    description: `Qurani Qaidah in the 14x21 size is a foundational Quran reading primer designed to teach beginners the Arabic alphabet, the rules of letter joining, vowel markings, and the basic pronunciation skills needed to begin reading the Quran. The 14x21 measurement refers to the dimensions of the book in centimetres, making this a compact and easily handled format that is well suited for young children whose smaller hands may struggle with larger, heavier textbooks, as well as for adult learners who prefer a lightweight primer that can be conveniently held and stored. The Noorani Qaidah methodology that this book follows is the most widely used system for teaching Quran reading in South Asian Muslim communities, and it has proven effective across generations of learners ranging from young children to elderly converts to Islam. The book begins with the individual letters of the Arabic alphabet, presenting each letter in its isolated form with its name and pronunciation clearly indicated. Subsequent lessons introduce the different forms that each letter takes depending on its position within a word: the initial, medial, final, and independent forms. The system then progresses to the short vowels or harakat, the long vowels, the sukun or absence of a vowel, the shaddah or doubled consonant, the tanween or double vowel marks, and the various other diacritical marks that are essential for correct Quranic pronunciation. Each lesson builds systematically upon the previous one, gradually increasing the complexity of the reading exercises from individual letters to syllables, then to individual words, then to short phrases, and finally to complete sentences and verses from the Quran. The exercises are designed to develop the learner's ability to recognise letter combinations quickly and to read connected text fluently, moving from the controlled environment of the primer to the actual text of the Quran with confidence. The 14x21 size is the smaller of the two standard sizes in which this Qaidah is published, and it is particularly popular for use in home schooling, private tutoring sessions, and for individual self-study where a smaller, more personal book is preferred. The pages are printed on paper that supports comfortable writing practice, allowing students to trace letters and complete exercises directly in the book. This Qaidah is the essential first step in any Quran learning journey, providing the foundation upon which all subsequent Quranic study and recitation depends.`,
    metaDescription: "This 14x21 cm Qurani Qaidah teaches Arabic alphabet and Quran reading basics in a compact format ideal for children and beginner learners."
  },
  {
    slug: "qurani-qaidah-17x24",
    description: `Qurani Qaidah in the 17x24 size is the larger standard format of the foundational Quran reading primer that follows the established Noorani Qaidah methodology for teaching Arabic script and basic Quran reading skills to beginners of all ages. The 17x24 centimetre dimensions make this a substantially larger book than the 14x21 edition, offering several practical advantages for certain teaching and learning contexts. The larger page size allows for a bigger font and more generous spacing between letters, words, and exercises, which is particularly beneficial in classroom settings where the teacher needs to hold up the book and have the text visible to a group of students, or where the book is being used for demonstration purposes from the front of a classroom or mosque study circle. The increased page area also provides more space for students to practice writing letters and words directly in the book, with ruled guidelines that help learners maintain consistent letter size and proper alignment. The content and pedagogical sequence of this 17x24 edition are identical to those of the smaller format: beginning with the individual Arabic letters and progressing systematically through letter forms, vowel markings, joined letters, syllables, words, and eventually Quranic verses. However, the larger format presents each lesson with greater visual clarity, using colour coding and visual separators that help organise the page and direct the learner's attention to the current exercise. This edition is particularly favoured in formal classroom settings including madrasahs, Islamic schools, and mosque Quran classes, where the larger format supports the teacher's instructional needs and provides a more durable and substantial textbook that can withstand the rigours of classroom use across multiple academic terms. The 17x24 format is also preferred by adult learners who appreciate the larger text size for easier reading, especially those whose eyesight may not be optimal for the smaller print of compact editions. Educational institutions that adopt this Qaidah for their Quran literacy programmes often standardise on the 17x24 size because it is easier to manage in a classroom inventory, easier for teachers to reference during instruction, and more durable in the hands of young children who may not handle books with the same care as older students. This primer remains the essential first step in the journey of Quran learning, and the 17x24 format ensures that this foundational material is presented in the most effective and accessible manner for classroom and institutional use.`,
    metaDescription: "This 17x24 cm Qurani Qaidah is the larger classroom format of the Quran reading primer, ideal for madrasahs, Islamic schools, and group teaching."
  },
  {
    slug: "qurani-wazaif",
    description: `Qurani Wazaif is a focused Urdu-language compilation that presents specific spiritual practices and prescribed recitations derived from the Quran for Muslims who seek to incorporate structured Quranic engagement into their daily spiritual routine. The book is dedicated exclusively to the wazaif dimension of Islamic spiritual practice, offering a curated collection of Quranic recitations that have been recommended by authentic scholars and pious predecessors for various spiritual and practical purposes. Each wazifa entry in the book provides the specific Quranic verse, surah, or phrase to be recited, along with detailed instructions regarding the recommended time for its recitation, the number of times it should be repeated, any specific conditions or preparations required before beginning the practice, and the intended spiritual benefit or purpose that the wazifa serves. The wazaif are organised by their purpose and occasion, with sections covering daily spiritual maintenance, wazaif for seeking forgiveness and expiation of sins, practices for developing closeness to Allah, recitations for protection from various forms of harm, practices for alleviating difficulties and hardships, wazaif related to financial matters and sustenance, spiritual practices for health and healing, and wazaif for family well-being including marital harmony, children's welfare, and parental blessings. A distinctive feature of this compilation is its careful attention to authenticity, clearly distinguishing between wazaif that are grounded in the Quran and established scholarly practice and those that circulate in popular culture but lack a sound basis in authentic Islamic sources. The book includes a substantial introductory section that explains the Islamic principles governing the practice of wazaif, including the importance of sincerity, the requirement to combine spiritual practices with practical effort, the prohibition against treating Quranic recitation as a magical formula, and the understanding that all outcomes are ultimately in Allah's hands regardless of the practices a person performs. The Urdu prose is clear and practical, avoiding both the extreme of dismissing all structured spiritual practices and the opposite extreme of presenting wazaif as guaranteed solutions to life's problems. The book also includes a section on the etiquette of reciting the Quran during wazaif, covering the recommended state of physical purity, the appropriate mental focus, the importance of consistency over intensity, and the spiritual benefits of regular engagement with the Quran even when immediate results are not apparent. This compilation is a valuable resource for Muslims who wish to develop a disciplined and authentic approach to Quranic spiritual practice.`,
    metaDescription: "Qurani Wazaif is an Urdu compilation of authenticated Quranic spiritual practices and recitations, organised by purpose with clear instructions."
  },
  {
    slug: "qurbani-aqeeqah-aur-ashra-zil-hajja",
    description: `Qurbani, Aqeeqah aur Ashra Zil Hajja is an Urdu-language book that provides comprehensive guidance on three interconnected Islamic practices associated with sacrifice, devotion, and the blessed days of Dhul Hijjah, the twelfth month of the Islamic calendar. The book brings together three topics that are often treated separately in Islamic literature, recognising that they share common themes of sacrifice, submission to Allah, and the expression of gratitude through the offering of what is valuable. The section on Qurbani covers the Islamic practice of animal sacrifice performed during the days of Eid al-Adha, providing detailed rulings on who is obligated to perform the sacrifice, which animals are acceptable, the minimum standards for the health and condition of the sacrificial animal, the proper method of slaughtering according to Islamic requirements, the distribution of the meat between the person performing the sacrifice, their family, and the poor, and the spiritual significance of the practice as a commemoration of Prophet Ibrahim's willingness to sacrifice his son in obedience to Allah. The fiqh rulings are presented with attention to the differences of opinion among the major schools of Islamic jurisprudence, allowing readers to follow the guidance of their own school while understanding the basis for alternative positions. The section on Aqeeqah covers the Islamic practice of sacrificing an animal on the occasion of a child's birth, detailing the recommended timing, the type and number of animals to be sacrificed for a boy versus a girl, the naming ceremony, the shaving of the newborn's hair, and the spiritual significance of Aqeeqah as an expression of gratitude to Allah for the blessing of a child. The section on Ashra Zil Hajja addresses the first ten days of Dhul Hijjah, which the Prophet Muhammad, peace be upon him, described as the best days in the sight of Allah. This section discusses the virtues and specific recommended acts of worship for these blessed days, including fasting on the Day of Arafah, increased remembrance of Allah, charity, and the recitation of takbir. The book provides practical guidance for Muslims who want to make the most of these important days and ensure that their observance of Qurbani and related practices meets the requirements of Islamic law while maximising the spiritual benefit they derive from these acts of devotion.`,
    metaDescription: "This Urdu book covers the rulings and virtues of Qurbani, Aqeeqah, and the blessed first ten days of Dhul Hijjah with detailed fiqh guidance."
  },
  {
    slug: "rab-ka-dar-per",
    description: `Rab Ka Dar Per, meaning At the Door of the Lord, is an Urdu-language book that explores the profound spiritual theme of a believer's approach to Allah through prayer, supplication, and the cultivation of a personal relationship with the Creator. The title evokes the image of a servant standing humbly at the door of their master, a metaphor that captures both the reverence and the hope that characterise the Islamic approach to divine communion. The book develops this metaphor throughout its chapters, examining the various ways in which a Muslim can approach the door of their Lord, the attitudes and qualities that make this approach acceptable and beloved to Allah, and the blessings and spiritual gifts that await those who persist in seeking nearness to their Creator. The author draws extensively upon Quranic verses that describe Allah's nearness to His servants, His responsiveness to their calls, and His love for those who turn to Him in sincerity. The hadith literature is similarly rich with material on this topic, and the book presents numerous authenticated narrations of the Prophet Muhammad, peace be upon him, that describe the manner in which Allah descends to the lowest heaven in the last third of the night, how He boasts about His fasting servants to the angels, how He stretches out His hand during the night to accept the repentance of those who sinned during the day, and how the doors of heaven are opened during the hours of prayer. The book discusses the different spiritual stations that a believer passes through on their journey toward divine proximity, from the basic obligations of prayer and fasting through the supererogatory acts of worship that bring a person closer to Allah, to the highest levels of ihsan or spiritual excellence where the believer becomes aware of Allah's presence at all times. Practical chapters provide guidance on developing a consistent routine of supplication and remembrance, overcoming the spiritual dryness and distraction that can interrupt a person's connection with Allah, and dealing with the sense of unworthiness that sometimes prevents people from approaching their Lord in prayer. The Urdu prose is lyrical and spiritually evocative, drawing the reader into the contemplative atmosphere that the book seeks to create. This title is recommended for readers who are seeking to deepen their prayer life and develop a more intimate and meaningful relationship with Allah through the practices of dua, dhikr, and spiritual reflection.`,
    metaDescription: "Rab Ka Dar Per is an Urdu book on approaching Allah through prayer and supplication, exploring spiritual stations and divine proximity."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
