const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "the-dua-of-faizah",
    description: `The Dua of Faizah is an English-language Islamic storybook that weaves a narrative around the practice of making dua (supplication to Allah), using the experiences of a relatable young character to teach children about the importance, power, and proper manner of supplication in Islam. The story follows Faizah, a young Muslim girl who encounters situations in her daily life that lead her to turn to Allah through dua, discovering in the process that supplication is not merely a ritual but a profound means of communication with her Creator that brings comfort, guidance, and answered prayers.

The narrative is structured around a series of episodes from Faizah's life, each episode presenting a different situation that calls for dua. Some situations involve ordinary childhood challenges such as difficulty with schoolwork, anxiety about a new experience, or conflict with a friend. Others involve more significant moments such as concern for a family member's health or a community hardship. In each case, the story shows Faizah learning about the specific duas that are relevant to her situation, understanding the proper etiquette of making dua, and experiencing the reassurance and peace that comes from placing her trust in Allah. The story demonstrates that dua is not limited to formal situations or specific times but is a constant companion that a Muslim can turn to in every circumstance.

The book incorporates a significant educational component by presenting the actual text of specific duas that are relevant to the situations in the story. These duas are drawn from the authentic hadith collections and the Quran, providing children with practical supplications that they can memorize and use in their own lives. The Arabic text of each dua is presented alongside its English translation and transliteration, making it accessible to children who are learning Arabic as well as those who are not yet familiar with the Arabic script. The story context helps children understand not only the words of each dua but also the appropriate circumstances for its use and the proper attitude of humility, sincerity, and hope that should accompany supplication.

The writing style is warm and engaging, with descriptive language that brings Faizah's world to life without being overly complex for young readers. The story carries natural emotional resonance as Faizah navigates the ups and downs of childhood while growing in her understanding of and relationship with Allah through the practice of dua. Parents will find this book to be a valuable tool for teaching their children about supplication in a way that feels natural and relatable rather than purely instructional. The story format allows children to absorb the lessons about dua through identification with the protagonist, making the teaching more effective and lasting than direct instruction alone. The Dua of Faizah is suitable for children aged approximately five to ten years, and it works well both as a bedtime story and as a classroom reading text in Islamic schools.`,
    metaDescription: "An English storybook teaching children about Islamic supplication through the relatable experiences of young Faizah, with authentic duas and translations."
  },
  {
    slug: "the-emir-and-the-verse",
    description: `The Emir and the Verse is an English-language storybook that uses narrative fiction to convey Islamic values and moral lessons through an engaging tale that captures the imagination of young readers. The story centers on an emir, a leader or commander, whose life is transformed by his encounter with a single verse of the Quran. This central premise allows the book to explore themes of humility, the power of divine guidance, the responsibility of leadership, and the transformative effect that genuine engagement with Allah's words can have on a person's character and priorities.

The narrative is crafted to hold the attention of children through a combination of vivid descriptions, relatable emotions, and a plot that moves with sufficient momentum to maintain interest while still allowing the central moral and spiritual themes to develop naturally. The emir is presented as a complex character who has achieved significant worldly success and power but who discovers, through his encounter with a Quranic verse, that true greatness lies not in worldly authority but in submission to Allah and service to His creation. The journey of transformation that the emir undergoes is portrayed with sensitivity and nuance, showing both the initial resistance that a proud person might feel when confronted with a truth that challenges their self-image and the gradual, sometimes painful process of internal change that genuine spiritual awakening requires.

The book uses the story format to introduce children to important Islamic concepts in a way that feels organic and natural rather than didactic. The concept of tawbah (repentance), the importance of humility before Allah, the responsibility that comes with power and authority, the significance of the Quran as a guide for all aspects of life, and the principle that a person's true worth is measured by their taqwa (consciousness of Allah) rather than their worldly status are all woven into the narrative without disrupting its flow or becoming preachy. The Quranic verse that serves as the catalyst for the emir's transformation is presented in full, with its Arabic text, English translation, and an age-appropriate explanation of its meaning and context.

The educational value of the book extends beyond its central moral lesson. The story exposes children to elements of Islamic history and culture, introduces them to the idea that the Quran's guidance is relevant to all people regardless of their social position, and models the process of engaging with Quranic text in a reflective and personal way. The language is appropriate for independent reading by children in the middle elementary grades, and it also works well as a read-aloud story for younger children. Teachers and parents will find the story useful as a starting point for discussions about character development, the power of the Quran, and the Islamic understanding of true leadership and success.`,
    metaDescription: "An English storybook about an emir transformed by a Quranic verse, teaching children about humility, leadership, and the power of divine guidance."
  },
  {
    slug: "the-end-of-the-world",
    description: `The End of the World is an English-language book that provides a thorough and systematic treatment of Islamic eschatology, presenting the Quranic and prophetic teachings about the events that will precede and accompany the end of the world and the Day of Judgment. Eschatology, the study of the final events of human history, is a significant component of Islamic belief that receives considerable attention in both the Quran and the hadith literature. This book gathers and organizes the authentic narrations about these events, providing English-speaking readers with a comprehensive and reliable guide to what Islam teaches about the culmination of human history.

The book is organized in a chronological framework that follows the sequence of events as described in the authentic sources. It begins with the minor signs of the Last Hour, the portents and indicators that the end of the world is approaching, which include both specific events mentioned in the hadith and general moral and social conditions that the Prophet predicted would prevail in the later days. The minor signs are discussed individually, with each sign presented along with its source in the hadith literature and an explanation of its meaning and significance. The treatment is careful to distinguish between well-authenticated narrations and those of weaker reliability, providing readers with a clear understanding of which signs are firmly established in the prophetic tradition.

The major signs of the Last Hour, which are the extraordinary cosmic and historical events that will directly precede the Day of Judgment, receive extensive treatment. These include the emergence of the Dajjal (the False Messiah or Antichrist), the descent of Isa ibn Maryam (Jesus, son of Mary), the emergence of Yajuj and Majuj (Gog and Magog), the rising of the sun from the west, the beast of the earth, and the blowing of the trumpet. Each of these events is discussed with reference to the relevant Quranic verses and hadith, and the authentic narrations are distinguished from legendary or weak reports that have been attributed to these events in popular literature.

The sections covering the Day of Judgment itself describe the events of that tremendous day as they are portrayed in the Quran and hadith, including the resurrection, the gathering of all creation, the presentation of the record of deeds, the weighing of deeds, the bridge over the Hellfire, the intercession, and the ultimate destinations of Paradise and Hellfire. The descriptions are drawn directly from the primary sources and are presented in a manner that conveys the seriousness and reality of these events without engaging in speculative elaboration.

The book concludes with a discussion of the practical implications of belief in the Hereafter, showing how this belief should affect a Muslim's priorities, behavior, and attitude toward life. The final chapters address the relationship between eschatological belief and spiritual vitality, demonstrating how consciousness of the end of the world and the Day of Judgment serves as a powerful motivator for righteous action and a source of comfort in the face of worldly difficulties. The English presentation makes this important area of Islamic knowledge accessible to a wide readership, and the careful attention to the authenticity of sources makes it a reliable reference work.`,
    metaDescription: "A comprehensive English book on Islamic eschatology covering the minor and major signs of the Last Hour and the events of the Day of Judgment."
  },
  {
    slug: "the-essential-pearls-gems-of-ibn-taymiyyah",
    description: `The Essential Pearls and Gems of Ibn Taymiyyah is a curated collection of the most significant teachings, insights, and scholarly contributions of Shaikh ul-Islam Ibn Taymiyyah, one of the most influential and intellectually powerful Islamic scholars in history. Ibn Taymiyyah's written output was enormous, encompassing works on Quranic exegesis, hadith, jurisprudence, theology, philosophy, and polemics, and his ideas have continued to shape Islamic thought for the seven centuries since his death. This book distills his vast scholarly legacy into a manageable volume that captures the essential themes and arguments that define his contribution to Islamic knowledge.

The collection is organized thematically, with each chapter focusing on a major area of Ibn Taymiyyah's thought. The opening chapters address his contributions to the science of tawheed (Islamic monotheism), which represent some of his most original and influential work. His writings on the names and attributes of Allah, his critique of the philosophical theology that had gained influence in some circles of Islamic thought, and his insistence on returning to the methodology of the early generations for understanding these issues are presented in carefully selected excerpts that convey the substance of his arguments without requiring readers to work through his massive original treatises. The chapter on creed also covers his positions on faith, the companions, and the relationship between reason and revelation.

The sections on jurisprudence highlight Ibn Taymiyyah's distinctive approach to Islamic law, which combined deep knowledge of the four major schools of jurisprudence with a commitment to following the strongest evidence regardless of which school it supported. His famous fatwas on issues such as talaq (divorce), the treatment of prisoners of war, economic transactions, and the interaction between Islamic law and non-Muslim communities are among the most widely cited and debated in the entire fiqh literature. This collection presents selections from his most important juristic discussions, showing how he arrived at his positions through rigorous analysis of the primary sources.

The chapters on spirituality and ethics reveal a dimension of Ibn Taymiyyah that is sometimes overshadowed by his reputation as a polemicist and jurist. His writings on the diseases of the heart, the importance of sincerity in worship, the virtues of the Quran, and the proper approach to spiritual development show a scholar whose concern for the internal states of the believer was as profound as his concern for the correctness of external belief and practice. These selections demonstrate that Ibn Taymiyyah's scholarly project was not merely an intellectual exercise but a comprehensive effort to guide Muslims toward the full realization of Islamic teachings in both belief and practice.

The book includes biographical material that places Ibn Taymiyyah's work in its historical context, explaining the intellectual and political environment in which he lived and worked. The English translation and commentary make his ideas accessible to readers who cannot access the original Arabic works. The Essential Pearls and Gems serves as an excellent introduction to Ibn Taymiyyah's thought for students and general readers, and as a useful reference for scholars who want quick access to his positions on specific topics.`,
    metaDescription: "A curated English collection of Ibn Taymiyyah's key teachings on tawheed, jurisprudence, and spirituality, an introduction to his scholarly legacy."
  },
  {
    slug: "the-example-of-sacrifice-shuaib-ar-romi",
    description: `The Example of Sacrifice - Shuaib Ar Romi presents the biography of Shuaib Ar-Romi, a companion of the Prophet Muhammad whose story exemplifies the principle of sacrifice in the path of Islam. The title "Ar-Romi" indicates that Shuaib was of Roman or Byzantine origin, which means he was a convert to Islam from a Christian or pagan background in the Byzantine-controlled territories. The biographies of non-Arab companions are of particular significance because they demonstrate the universal appeal of Islam from its earliest days and the diverse backgrounds from which the Prophet's followers came.

Shuaib Ar-Romi's story of sacrifice encompasses multiple dimensions. The most fundamental sacrifice was his abandonment of his previous religious and cultural identity to embrace Islam, a decision that in the context of the Byzantine empire carried significant personal, social, and potentially legal consequences. The story traces his journey from his origins in the Roman territories to his arrival in the Muslim community, the challenges he faced in adapting to a new life and a new faith, and the contributions he made to the early Muslim community. His experience as a convert provides insight into the early Muslim community's approach to integrating people from diverse backgrounds and the principle that Islam transcends ethnic and cultural boundaries.

The biography details Shuaib's participation in the major events of the prophetic period and the subsequent caliphate, focusing on instances where his willingness to sacrifice personal comfort, safety, or advantage for the sake of Islam was most clearly demonstrated. Like many of the less well-known companions, his contributions may not be as widely documented as those of the most famous figures, but his example of dedication and sacrifice is no less powerful or instructive. The book draws upon the available historical sources, including hadith collections, biographical dictionaries, and historical chronicles, to construct as complete a picture of his life and contributions as the surviving evidence allows.

The narrative emphasizes the lessons that contemporary Muslims can draw from Shuaib's example. The principle of sacrifice is a recurring theme in Islamic teaching, and Shuaib's life illustrates what this principle looks like when lived out in practice. His willingness to leave behind everything familiar, to face uncertainty and potential hardship, and to dedicate himself fully to his new faith and community provides a model for Muslims of all backgrounds who are called upon to make sacrifices for their faith in their own lives. The book is written in clear English that makes this companion's story accessible to a wide audience, and it serves as a valuable addition to the biographical literature on the companions of the Prophet Muhammad. The story of Shuaib Ar-Romi reminds readers that the early Muslim community was enriched by people from every background who were united by their faith and their willingness to sacrifice for it.`,
    metaDescription: "The biography of Shuaib Ar-Romi, a companion of Byzantine origin whose conversion to Islam exemplifies sacrifice and the universal message of the faith."
  },
  {
    slug: "the-faith-of-truth-pocket-size",
    description: `The Faith of Truth in its pocket-size edition provides a compact and portable reference on Islamic aqidah (creed) that is designed to be carried easily and consulted quickly when questions about matters of belief arise. Despite its small dimensions, this book contains a remarkably comprehensive treatment of the major articles of Islamic faith, presented in a clear and organized format that makes it useful as both a quick reference and a study text. The pocket-size format reflects a practical understanding that questions about matters of creed can arise at any time and in any setting, and having a reliable source of answers readily available is valuable for Muslims who want to maintain correct belief and be able to address misconceptions when they encounter them.

The book covers the six pillars of iman (faith) as defined in the famous hadith of Jibril: belief in Allah, His angels, His revealed books, His messengers, the Day of Judgment, and divine decree (qadar). Each pillar is discussed with sufficient detail to provide a meaningful understanding, supported by references to the Quran and authentic hadith. The section on belief in Allah covers the three categories of tawheed, the divine attributes, and the common errors that distort the proper understanding of Allah's nature. The section on the angels discusses the nature of these beings, their roles and functions, and the specific angels mentioned in the Quran and hadith. The sections on the revealed books and messengers trace the history of divine revelation through the major prophets and scriptures, culminating in the final revelation through Prophet Muhammad and the Quran.

The chapter on the Day of Judgment provides an overview of Islamic eschatology, covering the events that will precede the Last Day, the resurrection, the accounting of deeds, and the ultimate destinations of Paradise and Hellfire. The chapter on divine decree addresses one of the most intellectually challenging aspects of Islamic theology, explaining the four components of qadar (divine knowledge, divine writing, divine will, and divine creation) and how belief in divine decree relates to human free will and responsibility. The explanation is carefully calibrated to be accessible to general readers while maintaining theological accuracy.

Additional sections of the book address important creedal topics that are closely related to the six pillars, including the definition and types of shirk (associating partners with Allah), the concept of bid'ah (religious innovation) and its relationship to creed, the status of the companions of the Prophet, and the proper approach to differences of opinion in matters of belief. Each topic is treated with the clarity and concision that the pocket-size format demands, making every paragraph count. The English language presentation is straightforward and free of unnecessary jargon, making the content accessible to readers with varying levels of familiarity with Islamic theology. This pocket-size edition is particularly useful for students, teachers, chaplains, and anyone who needs a quick and reliable reference on Islamic creed that can be carried at all times.`,
    metaDescription: "A pocket-size English reference on Islamic creed covering the six pillars of faith, tawheed, divine decree, and related creedal topics."
  },
  {
    slug: "the-first-caliph-of-islam-abu-bakr-as-siddeeq-ra",
    description: `The First Caliph of Islam - Abu Bakr As Siddeeq presents a detailed biography of Abu Bakr Abdallah ibn Abi Quhafah, the closest companion of Prophet Muhammad and the first person to succeed him as the leader of the Muslim community. Abu Bakr's life story is inseparable from the story of Islam itself, as he was present from the very beginning of the prophetic mission and played a critical role in every major development of the early Muslim community. His biography is essential reading for anyone who wishes to understand the foundations of Islamic history and the qualities that defined the early Muslim leadership.

The book traces Abu Bakr's life from his early years in Mecca, where he was a respected merchant and a close friend of Muhammad even before the advent of Islam, through his immediate acceptance of the prophetic message and his subsequent role as the Prophet's most trusted companion. The title "As-Siddeeq" (the truthful) was given to him by the Prophet himself, in recognition of his unwavering affirmation of the Prophet's truthfulness, most notably during the event of the Isra and Mi'raj (the Night Journey and Ascension) when some Muslims wavered in their belief but Abu Bakr immediately accepted the account without hesitation. The book examines the qualities that earned him this title and the practical ways in which he demonstrated truthfulness and loyalty throughout his association with the Prophet.

Abu Bakr's contributions to the early Muslim community were multifaceted and indispensable. He was the first adult male to accept Islam, and he used his considerable wealth, social standing, and personal influence to support the Muslim community throughout the Meccan period. He bought and freed numerous slaves who had been tortured for accepting Islam, he accompanied the Prophet during the migration to Madinah, and he participated in all the major battles. The book provides detailed accounts of his role in these events, drawing upon the well-authenticated reports in the hadith and sirah literature. His relationship with the Prophet was one of extraordinary closeness, characterized by mutual trust, affection, and respect, and the book documents this relationship through the numerous narrations that describe their interactions.

The caliphate of Abu Bakr, which lasted approximately two years from 11 AH to 13 AH (632-634 CE), receives extensive treatment in the book. His caliphate faced immediate and existential challenges, including the apostasy wars (the Riddah wars) that threatened to dissolve the unity of the Muslim community, the false prophets who emerged in various regions claiming prophethood after the death of Muhammad, and the military campaigns against the Byzantine and Persian empires that began the great expansion of Islamic rule. The book examines Abu Bakr's handling of each crisis with the calm decisiveness, strategic wisdom, and unwavering faith that characterized his leadership. His famous statement upon assuming the caliphate, that if he did wrong the people should correct him and if he did right they should support him, encapsulates the spirit of accountable leadership that he embodied. The biography draws upon the major classical sources and presents the material in clear English, making the life of this essential companion accessible to contemporary readers.`,
    metaDescription: "A detailed biography of Abu Bakr As-Siddeeq, the first caliph of Islam, covering his life, his closeness to the Prophet, and his decisive leadership."
  },
  {
    slug: "the-first-human-murder",
    description: `The First Human Murder is a children's book that retells the Quranic story of Habil and Qabil (Abel and Cain), the two sons of Adam and Hawwa, in a manner that is accessible, engaging, and educational for young readers. This story, narrated in the Quran in Surah Al-Ma'idah, is one of the earliest and most powerful accounts of human moral failure, and it carries lessons about jealousy, obedience to Allah, the sanctity of life, and the consequences of allowing negative emotions to override reason and faith. The book brings this ancient narrative to life for children while carefully conveying its moral and spiritual teachings in an age-appropriate way.

The story follows the two brothers, Habil and Qabil, as they grow up in the first family on earth. As they reach adulthood, each is required to present an offering to Allah. Habil, who is a shepherd, offers the best of his flock with sincerity and devotion, while Qabil, who is a farmer, offers inferior produce from his harvest with a begrudging and insincere attitude. When Allah accepts Habil's offering and rejects Qabil's, Qabil's jealousy and anger overwhelm him, leading to the first act of murder in human history. The book tells this story with careful attention to the emotional and moral dynamics at play, helping children understand not just what happened but why it happened and what the story teaches about handling negative emotions.

The book takes particular care in presenting the murder itself. Rather than dwelling on the violence, the narrative focuses on the moral choices that led to the act and its devastating consequences. The Quranic account is followed closely, including the powerful scene in which Qabil, after killing his brother, does not know what to do with the body until Allah sends a crow to scratch the ground and show him how to bury it. This episode is presented in a way that highlights the gravity of taking a life and the dignity that Islam accords to every human being, even after death, through the requirement of proper burial.

The educational component of the book is reinforced through several features. After the main narrative, the book includes a section that discusses the key lessons of the story in language that children can understand. These lessons include the importance of sincerity in worship, the danger of jealousy and anger, the sanctity of human life, the idea that Allah sees and knows everything, and the principle that every action has consequences. The book also includes discussion questions that parents and teachers can use to engage children in conversation about the story and its relevance to their own lives. The language is appropriate for children in the early to middle elementary grades, and the narrative holds attention through its dramatic arc and its emotional resonance. The illustrations, if included, are designed to support the story without depicting the murder directly. The First Human Murder serves as both a compelling story and a valuable educational resource for teaching children about one of the Quran's most important moral narratives.`,
    metaDescription: "A children's book retelling the Quranic story of Habil and Qabil, teaching about jealousy, the sanctity of life, and the consequences of moral failure."
  },
  {
    slug: "the-football-feud",
    description: `The Football Feud is an English-language children's book that uses the popular and relatable context of a football (soccer) rivalry to teach Islamic values of sportsmanship, brotherhood, fair play, and emotional control. The story centers on a group of young Muslim boys whose enthusiasm for football creates tension and conflict, both within their team and between rival teams, and it follows their journey toward learning how to balance competitive spirit with the Islamic principles of good character and mutual respect.

The narrative unfolds through a series of episodes that will be immediately recognizable to any child who participates in team sports. The central conflict arises when the competitive desire to win begins to overshadow the values of fair play and good sportsmanship. Arguments between teammates, clashes with opposing players, and the temptation to bend or break the rules to gain an advantage create situations that test the characters' commitment to Islamic values under pressure. The story shows how these situations are resolved through the guidance of parents, coaches, and Islamic teachings, demonstrating that the principles of Islam are not limited to the mosque or the prayer mat but apply to every aspect of life, including the playing field.

Each episode in the story is designed to teach a specific Islamic value or character trait. The value of controlling anger is addressed through a character who struggles with temper on the pitch. The importance of honesty is explored through a situation involving a disputed refereeing decision. The principle of brotherhood is demonstrated when teammates must set aside their differences and support one another for the good of the team. The value of humility is taught through the experience of both winning and losing gracefully. The concept of intention (niyyah) is introduced through a discussion of whether playing sports for enjoyment and health can be an act of worship when done with the right intention.

The book includes Quranic verses and hadith that are relevant to the lessons being taught, presenting them in a natural context that helps children understand their practical application. The references are included without being heavy-handed or disrupting the flow of the narrative, and they serve to show children that Islam provides guidance for every situation they encounter. The story is written in language that is appropriate for independent reading by children in the middle elementary grades, and it works equally well as a read-aloud book for younger children. The characters are diverse and relatable, representing different personalities and challenges that children will recognize from their own experiences with sports and social interaction. Teachers and coaches in Islamic schools and youth programs will find this book to be a useful tool for teaching good character through a medium that children naturally enjoy and engage with.`,
    metaDescription: "A children's book using a football rivalry to teach Islamic values of sportsmanship, honesty, brotherhood, and emotional control through storytelling."
  },
  {
    slug: "the-fourth-caliph-of-islam-ali-bin-abi-talib-ra",
    description: `The Fourth Caliph of Islam - Ali Bin Abi Talib presents a comprehensive biography of Ali ibn Abi Talib, the cousin and son-in-law of Prophet Muhammad and the fourth of the rightly guided caliphs. Ali's life is one of the most extensively documented and most frequently discussed in all of Islamic history, and his biography touches upon virtually every major theme in the study of early Islam, from theology and jurisprudence to politics and military history. This book provides a balanced and thorough account of his life, drawing upon the major classical sources to present the historical record with scholarly objectivity.

The biography begins with Ali's extraordinary early life. He was raised in the household of the Prophet Muhammad from a young age, giving him an unparalleled proximity to the source of Islamic revelation during the most critical period of its communication. He was among the very first to accept Islam, accepting the message as a young boy of approximately ten years of age, making him the first child to embrace the faith. This early entry into Islam, combined with his upbringing in the Prophet's household, gave him a depth of knowledge and a strength of character that would define his entire life. The book documents his education under the Prophet's direct guidance, his participation in the key events of the Meccan and Medinan periods, and the development of the remarkable qualities of knowledge, courage, eloquence, and spiritual devotion for which he became renowned.

Ali's marriage to Fatimah, the daughter of the Prophet, produced the Prophet's grandchildren, Hasan and Husayn, who are among the most beloved figures in Islamic history. The book discusses this family relationship and its significance in Islamic tradition, while maintaining focus on Ali's own life and contributions. His role in the major battles of the prophetic period, including Badr, Uhud, the Trench, and the conquest of Mecca, is documented with detailed accounts of his exploits and the Prophet's praise for his bravery and loyalty.

The caliphate of Ali, from 35 AH to 40 AH (656-661 CE), was among the most turbulent periods in early Islamic history, and the book addresses the major events and controversies of this period with scholarly balance. The challenges Ali faced upon assuming the caliphate, including the opposition of several prominent companions, the fitnah (civil strife) that engulfed the Muslim community, the Battle of the Camel, the Battle of Siffin, and the emergence of the Kharijites are all discussed in detail. The book presents the different perspectives on these events that exist in the historical sources, allowing readers to understand the complexity of the situation without taking sectarian positions. Ali's personal qualities during this difficult period, including his patience, his devotion to justice, his deep knowledge of Islamic law, and his spiritual intensity, are documented through authentic reports.

The book also covers Ali's contributions to Islamic scholarship, particularly his knowledge of the Quran, his juristic opinions, and his eloquent sermons and letters that have been preserved in collections such as Nahj al-Balagha. His reputation as one of the most knowledgeable companions and as a master of Arabic eloquence is examined. The biography concludes with an assessment of Ali's legacy and his enduring significance in Islamic history, theology, and culture.`,
    metaDescription: "A comprehensive biography of Ali ibn Abi Talib, the fourth caliph, covering his upbringing in the Prophet's household, caliphate, and scholarly legacy."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
