const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "gunahon-ko-dho-dalny-waly-amal",
    description: `"Gunahon Ko Dho Dalny Waly Amal" is a spiritually uplifting Urdu book that focuses on the merciful aspect of Allah's nature — specifically, the deeds and acts of worship that have the power to wipe away sins and transgressions, no matter how numerous or grave they may seem. This book addresses a fundamental concern of every believer: the weight of past sins and the anxiety of whether one can ever be truly forgiven. Drawing upon authentic Hadith narrations and Quranic verses, the author provides a comprehensive and reassuring guide to the various means through which Allah, in His infinite mercy, has promised to erase the record of our wrongdoings.

The book covers a wide range of virtuous deeds that serve as expiation for sins, including the performance of obligatory prayers, voluntary prayers, fasting, charity, pilgrimage, seeking forgiveness (istighfar), recitation of the Quran, night prayers (tahajjud), and acts of kindness toward fellow human beings. Each chapter explains the specific merit of a particular deed and cites the relevant Hadith in which the Prophet Muhammad (PBUH) described its sin-erasing power. For example, the book discusses the famous Hadith in which the Prophet (PBUH) compared the five daily prayers to a river flowing beside one's door in which a person bathes five times a day, washing away all impurities. Similarly, the expiation achieved through fasting on the Day of Arafah, the night of Qadr, and during Ramadan is explored in detail.

At Rs.200, this compact and affordable book is designed to be accessible to all readers regardless of their financial situation. The Urdu language is straightforward and easy to understand, making the profound spiritual concepts discussed in the book approachable for readers from all backgrounds. The book includes a special section on the conditions for sincere repentance (tawbah) and the signs that one's repentance has been accepted. It also addresses common misconceptions about forgiveness, such as the false belief that certain sins are too great to be pardoned. "Gunahon Ko Dho Dalny Waly Amal" is a beacon of hope for anyone who feels burdened by their past mistakes, reminding them that Allah's mercy encompasses all things and that the door of repentance is always open until the sun rises from the west.`,
    metaDescription: "Gunahon Ko Dho Dalny Waly Amal - Urdu Islamic book about deeds that erase sins. Hope for forgiveness at Rs.200."
  },
  {
    slug: "haashim-discovers-the-stars",
    description: `"Haashim Discovers the Stars" is a delightful children's book that introduces young readers to the wonders of Allah's creation through the eyes of its curious young protagonist, Haashim. On a clear night while gazing at the sky from his rooftop, Haashim begins to ask questions about the twinkling lights above — questions that lead him on an educational journey combining scientific knowledge with Islamic spirituality. This beautifully illustrated book is designed to nurture both a child's natural curiosity about the universe and their growing awareness of the Creator behind it all.

The story follows Haashim as he learns about the stars from various sources — his wise grandfather who teaches him the Islamic perspective, his teacher at school who explains the scientific facts, and his own observations during a family camping trip. Along the way, young readers learn about the different types of stars, constellations, the movement of celestial bodies, and the vast scale of the universe. More importantly, each scientific fact is connected to an Islamic lesson — the creation of the stars as signs of Allah's power and majesty, the Quranic references to stars and the cosmos, and the Prophet's (PBUH) encouragement to seek knowledge about the natural world. The book cleverly avoids the false dichotomy between science and religion, instead showing children that learning about the natural world is a form of worship when done with the right intention.

At Rs.350, this hardcover children's book features vibrant, full-color illustrations that capture the beauty of the night sky and the excitement of discovery. The large, easy-to-read text is perfect for young readers aged 6-12, and the story can also be enjoyed as a read-aloud book for younger children. Parents will appreciate the positive messages about curiosity, family bonding, respect for elders, and the harmony between faith and reason. Schools and madrassas will find it a valuable resource for their science and Islamic studies curriculum, offering a fresh approach to teaching children about the universe from an Islamic perspective. "Haashim Discovers the Stars" is the kind of book that sparks a lifelong love of learning and strengthens a child's connection to their Creator.`,
    metaDescription: "Haashim Discovers the Stars - Islamic children's book exploring astronomy and Allah's creation. Illustrated hardcover at Rs.350."
  },
  {
    slug: "hadith-ka-imam-imam-ahmad-bin-hanbal",
    description: `"Hadith Ka Imam — Imam Ahmad Bin Hanbal" is a concise yet comprehensive Urdu biography of one of the most important figures in Islamic history and one of the four great imams of Islamic jurisprudence. Imam Ahmad ibn Hanbal (Rahimahullah) is renowned not only for founding the Hanbali school of fiqh but also for his unmatched knowledge of Hadith, his compilation of the monumental Musnad Ahmad (which contains over 30,000 Hadith narrations), and his legendary steadfastness during the trials of the Inquisition (Mihnah) when he refused to compromise his beliefs despite severe persecution.

This book traces the life of Imam Ahmad from his birth in Baghdad in 164 AH to his passing in 241 AH, covering the key events and influences that shaped him into one of the most revered scholars in Islamic history. Readers will learn about his exceptional upbringing under his pious mother who raised him as a single parent after his father's death, his relentless pursuit of knowledge that took him across the Muslim world to study under hundreds of teachers, his photographic memory that allowed him to recall hundreds of thousands of Hadith narrations along with their complete chains of transmission, and his ascetic lifestyle despite his immense scholarly stature. The book devotes significant attention to the Mihnah period, during which Imam Ahmad was imprisoned and tortured for refusing to accept the Mu'tazilite doctrine of the createdness of the Quran — a stand that ultimately preserved orthodox Islamic theology for all subsequent generations.

At Rs.200, this affordable biography makes the life and legacy of Imam Ahmad accessible to Urdu-speaking readers of all backgrounds. The writing style is engaging and narrative-driven, avoiding dry academic prose in favor of a storytelling approach that brings historical events to life. The book includes a brief overview of Imam Ahmad's legal methodology and his contributions to Hadith science, making it useful for students of Islamic studies as well as general readers. It serves as an inspiring reminder that true scholarship is rooted in piety, patience, and an unwavering commitment to the truth regardless of the personal cost. This book is a valuable addition to any home library and makes an excellent gift for students of Islamic knowledge.`,
    metaDescription: "Hadith Ka Imam Imam Ahmad Bin Hanbal - Urdu biography of the great Hadith scholar and fiqh imam. Inspiring life story at Rs.200."
  },
  {
    slug: "hadiyat-al-atfal",
    description: `"Hadiyat al-Atfal" (Gift for Children) is a thoughtfully designed Islamic educational resource created specifically to introduce young Muslim children to the fundamentals of their faith in an engaging, age-appropriate manner. This book covers the essential knowledge that every Muslim child should acquire during their early years, including the basic beliefs of Islam (aqeedah), the pillars of Islam and Iman, simple daily prayers and supplications (duas), short chapters (surahs) from the Quran, stories of the prophets, and the basic manners and etiquette that Islam teaches.

The content is organized in a child-friendly format with colorful illustrations, clear Arabic text with Urdu translation and transliteration, and interactive elements that encourage active learning rather than passive reading. Each lesson is kept short and focused to match the attention span of young children, with review questions and simple activities at the end of each section to reinforce learning. The book follows a progressive structure, starting with the simplest concepts — such as the Shahadah and the names of Allah — and gradually building toward more complex topics, ensuring that children develop a solid foundation before moving on to advanced material.

At Rs.220, "Hadiyat al-Atfal" is an affordable investment in your child's Islamic education. The sturdy paperback binding and quality paper ensure durability, even in the hands of enthusiastic young readers. This book is ideally suited for children aged 4-8 and can be used both at home for family-based Islamic education and in formal settings such as madrassas and Islamic schools. Parents who are looking for a systematic and engaging way to introduce their children to the basics of Islam will find this book to be an invaluable resource. The book's approach to Islamic education is balanced and inclusive, presenting the teachings of Islam in a way that is warm, encouraging, and free from sectarian bias. "Hadiyat al-Atfal" truly lives up to its name — it is a gift that keeps on giving, laying the groundwork for a lifetime of faith, knowledge, and spiritual growth.`,
    metaDescription: "Hadiyat al Atfal - Colorful Islamic educational book for children covering basics of faith, Quran and duas. Ages 4-8 at Rs.220."
  },
  {
    slug: "haji-soap-fragrance-free",
    description: `Haji Soap (Fragrance Free) is a specially formulated, pure soap designed with the needs of Muslim consumers in mind, particularly those who require a mild, unscented cleansing option for daily use or for specific religious occasions. This soap is manufactured using high-quality natural ingredients and is completely free from artificial fragrances, colors, and harsh chemicals that may cause skin irritation. The fragrance-free formulation makes it especially suitable for individuals with sensitive skin, allergies, or conditions that are aggravated by perfumed products.

For Muslim consumers, Haji Soap holds particular appeal because of its purity and suitability for use during religious rituals. Many Muslims prefer unscented products when performing ablution (wudu) and bathing (ghusl) to ensure that no barrier prevents water from reaching the skin — a requirement for the validity of these acts of worship. The soap produces a rich, creamy lather that cleanses effectively without leaving any residue or artificial scent behind. Its gentle formula respects the skin's natural moisture balance, making it suitable for frequent use during Ramadan, Hajj, Umrah, or daily prayer routines when multiple ablutions are performed throughout the day.

At just Rs.100, Haji Soap (Fragrance Free) represents excellent value for a high-quality, pure cleansing product. The compact size makes it convenient for travel — perfect for carrying in your luggage during Hajj or Umrah pilgrimages. The soap is long-lasting and produces consistent results with every use. Bab-ul-Fatah is proud to offer this essential personal care product to its customers, recognizing that purity and quality in everyday items are part of living a mindful Islamic lifestyle. Stock up on Haji Soap for your household needs, or include it in care packages for pilgrims heading to Makkah and Madinah. It is a small but meaningful product that supports a clean and worship-ready lifestyle.`,
    metaDescription: "Haji Soap Fragrance Free - Pure unscented soap ideal for wudu and sensitive skin. Travel-friendly at Rs.100."
  },
  {
    slug: "hajj-aur-umrah-kay-masail",
    description: `"Hajj aur Umrah Kay Masail" is a comprehensive Urdu reference book that provides detailed rulings and practical guidance on every aspect of performing Hajj and Umrah according to Islamic law. This authoritative guide covers the complete journey of the pilgrim — from the moment they decide to undertake the sacred journey to the rites performed at each holy site in Makkah and Madinah, and the rulings governing common situations and problems that pilgrims may encounter along the way. The book draws its rulings from the major schools of Islamic jurisprudence, with particular emphasis on the Hanafi school which is predominant in the Indian subcontinent.

The book is systematically organized into clear sections that follow the chronological sequence of the Hajj and Umrah rituals. It begins with the prerequisites for Hajj and Umrah — including the financial ability, physical fitness, and mahram requirements — before moving to detailed guidance on entering the state of ihram, the restrictions that apply during ihram, the rituals of Tawaf (circumambulation), Sa'i (walking between Safa and Marwah), standing at Arafat, staying in Muzdalifah and Mina, the stoning of the Jamaraat, animal sacrifice, and the farewell Tawaf. Each ritual is explained with step-by-step instructions that make it easy for first-time pilgrims to follow. The book includes fatwas (religious rulings) on contemporary issues such as performing Tawaf on upper floors, using wheelchair assistance, dealing with menstrual issues during Hajj, and the rulings for women pilgrims.

At Rs.1020, this well-organized reference book is printed in a clear, easy-to-read Urdu font with headings and bullet points that facilitate quick reference during the pilgrimage itself. The book includes diagrams of the Ka'bah and the holy sites, maps of the pilgrimage routes, and a comprehensive index that allows readers to quickly find specific rulings. Many experienced Hajj guides and group leaders recommend this book to their pilgrims because of its practical approach and comprehensive coverage. Whether you are a first-time pilgrim or someone who has performed Hajj multiple times and wishes to ensure the correctness of your worship, "Hajj aur Umrah Kay Masail" is an essential companion that will guide you through every step of your sacred journey with confidence and peace of mind.`,
    metaDescription: "Hajj aur Umrah Kay Masail - Comprehensive Urdu guide to Hajj Umrah rituals with fiqh rulings. Essential pilgrimage manual at Rs.1020."
  },
  {
    slug: "hajj-umrah-visitors",
    description: `"Hajj, Umrah & Visitors" is a comprehensive English-language guide that caters to three distinct categories of travelers to the holy cities of Makkah and Madinah: those performing the obligatory Hajj pilgrimage, those undertaking the voluntary Umrah, and general visitors who travel to the region for tourism, business, or to visit the Prophet's Mosque in Madinah. This versatile guidebook provides practical, up-to-date information that helps all categories of travelers plan their trip effectively, navigate the holy sites with ease, and maximize the spiritual benefit of their time in the blessed cities.

For Hajj and Umrah pilgrims, the book offers detailed step-by-step instructions for every ritual, supported by clear diagrams and illustrations. The rites of ihram, Tawaf, Sa'i, the day of Arafat, and all other essential rituals are explained with precision and clarity. The book includes special sections on common mistakes that pilgrims make and how to avoid them, health and safety tips for the pilgrimage, packing checklists, currency and communication advice, and guidance on managing the logistics of travel, accommodation, and transportation in Saudi Arabia. For general visitors to Madinah, the book provides information about the Prophet's Mosque, visiting protocols, nearby historical sites, and the etiquette of being in the sacred city.

At Rs.1950, this guidebook is a worthwhile investment for anyone planning a trip to the holy cities. The information is presented in a well-organized format with tabbed sections, color-coded categories, and a quick-reference card that can be carried separately during the actual pilgrimage. The book has been updated to reflect recent changes in Saudi infrastructure, including the expanded mataf area around the Ka'bah, the upgraded Jamaraat bridge, and new transportation systems. It also includes duas (supplications) for each stage of the journey, presented in Arabic with English translation and transliteration. Whether you are traveling independently or with a group, "Hajj, Umrah & Visitors" is the comprehensive companion you need to ensure your sacred journey is spiritually fulfilling and practically smooth.`,
    metaDescription: "Hajj Umrah & Visitors - Complete English guide for pilgrims and visitors to Makkah and Madinah with maps and duas at Rs.1950."
  },
  {
    slug: "hajj-umrah-ziyarah",
    description: `"Hajj, Umrah & Ziyarah" is a practical, user-friendly guidebook designed to serve as a compact companion for pilgrims performing Hajj and Umrah, as well as those undertaking ziyarah (visitation of sacred sites) in Makkah and Madinah. This book distinguishes itself by its focus on the ziyarah component — the visitation of historical and religious sites associated with Islamic history that many pilgrims wish to include in their itinerary but often lack sufficient information about. The book provides detailed descriptions of these sites, their historical and religious significance, and practical guidance on how to visit them.

The Hajj and Umrah sections of the book offer concise yet complete instructions for performing all the required rituals, presented in a straightforward format that pilgrims can easily follow even in crowded and stressful conditions. The ziyarah sections cover sites in both Makkah and Madinah — including the Cave of Hira where the Prophet (PBUH) received the first revelation, the Cave of Thawr where he hid during the migration, the battlefield of Uhud, the Quba Mosque (the first mosque in Islam), and the Seven Mosques of the Battle of the Trench, among others. Each site description includes its historical background, religious significance, practical visiting information, and relevant supplications to be recited at the location.

At Rs.700, this affordable guide is designed to be lightweight and portable — the ideal size to carry in your pocket or bag during the actual pilgrimage. The book includes a comprehensive dua collection organized by occasion, making it a dual-purpose resource that serves as both a ritual guide and a supplication handbook. The color-coded sections and clear headings allow for quick reference when time is limited. The author has included practical tips based on personal experience, such as the best times to perform rituals to avoid crowds, recommended routes between sites, and advice for pilgrims with elderly companions or young children. Whether this is your first pilgrimage or a return visit, "Hajj, Umrah & Ziyarah" provides the knowledge and confidence you need to make the most of your blessed journey.`,
    metaDescription: "Hajj Umrah & Ziyarah - Compact pocket guide with ritual instructions and sacred site visits. Perfect travel companion at Rs.700."
  },
  {
    slug: "hamsaigi-ky-haqooq",
    description: `"Hamsaigi Ky Haqooq" (Rights of Neighbors) is a focused Urdu book that addresses one of the most emphasized yet frequently neglected social obligations in Islam — the rights and responsibilities that neighbors have toward one another. The importance of good neighborly relations in Islam cannot be overstated, as evidenced by the Prophet Muhammad's (PBUH) repeated emphasis on this topic, including his famous declaration, "Jibril kept recommending me to be kind to neighbors until I thought he would make them my heirs." This book explores the comprehensive framework of neighborly rights that Islam establishes and provides practical guidance on how to fulfill these obligations in modern life.

The book begins by defining the concept of "neighbor" in Islamic jurisprudence, which extends far beyond the occupants of adjacent houses to include anyone whose property is within a certain radius — approximately forty houses in each direction according to some scholars. It then details the specific rights of neighbors, including the obligation to protect their property and dignity, to share food and resources during times of need, to refrain from causing them harm or inconvenience, to visit them during illness, to congratulate them during times of joy, and to console them during times of grief. The author supports each point with relevant Quranic verses and Hadith narrations, providing a solid scriptural foundation for the practical advice offered.

At Rs.150, this compact book is an accessible and affordable resource for anyone who wishes to strengthen their relationships with their neighbors according to Islamic principles. The Urdu language is clear and direct, making the book suitable for readers of all educational backgrounds. The book addresses contemporary issues such as noise pollution, privacy concerns, parking disputes, and the challenges of maintaining good neighborly relations in apartment buildings and housing societies. It also discusses the rights of neighbors of different faiths, emphasizing that Islam commands fair and kind treatment of all neighbors regardless of their religious affiliation. In an age of increasing social isolation and community breakdown, "Hamsaigi Ky Haqooq" serves as a timely reminder that the strength of a community begins with the quality of its neighborly bonds.`,
    metaDescription: "Hamsaigi Ky Haqooq - Urdu book on Islamic rights and responsibilities of neighbors. Social ethics guide at Rs.150."
  },
  {
    slug: "haqooq-al-zaujain-haqooq-series",
    description: `"Haqooq Al Zaujain" (Rights of Spouses) is a vital volume in the acclaimed Haqooq Series, dedicated exclusively to the mutual rights and responsibilities that Islam establishes between husbands and wives. This book addresses one of the most important aspects of Muslim family life, providing a balanced and comprehensive treatment of marital obligations from both perspectives — what a husband owes his wife and what a wife owes her husband — in strict accordance with the Quran, the Sunnah of the Prophet Muhammad (PBUH), and the consensus of Islamic scholars.

The book systematically covers each category of marital rights, beginning with the foundational rights including the right to kind treatment, mutual respect, and maintaining privacy. It then addresses financial rights such as mahr (dower), maintenance (nafaqah), and the wife's right to independent property ownership. The section on physical and emotional rights covers the obligations of marital intimacy, companionship, and emotional support. The book also discusses the rights related to children, including decisions about their upbringing, education, and discipline. Each right is supported with references to the relevant Quranic verses and Hadith, and the author provides commentary explaining how these principles apply in contemporary Muslim households.

At Rs.170, this volume from the Haqooq Series is an essential resource for Muslim couples — whether newly married or well-established in their married life. The book is written in clear Urdu that is accessible to readers of all backgrounds, and the practical focus makes it useful as both an educational resource and a quick reference for resolving common marital disagreements. Imams and marriage counselors will find it a valuable tool for premarital counseling sessions, as it clearly establishes the Islamic framework within which a healthy marriage operates. The balanced approach avoids the common pitfalls of presenting marital rights in a one-sided manner, instead emphasizing that a successful marriage is built on mutual fulfillment of obligations rather than insistence on one's own rights. "Haqooq Al Zaujain" is a book that every Muslim household should have, as it contains the knowledge needed to build and maintain a strong, loving, and Islamically grounded marriage.`,
    metaDescription: "Haqooq Al Zaujain - Comprehensive Urdu guide on marital rights and duties in Islam from the Haqooq Series. Rs.170."
  }
];

async function main() {
  for (const item of updates) {
    try {
      await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log(`✅ Updated: ${item.slug}`);
    } catch (err) {
      console.error(`❌ Failed: ${item.slug} - ${err.message}`);
    }
  }
  console.log("Done!");
}
main().then(() => prisma.$disconnect());
