const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "my-first-quran-with-pictures",
    description: `My First Quran with Pictures is a thoughtfully illustrated edition designed to introduce young Muslim children to the stories and lessons of the Quran through vibrant, age-appropriate imagery. Each page pairs simplified Quranic narratives with colourful drawings that capture the attention of early readers and pre-readers alike, making the sacred text approachable and engaging for children who are just beginning their religious education. The book covers key stories from the Quran including the creation of the heavens and the earth, the story of Prophet Adam, the patience of Prophet Ayyub, the wisdom of Prophet Sulaiman, the courage of Prophet Musa, and the journey of Prophet Yunus, among many others. What sets this edition apart is its careful balance between visual appeal and textual integrity. The language used throughout the book has been simplified so that children between the ages of three and eight can understand the core message of each story without losing the essential Islamic teachings embedded within them. Parents reading alongside their children will find that each story naturally opens discussions about faith, kindness, patience, gratitude, and trust in Allah. The illustrations are rendered in a style that respects Islamic guidelines regarding visual representation while remaining lively enough to hold a child's focus during story time. The durable binding and thick pages make this book suitable for repeated handling by small hands. Teachers at Islamic schools and weekend madrasah programs frequently use this book as a supplementary resource in early Quranic studies classes, as it provides a visual bridge between oral storytelling and the actual text of the Quran. Families building a home Islamic library will find this illustrated Quran to be a valuable starting point for nurturing love of the Quran in the next generation. The book serves as both an educational tool and a meaningful gift for occasions such as Eid, Ramadan, or a child's first day of madrasah.`,
    metaDescription: "My First Quran with Pictures brings key Quranic stories to life with vibrant illustrations for children aged 3 to 8, making sacred narratives accessible."
  },
  {
    slug: "my-prayer-book",
    description: `My Prayer Book is a practical and beautifully designed instructional guide that teaches Muslim children the fundamentals of Salah in a format tailored to their level of understanding. Rather than overwhelming young learners with complex jurisprudential details, this book breaks down the prayer into clear, sequential steps that children can follow and memorize at their own pace. Each of the five daily prayers is covered individually, with the specific recitations, postures, and number of rakat explained through simple language and supportive visual cues. The book includes the Arabic text for essential supplications alongside transliterated versions and clear English translations, allowing children who are still learning to read Arabic to participate fully in their prayers. Colour-coded sections help distinguish between the different parts of each prayer unit, from the opening Takbir to the final Tasleem. One of the standout features of this book is its emphasis on understanding the meaning behind what is being recited during prayer, rather than treating Salah as a purely physical routine. Brief explanations accompany each dua and dhikr, helping children develop a genuine spiritual connection to their daily worship from an early age. The book also covers the conditions of prayer, the obligatory actions, and common mistakes that children should be aware of, all presented in a friendly and encouraging tone that builds confidence rather than anxiety. Wudu instructions are included as a preliminary section, ensuring that children understand the complete process from purification through to the conclusion of prayer. Parents and Islamic school teachers will appreciate the supplementary activities and review questions that reinforce the material covered in each chapter. The compact size of the book makes it convenient for children to carry to the masjid or keep beside their prayer mat at home. This resource is particularly useful for children who have recently reached the age of seven and are beginning to establish their daily prayer habit.`,
    metaDescription: "My Prayer Book teaches children the steps, recitations, and meanings of Salah through simple language and colour-coded visuals for ages 7 and above."
  },
  {
    slug: "my-wudu-book",
    description: `My Wudu Book is a charming and instructional resource created specifically to help young Muslim children learn the correct method of performing Wudu, the Islamic ritual ablution that precedes prayer and other acts of worship. The book walks children through each step of the Wudu process with clarity and precision, starting from the niyyah or intention and proceeding through the washing of hands, rinsing the mouth, cleaning the nose, washing the face, the arms up to the elbows, wiping the head, cleaning the ears, and finally washing the feet. Each step is illustrated with friendly, child-appropriate images that demonstrate the correct technique, ensuring that even children who cannot yet read fluently can follow along visually. The accompanying text uses short, simple sentences that explain not only what to do but why each action matters within the broader framework of Islamic purification. Alongside the practical instructions, the book introduces children to the concept of taharah or purity as a fundamental principle in Islam, helping them understand that Wudu is more than a physical washing routine; it is a spiritual preparation that cleanses both the body and the soul in preparation for standing before Allah in prayer. The book also covers situations that break Wudu so that children learn when they need to renew their ablution, as well as brief guidance on Tayammum or dry ablution for circumstances where water is unavailable. A section on common mistakes helps children and their parents identify errors that many beginners make, such as not washing between the fingers or neglecting to ensure water reaches the skin beneath the ankles. The durable construction and wipe-clean pages make this book practical for use near sinks and wash areas. Islamic educators recommend this book as a pre-prayer primer that complements any comprehensive Salah education programme for children aged four to nine.`,
    metaDescription: "My Wudu Book guides young children through every step of Islamic ablution with clear illustrations, simple text, and explanations of purity in Islam."
  },
  {
    slug: "naashty-se-school-tak",
    description: `Naashty Se School Tak is an engaging Urdu-language children's book that follows a young child through the morning routine from the moment of waking up to the arrival at school. Written in a rhythmic and conversational style that resonates naturally with young Urdu-speaking readers, the book transforms the everyday activities of a Muslim child's morning into a series of meaningful moments connected to faith, discipline, and personal responsibility. The narrative begins with the child waking up for Fajr prayer, performing Wudu, and completing the first prayer of the day before moving on to brushing teeth, getting dressed, eating a wholesome breakfast, and preparing the school bag. Each activity is described with warmth and gentle humour, making the book enjoyable for children to read independently or listen to during bedtime storytelling. Throughout the pages, Islamic values are woven seamlessly into the fabric of daily life rather than presented as separate religious lessons. The child recites morning supplications, remembers to greet family members with Assalamu Alaikum, thanks Allah for the food provided at breakfast, and makes dua before leaving the house. The book emphasises the importance of punctuality, cleanliness, respect for elders, and gratitude, all within the context of a relatable morning scenario. The Urdu vocabulary used in the book has been selected to be accessible to children who are developing their reading skills, with slightly challenging words appearing frequently enough to build language competence without causing frustration. Teachers at Urdu-medium schools and parents raising children in Urdu-speaking households find this book particularly valuable because it reinforces both linguistic development and Islamic manners simultaneously. The illustrations complement the text by showing a positive, nurturing home environment where Islamic practices are a natural part of everyday living. This book is recommended for children between the ages of five and ten who are comfortable reading Urdu at an elementary level.`,
    metaDescription: "Naashty Se School Tak is an Urdu children's book following a Muslim child's morning routine from Fajr to school, weaving Islamic values into daily life."
  },
  {
    slug: "naat-goi-aur-us-k-adaab",
    description: `Naat Goi aur Us k Adaab is a comprehensive Urdu-language guide that addresses the art and practice of Naat recitation alongside the essential etiquette and guidelines that every Naat reciter should observe. The book serves as both an instructional manual and a work of religious guidance, drawing upon classical Islamic scholarship to establish the proper framework within which the praise of the Prophet Muhammad, peace be upon him, should be expressed. The opening chapters establish the theological foundation for Naat recitation by discussing the elevated status of the Prophet in Islam and the permissibility and merit of expressing love and reverence for him through poetry and prose. The author then transitions into a detailed examination of the adaab or etiquettes that govern this practice, including the importance of maintaining factual accuracy when describing the Prophet's qualities, avoiding exaggerated or inappropriate language that could be construed as shirk, and ensuring that the intention behind recitation remains sincerely directed toward Allah rather than seeking personal fame or applause. The book provides specific guidance on linguistic standards, recommending that Naat be composed and recited in refined Urdu and Arabic that honours the dignity of the subject matter. A significant portion of the text is dedicated to practical instruction for aspiring Naat reciters, covering vocal technique, the appropriate emotional tone, posture during recitation, and the contexts in which Naat recitation is considered most appropriate such as gatherings of dhikr, Mawlid celebrations, and educational settings. The book also includes a curated collection of well-known Naat verses with annotations explaining their meaning and literary devices, making it useful for both performers and listeners who wish to deepen their understanding of the poetry. Scholars and students of Islamic studies will appreciate the scholarly references and hadith citations that underpin the guidance presented throughout the book. This volume is widely used in madrasahs and Islamic institutions where Naat recitation is taught as a formal subject alongside other religious sciences.`,
    metaDescription: "Naat Goi aur Us k Adaab is an Urdu guide covering the art of Naat recitation, its etiquettes, and proper conduct for praising the Prophet Muhammad PBUH."
  },
  {
    slug: "nabi-akram-pbuh-bahesiat-sipah-salar",
    description: `Nabi Akram (PBUH) Bahesiat Sipah Salar is a focused study that examines the role of the Prophet Muhammad, peace be upon him, as a military commander and strategic leader during the various battles and expeditions that shaped the early Muslim community. This book approaches the subject with scholarly rigour, drawing upon authentic hadith sources, classical Seerah literature, and established historical accounts to construct a detailed picture of the Prophet's military leadership qualities. The narrative covers all major engagements including the Battle of Badr, the Battle of Uhud, the Battle of the Trench, the Treaty of Hudaybiyyah, the conquest of Makkah, and the Battle of Hunayn, analysing the strategic decisions made before, during, and after each encounter. What distinguishes this work from general Seerah books is its concentrated attention on the tactical and organisational dimensions of the Prophet's leadership, including his methods of intelligence gathering, his approach to troop deployment, his use of terrain and geography to strategic advantage, his systems for maintaining supply lines, and his consultation with companions on military matters. The book also explores the ethical framework within which the Prophet conducted warfare, documenting his clear instructions regarding the protection of non-combatants, the prohibition of destroying crops and trees, the humane treatment of prisoners of war, and the strict adherence to treaties and agreements. Each chapter presents the historical events alongside analysis of the leadership principles that can be derived from the Prophet's conduct, making the book relevant not only for students of Islamic history but also for readers interested in leadership studies more broadly. The author supports every claim with references to primary sources, allowing readers to verify the information independently. Military professionals, historians, and students of Islamic studies will find this book to be a valuable addition to their libraries, as it fills a specific niche by examining the prophetic military career through an analytical rather than purely narrative lens.`,
    metaDescription: "Nabi Akram PBUH Bahesiat Sipah Salar examines the Prophet's military leadership across major battles with strategic and ethical insights."
  },
  {
    slug: "naiki-kai-safeer",
    description: `Naiki Kai Safeer, meaning Ambassadors of Goodness, is an inspiring Urdu-language book that profiles the lives and contributions of individuals who dedicated themselves to serving Islam and their communities through acts of charity, education, social reform, and moral leadership. The book presents a diverse collection of biographical accounts spanning different eras and regions, each demonstrating how ordinary Muslims transformed their societies through unwavering commitment to Islamic principles and selfless service to others. Among the figures profiled are scholars who established educational institutions that continue to operate centuries after their founding, philanthropists who directed their wealth toward building mosques, hospitals, and orphanages, and community leaders who mediated conflicts and promoted unity during periods of social division. Each chapter follows a consistent structure that introduces the figure's background, describes the challenges they faced, details the specific contributions they made, and extracts enduring lessons that readers can apply to their own lives. The author writes in an accessible Urdu style that brings each personality to life through vivid storytelling while maintaining the factual accuracy that readers expect from a serious biographical work. A recurring theme throughout the book is the Islamic principle that even small, consistent acts of goodness carry immense weight in the sight of Allah, and that one does not need to possess great wealth or high social standing to become an ambassador of goodness. The book emphasises qualities such as sincerity, patience, humility, perseverance, and compassion as the true markers of a person who serves as a positive representative of Islamic values. Sidebars and callout boxes throughout the text highlight relevant Quranic verses and hadith that connect the stories to scriptural guidance. This book is suitable for a wide range of readers including students, educators, community workers, and anyone seeking inspiration to contribute positively to their surroundings. It serves as an excellent resource for Islamic schools looking to introduce students to positive role models from Muslim history.`,
    metaDescription: "Naiki Kai Safeer profiles inspiring Muslims who served communities through charity, education, and reform, offering timeless Urdu lessons for all ages."
  },
  {
    slug: "namaz-aur-modern-medical-science",
    description: `Namaz aur Modern Medical Science presents a unique interdisciplinary examination that bridges Islamic worship practices with contemporary medical and physiological research. The book systematically analyses each physical movement and posture of the five daily prayers, including standing, bowing, prostration, and sitting, correlating these actions with their documented effects on the human musculoskeletal system, cardiovascular health, respiratory function, and mental wellbeing. Drawing upon peer-reviewed medical studies, anatomical research, and physiological data, the author demonstrates how the regular performance of Salah engages multiple muscle groups, promotes joint flexibility, improves blood circulation, and contributes to spinal health. The section on prostration or Sujud is particularly detailed, examining how the position affects cerebral blood flow, the drainage of the paranasal sinuses, and the regulation of the autonomic nervous system. The book also addresses the psychological and neurological benefits of prayer, including the effects of rhythmic recitation on stress reduction, the impact of regular spiritual practice on cortisol levels, and the relationship between meditative worship and emotional resilience. Beyond the physical postures, the book discusses the medical implications of Wudu, the timing of prayers relative to circadian rhythms, the health benefits of fasting-related practices, and the impact of the pre-dawn routine on metabolism and sleep quality. Each chapter presents medical evidence alongside relevant Islamic texts, creating a dual perspective that appeals to both health-conscious readers and those seeking to deepen their understanding of the wisdom embedded in Islamic rituals. The author maintains scientific objectivity throughout, clearly distinguishing between established medical findings and areas where further research is needed. References to specific studies, journals, and medical institutions are provided for readers who wish to investigate the source material independently. This book is particularly valuable for Muslim healthcare professionals, medical students, and educated readers who wish to understand how the practice of Salah aligns with and supports principles of physical and mental health established by modern science.`,
    metaDescription: "Namaz aur Modern Medical Science examines how Salah postures align with modern research on physical health, circulation, and mental wellbeing."
  },
  {
    slug: "namaz-ba-jamaat-se-peechay-rhnay-waly",
    description: `Namaz Ba Jamaat se Pechay Rhnay Waly is an Urdu-language religious text that addresses the serious topic of Muslims who habitually delay or neglect congregational prayer despite having the ability to attend. The book takes its subject from the well-established Islamic principle that praying in congregation carries significantly greater reward than praying individually, and that the consistent neglect of Jamaat prayer by those who are able to participate is considered a blameworthy practice in the Shariah. The author structures the book around three main pillars: first, a thorough presentation of the evidences from the Quran and authentic hadith that emphasise the importance of congregational prayer; second, a detailed discussion of the rulings issued by classical and contemporary scholars regarding the obligation of Jamaat for men; and third, a compassionate yet firm set of recommendations for individuals who struggle with this aspect of their religious practice. The hadith references include the well-known narration in which the Prophet Muhammad, peace be upon him, considered burning the houses of those who did not attend congregational prayer, as well as multiple traditions describing the twenty-five or twenty-seven times greater reward for praying in Jamaat. The book does not merely present warnings but also explores the common reasons why people fall into the habit of missing congregational prayers, including laziness, preoccupation with work, social anxiety, and a lack of understanding of the spiritual significance of the Jamaat. For each barrier identified, the author offers practical suggestions and spiritual remedies grounded in Islamic teaching. The writing style is direct and persuasive without being harsh, appealing to the reader's sense of religious duty while acknowledging the genuine challenges of modern life. A dedicated chapter discusses the communal consequences of weakened congregational prayer, including its effects on community cohesion, the spiritual atmosphere of the neighbourhood, and the upbringing of children who observe their parents' prayer habits. This book is recommended for imams, community leaders, and any Muslim who wishes to strengthen their commitment to congregational worship.`,
    metaDescription: "Namaz Ba Jamaat se Pechay Rhnay Waly discusses the importance of congregational prayer in Urdu, addressing barriers with Quranic and hadith evidence."
  },
  {
    slug: "namaz-e-muhammadi-12x17",
    description: `Namaz e Muhammadi in the 12x17 format is a detailed and authoritative guide to the method of prayer as directly taught and practised by the Prophet Muhammad, peace be upon him. This edition, produced in a generous 12 by 17 inch size, offers enhanced readability that makes it particularly suitable for use in mosques, madrasah classrooms, and group study settings where multiple readers may need to view the text simultaneously. The book meticulously documents every aspect of the Prophetic prayer, from the opening Takbir to the final Salam, covering the precise wording of each recitation, the correct physical postures, the recommended supplications, and the sunnah actions that complete the prayer. Unlike abbreviated prayer guides that provide only the essential components, this comprehensive volume distinguishes clearly between the obligatory acts of prayer, the sunnah muakkadah or emphasised recommended acts, and the mustahabb or desirable acts, giving readers a thorough understanding of what constitutes a complete and perfected prayer. The Arabic text for all recitations is presented in a large, clear font with full vowel marks, accompanied by transliteration and Urdu translation that together make the content accessible to readers at various levels of Arabic proficiency. The postures of prayer are described with precise anatomical detail, specifying the placement of hands, the angle of bowing, the positioning of the forehead during prostration, and the arrangement of the feet during sitting. Extensive footnotes and marginal commentary address common questions and resolve differences of opinion between schools of thought by prioritising the evidences from authentic hadith. The book also includes chapters on the spiritual dimensions of prayer, discussing concepts such as khushu and khudhu, concentration, and the presence of heart during worship. Tables and charts summarise the structure of each of the five daily prayers, showing the number of rakat, the recitations for each position, and the variations between different prayer times. The sturdy construction of this 12x17 edition ensures durability through frequent handling in institutional settings. Scholars, teachers, and serious students of Islamic prayer will find this to be an indispensable reference work.`,
    metaDescription: "Namaz e Muhammadi 12x17 is a large-format Urdu guide to the Prophet's prayer method with Arabic text, transliteration, and commentary."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
