const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "zakkah-according-to-quran-and-sunnah",
    description: `Zakkah According to Quran and Sunnah is a meticulously researched English-language work that presents the complete system of Islamic obligatory charity as it is derived directly from the two primary sources of Islamic law — the Quran and the authentic Sunnah of the Prophet Muhammad (peace be upon him). Unlike many contemporary books on zakat that rely heavily on later juristic interpretations or regional customs, this work traces every ruling back to its scriptural and prophetic roots, providing the reader with a clear, source-based understanding that transcends sectarian and cultural boundaries.

The book is methodically organized, beginning with the theological foundations of zakat. The opening chapters explore the Quranic verses that establish zakat as a pillar of Islam, examining the language and context of key ayat in Surah Al-Baqarah, Surah At-Tawbah, and other surahs. The author provides word-by-word analysis of critical terms such as "sadaqah," "zakat," and "haqq," showing how the Quran uses these terms with specific legal connotations. The relationship between zakat and salat (prayer) is examined across multiple verses, demonstrating that the Quran consistently presents these two pillars as inseparable components of genuine faith.

The Sunnah section draws upon the major hadith collections to elaborate on the practical implementation of zakat during the Prophet's lifetime. Detailed narrations about the zakat on different categories of wealth — gold and silver, livestock (camels, cattle, sheep, and goats), agricultural produce, and trade goods — are presented with their full chains of narration and assessments by hadith scholars. The famous hadith of the Prophet sending Muadh ibn Jabal to Yemen, where he instructed him to take zakat from the wealthy and distribute it to the poor, is analyzed as a foundational text for understanding the governmental role in zakat collection and distribution.

A substantial portion of the book is devoted to the eight categories of zakat recipients enumerated in Surah At-Tawbah, verse 60. Each category — the poor, the needy, zakat administrators, those whose hearts are to be reconciled, those in bondage, those in debt, those fighting in Allah's cause, and wayfarers — is discussed in detail, with classical and contemporary scholarly opinions on how these categories apply in the modern world. The book addresses contemporary questions such as whether zakat can be used to fund Islamic schools, hospitals, dawah organizations, and community infrastructure, providing balanced, evidence-based answers.

The calculation section includes practical worksheets and examples covering common modern scenarios: zakat on bank savings, shares and mutual funds, rental properties, business inventory, retirement accounts, and cryptocurrency holdings. The appendices include conversion tables for gold and silver weights, a zakat calculation checklist, and a glossary of Arabic terms. Throughout the book, the author maintains a tone of scholarly humility, acknowledging areas where legitimate scholarly disagreement exists while clearly stating his preferred position and its evidentiary basis. This work serves as both a practical handbook and an academic reference, suitable for individual Muslims, imams, zakat committee members, and students of Islamic studies.`,
    metaDescription: "Zakkah According to Quran and Sunnah provides source-based Islamic charity rulings covering calculations, recipients, and modern applications in English."
  },
  {
    slug: "zalim-badshah-qissa-syedna-haroon-silsila-qasas-ul-anbiya-2230",
    description: `Zalim Badshah — "The Cruel King" — is the twenty-second installment in the celebrated Silsila Qasas ul Anbiya (Series of Prophetic Stories), a thirty-volume Urdu collection that brings the stories of the prophets to life through engaging, child-friendly narrative while remaining faithful to authentic Islamic sources. This particular volume focuses on the life and mission of Prophet Haroon (Aaron, peace be upon him), the brother of Prophet Musa (Moses), and his confrontation with a tyrannical ruler whose cruelty and injustice tested the faith and resolve of the Children of Israel.

The story is set against the backdrop of one of the most dramatic periods in prophetic history. While Prophet Musa had departed to receive the Torah on Mount Sinai, he left Prophet Haroon in charge of his people — a responsibility of immense trust. During this critical period, the Israelites faced the temptation of the Samiri, who led many of them astray into worshipping the golden calf. Prophet Haroon's response to this crisis — his attempts at gentle persuasion, his refusal to use force against his own people, and his unwavering commitment to the message of tawhid (monotheism) — forms the emotional and moral core of this volume.

The narrative skillfully contrasts the character of the zalim badshah (cruel king) — whether representing Pharaoh's lingering influence or the internal tyranny that the Israelites imposed upon themselves through disobedience — with the patience, wisdom, and steadfastness of Prophet Haroon. Children reading this book will learn important lessons about the difference between true leadership, which is based on service and guidance, and tyrannical rule, which is based on coercion and self-interest. The book shows how Prophet Haroon, despite facing enormous pressure, chose the path of wisdom and maintained his loyalty to both Allah and his brother Musa.

As with all volumes in the Silsila Qasas ul Anbiya series, the storytelling is vivid and age-appropriate, using simple yet expressive Urdu that captivates young readers without oversimplifying the theological messages. Illustrations complement the text, helping children visualize the historical setting while maintaining respect for prophetic dignity. Each chapter ends with a brief moral reflection that connects the events of the story to everyday values such as honesty, patience, trust in Allah, and the importance of brotherhood. Parents and teachers will find this volume an effective tool for introducing children to the rich heritage of prophetic history while reinforcing positive character traits.`,
    metaDescription: "Zalim Badshah from Silsila Qasas ul Anbiya tells the story of Prophet Haroon's courage and wisdom facing tyranny, part 22 of 30 Urdu children's series."
  },
  {
    slug: "zalim-bhai-qissa-syedna-yusuf-silsila-qasas-ul-anbiya-1130",
    description: `Zalim Bhai — "The Cruel Brother" — is the eleventh volume in the thirty-part Silsila Qasas ul Anbiya series, dedicated to telling the story of Prophet Yusuf (Joseph, peace be upon him) through a lens that focuses on the betrayal and jealousy of his brothers. The story of Prophet Yusuf is one of the most detailed and emotionally powerful narratives in the Quran, occupying an entire surah (Surah Yusuf), and this volume distills its essential lessons into an accessible, moving account for young Urdu-speaking readers.

The book opens with the family dynamics that set the stage for the central conflict. Prophet Yaqub's (Jacob's) deep love for his youngest son Yusuf and the special dream that Yusuf narrates to his father create an atmosphere of tension with his older brothers. The narrative handles the brothers' jealousy with psychological nuance, showing how envy can grow from a small seed of resentment into an act of extreme cruelty — throwing their own brother into a well and then lying to their father about his fate. Children reading this story will recognize the destructive power of jealousy and the importance of controlling negative emotions before they lead to harmful actions.

The subsequent chapters follow Prophet Yusuf's remarkable journey — from the darkness of the well to the household of the Aziz of Egypt, from the false accusation that lands him in prison to his eventual elevation as the minister of finance. Through every trial, Yusuf's faith in Allah remains unshakeable, and his patience under adversity becomes a recurring theme that the book emphasizes at every turn. The narrative reaches its emotional climax when the brothers, now suffering from famine, come to Egypt seeking grain and unknowingly stand before the very brother they wronged years ago.

What makes this volume particularly valuable for young readers is its focus on forgiveness and reconciliation. When Prophet Yusuf finally reveals his identity, he does not seek revenge. Instead, he says the famous words recorded in the Quran: "No blame will there be upon you today. Allah will forgive you, and He is the most merciful of the merciful." This powerful demonstration of prophetic forgiveness provides children with a profound moral lesson about the superiority of pardon over vengeance. The Urdu prose is rhythmic and engaging, with age-appropriate vocabulary that builds language skills while conveying deep spiritual truths. Illustrations bring key scenes to life, and the chapter-end reflections encourage children to think about how the lessons of the story apply to their own relationships with siblings, friends, and classmates.`,
    metaDescription: "Zalim Bhai from Silsila Qasas ul Anbiya narrates Prophet Yusuf's story of betrayal, patience, and forgiveness in Urdu for young readers, part 11 of 30."
  },
  {
    slug: "zalim-malika-qissa-syedna-yahya-silsila-qasas-ul-anbiya-2830",
    description: `Zalim Malika — "The Cruel Queen" — is the twenty-eighth volume in the Silsila Qasas ul Anbiya series, bringing to young Urdu-speaking readers the powerful and poignant story of Prophet Yahya (John the Baptist, peace be upon him) and his martyrdom at the hands of a cruel and misguided queen. This installment tackles one of the more challenging narratives in prophetic history with sensitivity, clarity, and a focus on the enduring moral and spiritual lessons that children can derive from it.

The story of Prophet Yahya is intertwined with the complex political and moral landscape of his time. He was born to Prophet Zakariya (Zechariah, peace be upon him) in response to a heartfelt supplication — a miraculous birth in old age that itself carries powerful lessons about the power of dua and Allah's ability to grant the impossible. From his earliest years, Yahya was marked by wisdom, piety, and an unwavering commitment to speaking the truth, qualities that the Quran highlights when it describes him as having been given wisdom while still a child.

The central conflict of this volume revolves around the zalim malika (cruel queen) — a figure of authority who becomes enraged when Prophet Yahya courageously speaks out against an unjust and immoral decree. Rather than remaining silent in the face of wrongdoing, Yahya chooses to uphold the command of Allah, even knowing the severe consequences that would follow. His refusal to compromise his principles, even under the threat of death, demonstrates a level of courage and conviction that serves as an inspirational model for readers of all ages.

The book handles the martyrdom of Prophet Yahya with appropriate sensitivity for its young audience. The emphasis is not on the violence of the event but on the spiritual significance of a life lived in complete devotion to Allah and the eternal reward promised to those who stand firm in truth. The narrative draws parallels between Prophet Yahya's willingness to speak truth to power and the responsibility that every Muslim has to enjoin good and forbid evil, regardless of the personal cost.

As with all volumes in this series, the Urdu text is crafted for readability and engagement, with a vocabulary that challenges young readers without overwhelming them. The illustrations maintain the series' standard of dignity and respect, depicting historical settings and key scenes in a style that is both attractive and appropriate. Parents and educators will appreciate the discussion prompts included at the end of each chapter, which encourage children to reflect on questions such as: What does it mean to be truly brave? Is it ever right to stay silent when you see something wrong? How do we trust Allah when doing the right thing seems dangerous? This volume is a powerful addition to any child's Islamic library.`,
    metaDescription: "Zalim Malika from Silsila Qasas ul Anbiya tells Prophet Yahya's courageous stand for truth against a cruel queen, part 28 of 30 Urdu children's series."
  },
  {
    slug: "zam-zam-5-litter-without-packing",
    description: `Zamzam water in a five-liter bulk container represents one of the most meaningful and spiritually significant products available to Muslims worldwide. Drawn from the sacred well of Zamzam, located within the Masjid al-Haram in Makkah, Saudi Arabia — just meters from the Kaaba — this water carries a heritage that stretches back thousands of years to the time of Prophet Ibrahim (Abraham, peace be upon him) and his wife Hajar. The story of Zamzam's origin, as recounted in the Quran and authenticated hadith, is one of divine mercy: when Hajar was left in the barren desert with her infant son Prophet Ismail, the angel Jibril struck the ground and a spring of water gushed forth, saving their lives and establishing a well that has never run dry since.

This five-liter offering is specifically designed for those who need a larger quantity of Zamzam for regular use. Unlike single-serving bottles meant for occasional sipping, this bulk size is ideal for families who incorporate Zamzam into their daily routines — whether for drinking, for using in cooking, for sharing with guests, or for keeping a supply at home throughout the year. The "without packing" designation indicates a focus on the essential product itself, offering the water in a straightforward container that prioritizes the purity and authenticity of the contents over elaborate packaging.

The significance of Zamzam water extends far beyond its physical properties. The Prophet Muhammad (peace be upon him) described Zamzam as "blessed" and said it serves whatever purpose it is consumed for. In Islamic tradition, Zamzam is considered the best water on Earth, and numerous hadith attest to its spiritual and physical benefits. It is commonly consumed by pilgrims during Hajj and Umrah, brought home as a gift for family and friends, and used in various religious and cultural contexts. Many Muslims use Zamzam water when breaking their fast, during illness, before important life events, and when seeking spiritual closeness to Allah through du'a.

From a practical standpoint, this five-liter container provides several months' supply for a typical household, depending on usage patterns. The water is valued for its distinctive mineral composition, which has been the subject of scientific studies noting its unique balance of calcium, magnesium, and other minerals. Storing Zamzam in a clean, cool place preserves its quality and ensures that it remains a source of blessing for the household. Whether used daily for drinking and cooking or reserved for special occasions, this five-liter Zamzam water brings the spiritual essence of the Haram into the home, serving as a tangible connection to the holiest site in Islam.`,
    metaDescription: "Five-liter bulk Zamzam water from the sacred well in Makkah, ideal for family use, cooking, and daily spiritual routines. Authentic and untreated."
  },
  {
    slug: "zameen-ki-pakar-qissa-syedna-musa-silsila-qasas-ul-anbiya-2030",
    description: `Zameen Ki Pakar — "Grip of the Earth" — is the twentieth volume in the Silsila Qasas ul Anbiya series, focusing on a pivotal episode from the life of Prophet Musa (Moses, peace be upon him). This installment captures one of the most dramatic confrontations in prophetic history: the encounter between Prophet Musa and Pharaoh's court magicians, a moment that tested the limits of human courage and demonstrated the supreme power of Allah over all forms of deception and sorcery.

The title "Zameen Ki Pakar" evokes the image of the ground swallowing those who defied divine truth, a powerful visual that children can readily imagine and that serves as a metaphor for the inescapable consequences of arrogance and falsehood. The narrative begins by setting the stage: Pharaoh, consumed by his own delusion of divinity, summons the most skilled magicians of Egypt to counter the miracles of Prophet Musa. The magicians, confident in their craft, throw their ropes and staffs to create an illusion of serpents — a display so convincing that it overwhelms the onlookers. But when Prophet Musa throws down his staff at Allah's command, it transforms into a genuine serpent that swallows every illusory one.

What follows is the most emotionally charged moment of the story. The magicians, who are experts in trickery and illusion, immediately recognize that what they have witnessed is not magic but a genuine divine miracle. In an act of extraordinary courage, they fall into prostration before Allah, declaring their faith in the Lord of Musa and Haroon — even as Pharaoh threatens them with the most horrific punishment: amputation of their hands and feet from opposite sides and crucifixion. Their response, as recorded in the Quran, is one of the most powerful statements of conviction in all of scripture: they declare that they will return to their Lord and have no concern for Pharaoh's threats.

This volume uses the dramatic tension of the confrontation to teach children several important lessons. The first is the distinction between truth and illusion — the magicians themselves, as masters of deception, are the first to recognize genuine divine power. The second is the courage to stand for truth even when the consequences are severe. The third is the Islamic teaching that when a person sincerely turns to Allah, the threats of tyrants lose their power. The book also subtly introduces the concept that true knowledge — even the knowledge of magic — ultimately leads the sincere seeker toward recognition of the Creator.

The Urdu narration is crafted to maintain suspense and emotional engagement while ensuring that the theological message remains clear and central. Illustrations depict the key moments of the confrontation — the throwing of the staffs, the prostration of the magicians, the fury of Pharaoh — in a style that captures the drama without being frightening for young readers. Chapter-end discussions encourage children to think about situations in their own lives where they might need to choose between popular opinion and what they know to be right.`,
    metaDescription: "Zameen Ki Pakar from Silsila Qasas ul Anbiya recounts Prophet Musa's miracle against Pharaoh's magicians in Urdu, part 20 of the 30-volume series."
  },
  {
    slug: "zameen-per-pehla-qadam-qissa-syedna-adam-silsila-qasas-ul-anbiya-130",
    description: `Zameen Per Pehla Qadam — "First Step on Earth" — is the opening volume of the thirty-part Silsila Qasas ul Anbiya series, and it begins at the very beginning of human history with the story of Prophet Adam (peace be upon him). As the first installment in this comprehensive collection of prophetic stories, this book sets the tone for the entire series by introducing young readers to the fundamental Islamic narrative of creation, the origin of humanity, and the beginning of the relationship between Allah and mankind.

The book opens with the creation of Prophet Adam — how Allah fashioned him from clay and breathed His spirit into him, elevating him above the angels and granting him the unique honor of being khalifah (steward) on Earth. The famous scene of Allah teaching Adam the names of all things — a knowledge that the angels did not possess — is beautifully narrated, showing children that knowledge and learning have always been central to humanity's purpose. This scene also introduces the concept of respect: when Allah commanded the angels to prostrate before Adam in recognition of this honor, all obeyed except Iblis, whose refusal stemmed from arrogance and a false sense of superiority.

The story of Iblis's rebellion and his subsequent vow to mislead Adam and his descendants provides the book's central conflict. The narrative handles this with age-appropriate clarity, showing children that the enemy of mankind is not a visible monster but a subtle whisperer who exploits human weakness. When Iblis approaches Adam and Hawwa (Eve) in the Garden and whispers to them, the book emphasizes that it was not curiosity alone but a momentary lapse in remembrance of Allah's command that led to their error — and that this error was immediately followed by sincere repentance (tawbah) for which Allah forgave them.

The title "First Step on Earth" refers to the moment when Prophet Adam and Hawwa were sent down from the Garden to begin their life on Earth. The book presents this transition not as a punishment but as the beginning of a new chapter — a world where Adam and his descendants would have the opportunity to prove their devotion to Allah through their choices and actions. This framing teaches children an important lesson: life on Earth is a test, but it is also a gift, and every step we take is an opportunity to draw closer to our Creator.

The Urdu prose in this foundational volume is carefully calibrated to be accessible to the youngest readers in the series' target age group. Sentences are shorter, vocabulary is simpler, and the narrative pace is gentle. The illustrations are warm and inviting, depicting the beauty of the Garden, the majesty of the angels, and the humanity of Adam and Hawwa in a style that sparks imagination while maintaining Islamic propriety. A special introductory note for parents explains the pedagogical approach of the series and suggests ways to discuss the story's themes with children at different age levels.`,
    metaDescription: "Zameen Per Pehla Qadam begins the 30-volume Qasas ul Anbiya series with Prophet Adam's creation story in engaging Urdu for young children."
  },
  {
    slug: "zamzam-water",
    description: `Zamzam Water is a product of extraordinary spiritual and historical significance, sourced directly from the well of Zamzam located within the sacred precincts of Masjid al-Haram in Makkah al-Mukarramah. This well, which has been flowing continuously for thousands of years, holds a unique position in Islamic tradition as one of the most blessed substances on Earth. Its origin is traced to the miraculous intervention of the angel Jibril, who struck the ground at the feet of the infant Prophet Ismail to produce a spring that saved the lives of Hajar and her son in the barren desert valley — an event commemorated by the Sa'i ritual performed by every pilgrim during Hajj and Umrah.

In Islamic theology, Zamzam water occupies a status unlike any other water. The Prophet Muhammad (peace be upon him) referred to it as "blessed" and described it as satisfying both hunger and thirst. Numerous hadith narrations extol its virtues: it is described as a cure for illness, a means of seeking Allah's blessings, and a water that fulfills whatever intention the drinker has when consuming it. The Prophet himself drank Zamzam water and encouraged his companions to do the same, establishing a practice that Muslims have followed faithfully for over fourteen centuries.

The physical properties of Zamzam water have also been the subject of modern scientific interest. Research conducted by various laboratories and institutions has noted its unique mineral composition — particularly its high levels of calcium and magnesium — and its natural purity. Unlike ordinary groundwater, Zamzam contains no bacterial contamination despite being drawn from a well in a densely populated area, a fact that scientists attribute to its unique geological source and the mineral composition that acts as a natural antimicrobial agent. These scientific findings complement rather than contradict the spiritual understanding of Zamzam as a divinely blessed water.

Muslims around the world incorporate Zamzam water into numerous aspects of their daily lives. It is commonly used for drinking, particularly during Ramadan for breaking the fast, and is considered a Sunnah to drink while facing the Kaaba. Many families use Zamzam water in cooking, especially for preparing meals during special occasions such as Eid, weddings, and the welcoming of a newborn. It is also used by those seeking healing during illness, with the understanding that all cure ultimately comes from Allah and that Zamzam is a means through which He grants it. The practice of giving Zamzam water as a gift to family, friends, and neighbors — particularly those who were unable to perform Hajj or Umrah — is a cherished tradition that strengthens community bonds and shares the blessings of the sacred sites with those who have not yet visited them.

This Zamzam water product is carefully handled to maintain its purity from the source in Makkah to its final destination, ensuring that the water reaches consumers in its natural, untreated state — exactly as it flows from the well. Storing it in a clean container away from direct sunlight preserves both its quality and its barakah, making it a lasting source of spiritual connection to the House of Allah.`,
    metaDescription: "Authentic Zamzam water from the sacred well in Makkah, cherished for spiritual blessings, healing, and daily use by Muslims worldwide."
  },
  {
    slug: "zaqaat-kay-masail",
    description: `Zaqaat Kay Masail is a focused, Urdu-language treatise that addresses the practical questions and rulings related to the obligation of zakat, making it a specialized companion to broader works on Islamic worship. While several books in the Islamic literature cover zakat alongside other pillars, this volume dedicates itself entirely to the subject, allowing for a depth of treatment that general-purpose fiqh manuals cannot provide. The result is a resource that serves as both a quick-reference guide for common zakat questions and a detailed study text for those seeking a thorough understanding of the subject.

The book is structured around the most frequently asked questions that arise during zakat season — the period at the end of each Islamic lunar year when Muslims calculate and distribute their obligatory charity. These questions reflect the real-world financial complexity of modern life and cover scenarios that classical fiqh texts could not have anticipated. Among the topics addressed in detail are: the zakat on different types of bank accounts (current, savings, fixed deposits), the treatment of gold jewelry (whether zakat is due on jewelry worn regularly versus stored for investment), the calculation of zakat on shares and securities (including the distinction between trading shares and long-term investments), the zakat implications of rental income and property investments, the treatment of retirement accounts and pension funds, the zakat on cryptocurrency holdings, and the handling of business inventory and receivables.

For each question, the author provides a clear answer supported by references to relevant Quranic ayat, hadith, and authoritative Hanafi fiqh texts such as al-Hidaya, Radd al-Muhtar, and Bahr al-Ra'iq. Where multiple scholarly opinions exist within the Hanafi school — or between the Hanafi school and other schools of thought — the author notes the different positions and explains the reasoning behind each one, allowing the reader to make an informed decision in consultation with a qualified scholar.

A particularly valuable feature of this book is its treatment of common mistakes and misconceptions about zakat. The author systematically addresses errors such as the belief that zakat is only due on gold and not on silver, the assumption that zakat need not be paid on business losses, the confusion between zakat and sadaqah (voluntary charity), and the practice of paying zakat on the total value of a property rather than on the rental income it generates. Each misconception is corrected with clear evidence and practical explanation.

The book also covers the conditions that make zakat obligatory (Islam, freedom, sanity, adulthood, ownership of nisab, and the passage of a complete lunar year), the concept of nisab and how it is calculated in various currencies and asset classes, and the proper method of distributing zakat to the eight categories of recipients. A glossary of Arabic and Urdu fiqh terms is included, along with a subject index that makes it easy to locate specific topics quickly. The Urdu prose is clear, structured, and free of unnecessary digressions, making this book a practical tool that Muslims can reach for year after year during their zakat calculations.`,
    metaDescription: "Zaqaat Kay Masail is a detailed Urdu reference on zakat rulings covering bank accounts, jewelry, property, stocks, crypto, and common calculation errors."
  },
  {
    slug: "zerah-mashaq-calligraphy-board-a3-color-may-vary",
    description: `The Zerah Mashaq Calligraphy Board in A3 size is a dedicated practice tool designed for students and enthusiasts of Arabic and Islamic calligraphy who want to develop their penmanship skills through structured, repetitive exercise. The word "mashaq" itself refers to the disciplined practice that calligraphers undertake to train their hands, and this board provides the ideal surface for that essential work. Measuring A3 (approximately 297 by 420 millimeters), the board offers a generous work area that accommodates full words, phrases, and even complete lines of Arabic text, allowing for practice that extends beyond individual letters to connected script and compositional layout.

The surface of the board is engineered specifically for calligraphy practice. It provides a smooth, slightly resistant texture that works well with both traditional reed pens (qalam) and modern calligraphy markers. The resistance helps control ink flow and prevents the pen from sliding unpredictably, which is critical for developing the consistent stroke width variation that distinguishes good calligraphy from poor writing. Unlike paper, which can absorb ink unevenly and degrade after repeated erasing, this board can be used repeatedly, making it an economical and environmentally friendly alternative to consuming large quantities of practice paper.

The A3 size is particularly well-suited for practicing the larger scripts used in Islamic art and design — Naskh for Quranic text, Thuluth for architectural inscriptions, Diwani for formal documents, and Ruq'ah for everyday handwriting. The larger format allows students to practice the full range of motion required by each script, from the sweeping curves of Thuluth to the compact letterforms of Ruq'ah. For those studying henna-style decorative calligraphy or the ornate styles used in mosque decoration, the board provides adequate space for practicing decorative elements alongside the core letterforms.

Calligraphy holds a special place in Islamic civilization as both an art form and a spiritual practice. The Prophet Muhammad (peace be upon him) is reported to have said that one who writes beautifully the name of Allah and the Quran will be among the companions of the righteous scribes. This spiritual dimension elevates calligraphy practice from a mere craft to an act of worship, and the Zerah Mashaq board serves as a practical instrument for those who approach their art with this understanding. The board is lightweight and portable, making it easy to carry to classes, workshops, or any space where practice takes place. Please note that the color of the board may vary, as it is produced in different color options — each offering the same high-quality practice surface regardless of the exterior appearance. Whether you are a beginner taking your first steps in Arabic calligraphy or an experienced artist maintaining your daily practice routine, this board provides a reliable and durable foundation for your artistic development.`,
    metaDescription: "A3-size Zerah Mashaq calligraphy board for Arabic and Islamic script practice, featuring a durable reusable surface suitable for qalam and markers."
  }
];

async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: {
        description: item.description,
        metaDescription: item.metaDescription
      }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}

main().then(() => prisma.$disconnect());
