const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "supplication-and-treatment-with-ruqya",
    description: `Ruqya, the Islamic practice of spiritual healing through prescribed supplications and Quranic recitations, occupies a well-defined place within the broader framework of Muslim medicine and theology. This English-language book provides a structured, evidence-based examination of how the Prophet Muhammad (peace be upon him) and his companions approached ailments that were understood to originate from harmful spiritual forces, including the evil eye, envy, and malevolent unseen influences. Rather than presenting ruqya as folklore or superstition, the author grounds every recommendation in authentic hadith literature and established scholarly consensus, making it a reliable reference for Muslims who wish to understand this subject correctly.

The text is organized into clear thematic sections that address the nature of spiritual affliction as described in the Quran and Sunnah, the specific verses and supplications recommended for protection and cure, and the conditions under which ruqya is considered valid and effective. A significant portion of the book is devoted to differentiating between legitimate Islamic ruqya and practices that have crept into Muslim communities from pre-Islamic traditions or cultural superstitions. This distinction is critical, as many Muslims unknowingly engage in procedures that violate Islamic principles while believing they are following prophetic guidance. The book addresses common misconceptions head-on, providing readers with the knowledge needed to avoid blameworthy innovations.

Practical application is another strength of this work. Readers will find step-by-step guidance on performing ruqya for themselves and their family members, the proper etiquette of seeking treatment, and the role of patience and reliance upon Allah throughout the healing process. The book also discusses when medical treatment should be sought alongside spiritual remedies, reflecting the balanced Islamic position that does not oppose physical medicine but complements it with supplication. For anyone seeking a thorough, scholarly, and practical guide to this important aspect of Islamic practice, this volume serves as an indispensable resource that bridges the gap between academic rigor and everyday usability.`,
    metaDescription: "An English guide to Islamic spiritual healing through Ruqya, covering authentic Quranic supplications, evil eye protection, and proper healing practices."
  },
  {
    slug: "surah-yaseen",
    description: `Surah Yaseen, the thirty-sixth chapter of the Holy Quran, holds a uniquely revered position in the hearts of Muslims across the world. Often referred to as the heart of the Quran, this surah is recited in moments of difficulty, during times of illness, at funerals, and in daily devotional gatherings. This edition presents the complete Arabic text of Surah Yaseen in a format designed for ease of reading and regular recitation, making it accessible to readers of all ages and levels of Quranic proficiency.

The spiritual significance of Surah Yaseen is well documented in the hadith literature, where the Prophet Muhammad (peace be upon him) emphasized its merits on multiple occasions. The surah covers profound theological themes including the oneness of Allah, the truth of prophethood, the reality of resurrection and judgment, and the consequences faced by communities that rejected their messengers. Through vivid parables and powerful rhetorical questions, it addresses both the intellect and the heart, compelling the reader to reflect on the purpose of existence and the certainty of the afterlife. The narrative of the believers who visited a city and the account of the man who came from the farthest part of the city urging his people to follow the messengers are among the most compelling passages in the entire Quran.

This publication is particularly suited for those who wish to keep a dedicated copy of Surah Yaseen for daily recitation or for distribution as a gift on special occasions. The clear Arabic typography ensures that each letter and diacritical mark is legible, which is essential for correct pronunciation. Many Muslims maintain a habit of reciting Surah Yaseen each morning, and this compact volume makes that practice convenient whether at home, during travel, or at the workplace. The durable binding and quality paper ensure that the text remains in good condition through repeated use over an extended period.`,
    metaDescription: "A clear Arabic edition of Surah Yaseen, the heart of the Quran, designed for daily recitation with legible typography and durable binding for regular use."
  },
  {
    slug: "surah-yaseen-urdu-english",
    description: `This bilingual edition of Surah Yaseen brings together the original Arabic text with parallel Urdu and English translations, making the profound meanings of this cherished surah accessible to a significantly wider readership. Surah Yaseen is universally recognized as one of the most frequently recited chapters of the Quran, and its messages regarding divine oneness, prophetic truth, resurrection, and moral accountability resonate deeply with Muslims regardless of their linguistic background. By presenting the translation in both Urdu and English, this edition serves households and communities where multiple languages are spoken and understood.

The Urdu translation has been composed in a style that balances faithfulness to the Arabic original with clarity and natural flow, allowing readers whose first language is Urdu to grasp the full meaning without constant reference to explanatory notes. Similarly, the English translation is written in contemporary, straightforward language that avoids overly technical terminology while preserving the theological precision required for accurate Quranic interpretation. This dual-language approach means that families can study the surah together, with each member reading in the language they find most comfortable, and then discussing the meanings collectively.

The layout has been carefully designed so that corresponding portions of the Arabic text, Urdu translation, and English translation appear together on each page or in closely aligned sections. This structure facilitates cross-referencing and helps readers who are learning one of the languages to improve their comprehension by comparing it against the text they already know. The volume is especially useful in South Asian Muslim communities living in English-speaking countries, where both Urdu and English are commonly spoken. Educational institutions, madrasahs, and Islamic study circles will find this edition to be a practical teaching tool. Whether used for personal study, group discussion, or as a gift for someone embarking on their Quranic learning journey, this trilingual presentation of Surah Yaseen fills an important niche in Islamic publishing.`,
    metaDescription: "Bilingual Urdu and English translation of Surah Yaseen alongside Arabic text, for families and study circles in multilingual Muslim communities."
  },
  {
    slug: "surahs-to-seek-refuge",
    description: `The Quran prescribes specific chapters for seeking protection from various forms of harm, and this English-language book provides a comprehensive study of those surahs, with particular focus on Surah Al-Falaq and Surah An-Nas. These two chapters, collectively known as Al-Mu'awwidhatayn or the two verses of seeking refuge, were revealed to the Prophet Muhammad (peace be upon him) during a period when he was affected by sorcery cast by a Jewish individual in Medina. The events surrounding their revelation give these surahs a practical urgency that extends far beyond their relatively brief length.

The book examines each verse of Surah Al-Falaq and Surah An-Nas in detail, drawing upon classical tafseer works to explain the linguistic nuances and theological implications of every word. Surah Al-Falaq teaches the believer to seek refuge in the Lord of daybreak from four categories of harm: the evil of created things, the darkness of night, those who practice sorcery, and the envy of the envious. Surah An-Nas extends this protection by directing the believer to seek refuge in the Lord of mankind, the King of mankind, and the God of mankind from the whispers of the retreating devil who targets human hearts. The author systematically analyzes each of these categories, providing readers with a deep understanding of what types of harm are being addressed and how the Quranic prescription serves as both a literal supplication and a conceptual framework for spiritual vigilance.

Beyond these two surahs, the book also addresses the broader Quranic and prophetic guidance on seeking refuge, including Ayatul Kursi, the last two verses of Surah Al-Baqarah, and various supplications recorded in the authentic hadith collections. The discussion extends to the proper methodology of reciting these verses, the recommended times and circumstances for seeking refuge, and the Islamic position on using amulets, talismans, and other protective objects. This makes the book a thorough reference for understanding the Quranic approach to spiritual protection.`,
    metaDescription: "An in-depth English study of Surah Al-Falaq and Surah An-Nas, explaining Quranic guidance on seeking refuge from harm, sorcery, and the evil eye."
  },
  {
    slug: "suraj-kahaani",
    description: `Suraj Kahaani, which translates to The Sun Story, is a uniquely titled Urdu book that draws its inspiration from the Quranic narrative concerning the Prophet Dhul-Qarnayn and his journey to the place where the sun sets, as described in Surah Al-Kahf. This narrative has fascinated Quranic scholars and Muslim thinkers for centuries, raising questions about geography, cosmology, divine power, and the limits of human knowledge that remain relevant to contemporary discussions about faith and science. The author approaches this subject with a literary sensibility that makes complex theological concepts accessible to the general Urdu reader.

The book situates the Quranic account within its proper context by first examining what classical commentators, including Ibn Kathir, Al-Tabari, and Al-Qurtubi, understood about the story of Dhul-Qarnayn. Each major element of the narrative is discussed separately: the identity of Dhul-Qarnayn himself, the nature of his three journeys described in the Quran, the people he encountered, and the wall he built between two mountains to protect a community from Gog and Magog. The author does not shy away from addressing the various scholarly opinions regarding these matters, presenting the strongest arguments for each position while guiding the reader toward the most textually sound interpretations.

What distinguishes this work is its ability to connect the ancient Quranic narrative to the lived experience of modern Muslims. The author draws moral and spiritual lessons from each episode in Dhul-Qarnayn's story, discussing themes such as the proper use of power and authority, the importance of knowledge in leadership, the responsibility to protect the vulnerable, and the reality that all worldly power is subordinate to divine will. The Urdu prose is engaging and clear, avoiding overly academic language while maintaining scholarly accuracy. For Urdu readers interested in Quranic stories, this book offers a thoughtful and thorough treatment of one of the most mysterious and frequently discussed narratives in the entire Quran.`,
    metaDescription: "An Urdu book exploring the Quranic story of Dhul-Qarnayn and the sun from Surah Al-Kahf, combining classical commentary with spiritual and moral lessons."
  },
  {
    slug: "surat-al-arz",
    description: `Surat Al-Arz, meaning The Chapter of the Earth, is a thematic study that examines the extensive references to the earth and natural phenomena found throughout the Quran. The Quran repeatedly directs human attention to the natural world as a sign of the Creator's existence, wisdom, and power, and this book systematically catalogs and analyzes those references to build a comprehensive picture of what the Quran teaches about the physical world. From the structure of mountains and the flow of rivers to the alternation of night and day and the formation of clouds, the Quran contains remarkable descriptions of natural processes that continue to inspire scientific and theological reflection.

The author organizes the discussion into topical chapters, each addressing a different aspect of the earth as described in Quranic revelation. One section examines the Quranic portrayal of mountains as pegs and stabilizers for the earth, drawing connections to modern geological understanding of mountain formation and tectonic activity. Another section explores the Quranic descriptions of the water cycle, including evaporation, cloud formation, and rainfall, comparing these ancient descriptions to contemporary meteorological science. The discussion of the earth's expanding nature, the layered structure of the atmosphere, and the protective role of the sky are all addressed with reference to both classical tafseer and modern scientific research.

Beyond the scientific dimensions, the book also addresses the theological and ethical implications of the Quranic view of the earth. The Quran presents the natural world not merely as a backdrop for human existence but as an active participant in the worship of Allah, with everything in creation engaged in praise and glorification. This perspective has profound implications for how Muslims should relate to the environment, approaching natural resources as a trust from Allah rather than an unlimited commodity for exploitation. The book challenges readers to develop a Quranically informed environmental consciousness that balances human needs with responsible stewardship. For anyone interested in the relationship between Quranic revelation and the natural sciences, this work provides a well-researched and thoughtfully presented study.`,
    metaDescription: "A thematic study of the earth and natural phenomena in the Quran, connecting scriptural descriptions with modern science and environmental ethics."
  },
  {
    slug: "syedina-abdullah-bin-abbas-ra",
    description: `Abdullah bin Abbas, the cousin of the Prophet Muhammad (peace be upon him), is universally regarded as one of the most learned companions of the Messenger of Allah. His mastery of Quranic interpretation, Islamic jurisprudence, and the Prophet's sayings and practices earned him the title of Tarjuman al-Quran, the Translator of the Quran. This biography chronicles his remarkable life from his earliest years in the household of the Prophet, through the turbulent period of the rightly guided caliphs, to his later years as the most respected scholar of his generation.

The book begins with the circumstances of Abdullah bin Abbas's birth and his unique childhood in close proximity to the Prophet. Despite his young age during the Prophet's lifetime, Abdullah was known for his acute intelligence and his habit of seeking knowledge with extraordinary dedication. He would wait at the doors of the Prophet's companions, asking them about every saying and action of the Messenger he had witnessed. This tireless pursuit of knowledge laid the foundation for his future eminence as a scholar. The biography provides numerous accounts from authentic sources that illustrate his character, his humility despite his vast knowledge, and his commitment to accurate transmission of religious information.

A significant portion of the book is devoted to Abdullah bin Abbas's contributions to Quranic exegesis. His tafseer, preserved through his students and referenced extensively in the major classical commentary works, represents some of the earliest and most authoritative interpretation of Quranic verses. The author examines specific examples of his exegetical method, showing how he combined linguistic analysis with contextual understanding and knowledge of the circumstances of revelation. His juridical opinions and his role in advising the caliphs are also discussed in detail. The biography does not avoid the complex political landscape of his era, including his relationship with Ali bin Abi Talib during the fitnah and his later withdrawal from active politics to focus on teaching. This comprehensive portrait of one of Islam's greatest scholars provides readers with both historical knowledge and inspirational lessons in the pursuit of sacred knowledge.`,
    metaDescription: "A biography of Abdullah bin Abbas (R.A), the companion known as Tarjuman al-Quran, covering his scholarship, tafseer contributions, and lasting legacy."
  },
  {
    slug: "syedina-usman-bin-affan-ki-zindagi-k-sunehray-waqiyat",
    description: `Syedina Usman bin Affan ki Zindagi ke Sunehray Waqiyat, meaning The Golden Events from the Life of Usman bin Affan, is a Urdu-language collection of incidents and anecdotes from the life of the third rightly guided caliph. Rather than presenting a conventional chronological biography, this book focuses on specific events and moments that illuminate the character, piety, generosity, and leadership qualities of one of the ten companions promised paradise. Each narrative has been selected for its ability to convey a moral lesson or to provide insight into the personality of a man whose caliphate shaped the course of Islamic history.

The book opens with Usman's early life in Mecca, his conversion to Islam at the hands of Abu Bakr al-Siddiq, and his two marriages to two daughters of the Prophet Muhammad (peace be upon him), which earned him the title Dhun-Nurayn, the Possessor of Two Lights. These early chapters establish the foundation of his deep personal connection to the Prophet and his family. The narratives then move through the Meccan period, describing the hardships Usman endured for the sake of Islam, including the migration to Abyssinia and his participation in key battles.

The most extensive section of the book covers Usman's caliphate and the monumental achievements that occurred during his twelve years of leadership. His standardization of the written text of the Quran into a single authoritative mushaf is discussed as one of the most significant contributions to Islamic civilization, preserving the exact wording of divine revelation for all subsequent generations. The book also details his legendary generosity, including the funding of military expeditions, his sponsorship of the expansion of the Prophet's Mosque in Medina, and his habitual charity that continued even during the financial difficulties that marked the later years of his life. The events surrounding the fitnah and his martyrdom are treated with appropriate gravity and historical accuracy. Written in accessible Urdu prose, this collection brings the golden moments of Usman's life to vivid reality for readers of all backgrounds.`,
    metaDescription: "A Urdu collection of golden events from the life of Caliph Usman bin Affan (R.A), highlighting his piety, generosity, and the standardization of the Quran."
  },
  {
    slug: "syedna-sohail-bin-amar-ra",
    description: `Sohail bin Amar was a companion of the Prophet Muhammad (peace be upon him) whose life story encapsulates some of the most transformative moments in early Islamic history. Before his conversion to Islam, Sohail was one of the prominent leaders of the Quraysh tribe in Mecca, known for his eloquence, intelligence, and firm opposition to the Muslim community. His name appears most notably in the context of the Treaty of Hudaybiyyah, where he served as the chief negotiator for the Quraysh and engaged directly with the Prophet in drafting the terms of what initially appeared to be a humiliating agreement but which the Quran itself declared a clear victory.

This biography traces Sohail's journey from his position of influence among the pagan Quraysh to his eventual embrace of Islam after the conquest of Mecca. The transformation of a man who had once been among the most determined opponents of the Prophet into a devoted Muslim companion is a powerful testament to the truth of the Islamic message and the profound changes it effected in the hearts of the early Muslims. The author draws upon authentic historical sources to reconstruct the key episodes of Sohail's life, including his role in the Battle of Badr, his imprisonment by the Muslims, his diplomatic exchanges during the Hudaybiyyah negotiations, and the circumstances surrounding his conversion.

The book also explores Sohail's contributions after becoming Muslim, including his participation in the subsequent battles and his role in the early Islamic community during the reigns of Abu Bakr and Umar. His two sons, Abu Jandal and Abdullah, both became notable figures in Islamic history, and the book discusses their relationship with their father, particularly the dramatic episode at Hudaybiyyah when Abu Jandal, who had been imprisoned and tortured by his own father for accepting Islam, pleaded with the Prophet not to be returned to Mecca in accordance with the treaty terms. Written in clear and engaging prose, this biography sheds light on a companion whose story is often mentioned in passing but whose full narrative deserves careful study.`,
    metaDescription: "A biography of companion Sohail bin Amar (R.A), tracing his journey from Quraysh negotiator at Hudaybiyyah to a devoted Muslim and his legacy."
  },
  {
    slug: "tafheem-ul-quran-urdu-vol6-set",
    description: `Tafheem ul Quran, the monumental Quranic commentary by Maulana Sayyid Abul A'la Maududi, represents one of the most ambitious and influential exegetical works produced in the modern Muslim world. This volume contains the sixth and final installment of the complete Urdu tafseer, covering the concluding sections of the Quran. Readers who have already completed the first five volumes will find in this final installment the culmination of Maududi's comprehensive approach to Quranic interpretation, which integrates linguistic analysis, historical context, legal discussion, and contemporary relevance into a unified commentary.

Volume six of Tafheem ul Quran addresses the shorter surahs found toward the end of the Quran, many of which are among the most frequently recited chapters in daily prayer. Despite their relative brevity, these surahs contain extremely concentrated theological content, addressing themes of divine unity, prophethood, the afterlife, moral accountability, and the fate of previous nations in powerfully compressed language. Maududi's commentary unpacks each verse with meticulous attention to the classical Arabic usage while simultaneously relating the Quranic message to the social, political, and spiritual challenges facing Muslims in the modern era. His translation of the Quranic text into contemporary Urdu is itself a significant contribution, making the divine message accessible to Urdu-speaking readers without the need for classical Arabic training.

The distinctive feature of Maududi's tafseer methodology is his emphasis on understanding the Quran as a coherent, integrated message rather than a collection of disconnected verses. Throughout this volume, he draws connections between the themes of these concluding surahs and the broader arguments developed across the entire Quranic text. His introductions to each surah provide essential context regarding the circumstances of revelation and the central themes, helping readers approach each chapter with appropriate orientation. This individual volume is suitable for readers who are specifically interested in the tafseer of the later surahs or who are completing their study of the entire Tafheem ul Quran series. The quality of printing and binding ensures that this volume will withstand the regular use that a detailed study of tafseer typically demands.`,
    metaDescription: "Volume 6 of Tafheem ul Quran in Urdu by Maulana Maududi, covering the final surahs with commentary connecting classical and modern perspectives."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
