const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "what-is-islam",
    description: `What is Islam? is an English-language book that provides a comprehensive and accessible introduction to the religion of Islam, designed for readers who have little or no prior knowledge of the faith and who want an accurate, balanced, and thorough account of what Islam teaches and how Muslims practice their religion. The book is written from the perspective of mainstream Sunni Islam and presents its subject matter with the conviction that understanding Islam on its own terms — through its primary sources and its own internal logic — is the prerequisite for any meaningful evaluation of the religion.

The book opens with a historical introduction that places Islam within the broader context of Abrahamic monotheism. The relationship between Islam, Judaism, and Christianity is explained, showing how Islam understands itself as the final and complete form of the divine guidance that Allah has been sending to humanity through a succession of prophets beginning with Adam and culminating in Muhammad. The pre-Islamic conditions of Arabia are described to provide context for the Prophet's mission, and the basic narrative of how Islam emerged — from the first revelation in the cave of Hira through the persecution in Mecca, the migration to Madinah, and the eventual establishment of the Islamic state — is presented as the historical foundation upon which the religion was built.

The core of the book is organized around the five pillars of Islam — the shahadah (declaration of faith), salah (prayer), zakat (charity), sawm (fasting), and Hajj (pilgrimage) — which form the practical framework of Muslim worship. Each pillar is explained in detail: the shahadah's two parts and their theological implications, the structure and meaning of the five daily prayers, the calculation and distribution of zakat, the rules and spiritual dimensions of the Ramadan fast, and the rituals and significance of the Hajj pilgrimage. The six articles of faith — belief in Allah, the angels, the revealed books, the messengers, the Day of Judgment, and divine decree — are similarly explained as the creedal framework that underlies the practical worship.

The book also covers topics that are essential for a complete understanding of Islam but that introductory works sometimes neglect. The Quran — its structure, its themes, its method of preservation, and its role in Muslim life — receives a dedicated chapter. The life of Prophet Muhammad and his role as the practical embodiment of the Quranic message is presented through a concise biography that highlights the key events and qualities of his prophetic mission. The Shariah — the Islamic legal and ethical framework — is explained as a comprehensive system that governs not only worship but also family life, business transactions, criminal justice, and international relations. The Islamic perspective on social issues such as the status of women, the treatment of non-Muslims, the concept of jihad, and the relationship between religion and state is addressed with scholarly accuracy and attention to the nuance that these complex topics require.

The book concludes with a chapter on the contemporary Muslim world that addresses the diversity of Muslim societies, the challenges facing Muslims in the modern era, and the relationship between Islam and Western civilization. The distinction between Islamic teachings and the cultural practices of Muslim societies is emphasized throughout the book, helping readers understand that what they may observe in specific Muslim communities does not necessarily represent the teachings of Islam itself. What is Islam? is written in clear, straightforward English that avoids both apologetics and hostility, presenting Islam as it understands itself while acknowledging areas of legitimate scholarly discussion and historical complexity.`,
    metaDescription: "A comprehensive English introduction to Islam covering the five pillars, six articles of faith, Quran, Prophet Muhammad, and Shariah."
  },
  {
    slug: "what-is-taqwa",
    description: `What Is Taqwa is an English-language book dedicated entirely to explaining the central Islamic concept of taqwa — a term that is often translated as "God-consciousness," "fear of Allah," or "piety" but whose full meaning encompasses a state of being that goes beyond any single English word. The Quran describes taqwa as the best provision a person can carry, the criterion by which Allah distinguishes the noblest human beings, and the quality that determines the acceptance of deeds. Despite its central importance, taqwa is a concept that many Muslims understand only superficially, and this book aims to provide a thorough and practical understanding of what taqwa actually means, how it is cultivated, and how it manifests in a person's daily life.

The book begins with a linguistic and Quranic analysis of the word taqwa, tracing its Arabic root meaning of "protection" or "shielding" and showing how the Islamic concept of taqwa involves protecting oneself from Allah's displeasure by avoiding what He has prohibited and fulfilling what He has commanded. The book examines every Quranic verse in which the word taqwa or its derivatives appear, grouping them into thematic categories that reveal the multifaceted nature of the concept. The Quranic description of taqwa as an inner quality of the heart that motivates righteous action, rather than merely an external display of religious behavior, is established as the foundation for the rest of the book's discussion.

The book distinguishes between the different dimensions of taqwa that the scholars have identified. There is taqwa in relation to Allah — the consciousness of His presence, His knowledge, and His power that prevents a person from sinning even when no other human being is watching. There is taqwa in relation to the self — the self-restraint that prevents a person from following their desires when those desires lead to disobedience. There is taqwa in relation to others — the justice and fairness that prevents a person from wronging others, knowing that Allah is watching and will hold them accountable. And there is taqwa in relation to the unseen — the belief in the Day of Judgment and the accountability that it entails, which motivates a person to prepare for that day through righteous deeds.

The practical section of the book provides specific guidance on how to cultivate taqwa. The connection between knowledge and taqwa is discussed, showing how a deeper understanding of Allah's names and attributes, His commands and prohibitions, and the reality of the hereafter naturally increases a person's taqwa. The role of worship — particularly the five daily prayers, Quran recitation, and fasting — in developing taqwa is explained with reference to the relevant hadith. The practice of muhasabah (self-accountability), in which a person regularly reviews their actions and intentions, is presented as a powerful tool for cultivating taqwa. The importance of choosing righteous companions who encourage taqwa and avoiding environments that weaken it is also discussed.

The book addresses the obstacles to taqwa that people commonly face, including the distraction of worldly pursuits, the influence of bad company, the normalizing of sin through repeated exposure, and the spiritual dryness that sometimes follows periods of negligence. For each obstacle, the book provides practical strategies for overcoming it, drawing upon the Quranic and prophetic guidance and the accumulated wisdom of the early Muslim community. The stories of the companions and the righteous predecessors who achieved extraordinary levels of taqwa are narrated as sources of inspiration. What Is Taqwa is written in clear, accessible English that makes this essential but sometimes challenging concept understandable for readers at every level of Islamic knowledge.`,
    metaDescription: "An English book exploring the Islamic concept of taqwa through Quranic analysis, its practical dimensions, and methods of cultivation."
  },
  {
    slug: "what-is-the-holy-quran-how-to-recite-it",
    description: `What is the Holy Quran and How to Recite It is an English-language introductory book that serves a dual purpose: it provides a comprehensive overview of the Quran as the central text of Islam, and it offers practical instruction on how to recite the Quran correctly according to the rules of tajweed. This combination of informational content and practical guidance makes the book particularly valuable for new Muslims and for those who have grown up in Muslim families but have not had the opportunity to develop their Quranic recitation skills.

The first part of the book establishes what the Quran is — the literal word of Allah as revealed to Prophet Muhammad through the angel Jibril over a period of approximately twenty-three years. The structure of the Quran — its division into surahs (chapters), ayat (verses), juz (parts), and hizb (sections) — is explained with visual aids that help the reader understand how the text is organized. The thematic content of the Quran is surveyed, showing how it addresses three primary areas: the nature of Allah and the relationship between the Creator and creation, the history of the prophets and previous communities, and the legal and ethical principles that govern individual and communal life. The unique characteristics of the Quran — including its inimitability (i'jaz), its preservation from alteration, and its status as the final revelation — are discussed to establish the reader's understanding of why the Quran holds the position it does in Islam.

The second part of the book addresses the proper etiquette of handling and reading the Quran. The requirement of ritual purity (wudu) before touching the Quran, the obligation to show physical respect for the text, the importance of reading with attention and reflection, and the practice of saying the appropriate dua before beginning and after completing a reading are all explained with their evidences from the Quran and Sunnah. The book argues that the Quran is not merely a text to be read but a communication from Allah that deserves to be received with the same attention and respect that a person would give to an important message from a revered figure.

The third and most extensive part of the book provides a practical introduction to the rules of tajweed — the science of Quranic recitation that governs the correct pronunciation of Arabic letters, the rules governing the elongation and shortening of vowel sounds, the rules for the noon sakinah and tanween, the rules for the meem sakinah, and the rules governing the stopping and starting of recitation. Each rule is explained in clear English with accompanying Arabic examples that illustrate how the rule is applied. The phonetic descriptions of the Arabic letters and their points of articulation (makharij) are provided for readers who are not native Arabic speakers, helping them produce the sounds correctly even if they have not studied Arabic formally.

The book includes a practice section that features selected Quranic passages — including Surah Al-Fatiha, Surah Al-Ikhlas, Surah Al-Falaq, and Surah An-Nas — with the tajweed rules marked and explained for each word, allowing the reader to practice applying what they have learned. The transliteration of these surahs is provided alongside the Arabic text for readers who need assistance with pronunciation. The book concludes with guidance on how to continue developing Quranic recitation skills after completing the book, including recommendations for teachers, courses, and digital resources. What is the Holy Quran and How to Recite It is designed for absolute beginners and provides a solid foundation upon which more advanced Quranic study can be built.`,
    metaDescription: "An English introduction to the Quran covering its structure, themes, preservation, etiquette, tajweed rules, and beginner practice surahs."
  },
  {
    slug: "what-must-be-known-about-islam",
    description: `What Must be Known about Islam is an English-language book that distills the essential knowledge that every Muslim is obligated to know into a single, well-organized volume. The book is based on the classical scholarly concept of "the knowledge that is an individual obligation" (fard al-ayn) — the minimum body of religious knowledge that no Muslim can be excused for not possessing. This concept, developed by the scholars of Islamic jurisprudence over centuries, identifies the specific beliefs, practices, and rulings that every Muslim must learn and implement, distinguishing them from the broader body of religious knowledge that is a collective obligation (fard kifayah) and from the specialized knowledge that is required only of scholars.

The book organizes this essential knowledge into clear and manageable categories. The first category is the knowledge of aqeedah (creed) — the fundamental beliefs that define a person as a Muslim and without which their Islam is not complete. The meaning of the shahadah, the oneness of Allah, the belief in the prophets and messengers, the belief in the revealed books, the belief in the angels, the belief in the Day of Judgment, and the belief in divine decree are each explained with their supporting evidences from the Quran and the authentic Sunnah. The book takes care to present the creed in its purest form, free from the additions and distortions that have crept into some popular expressions of Muslim belief over the centuries.

The second category is the knowledge of the pillars of Islam — the practical obligations that every Muslim must perform. The conditions, pillars, and obligations of the five daily prayers are explained in sufficient detail for a person to perform them correctly, including the method of wudu, the times of the prayers, the basic movements and recitations, and the things that invalidate the prayer. The obligation of fasting in Ramadan, the basic rules of zakat calculation, and the essential rituals of Hajj (for those who are able to perform it) are each covered with enough detail to be practically useful while avoiding the complexities that belong in specialized fiqh texts.

The third category covers the knowledge of prohibited things — the major sins and forbidden actions that every Muslim must know to avoid. The major sins that the scholars have identified — including shirk, murder, disobedience to parents, false testimony, consuming interest, consuming orphan's property, and fleeing from battle — are listed and explained with their supporting evidences. The practical implications of these prohibitions for daily life — including the halal and haram in food, income, dress, speech, and social interaction — are addressed with clarity and practical specificity.

The fourth category addresses the knowledge of Islamic manners and ethics that every Muslim should practice in their daily life. The Islamic greetings, the etiquette of eating and drinking, the respect for elders, the kindness to children, the treatment of neighbors, the honesty in business, and the general principles of good character are all covered as the essential behavioral knowledge that complements the formal worship. The book argues that a person's knowledge of Islam is incomplete if they know the rituals but not the manners that should accompany them.

The final category addresses contemporary issues that Muslims frequently encounter but about which they may not have received clear guidance. The use of modern financial products, engagement with social media, interaction with non-Muslim colleagues and neighbors, and the approach to cultural practices that conflict with Islamic principles are all discussed with reference to the underlying Islamic principles that should guide decision-making. What Must be Known about Islam is written in plain English that avoids unnecessary technical jargon, making it accessible to readers who are not trained in Islamic studies while maintaining the accuracy and completeness that the subject demands.`,
    metaDescription: "An English guide to essential religious knowledge every Muslim must know covering creed, prayer, fasting, prohibitions, and manners."
  },
  {
    slug: "when-the-moon-split-coloured-edition",
    description: `When the Moon Split — Coloured Edition is an English-language biography of Prophet Muhammad that is distinguished by its engaging narrative style and its use of color illustrations and maps that bring the story of the Prophet's life to visual life for the reader. The book traces the complete arc of the Prophet's life from his birth in Mecca through his childhood, his pre-prophetic career as a merchant, the beginning of revelation, the thirteen years of preaching in Mecca, the migration to Madinah, the establishment of the Islamic state, the major battles and treaties, the conquest of Mecca, the Farewell Pilgrimage, and his death and burial.

The Coloured Edition enhances the narrative text with a carefully curated selection of visual materials. Maps showing the geography of the Arabian Peninsula, the routes of the major migrations and military campaigns, and the layout of Mecca and Madinah help the reader understand the spatial dimensions of the Prophet's story. Illustrations of key sites — the Kaaba, the Cave of Hira, the Prophet's Mosque in Madinah, and the plains of Arafat — provide visual context for the events described in the text. Timelines, family trees, and organizational charts clarify complex information such as the Prophet's lineage, the chronological sequence of events, and the relationships between the various tribes and factions that feature in the narrative.

The book follows a chronological structure that allows the reader to follow the development of the prophetic mission from its beginning to its completion. Each major phase of the Prophet's life is treated in a dedicated chapter or set of chapters, with clear headings and subheadings that make it easy to locate specific events and topics. The writing style is narrative rather than academic, prioritizing readability and engagement while maintaining factual accuracy based on the major classical sources of seerah (prophetic biography), including the works of Ibn Ishaq, Ibn Hisham, Ibn Sa'd, and Ibn Kathir.

The book pays particular attention to the character and personality of the Prophet, weaving descriptions of his kindness, his humor, his courage, his patience, and his compassion throughout the narrative. Specific incidents that illustrate his character — his gentle treatment of children, his forgiveness of enemies, his sharing in the labor of building the mosque in Madinah, his weeping at the death of his son Ibrahim, and his humility despite holding the highest position in the Muslim community — are narrated with emotional sensitivity that helps the reader develop a genuine connection to the Prophet as a person rather than merely as a historical figure.

The events that are sometimes misunderstood or misrepresented in popular discourse are addressed with clarity and evidence. The treatment of the Jewish tribes in Madinah, the marriage to Aishah, the relationship with the Hypocrites, and the military campaigns are each presented in their historical context with reference to the specific circumstances that led to the Prophet's decisions. The book avoids both the uncritical hagiography and the hostile revisionism that characterize some accounts of the Prophet's life, instead presenting a balanced, evidence-based narrative that allows the reader to form an informed understanding.

The Coloured Edition of When the Moon Split is particularly suitable for readers who are visual learners, for young people and students who benefit from the illustrations and maps, and for anyone who wants an engaging and comprehensive introduction to the life of the most influential person in human history. The combination of narrative quality, visual enhancement, and scholarly reliability makes this edition a standout choice among English-language seerah works.`,
    metaDescription: "A colour-illustrated English biography of Prophet Muhammad with maps, timelines, and visual context covering his entire prophetic life."
  },
  {
    slug: "white-para-set-complete-farhat-hashmi-al-huda",
    description: `White Para Set Complete (Farhat Hashmi) Al-Huda is a complete set of the thirty paras (juz) of the Holy Quran, published in a distinctive white cover design and formatted according to the methodology developed by Dr. Farhat Hashmi and the Al-Huda organization for Quran study and education. This para set is specifically designed to support the structured Quran study program that Al-Huda has become known for, with formatting features that facilitate word-by-word translation, root word analysis, and the study of grammatical structures — all tools that are central to the Al-Huda approach to Quranic education.

The Al-Huda approach to Quran study, developed by Dr. Farhat Hashmi, emphasizes understanding the Quran through direct engagement with the Arabic text rather than relying solely on translations. The methodology involves breaking down each verse into its component words, identifying the root word from which each Arabic word is derived, understanding the grammatical structure of each sentence, and building comprehension through this analytical process. This para set supports this methodology by presenting the Quranic text in a format that is optimized for word-by-word study, with sufficient spacing between words to allow for annotation and with a typeface that makes the diacritical marks (tashkeel) clearly visible.

The white cover design distinguishes this set from other Quran publications and has become associated with the Al-Huda educational brand. The complete thirty-para set allows students and teachers to work through the entire Quran systematically, whether in a classroom setting, a study circle, or individual self-study. Each para is bound as a separate volume, making it convenient to carry and study one section at a time — a practical consideration for students who are working through the Quran in stages and who may find a single complete Quran volume cumbersome for focused study of specific sections.

The formatting of the text is designed to support the translation methodology that Al-Huda teaches. The Arabic text is presented in a clear, large font that accommodates the marking of root words, verb forms, and grammatical structures. The margins provide space for students to write their translations and notes as they work through each verse. The numbering of verses, the markers for sajdah (prostration) verses, and the indicators for the beginning and end of each ruku are all clearly marked, providing the navigational aids that students need for efficient study.

This para set is used extensively in the Al-Huda Quran study courses that are conducted in classrooms, online, and through self-study programs across the Urdu-speaking world and in diaspora communities. The courses guide students through a systematic study of the entire Quran, typically completing the thirty paras over a period of one to two years, with regular assessments, reviews, and practical applications. The para set serves as the primary textbook for these courses, and its formatting is designed to integrate seamlessly with the Al-Huda teaching methodology.

The set is also suitable for individual Quran study outside the formal Al-Huda program. Any Muslim who wants to develop a deeper understanding of the Quranic Arabic can benefit from the word-by-word formatting, regardless of whether they are enrolled in a specific course. The durable binding and quality printing ensure that the set can withstand the regular use and handling that a serious study program requires. White Para Set Complete (Farhat Hashmi) Al-Huda is a valuable resource for anyone who wants to move beyond surface-level reading of the Quran toward genuine understanding of its language and meaning.`,
    metaDescription: "A complete thirty-para Quran set in white covers formatted for Al-Huda word-by-word study with clear Arabic text and annotation margins."
  },
  {
    slug: "who-deserves-to-be-worshipped",
    description: `Who Deserves to be Worshipped is an English-language book that addresses the fundamental theological question of divine worship — why Allah alone, and no other being, deserves to be worshipped according to Islam. The book takes a logical and evidence-based approach to this question, arguing that the obligation to direct all worship exclusively to Allah is not merely a matter of blind faith or cultural tradition but is supported by rational arguments, empirical evidence, historical analysis, and the consistent testimony of the prophets throughout human history.

The book begins with a philosophical examination of the concept of worship itself, defining what worship means in the Islamic context — the comprehensive submission of a person's will, love, fear, hope, and obedience to a being whom they recognize as their Creator, Sustainer, and ultimate authority. The book distinguishes between worship in its broad Islamic sense (which encompasses the entirety of a person's life when lived in obedience to Allah) and worship in the narrow sense of ritual acts such as prayer, fasting, and sacrifice. This broad definition of worship is essential for understanding the Islamic claim that many people who consider themselves monotheists are, in fact, directing elements of worship to beings other than Allah.

The rational arguments for the exclusive worship of Allah are presented in a systematic fashion. The cosmological argument — that the existence, complexity, and order of the universe point to a single Creator who must be worshipped — is discussed with reference to the Quranic verses that invite reflection on the natural world as evidence of Allah's existence and uniqueness. The teleological argument — that the purposeful design evident in living organisms and natural systems requires an intelligent Designer — is presented through the Quranic descriptions of the signs (ayat) in creation. The moral argument — that objective moral values require a transcendent moral source — is developed with reference to the Islamic understanding of the fitrah (innate human disposition) that recognizes the existence of a supreme moral authority.

The book examines the historical phenomenon of prophethood as evidence for the exclusive worship of Allah. Every prophet in the Quranic narrative, from Adam through Nuh, Ibrahim, Musa, Isa, and finally Muhammad, preached the same fundamental message: worship Allah alone and avoid the worship of false deities. The consistency of this message across thousands of years, diverse cultures, and vastly different historical contexts is presented as powerful evidence for the truth of its content. The book shows how the message of tawheed (monotheism) was the central theme of every prophet's mission and that the corruptions and deviations that crept into previous religious traditions always involved the introduction of partners in worship alongside Allah.

The book addresses the specific forms of worship that Islam requires to be directed exclusively to Allah, including dua (supplication), seeking help in times of distress, placing trust and reliance, making vows and sacrifices, and seeking judgment and legislation. For each form, the book explains why directing it to anyone other than Allah contradicts the fundamental principle of tawheed, even if the person making the dua or offering the sacrifice does not consciously consider themselves to be worshipping a false deity. The book also addresses the modern forms of shirk — including the worship of wealth, power, status, and personal desire — that are prevalent in contemporary society but that often go unrecognized as forms of idolatry. Who Deserves to be Worshipped is written in clear, reasoned English that makes the Islamic argument for exclusive divine worship accessible and compelling for readers of all backgrounds.`,
    metaDescription: "An English theological book presenting rational and historical arguments for why Allah alone deserves worship, addressing polytheism and modern idolatry."
  },
  {
    slug: "who-is-allah-and-his-prophet-pbuh",
    description: `Who Is Allah and His Prophet is an English-language book that provides a clear and comprehensive introduction to the two central figures of Islamic belief — Allah (God) and Prophet Muhammad — whose proper understanding is essential for anyone who wants to know what Islam actually teaches about its Supreme Being and its final messenger. The book is designed as an entry point for readers who are new to Islam or who want to consolidate their understanding of the most fundamental aspects of Islamic theology.

The first half of the book is devoted to the Islamic understanding of Allah, presenting the Islamic concept of God through the Quranic descriptions, the prophetic teachings, and the analytical framework that Islamic theology has developed over fourteen centuries. The book begins with the most fundamental Islamic belief: that Allah is One, without partner, without equal, and without beginning or end. The three categories of tawheed — the oneness of Allah's lordship (He alone is the Creator, Sustainer, and Controller of all existence), the oneness of His worship (He alone deserves to be worshipped), and the oneness of His names and attributes (He possesses the most beautiful names and perfect attributes that are unique to Him) — are each explained with clarity and supporting Quranic evidence.

The book addresses the specific names and attributes of Allah that the Quran and the Sunnah describe, including His knowledge (He knows all things), His power (He is able to do all things), His wisdom (He does everything with purpose), His mercy (He is the Most Merciful), His justice (He does not wrong anyone), His hearing and sight (He hears and sees all), and His speech (He has spoken through revelation). For each attribute, the book explains what Islam affirms about Allah, what Islam denies (the idea that Allah resembles His creation in any way), and what the proper attitude of the believer should be toward this attribute. The common misconceptions about God in Islam — including the false claim that Islam teaches a harsh or arbitrary deity — are addressed and corrected.

The second half of the book presents Prophet Muhammad as the final messenger of Allah, examining both who he was as a historical person and what his role as a prophet means for Muslims and for humanity. The book provides a concise biography covering his birth, his character before prophethood, the beginning of revelation, his mission in Mecca and Madinah, and his death. The evidences for his prophethood — including the miraculous nature of the Quran, the fulfilled prophecies, his character as acknowledged by friend and foe alike, and the transformative impact of his message on human civilization — are presented systematically.

The book explains the Prophet's role as the practical interpreter of the Quran, showing how his Sunnah (way) provides the detailed guidance for implementing the Quranic teachings in every area of life. The distinction between the obligatory and recommended aspects of following the Prophet is clarified, and the common objections to the concept of following a human prophet are addressed with rational arguments. The book also discusses the Prophet's status in Islam — the high love and respect that Muslims have for him and the clear boundaries of that love (worship is for Allah alone). The final chapter addresses common misconceptions and misrepresentations of both Allah and the Prophet that circulate in non-Muslim discourse, providing factual corrections based on the primary Islamic sources. Who Is Allah and His Prophet is written in accessible English that makes it suitable for readers with no background in Islamic studies.`,
    metaDescription: "An English introduction to Islamic beliefs about Allah's oneness, names, and attributes, and Prophet Muhammad's life, prophethood evidences, and Sunnah."
  },
  {
    slug: "why-do-we-pray",
    description: `Why Do We Pray? is an English-language book that addresses one of the most fundamental questions in Islamic practice: why Muslims pray five times a day, what the prayer actually accomplishes, and how a practice that involves repeating the same words and movements multiple times every day can serve as a meaningful and transformative spiritual discipline rather than a mechanical ritual. The book approaches this question from multiple angles — theological, spiritual, psychological, social, and practical — providing a comprehensive answer that addresses both the intellectual curiosity of the questioning mind and the spiritual hunger of the seeking heart.

The book begins with the theological foundation of prayer: the command of Allah. The Quranic verses that establish the obligation of the five daily prayers are presented with their context and commentary, establishing that prayer is not an optional spiritual exercise but a binding divine command that is one of the pillars upon which Islam stands. The hadith in which the Prophet described prayer as the "pillar of the religion" and the hadith in which he identified the distinction between belief and disbelief as the abandonment of prayer are cited to emphasize the gravity of this obligation. The book explains that the primary reason Muslims pray is simply that Allah has commanded them to do so, and that obedience to divine command is itself an act of worship regardless of any additional benefits that the commanded act may provide.

The spiritual benefits of prayer are explored in depth. The book describes prayer as a direct conversation with Allah — a privilege that is available to every Muslim five times a day without any intermediary. The concept of the mi'raj al-mu'min (the ascension of the believer) — the Prophet's description of the prayer as the closest a person comes to their Lord while still alive — is discussed as a framework for understanding the spiritual potential of each prayer. The book explains how the physical postures of prayer — standing, bowing, prostrating, and sitting — each carry spiritual symbolism and contribute to the experience of submitting to Allah's authority.

The psychological and emotional benefits of prayer are discussed in relation to contemporary research on the effects of regular meditation, mindfulness, and structured spiritual practice. The stress-reducing effects of the physical movements of prayer, the mental focus required by the recitation, the emotional comfort of expressing one's needs and gratitude to a benevolent Creator, and the psychological stability that comes from having a structured daily practice that provides regular breaks from worldly concerns are all presented as practical benefits that complement the primary spiritual purpose of prayer.

The social dimension of prayer is addressed through the discussion of congregational prayer, the Friday prayer, and the Eid prayers. The book shows how the prayer serves as a social equalizer that brings together people of all social and economic classes five times a day, standing shoulder to shoulder in the same rows, facing the same direction, and bowing and prostrating to the same Lord. The role of the mosque as a community center where social bonds are formed, problems are shared, and collective action is coordinated is discussed as one of the prayer's social functions.

The practical section of the book provides guidance for overcoming the common obstacles that prevent people from praying consistently, including spiritual dryness, time management challenges, lack of concentration, and the temptation to postpone prayer. The book offers specific strategies for improving the quality of prayer, developing khushu (concentration and humility), and maintaining consistency through the inevitable ups and downs of spiritual life. Why Do We Pray? is written in an engaging, question-driven style that makes it suitable for Muslims who are struggling with their prayer practice, for young people who are questioning the relevance of this obligation, and for anyone who wants to understand the rationale behind one of the most distinctive practices of the Islamic faith.`,
    metaDescription: "An English book exploring why Muslims pray five times daily through theological, spiritual, psychological, and social perspectives."
  },
  {
    slug: "why-islam-is-our-only-choice",
    description: `Why Islam is Our Only Choice is an English-language book that presents the case for Islam as the true and complete religion for all of humanity, addressing both Muslims who want to strengthen the rational foundations of their faith and non-Muslims who are seeking to understand why Islam claims to be the final and only acceptable way of life before Allah. The book takes its title seriously, arguing not merely that Islam is a good religion or one valid path among many, but that it is the only comprehensive, internally consistent, and divinely validated system of belief and practice that adequately addresses the fundamental questions of human existence.

The book begins by establishing the framework within which the case for Islam is presented. The fundamental premise is that human beings were created with a purpose, that this purpose is known to the Creator who created them, and that the Creator has communicated this purpose through the system of prophethood that culminated in the message of Prophet Muhammad. The book argues that the question of which religion is true is not a matter of personal preference or cultural conditioning but an objective question of fact that can and should be investigated through rational inquiry, empirical evidence, and honest evaluation of the available options.

The rational arguments for Islam are presented through several distinct lines of reasoning. The argument from the Quran's linguistic inimitability (i'jaz) is discussed as evidence that the Quran could not have been produced by any human being, given that Prophet Muhammad was unlettered and the Arabian society of his time was not known for producing literature of comparable depth and beauty. The argument from the Quran's scientific content — the references to natural phenomena that were not understood by science until centuries after the Quran's revelation — is presented with specific examples and careful discussion of the methodology of Quranic scientific interpretation. The argument from the consistency of the prophetic message across thousands of years of human history is developed by showing how every prophet, regardless of time, place, or culture, preached the same fundamental message of monotheism and accountability.

The book examines the alternatives to Islam and demonstrates why they are inadequate as comprehensive systems of guidance. The limitation of human-made philosophies and ideologies — which change over time, contradict each other, and fail to address the fundamental questions of origin, purpose, and destiny — is discussed as evidence for the need for divine guidance. The corruption of the previously revealed religions — the way in which the original messages of Moses, David, and Jesus were altered by human editing, cultural influence, and institutional interests — is documented with reference to historical scholarship. The book argues that Islam alone preserves its original text intact, maintains the consistency between its theological claims and its historical evidence, and provides a comprehensive system that addresses every aspect of human life.

The section on the practical benefits of Islam shows how the Islamic system — when properly understood and implemented — produces individuals who are morally upright, families that are stable and nurturing, and societies that are just and cohesive. The Islamic approach to social justice, economic fairness, family structure, criminal justice, and environmental stewardship is presented as a system that addresses the root causes of the problems that plague modern societies. The book argues that these practical benefits are not incidental but flow directly from the coherence between Islam's theological principles and its practical prescriptions.

The book addresses the common objections and criticisms that are raised against Islam, including questions about the status of women, the concept of jihad, the treatment of non-Muslims, and the compatibility of Islam with modernity. Each objection is addressed with evidence from the primary Islamic sources, demonstrating that most criticisms are based on misunderstandings of Islamic teachings, the conflation of cultural practices with religious requirements, or the selective citation of texts without their proper context. Why Islam is Our Only Choice is written in a confident but respectful tone that invites the reader to examine the evidence and reach their own conclusion, making it suitable for da'wah (inviting to Islam), for Muslim students who need to defend their faith in academic or social settings, and for open-minded non-Muslims who are willing to consider the case for Islam with intellectual honesty.`,
    metaDescription: "An English book presenting the rational case for Islam through Quranic miracles, prophetic consistency, and responses to common objections."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
