const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "noble-quran-eng-17x24-local-bw",
    description: `The Noble Quran in English translation, 17x24 local black and white edition, provides a complete and faithful English rendering of the Quranic text in a practical and affordable format suitable for daily reading, study, and reference. This edition uses the widely respected English translation that has been carefully reviewed by scholars to ensure accuracy in conveying the meaning of the Quranic Arabic while maintaining readability in contemporary English. The 17x24 dimensions represent a standard medium-large size that offers comfortable readability for extended reading sessions while remaining portable enough for use at home, in the mosque, and during travel. The black and white printing approach keeps the production accessible, focusing resources on the quality of the text rather than on decorative elements, which makes this edition particularly suitable for readers who prioritise content over aesthetics or who require multiple copies for classroom and group study settings. The layout presents the English translation alongside the corresponding Arabic text in a parallel format that allows bilingual readers to compare the translation with the original. Surah headings and verse numbers are clearly marked throughout, and the traditional division markers for juz, hizb, and ruku are indicated in the margins to facilitate structured reading plans and easy navigation to specific passages. A comprehensive index of subjects at the end of the book enables readers to locate Quranic verses by topic, which is especially useful for research, sermon preparation, and personal study. The binding is designed to withstand the demands of regular use, with a sturdy cover and secure stitching that prevent pages from loosening even after extended periods of daily reading. Footnotes at the bottom of relevant pages provide brief explanatory notes on historical context, linguistic nuances, and cross-references to related verses elsewhere in the Quran. The translation methodology prioritises faithfulness to the original meaning while avoiding paraphrastic interpretations that might introduce the translator's personal understanding as though it were part of the divine text. This local edition has been produced with attention to the needs of English-speaking Muslim communities, using spellings, terminology, and stylistic conventions that align with the preferences of readers in South Asian and international Muslim contexts. The book is recommended for new Muslims learning about the Quran, English-speaking families building their Islamic library, students engaged in Quranic study programmes, and anyone who wishes to engage with the Quranic message in clear, reliable English.`,
    metaDescription: "The Noble Quran English 17x24 Local B/W offers a faithful English translation with Arabic text in a durable medium-format edition for daily reading."
  },
  {
    slug: "noor-ul-quran",
    description: `Noor ul Quran, meaning The Light of the Quran, is an Urdu-language work that explores the profound guidance, wisdom, and transformative power that the Quran brings to individual lives and to humanity as a whole. The book approaches the Quran not merely as a text to be read but as a living source of illumination that dispels the darkness of ignorance, confusion, and spiritual malaise. The author structures the book around thematic explorations of the various dimensions of Quranic guidance, including its role as a source of legal and ethical principles, its function as a spiritual compass that directs the human heart toward its Creator, and its capacity to provide answers to the fundamental questions of human existence. Each chapter selects specific Quranic passages and examines them in depth, drawing upon classical tafsir or Quranic exegesis to unpack layers of meaning that may not be immediately apparent to the casual reader. The book discusses the concept of noor or light as it appears throughout the Quran, connecting this metaphor to the actual experience of readers who find clarity, purpose, and peace through sustained engagement with the Quranic text. The author addresses practical aspects of Quranic engagement as well, including the etiquettes of handling and reciting the Quran, the recommended approach to studying tafsir, the relationship between Quran recitation and understanding, and the methods used by the early Muslims to internalise the Quranic message in their daily lives. A recurring theme is the Quran's universality and timelessness, with the author demonstrating how verses revealed over fourteen centuries ago continue to provide relevant guidance for contemporary challenges in personal conduct, family life, social organisation, and interfaith relations. The Urdu prose style is refined and literary, reflecting the author's deep engagement with both the Quranic text and the classical scholarly tradition that has preserved its interpretation across generations. The book includes references to major tafsir works including those of Ibn Kathir, Al-Tabari, Al-Qurtubi, and other authoritative exegetes, allowing interested readers to pursue further study of specific passages. This work is suitable for anyone who wishes to deepen their understanding and appreciation of the Quran's role as the central source of guidance in Islam, from students of Islamic studies to general readers seeking spiritual enrichment through Quranic reflection.`,
    metaDescription: "Noor ul Quran is an Urdu work exploring the Quran's transformative guidance, wisdom, and light through thematic tafsir and classical scholarly references."
  },
  {
    slug: "now-you-are-a-mother",
    description: `Now You Are a Mother is an English-language guide that addresses the practical, emotional, and spiritual dimensions of motherhood within an Islamic framework. Written specifically for Muslim women who have recently become mothers or are preparing for motherhood, this book provides comprehensive guidance that bridges the gap between general parenting advice and the specific values and principles that shape Islamic approaches to raising children. The book opens by acknowledging the profound transition that motherhood represents in a woman's life, validating the mixture of joy, anxiety, exhaustion, and spiritual reflection that accompanies the arrival of a newborn. It then proceeds to address the immediate practical needs of new mothers, including post-delivery recovery, breastfeeding guidance, establishing sleep routines, and managing the physical demands of caring for an infant, all framed within the context of Islamic teachings that honour and support the mother's wellbeing. The spiritual dimensions of motherhood receive significant attention, with chapters discussing the immense reward promised to mothers in Islam, the concept of motherhood as a form of worship and ongoing charity, and the specific supplications and remembrances recommended for new mothers. The book provides detailed guidance on the Islamic practices related to newborns, covering the adhan in the newborn's ear, tahneek, aqiqah, naming, and circumcision, explaining each practice's significance and the authentic hadith sources that establish it. As the child grows, the book offers age-specific guidance on nurturing faith, teaching basic Islamic manners, introducing prayer, and creating a home environment that supports the child's religious and moral development. The author addresses common challenges faced by Muslim mothers in contemporary society, including balancing professional aspirations with family responsibilities, managing the expectations of extended family, navigating cultural practices that may conflict with Islamic principles, and maintaining personal spiritual growth during the demanding early years of motherhood. The tone throughout is supportive and encouraging, avoiding judgment while gently guiding readers toward practices that align with Islamic teachings. Real-life scenarios and practical tips make the guidance immediately applicable. This book serves as both a practical manual and a source of spiritual comfort for Muslim mothers at every stage of their parenting journey, and it is frequently recommended as a gift for women approaching motherhood.`,
    metaDescription: "Now You Are a Mother offers Muslim women practical and spiritual guidance on Islamic motherhood, from newborn care to nurturing faith in children."
  },
  {
    slug: "nukhbat-al-sahihayn",
    description: `Nukhbat al-Sahihayn is a scholarly Islamic work that curates and presents a selection of authentic hadith drawn from the two most revered hadith collections in Islam: Sahih al-Bukhari and Sahih al-Muslim. The title, which can be translated as The Selection of the Two Authentic Books, indicates the author's purpose of distilling the most essential narrations from these monumental works into a single, focused volume that captures the core teachings of the Prophet Muhammad, peace be upon him, on the most important topics of faith and practice. The selection process has been guided by scholarly criteria that prioritise hadith covering the pillars of Islam, the foundations of belief, moral conduct, social responsibilities, and spiritual development, ensuring that the resulting compilation provides a well-rounded education in Prophetic guidance through a manageable number of narrations. Each hadith is presented with its complete Arabic text as it appears in the original Bukhari or Muslim collection, followed by the chain of narrators or isnad that establishes its authenticity. The commentary accompanying each hadith draws upon the explanations of classical hadith scholars, providing context for the narration, explaining uncommon vocabulary, and clarifying any ambiguities in the text. The author pays particular attention to the legal and practical implications of each hadith, showing how the Prophetic guidance applies to real-world situations and how the early Muslims understood and implemented these teachings. The book includes an introductory section that discusses the methodology used by Imam al-Bukhari and Imam Muslim in compiling their collections, the criteria each applied in accepting or rejecting narrations, and the distinctive features that have earned these two works their unparalleled status in Islamic scholarship. This introduction equips readers with the background knowledge needed to appreciate why the hadith in this compilation carry the weight of the highest level of authentication in the hadith tradition. The organisational structure follows a thematic arrangement that groups related hadith together, allowing readers to study specific topics comprehensively. The work serves as an excellent bridge for students who wish to progress from introductory hadith studies to direct engagement with the primary collections, providing the essential narrations with sufficient scholarly apparatus to support serious study while remaining accessible to readers who are building their hadith knowledge systematically.`,
    metaDescription: "Nukhbat al-Sahihayn is a scholarly selection of essential hadith from Sahih al-Bukhari and Sahih Muslim with Arabic text, chains, and commentary."
  },
  {
    slug: "nunehalon-kay-liye-sunehre-azkar",
    description: `Nunehalon kay liye Sunehre Azkar, meaning Golden Supplications for Children, is a carefully curated Urdu-language collection of daily prayers and remembrances specifically compiled for young Muslim children. The word sunehre or golden in the title reflects the precious value that these supplications carry in a child's spiritual development, serving as the building blocks of a lifelong relationship with Allah. The book is designed as an interactive learning tool that introduces children to the practice of making dua and remembering Allah throughout the various activities and moments of their daily routine. Each supplication is selected from authentic hadith sources and is presented with the complete Arabic text in a large, child-friendly font with full vowel marks to support correct pronunciation. Alongside the Arabic, the book provides simple Urdu transliteration that helps children who are still learning Arabic script to recite the duas accurately, and a clear Urdu translation written in language that children between the ages of four and ten can readily understand. The supplications are organised according to the moments in a child's day when they are traditionally recited: waking up in the morning, entering and leaving the bathroom, before and after eating, leaving for and returning from school, before sleeping, and during special occasions such as visiting the mosque or greeting guests. This routine-based organisation helps children understand that remembering Allah is not limited to specific prayer times but permeates every aspect of daily life. The book includes brief explanations for each dua that help children grasp not only what they are saying but why it matters, fostering a sense of meaning and purpose behind each act of remembrance. Colourful illustrations accompany each section, depicting children in familiar everyday situations and serving as visual cues that reinforce the connection between specific moments and their corresponding supplications. Parents and teachers will find the review section at the end of each chapter useful for testing retention and encouraging children to memorise the duas. The durable binding and thick pages are chosen to withstand frequent handling by young readers. This book is an excellent starting point for establishing the habit of daily azkar in children and is widely used in Islamic preschools, kindergarten programmes, and homes where religious education is a priority.`,
    metaDescription: "Nunehalon kay liye Sunehre Azkar is a beautifully illustrated Urdu collection of daily supplications for children aged 4 to 10, organised by daily routine."
  },
  {
    slug: "on-the-mountain-peak",
    description: `On The Mountain Peak is an English-language Islamic storybook that uses the metaphor of a mountain climb to convey profound lessons about faith, perseverance, trust in Allah, and the spiritual journey of a believer. The narrative follows characters who embark on a challenging mountain ascent, and through the physical challenges they face on the climb, the book draws parallels to the spiritual challenges that every Muslim encounters throughout their life. The mountain setting provides a rich backdrop for exploring themes such as the importance of having a clear destination or purpose, the value of a knowledgeable guide or mentor, the necessity of preparation and proper equipment for the journey, and the different types of obstacles that can cause a climber to stumble or turn back. Each chapter of the story introduces a new challenge on the mountain and simultaneously presents a corresponding spiritual lesson drawn from Islamic teachings. The physical difficulty of the climb mirrors the difficulty of maintaining faith during times of hardship, the temptation to take easier but misguided paths reflects the distractions that lead believers away from the straight path, and the moments of reaching a summit echo the spiritual elevation that comes with overcoming trials through patience and reliance upon Allah. The writing style is engaging and descriptive, using vivid imagery to bring the mountain landscape to life while maintaining a narrative pace that keeps readers invested in the characters' journey. The Islamic lessons are woven naturally into the story rather than being presented as didactic interruptions, allowing the moral and spiritual content to emerge organically from the narrative. The book is suitable for readers aged twelve and above, including teenagers and adults, who appreciate allegorical storytelling that deepens their understanding of Islamic principles through imaginative fiction. Discussion questions at the end of each chapter encourage readers to reflect on how the story's themes apply to their own lives and faith experiences. Teachers at Islamic schools have found this book to be an effective tool for stimulating classroom discussions about patience, gratitude, reliance on Allah or tawakkul, and the purpose of tests and difficulties in a believer's life.`,
    metaDescription: "On The Mountain Peak is an English Islamic storybook using a mountain climb to explore faith, perseverance, and trust in Allah for ages 12 and above."
  },
  {
    slug: "our-children-memorization-of-the-quran",
    description: `Our Children and Memorization of the Quran is a practical English-language guide designed to support parents, teachers, and Islamic educators in the vital task of helping children memorise the Holy Quran. The book addresses a concern shared by Muslim families worldwide: the desire to raise children who have committed the Quran to memory while navigating the practical challenges of modern education, busy schedules, and varying levels of access to qualified Quran teachers. The author approaches the subject with both scholarly grounding and practical experience, drawing upon established pedagogical principles in Quran memorisation as well as contemporary educational research on memory, learning, and child development. The book begins by establishing the importance and immense reward of Quran memorisation, citing relevant Quranic verses and hadith that encourage families to prioritise this endeavour, before moving into the practical guidance that forms the core of the work. Detailed chapters cover the process of selecting an appropriate Quran memorisation programme or teacher, understanding the different methodologies used in hifz schools, and creating a home environment that supports the memorisation process through consistent routines, positive reinforcement, and minimal distractions. The book provides specific techniques for effective memorisation, including the methods of repetition, the use of audio recordings alongside oral recitation, the strategy of linking new verses to previously memorised passages, and the importance of daily review to consolidate what has been learned. A significant section addresses the common obstacles that children face during memorisation, including loss of motivation, difficulty with specific passages, the challenge of maintaining memorisation during school holidays, and the emotional and psychological pressures that intensive hifz programmes can place on young learners. For each obstacle, the author offers evidence-based strategies and spiritual remedies, including making dua, adjusting expectations, providing appropriate breaks, and maintaining a supportive rather than pressuring attitude. The book also covers the role of technology in Quran memorisation, discussing the benefits and limitations of Quran applications, digital recording devices, and online memorisation programmes. Guidance is provided on the milestones that indicate a child is progressing appropriately and on the criteria for evaluating the quality of a child's memorisation. This comprehensive guide is recommended for any parent or educator committed to supporting a child's Quran memorisation journey from the initial stages through to completion and long-term retention.`,
    metaDescription: "Our Children and Memorization of the Quran is a practical English guide for parents and teachers supporting children's hifz journey with proven techniques."
  },
  {
    slug: "our-prophet-muhammad-pbuh",
    description: `Our Prophet Muhammad, peace be upon him, is an English-language children's book that introduces young readers to the life and character of the final messenger of Allah in a manner that is engaging, age-appropriate, and grounded in authentic Islamic sources. Written specifically for children between the ages of six and twelve, this book takes young readers on a chronological journey through the major events of the Prophet's life, from his birth in Makkah and his upbringing in the household of Halimah as-Sa'diyah, through his marriage to Khadijah, the first revelation in the cave of Hira, the challenges of preaching Islam in Makkah, the migration to Madinah, the establishment of the Muslim community, the battles and treaties that defined the early Islamic state, and the final farewell pilgrimage. The narrative is crafted in a storytelling style that captures children's imagination while maintaining factual accuracy based on the most reliable Seerah sources. Each chapter is written at a reading level that upper primary and lower secondary students can manage independently, while younger children can enjoy the book as a read-aloud experience with parents or teachers. The character of the Prophet is presented through specific incidents that illustrate his qualities of mercy, patience, honesty, courage, generosity, humility, and justice, allowing children to develop a personal connection to these traits rather than encountering them as abstract concepts. The book addresses difficult topics such as the persecution of Muslims in Makkah, the loss of loved ones, and the challenges of warfare in a manner that is honest but not frightening, using age-appropriate language that acknowledges hardship while emphasising the lessons of resilience and faith. Illustrations throughout the book provide visual context for the settings and events described in the text, following Islamic guidelines regarding visual representation. Each chapter concludes with a key lesson or moral that children can apply to their own lives, reinforcing the book's educational value beyond mere historical knowledge. A timeline, glossary of Arabic terms, and map of important locations support the educational framework. This book is widely used in Islamic schools, Sunday school programmes, and home libraries as a first introduction to the Prophet's life for English-speaking Muslim children.`,
    metaDescription: "Our Prophet Muhammad PBUH is an English children's book introducing the Prophet's life and character for readers aged 6 to 12 with illustrations."
  },
  {
    slug: "pachtawa",
    description: `Pachtawa, meaning Repentance, is a deeply reflective Urdu-language book that examines the concept of tawbah or repentance in Islam with both scholarly thoroughness and emotional sensitivity. The book addresses one of the most universal human experiences: the recognition of one's own mistakes, the burden of guilt that follows, and the longing for forgiveness and spiritual renewal. Drawing upon the Quran, authentic hadith, and the wisdom of classical Islamic scholars, the author constructs a comprehensive treatment of repentance that covers its theological foundations, its practical requirements, its spiritual effects, and the barriers that prevent people from turning back to Allah. The opening chapters establish the Quranic perspective on human error and divine forgiveness, demonstrating through specific verses that Allah's mercy encompasses all sins for those who repent sincerely. The book discusses the conditions of a valid repentance as outlined by Islamic scholars, including sincere remorse, immediate cessation of the sinful action, firm intention not to return to the sin, and where applicable, restoration of the rights of any person who was wronged. Each condition is explained with reference to Quranic verses and hadith, and practical guidance is provided for readers who struggle to fulfil these conditions. A significant and compassionate section of the book addresses the psychological barriers to repentance, including feelings of unworthiness, the fear that one's sins are too great to be forgiven, the shame of admitting wrongdoing, and the tendency to delay repentance out of attachment to sinful habits. The author counters each barrier with evidence from the Quran and hadith that demonstrates the inclusiveness of Allah's forgiveness and the encouragement that Islam offers to those who seek to return to their Lord. The book also distinguishes between major and minor sins, discusses the concept of good deeds erasing bad deeds, and explores the role of the five daily prayers, fasting, and other acts of worship in the process of spiritual purification. Throughout the text, real-life examples and parables illustrate the principles being discussed, making the content relatable and actionable for readers. The Urdu prose is lyrical yet direct, conveying both the gravity of sin and the beauty of divine mercy. This book is recommended for anyone seeking spiritual renewal, including those who feel distant from Allah due to past mistakes and those who wish to maintain a consistent practice of repentance in their daily lives.`,
    metaDescription: "Pachtawa is a reflective Urdu book on Islamic repentance, addressing theological foundations and practical requirements for seeking forgiveness."
  },
  {
    slug: "paighambar-e-islam-muhammad-saw-an-illustrated-guide",
    description: `Paighambar e Islam Muhammad S.A.W. - An Illustrated Guide is a visually rich English-language biography of the Prophet Muhammad, peace be upon him, that combines authoritative historical narration with illustrative content to create an engaging and educational resource on the life of Islam's final messenger. The book covers the complete span of the Prophet's life from his birth in Makkah to his death in Madinah, presenting the major events, decisions, and milestones in a chronological narrative that draws upon the most reliable sources of Seerah literature. The illustrated format distinguishes this biography from text-only works by providing visual context that helps readers, particularly younger audiences and visual learners, to develop a more vivid and concrete understanding of the settings, events, and cultural environment in which the Prophet's mission unfolded. Maps of the Arabian Peninsula show the locations of Makkah, Madinah, Taif, Badr, Uhud, and other significant sites, allowing readers to follow the geographical progression of the Prophet's journey. Illustrations depict the architecture, landscapes, and daily life of seventh-century Arabia, providing the cultural context that enriches comprehension of the historical events. The narrative covers the Prophet's lineage and early life, his reputation for honesty before prophethood, the first revelation and its immediate aftermath, the persecution of early Muslims in Makkah, the migration to Abyssinia, the boycott of Banu Hashim, the Night Journey and Ascension, the migration to Madinah, the establishment of the Islamic state, the battles of Badr, Uhud, and the Trench, the Treaty of Hudaybiyyah, the conquest of Makkah, the farewell pilgrimage, and the Prophet's final illness and passing. Throughout the narrative, the Prophet's character is highlighted through specific incidents that demonstrate his mercy toward all creation, his justice even toward enemies, his concern for the vulnerable members of society, and his unwavering commitment to conveying Allah's message despite facing intense opposition. The writing style is clear and engaging, making the content accessible to readers aged twelve and above while maintaining the scholarly accuracy expected of a serious biographical work. Sidebars and callout boxes provide additional information on topics such as the Prophet's family tree, the names of his companions, the weapons and tools of the period, and the significance of key locations. This illustrated guide serves as an excellent educational resource for Islamic schools, a reference for Seerah study circles, and a valuable addition to any Muslim household's library.`,
    metaDescription: "Paighambar e Islam Muhammad SAW Illustrated Guide is a visually rich English biography covering the Prophet's complete life for ages 12 and above."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
