const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const descriptions = [
  {
    slug: "tafsir-kalimaat-al-quran-14x21",
    description: `Tafsir Kalimaat Al Quran (Words of the Quran Explained) in the 14x21 cm edition is a distinctive Urdu tafsir work that approaches Quranic exegesis through a word-by-word analytical methodology, making it particularly valuable for readers who want to understand the precise meaning of each word and phrase in the Holy Quran rather than receiving only a general translation of complete verses. This tafsir systematically breaks down each verse into its individual vocabulary components, explaining the root meaning of each Arabic word, its grammatical form and function within the sentence, and how the combined meaning of the individual words creates the verse's complete message. This word-level approach is especially beneficial for students of Arabic grammar who want to see how grammatical rules function within the actual Quranic text, for Quran teachers who need to explain individual words during classes, and for anyone who has learned basic Arabic vocabulary and wants to reinforce and expand their understanding by studying how those words are used in their original divine context. The 14x21 cm format is a standard and popular Quran size in Pakistan — large enough for comfortable reading of both the Arabic text and the Urdu commentary, yet compact enough for convenient handling and storage. This edition features quality printing on durable paper, clear Urdu typography, and reliable binding suitable for daily study use. Tafsir Kalimaat Al Quran occupies a unique niche in Urdu tafsir literature because it bridges the gap between translation (tarjuma) and full exegesis (tafsir), providing more depth than a simple translation while remaining more accessible than comprehensive multi-volume tafsir works like Tafsir Ibn Kathir. At Rs. 3,550, this quality tafsir edition represents an important investment in Quranic understanding. Available at Bab-ul-Fatah with careful packaging and delivery across Pakistan.`,
    metaDescription: "Tafsir Kalimaat Al Quran 14x21 — Urdu word-by-word Quranic exegesis for deeper understanding. Clear format. Order at Bab-ul-Fatah."
  },
  {
    slug: "fazail-e-sahabiyat-kareemat-part-2",
    description: `Fazail e Sahabiyat Kareemat Part 2 (Virtues of the Noble Female Companions — Volume 2) is a continuation of the Urdu series dedicated to documenting the lives, virtues, and contributions of the female Companions (Sahabiyat) of the Prophet Muhammad (peace be upon him). This second volume covers additional female Companions whose lives serve as timeless models of faith, courage, knowledge, and devotion — women who were direct witnesses to revelation, participants in the building of the first Islamic society, and transmitters of prophetic knowledge to subsequent generations. The Fazail e Sahabiyat Kareemat series addresses a significant gap in Urdu Islamic literature, where the lives of female Companions have historically received less detailed coverage than those of their male counterparts, despite the crucial role that women like Khadijah, Aisha, Hafsa, Umm Salama, Fatimah, Asma bint Abi Bakr, and many others played in the early Muslim community. Each biography in this volume provides the Companion's lineage, her conversion story or circumstances of embracing Islam, her contributions during the Prophet's lifetime, her scholarly achievements, and any specific hadith narrations she transmitted. The book highlights how these remarkable women excelled in various roles — as scholars, warriors, businesswomen, nurses, political advisors, and spiritual guides — demonstrating that Islam elevated women's status and recognized their capabilities over fourteen centuries before modern feminism. The volume is meticulously sourced from authenticated hadith collections and classical biographical works, ensuring that every account is historically reliable. At Rs. 1,180, this volume continues the important work of preserving and celebrating the legacy of Islam's first generation of female believers. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Fazail e Sahabiyat Kareemat Part 2 — Urdu biographies of noble female Companions of Prophet Muhammad. Authenticated sources. Order Bab-ul-Fatah."
  },
  {
    slug: "the-end-of-the-world",
    description: `The End of the World by Darussalam is a comprehensive English-language book that presents a detailed, source-based account of Islamic eschatology — the signs of the Last Day (Ashrat as-Sa'ah), the events of the Day of Judgment (Yawm al-Qiyamah), and the ultimate destiny of humanity as described in the Holy Quran and authenticated hadith literature. This important work systematically organizes the vast body of prophetic narrations about the end times into a coherent chronological framework, beginning with the minor signs (alamat as-sughra) that the Prophet Muhammad (peace be upon him) foretold would appear as indicators that the Day of Judgment is approaching. These minor signs include the spread of ignorance despite the availability of knowledge, the proliferation of tall buildings, the prevalence of musical instruments, the acceptance of sexual immorality, the drinking of wine becoming widespread, and many other social and moral phenomena that are strikingly visible in the contemporary world. The book then progresses to the major signs (alamat al-kubra) — the extraordinary events that will occur in the final period before the Day of Judgment, including the appearance of the Dajjal (the False Messiah or Antichrist), the return of Prophet Isa (Jesus, peace be upon him), the emergence of Gog and Magog (Ya'juj and Ma'juj), the rising of the sun from the west, and the Beast of the Earth. The final sections cover the Day of Judgment itself — the resurrection, the gathering, the reckoning, the weighing of deeds, the bridge over Hell, the intercession, and the ultimate destinations of Paradise and Hellfire. At Rs. 2,500, this hardcover book provides an essential understanding of what Islam teaches about humanity's final chapter. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "The End of the World — Islamic eschatology book covering minor & major signs of Qiyamah, Day of Judgment from Quran & Hadith. Order Bab-ul-Fatah."
  },
  {
    slug: "islam-atotal-beginners-guide-2",
    description: `Islam: A Total Beginners Guide (Volume 2) by Maulvi Abdul Aziz is the second installment of a comprehensive English-language introductory series designed specifically for new Muslims, non-Muslims curious about Islam, and young Muslims seeking a clear, structured overview of their faith. This second volume builds upon the foundational knowledge presented in Volume 1 and delves deeper into the practical and spiritual aspects of Islamic life, covering topics that a beginner needs to understand but may find difficult to learn through fragmented sources. The book addresses key areas including the detailed methodology of performing the five daily prayers with illustrated step-by-step instructions, the complete guide to fasting during Ramadan with practical tips for beginners, the calculation and payment of Zakat explained through worked examples, the essential knowledge needed for performing Hajj and Umrah, Islamic family law basics covering marriage, divorce, and inheritance at an introductory level, and the fundamental principles of Islamic ethics and character development. What makes this series particularly valuable for beginners is its non-sectarian approach — presenting Islamic teachings based directly on the Quran and authentic hadith without favoring any particular school of thought, and its clear, simple English that avoids unnecessary technical jargon while remaining respectful of the subject matter. The book includes helpful features such as a glossary of Islamic terms, suggestions for further reading, and practical checklists that help new Muslims track their progress in learning essential Islamic knowledge. At Rs. 1,400, this guide serves as an excellent textbook for new Muslim programs, dawah initiatives, Islamic school introductory courses, and individual self-study. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Islam: A Total Beginners Guide Vol.2 by Maulvi Abdul Aziz — practical English guide to prayers, fasting, Zakat & Hajj. Order at Bab-ul-Fatah."
  },
  {
    slug: "syedina-abdullah-bin-abbas-ra",
    description: `Syedina Abdullah bin Abbas (R.A) by Abdul Malik Mujahid is a concise yet rich English biography of Abdullah ibn Abbas (may Allah be pleased with him and his father) — the cousin of the Prophet Muhammad (peace be upon him), one of the most prolific hadith narrators, and the scholar whom the Prophet himself prayed for, asking Allah to grant him deep understanding of the Quran and Islamic jurisprudence. This biography traces the remarkable life of a man who, despite being only thirteen years old at the time of the Prophet's passing, grew to become the most knowledgeable Qur'anic exegete among the Companions and was given the title "Tarjuman al-Quran" (Interpreter of the Quran) — a testament to his extraordinary depth of understanding. The book covers Ibn Abbas's privileged childhood in the Prophet's household, where he received direct religious instruction from the Messenger of Allah, his subsequent scholarly development under the guidance of senior Companions including Umar ibn al-Khattab and Ubayy ibn Ka'b, his role as the chief advisor on religious matters during the caliphate of Uthman and Ali, and his establishment of the great school of Quranic interpretation in Ta'if. The biography highlights specific incidents that demonstrate Ibn Abbas's remarkable scholarly abilities — his famous interpretation of Surah An-Nasr that proved his insight exceeded that of senior Companions, his judicial rulings on complex legal questions, and his encyclopedic knowledge of pre-Islamic Arabic poetry, genealogy, and history that enriched his Quranic exegesis. The book also covers his personal characteristics including his generosity, humility, and dedication to teaching. At just Rs. 385, this affordable biography makes the inspiring story of the "Interpreter of the Quran" accessible to every reader. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Syedina Abdullah bin Abbas R.A. biography — the Interpreter of the Quran, cousin of Prophet Muhammad. Scholarly heritage. Order at Bab-ul-Fatah."
  },
  {
    slug: "sipara-set-qudrat-ullah-company-100",
    description: `This Sipara Set by Qudrat Ullah Company is a complete 30-volume set of the Holy Quran divided into individual Juz (parts), each volume containing one of the thirty sections into which the Quran is traditionally divided for ease of reading and memorization. The Qudrat Ullah Company has been one of Pakistan's most established and trusted Quran publishers for generations, known for producing reliable texts that are used extensively in madrasas, mosques, and homes throughout the country. Each individual volume (sipara/para) is bound in a durable soft or hard cover designed to withstand daily handling, making this set particularly practical for students memorizing the Quran (hifz) who typically focus on one Juz at a time and need to carry just that volume with them. The text is printed in a clear Pakistani/Indian script style with proper vowel marks (tashkeel) and tajweed color coding or markings that help readers apply correct pronunciation rules during recitation. The Qudrat Ullah Company's reputation for textual accuracy means that readers can trust the Arabic text to be free from printing errors — a critical concern for any Quran publication, as even a single misplaced diacritical mark can alter the meaning of a word. This complete 30-volume set at Rs. 4,500 offers excellent value for a full Quran in the popular divided format, working out to approximately Rs. 150 per volume. The set is ideal for distribution in madrasas where each student needs access to individual Juz volumes, for households with multiple family members studying different sections simultaneously, or as a significant Ramadan or Eid gift. Available at Bab-ul-Fatah with careful packaging and delivery across Pakistan.`,
    metaDescription: "Sipara Set 30 volumes by Qudrat Ullah Company — complete Quran in individual Juz parts for hifz students. Trusted Pakistani publisher. Order Bab-ul-Fatah."
  },
  {
    slug: "islamic-studies-grade-vol-8",
    description: `Islamic Studies Grade (Volume 8) by Maulvi Abdul Aziz is part of a comprehensive multi-volume Islamic studies curriculum designed for school-aged Muslim students, with this eighth volume targeting students at an intermediate to advanced level of Islamic education. This volume builds upon the knowledge established in the preceding seven volumes and introduces more sophisticated theological, legal, and historical topics that prepare students for advanced Islamic scholarship. The content typically covers detailed study of advanced aqeedah topics including the attributes of Allah and their correct understanding, deeper exploration of the science of hadith including classification of narrations and major hadith collections, intermediate-level fiqh covering worship, transactions, and contemporary issues with evidence from primary sources, comprehensive study of Islamic history from the Abbasid period through the Ottoman era, introduction to Quranic sciences (ulum al-Quran) including types of revelation, abrogation, and the seven modes of recitation, and ethical discussions on contemporary challenges facing Muslim youth including social media ethics, substance abuse prevention, and maintaining Islamic identity in secular environments. Maulvi Abdul Aziz's approach in this curriculum series is notable for its balance between traditional Islamic knowledge and modern educational methodology — using clear explanations, review questions, discussion topics, and practical exercises that engage students actively rather than relying solely on rote memorization. The volume is designed for classroom use but works equally well for home-schooling or supplementary parental instruction. The graded approach ensures that students develop a progressively deeper understanding of their faith year by year, building a solid foundation for lifelong Islamic learning. At Rs. 2,250, this quality educational volume is an investment in a student's Islamic education. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Islamic Studies Grade Vol.8 by Maulvi Abdul Aziz — advanced Islamic curriculum covering hadith, fiqh, history & Quranic sciences. Order at Bab-ul-Fatah."
  },
  {
    slug: "inam-yafta-taqreeain",
    description: `Inam Yafta Taqreeain (Award-Winning Competitions) is a unique Urdu educational book that presents Islamic knowledge in an innovative quiz and competition format designed to test and strengthen the reader's understanding of various Islamic subjects. This engaging book transforms Islamic learning from passive reading into an active, competitive exercise that stimulates recall, deepens understanding, and makes the learning process genuinely enjoyable — particularly for younger readers and students. The book contains a wide range of question formats including multiple-choice questions, fill-in-the-blank exercises, true-or-false statements, short-answer questions, and detailed essay-type questions covering the complete spectrum of Islamic knowledge: Quranic studies (names of surahs, number of verses, key themes), hadith narrations and their chain of transmitters, seerah (dates, names, locations, events), fiqh (rulings on worship, daily life, and contemporary issues), aqeedah (articles of faith, names and attributes of Allah), Islamic history (caliphs, battles, dynasties, scholars), and general Islamic trivia. Each section is organized by topic and difficulty level, allowing readers to progressively challenge themselves as their knowledge grows. The book is particularly valuable for Islamic school teachers who can use it to prepare quiz competitions, for parents who want to make Islamic learning fun for their children, for madrasa students preparing for examinations, and for Islamic study circles that want to add an interactive element to their sessions. The competitive format taps into the natural human desire for achievement and recognition, motivating learners to study more seriously and retain information more effectively than traditional textbook reading alone. At Rs. 500, this affordable book provides hours of educational entertainment and makes an excellent addition to any Islamic school resource library. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Inam Yafta Taqreeain — Urdu Islamic quiz & competition book testing Quran, Hadith, Seerah & Fiqh knowledge. Fun learning. Order at Bab-ul-Fatah."
  },
  {
    slug: "khutbat-e-haram",
    description: `Khutbat e Haram (Sermons of the Sacred Mosque) by Dr. Abdul Rahman As-Sudais is a collected volume of the Friday sermons (khutbas) and special occasion addresses delivered by Sheikh Dr. Abdul Rahman ibn Abdul Aziz Al-Sudais — the Imam and Khateeb of Masjid al-Haram in Makkah, the holiest mosque in Islam. As the Imam of the Grand Mosque where millions of Muslims gather for prayers throughout the year and especially during Hajj and Ramadan, Sheikh Sudais delivers some of the most widely heard Islamic sermons in the world, and this collection brings a selection of his most impactful addresses to Urdu-speaking readers through professional Urdu translation. The sermons in this collection cover the full range of contemporary Islamic topics that Sheikh Sudais regularly addresses in his khutbas: the importance of unity among the Muslim ummah, the dangers of extremism and sectarianism, the responsibility of Muslims toward the oppressed and suffering around the world, the significance of the holy cities of Makkah and Madinah, the spiritual preparation for Hajj and Ramadan, the Islamic perspective on contemporary social issues, and the urgent need for Muslims to return to the authentic teachings of the Quran and Sunnah. Sheikh Sudais is known for his powerful oratorical style — combining deep scholarly content with emotional delivery that moves listeners to tears and reflection — and this Urdu translation captures both the intellectual substance and the spiritual passion of his original Arabic sermons. At Rs. 2,600, this hardcover volume allows readers to benefit from the guidance of one of the Islamic world's most influential religious leaders from the comfort of their homes. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Khutbat e Haram by Dr. Abdul Rahman Sudais — Urdu translation of Makkah Grand Mosque sermons. Inspiring guidance. Order at Bab-ul-Fatah."
  },
  {
    slug: "ashra-zil-hajja-eid-ul-adha-aur-qurbani",
    description: `Ashra Zil Hajja — Eid ul Adha aur Qurbani (The First Ten Days of Dhul Hijjah, Eid ul Adha, and Sacrifice) is a focused Urdu booklet that provides essential guidance on three interconnected topics that define one of the most sacred periods in the Islamic calendar. The first section covers the "Ashra Zil Hajja" (the first ten days of the Islamic month of Dhul Hijjah), which the Prophet Muhammad (peace be upon him) described as the best days in the sight of Allah — even more virtuous than the days of Ramadan — explaining the specific acts of worship recommended during these days including fasting, increased remembrance of Allah (dhikr), recitation of takbir and tahmeed, charitable giving, and voluntary prayers. The second section details the rulings and Sunnah practices of Eid ul Adha (the Festival of Sacrifice), including the method of performing the Eid prayer, the recommended acts on Eid day, and the etiquettes of celebration in the Islamic tradition. The third section provides a comprehensive guide to Qurbani (the udhiyah sacrifice), covering the legal basis for this obligation, which animals are acceptable for sacrifice and their minimum age requirements, the recommended method of slaughtering according to Islamic law, how the meat should be distributed (one-third for family, one-third for friends, one-third for the poor), common mistakes to avoid, and the spiritual significance of this act of worship that commemorates Prophet Ibrahim's willingness to sacrifice his son for Allah's sake. At just Rs. 30, this extremely affordable booklet ensures that every Muslim household can access the essential knowledge needed to properly observe these important religious obligations. Ideal for mass distribution before Dhul Hijjah. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Ashra Zil Hajja — complete Urdu guide on Dhul Hijjah first 10 days, Eid ul Adha & Qurbani rulings. Just Rs.30. Order at Bab-ul-Fatah."
  },
  {
    slug: "atlas-fatuhat-e-islamia",
    description: `Atlas Fatuhat e Islamia (Atlas of Islamic Conquests) is a large-format, richly illustrated Urdu reference book that maps out the geographical expansion of Islam from the time of the Prophet Muhammad (peace be upon him) through the era of the Rightly Guided Caliphs and the subsequent major Islamic dynasties. This unique atlas combines historical narrative with detailed cartographic maps to provide readers with a visual understanding of how Islam spread from its origins in the Arabian Peninsula to encompass vast territories spanning three continents within just a century of the Prophet's passing. The book contains dozens of full-color maps that illustrate the routes of military campaigns, the locations of major battles (Badr, Uhud, Trench, Yarmouk, Qadisiyyah, and others), the boundaries of various Islamic caliphates and empires, the locations of important Islamic cities and centers of learning, and the trade routes that connected the Islamic world with Europe, Africa, and Asia. Each map is accompanied by detailed Urdu text explaining the historical context, the key figures involved, the strategic significance of each campaign or territory, and the lasting impact of these conquests on world civilization. The atlas format makes this complex historical material far more accessible than text-only history books, as readers can literally see the scope and progression of Islamic expansion while reading about each event. The book also covers the spread of Islam through peaceful means — trade, dawah, scholarship, and migration — providing a complete picture of how Islam became the world's second-largest religion. At Rs. 3,950, this large-format hardcover atlas is a significant reference work suitable for Islamic schools, libraries, researchers, and anyone who wants to understand the geographical history of Islamic civilization. Available at Bab-ul-Fatah with careful packaging and delivery across Pakistan.`,
    metaDescription: "Atlas Fatuhat e Islamia — illustrated Urdu atlas mapping Islamic conquests, battles & empire expansion. Full-color maps. Order at Bab-ul-Fatah."
  },
  {
    slug: "historical-atlas-of-the-prophets-messengers",
    description: `Historical Atlas of the Prophets and Messengers is a large-format, beautifully produced English-language reference book that provides a comprehensive geographical and historical survey of the lives and missions of the Prophets and Messengers mentioned in the Holy Quran and authentic Islamic tradition. This unique atlas combines scholarly historical narrative with detailed full-color maps, photographs, and illustrations to bring the stories of the Prophets to life in a way that text-only books cannot achieve. The book covers all the major Prophets from Adam (peace be upon him) through Muhammad (peace be upon him), providing for each Prophet the geographical context of their mission — the location of their people, the routes they traveled, the sites of significant events, and the archaeological and historical evidence (where available) that supports the Quranic and hadith narratives. The maps and illustrations help readers visualize the ancient civilizations where Prophets delivered their messages — the Mesopotamian cities of Prophet Ibrahim, the Egyptian settings of Prophet Musa, the Babylonian and Assyrian empires faced by Prophets Yunus and Ibrahim, the Arabian landscape of Prophet Muhammad's mission, and many others. Beyond the maps, the book includes timeline charts that show how the Prophetic missions relate to each other chronologically, genealogical charts tracing the lineages of the Prophets (particularly the family of Ibrahim), and information panels with key facts and Quranic references for each Prophet. This atlas format is particularly effective for Islamic school students who are visual learners, for parents teaching their children about the Prophets, and for anyone who wants to deepen their understanding of Quranic history by understanding the geographical and cultural contexts in which prophetic missions took place. At Rs. 7,000, this premium hardcover reference is a valuable addition to any Islamic library. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Historical Atlas of the Prophets & Messengers — English atlas with maps, timelines & illustrations of Prophetic missions. Premium hardcover. Order Bab-ul-Fatah."
  },
  {
    slug: "aqziya-tur-rasool-allah-2-vols-set",
    description: `Aqziya tur Rasool Allah (2 Volumes Set) is a comprehensive two-volume Urdu collection that documents the legal judgments, court cases, and judicial decisions made by the Prophet Muhammad (peace be upon him) during his lifetime as the head of the first Islamic state in Madinah. The word "aqziya" (plural of qadhiya) refers to specific legal cases or disputes that were brought before the Prophet for resolution, and this collection presents these cases with their complete contexts, the evidence and arguments presented by each party, and the Prophet's ruling along with the reasoning behind it. These judgments collectively form the foundational precedents of Islamic jurisprudence and provide invaluable insight into how Islamic law was practically applied by its greatest interpreter. The cases cover an extraordinarily wide range of legal areas: property disputes and boundary disagreements, commercial transactions and contract disputes, criminal cases including theft, assault, and murder, family law matters including marriage, divorce, custody, and inheritance, land and agricultural disputes, cases involving non-Muslim citizens of the Islamic state, and rulings on new situations that had no direct precedent in earlier revelation. Each case is presented with its source references from the major hadith collections and seerah works, along with commentary from classical Islamic jurists who analyzed the Prophet's legal reasoning. This two-volume set at Rs. 2,495 serves as an important reference for Islamic law students, legal professionals, qadis (Islamic judges), and anyone interested in understanding how the Prophet Muhammad (peace be upon him) — the greatest judge in human history — administered justice with wisdom, compassion, and strict adherence to divine guidance. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Aqziya tur Rasool Allah 2-vol set — Urdu collection of Prophet Muhammad's legal judgments & court cases. Islamic jurisprudence foundation. Order Bab-ul-Fatah."
  },
  {
    slug: "aap-ke-masail-aur-un-ka-hall-3vol",
    description: `Aap ke Masail Aur Un Ka Hall (3 Volume Set) is a comprehensive three-volume Urdu question-and-answer compendium that addresses hundreds of contemporary Islamic issues and problems that Muslims face in their daily lives, providing clear, evidence-based solutions from the Quran, authenticated Sunnah, and the consensus of Islamic scholars. This multi-volume set is organized by topic for easy reference, covering virtually every area of modern Muslim life: personal worship questions (prayer, fasting, charity, pilgrimage), family and marital issues (nikah, talaq, khula, maintenance, custody), business and financial matters (interest-free banking, investments, insurance, online transactions), social and community issues (inheritance, waqf, endowments), health and medical ethics (organ donation, IVF, euthanasia, abortion), technology-related questions (social media, digital transactions, online learning), dietary rulings (halal/haram food, slaughter, food additives), and contemporary challenges unique to Muslims living in the modern world. Each question is presented in a clear, straightforward manner followed by a detailed answer that cites the relevant Quranic verses, hadith narrations, and scholarly opinions that support the given ruling. Where scholarly differences of opinion exist on a particular issue, the book acknowledges these differences and presents the strongest evidence-based position while maintaining respect for other valid scholarly viewpoints. The three-volume format allows for thorough coverage without making individual books too unwieldy, and the topical organization makes it easy for readers to quickly find answers to specific questions as they arise in daily life. At Rs. 2,040 for the complete three-volume set, this comprehensive reference is an essential addition to every Muslim household library in Pakistan. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Aap ke Masail Aur Un Ka Hall 3-vol set — comprehensive Urdu Q&A on modern Islamic issues covering worship, finance, family & health. Order Bab-ul-Fatah."
  },
  {
    slug: "fazail-e-dawat",
    description: `Fazail e Dawat (Virtues of Dawah and Preaching) published by Daar ul Noor Islamabad is an Urdu book dedicated to the important subject of dawah — the Islamic duty of inviting others toward the path of Allah and conveying the message of Islam to both Muslims who need religious education and non-Muslims who may be unaware of Islam's true teachings. This book systematically presents the virtues, methodology, and practical guidelines for effective dawah work based on evidence from the Quran and authenticated hadith. The book establishes the theological foundation for dawah by citing the numerous Quranic verses that describe dawah as a defining characteristic of the Muslim community — "You are the best nation produced for mankind: you enjoin what is right and forbid what is wrong" (Surah Al Imran 3:110) — and by documenting how the Prophet Muhammad (peace be upon him) and his Companions prioritized dawah throughout their lives. It then provides practical guidance on the methodology of effective dawah including the importance of knowledge before speaking, using wisdom and beautiful preaching (hikmah wa maw'izah hasanah), adapting the approach to the audience's background and level of understanding, addressing common misconceptions about Islam, handling objections and difficult questions, the role of good character and personal conduct as a form of dawah, and the patience and perseverance required for long-term dawah work. The book also addresses the common pitfalls that dawah workers should avoid, including argumentativeness, harshness, and presenting personal opinions as religious rulings. Published by Daar ul Noor Islamabad, a respected Islamic publisher, this book at Rs. 350 is an affordable resource for dawah workers, Islamic school teachers, imams, and every Muslim who takes seriously the responsibility of sharing Islamic knowledge with others. Available at Bab-ul-Fatah with delivery across Pakistan.`,
    metaDescription: "Fazail e Dawat by Daar ul Noor — Urdu guide on Islamic dawah methodology, virtues & practical preaching techniques. Order at Bab-ul-Fatah."
  }
];

async function main() {
  let updated = 0;
  const failed = [];
  for (const item of descriptions) {
    try {
      await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log('Updated:', item.slug);
      updated++;
    } catch (e) {
      failed.push(item.slug);
      console.error('FAILED:', item.slug, e.message.substring(0, 80));
    }
  }
  await prisma.$disconnect();
  console.log(`\nDone: ${updated}/15 products updated`);
  if (failed.length) console.log('Failed slugs:', failed);
}

main().catch(console.error);
