const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "namaz-e-muhammadi-8x12",
    description: `Namaz e Muhammadi in the compact 8x12 inch format is a conveniently sized edition of the comprehensive prayer guide that documents the exact method of Salah as practised by the Prophet Muhammad, peace be upon him. This smaller dimensions edition retains all the scholarly content of the larger format while being designed for personal use in homes, offices, and during travel. The book fits easily into a bag or briefcase, making it a practical companion for individuals who wish to review the finer points of their prayer during commutes, breaks at work, or quiet moments at home. The content covers the complete prayer methodology from the opening Takbir through to the concluding Salam, with each posture and recitation described according to authentic hadith sources. The Arabic text for every supplication and Quranic recitation within the prayer is printed in a legible font with full diacritical marks, paired with Urdu transliteration and translation that serve readers who are building their Arabic proficiency alongside their prayer knowledge. A distinctive feature of this 8x12 edition is its reorganised layout that groups related information into concise sections, allowing readers to quickly locate specific rulings or recitations without flipping through extensive chapters. The book systematically categorises the obligatory elements of prayer, the sunnah components, and the recommended acts, making it straightforward for readers to understand the hierarchy of importance within each element of Salah. Practical guidance is provided for common situations that arise during prayer, including what to do when a mistake is made, how to perform the prostration of forgetfulness or Sujud al-Sahw, and what invalidates the prayer. The margins include cross-references to hadith sources so that readers can verify the authenticity of each practice. The soft cover binding keeps the weight minimal while the quality paper stock ensures durability through daily use. This edition is especially popular among individuals who have recently completed a formal prayer education course and want a portable reference that reinforces what they have learned. It is equally useful for parents who are teaching their children to pray and need a reliable quick-reference guide during the learning process.`,
    metaDescription: "Namaz e Muhammadi 8x12 is a compact Urdu prayer guide documenting the Prophet's Salah method with Arabic text, transliteration, and hadith references."
  },
  {
    slug: "namaz-e-nabvi-hisn-al-muslim-17x24",
    description: `Namaz e Nabvi and Hisn al Muslim combined in a single 17x24 inch volume represents one of the most comprehensive prayer and supplication references available in Urdu. This large-format edition brings together two essential works of Islamic practice: the first being a detailed guide to the Prophetic method of prayer covering every aspect from purification through the five daily prayers, Friday prayer, funeral prayer, and Taraweeh; and the second being the renowned compilation Hisn al Muslim, which gathers authentic supplications from the Quran and Sunnah for virtually every occasion a Muslim may encounter in daily life. The decision to combine these two works into a single binding reflects the natural relationship between the structured worship of Salah and the continuous remembrance of Allah through dua that should characterise a Muslim's daily routine. The prayer section covers each prayer position with precise descriptions, the Arabic text of every recitation, transliteration for Urdu speakers, and scholarly commentary that explains the evidences and reasoning behind each element of the Prophetic prayer method. The Hisn al Muslim section organises supplications thematically, with chapters covering morning and evening azkar, supplications before and after eating, prayers for travelling, duas for seeking forgiveness, supplications during illness, prayers for parents, invocations during times of difficulty, and many other categories. Each dua is presented with its Arabic source text, the hadith reference establishing its authenticity, and a clear Urdu translation. The 17x24 format allows for spacious typography that reduces eye strain during extended study sessions, and the large page size accommodates the extensive content without requiring an unwieldy number of pages. This combined volume is widely used as a textbook in madrasahs and Islamic educational institutions where both prayer methodology and daily supplications are taught as complementary subjects. The binding is designed for institutional durability, with reinforced stitching that withstands the demands of classroom use over multiple academic years. Scholars, teachers, students, and families seeking a single authoritative reference for both prayer and supplication will find this combined edition to be an exceptional resource.`,
    metaDescription: "Namaz e Nabvi and Hisn al Muslim 17x24 combines a Prophetic prayer guide with authentic daily supplications in a large-format Urdu reference edition."
  },
  {
    slug: "namaz-e-nabvi-hc-14x21",
    description: `Namaz e Nabvi in hard cover 14x21 format is a premium edition of the detailed prayer guide that meticulously documents the Salah methodology of the Prophet Muhammad, peace be upon him. This mid-sized hard cover edition occupies a practical middle ground between the larger institutional formats and smaller personal editions, making it equally suited for home libraries, office desks, and madrasah classrooms. The hard cover binding provides superior protection for the contents, ensuring that the book maintains its condition through years of regular reference and handling. Inside, the content follows a structured progression that begins with the prerequisites of prayer including purification, facing the Qiblah, and covering the awrah, before moving into a position-by-position walkthrough of the entire prayer. Each prayer posture is described with attention to the specific sunnah actions that accompany it, such as the placement of the right hand over the left on the chest during qiyam, the specific points of contact during ruku, the arrangement of fingers and toes during sujud, and the method of sitting between the two prostrations. The Arabic recitations for each position are presented in clear text with vowel marks, and each is accompanied by transliteration and Urdu translation. Where multiple authentic narrations exist for a particular element of the prayer, the book presents the various opinions with their supporting evidences, allowing readers to understand the breadth of scholarly interpretation while grounding their practice in established Prophetic tradition. The book includes detailed coverage of the Friday prayer, Eid prayers, the funeral prayer, the prayer during eclipses, the prayer for rain or Istisqa, and the Tahajjud or night prayer. Appendices provide quick-reference charts showing the structure and rakat count for each of the five daily prayers. The 14x21 page size offers comfortable readability without being cumbersome, and the premium paper quality gives the Arabic text excellent clarity and contrast. This edition is particularly favoured by individuals who want a durable, high-quality reference that will serve them for many years of daily use.`,
    metaDescription: "Namaz e Nabvi HC 14x21 is a durable hardcover Urdu guide to the Prophet's prayer method with Arabic text, transliteration, and scholarly footnotes."
  },
  {
    slug: "namaz-e-nabvi-hard-cover-imp",
    description: `Namaz e Nabvi in this imported hard cover edition is a specially sourced version of the Prophetic prayer guide that meets the highest standards of print quality and binding durability. Unlike locally produced editions, this imported version features premium materials including acid-free paper that resists yellowing over time, a reinforced spine that lies flat when the book is open, and a cover constructed from board-grade materials that protect against moisture, bending, and everyday wear. The production quality extends to the typography as well, with the Arabic text rendered in a calligraphic Naskh font that maximises legibility and aesthetic appeal, while the Urdu commentary is set in a clean, modern typeface that ensures comfortable reading during extended study sessions. The content itself covers the complete methodology of the Prophetic prayer with comprehensive detail, documenting every obligatory act, sunnah practice, and recommended action according to the strongest evidences from authentic hadith collections. The imported edition distinguishes itself through its scholarly apparatus, which includes extensive footnotes referencing specific hadith numbers from Sahih al-Bukhari, Sahih Muslim, Sunan Abu Dawud, Sunan al-Tirmidhi, Sunan al-Nasai, and Sunan Ibn Majah. These references allow scholars and advanced students to trace every ruling back to its primary source. The book also features a detailed introduction that discusses the methodology used in compiling the prayer guide, the criteria applied in selecting between differing scholarly opinions, and the principles of fiqh that undergird the rulings presented. The prayer descriptions cover not only the standard five daily prayers but also special prayers including the prayer of the traveller, the prayer during fear, the prayer of a sick person, and the make-up prayers for those who have missed obligatory prayers. A comprehensive index at the end of the book allows readers to locate specific topics quickly. This imported hard cover edition is recommended for serious students of Islamic sciences, mosque libraries, and institutions where a premium quality reference work is desired for long-term use.`,
    metaDescription: "Namaz e Nabvi Hard Cover Imported edition offers premium print quality for this comprehensive Urdu Prophetic prayer guide with hadith references."
  },
  {
    slug: "namaz-kay-masail",
    description: `Namaz Kay Masail is a well-organised Urdu-language reference book that systematically addresses the rulings and practical issues related to the five daily prayers. Written in a question-and-answer format that makes it highly accessible for readers of all educational backgrounds, this book covers an extensive range of topics that arise in the daily practice of Salah. The content is divided into logical sections beginning with the prerequisites and conditions of prayer, moving through the obligatory and sunnah components, and concluding with situations that invalidate the prayer and require repetition. Among the many topics addressed are the rulings for praying while travelling, the method of combining and shortening prayers during journeys, the procedure for making up missed prayers, the rules governing prayer during illness when standing is not possible, the permissibility of praying while seated or lying down, the ruling on praying in shoes, the etiquette of the mosque, and the appropriate conduct during the Friday sermon. The book also addresses common contemporary questions that many Muslims face, such as the ruling on praying in an airplane, the permissibility of using a prayer timetable application, the status of prayer in a room where there are images, and the method of determining the Qiblah direction when no clear indicator is available. Each answer is supported by references to the relevant Quranic verse or hadith, and the author includes the opinions of major scholars from the four schools of Islamic jurisprudence where significant differences of opinion exist. The question-and-answer structure serves a dual purpose: it allows readers to find quick answers to specific practical concerns, and it naturally covers a broader range of topics than a traditional narrative format would permit. The language is straightforward and avoids unnecessary technical terminology, making the book suitable for readers who have not undergone formal Islamic education. An alphabetical index at the end enables efficient navigation to specific topics. This book serves as an essential household reference for Urdu-speaking Muslim families and is frequently used by imams and religious teachers who need to provide accurate answers to community members' questions about prayer.`,
    metaDescription: "Namaz Kay Masail is a practical Urdu Q&A reference covering prayer rulings, travel prayers, contemporary issues, and fiqh for daily Salah practice."
  },
  {
    slug: "namaz-ke-baad-masnoon-azkaar-flax",
    description: `Namaz Ke Baad Masnoon Azkaar in flex print format is a practical and durable reference card that presents the authentic supplications recommended to be recited after completing the five daily prayers. The flex printing technology used in this production gives the material a smooth, flexible, and water-resistant quality that makes it significantly more durable than standard paper-based cards, allowing it to be kept near the prayer area, tucked into a prayer mat, or carried in a pocket without risk of damage from folding or moisture. The card collects the post-prayer azkar that have been authentically narrated from the Prophet Muhammad, peace be upon him, including the declaration of faith recited after each prayer, the Tasbih of Fatimah which consists of thirty-three repetitions of Subhan Allah, thirty-three repetitions of Alhamdulillah, and thirty-four repetitions of Allahu Akbar, the Ayat al-Kursi, the three Quls, and additional supplications for forgiveness and protection. Each dua is presented with the complete Arabic text in a clear, readable font with full vowel marks, accompanied by Urdu transliteration and translation so that readers can both pronounce the words correctly and understand their meanings. The layout is designed for ease of use during the immediate moments after prayer, with the azkar arranged in the order they are traditionally recited and numbered sequentially to help the reader keep track of progress through the routine. The card format is intentionally concise, focusing solely on the post-prayer remembrances without additional commentary, making it ideal for individuals who have already learned the rulings but need a reliable memory aid for the exact wording. The compact size and lightweight construction mean it can be placed on a stand beside the prayer mat or attached to a wall near the prayer area for quick reference. This flex print card is particularly useful for new Muslims, children who are learning their daily azkar, and anyone who wishes to establish a consistent habit of post-prayer remembrance. The durable material ensures that this reference will remain legible and intact through months and years of daily use.`,
    metaDescription: "Namaz Ke Baad Masnoon Azkaar Flex Print presents authentic post-prayer supplications on a durable card with Arabic text and Urdu translation."
  },
  {
    slug: "namaz-ki-masnoon-duain-flex",
    description: `Namaz ki Masnoon Duain in flex print format is a focused reference card that compiles the Prophetic supplications recited during the prayer itself, distinct from the post-prayer azkar. This card serves as an essential companion for Muslims who are in the process of memorising the duas that are part of the prayer or who wish to verify the exact wording and sequence of supplications they recite during Salah. The supplications covered include the opening dua of the prayer or Istiftah, the dua recited during ruku or bowing, the tasbeeh and dua said between the two prostrations, the supplication of prostration or Sujud, the dua recited in the final sitting or Tashahhud, and the durood and final supplication before the Salam. Multiple authentic versions of each dua are included where the Prophet Muhammad, peace be upon him, was recorded as having used different wordings, allowing readers to choose from among the verified options. The Arabic text is printed in a large, clear font with full diacritical marks to ensure correct pronunciation, and each dua is paired with Urdu transliteration that follows standard conventions and a clear Urdu translation. The flex print medium provides exceptional durability compared to traditional paper, being resistant to tearing, water damage, and the wear that comes from repeated folding and unfolding. This makes the card suitable for placement in a variety of locations including beside the prayer mat at home, inside a mosque, or in a bag for use while travelling. The card's compact dimensions are carefully calculated to be large enough for comfortable reading while remaining unobtrusive in the prayer space. The sequential numbering of each dua corresponds to the order in which they occur within the prayer, helping users develop the correct flow and habit. Islamic teachers and madrasah instructors frequently recommend this card as a supplementary tool for students who are learning to pray, as it provides a reliable reference that students can consult between prayer attempts. The minimalist design focuses attention entirely on the content without distracting decorative elements.`,
    metaDescription: "Namaz ki Masnoon Duain Flex Print collects Prophetic supplications recited during Salah on a durable card with Arabic text and Urdu transliteration."
  },
  {
    slug: "namaz-se-pehle-new-edition",
    description: `Namaz se Pehle in its new edition is a revised and expanded Urdu-language guide that focuses specifically on the sunnah acts, recommended supplications, and spiritual preparations that should precede the five daily prayers. While many prayer guides concentrate on the prayer itself, this book addresses the often-overlooked preparatory phase that precedes Salah, recognising that the quality of one's prayer is deeply influenced by the state of mind, body, and spirit at the moment the prayer begins. The new edition includes substantial updates and additions over the previous version, with expanded chapters, additional hadith references, and newly included topics that reflect contemporary questions from the Muslim community. The book opens with a discussion of the spiritual preparation for prayer, including the concept of khushu or concentration and the methods the early Muslims used to cultivate a present, attentive state of mind before standing for Salah. Subsequent chapters cover the practical sunnah acts before prayer, such as the use of the miswak, wearing clean and presentable clothing, applying perfume where available, and walking to the mosque with dignity and composure. A comprehensive section details the Adhan and Iqamah, explaining their wording, virtues, the appropriate response for the listener, and the dua that should be recited after hearing each call to prayer. The book then addresses the recommended supplications to be recited between the Adhan and the Iqamah, the dua upon entering the mosque, the two rakat of Tahiyyat al-Masjid or the greeting of the mosque, and the recommended acts while waiting for the congregational prayer to begin. The new edition adds a chapter on the spiritual dimensions of waiting for prayer, discussing how the time spent in the mosque before Salah can be used for dhikr, Quran recitation, and making dua. Updated fatwas address modern situations such as preparing for prayer in an office environment, a shopping centre prayer room, or while travelling. The revised edition features improved typography and a reorganised index that makes navigation more intuitive. This book is recommended for anyone who wishes to approach their prayer with greater mindfulness and preparation.`,
    metaDescription: "Namaz se Pehle New Edition is an expanded Urdu guide covering sunnah acts, supplications, and spiritual preparation before the five daily prayers."
  },
  {
    slug: "namaz-e-mustafa-anwaar-us-salah",
    description: `Namaz-e-Mustafa: Anwaar-us-Salah is an illuminating Urdu work that presents the methodology of the Prophet's prayer within a framework of spiritual insight and practical instruction. The title, meaning Illuminations of Prayer, reflects the author's approach of combining detailed fiqh-based guidance on prayer mechanics with the inner dimensions of worship that elevate Salah from a mechanical ritual to a profound spiritual experience. The book begins by establishing the foundational concept that prayer is the mi'raj or ascension of the believer, drawing upon the famous hadith in which the Prophet described prayer as the coolness of his eyes and the delight of his heart. This thematic opening sets the tone for a work that consistently emphasises both the outward precision and inward devotion that characterise the perfected prayer. The detailed walkthrough of each prayer position includes not only the physical requirements and sunnah actions but also the spiritual states and mental focuses recommended by the early scholars for each posture. For example, during ruku, the reader learns both how to bow correctly and what to contemplate about the majesty of Allah while in that position; during sujud, the physical technique is accompanied by guidance on what the heart should feel when the forehead touches the ground in the most humble posture of worship. The book presents the Arabic text of every recitation within the prayer with vowel marks, transliteration, and Urdu translation, along with explanations of the linguistic beauty and spiritual depth of the chosen words. The author has drawn upon a wide range of classical and contemporary sources, including the works of Imam Ghazali, Ibn al-Qayyim, and the hadith commentaries of major scholars, to provide a multi-layered understanding of each element of prayer. The book addresses the common spiritual obstacles that prevent Muslims from achieving concentration in prayer, offering practical and spiritual remedies drawn from the Prophetic tradition. Chapters are dedicated to the virtues of each of the five daily prayers, explaining why each was specifically ordained at its particular time and what unique spiritual benefits it offers. This work is suited for readers who have already learned the basic mechanics of prayer and wish to deepen both their knowledge and their spiritual engagement with Salah.`,
    metaDescription: "Namaz-e-Mustafa Anwaar-us-Salah combines detailed prayer methodology with spiritual insights for Urdu readers seeking deeper engagement in daily Salah."
  },
  {
    slug: "namaz-e-nabvi-hisn-ul-muslim-14x21",
    description: `Namaz-e-Nabvi and Hisn-Ul-Muslim combined in a 14x21 inch volume offers a medium-format edition of the dual-purpose Islamic reference that pairs a comprehensive Prophetic prayer guide with the most widely trusted collection of authentic daily supplications. This 14x21 format strikes an ideal balance between portability and readability, making it a versatile choice for personal study at home, use in the mosque, and reference in educational settings. The Namaz-e-Nabvi section provides an exhaustive treatment of the prayer methodology as practised by the Prophet Muhammad, peace be upon him, covering the five daily prayers, Jumuah prayer, Eid prayers, funeral prayer, eclipse prayer, and the prayer during times of fear. Each prayer is documented with the exact Arabic recitations, physical postures, and sunnah actions, supported by references to authentic hadith collections. Where multiple narrations exist for a particular element, the book presents the variants with their chains of transmission, enabling educated readers to understand the evidential basis for each practice. The Hisn-Ul-Muslim section, authored by the renowned scholar Sa'id al-Qahtani, is included in its complete form with Urdu translation and commentary. This fortress of the Muslim compiles authenticated supplications from the Quran and Sunnah covering every dimension of daily life: waking and sleeping, eating and drinking, entering and leaving the home, travelling, wearing clothing, visiting the sick, attending funerals, seeking knowledge, facing trials, and many more situations. Each dua entry includes the Arabic text, its source reference, and a faithful Urdu translation that preserves the meaning and tone of the original. The two sections are linked through a shared index and cross-referencing system that allows readers to move seamlessly between the structured worship of Salah and the continuous remembrance of Allah through daily supplication. The 14x21 page size provides adequate space for clear typography without being excessively large, and the quality paper stock ensures that the Arabic text renders with excellent definition. This combined volume is one of the most frequently recommended references for Muslim households, madrasah libraries, and individuals seeking a single comprehensive resource for both prayer and daily azkar in Urdu.`,
    metaDescription: "Namaz-e-Nabvi and Hisn-Ul-Muslim 14x21 pairs a Prophetic prayer guide with authenticated daily supplications in a portable Urdu dual-reference edition."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
