const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "mein-tawbah-krna-chahta-hun-lekin",
    description: `Mein Tawbah Karna Chahta Hun Lekin — "I Want to Repent But..." — is a practical and spiritually uplifting Urdu book that directly addresses the psychological and emotional barriers that prevent people from turning to Allah in sincere repentance. The title captures a sentiment experienced by countless Muslims who recognize their sins and feel the urge to seek forgiveness yet find themselves held back by doubt, shame, or a sense that their wrongdoing is too great to be pardoned. This book dismantles those barriers one by one, offering readers a clear, compassionate, and evidence-based path back to their Lord.

The author begins by explaining the true nature of repentance (tawbah) in Islamic teaching — what it requires, what it accomplishes, and how Allah's mercy operates in relation to human shortcomings. Drawing extensively from the Quran and authenticated Hadith, the book establishes that Allah's doors of forgiveness are never closed to a servant who approaches Him with genuine sincerity. Specific Quranic verses such as "O My servants who have transgressed against themselves, do not despair of the mercy of Allah" receive detailed commentary that addresses the misunderstandings and spiritual despair that often accompany persistent sinning.

Each chapter of this book tackles a specific obstacle to repentance that the author has identified through pastoral experience and scholarly analysis. The feeling that one's sins are too numerous or too grave is addressed by citing the Prophetic Hadith about Allah's mercy outstripping His anger and the narration that every son of Adam sins, and the best of sinners are those who repent. The fear of hypocrisy — the worry that repenting and then sinning again makes one a hypocrite — is answered with scholarly nuance that distinguishes between the weakness of human nature and the conscious deception of nifaq. The book also addresses the procrastination trap, the social embarrassment of admitting wrongdoing, the fear of losing face before family and community, and the mistaken belief that certain categories of sin cannot be forgiven. For each obstacle, the author provides practical spiritual prescriptions — specific duas, acts of worship, mental reframing techniques, and behavioral strategies — that help the reader move from the paralysis of guilt to the active practice of tawbah. This book is a lifeline for any Muslim struggling with the weight of past mistakes, offering them both the theological assurance and the practical tools needed to rebuild their relationship with Allah.`,
    metaDescription: "Mein Tawbah Karna Chahta Hun Lekin is a Urdu guide addressing common obstacles to repentance with Quranic wisdom, Hadith, and practical advice."
  },
  {
    slug: "memoirs-of-repentant-people",
    description: `Memoirs of Repentant People is a compelling English-language collection of real-life accounts from individuals who once lived lives of sin, deviation, or spiritual neglect and subsequently experienced a genuine transformation through the grace of Allah and the power of sincere repentance. Unlike theoretical discussions of tawbah, this book presents the raw, unfiltered narratives of people who walked away from Islam or immersed themselves in wrongdoing before finding their way back — their stories told in their own words or through carefully documented accounts that preserve the authenticity and emotional power of each journey.

The book features a diverse range of stories that demonstrate the breadth of Allah's mercy and the many paths that can lead a person back to faith. Some accounts describe individuals who grew up in Muslim families but drifted into secular lifestyles, substance abuse, or criminal behavior before a defining moment — a near-death experience, a conversation, a dream, or an encounter with the Quran — awakened their spiritual consciousness. Others recount the journeys of people who converted to Islam from other faiths or from atheism, describing the intellectual and emotional processes that brought them to recognize the truth of Islam and commit their lives to it. Each memoir captures the internal struggle between old habits and new convictions, the social pressures and personal losses that often accompany a life change of this magnitude, and the profound peace and purpose that ultimately come from returning to Allah.

What makes Memoirs of Repentant People particularly powerful is its unflinching honesty about the difficulty of change. The stories do not present repentance as a simple, instantaneous event but as a process — often messy, frequently marked by setbacks and relapses, yet sustained by hope and divine assistance. Readers who are struggling with their own faith will find these accounts deeply relatable and encouraging, recognizing their own doubts and difficulties mirrored in the experiences of others who successfully navigated the same terrain. The book also includes reflections from scholars and counselors who provide Islamic context and guidance for readers who wish to begin their own journey of repentance. This collection serves as both a source of inspiration and a practical testament to the Quranic promise that Allah loves those who turn to Him in repentance and purify themselves.`,
    metaDescription: "Memoirs of Repentant People presents real-life stories of individuals who transformed their lives through sincere repentance and returned to Islamic faith."
  },
  {
    slug: "men-and-the-universe-reflections-of-ibn-al-qayyem",
    description: `Men and the Universe: Reflections of Ibn al-Qayyim is an English translation and compilation of the profound cosmological and philosophical observations of Imam Ibn al-Qayyim al-Jawziyyah, one of the most celebrated scholars in Islamic intellectual history and a devoted student of the renowned Imam Ibn Taymiyyah. This book gathers Ibn al-Qayyim's reflections on the relationship between human beings and the created universe — a topic to which he devoted considerable attention in several of his major works, most notably in his celebrated book "Madarij al-Salikin" and "Shifa al-Alil." The compilation presents his insights in an accessible English format, making the profound worldview of this classical scholar available to contemporary readers who may not have access to his original Arabic texts.

Ibn al-Qayyim's approach to understanding the universe is deeply rooted in the Quranic worldview, which presents the natural world as a system of signs (ayat) pointing toward the existence, wisdom, and majesty of the Creator. In this compilation, his reflections cover a remarkable range of topics — the purpose behind the creation of the heavens and the earth, the significance of the alternation of day and night, the wisdom embedded in the diversity of living creatures, the spiritual lessons contained in natural phenomena such as rain, wind, mountains, and oceans, and the relationship between the physical universe and the unseen realities of the human soul. Each reflection demonstrates Ibn al-Qayyim's characteristic method of moving from observation of the natural world to deep spiritual insight, connecting physical phenomena to metaphysical truths in a way that enriches both the reader's understanding of creation and their relationship with the Creator.

The book also explores Ibn al-Qayyim's perspectives on humanity's place within the cosmic order — the unique status of human beings as Allah's khalifah (vicegerent) on earth, the relationship between the human soul and the material world, the spiritual diseases that arise from excessive attachment to worldly pleasures, and the path to restoring the proper balance between engaging with creation and remembering the Creator. His reflections on time, mortality, and the transient nature of worldly life are particularly moving, encouraging readers to view their brief existence in the context of the eternal. The English translation preserves the literary beauty and intellectual depth of Ibn al-Qayyim's original prose while making his complex ideas accessible to modern readers. This book is an invaluable resource for anyone interested in Islamic philosophy, spirituality, or the intellectual heritage of one of Islam's greatest thinkers.`,
    metaDescription: "Men and the Universe presents Ibn al-Qayyim's profound reflections on creation, cosmology, and humanity's place in the universe in accessible English."
  },
  {
    slug: "men-and-women-around-the-messenger-pbuh",
    description: `Men and Women Around the Messenger (PBUH) is a comprehensive biographical work in English that presents detailed life accounts of the men and women who formed the inner circle of Prophet Muhammad's companions — the Sahabah and Sahabiyyat whose lives were transformed by their proximity to the Prophet and whose example continues to illuminate the Muslim Ummah more than fourteen centuries after their passing. This book goes beyond brief character sketches to provide substantive, well-researched biographies that capture the full arc of each companion's life — their background before Islam, their encounter with the Prophet's message, their contributions during the Prophet's lifetime, and their legacy after his death.

The book covers a broad cross-section of the Prophet's companions, representing the diversity of the early Muslim community. Readers encounter the well-known figures whose names are familiar to every Muslim — Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, and Ali ibn Abi Talib — but also meet lesser-known companions whose stories are no less inspiring. The accounts include companions who were among the earliest converts to Islam, those who migrated to Abyssinia and then to Madinah, warriors who fought at Badr, Uhud, and other pivotal battles, scholars who memorized and transmitted the Quran and Hadith, women who made significant contributions to the community's social and intellectual life, and individuals from diverse tribal, ethnic, and social backgrounds who found unity under the banner of Islam.

A distinctive feature of this book is its balanced treatment of both male and female companions, giving equal attention and scholarly rigor to the biographies of the Sahabiyyat. The stories of Khadijah bint Khuwaylid, Aisha bint Abi Bakr, Fatimah bint Muhammad, Hafsa bint Umar, Umm Salamah, and many other notable women are presented with the same depth and detail as their male counterparts, highlighting their intellectual contributions, their courage, their spiritual devotion, and their indispensable roles in the formation of the Muslim community. Each biography draws upon authentic Hadith collections, classical historical sources, and respected biographical works to present an accurate and inspiring account. The book also contextualizes each companion's life within the broader narrative of Islamic history, helping readers understand how individual lives intertwined with the collective story of the early Muslim community. For anyone seeking to understand the human foundation upon which Islamic civilization was built, Men and Women Around the Messenger offers a rich, detailed, and deeply moving portrait of the generation that the Prophet described as the best of all generations.`,
    metaDescription: "Men and Women Around the Messenger PBUH offers detailed English biographies of the Prophet's male and female companions, their lives and legacy."
  },
  {
    slug: "men-in-captivity",
    description: `Men In Captivity is a powerful and sobering English-language book that addresses the experience of Muslims who have been imprisoned, detained, or otherwise held in captivity — whether for their religious beliefs, political circumstances, or the trials that Allah has decreed for them. The book examines the concept of captivity and imprisonment through the dual lens of Islamic theology and practical guidance, drawing upon the Quranic narratives of prophets and believers who faced imprisonment, the Hadith literature on the virtues and trials of the imprisoned, and the scholarly tradition of Islamic jurisprudence regarding the rights and duties of captives.

The book opens with a thorough Quranic survey of imprisonment and captivity as themes in divine scripture. The story of Prophet Yusuf (Joseph), peace be upon him, who spent years in prison after being falsely accused, receives extensive treatment as the primary Quranic model of a righteous believer maintaining faith and dignity under captivity. The author analyzes how Prophet Yusuf's experience in prison became a means of dawah (invitation to Islam), personal spiritual growth, and eventual elevation to a position of authority — demonstrating that captivity in the Islamic worldview is not a dead end but a test that can become a source of blessing. Other Quranic references to captivity, including the treatment of prisoners of war and the broader concept of being held against one's will, are examined to build a comprehensive Islamic theology of captivity.

Men In Captivity also addresses the practical and spiritual needs of Muslims who are currently imprisoned or facing detention. The book provides guidance on maintaining the five daily prayers in confinement, preserving one's faith and moral compass in a challenging environment, dealing with loneliness, depression, and despair, using the time of imprisonment for productive spiritual and intellectual development, and maintaining hope in Allah's mercy and ultimate justice. Specific chapters address the rights of prisoners in Islamic law, the obligation of the Muslim community to advocate for the unjustly imprisoned, the ethics of visiting and supporting prisoners, and the spiritual rewards promised to those who help secure the freedom of captives. The book draws upon the writings of classical scholars such as Ibn Taymiyyah, who himself spent time in prison and produced some of his most important works during his detention, and Imam Ahmad ibn Hanbal, who endured imprisonment with remarkable steadfastness. Real-life accounts of contemporary Muslims who have maintained their faith under captivity are interwoven with the classical material, creating a work that is both spiritually nourishing and practically relevant.`,
    metaDescription: "Men In Captivity examines Islamic perspectives on imprisonment, offering spiritual guidance and Quranic wisdom for Muslims facing detention and trials."
  },
  {
    slug: "mera-jeena-mera-marna",
    description: `Mera Jeena Mera Marna — "My Life, My Death" — is a thought-provoking Urdu book that presents the Islamic perspective on the two most fundamental realities of human existence: life and death. Written to address the widespread neglect of these topics in contemporary Muslim consciousness, this book guides readers through what Islam teaches about the purpose of life, the inevitability and meaning of death, and the eternal existence that follows. The title itself frames the discussion in personal terms, reminding every reader that both their life and their death are deeply personal matters for which they will be individually accountable before Allah.

The book begins with a thorough exploration of the Islamic understanding of life (hayat) — not merely as a biological phenomenon but as a sacred trust (amanah) from Allah that carries profound responsibilities. The author explains the Quranic concept that human life has a defined purpose: to worship Allah, to steward the earth as His vicegerent, and to prepare for the eternal life of the Hereafter. Drawing upon Quranic verses, Prophetic Hadith, and the writings of classical Islamic scholars, the book examines how every aspect of human existence — from the daily routine to major life decisions — should be oriented toward this ultimate purpose. The discussion covers the Islamic view of time as a finite and precious resource, the importance of intention (niyyah) in giving meaning to daily actions, and the danger of living a life that is merely reactive and purposeless.

The section on death (maut) is equally comprehensive and equally necessary in an age where death is often avoided as a topic of reflection. The book presents the Islamic teachings on the nature of death as a transition rather than an annihilation, the events that follow death according to authentic Hadith — including the questioning in the grave, the barzakh (intermediate state), and the Day of Judgment — and the practical implications of these beliefs for how a Muslim should live. The author addresses common fears and misconceptions about death with both theological precision and pastoral sensitivity, helping readers develop a healthy relationship with mortality that motivates rather than paralyzes. Special attention is given to practical preparations for death — writing a will, settling debts, maintaining family ties, and accumulating good deeds that will serve the believer after their earthly life has ended. Mera Jeena Mera Marna is not a morbid book but an empowering one, encouraging readers to take ownership of both their life and their death in a way that brings meaning, purpose, and peace to every moment of their existence.`,
    metaDescription: "Mera Jeena Mera Marna is a Urdu book presenting the Islamic perspective on life's purpose, death, and the Hereafter with Quranic and Hadith guidance."
  },
  {
    slug: "meray-aslaaf",
    description: `Meray Aslaaf — "My Predecessors" or "My Ancestors" — is a rich Urdu biographical and historical work that celebrates the lives, achievements, and spiritual legacy of the great Muslim scholars, saints, reformers, and leaders who preceded the current generation and laid the foundations upon which Islamic civilization was built. The word "aslaaf" (singular: salaf) carries deep significance in Islamic culture, referring to the pious predecessors whose knowledge, piety, and sacrifice established the standards of excellence that subsequent generations have aspired to. This book brings the stories of these remarkable individuals to life, connecting contemporary readers with the intellectual and spiritual heritage of their forebears.

The book spans a broad historical period, covering figures from the earliest generations of Islam through the classical and medieval periods of Islamic civilization. The biographies include companions of Prophet Muhammad (peace be upon him) who carried the message of Islam to distant lands, the great Imams of Islamic jurisprudence whose legal methodologies continue to guide Muslim practice today, the traditionists (muhaddithin) who devoted their lives to preserving the words of the Prophet, the theologians and philosophers who defended Islamic doctrine against intellectual challenges, the Sufi masters who cultivated the inner dimensions of faith, and the rulers and military leaders who established and defended Muslim polities. Each biography is written with careful attention to historical accuracy, drawing upon authentic sources while maintaining an engaging narrative style that makes the material accessible to general readers.

What distinguishes Meray Aslaaf from a simple biographical dictionary is the author's intention to inspire contemporary Muslims by demonstrating what is possible when faith is combined with knowledge, dedication, and moral courage. Each chapter concludes with reflections on the lessons that modern readers can draw from the life of the featured predecessor — lessons about perseverance in seeking knowledge, sacrificing comfort for the sake of truth, maintaining moral integrity in the face of temptation, and balancing worldly engagement with spiritual focus. The book argues that reconnecting with the legacy of the aslaaf is not an exercise in nostalgia but a practical necessity for a Muslim community that has, in the author's view, lost touch with the standards and values that once defined its greatness. The writing style combines the elegance of classical Urdu prose with the clarity needed for modern readership, creating a work that functions simultaneously as historical scholarship, spiritual literature, and a call to personal and communal renewal.`,
    metaDescription: "Meray Aslaaf is a Urdu biographical work celebrating the lives and legacy of great Muslim scholars, saints, and leaders who shaped Islamic civilization."
  },
  {
    slug: "meray-pyary-rasool-saw-imported",
    description: `Meray Pyary Rasool (SAW) — "My Beloved Prophet" — is a lovingly written Urdu book that presents the life and character of Prophet Muhammad (peace be upon him) in a narrative style designed to deepen the reader's emotional and spiritual connection with the Messenger of Allah. This imported edition brings to Urdu readers a work that has been cherished for its ability to convey not just the historical facts of the Prophet's life but the profound love and reverence that every Muslim should hold for him. The title itself — "My Beloved Prophet" — establishes the personal, intimate tone that pervades the entire book, inviting readers to approach the Prophet's seerah not as an academic subject but as the story of the most beloved person in their lives.

The book traces the complete life journey of Prophet Muhammad (peace be upon him) from his birth in Makkah through his childhood, his youth, his prophethood, the struggles of the Makkan period, the establishment of the Islamic state in Madinah, the major battles and treaties, the conquest of Makkah, the farewell pilgrimage, and his passing from this world. Each phase of the Prophet's life is presented with careful attention to historical detail, supported by references to authenticated Hadith and classical seerah sources such as the works of Ibn Hisham, Ibn Ishaq, and Imam al-Waqidi. However, the factual narrative is consistently enriched with reflections on the moral and spiritual lessons embedded in each event, encouraging readers to see the Prophet's life not merely as history but as a living guide for their own conduct and character.

The imported edition of Meray Pyary Rasool is distinguished by its production quality — superior printing, clear typography, and durable binding that does justice to the importance of its content. The Urdu prose is refined and accessible, suitable for readers of various educational backgrounds. Special attention is given to aspects of the Prophet's character that are particularly relevant to contemporary Muslims — his mercy and compassion, his treatment of women and children, his approach to justice and forgiveness, his simplicity of lifestyle despite his authority, his sense of humor, and his interactions with people of different faiths. The book includes discussions of the Prophet's physical appearance (his shamail), his daily habits and routines, his manner of worship, and the specific ways in which his companions expressed their love for him. For anyone seeking to strengthen their relationship with Prophet Muhammad (peace be upon him) and to understand why he is described in the Quran as "an excellent example," this imported edition of Meray Pyary Rasool offers a beautiful and comprehensive resource.`,
    metaDescription: "Meray Pyary Rasool SAW imported edition presents the Prophet's life in eloquent Urdu, deepening love and connection with the Messenger of Allah."
  },
  {
    slug: "mere-sunehray-safarnaamay",
    description: `Mere Sunehray Safarnaamay — "My Golden Travels" — is an engaging Urdu travelogue that documents the author's journeys to various places of historical, religious, and cultural significance in the Muslim world and beyond. Unlike dry itinerary-based travel writing, this book combines vivid descriptive prose with personal reflection, historical context, and spiritual observation to create a travel narrative that educates, entertains, and inspires. The word "sunehray" (golden) in the title suggests that these are not ordinary journeys but experiences that yielded precious memories, insights, and lessons — golden moments that the author has captured in prose for the benefit of his readers.

The travelogue covers visits to a range of destinations, each described with the author's characteristic attention to the sensory details that bring a place to life — the sights, sounds, smells, textures, and atmosphere that a casual visitor might overlook but a thoughtful writer captures and conveys. The narratives include journeys to the holy cities of Makkah and Madinah, where the author describes not only the grandeur of the Haramain but also the intimate moments of worship and reflection that these sacred spaces inspire. Visits to historical sites associated with Islamic heritage — ancient mosques, tombs of scholars and saints, battlefields, and archaeological remains — are presented with thorough historical background that transforms each location from a mere tourist stop into a window into centuries of Islamic civilization.

What elevates Mere Sunehray Safarnaamay beyond conventional travel literature is the author's ability to weave personal spiritual reflections into the descriptive fabric of each journey. At each destination, the author pauses to consider what the place teaches about faith, history, human achievement, and the passage of time. The descriptions of natural landscapes — mountains, deserts, coastlines, and forests — are infused with the Quranic perspective on nature as a book of divine signs, encouraging readers to see the beauty of the natural world as an invitation to know its Creator. The encounters with local people, their customs, their hospitality, and their stories add a human dimension to the travel narrative that creates genuine emotional connection between the reader and the places being described. The Urdu prose style is literary yet accessible, employing the rich vocabulary and metaphorical range of the Urdu language without becoming opaque to general readers. For armchair travelers, prospective pilgrims, and anyone who appreciates well-crafted Urdu prose that combines travel, history, and spirituality, Mere Sunehray Safarnaamay offers a richly rewarding reading experience.`,
    metaDescription: "Mere Sunehray Safarnaamay is a captivating Urdu travelogue combining vivid descriptions, historical insights, and spiritual reflections."
  },
  {
    slug: "meri-namaaz-sunnat-e-nabwi-k-mutabik-tareeka-e-namaaz",
    description: `Meri Namaaz: Sunnat-e-Nabwi ke Mutabiq Tareeka-e-Namaaz — "My Prayer: The Method of Prayer According to the Prophetic Sunnah" — is a meticulously detailed Urdu guidebook that teaches the correct way to perform the five daily Islamic prayers exactly as Prophet Muhammad (peace be upon him) performed them. In a time when variations in prayer methodology have become a source of confusion and disagreement among Muslims, this book provides a comprehensive, evidence-based reference that traces every movement, position, and recitation of the prayer back to authenticated narrations from the Prophet and his companions.

The book follows a systematic, step-by-step approach that breaks down the prayer into its individual components — each explained with the highest level of detail. The opening takbeer (Allahu Akbar), the placement of the hands, the recitation of Surah Al-Fatihah and additional Quranic verses, the ruku (bowing) with its specific dhikr, the standing after ruku, the two prostrations (sujud) with their exact supplications, the sitting between the two prostrations, the tashahhud in its complete form, the durood upon the Prophet, and the final supplications before the salam — every element of the prayer is described with precision, accompanied by references to the specific Hadith narrations that establish the Prophet's practice. The author pays particular attention to points where there are differences of opinion among scholars, presenting the evidence for each view and explaining which position is most strongly supported by the Hadith.

Beyond the mechanical description of prayer movements, Meri Namaaz addresses the inward dimensions that are essential for the prayer to be accepted. The book discusses the requirements of khushu (concentration and humility in prayer), the correct intention (niyyah), the importance of understanding what is being recited, and the common mistakes that diminish the quality of prayer — such as hastening through the movements, looking around during prayer, and failing to achieve tranquility (tuma'ninah) in each position. Specific chapters are devoted to the congregational prayer, the Friday prayer, the Eid prayers, the funeral prayer, the prayer during travel, the Taraweeh prayer of Ramadan, and the voluntary (nafl) prayers that the Prophet recommended. The book also covers the prerequisites of prayer — ablution (wudu), the proper covering (satr), the direction of the qiblah, and the times at which prayer is prohibited. Illustrated diagrams clarify the physical positions of prayer, and the Arabic supplications are provided alongside their Urdu translations. For any Muslim who wishes to ensure that their daily prayers conform as closely as possible to the Prophetic method, this book serves as an authoritative and accessible reference that brings the Sunnah of prayer within reach of every reader.`,
    metaDescription: "Meri Namaaz is a detailed Urdu guide teaching the correct method of Islamic prayer according to the Prophetic Sunnah with Hadith references."
  }
];

async function main() {
  for (const item of updates) {
    const result = await prisma.product.update({
      where: { slug: item.slug },
      data: {
        description: item.description,
        metaDescription: item.metaDescription
      }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done - updated", updates.length, "products");
}

main().then(() => prisma.$disconnect());
