const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "asaan-tarjuma-quran-mufti-taqi-usmani",
    description: `Asaan Tarjuma Quran by Mufti Taqi Usmani represents one of the most trusted and widely respected Urdu translations of the Holy Quran produced in the modern era. Mufti Muhammad Taqi Usmani, a globally recognized scholar of Islamic jurisprudence, Quranic exegesis, and Islamic finance, brings decades of scholarly rigor to this translation project, producing a work that balances accessibility with accuracy in a way that few translators have achieved. Unlike casual translations that sacrifice precision for simplicity, this Asaan (easy) translation maintains strict adherence to the established principles of Quranic tafsir while using clear, contemporary Urdu that ordinary readers can understand without difficulty — making it the ideal choice for households where both religious authenticity and ease of comprehension are equally valued.

Mufti Taqi Usmani's approach to Quranic translation is informed by his deep engagement with both the classical tafsir tradition — including the works of Imam Al-Tabari, Imam Al-Qurtubi, Ibn Kathir, and Al-Baghawi — and the demands of modern Urdu readership. His translation avoids the two extremes that plague many contemporary works: it does not resort to overly literal rendering that produces incomprehensible Urdu, nor does it take excessive interpretive liberties that insert the translator's opinions into the divine text. Instead, each verse is rendered into natural, flowing Urdu that captures both the apparent meaning (zahir) and, where appropriate through careful annotation, the deeper implications understood by the early scholars of the Muslim community. This balanced methodology has earned the endorsement of numerous Islamic institutions and scholars across Pakistan, India, Bangladesh, and the global Urdu-speaking diaspora.

This premium edition is produced with exceptional print quality on high-grade paper that ensures longevity even with daily use, featuring clear Naskh typography for the Arabic text alongside the translation in a parallel-column layout that allows seamless comparison between the original and its Urdu rendering. The binding is designed for durability, making it suitable for reference use in madrasahs, mosques, Islamic libraries, and homes where the Quran is read regularly. Many families purchase this translation specifically because of Mufti Taqi Usmani's reputation for orthodoxy and reliability — knowing that his work reflects the authentic understanding of the Ahlus Sunnah wal Jama'ah as transmitted through centuries of scholarly tradition. For anyone seeking a Quran translation that they can read with complete confidence in its accuracy, trust in its scholarly credentials, and enjoy through its clear, readable Urdu prose, this Asaan Tarjuma by Mufti Taqi Usmani stands as arguably the finest choice available in the market today.`,
    metaDescription: "Asaan Tarjuma Quran by Mufti Taqi Usmani — trusted, scholarly Urdu Quran translation. Clear, authentic, premium print. Order online at Bab-ul-Fatah."
  },
  {
    slug: "ashab-e-badr",
    description: `Ashab-e-Badr is a dedicated historical and biographical work that chronicles the lives, backgrounds, and extraordinary contributions of the 313 Muslim companions (Sahabah) who participated in the Battle of Badr — the first and arguably most pivotal military engagement in Islamic history. Fought on the 17th of Ramadan in the second year after Hijrah (624 CE), the Battle of Badr pitted a small, poorly equipped Muslim force of 313 against a much larger Makkan army of approximately 1,000 well-armed soldiers. The miraculous Muslim victory at Badr established the nascent Islamic state in Madinah as a political and military force to be reckoned with, and the participants earned the special honorific title of "Badriyyun" — a distinction so esteemed that subsequent generations of Muslims considered it a badge of unparalleled honor to be descended from even a single Badri companion.

This book goes far beyond a mere battle narrative by providing individual biographical sketches of the key participants from both the Muhajirun (those who migrated from Makkah) and the Ansar (the helpers from Madinah). Readers will encounter detailed accounts of Abu Bakr as-Siddiq's unwavering support, Umar ibn al-Khattab's fierce courage, Hamzah ibn Abdul Muttalib's lionhearted valor, Ali ibn Abi Talib's extraordinary combat prowess, and the strategic wisdom of the Prophet (ﷺ) himself. Equally important, the book highlights lesser-known Badri companions whose stories are rarely found in general Islamic histories — ordinary men and in some cases young boys who left their homes, families, and livelihoods to stand beside the Prophet (ﷺ) in a battle they had no realistic hope of winning except through divine assistance. Each biography covers the companion's lineage, their life before Islam, their conversion story, their role at Badr, and their subsequent contributions to the Islamic community.

The author has drawn from the most reliable sources of early Islamic history, including Sahih Al-Bukhari, Sahih Muslim, the Musnad of Imam Ahmad, Ibn Hisham's Seerah, Ibn Sa'd's Tabaqat, and the historical works of Al-Waqidi and At-Tabari, carefully cross-referencing accounts to ensure accuracy and resolve any apparent contradictions between different narrations. The book addresses the military tactics employed by the Prophet (ﷺ), the significance of the strategic positioning at the water wells, the role of the angels who fought alongside the Muslims, and the aftermath including the treatment of prisoners of war — an event that established humanitarian precedents still studied in modern international law. For Pakistani readers, this book serves as both an inspirational spiritual resource and an important educational tool for understanding the foundational events that shaped Islamic civilization. Islamic schools use it as supplementary reading material for Seerah and Islamic history courses, and study circles (halaqat) often dedicate an entire series of sessions to discussing the lessons of Badr using this book as their primary reference.`,
    metaDescription: "Ashab-e-Badr — detailed biographies of 313 companions at the Battle of Badr. Authentic Islamic history with individual Sahabah accounts. Buy online."
  },
  {
    slug: "ashra-mubashra-ki-zindagiyon-ke-sunehre-waqiaat",
    description: `Ashra Mubashra Ki Zindagiyon Ke Sunehre Waqiaat (The Golden Events from the Lives of the Ashra Mubashra) is a captivating Urdu collection of stories and incidents from the lives of the ten companions of Prophet Muhammad (ﷺ) who were given the glad tidings of Paradise during their lifetimes — collectively known as the Ashra Mubashra or Al-Asharah Al-Mubashsharah. These ten noble companions — Abu Bakr as-Siddiq, Umar ibn al-Khattab, Uthman ibn Affan, Ali ibn Abi Talib, Talhah ibn Ubaidullah, Zubayr ibn al-Awwam, Abdur Rahman ibn Awf, Sa'd ibn Abi Waqqas, Abu Ubaidah ibn al-Jarrah, and Sa'id ibn Zayd — represent the very best of the Prophet's companions, and their lives contain countless lessons in faith, courage, generosity, humility, wisdom, and devotion that continue to illuminate the path for Muslims across every generation.

The book's title, "Sunehre Waqiaat" (Golden Events), reflects the author's approach of selecting the most inspiring, educational, and spiritually uplifting incidents from each companion's life rather than attempting a comprehensive chronological biography. Each story is narrated in engaging, story-like Urdu prose that brings the events to vivid life — allowing readers to feel as though they are witnessing the Prophet's (ﷺ) interactions with his closest companions firsthand. Readers will discover how Abu Bakr spent virtually his entire fortune freeing slaves and supporting the Muslim community, how Umar's conversion struck terror into the hearts of Islam's enemies while bringing immense joy to the believers, how Uthman's legendary modesty and generosity earned him the title Dhun-Nurayn (Possessor of Two Lights), how Ali's unmatched bravery at the Battle of the Trench and his encyclopedic knowledge made him one of the most remarkable figures in human history, and how Abdur Rahman ibn Awf became one of the wealthiest men in Islamic history while maintaining the humility of the poorest believer.

The stories are drawn exclusively from authentic hadith collections and classical biographical sources, with particular emphasis on narrations found in Sahih Al-Bukhari, Sahih Muslim, and the Musnad of Imam Ahmad. The author has taken care to verify each incident through multiple chains of transmission where possible, and has included references at the end of each story for readers who wish to conduct further research. The book is organized companion-by-companion, allowing readers to study each of the Ashra Mubashra individually or read the book cover-to-cover for a comprehensive overview. For Islamic schools in Pakistan, this book serves as an excellent supplementary text for Seerah and Islamic history classes, while families use it for bedtime reading with children, halaqah discussions, and personal spiritual development. The affordable price and engaging writing style make it accessible to readers of all ages and backgrounds, ensuring that the golden legacy of these ten promised companions reaches the widest possible audience.`,
    metaDescription: "Ashra Mubashra Ke Sunehre Waqiaat — inspiring golden stories of 10 promised companions. Authentic hadith-based Urdu collection. Order online at Bab-ul-Fatah."
  },
  {
    slug: "ashra-zil-hajja-eid-ul-adha-aur-qurbani",
    description: `Ashra Zil Hajja — Eid ul Adha aur Qurbani is a focused, informative booklet that serves as a complete practical guide for Muslims in Pakistan and around the world who wish to properly observe the first ten days of Dhul Hijjah, perform the Eid ul Adha prayers, and carry out the ritual sacrifice (Qurbani/Udhiyah) in accordance with Islamic law. The first ten days of Dhul Hijjah are described by the Prophet (ﷺ) as the best days in the sight of Allah — even superior to the days of Ramadan — making this booklet an essential companion for every Muslim household as the Hajj season approaches each year. The author has compiled relevant Quranic verses, authentic hadith, and practical Fiqh rulings from all four major schools of Islamic jurisprudence, presenting them in a concise Urdu format that covers everything a person needs to know without unnecessary academic digressions.

The booklet's section on the Ashra Zil Hijjah (the blessed ten days) covers the virtues of fasting during these days — particularly the Day of Arafah, which expiates the sins of the previous and coming year according to the Prophet's (ﷺ) explicit promise. It details the recommended acts of worship including increased dhikr, recitation of takbir (Allahu Akbar, Allahu Akbar, La ilaha illallahu wallahu Akbar, Allahu Akbar wa lillahil hamd), charity, and voluntary prayers. The section on Eid ul Adha provides step-by-step guidance for the Eid prayer — including the method for those praying at home when mosque attendance is not possible — the sunnah acts of the Eid day such as taking a bath (ghusl), wearing one's best clothes, using perfume, eating something before the prayer, and taking different routes to and from the prayer ground.

The Qurbani section forms the most practically valuable portion of this booklet, addressing the questions that Pakistani Muslims ask every year with clear, authoritative answers. It covers who is obligated to perform Qurbani (the minimum nisab threshold calculated in Pakistani rupee terms), which animals are permissible for sacrifice and their minimum age and health requirements, how to share a larger animal (cow, camel, buffalo) among multiple participants, the proper method of slaughtering according to the Sunnah, what to recite at the time of slaughter, how to distribute the meat between personal consumption, family and friends, and the poor, common mistakes to avoid, and the spiritual significance of the sacrifice as a commemoration of Prophet Ibrahim's (AS) willingness to sacrifice his son for Allah's sake. The booklet's extremely affordable price of just Rs.30 makes it accessible to virtually every family, and many mosques and Islamic organizations in Pakistan distribute it freely during the Dhul Hijjah season as a community service.`,
    metaDescription: "Ashra Zil Hajja booklet — complete guide to Eid ul Adha and Qurbani rules. Virtues of first 10 days, fasting, sacrifice method. Affordable pocket guide."
  },
  {
    slug: "asmad-surma-large",
    description: `Asmad Surma (Large Size) is a traditional Islamic natural eye care product prepared from authentic kohl stone (ismaad/ithmid), following the Sunnah practice of Prophet Muhammad (ﷺ) who regularly applied surma to his eyes and recommended its use to his companions. The Prophet (ﷺ) specifically instructed Muslims to use ismad (antimony-based kohl) rather than other types of kohl, saying in a hadith narrated by Ibn Abbas (RA): "Use kohl made from ithmid, for it brightens the eyesight and makes the eyelashes grow." This authentic Asmad Surma is prepared from genuine ithmid stone that has been carefully selected, cleaned, and ground into an ultra-fine powder using traditional methods that preserve its natural mineral properties and therapeutic benefits, distinguishing it from commercially mass-produced synthetic surma products that may contain harmful chemical additives.

The therapeutic properties of authentic ithmid surma have been recognized both in traditional Islamic medicine (Tibb al-Nabawi) and in modern scientific research. Studies have found that natural antimony (stibnite) used in genuine ithmid surma possesses antimicrobial properties that help protect the eyes from bacterial infections, reduce inflammation, and soothe eye strain caused by exposure to dust, screen time, and harsh lighting conditions. In the context of Pakistan's climate — where dust storms, intense sunlight, and air pollution are daily realities — applying natural surma provides a protective barrier for the eyes while simultaneously delivering trace minerals that support eye health. Unlike chemical-based eye cosmetics that may contain lead, parabens, or synthetic dyes, this authentic Asmad Surma is made from a single natural ingredient, making it safe for long-term regular use in accordance with the Prophetic recommendation.

This large-size container provides an extended supply, offering excellent value for regular users who apply surma as part of their daily routine — typically before sleeping, as was the Sunnah of the Prophet (ﷺ). The surma can be applied using a traditional wooden applicator (miswah stick) or a clean finger, drawing a thin line along the inner edge of the lower eyelid. Many Muslim families in Pakistan consider authentic ithmid surma an essential household item, not only for its health benefits but also as a means of following a verified Sunnah that carries spiritual reward. The product is particularly popular during Ramadan and on Fridays, when many Muslims make a special effort to practice additional Sunnah acts. Whether you are seeking a natural remedy for tired eyes, looking to follow the Prophet's (ﷺ) guidance on personal care, or wanting to transition away from chemically laden commercial eye products, this authentic Asmad Surma large size offers a pure, traditional, and spiritually rewarding choice.`,
    metaDescription: "Asmad Surma Large — authentic natural ithmid kohl following Prophet's Sunnah. Protects eyes, antimicrobial, chemical-free. Buy online in Pakistan."
  },
  {
    slug: "asr-se-maghrib-tak",
    description: `Asr Se Maghrib Tak (From Asr to Maghrib) is a uniquely structured Urdu book that captures the profound spiritual significance of the time period between the Asr (afternoon) and Maghrib (sunset) prayers — a daily window that the Prophet Muhammad (ﷺ) highlighted as being especially meritorious for supplication and worship. The book draws its inspiration from the famous hadith recorded in Sahih Muslim where the Prophet (ﷺ) said: "A servant's supplication is never refused as long as he does not supplicate for something sinful or for severing family ties, and as long as he is not impatient" — and specifically identified the time between the Asr and Maghrib prayers as one of the three times when du'as are most readily accepted by Allah. This daily sacred window, available to every Muslim regardless of their circumstances, becomes through this book a powerful framework for spiritual growth and consistent connection with the Divine.

The book's structure mirrors the progression of this daily time period, beginning with the completion of the Asr prayer and the spiritual atmosphere that descends upon a believer who has faithfully performed all four obligatory prayers from Fajr through Asr. The author explores what makes this specific time so spiritually potent, drawing on classical tafsir, hadith commentary, and the writings of pious predecessors (salaf as-salih) who considered the late afternoon hours to be among the most precious moments of a Muslim's day. Practical guidance is provided on how to maximize the spiritual benefit of this period — including recommended adhkar (remembrances), specific du'as from the Quran and Sunnah that are particularly effective when recited during this time, the practice of istighfar (seeking forgiveness), and the recitation of Quranic passages that relate to the fading of the day and the approach of night, creating an atmosphere of reflection and humility before Allah.

What sets this book apart from general du'a compilations is its focused, time-specific approach that gives readers a concrete daily practice to adopt rather than an overwhelming collection of prayers without context. The author includes personal anecdotes and stories of pious individuals from Islamic history whose du'as made during the Asr-to-Maghrib period were answered in remarkable ways — stories that inspire hope and persistence in supplication. The book addresses common obstacles that prevent people from utilizing this time effectively, such as the distraction of household chores, social media usage, and the mental fatigue that accumulates by late afternoon, offering practical strategies for overcoming each barrier. For Pakistani readers seeking to transform a mundane daily transition period into a meaningful spiritual practice, Asr Se Maghrib Tak provides the knowledge, motivation, and practical framework to make the most of these divinely blessed minutes every single day of their lives.`,
    metaDescription: "Asr Se Maghrib Tak — Urdu book on the blessed time between Asr and Maghrib for accepted du'as. Practical daily spiritual guide. Order online at Bab-ul-Fatah."
  },
  {
    slug: "assalato-wassalam-ala-rasool-allah",
    description: `Assalato Wassalam Ala Rasool Allah (الصلاة والسلام على رسول الله) is a comprehensive and spiritually enriching book dedicated to the Islamic practice of sending blessings and salutations upon Prophet Muhammad (ﷺ) — commonly known as Salawat or Durud. This practice, which Allah Himself commands in the Quran with the words "Indeed, Allah and His angels send blessings upon the Prophet. O you who believe, send blessings upon him and greet him with peace" (Al-Ahzab 33:56), represents one of the most meritorious and beloved acts of worship in Islam. The book explores every dimension of this practice — from its theological foundations and spiritual benefits to its various formulations, optimal times for recitation, and the extraordinary rewards promised to those who consistently send Salawat upon the final messenger of Allah.

The author begins by establishing the Quranic and hadith basis for sending Salawat, providing detailed commentary on the relevant verse of Surah Al-Ahzab and analyzing the numerous authentic hadith in which the Prophet (ﷺ) described the rewards of this practice. Among the most striking narrations included is the hadith where the Prophet (ﷺ) said: "Whoever sends one blessing upon me, Allah will send ten blessings upon him, and will erase ten sins from him, and will raise him by ten degrees." Another narration promises that the person who sends the most Salawat upon him will be closest to the Prophet on the Day of Judgment. The book also addresses and clarifies common questions — such as whether Salawat can be sent in any language or only in Arabic, whether there is a specific number that one should aim for daily, and the scholarly discussion around whether the Salawat of Allah differs in meaning from the Salawat of the angels and the believers.

A significant portion of the book is devoted to compiling and explaining the various authentic formulations of Salawat that have been taught by the Prophet (ﷺ) himself, the companions, and the pious early generations. The most well-known — Salawat al-Ibrahimiyyah (recited in every sitting during prayer) — is analyzed word by word to reveal its profound meanings and the wisdom behind each phrase. Other formulations include the Salawat taught by the Prophet to various companions for specific purposes, such as the Salawat that the Prophet recommended for alleviating poverty, for seeking forgiveness of major sins, for protection from calamities, and for intercession on the Day of Judgment. The book also explores the practice of collective Salawat gatherings, the Salawat recited during Mawlid gatherings and Friday nights, and the relationship between Salawat and the concept of wasilah (seeking nearness to Allah through the Prophet). For Pakistani Muslims who wish to deepen their connection with the Prophet (ﷺ) through this beautiful daily practice, Assalato Wassalam Ala Rasool Allah provides both the scholarly foundation and the practical guidance to make Salawat a central, transformative part of their worship routine.`,
    metaDescription: "Assalato Wassalam Ala Rasool Allah — comprehensive book on Salawat/Durud with Quranic evidence, authentic formulations, and rewards. Buy online at best price."
  },
  {
    slug: "assembly-se-class-room-tak",
    description: `Assembly Se Class Room Tak (From Assembly to Classroom) is a distinctive Urdu book that addresses the often-overlooked transition space in a Muslim student's daily routine — the journey from the school assembly to the classroom — and transforms it into a meaningful educational experience rooted in Islamic values and practical wisdom. Written specifically for students in Pakistani schools where the morning assembly is a daily institution, this concise yet impactful book bridges the gap between the formal Islamic instruction delivered during assembly (such as Quran recitation, du'a, and nasheeds) and the academic learning that follows in the classroom. The book's central thesis is that the values, discipline, and spiritual awareness cultivated during the morning assembly should not be left behind when students move to their classrooms — rather, these Islamic principles should inform and enhance every aspect of their educational experience.

The book is structured as a series of short, engaging chapters that can be read individually or discussed in group settings. Each chapter addresses a specific aspect of the student experience — including respect for teachers (a concept deeply rooted in Islamic tradition where the status of a teacher is considered仅次于 the status of parents), honesty in academic work (with particular emphasis on the Islamic prohibition of cheating and plagiarism), kindness toward classmates (regardless of their background or academic ability), time management as a form of worship (drawing on Quranic and hadith teachings about the value of time), and the importance of maintaining Islamic manners (adab) throughout the school day — from greeting others with salaam to lowering one's gaze, from speaking with kindness to avoiding gossip and backbiting. Each topic is supported by relevant Quranic verses, hadith of the Prophet (ﷺ), and examples from the lives of the Sahabah and great Muslim scholars throughout history who excelled in both religious and worldly knowledge.

What makes this book particularly effective is its practical, relatable approach that speaks directly to the experiences of school-age children and teenagers. Rather than preaching abstract principles, the author presents realistic scenarios that students encounter daily — such as being tempted to copy homework, witnessing bullying, feeling discouraged by poor grades, dealing with unfair treatment by peers, and balancing academic pressure with religious obligations — and provides Islamic solutions that are both spiritually sound and practically achievable. The book has been adopted by several Islamic schools and madrasahs in Pakistan as a supplementary character education resource, and parents find it valuable for reading with their children at home to reinforce the values taught at school. At its remarkably affordable price point, this book represents an investment in a child's moral and spiritual development that no Muslim family should overlook — because the journey from assembly to classroom, the author argues, is not merely a physical walk down a hallway but a daily opportunity to put Islamic values into action.`,
    metaDescription: "Assembly Se Class Room Tak — Urdu book on Islamic values for school students. Character education, respect, honesty, time management. Affordable guide."
  },
  {
    slug: "astrophysics-and-the-holy-quran",
    description: `Astrophysics and the Holy Quran is a groundbreaking interdisciplinary work that examines the remarkable correspondence between modern astrophysical discoveries and the scientific references found in the Quran — the book revealed to Prophet Muhammad (ﷺ) over fourteen centuries ago. Written for an educated Urdu readership that appreciates both scientific rigor and religious faith, this volume systematically explores how Quranic verses describing celestial phenomena — the creation of the universe, the expansion of space, the structure of stars, the phenomenon of black holes, the orbital mechanics of planets, the nature of light, and the ultimate fate of the cosmos — align with findings from contemporary astrophysics, astronomy, and cosmology. The book does not claim that the Quran is a science textbook but rather demonstrates that its references to natural phenomena are consistently accurate, often anticipating discoveries that would not be made by human scientists until centuries or even millennia later.

Each chapter of the book focuses on a specific astrophysical topic and presents the relevant Quranic verses alongside the current scientific understanding, allowing readers to appreciate the precision and consistency of the Quranic descriptions. For instance, the chapter on cosmic expansion examines Surah Ad-Dhariyat (51:47) — "And the heaven We constructed with strength, and indeed, We are [its] expander" — alongside Edwin Hubble's 1929 discovery that galaxies are receding from each other, confirming that the universe is indeed expanding. The chapter on celestial orbits discusses Surah Ya-Sin (36:40) — "It is not allowable for the sun to reach the moon, nor does the night overtake the day, but each, in an orbit, is swimming" — in the context of Kepler's laws of planetary motion and Newton's theory of gravitation. The chapter on the origin of the universe explores the Quranic concept of the "smoke" state that preceded the formation of celestial bodies, paralleling the Big Bang theory's description of the early universe as a hot, dense, opaque gas.

The book's discussion of more advanced astrophysical concepts — including neutron stars, pulsars, dark matter, the cosmic microwave background radiation, and the event horizons of black holes — reveals how recent discoveries continue to validate Quranic descriptions that were incomprehensible to seventh-century Arabic speakers but make perfect sense in light of modern science. The author provides Urdu translations of technical scientific terms, diagrams and illustrations where helpful, and references to peer-reviewed scientific journals for readers who wish to verify the scientific claims independently. Importantly, the book maintains a balanced academic tone, avoiding both the extreme of forcing scientific interpretations onto vague Quranic verses and the opposite extreme of ignoring genuine scientific-Quranic convergences. Scholars, students, and educated lay readers in Pakistan who wish to strengthen their faith through the lens of modern scientific discovery, or who are simply fascinated by the intersection of science and religion, will find Astrophysics and the Holy Quran to be an intellectually stimulating, well-researched, and spiritually enriching addition to their library.`,
    metaDescription: "Astrophysics and the Holy Quran — explore scientific miracles in Quran. Big Bang, cosmic expansion, black holes aligned with modern astrophysics. Buy online."
  },
  {
    slug: "at-tawassal",
    description: `At-Tawassal (التوسل) is a focused scholarly treatise that provides a comprehensive, evidence-based examination of the Islamic concept of tawassul — the practice of seeking a means of nearness to Allah through various intermediaries, including supplicating through the rank and status of Prophet Muhammad (ﷺ), the righteous individuals, and one's own good deeds. This topic has been the subject of considerable scholarly debate within the Muslim ummah for centuries, and this book approaches the discussion with the academic rigor and balanced perspective that the subject demands, presenting the positions of different schools of thought while grounding the analysis firmly in the primary textual sources of Islam: the Quran, the authentic hadith, the practice of the Sahabah, and the consensus of the early Muslim community.

The book begins by defining tawassul in its broadest Islamic sense — explaining that the concept itself is not disputed, as even the most conservative scholars agree that a Muslim can seek nearness to Allah through his own good deeds, through invoking Allah by His beautiful names and attributes, and through a state of humility and repentance. The scholarly discussion centers on two more specific forms: seeking nearness to Allah through the status and intercession of the Prophet (ﷺ) and the righteous after their passing from this world, and the practice of seeking the Prophet's (ﷺ) intercession through visiting his blessed grave. The author presents the evidence for each position from the Quran and hadith, analyzing the strongest narrations cited by proponents of each view, addressing the objections raised by opponents, and examining how the early generations of Muslims — particularly the companions and the tabi'in — practiced or understood tawassul in their own lives.

The book's analytical approach is particularly valuable because it avoids the polarized, polemical tone that characterizes much of the existing literature on this topic. Instead of declaring one position absolutely right and the other absolutely wrong, the author carefully weighs the evidence, acknowledges the strengths and limitations of each argument, and presents the range of scholarly opinions within the Ahlus Sunnah wal Jama'ah framework. Specific hadith discussed include the famous narration of the blind man who the Prophet (ﷺ) taught to make du'a through his (the Prophet's) status, the hadith of Uthman ibn Hanif about the three men who sought rain through the Prophet's (ﷺ) intercession at his grave, and the practice of the companions during the lifetime of Adam (AS) as narrated in various sources. The book also addresses the practical implications of this discussion for Pakistani Muslims — including the common practices at shrines and mazaars, the etiquette of visiting the Prophet's grave in Madinah, and how to distinguish between permissible and impermissible forms of tawassul in daily religious life. For anyone seeking a clear, scholarly, and balanced understanding of this important but often misunderstood Islamic concept, At-Tawassal provides a trustworthy and comprehensive resource.`,
    metaDescription: "At-Tawassal — scholarly book on Islamic concept of seeking nearness to Allah. Balanced analysis of Tawassul with Quranic and hadith evidence. Order online."
  }
];

async function main() {
  let updated = 0, failed = 0;
  for (const item of updates) {
    try {
      const result = await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log(`✅ Updated: ${result.title} (${result.slug})`);
      updated++;
    } catch (err) {
      console.log(`❌ Failed: ${item.slug} — ${err.message}`);
      failed++;
    }
  }
  console.log(`\nBatch R3B complete: ${updated} updated, ${failed} failed`);
}

main().then(() => prisma.$disconnect());
