const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "hazrat-ibrahim-as-bahasit-walid",
    description: `Hazrat Ibrahim AS Bahasit Walid is an engaging Urdu-language biography of Prophet Ibrahim (peace be upon him) that traces the remarkable journey of the man whom the Quran describes as Khalilullah — the intimate friend of Allah. Priced at Rs.270, this book brings to life the story of a patriarch revered not only by Muslims but by Jews and Christians alike, presenting his struggles and triumphs through the lens of authentic Islamic sources. The title "Bahasit Walid" (The Dearest Father) highlights the unique bond between Ibrahim and his progeny — a lineage that produced countless prophets and culminated in the final messenger, Muhammad (ﷺ).

The narrative begins with Ibrahim's early life in the ancient city of Ur, where he grew up surrounded by idol worship and polytheism. Readers follow his extraordinary intellectual journey as a young man who questioned the faith of his community, smashed the idols of his people, and confronted the mighty ruler Nimrod — declaring his unwavering belief in the one true God. The book vividly describes how Ibrahim was thrown into a massive fire by his own father and community, only for Allah to command the fire: "O fire, be cool and safe for Ibrahim." This miraculous deliverance became one of the most iconic events in prophetic history and is narrated with dramatic detail that captivates readers of all ages.

Beyond the famous fire incident, the book covers the full breadth of Ibrahim's prophetic mission — his migration from Mesopotamia to Syria and Palestine, his relationship with his wives Sarah and Hajar, the birth of his sons Ismail and Ishaq, the building of the Ka'bah in Makkah alongside his son Ismail, and the supreme trial of being commanded to sacrifice his beloved son. The story of the sacrifice is told with particular sensitivity, showing how both father and son submitted completely to Allah's will — a moment of faith that Muslims commemorate every year during Eid al-Adha. The author draws connections between Ibrahim's life and the rituals of Hajj, helping readers understand why his legacy is so central to Islamic worship. For families looking to teach their children about the greatest prophets of Islam, for students of Seerah seeking deeper knowledge of prophetic history, and for any Urdu reader who wants to strengthen their connection with this legendary figure of faith, Hazrat Ibrahim AS Bahasit Walid offers a compelling, well-researched, and spiritually enriching narrative.`,
    metaDescription: "Hazrat Ibrahim AS Bahasit Walid — Urdu biography of Prophet Ibrahim (AS). Story of faith, sacrifice, and the Ka'bah. Engaging Seerah narrative at Rs.270."
  },
  {
    slug: "hazrat-ibrahim-as-ki-qurbani-ka-qissa",
    description: `Hazrat Ibrahim AS ki Qurbani ka Qissa (The Story of Prophet Ibrahim's Sacrifice) is a focused Urdu narrative that retells one of the most powerful and emotionally resonant stories in all of Islamic scripture — the moment when Allah commanded Prophet Ibrahim (peace be upon him) to sacrifice his own beloved son. Priced at just Rs.180, this slim yet deeply moving volume concentrates exclusively on this single episode, giving it the detailed treatment and emotional depth that such a monumental event in prophetic history deserves.

The book sets the stage by explaining the context of Ibrahim's life at the time of this trial. He had spent decades calling people to the worship of one God, enduring persecution, exile, and hardship with unwavering patience. After years of longing for a child, Allah had blessed him in his old age with a righteous son — Ismail. The joy of finally having an heir to continue his prophetic mission made the subsequent command to sacrifice that very son all the more devastating. The author portrays the internal struggle of a father torn between his love for his child and his absolute submission to his Creator — a tension that makes this story relevant to every parent and every believer who has ever been tested by difficult choices.

The narrative follows the events with careful attention to Quranic detail. Ibrahim sees a dream in which he is sacrificing his son — and recognizing it as a divine command, he consults his son. The young Ismail's response, as recorded in the Quran, is one of the most remarkable expressions of faith in human history: "O my father, do what you are commanded. You will find me, if Allah wills, among the patient." The book describes their journey to the place of sacrifice, the preparation, the binding, and the moment when Allah's mercy intervened — substituting a great ram in place of the boy. This event established the ritual of Qurbani that Muslims perform every year on Eid al-Adha, and the author connects each element of the story to the practical aspects of the Eid sacrifice, helping readers understand the deep spiritual significance behind this important Islamic practice. For children learning about the prophets, for families preparing for Eid al-Adha, and for anyone seeking to renew their appreciation for this timeless story of complete submission to Allah, this affordable booklet delivers a powerful and inspiring reading experience.`,
    metaDescription: "Hazrat Ibrahim AS ki Qurbani ka Qissa — Urdu story of Ibrahim's sacrifice. Eid al-Adha origins, Quranic narrative. Inspiring faith story for Rs.180."
  },
  {
    slug: "healing-with-the-medicine-of-the-prophet-pbuh",
    description: `Healing with the Medicine of the Prophet (PBUH) is the landmark English translation of Ibn al-Qayyim al-Jawziyyah's celebrated Arabic work "Al-Tibb al-Nabawi" — one of the most comprehensive and authoritative books ever written on Prophetic medicine. Ibn al-Qayyim (1292–1350 CE), the distinguished student of Imam Ibn Taymiyyah and one of the most prolific scholars in Islamic history, devoted years of research to compiling this extraordinary encyclopedia of natural healing methods that Prophet Muhammad (ﷺ) recommended, practiced, or approved of during his lifetime. Priced at Rs.4,500, this premium hardcover edition makes this masterwork accessible to English-speaking Muslims, health professionals, and researchers interested in the intersection of traditional Islamic medicine and modern wellness.

The book is far more than a simple list of remedies. Ibn al-Qayyim approaches Prophetic medicine as a complete holistic health system that addresses the physical, spiritual, and psychological dimensions of human well-being. He begins by establishing the foundational principle that true healing comes from Allah alone and that the medical remedies prescribed by the Prophet (ﷺ) represent divine guidance for maintaining health and treating illness. The text then systematically covers dozens of specific health conditions and their Prophetic treatments — including digestive disorders, respiratory ailments, skin conditions, eye diseases, fever, headache, joint pain, and many others. Each remedy is supported by references to authentic hadith, accompanied by Ibn al-Qayyim's scholarly analysis of the remedy's effectiveness, and enriched with insights from the classical Greek and Persian medical traditions that Islamic scholars had absorbed and refined.

Specific remedies covered in detail include the use of honey (which the Quran itself describes as a healing), black seed (Nigella sativa, which the Prophet called "a cure for every disease except death"), cupping therapy (hijama), the medicinal use of dates, Zamzam water, olive oil, siwak (miswak), various herbs and spices, and specific dietary recommendations. The author also discusses the spiritual dimension of healing — the role of prayer, Quranic recitation (ruqyah), charity, and repentance in the healing process. What elevates this work above ordinary remedy books is Ibn al-Qayyim's extraordinary intellectual depth — he discusses the underlying principles of each treatment, explains why certain remedies work for certain conditions based on the temperament theory of traditional medicine, and addresses potential objections and misunderstandings. The Darussalam edition features premium hardcover binding, clear English translation, comprehensive hadith referencing, and a detailed table of contents that makes this massive work navigable and practical. For Muslim doctors seeking to integrate Prophetic medicine into their practice, for families building a comprehensive home health library, and for anyone interested in the rich Islamic heritage of natural healing, this book is an indispensable reference.`,
    metaDescription: "Healing with the Medicine of the Prophet PBUH — Ibn al-Qayyim's Tibb al-Nabawi in English. Honey, black seed, hijama, herbal remedies. Premium hardcover Rs.4500."
  },
  {
    slug: "healing-with-the-medicine-of-the-prophet-pbuh-4-colour-local",
    description: `Healing with the Medicine of the Prophet (PBUH) — 4 Colour Local Edition is the budget-friendly Pakistani printing of Ibn al-Qayyim al-Jawziyyah's renowned work on Prophetic medicine, presented in a compact format with four-color interior printing that enhances the readability and visual appeal of this essential Islamic health reference. Priced at Rs.2,200 — less than half the cost of the imported hardcover edition — this local print makes the life-changing knowledge of Tibb al-Nabawi accessible to a much wider Pakistani audience without compromising on the quality of the content or the clarity of the English translation.

This edition retains the complete text of the original work, covering the full spectrum of Prophetic healing methods that Ibn al-Qayyim documented from authentic hadith sources. Readers will find detailed guidance on using honey as a universal remedy, the remarkable healing properties of black seed (kalonji), the therapeutic practice of cupping (hijama) with specific instructions on when and how it should be performed, the medicinal benefits of dates, Zamzam water, olive oil, and various herbs and spices that the Prophet (ﷺ) recommended for specific health conditions. The four-color printing enhances the reading experience by using color-coded headings, highlighted hadith text, and colored dividers between major sections — making it significantly easier to navigate this extensive reference work compared to standard single-color editions.

The physical production of this local edition is well-suited to the Pakistani market. The binding is sturdy enough for regular reference use, the paper quality is good, and the compact dimensions make it practical for home libraries, clinic waiting rooms, and Islamic school libraries. The text covers common ailments that are particularly relevant to the Pakistani context — including seasonal illnesses, digestive issues common to South Asian diets, and traditional remedies that many Pakistani families already practice but may not know have a basis in Prophetic tradition. The book also addresses the spiritual dimension of healing through ruqyah (Quranic healing), the importance of dietary moderation (a principle strongly emphasized by the Prophet), and the connection between spiritual health and physical well-being. For Pakistani Muslims who want to benefit from the Prophet's (ﷺ) medical guidance but prefer an affordable local edition, for medical students interested in Islamic medical heritage, and for families seeking natural health solutions rooted in divine revelation, this four-color local edition offers outstanding value and practical utility.`,
    metaDescription: "Healing with Medicine of the Prophet PBUH 4-Colour Local — affordable Pakistani edition of Ibn al-Qayyim's Tibb al-Nabawi. Color interior, Rs.2200. Prophetic remedies."
  },
  {
    slug: "help-yourself-in-reading-quran",
    description: `Help Yourself in Reading Qur'an is a practical, self-paced English guidebook designed to teach the fundamental skills needed to read the Arabic text of the Holy Quran correctly — even for adult learners with absolutely no prior knowledge of the Arabic language. Priced at Rs.700, this workbook has become one of the most popular Quran-reading primers in the English-speaking Muslim world because of its remarkably effective step-by-step methodology that transforms complete beginners into confident Quran readers within a matter of weeks, not months or years.

The book's approach is built on the proven principle that Arabic script can be taught systematically by introducing one concept at a time in a carefully planned sequence. It begins with the individual Arabic letters — teaching the shape, name, and sound of each letter through clear diagrams and ample practice exercises. Unlike many Arabic primers that overwhelm beginners with too much information at once, this guide introduces letter forms gradually, allowing the learner to master each one before moving to the next. The book then covers the different forms that each letter takes depending on its position in a word (initial, medial, final, and isolated forms) — one of the most challenging aspects of Arabic for new learners. Practice exercises reinforce each concept with writing drills and recognition exercises.

Once the letters are mastered, the book moves to connecting letters to form words, then to reading short words and phrases, and finally to reading complete Quranic verses. Special attention is given to the pronunciation rules (Tajweed basics) that affect how letters are sounded — including the difference between similar-sounding letters, the rules of noon sakinah and tanween, and the proper articulation points (makharij) of Arabic letters. The book includes a helpful reference section with charts summarizing all the letters, their forms, and their pronunciations. Each lesson is designed to be completed in a short session, making the book ideal for busy adults who can only dedicate fifteen to twenty minutes per day to their Quran-reading journey. For new Muslims who are learning to read Quran for the first time, for adult Muslims who never learned to read Arabic properly in childhood, for parents who want to help their children with Quran homework, and for anyone who has been meaning to learn but kept putting it off, Help Yourself in Reading Qur'an provides the structured, patient, and effective guidance needed to finally achieve this important goal.`,
    metaDescription: "Help Yourself in Reading Qur'an — step-by-step English guide to reading Arabic Quran. Beginner-friendly, Tajweed basics, self-paced workbook. Rs.700."
  },
  {
    slug: "heroes-of-islam",
    description: `Heroes of Islam is an inspiring English-language collection of biographical accounts that introduces readers to the extraordinary men and women who shaped the course of Islamic civilization through their faith, courage, scholarship, and sacrifice. Priced at Rs.3,450, this substantial volume goes beyond the familiar stories of the Prophet's companions to include heroes from across Islamic history — from the earliest days of Islam to the medieval golden age and beyond — presenting a panoramic view of the remarkable individuals whose lives continue to inspire Muslims around the world today.

The book opens with detailed accounts of the greatest heroes of early Islam — Abu Bakr as-Siddiq, whose unwavering faith earned him the title "the Truthful"; Umar ibn al-Khattab, whose justice transformed nations; Khalid ibn al-Walid, the Sword of Allah who never lost a battle; and the courageous Muslim women like Khadijah, Aishah, and Fatimah whose wisdom and sacrifice were indispensable to Islam's success. Each biography is meticulously researched, drawing on authentic hadith sources, classical historical works, and respected biographical compilations. The narratives focus not only on the dramatic moments — battles, migrations, and political upheavals — but also on the character qualities that made these individuals truly heroic: their patience in adversity, their generosity in poverty, their humility in power, and their devotion to worship.

Beyond the early companions, the book introduces readers to Islamic heroes from later periods — the great scholars who preserved and systematized Islamic knowledge (Imam Bukhari, Imam Muslim, Imam Abu Hanifah, Imam Malik, Imam Shafi'i, Imam Ahmad), the warrior-scholars who defended the Muslim world (Salahuddin Ayyubi, Tariq ibn Ziyad), the scientists and philosophers who advanced human knowledge (Ibn Sina, Al-Khwarizmi, Ibn al-Haytham), the spiritual masters who illuminated hearts (Imam al-Ghazali, Rumi, Abdul Qadir Jilani), and the lesser-known but equally remarkable Muslims whose contributions built the civilization that the world inherited from Islam. The biographies are written in an engaging narrative style that reads like adventure stories while maintaining scholarly accuracy and Islamic propriety. Each chapter concludes with practical lessons that modern readers can apply to their own lives — making the stories of these heroes not just inspiring tales from the past but living sources of guidance for the present. For families, schools, libraries, and any reader seeking to discover the true heroes of Islamic history, this comprehensive collection provides an outstanding and deeply motivating reading experience.`,
    metaDescription: "Heroes of Islam — inspiring English biographies of great Muslims: Sahaba, scholars, warriors, scientists. Character lessons from Islamic history. Rs.3450 hardcover."
  },
  {
    slug: "hidayat-al-qari-sharh-sahih-al-bukhari-10-volume-set-local",
    description: `Hidayat al-Qari Sharh Sahih al-Bukhari is a monumental ten-volume Urdu commentary on Sahih al-Bukhari — the most authentic book after the Quran in Islamic tradition. Priced at Rs.27,700 for the complete ten-volume set, this local Pakistani edition makes an essential hadith commentary accessible to Urdu-speaking scholars, madrasah students, and serious students of Islamic knowledge who might otherwise have to rely on imported Arabic commentaries that cost significantly more and are inaccessible to readers without advanced Arabic proficiency.

Sahih al-Bukhari, compiled by Imam Muhammad ibn Ismail al-Bukhari (810–870 CE), contains approximately 7,563 hadith carefully selected from among hundreds of thousands that the Imam examined during his sixteen-year journey across the Muslim world. Understanding these hadith requires detailed commentary — and Hidayat al-Qari ("Guidance for the Reciter") provides exactly that. The commentary explains the terminology used in hadith chains of narration, clarifies obscure words and phrases in the hadith text, resolves apparent contradictions between different narrations, provides historical context for the events and personalities mentioned, and extracts the fiqh (jurisprudential) lessons that Imam Bukhari embedded in his chapter headings and hadith selections.

Each volume of this ten-volume set covers a distinct thematic section of Sahih al-Bukhari — beginning with the book of Revelation and the book of Faith, proceeding through the books of Knowledge, Prayer, Zakat, Fasting, Hajj, Marriage, Trade, and the remaining books, and concluding with the book of Divine Unity (Tawheed). The commentary's Urdu prose is scholarly yet accessible, written in the style of traditional madrasah commentary that Pakistani scholars and students are familiar with. Cross-references to related hadith in other collections (Muslim, Tirmidhi, Abu Dawud, Nasa'i, Ibn Majah) are provided throughout, enabling readers to see the complete picture of Prophetic guidance on any given topic. The local edition features durable binding suitable for the heavy use that hadith study demands, clear Urdu typography on quality paper, and volume-level indexes that help researchers navigate the massive content efficiently. For Pakistani madrasahs equipping their libraries, for scholars preparing for advanced hadith examinations, and for serious students of knowledge who want a reliable Urdu Sharh of Bukhari, this ten-volume set represents a major scholarly investment that will serve for a lifetime of study.`,
    metaDescription: "Hidayat al-Qari Sharh Sahih al-Bukhari 10-Vol Set Local — complete Urdu commentary on the most authentic hadith collection. Fiqh, chains, context. Rs.27,700."
  },
  {
    slug: "hindrances-on-the-path",
    description: `Hindrances on the Path is a thought-provoking English-language Islamic book that identifies and analyzes the spiritual, psychological, and social obstacles that prevent Muslims from progressing on their journey toward Allah — offering practical, Quran-based and Sunnah-grounded strategies for overcoming each obstacle. Priced at Rs.550, this concise but impactful work addresses a universal challenge: every sincere Muslim knows the feeling of wanting to grow closer to Allah but finding themselves repeatedly blocked by distractions, bad habits, negative influences, or internal struggles that seem impossible to overcome.

The book organizes these hindrances into clear categories, making it easy for readers to identify the specific obstacles that are holding them back. The first category covers external hindrances — the toxic social environments, un-Islamic media consumption, harmful friendships, and societal pressures that pull a Muslim away from the straight path. The book provides practical guidance on how to protect oneself from these external influences without completely isolating from society, drawing on the Quranic principle of maintaining good company and the Prophet's (ﷺ) advice about choosing friends wisely. The second category addresses internal hindrances — the diseases of the heart such as arrogance, jealousy, anger, greed, lust, and despair that corrode a Muslim's relationship with Allah from within. For each spiritual disease, the book presents the Quranic diagnosis, the Prophetic remedy, and practical steps for treatment and prevention.

The third category covers intellectual hindrances — the doubts, misconceptions, and philosophical confusions that can undermine a Muslim's faith, particularly in the modern age where secular ideologies and anti-religious arguments are constantly encountered online and in academic settings. The book equips readers with rational arguments and emotional resilience to maintain their faith despite these intellectual challenges. The fourth category addresses practical hindrances — the busy schedules, financial pressures, family obligations, and other real-world demands that make it difficult to maintain consistent worship and spiritual growth. Rather than offering unrealistic advice, the book provides realistic strategies for integrating spiritual practices into a busy modern life, showing how the early Muslims managed their worldly responsibilities while maintaining exemplary spiritual lives. The writing style is direct, compassionate, and free of unnecessary jargon — making it accessible to readers at every level of Islamic education. For young Muslims navigating the challenges of modern life, for reverts who are struggling to establish their practice, and for anyone who feels stuck in their spiritual journey, Hindrances on the Path provides the honest diagnosis and practical treatment plan that every traveler on the path to Allah needs.`,
    metaDescription: "Hindrances on the Path — English Islamic book on overcoming spiritual, psychological, and social obstacles to faith growth. Practical Quran-based guidance. Rs.550."
  },
  {
    slug: "hirz-e-azam-card-cover",
    description: `Hirz e Azam (The Great Shield) in its convenient card-cover edition is one of the most widely used supplication booklets in the Urdu-speaking Muslim world — a compact collection of essential du'as (prayers) and protective invocations that Muslims recite daily for spiritual safeguarding, blessings, and peace of mind. Priced at an incredibly affordable Rs.90, this card-cover edition makes the essential daily prayers of Islam accessible to virtually everyone, regardless of their financial situation, making it one of the most commonly found Islamic booklets in Pakistani households, mosques, schools, and workplaces.

The content of Hirz e Azam centers around prayers of protection and blessing — specifically the renowned "Hirz e Azam" (also known as "Al-Hisn al-Hasin" in Arabic tradition) which is a collection of supplications attributed to the great scholar Imam al-Jazari, augmented with additional du'as from authentic hadith sources. The booklet includes the famous morning and evening adhkar that the Prophet (ﷺ) strongly recommended every Muslim recite — protective prayers against all forms of harm, evil eye, envy, accidents, illness, and misfortune. These include Ayat al-Kursi (the Verse of the Throne, which the Prophet described as the greatest verse in the Quran), Surah al-Falaq and Surah an-Nas (the two chapters of seeking refuge), the last two verses of Surah al-Baqarah, and numerous other Quranic verses and Prophetic du'as that form a spiritual armor around the believer.

The card-cover format is specifically designed for durability and portability. The stiff card cover protects the inner pages from damage during frequent handling and carrying, and the compact size allows the booklet to fit into a pocket, wallet, purse, or school bag with ease. Many Pakistani Muslims keep a copy of Hirz e Azam in their car dashboard, bedside drawer, or office desk — ensuring that these protective prayers are always within reach. The Urdu text is presented in clear, legible script with Arabic text provided for each du'a alongside the Urdu translation, enabling readers who may not be fluent in Arabic to understand the meaning of what they are reciting. The booklet also includes du'as for specific occasions — before eating, after eating, before sleeping, after waking, before traveling, after traveling, before entering the mosque, and many other daily situations. For anyone seeking an affordable, comprehensive, and portable daily prayer companion, this card-cover Hirz e Azam at just Rs.90 represents exceptional value and essential spiritual utility.`,
    metaDescription: "Hirz e Azam Card Cover — essential Urdu du'a booklet for daily protection and blessings. Morning-evening adhkar, Ayat al-Kursi. Only Rs.90."
  },
  {
    slug: "hisn-ul-muslim-12x17",
    description: `Hisn ul Muslim (Fortress of the Muslim) in the 12x17 centimeter edition is the most widely used dua compilation in the Urdu-speaking Islamic world, presented in a medium-format size that balances readability with portability. Priced at Rs.340, this edition of the famous supplication collection — originally compiled by the distinguished Saudi scholar Sa'id bin Ali bin Wahf al-Qahtani — contains approximately 267 authentic du'as from the Quran and Sunnah, organized to follow the Muslim's complete daily routine from morning until night.

The 12x17 centimeter dimensions make this the ideal "standard" edition of Hisn ul Muslim — large enough to feature clear, readable text that is comfortable for daily use, yet compact enough to sit on a bedside table, fit in a medium bag, or be carried to the mosque without being cumbersome. The Arabic text of each du'a is presented in a clear, well-spaced font, accompanied by its Urdu translation so that readers understand the meaning of every word they recite. The source reference for each du'a is provided — citing the specific hadith collection (Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasa'i, Ibn Majah, or others) and often including a brief assessment of the hadith's authenticity. This scholarly transparency gives readers confidence that every du'a in the collection is verified and reliable.

The organizational structure of Hisn ul Muslim is one of its greatest strengths. Du'as are arranged chronologically to match the flow of a Muslim's day — beginning with the supplications for waking up and using the bathroom, proceeding through the du'as for eating, drinking, dressing, leaving and entering the home, traveling, and conducting daily activities, then covering the du'as for the five daily prayers, the Friday prayer, and other acts of worship, and concluding with the evening adhkar and the du'as before sleeping. Special sections cover du'as for illness and recovery, du'as during times of distress and anxiety, du'as for forgiveness and repentance, du'as for seeking blessings (barakah) in various activities, and du'as for protection from evil, harm, and the evil eye. This chronological arrangement means that the book naturally becomes a daily companion — readers simply open to the section corresponding to their current activity and find the appropriate du'a within seconds. For families, students, professionals, and every Muslim who wants to incorporate the authentic Prophetic supplications into their daily life, this 12x17 edition of Hisn ul Muslim is the perfect balance of size, readability, and completeness.`,
    metaDescription: "Hisn ul Muslim 12x17 — complete Urdu dua collection from Quran and Sunnah. 267 authentic supplications organized by daily routine. Rs.340 medium format."
  },
  {
    slug: "hisn-ul-muslim-14x21",
    description: `Hisn ul Muslim (14x21) is the larger, easy-to-read edition of the indispensable daily supplication collection that has become a household fixture for millions of Muslim families across Pakistan and the Urdu-speaking world. Priced at Rs.550, this generously proportioned 14x21 centimeter format is specifically designed for readers who prefer larger text, for use in family settings where multiple people may read together, and for individuals with visual preferences that make a bigger font size more comfortable for extended reading sessions.

The expanded page size of this edition allows for significantly larger Arabic and Urdu text compared to the standard 12x17 and 8x12 editions. The Arabic du'as are printed in a clear, spacious font that makes it easy for readers — including those still learning to read Arabic script — to identify each letter and diacritical mark correctly. The Urdu translation is likewise presented in a larger, more legible font that reduces eye strain during the longer reading sessions that many families incorporate into their morning and evening routines. This makes the 14x21 edition particularly popular with elderly readers, with families who read together as a group (where one person holds the book while others follow along), and with Islamic teachers who use the book as a classroom reference that needs to be visible from a distance.

The content remains the complete compilation of authentic Prophetic supplications that has made Hisn ul Muslim the gold standard for dua collections worldwide. All 267 du'as are included, each with its Arabic text, Urdu translation, and source reference from the hadith collections. The chronological organization follows the Muslim's daily schedule from waking to sleeping, with additional sections for special occasions, illnesses, times of distress, travel, and worship. The larger format also allows for slightly more generous spacing between du'as and sections, making it easier to find specific supplications quickly. The binding of this edition is reinforced to handle the additional weight and size of the larger pages, and the cover is designed to withstand the regular use that this daily companion will inevitably receive. For families making their morning and evening adhkar a shared practice, for mosque imams who read from the book during congregation, for Islamic school teachers using it as a teaching text, and for any reader who simply prefers a larger, more comfortable edition, this 14x21 Hisn ul Muslim is the premium choice in the series.`,
    metaDescription: "Hisn ul Muslim 14x21 — large-format Urdu dua collection with bigger Arabic text. 267 authenticated supplications. Ideal for families and elders. Rs.550."
  },
  {
    slug: "hisn-ul-muslim-8x12-pocket-size",
    description: `Hisn ul Muslim (8x12) pocket-size edition is the ultra-compact version of the world's most trusted daily supplication collection — designed to go everywhere you go, ensuring that the authentic Prophetic du'as are always within arm's reach regardless of where life takes you. Priced at just Rs.190, this miniature edition packs the complete collection of 267 authenticated supplications into a format small enough to slip into a shirt pocket, a wallet, a small purse, or the palm of your hand — making it the ultimate everyday carry for every practicing Muslim.

Despite its tiny dimensions, the 8x12 pocket edition sacrifices nothing in terms of content completeness. Every du'a from the standard edition is included — from the morning and evening adhkar to the du'as for eating, drinking, sleeping, traveling, entering and leaving the home and mosque, for prayer, for illness, for forgiveness, for protection from harm, and for every other occasion covered in the full compilation. The Arabic text is necessarily smaller than in the larger editions, but it remains clearly printed and fully legible, with the Urdu translation provided alongside each du'a and the hadith source reference included for scholarly verification.

This pocket-size edition is specifically crafted for the modern Muslim's lifestyle. It fits easily into the pocket of a shalwar kameez, the inside pocket of a blazer, or the smallest compartment of a backpack — meaning that it can accompany the reader to the office, to school, to the market, on public transport, during travel, and even to the hospital bedside. Many Pakistani Muslims keep multiple copies of this pocket edition — one in their daily-carry bag, one in their car's glove compartment, one on their office desk, and one on their bedside table. The durable card cover and binding are engineered to withstand the rigors of constant pocket carrying, where the booklet may be sat on, compressed, and handled dozens of times daily. At Rs.190, this edition is affordable enough to purchase in bulk for distribution at Islamic events, wedding favors, school prizes, mosque libraries, and community outreach programs. For travelers who need a lightweight dua companion, for students who want du'as available between classes, for workers who keep a spiritual lifeline at their workstation, and for anyone who believes that the door of supplication to Allah should never be far from hand, this pocket Hisn ul Muslim is the essential everyday companion.`,
    metaDescription: "Hisn ul Muslim 8x12 Pocket Size — ultra-compact Urdu dua book. 267 authentic daily supplications. Fits in pocket. Only Rs.190. Essential Islamic carry."
  },
  {
    slug: "hisn-ul-muslim-pashto",
    description: `Hisn-ul-Muslim (Pashto Edition) brings the most comprehensive and widely trusted daily supplication collection to the Pashto-speaking Muslim community — translating the complete compilation of 267 authenticated du'as into clear, fluent Pashto that preserves both the accuracy of the original meanings and the devotional beauty that supplication demands. Priced at Rs.400, this edition serves the significant Pashto-speaking population in Pakistan's Khyber Pakhtunkhwa province, the tribal areas, parts of Balochistan, northern Afghanistan, and Pashtun diaspora communities worldwide who have long needed a high-quality Pashto dua reference.

The compilation, originally prepared by Sa'id bin Ali bin Wahf al-Qahtani, organizes the Prophetic supplications into a logical sequence that follows the Muslim's complete daily cycle — from the moment of waking through all activities, worship, and encounters until the time of sleeping. Each du'a is presented with its original Arabic text (in a clear, legible font suitable for readers across all levels of Arabic proficiency), the Pashto translation that conveys the meaning naturally, and the source reference identifying the specific hadith collection and narrator chain. The Pashto translation has been carefully reviewed to ensure that it uses vocabulary and expressions familiar to Pashto-speaking readers — avoiding the overly formal or Arabic-influenced language that can make some translations feel artificial to native speakers.

This Pashto edition fills an important gap in Islamic literature. While Hisn ul Muslim has been available in Arabic, Urdu, English, and many other languages for years, a quality Pashto edition has been relatively scarce — despite the enormous Pashto-speaking Muslim population. The book is particularly valuable for Pashto-speaking families who want to establish the practice of morning and evening adhkar in their homes, for madrasah students studying in Pashto-medium institutions, for mosque imams who deliver khutbahs and lead du'as in Pashto, and for Pashto-speaking new Muslims who are learning the daily prayers in their mother tongue before developing Arabic proficiency. The sections on du'as for protection during travel are especially relevant to the Pashtun communities of Pakistan's northern areas, where mountain travel and challenging terrain make the Prophetic travel supplications a daily necessity. For every Pashto-speaking Muslim household, this Hisn-ul-Muslim provides a complete, reliable, and beautifully translated dua companion that bridges the gap between the timeless Prophetic supplications and the linguistic preferences of the Pashto-speaking ummah.`,
    metaDescription: "Hisn-ul-Muslim Pashto Edition — complete daily dua collection in Pashto. 267 authenticated supplications with Arabic text. Essential for Pashto-speaking Muslims. Rs.400."
  },
  {
    slug: "historical-atlas-of-the-prophets-messengers",
    description: `Historical Atlas of the Prophets and Messengers is a visually stunning, scholarly English-language reference work that combines detailed cartography with comprehensive historical narrative to map the journeys, missions, and legacies of all the prophets mentioned in the Quran and authentic Islamic tradition. Priced at Rs.7,000, this premium atlas is one of the most ambitious Islamic geography and history publications available — offering readers a unique visual understanding of where the prophets lived, traveled, preached, and established their communities across the ancient world.

The atlas features dozens of meticulously researched full-color maps that plot the geographic context of prophetic history with unprecedented detail. Readers can trace Prophet Adam's (AS) story from the Garden to the earth, follow Prophet Nuh's (AS) ark journey, locate the ancient cities where Prophet Ibrahim (AS) preached and traveled, map Prophet Musa's (AS) exodus from Egypt through the Sinai wilderness, trace the routes of Prophet Dawud (AS) and Prophet Sulaiman's (AS) kingdoms, identify the locations associated with Prophet Isa (AS) in the Levant, and of course, follow every significant location in the life of Prophet Muhammad (ﷺ) — from Makkah and Madinah to the farthest reaches of the early Islamic conquests. Each map is accompanied by explanatory text that provides historical context, Quranic references, and hadith evidence for the locations and events depicted.

The historical information is drawn from authentic Islamic sources — the Quran, authenticated hadith collections, classical tafseer works (particularly Ibn Kathir), and respected works of Islamic history such as those by Imam al-Tabari. The atlas also incorporates findings from modern archaeology and historical geography where they support or illuminate the Islamic narrative, while maintaining a clear distinction between definitively established facts and scholarly interpretations or theories. The production quality is exceptional — printed on thick, glossy paper with full-color maps that feature elevation shading, ancient trade routes, city locations, battle sites, and migration paths rendered in clear, professional cartographic style. The binding is durable hardcover designed to withstand years of reference use. For Islamic school libraries, for families who want to bring prophetic history to life for their children, for scholars and researchers studying the geography of revelation, and for any reader who believes that understanding the physical landscapes of prophetic history deepens one's appreciation of the divine message, this Historical Atlas of the Prophets and Messengers is an invaluable and visually breathtaking addition to any Islamic library.`,
    metaDescription: "Historical Atlas of the Prophets & Messengers — full-color maps tracing prophetic journeys from Adam to Muhammad (PBUH). Premium cartography, Rs.7000."
  },
  {
    slug: "history-of-islam-3-vol",
    description: `History of Islam (3 Volume Set) is a comprehensive English-language survey of Islamic civilization from its origins in seventh-century Arabia to the modern era, presented across three substantial volumes that together provide one of the most complete single-author accounts of Muslim history available in the English language. Priced at Rs.10,600 for the complete three-volume set, this work offers exceptional value for readers seeking a thorough, academically grounded, and Islamically sensitive narrative of the faith's development over fourteen centuries.

Volume One covers the foundational period — the pre-Islamic background of Arabia, the life and mission of Prophet Muhammad (ﷺ) in detail, the era of the Rightly Guided Caliphs (Abu Bakr, Umar, Uthman, and Ali), and the early Umayyad period. This volume establishes the political, social, and intellectual foundations upon which Islamic civilization was built, including the compilation of the Quran, the development of hadith literature, the early legal schools, and the rapid territorial expansion that brought Islam from the Arabian Peninsula to the Atlantic coast of Africa and the borders of India within a single century. Volume Two covers the classical golden age — the Abbasid caliphate, the flowering of Islamic science, medicine, philosophy, and literature, the development of sophisticated legal and theological systems, the Crusades and their impact, the Mongol invasions, and the rise of regional Islamic powers including the Mamluks, the Delhi Sultanate, and the Ottoman Empire in its formative stages.

Volume Three brings the narrative to the modern era — covering the Ottoman Empire at its height and decline, the Safavid and Mughal empires, European colonialism and its impact on the Muslim world, the rise of Islamic reform and revival movements, the emergence of modern nation-states in the Muslim world, and contemporary challenges and developments. Throughout all three volumes, the author maintains a balanced perspective that acknowledges both the achievements and the shortcomings of Muslim societies at different periods, avoiding both the uncritical triumphalism and the hostile orientalism that distort so many historical accounts of Islam. The work is based on primary sources where possible, supplemented by respected secondary scholarship from both Muslim and non-Muslim historians. For university students, for Islamic school teachers preparing lessons, for general readers seeking to understand the full arc of Islamic history, and for libraries building comprehensive collections, this three-volume set provides an authoritative, engaging, and beautifully produced historical reference.`,
    metaDescription: "History of Islam 3-Vol Set — comprehensive English survey from Prophet Muhammad (PBUH) to modern era. Golden age, caliphates, civilizations. Rs.10,600."
  },
  {
    slug: "history-of-islam-al-khulafa-ar-rashidun-muawiyah-bin-abi-sufyan",
    description: `History of Islam: Al Khulafa ar-Rashidun and Muawiyah bin Abi Sufyan is a detailed English-language historical work that focuses on the critical thirty-year period following the death of Prophet Muhammad (ﷺ) — the era of the four Rightly Guided Caliphs and the transition to the Umayyad dynasty under Muawiyah ibn Abi Sufyan. Priced at Rs.13,050, this premium volume is one of the most thorough English treatments of this pivotal era available, drawing on classical Islamic sources to present a nuanced, evidence-based account of the events, personalities, and debates that shaped the early Muslim community.

The book devotes substantial chapters to each of the four Rashidun caliphs, presenting their achievements, challenges, and legacy with scholarly balance. Abu Bakr as-Siddiq's brief but transformative caliphate — marked by the Ridda (apostasy) wars, the initiation of the Quran's compilation, and the launch of military campaigns against the Byzantine and Persian empires — is covered in detail. Umar ibn al-Khattab's decade of governance receives extensive treatment, including his administrative reforms, his justice system, his conquest policies, and the circumstances of his assassination. Uthman ibn Affan's caliphate — the period of internal strife (fitnah) that led to his martyrdom — is analyzed with careful attention to the different perspectives that exist within Islamic tradition. Ali ibn Abi Talib's complex and challenging caliphate, including the Battle of the Camel, the arbitration with Mu'awiyah, and the rise of the Khawarij, is presented with scholarly nuance and sensitivity to the differing historical narratives.

The book then covers the caliphate of Muawiyah ibn Abi Sufyan — a pivotal figure in Islamic history whose reign marked the transition from the Rashidun model of leadership to dynastic rule. The author examines Muawiyah's political acumen, his administrative achievements, the consolidation of the Umayyad dynasty, and the complex historical assessment of his legacy that continues to be debated among scholars. The volume features extensive footnotes citing primary Arabic sources (Tabari, Baladhuri, Ibn Kathir, Ibn al-Athir), maps showing the expanding Islamic territories, genealogical charts of key families, and a comprehensive index. The physical production matches the scholarly content — premium hardcover binding, acid-free paper, and professional typesetting. For advanced students of Islamic history, for scholars researching the early caliphate period, and for serious readers who want to move beyond simplified narratives to understand the genuine complexity of Islam's formative decades, this volume provides an indispensable, deeply researched, and intellectually honest historical reference.`,
    metaDescription: "History of Islam: Rashidun & Muawiyah — detailed English account of the four Rightly Guided Caliphs and Umayyad transition. Scholarly, Rs.13,050 hardcover."
  },
  {
    slug: "history-of-islam-abu-bakr-as-siddiq-ra",
    description: `History of Islam: Abu Bakr as-Siddiq (R.A) is a dedicated biographical volume that presents the life and legacy of the first caliph of Islam — the man whom Prophet Muhammad (ﷺ) chose as his companion in the cave during the Hijrah and whom the entire Muslim community accepted as their leader after the Prophet's passing. Priced at Rs.2,650, this English biography draws on authentic hadith sources and classical historical works to paint a vivid portrait of a man whose relatively brief caliphate (approximately two years) laid the foundations for one of history's greatest civilizations.

The narrative begins with Abu Bakr's early life in Makkah — his background among the Quraysh elite, his reputation as a successful and honest merchant, and his remarkable distinction of being the first adult male to accept Islam when Prophet Muhammad (ﷺ) first proclaimed the message. The book details his unwavering support for the Prophet during the most difficult years of persecution in Makkah — his financial sacrifices, his physical protection of the Prophet during hostile confrontations, his role in the migration to Madinah, and his participation in every major battle and treaty. The famous incident in the Cave of Thawr during the Hijrah — when Abu Bakr tearfully expressed fear for the Prophet's safety and received the reassurance "Do not grieve, indeed Allah is with us" — is narrated with the emotional depth this moment deserves.

The core of the book covers Abu Bakr's caliphate, which began with the crisis of the Prophet's death and the subsequent debate over succession. The author examines how Abu Bakr's decisive leadership during the Ridda Wars (Wars of Apostasy) prevented the collapse of the nascent Islamic state, how his insistence on compiling the Quran into a single written volume preserved the divine revelation for all future generations, and how his authorization of military campaigns against the Byzantine and Persian empires set the stage for Islam's rapid expansion. His personal qualities — his humility (he refused a salary from the state treasury), his justice (he returned a horse to its previous owner when he realized he had been overpaid), his compassion, and his devotion to prayer — are illustrated through authenticated hadith. The book concludes with an assessment of Abu Bakr's lasting legacy and the lessons his leadership offers for Muslims in every era. For students of Islamic history, for readers inspired by stories of principled leadership, and for anyone who wants to know the man the Prophet called "the most truthful of all people," this biography provides a thorough, engaging, and spiritually enriching account.`,
    metaDescription: "History of Islam: Abu Bakr as-Siddiq RA — English biography of the first caliph. First male convert, Cave of Thawr companion. Rs.2650."
  },
  {
    slug: "history-of-islam-grade-4",
    description: `History of Islam Grade 4 is a beautifully designed English-language Islamic history textbook specifically crafted for fourth-grade students (approximately 9-10 years old) as part of a comprehensive Islamic studies curriculum. Priced at Rs.1,050, this textbook introduces young Muslim learners to the major events, personalities, and lessons of Islamic history through an age-appropriate, visually engaging, and educationally sound approach that makes history come alive for children at this critical stage of their intellectual and spiritual development.

The textbook is structured around key themes and periods of Islamic history that fourth graders can understand and connect with. It opens with the life of Prophet Muhammad (ﷺ) in a format that builds on the basic Seerah knowledge children acquired in earlier grades, introducing more detailed accounts of major events — the first revelation, the persecution in Makkah, the migration to Madinah, the battles, the treaties, and the farewell pilgrimage. The narrative style is vivid and descriptive, using language that paints mental pictures for young readers without overwhelming them with too many names, dates, or complex political details. Each chapter includes review questions, vocabulary words, and discussion prompts that encourage critical thinking and personal reflection.

The textbook also covers the lives of the Rightly Guided Caliphs at an introductory level, presenting each caliph's major achievements and character qualities in a way that inspires admiration and provides role models for young students. Chapters on the spread of Islam to different regions of the world — North Africa, Spain, Persia, India, Southeast Asia, and Africa — help students understand that Islam is a global faith with a rich, diverse history. The book addresses the contributions of Muslim civilization to science, medicine, mathematics, architecture, and art, helping young Muslims develop pride in their civilizational heritage. The production quality is excellent — full-color illustrations, maps, photographs of historical sites, timelines, and infographics that break up the text and maintain young readers' engagement. Activity sections at the end of each chapter include map exercises, matching activities, short-answer questions, and creative writing prompts. For Islamic school administrators seeking a standards-aligned English history curriculum, for homeschooling parents, and for families supplementing their children's Islamic education at home, this Grade 4 History of Islam textbook provides a well-structured, visually appealing, and pedagogically sound educational resource.`,
    metaDescription: "History of Islam Grade 4 — English Islamic history textbook for ages 9-10. Seerah, caliphs, civilization. Colorful, activities, maps. Rs.1,050."
  },
  {
    slug: "history-of-islam-ali-ibn-abi-taalib-ra",
    description: `History of Islam: Ali Ibn Abi Taalib (R.A) is a comprehensive English biography of the fourth Rightly Guided Caliph — a figure of extraordinary complexity and significance in Islamic history whose life encompasses the highest virtues of faith, knowledge, courage, and sacrifice. Priced at Rs.3,250, this volume is one of the most thorough English-language treatments of Ali's life available, presenting his story through authentic Islamic sources while navigating the historical complexities with scholarly integrity and balance.

The book traces Ali's life from his earliest days — his birth inside the Ka'bah (a distinction unique to him among all human beings), his upbringing in the household of Prophet Muhammad (ﷺ) after being taken in as a young child, and his position as the first youth to accept Islam. The author documents the close personal bond between Ali and the Prophet, including his marriage to the Prophet's daughter Fatimah (RA) and his role as one of the most knowledgeable companions in matters of Islamic law and Quranic interpretation. Ali's participation in every major battle during the Prophet's lifetime — including his legendary bravery at the Battle of Badr, Uhud, the Trench (Khandaq), and the conquest of Makkah — is narrated with detail drawn from authenticated hadith and classical historical sources.

The central portion of the book covers Ali's caliphate (656-661 CE), which was perhaps the most challenging period any Islamic leader has faced. The author provides a detailed account of the fitnah (civil strife) that dominated Ali's reign — including the Battle of the Camel against Aishah, Talhah, and Zubayr; the extended conflict with Muawiyah ibn Abi Sufyan that culminated in the Battle of Siffin and the subsequent arbitration; and the emergence of the Khawarij sect. These events are analyzed with careful attention to the various historical perspectives, helping readers understand why different Muslim communities have interpreted these events differently while maintaining respect for all parties involved. The book does not shy away from the difficulties and tragedies of this period, including the assassination of Ali ibn Abi Talib by a Kharijite extremist in the mosque of Kufa. Ali's legacy as a scholar, jurist, and paragon of piety is examined in the concluding chapters — including his famous collection of wisdom known as Nahj al-Balaghah (The Peak of Eloquence). For students of Islamic history, for researchers studying the early caliphate period, and for readers seeking a balanced, comprehensive, and well-sourced account of this towering figure in Islamic civilization, this biography provides outstanding scholarly depth and readability.`,
    metaDescription: "History of Islam: Ali Ibn Abi Taalib RA — comprehensive English biography of the 4th caliph. Scholarship, bravery, and complex caliphate. Rs.3250."
  },
  {
    slug: "history-of-islam-muawiyah-bin-abi-sufyan-ra",
    description: `History of Islam: Muawiyah Bin Abi Sufyan (R.A) is a focused English-language historical study of one of the most consequential and controversial figures in early Islamic history — the man who served as governor of Syria for twenty years before becoming the fifth caliph and founder of the Umayyad dynasty that ruled the Islamic world for nearly a century. Priced at Rs.2,450, this volume approaches Muawiyah's life and legacy with the scholarly balance and source-based methodology that this complex subject demands, drawing on classical Islamic histories, hadith literature, and respected academic research.

The book begins with Muawiyah's early life — his upbringing in the powerful Umayyad clan of the Quraysh, his father Abu Sufyan's initial opposition to Islam and subsequent conversion, and Muawiyah's own eventual embrace of the faith. The author documents his skills as a scribe of Quranic revelation during the Prophet's lifetime — a role that indicates his literacy and trustworthiness — and his appointment as governor of Syria by Umar ibn al-Khattab, a position he maintained under Uthman and which he transformed into the most well-organized and militarily powerful province in the Islamic empire. Muawiyah's administrative abilities, his diplomatic skills, his development of a naval fleet that contested Byzantine control of the Mediterranean, and his governance model for Syria are examined in detail.

The most challenging aspects of Muawiyah's career — his conflict with Ali ibn Abi Talib during the fitnah, the Battle of Siffin, the arbitration episode, and the political maneuvering that eventually led to his accession as caliph — are treated with scholarly rigor and sensitivity. The author presents the multiple perspectives that exist within Islamic tradition regarding these events, citing the relevant sources and allowing readers to understand the complexity of the historical record. The book covers Muawiyah's caliphal period, including his administrative reforms, his expansion of the Islamic empire, his relationship with the various Muslim factions, and the controversial practice of naming his son Yazid as his successor that ended the system of caliphal selection by consultation. The volume includes genealogical charts, maps of the territories under Muawiyah's control, extensive footnotes, and a bibliography of primary and secondary sources. For university-level students of Islamic history, for scholars researching early Islamic political institutions, and for general readers seeking to understand one of history's most debated Islamic leaders, this biography provides a thorough, well-documented, and intellectually honest treatment.`,
    metaDescription: "History of Islam: Muawiyah Bin Abi Sufyan RA — English biography covering his governorship, caliphate, and Umayyad legacy. Balanced scholarly treatment. Rs.2450."
  },
  {
    slug: "history-of-islam-umar-bin-al-khattab-ra",
    description: `History of Islam: Umar Bin al-Khattab (R.A) is a comprehensive English biography of the second caliph of Islam — a man whose ten-year reign transformed the Muslim community from a small city-state in Madinah into one of the largest empires the world had ever seen, and whose administrative genius, uncompromising justice, and personal piety have made him one of the most admired leaders in all of human history. Priced at Rs.2,950, this volume presents the complete story of Umar's remarkable journey from a fierce opponent of Islam to the most powerful ruler of his age, drawing on authentic hadith, classical biographical sources, and modern historical scholarship.

The narrative begins with Umar's pre-Islamic life among the Quraysh — his physical strength, his reputation as a wrestler and orator, his role as an envoy of the Quraysh, and his fierce opposition to the early Muslim community. His dramatic conversion story — setting out to assassinate the Prophet but being stopped by the sight of his own sister and brother-in-law reading the Quran, which moved him to embrace Islam — is narrated with the vivid detail it deserves. The book then covers Umar's role during the Prophet's lifetime, including his close companionship with the Prophet (who once said that if a prophet were to come after him, it would have been Umar), his participation in battles, and his counsel on major decisions.

The heart of the biography covers Umar's caliphate (634-644 CE), widely regarded as a golden age of Islamic governance. The author provides detailed accounts of Umar's military conquests — the fall of Persia, the conquest of Syria, Egypt, and much of the Byzantine Empire — while emphasizing that Umar's greater achievement was his administrative system. The book documents his establishment of the diwan (public treasury), his judicial reforms, his municipal governance model for conquered cities, his welfare system for the poor, elderly, and disabled, his land tax regulations, his approach to the rights of non-Muslim citizens under Islamic rule, and his personal lifestyle of extreme simplicity despite commanding the greatest empire of his time. Famous stories of his justice — wandering the streets of Madinah at night in disguise to check on his people's welfare, holding himself and his own family to the strictest accountability — are presented with their full hadith chains and historical context. For anyone inspired by principled leadership and just governance, this biography of Umar ibn al-Khattab provides a masterclass in Islamic statesmanship that remains deeply relevant to the modern world.`,
    metaDescription: "History of Islam: Umar Bin al-Khattab RA — English biography of Islam's 2nd caliph. Justice, conquests, governance genius. Inspirational leadership. Rs.2950."
  },
  {
    slug: "history-of-islam-uthman-ibn-affan-ra",
    description: `History of Islam: Uthman Ibn Affan (R.A) is a dedicated English biography of the third Rightly Guided Caliph — the companion of Prophet Muhammad (ﷺ) known as "Dhu al-Nurayn" (Possessor of Two Lights) for his marriages to two of the Prophet's daughters and for his renowned generosity, modesty, and devotion. Priced at Rs.2,650, this volume presents a comprehensive, source-based account of Uthman's life that does justice to both his remarkable achievements and the tragic circumstances of his martyrdom — an event that marked one of the most painful turning points in Islamic history.

The biography begins with Uthman's background among the wealthy Umayyad clan of the Quraysh and his early conversion to Islam — becoming one of the earliest Muslims despite the social and financial cost this decision entailed. The book documents his generous financial contributions to the Muslim community, including his funding of several major military expeditions during the Prophet's lifetime (earning the Prophet's prophecy of Paradise for him), his marriages to Ruqayyah and then Umm Kulthum (the Prophet's daughters), and his character traits of humility, patience, and quiet strength that distinguished him from the more assertive personalities among the companions.

The central portion of the book covers Uthman's twelve-year caliphate (644-656 CE), which saw the Islamic empire continue its expansion while facing growing internal tensions. The author provides a balanced analysis of Uthman's governance — including his appointment of family members to provincial governorships (a decision that generated significant opposition), his economic policies, his handling of the growing tribal and ethnic tensions within the Muslim community, and his unprecedented achievement of standardizing and distributing the complete written text of the Quran — a contribution whose value to Islamic civilization is literally immeasurable. The crisis that led to Uthman's martyrdom is examined in detail, with the author presenting the various perspectives from different historical sources and explaining how the fitnah that began during Uthman's time shaped the subsequent course of Islamic history. The book does not gloss over the controversies but treats them with the scholarly rigor and Islamic sensitivity they require. For students of Islamic history, for researchers studying the early caliphate, and for readers who want to understand one of Islam's most important yet often misunderstood leaders, this biography of Uthman ibn Affan provides a thorough, balanced, and enlightening account.`,
    metaDescription: "History of Islam: Uthman Ibn Affan RA — English biography of the 3rd caliph. Quran compilation, generosity, martyrdom. Balanced scholarly account. Rs.2650."
  },
  {
    slug: "history-of-madinah-munawwarah",
    description: `History of Madinah Munawwarah is a comprehensive English-language historical work that chronicles the story of the city the Quran calls "Al-Madinah" (The City) — one of the most sacred places on earth for over 1.9 billion Muslims worldwide and the destination of millions of pilgrims every year. Priced at Rs.950, this book traces Madinah's extraordinary journey from a small desert oasis inhabited by Jewish and polytheist Arab tribes to the radiant city that became the first Islamic capital, the burial place of Prophet Muhammad (ﷺ), and a center of learning and civilization that has influenced the entire course of human history.

The narrative begins with Madinah's pre-Islamic period — known as Yathrib — describing its geography, climate, tribal structure, agricultural economy (famous for its date palms), and the social tensions between its Arab tribes (Aws and Khazraj) and its Jewish communities (Banu Qaynuqa, Banu Nadir, and Banu Qurayzah). The book explains how these internal conflicts created the conditions that led the city's leaders to seek the Prophet's mediation — culminating in the First and Second Pledges of Aqabah and the historic migration (Hijrah) that transformed both the city and the world. The author provides detailed descriptions of the Prophet's arrival in Madinah, the building of the first mosque (Masjid al-Nabawi), the establishment of the Islamic state, and the drafting of the Constitution of Madinah — widely regarded as the first written constitution in history.

Subsequent chapters cover Madinah's development during the caliphate period, its role as the capital of the Rashidun caliphate, the expansion of the Prophet's Mosque under successive rulers, and the city's evolution through the Umayyad, Abbasid, Mamluk, and Ottoman periods. The book documents the major historical events that took place in Madinah, the development of its Islamic educational institutions, the lives of its scholars and inhabitants, and the physical transformation of the city's sacred sites — particularly the Prophet's Mosque and its surrounding area. The author also addresses the modern history of Madinah, including the Saudi expansion of the Prophet's Mosque, the development of the city's infrastructure to accommodate millions of annual visitors, and the preservation efforts that protect the city's historical heritage. Maps, photographs of historical sites, and architectural illustrations enhance the text throughout. For Hajj and Umrah pilgrims who want to understand the history of the city they are visiting, for students of Islamic history, and for anyone who loves Madinah and wants to know its story, this book provides an informative, well-researched, and visually enriched reading experience.`,
    metaDescription: "History of Madinah Munawwarah — English historical survey of the Prophet's city. Pre-Islamic to modern era, Masjid al-Nabawi, Hajj guide. Rs.950."
  },
  {
    slug: "history-of-makkah",
    description: `History of Makkah is an informative English-language work that presents the complete historical narrative of Islam's holiest city — from its ancient origins in the deserts of the Hijaz to its current status as a modern metropolis that welcomes millions of Muslim pilgrims annually for Hajj and Umrah. Priced at Rs.950, this book offers readers a comprehensive understanding of Makkah's sacred significance, its historical development, and its enduring role as the spiritual center of the Islamic world.

The book begins with the legendary and scriptural history of Makkah — the story of Prophet Ibrahim (AS) and his wife Hajar, the miraculous appearance of the Zamzam well, Ibrahim's construction of the Ka'bah with his son Ismail, and the establishment of Makkah as a center of monotheistic worship that was gradually corrupted into polytheism over the centuries. The author discusses Makkah's geography and its unusual position in a barren valley — a location that seems illogical for a major city but that Allah chose to test the faith of its inhabitants and to demonstrate His blessing upon those who worship Him. The pre-Islamic period covers the Quraysh tribe's custodianship of the Ka'bah, the development of Makkah as a major trade hub (particularly through its winter and summer caravans), and the religious and social conditions that prevailed when Prophet Muhammad (ﷺ) was born.

The heart of the book covers the Islamic period of Makkah's history — the Prophet's mission, the persecution of Muslims, the migration to Madinah, the battles between the Muslims and the Quraysh, the eventual conquest of Makkah in 8 AH (630 CE), and the Prophet's purification of the Ka'bah from its 360 idols. The author documents the physical changes to Makkah and the Ka'bah during the Prophet's lifetime and under subsequent caliphs. Later chapters trace Makkah's development through the Abbasid, Mamluk, and Ottoman periods, including the various renovations and expansions of the Masjid al-Haram, the challenges posed by natural disasters and political upheavals, and the city's enduring religious significance despite its changing political circumstances. The book brings the narrative to the modern era, covering the Saudi era's massive expansion of the Masjid al-Haram, the development of the surrounding infrastructure (hotels, transportation, the Metro), and the ongoing efforts to accommodate the growing numbers of pilgrims while preserving the city's sacred character. Photographs, historical illustrations, and maps enrich the text. For every Muslim who dreams of visiting Makkah, for pilgrims preparing for their journey, and for readers interested in the history of humanity's most important religious site, this book provides a thorough and engaging account.`,
    metaDescription: "History of Makkah — English historical narrative of Islam's holiest city. From Ibrahim (AS) to modern era, Ka'bah, Masjid al-Haram. Rs.950."
  },
  {
    slug: "holnak-aag-qissa-syedna-ibrahim-silsila-qasas-ul-anbiya-630",
    description: `Holnak Aag (Qissa Syedna Ibrahim) is the sixth installment of the Silsila Qasas ul Anbiya (Series of Prophetic Stories) — a popular Urdu children's book series that retells the stories of the prophets in an engaging, age-appropriate narrative style. Priced at just Rs.220, this volume tells the dramatic story of Prophet Ibrahim (peace be upon him) and the miraculous fire into which his people threw him — an event that the Quran describes as one of the most powerful demonstrations of Allah's protection of His faithful servants.

The title "Holnak Aag" (The Fierce Fire) immediately captures the dramatic tension at the heart of this story. The book opens by introducing young readers to Prophet Ibrahim's situation — a lone believer in the one true God standing against his entire community, including his own father Azar, who was an idol maker. Ibrahim's famous act of smashing the idols — leaving only the largest one and placing the axe in its hands, then telling his people to ask it who destroyed the others — is narrated in simple, vivid Urdu that children can understand and visualize. The community's furious response — building a massive fire and throwing Ibrahim into it — is described with appropriate dramatic intensity while remaining suitable for young readers.

The central miracle — Allah's command to the fire, "O fire, be cool and safe for Ibrahim" — is presented as the powerful divine intervention that it was, teaching children the lesson that Allah protects those who stand firm in their faith regardless of the odds against them. The book draws a clear moral from the story about the importance of speaking truth to power, the foolishness of worshipping man-made objects, and the limitless power of Allah over all creation. The Silsila Qasas ul Anbiya series is specifically designed for Pakistani children aged 6 to 12, using language that is simple yet literary, with illustrations that bring the stories to life without violating Islamic guidelines on the depiction of prophets. Each volume includes a set of review questions at the end that test comprehension and encourage discussion between parents and children. This sixth volume, with its theme of faith versus fire, is one of the most popular in the series and is frequently purchased as a gift for children during Eid al-Adha — when the story of Ibrahim's sacrifice and devotion is especially relevant. For families building their children's Islamic library, this affordable volume provides an excellent and spiritually enriching addition.`,
    metaDescription: "Holnak Aag — Qissa Syedna Ibrahim, Silsila Qasas ul Anbiya 6/30. Urdu kids' story of Prophet Ibrahim and the miraculous fire. Ages 6-12, Rs.220."
  },
  {
    slug: "holnak-azab-qissa-syedna-shoaib-silsila-qasas-ul-anbiya-1430",
    description: `Holnak Azab (Qissa Syedna Shoaib) is the fourteenth volume of the acclaimed Silsila Qasas ul Anbiya children's series — retelling in accessible Urdu the story of Prophet Shu'aib (peace be upon him) and the dramatic divine punishment that befell the people of Madyan who rejected his message. Priced at Rs.220, this installment introduces young Muslim readers to one of the Quran's most compelling stories about the consequences of cheating in trade, the importance of fair business dealings, and the certainty of divine justice for those who persist in wrongdoing.

Prophet Shu'aib was sent to the people of Madyan — a community known for their involvement in trade and commerce but also notorious for their dishonesty. The book explains, in language suitable for children, how the people of Madyan used to cheat in their measurements and weights when selling goods, how they blocked roads and robbed travelers, and how they worshipped a sacred grove of trees instead of the one true God. Prophet Shu'aib warned his people repeatedly, calling them to honest dealings, fair trade, and the worship of Allah alone — but they mocked him, rejected his message, and threatened to expel him and his followers.

The dramatic climax of the story — the divine punishment that destroyed Shu'aib's people — is narrated with appropriate gravity, teaching children the serious Quranic lesson that communities which persist in oppression and dishonesty ultimately face consequences. The book emphasizes the positive lessons: honesty in business, fairness in dealings, patience in delivering the message of truth, and trust in Allah's justice even when the wrongdoers seem powerful and successful. As with all volumes in the Qasas ul Anbiya series, the story is based directly on Quranic narrative, with references to the relevant Surah and verses provided so that parents can connect the children's storybook to the actual Quranic text. The book features colorful illustrations (observing Islamic guidelines regarding prophetic depiction), simple yet elegant Urdu text, and review questions at the end. This fourteenth volume is particularly relevant in today's world, where discussions about business ethics, honesty, and accountability are more important than ever — giving parents an excellent opportunity to discuss these values with their children through the lens of Quranic storytelling. For children's Islamic education at home, for Islamic school libraries, and for parents looking to build a complete set of the Qasas ul Anbiya series, this volume at Rs.220 offers both educational and moral value.`,
    metaDescription: "Holnak Azab — Qissa Syedna Shoaib, Silsila Qasas ul Anbiya 14/30. Urdu kids' story on honesty, trade ethics, and divine justice. Ages 6-12. Rs.220."
  },
  {
    slug: "holnak-toofan-qissa-syedna-nooh-silsila-qasas-ul-anbiya-330",
    description: `Holnak Toofan (Qissa Syedna Nooh) is the third volume of the beloved Silsila Qasas ul Anbiya children's series — bringing to life in Urdu the epic story of Prophet Nuh (Noah, peace be upon him) and the Great Flood that Allah sent as a punishment upon those who rejected His message. Priced at Rs.220, this volume introduces young readers to one of the most dramatic and universally recognized stories in human religious tradition, told from the Islamic perspective with all its Quranic details and spiritual lessons intact.

The story begins by introducing children to Prophet Nuh — a righteous man whom Allah chose to warn his people about their idol worship and immoral behavior. The book describes, in language carefully calibrated for children aged 6 to 12, how Prophet Nuh spent 950 years calling his people to the worship of one God — an extraordinary demonstration of patience and persistence that the Quran highlights as one of the longest prophetic missions in history. Despite centuries of preaching, only a small group of believers accepted his message, while the majority continued in their arrogance and mockery.

The building of the Ark (Safinah) is narrated with vivid detail — how Prophet Nuh, who had never built a ship before, followed Allah's instructions to construct a massive vessel, and how his people laughed and ridiculed him for building a boat in the middle of dry land far from any sea. When the Great Flood came, the book describes how the earth opened up with springs of water, the sky poured down rain, and the Ark floated on the rising waters carrying Prophet Nuh, the believing members of his family, and pairs of animals to safety. The heartbreaking moment when Nuh's own son refused to board the Ark — choosing instead to climb a mountain that was ultimately submerged — is told with sensitivity, teaching children about the painful reality that even family members may reject the truth and that a parent's love cannot override a person's choice. The story concludes with the Ark coming to rest on Mount Judi and the new beginning that awaited Prophet Nuh and his companions. The moral lessons — patience in adversity, obedience to Allah even when others mock, the consequences of rejecting truth, and the importance of family bonds — are woven naturally into the narrative rather than presented as heavy-handed lectures. For families building their children's understanding of Quranic stories, this third volume of the Qasas ul Anbiya series delivers an engaging, educational, and spiritually enriching reading experience at an affordable price.`,
    metaDescription: "Holnak Toofan — Qissa Syedna Nooh, Silsila Qasas ul Anbiya 3/30. Urdu kids' story of Noah and the Great Flood. Patience and faith. Ages 6-12, Rs.220."
  },
  {
    slug: "holy-makkah-brief-history-geography-hajj-guide",
    description: `Holy Makkah: Brief History, Geography and Hajj Guide is a practical and informative English-language handbook that combines essential historical and geographical information about Makkah with a step-by-step Hajj and Umrah guide — making it an ideal all-in-one reference for pilgrims preparing for their journey to the House of Allah. Priced at Rs.950, this compact volume is designed to be carried during the pilgrimage, fitting easily into a travel bag or pocket alongside other essential Hajj supplies.

The book opens with a concise but comprehensive history of Makkah — from its founding after Prophet Ibrahim and Ismail constructed the Ka'bah, through the pre-Islamic period of the Quraysh, to the Prophet's conquest of Makkah and the subsequent development of the holy city across the centuries. This historical overview helps pilgrims understand the sacred significance of every location they will visit, transforming their physical journey into a deeper spiritual and educational experience. The geography section provides detailed descriptions of Makkah's location in the Hijaz mountains, its climate, its current layout (including the expansion of the Masjid al-Haram and the surrounding hotel and infrastructure development), and orientation information that helps pilgrims navigate the city during the crowded Hajj and Umrah seasons.

The Hajj and Umrah guide section is the most practical portion of the book. It provides clear, step-by-step instructions for performing every ritual of Hajj (the five days from the 8th to the 12th of Dhul Hijjah) and Umrah (the lesser pilgrimage that can be performed year-round). Each ritual is explained with its Arabic name, the specific du'as to be recited at each stage (provided in Arabic with English transliteration and translation), the common mistakes to avoid, and practical tips for managing the physical challenges of the pilgrimage — heat, crowds, fatigue, and the logistics of moving between Makkah, Mina, Arafat, and Muzdalifah. The book includes maps of the Masjid al-Haram showing key locations (the Ka'bah, Maqam Ibrahim, Hijr Ismail, Zamzam well, Safa and Marwah), maps of the Hajj sites, and a checklist of essential items to bring. The compact format, durable cover, and clear layout make this book an ideal pilgrimage companion. For first-time pilgrims who want a single comprehensive guide, for experienced pilgrims who appreciate a quick reference, and for anyone planning to visit the holy cities, Holy Makkah provides the essential information needed in a format that is both practical and spiritually enriching.`,
    metaDescription: "Holy Makkah: History, Geography & Hajj Guide — English handbook with step-by-step Hajj/Umrah instructions, du'as, maps. Essential pilgrimage companion. Rs.950."
  },
  {
    slug: "holy-quran-holder-mdf-rehal",
    description: `Holy Quran Holder (MDF Rehal) is a beautifully designed, sturdy book rest crafted from Medium Density Fiberboard (MDF) — a modern engineered wood material that offers superior durability, consistent quality, and resistance to the warping and cracking that can affect traditional solid wood rehals in Pakistan's variable climate conditions. Priced at Rs.1,600, this MDF rehal combines the elegance of traditional Islamic craftsmanship with the practical advantages of modern manufacturing, resulting in a Quran holder that is both beautiful and built to last.

The MDF material provides several important advantages over natural wood for a rehal that will be used daily. Unlike solid wood, which can warp, split, or develop cracks in humid conditions or when exposed to temperature changes, MDF maintains its shape and structural integrity under all normal household conditions. This makes it particularly well-suited for Pakistani homes where seasonal humidity variations can be significant. The MDF surface is finished with a smooth laminate that is easy to clean, resists stains, and provides a stable platform for Quran volumes of all sizes — from compact pocket Mushafs to large deluxe editions and heavy reference Qurans with tafseer.

The design of this MDF rehal follows the classic X-frame folding pattern that has been used for Quran holders across the Muslim world for centuries. The folding mechanism allows the rehal to open and close smoothly, and the angled reading surface holds the Quran at an optimal angle for comfortable reading — reducing neck and back strain during extended recitation sessions. When folded flat, the rehal's slim profile allows it to be stored on a bookshelf, beside the prayer mat, or in a drawer without taking up significant space. The weight of the MDF construction provides good stability — preventing the rehal from tipping when larger books are placed on it — while remaining light enough to carry easily between rooms or to the mosque.

The aesthetic design features an elegant Islamic motif on the front panels — executed through precision printing or laser engraving that reproduces traditional Islamic geometric and floral patterns with the crisp detail that MDF's smooth surface allows. The finish is available in natural wood tones and dark wood tones that complement both traditional and contemporary home decor. This MDF rehal is an excellent choice for daily Quran readers who want a durable, low-maintenance book holder, for Islamic school classrooms where multiple rehals are needed and consistent quality is important, and for anyone who appreciates the marriage of traditional Islamic design with modern materials and manufacturing precision. For households where the Quran is read daily and the rehal needs to withstand years of regular use without degradation, this MDF Holy Quran Holder delivers outstanding quality and enduring value.`,
    metaDescription: "Holy Quran Holder MDF Rehal — durable engineered wood Quran stand. Folding X-frame, Islamic motif, climate-resistant. Ideal daily use. Rs.1600."
  },
  {
    slug: "honorable-wives-of-the-prophet-pbuh",
    description: `Honorable Wives of the Prophet (PBUH) is a comprehensive English-language biographical work that presents the lives and contributions of the Mothers of the Believers (Ummahat al-Mu'minin) — the wives of Prophet Muhammad (ﷺ) whom Allah has elevated to a status of unparalleled honor in Islam. Priced at Rs.1,650, this volume provides detailed, source-based biographies of each of the Prophet's wives, offering readers a nuanced understanding of these remarkable women whose lives, scholarship, sacrifices, and personal qualities provide timeless role models for Muslim men and women alike.

The book dedicates substantial chapters to each of the Prophet's wives, beginning with Khadijah bint Khuwaylid — the first believer, the Prophet's supporter during the most difficult years of his mission, and the woman about whom the Prophet said he was given sustenance because of her. The narrative continues with Sawdah bint Zam'ah, whose early acceptance of Islam and generous nature provided comfort to the Prophet's household; Aishah bint Abu Bakr, whose extraordinary intellect, knowledge of hadith, and scholarship earned her the title "Mother of the Believers" in the fullest sense; Hafsah bint Umar, the custodian of the first written compilation of the Quran; Zaynab bint Khuzaymah, known for her generosity to the poor; Umm Salamah Hind bint Abi Umayyah, whose wisdom and counsel the Prophet valued; Zaynab bint Jahsh, whose marriage to the Prophet carried profound symbolic significance; Juwayriyyah bint al-Harith, Umm Habibah Ramlah bint Abi Sufyan, Safiyyah bint Huyayy, and Maymunah bint al-Harith — each of whose stories illuminates different aspects of the Prophet's character and the diverse backgrounds of the early Muslim community.

The author draws primarily on authentic hadith sources (Sahih al-Bukhari, Sahih Muslim, and other verified collections) and classical biographical works, presenting each wife's story with scholarly rigor while maintaining the reverence and respect that their status demands. The book addresses common misconceptions and polemical arguments about the Prophet's marriages with evidence-based responses and contextual analysis. It highlights the scholarly contributions of the Prophet's wives — particularly Aishah, who narrated over 2,200 hadith and was one of the most important sources of Islamic jurisprudence, and Umm Salamah, who narrated over 300 hadith. The women's personal qualities — their faith, patience, generosity, knowledge, courage, and devotion to worship — are emphasized throughout, showing how they embodied the Islamic ideal of womanhood in diverse and inspiring ways. For Muslim women seeking female role models from Islamic history, for students of Seerah and hadith, and for any reader who wants to understand the human dimension of the Prophet's household, this book provides a thorough, well-sourced, and deeply respectful treatment of the Honorable Wives of the Prophet (PBUH).`,
    metaDescription: "Honorable Wives of the Prophet PBUH — English biographies of the Mothers of the Believers. Khadijah, Aishah, Hafsah and more. Scholarly, Rs.1650."
  }
];

async function main() {
  let updated = 0, failed = 0;
  for (const item of updates) {
    try {
      await prisma.product.update({ where:{slug:item.slug}, data:{description:item.description, metaDescription:item.metaDescription} });
      console.log(`✅ Updated: ${item.slug}`);
      updated++;
    } catch (err) { console.log(`❌ Failed: ${item.slug} — ${err.message}`); failed++; }
  }
  console.log(`\nBatch R5E-R5G complete: ${updated} updated, ${failed} failed`);
}
main().then(() => prisma.$disconnect());
