const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "misali-musalman-mard",
    description: `Misali Musalman Mard, penned in Urdu, addresses the vital subject of Muslim masculinity as defined by Islamic teachings rather than contemporary cultural norms. In an era where competing visions of manhood shape the behavior and expectations of young men, this book offers a coherent, source-based model of the ideal Muslim man drawn from the Quran, the Sunnah, and the lives of the Companions and righteous predecessors.

The book establishes its framework by examining the character of Prophet Muhammad (peace be upon him) as the ultimate exemplar of Muslim manhood. His courage in standing for truth despite persecution, his tenderness with his family, his justice in governance, his humility despite unparalleled status, and his steadfastness in worship all demonstrate that Islamic masculinity integrates strength with compassion, authority with service, and ambition with contentment. Each of these qualities is explored in dedicated chapters with supporting evidence from authentic narrations.

The lives of the male Companions provide additional models, each illustrating different facets of Islamic character. Abu Bakr's unwavering faith and generosity, Umar's sense of justice and administrative acumen, Ali's knowledge and bravery, and Uthman's modesty and devotion—these profiles show that Islamic excellence takes varied forms while remaining anchored to shared principles. The book also profiles less prominent Companions whose specific virtues offer relatable examples for ordinary Muslims striving to improve themselves.

Practical chapters address the responsibilities that Muslim men bear in their various roles: as sons responsible for honoring their parents, as husbands entrusted with the care and well-being of their wives, as fathers tasked with raising righteous children, as community members obligated to enjoin good and forbid evil, and as workers and providers who must earn halal sustenance. The book discusses common challenges faced by Muslim men today—including anger management, maintaining integrity in the workplace, balancing worldly ambition with spiritual priorities, and resisting societal pressures toward materialism and moral compromise. Each chapter concludes with actionable guidance rooted in Islamic teachings.`,
    metaDescription: "Urdu guide defining Islamic masculinity through Prophetic example and Companion profiles, covering roles as son, husband, father, and community member."
  },
  {
    slug: "mishkat-al-masabih-3-vols-set-amm",
    description: `Mishkat al-Masabih occupies a distinguished position among the hadith collections of Islamic literature, serving as a widely used reference work for scholars, students, and judges across centuries of Muslim civilization. This three-volume edition, identified by the "Amm" designation indicating its particular publishing variant, presents the full text of this classical compilation with careful attention to editorial quality and readability. Al-Khatib al-Tabrizi's refinement of Masabih al-Sunnah by al-Baghawi transformed the work into one of the most accessible yet comprehensive hadith references available.

The organization of Mishkat al-Masabih follows a thematic structure that groups hadith according to their subject matter, making it an exceptionally practical reference for locating narrations on specific topics. The books and chapters cover the full spectrum of Islamic knowledge: faith and creed, the pillars of worship, transactions and commerce, marriage and divorce, food and drink, dress and adornment, medicine, jihad, virtues of the Companions, and descriptions of the Hereafter. This systematic arrangement means that a reader seeking hadith on a particular topic can locate relevant narrations efficiently without searching through an unorganized collection.

The chain of transmission for each hadith is preserved in the text, allowing readers and scholars to trace the narration back to its source. Al-Tabrizi's editorial work included adding narrations from Sahih al-Bukhari and Sahih Muslim to strengthen the evidentiary basis of the collection, while also noting the authenticity status of narrations from other sources. This makes the Mishkat a reliable middle-ground collection—more comprehensive than the two Sahihs alone, yet more selective than the massive compilations that include weaker narrations.

This three-volume format provides adequate space for the text and its editorial apparatus, ensuring that the pages are not overly dense or difficult to read. The binding and paper quality support regular use and reference, which is essential for a work that serves as a continuing reference rather than a one-time read. Scholars preparing khutbahs, students of Islamic studies, and anyone seeking verified Prophetic guidance on specific matters will find this edition a valuable addition to their library.`,
    metaDescription: "Three-volume Mishkat al-Masabih edition with thematic hadith organization, preserved chains of transmission, and editorial quality for scholarly reference."
  },
  {
    slug: "mishkat-al-masabih-3-vols-set",
    description: `Hadith literature forms the second primary source of Islamic law and guidance after the Quran, and among the many compilations available to Muslim scholars and students, Mishkat al-Masabih holds a uniquely balanced position. This three-volume set presents the complete work in a distinct edition that offers its own typographic and formatting characteristics, providing readers with an alternative to other available printings. The enduring popularity of Mishkat al-Masabih across the Muslim world testifies to the effectiveness of al-Tabrizi's editorial vision in creating a hadith collection that is simultaneously comprehensive, reliable, and navigable.

The collection derives from al-Baghawi's Masabih al-Sunnah, which al-Tabrizi enhanced by incorporating additional narrations—particularly from Sahih al-Bukhari and Sahih Muslim—and by refining the organizational structure. The result is a work that serves effectively both as a teaching tool for Islamic seminaries and as a personal reference for individuals seeking Prophetic guidance on matters of daily life. The thematic arrangement covers virtually every aspect of Islamic practice and belief, from the fundamentals of creed to the specific rulings on ritual purity, prayer, fasting, pilgrimage, charity, marriage, business ethics, social conduct, and eschatology.

Each hadith in the collection is presented with its chain of narrators, preserving the isnad that is central to the Islamic science of hadith evaluation. Where the original compiler or editor has noted the authenticity grade of a narration, these notations are included, allowing readers to distinguish between sahih, hasan, and daif narrations. This transparency makes the Mishkat suitable for both general reading and scholarly work requiring verified sources.

The three-volume physical format divides the substantial text into manageable portions. Readers can work through one volume at a time without being overwhelmed by the total size of the collection. The volumes also facilitate shared use in study circles and classroom settings where multiple readers may need to consult the text simultaneously. For institutions, libraries, and individual scholars, this edition of Mishkat al-Masabih provides a complete, well-formatted hadith reference that has stood the test of scholarly scrutiny for centuries.`,
    metaDescription: "Three-volume Mishkat al-Masabih hadith collection with thematic organization, preserved chains of transmission, and authenticity grading."
  },
  {
    slug: "missing-out-on-rewards",
    description: `The Islamic concept of reward extends far beyond the formal acts of worship, encompassing a vast range of daily activities and interactions that most Muslims either overlook or perform without realizing their spiritual value. Missing Out on Rewards draws attention to these frequently neglected opportunities for earning divine merit, helping readers identify and act upon the many small deeds that accumulate into substantial spiritual credit.

The book systematically catalogs categories of rewarded actions that are commonly missed. The chapter on speech, for instance, highlights the rewards associated with dhikr—remembrance of Allah—that can be performed during routine activities: commuting, cooking, waiting in lines, walking, and resting. Specific phrases from the Sunnah, such as subhanAllah, alhamdulillah, and la ilaha illallah, are explained with their reported merits and the contexts in which the Prophet recommended their recitation. The reward for greeting others with salam, for speaking kind words, and for remaining silent when speech serves no beneficial purpose are similarly detailed.

Physical acts that carry unexpected spiritual weight receive attention throughout the book. Sleeping with the intention of resting for worship, eating with the right hand and in the name of Allah, drinking water in three sips, entering and exiting the home and mosque with the prescribed supplications, and using the miswak—these seemingly mundane actions are presented with their supporting hadith evidence, transforming the reader's understanding of everyday life from a series of worldly tasks to a continuous stream of potential rewards.

Social interactions provide another rich category of often-overlooked rewards. Smiling at a fellow Muslim, removing obstacles from the road, helping someone load their belongings, visiting the sick, and attending funerals are all acts that the Prophet explicitly associated with divine reward. The book also discusses the rewards of parenthood—raising righteous children, showing patience with their development, and providing them with Islamic education—as investments that continue yielding spiritual returns long after the parent's own lifetime.

The book's practical approach makes it suitable for Muslims at all levels of religious knowledge who wish to increase their spiritual productivity without necessarily adding new formal acts of worship to their routines.`,
    metaDescription: "Guide to frequently neglected spiritual rewards in daily speech, physical habits, and social interactions, supported by hadith evidence."
  },
  {
    slug: "modern-arabic-made-easy",
    description: `Learning Arabic presents a challenge that deters many aspiring students, but Modern Arabic Made Easy approaches the task with a pedagogical methodology designed to reduce difficulty and build competence progressively. The book recognizes that the traditional approach to Arabic instruction—which often begins with dense grammar rules before introducing practical vocabulary—can overwhelm beginners and lead to early abandonment of study. Instead, this text adopts a functional approach that prioritizes communication skills while gradually introducing grammatical structures in context.

The early lessons focus on building a core vocabulary of high-frequency words and phrases that students will encounter in real-world Arabic usage. Common greetings, everyday expressions, numbers, days of the week, and basic question words form the foundation upon which subsequent lessons build. Each new vocabulary set is reinforced through exercises that require active recall and contextual usage, moving students beyond passive recognition to genuine linguistic competence.

Grammar is introduced incrementally, with each concept tied to specific communicative needs. Rather than presenting noun declensions and verb conjugations as abstract tables to be memorized, the book shows how these grammatical elements function within the sentences and conversations that students are learning to construct. This contextual approach helps students understand not just the form of grammatical rules but their purpose, making the material more memorable and practically useful.

The book places particular emphasis on the differences between Modern Standard Arabic—the formal written language used in media, literature, and official communication—and the colloquial dialects spoken in daily life. Students gain awareness of when each register is appropriate and how the same concepts may be expressed differently across registers. This practical awareness is essential for anyone planning to travel, work, or study in an Arabic-speaking environment.

Exercises throughout each chapter include translation, fill-in-the-blank, sentence construction, and short reading passages that test comprehension and application. An answer key or solutions section allows self-learners to verify their work. For students preparing for formal Arabic courses, for travelers needing functional communication skills, or for independent learners pursuing Arabic as a personal goal, this book provides a structured and manageable pathway into the language.`,
    metaDescription: "Progressive Arabic learning guide using functional methodology, contextual grammar, and practical exercises for self-study and communication."
  },
  {
    slug: "mohr-e-nabowat-saww-calligraphy",
    description: `The seal of Prophethood—Mohr-e-Nabowat—holds a profound significance in Islamic tradition as the physical mark given to Prophet Muhammad (peace be upon him) by Allah as one of the signs of his prophetic mission. This calligraphic art piece renders the sacred words of the seal in an artistic format that serves both as a decorative element and as a reminder of the Prophet's elevated status. The art of Islamic calligraphy transforms written text into visual beauty, and this piece exemplifies the tradition at its finest.

The calligraphic rendering follows classical Arabic script traditions, with the letterforms shaped according to the proportional rules established by master calligraphers over centuries of artistic development. The strokes exhibit the characteristic variations in thickness that distinguish hand-crafted calligraphy from printed text—thick downward presses where the reed pen bears full weight, delicate hairline extensions where the pen lifts gracefully across the page. These qualities give the work a vitality and warmth that mechanical reproduction cannot replicate.

The design balances the sacred text with decorative elements drawn from the broader Islamic artistic tradition. Geometric patterns, floral motifs, or border work may frame the calligraphy, creating a composition that pleases the eye while directing attention to the central inscription. The color palette is chosen to complement both the calligraphic linework and the environments where the piece is likely to be displayed—homes, offices, educational institutions, and mosques.

The physical execution of the piece reflects careful craftsmanship. The choice of medium—whether paper, canvas, or another surface—affects the texture and presence of the finished work. The ink or paint used for the calligraphy is selected for its opacity, durability, and visual richness. For collectors of Islamic art, the piece represents a convergence of religious significance and artistic skill. For those seeking meaningful decorative items for their homes or gifts for loved ones, the calligraphy of Mohr-e-Nabowat carries a spiritual weight that distinguishes it from ordinary wall art, serving as a constant visual reminder of the Prophet and his blessed mission.`,
    metaDescription: "Calligraphic art piece of the Seal of Prophethood featuring classical Arabic script, traditional decorative elements, and handcrafted artistic execution."
  },
  {
    slug: "more-than-1000-sunnah-every-day-night",
    description: `The Sunnah of Prophet Muhammad (peace be upon him) encompasses every aspect of human life, and many Muslims are unaware of the remarkable number of Prophetic practices that can be incorporated into their daily routines. This book delivers on the promise of its title by cataloging more than one thousand specific Sunnah acts that span the complete cycle of a Muslim's day and night—from the moment of waking to the moment of sleeping, and even the acts recommended during the hours of darkness.

The book is organized chronologically, following the natural progression of a day. The opening chapters cover the Sunnahs of waking up: the prescribed supplications, the use of the miswak, washing the hands and face, and the recommended attitude of gratitude upon awakening. The morning routine continues with supplications for entering and leaving the home, using the bathroom, dressing, and beginning the day's work. Each Sunnah is numbered and referenced to its source hadith, allowing readers to verify the narration's authenticity and understand its full context.

Mealtime Sunnahs receive detailed treatment—beginning eating in the name of Allah, eating with the right hand, eating from the portion nearest to oneself, not criticizing food, sitting while eating, and the specific etiquette of drinking water. The book notes that these acts, while seemingly small, carry spiritual significance and divine reward when performed with the intention of following the Prophet's example.

The sections covering the five daily prayers include not only the well-known Sunnahs of the prayer itself but also the recommended acts surrounding prayer: the journey to the mosque, waiting for the congregational prayer, the supplications after prayer, and the recommended dhikr between prayer times. Work-related Sunnahs, social interaction guidelines, and the etiquette of visiting and hosting are all cataloged within the daily framework. The evening routine receives equal attention, with supplications before sleeping, the recommended sleeping posture, and the practice of reciting specific verses and surahs for protection during the night. With more than a thousand individual entries, this book transforms the reader's understanding of what it means to follow the Sunnah in daily life.`,
    metaDescription: "Catalog of over 1,000 daily Sunnah acts from waking to sleeping, each referenced to source hadith for integrating Prophetic practice."
  },
  {
    slug: "more-than-1000-sunnah-every-day-night-ps",
    description: `This special edition of the popular Sunnah compilation brings the same comprehensive content—over one thousand Prophetic practices organized throughout the daily cycle—to readers in a distinct publishing format. The "PS" designation marks this as a particular print variant that may differ from the standard edition in paper quality, binding style, typography, or supplementary materials, while maintaining the same scholarly content that has made the original work a valued resource for Muslims seeking to follow the Prophet's example more closely in their everyday lives.

The content follows the established chronological framework, beginning with the Sunnahs associated with waking and the early morning routine, progressing through the various activities and interactions of the day, and concluding with the evening and nighttime recommended acts. The numbering system for each Sunnah facilitates tracking and memorization, while the hadith references accompanying each entry provide the evidentiary foundation that distinguishes this work from collections of undocumented practices.

What distinguishes this edition's approach is its emphasis on practical implementation. Each Sunnah is not merely listed but contextualized with brief explanatory notes that help readers understand why the Prophet recommended a particular practice and how to incorporate it naturally into modern daily life. The notes address common questions: Is this Sunnah confirmed or recommended? Can it be combined with other acts? What if circumstances make it difficult to perform? These practical considerations make the content more actionable for readers who genuinely want to adopt these practices rather than simply read about them.

The book's structure supports both systematic study and casual browsing. A reader can work through the book sequentially, gradually building a Sunnah-rich daily routine over weeks and months, or they can consult specific sections as needed—for instance, reviewing the mealtime Sunnahs before a family gathering or the travel Sunnahs before a journey. For families, the book serves as a resource for parents teaching their children to follow the Sunnah from a young age, with many of the listed practices being simple enough for children to learn and adopt. The edition maintains the academic reliability of the original while enhancing its usability as a practical daily companion.`,
    metaDescription: "Special edition cataloging 1,000+ daily Sunnah acts with implementation notes, hadith references, and a framework for gradual adoption."
  },
  {
    slug: "muhafiz-e-qalb",
    description: `The human heart, in Islamic spiritual terminology, represents far more than a physical organ—it is the seat of faith, the center of moral consciousness, and the battleground where spiritual well-being is either protected or compromised. Muhafiz-e-Qalb, written in Urdu, addresses the critical task of guarding the heart against spiritual corruption while cultivating the qualities that strengthen faith and draw a person closer to Allah. The title itself—"Protector of the Heart"—signals the book's central concern with spiritual self-defense in an environment where the soul faces constant pressure.

The book draws heavily upon the Quranic framework of heart-related guidance. Verses describing the healthy heart—the qalb salim—as well as verses warning against the hardened heart, the diseased heart, and the sealed heart provide the foundational theological understanding. The author explains how each of these conditions develops and what actions and attitudes lead toward or away from spiritual health. The Quranic emphasis on heart-purification as a prerequisite for salvation receives thorough treatment, with reference to the relevant verses and their classical interpretations.

The diseases of the heart receive detailed individual attention in dedicated chapters. Arrogance, envy, jealousy, greed, anger, hatred, ostentation, and attachment to worldly pleasures are each examined as spiritual ailments that progressively damage the heart's capacity for faith. For each disease, the book identifies its root causes, its symptoms, its consequences, and—most importantly—the remedies prescribed by Islamic teaching. These remedies typically combine avoidance of the behaviors that feed the disease with active cultivation of the opposing virtues.

The positive cultivation section is equally thorough. Gratitude, patience, contentment, love for Allah and His Messenger, sincerity, humility, and hope in Allah's mercy are presented as spiritual nutrients that strengthen the heart. Practical strategies for developing these qualities—including specific dhikr, recommended acts of worship, and lifestyle adjustments—are provided throughout. The author integrates insights from classical works on spiritual purification, particularly the writings of scholars like Ibn al-Qayyim and Imam al-Ghazali, while presenting the material in accessible Urdu prose that speaks to contemporary readers facing modern spiritual challenges.`,
    metaDescription: "Urdu spiritual guide on protecting and purifying the heart, addressing envy and arrogance with Quranic remedies and cultivation strategies."
  },
  {
    slug: "muhammad-pbuh-for-the-global-village",
    description: `The message of Prophet Muhammad (peace be upon him) transcends the geographical and temporal boundaries of seventh-century Arabia, carrying relevance and applicability for every human society. Muhammad (PBUH) for the Global Village examines the Prophet's mission and teachings through the lens of their universal implications, demonstrating how the principles he established address the fundamental needs and challenges of human communities regardless of their cultural, political, or technological context.

The book analyzes the Prophet's approach to governance, showing how the principles of justice, consultation, accountability, and the rule of law that he established in the nascent Muslim state of Madinah provide a viable framework for political organization in any era. The Constitution of Madinah, widely regarded as one of the earliest written constitutional documents in history, is examined as a model for pluralistic governance that guaranteed the rights of Muslim and non-Muslim communities alike. The book argues that these principles remain applicable to contemporary debates about governance, minority rights, and social justice.

Inter-community and inter-faith relations receive substantial treatment, with the Prophet's interactions with Jewish tribes, Christian delegations, and polytheist communities serving as case studies for peaceful coexistence and constructive engagement. The book challenges both the Islamophobic narrative that portrays the Prophet as intolerant and the simplistic narrative that ignores the complexities of his diplomatic and military decisions. Each example is presented with historical context, showing how the Prophet's responses were calibrated to specific circumstances while reflecting consistent underlying principles.

The economic teachings of the Prophet are analyzed for their relevance to modern economic challenges. The emphasis on fair trade, workers' rights, the prohibition of exploitative practices, and the encouragement of charity and social welfare are presented as an economic philosophy that addresses systemic inequalities without relying on any particular economic ideology. Environmental stewardship, animal welfare, and public health measures—areas where the Prophet's guidance was remarkably progressive for its time—are also discussed with reference to contemporary concerns. The book makes a compelling case that the Prophet's example offers practical solutions to many of the challenges facing the global village of the twenty-first century.`,
    metaDescription: "Analysis of Prophet Muhammad's universal relevance for governance, interfaith relations, economics, and social justice in the modern world."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({
      where: { slug: item.slug },
      data: { description: item.description, metaDescription: item.metaDescription }
    });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
