const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  // === FROM BATCH1 index 90-102 (13 entries) ===
  {
    slug: "al-lulu-wal-marjan-alaa",
    description: `Al-Lulu Wal-Marjan is a renowned compilation of authentic Ahadith drawn exclusively from the two most authoritative sources in Islamic literature: Sahih al-Bukhari and Sahih Muslim. This particular edition, marked as Alaa (premium) quality, is produced with superior art paper and enhanced printing standards that make reading the Arabic text and its accompanying translation a noticeably refined experience. The book is organized thematically, gathering narrations that appear in both Sahih al-Bukhari and Sahih Muslim under shared headings, which allows readers to quickly access hadith that carry the highest level of authentication in the entire body of Prophetic tradition. Scholars refer to narrations found in both of these collections as "Muttafaqun Alayh" (agreed upon), and these hold a special rank because both Imam al-Bukhari and Imam Muslim independently verified their authenticity through rigorous chains of narration.

The Alaa edition distinguishes itself through its premium paper quality, which resists wear and maintains clarity over extended use, making it suitable for daily reference in homes, masajid, and Islamic educational institutions. The text layout is designed with comfortable spacing between lines and clearly distinguished Arabic script, so that readers who are studying hadith seriously or referencing narrations during lectures can do so without eye strain. Each hadith is presented with its complete chain of narrators, preserving the classical format that students of Islamic sciences are accustomed to. This makes the book valuable not only for general readers seeking authentic Prophetic guidance but also for students enrolled in hadith study circles, scholars preparing khutbah material, and teachers who need a reliable reference for classroom instruction.

Topics covered in this collection span the breadth of Islamic life, including faith and belief, purification and prayer, fasting, charity, pilgrimage, marriage, business transactions, manners, and the hereafter. Because every narration in this volume carries dual authentication, it serves as a trustworthy first reference for anyone who wants to base their understanding of Islamic practice on the most reliably transmitted statements of the Prophet Muhammad. The binding and cover construction of the Alaa edition are built for durability, ensuring the volume withstands frequent handling in study environments.`,
    metaDescription: "Al-Lulu Wal-Marjan Alaa edition features agreed-upon Ahadith from Sahih Bukhari and Muslim printed on premium art paper for scholars and students."
  },
  {
    slug: "al-tohfa-alsunniya-arabic",
    description: `Al-Tohfa Al-Sunniya is a classical Arabic text that occupies a respected position in the curriculum of traditional Islamic seminaries, particularly within the Deobandi scholarly tradition. Written entirely in Arabic, this work is designed to equip students of Islamic theology with a structured and methodical understanding of Sunni creed as it has been transmitted through the earliest generations of Muslim scholars. The text addresses the foundational articles of faith including the oneness of Allah, the attributes of the Creator as understood through the methodology of the pious predecessors, the belief in prophets and messengers, the reality of the Hereafter, and the status of the Companions of the Prophet Muhammad. Each theological point is presented in a concise yet comprehensive format that has made this book a staple in madrasah classrooms for decades.

The language of Al-Tohfa Al-Sunniya reflects the classical Arabic style used in traditional Islamic texts, which means it serves a dual purpose: students not only learn the content of orthodox Sunni theology but also strengthen their command of formal Arabic expression. Instructors typically use this text as a core syllabus book for intermediate-level aqeedah courses, where students read passages aloud, analyze the theological arguments presented, and compare them with deviant views that the author systematically refutes. The book addresses philosophical and theological debates that emerged in earlier centuries of Islamic history, providing reasoned responses grounded in Quranic evidence and authentic hadith.

This edition is printed with careful attention to the accuracy of the Arabic text, ensuring that diacritical marks and grammatical notation are preserved correctly. For students pursuing formal Islamic education, having a personal copy of Al-Tohfa Al-Sunniya is essential for revision, class participation, and building a personal library of core theological references. The compact format makes it convenient to carry between classes, and the sturdy binding ensures it endures the demands of daily academic use in a madrasah setting.`,
    metaDescription: "Al-Tohfa Al-Sunniya is a classical Arabic text on Sunni creed used in traditional madrasahs for intermediate-level theology and aqeedah studies."
  },
  {
    slug: "allah-commands-us-to-make-duaa",
    description: `Allah Commands Us to Make Duaa is a children's Islamic book that focuses on one of the most fundamental and comforting aspects of a Muslim's relationship with the Creator: the act of supplication, or duaa. Written in clear and accessible English, this book teaches young readers that duaa is not merely a ritual but a direct line of communication with Allah, who has explicitly invited His servants to call upon Him at all times and in every situation. The book draws upon Quranic verses and authentic Prophetic traditions to establish the importance and power of making duaa, showing children that Allah loves to hear from them whether they are asking for help, expressing gratitude, seeking forgiveness, or simply talking about their feelings.

The content is structured around relatable scenarios that children encounter in their daily lives: waking up in the morning, before eating meals, when feeling scared or sad, before sleeping at night, when facing difficulties at school, and during times of illness. For each situation, the book provides specific duaa from the Quran and Sunnah along with an explanation of its meaning in simple terms that children can understand. Colorful illustrations complement the text and help young readers visualize the concepts being taught, making the learning experience engaging rather than purely textual.

Parents and Islamic school teachers will find this book particularly useful as a supplementary resource for teaching children how to incorporate duaa into their everyday routines. It serves as a conversation starter for discussions about tawakkul (reliance upon Allah), patience during hardships, and gratitude for blessings. The book also addresses common questions children have about duaa, such as why Allah does not always answer immediately or in the way we expect, providing age-appropriate answers rooted in Islamic teaching. The sturdy binding and quality paper make it suitable for repeated use in classroom settings and for preserving as part of a child's growing Islamic library.`,
    metaDescription: "Allah Commands Us to Make Duaa teaches children about Islamic supplication through Quranic verses, daily situations, and simple explanations with colorful illustrations."
  },
  {
    slug: "allah-forgives-mistakes-and-sins",
    description: `Allah Forgives Mistakes and Sins is an Islamic children's book that addresses one of the most essential concepts in a young Muslim's spiritual education: the vastness of Allah's mercy and His readiness to forgive those who sincerely repent. Written in straightforward English suited for young readers, this book introduces children to the Islamic understanding of tawbah (repentance) by explaining that every human being makes mistakes and commits sins, but what truly matters is turning back to Allah with a sincere heart and a genuine intention not to repeat the wrongdoing. The book uses Quranic ayat and hadith of the Prophet Muhammad to demonstrate that Allah's mercy surpasses His anger and that He is always waiting for His servants to return to Him.

The narrative approach of this book makes complex theological ideas accessible to children by using everyday examples they can relate to. When a child breaks something accidentally, says something hurtful to a sibling, or disobeys a parent, the book shows how these situations connect to the broader Islamic principle of seeking forgiveness. It explains the three conditions of sincere repentance in terms children can grasp: feeling truly sorry for what was done, stopping the wrongdoing, and making a firm decision not to do it again. The book also covers the importance of seeking forgiveness from people who may have been wronged, teaching children that Islamic repentance has both a vertical dimension (between the person and Allah) and a horizontal dimension (between the person and other human beings).

Illustrations throughout the book reinforce the messages and keep young readers engaged. Teachers at Islamic weekend schools and full-time Islamic schools will find this a valuable resource for lessons on Islamic manners, character development, and the names and attributes of Allah, particularly Ar-Rahman and Al-Ghaffar. Parents can read this book aloud at bedtime or use it as a tool for meaningful conversations after their child has made a mistake. The physical production uses durable paper and child-friendly binding to withstand regular use.`,
    metaDescription: "Allah Forgives Mistakes and Sins is a children's book teaching sincere repentance, Allah's mercy, and how to seek forgiveness using Quranic verses and hadith."
  },
  {
    slug: "allah-kay-akhri-nabi-saw",
    description: `Allah Kay Akhri Nabi (SAW) is a Urdu-language book that presents the life, character, and mission of Prophet Muhammad as the final messenger of Allah. Written for a general Urdu-speaking readership, this book covers the major events of the Prophet's life from his birth in Makkah through his childhood, his prophethood, the hardships faced by the early Muslim community, the migration to Madinah, the key battles and treaties, and ultimately his passing. The narrative weaves together authentic historical sources to create a comprehensive yet readable account that brings the Seerah to life for readers who may be encountering these events for the first time or revisiting them with greater depth.

The book places particular emphasis on the role of Prophet Muhammad as the Seal of the Prophets, explaining why his message represents the final and complete guidance from Allah to humanity. It discusses how the Quran was revealed over twenty-three years, how the Prophet implemented its teachings in his personal life and in the society he built, and how his example continues to serve as the benchmark for Muslim conduct in every era. The author addresses the Prophet's interactions with his Companions, his treatment of women, children, the elderly, and non-Muslims, and his approach to leadership, justice, and mercy. Each chapter is written in clear Urdu prose that avoids overly academic language while maintaining factual accuracy and scholarly integrity.

This book serves multiple audiences: families looking to introduce their children to the Seerah in Urdu, individuals performing dawah who need a reliable single-volume reference, and teachers at Urdu-medium Islamic schools who need a textbook for Seerah classes. The chapters are structured with headings and subheadings that make it easy to navigate specific topics. The binding and print quality are designed for comfortable extended reading, making this a permanent addition to any Urdu Islamic library.`,
    metaDescription: "Allah Kay Akhri Nabi (SAW) is a comprehensive Urdu-language Seerah book covering the complete life and mission of Prophet Muhammad for Urdu-speaking readers."
  },
  {
    slug: "allahs-beautiful-gardens",
    description: `Allah's Beautiful Gardens is a vibrantly illustrated Islamic children's book that describes Jannah (Paradise) in a way that is both faithful to Quranic and hadith descriptions and accessible to young imaginations. The book takes children on a guided tour of the gardens that Allah has promised to the righteous, describing the rivers flowing beneath the palaces, the fruits of every kind hanging within easy reach, the garments of silk and the couches adorned with gold and precious stones, and the companionship of the righteous and the angels. Each description is directly referenced to specific Quranic verses or authentic hadith narrations, so parents and teachers can be confident that the imagery presented to children is grounded in authentic Islamic sources rather than cultural embellishment.

Beyond the physical descriptions of Paradise, the book also addresses the spiritual dimensions of Jannah in age-appropriate language. It explains that the greatest reward in Paradise is the pleasure of Allah and the opportunity to see Him, a concept that is introduced gently and reinforced through the Prophet's hadith about the people of Paradise being called to see their Lord. The book discusses who will enter Jannah, connecting the descriptions of its blessings to the good deeds and character traits that earn a person this ultimate reward: being kind to parents, speaking truthfully, helping others, praying on time, and maintaining sincerity in worship.

The illustrations use rich, warm colors to create an inviting visual experience that captures a child's imagination without crossing into unrealistic or exaggerated depictions. Each page features a short passage of text accompanied by the relevant Quranic reference or hadith source, allowing educators to expand on the material during lesson time. This book is well suited for use in Islamic kindergarten and primary school classes, at home during bedtime reading, and as a gift for children on special occasions. The durable cover and quality printing ensure the book can be enjoyed repeatedly by multiple children in a family or classroom setting.`,
    metaDescription: "Allah's Beautiful Gardens is an illustrated children's book describing Jannah through Quranic verses and authentic hadith, teaching kids about Paradise rewards."
  },
  {
    slug: "allama-umaat-sayedina-abdullah-bin-abbas",
    description: `Allama Ummat Sayedina Abdullah Bin Abbas is a biographical work in Urdu dedicated to Abdullah ibn Abbas, one of the most learned Companions of the Prophet Muhammad and the person to whom the Prophet famously prayed, "O Allah, grant him understanding of the religion and teach him interpretation." This prayer was manifestly answered, as Abdullah ibn Abbas grew to become known as "Habr al-Ummah" (the Scholar of the Muslim Nation) and "Al-Bahr" (the Ocean) for the extraordinary depth and breadth of his knowledge. The book traces his life from his early childhood in the household of the Prophet, where he was raised in close proximity to the Messenger of Allah, through his development into one of the foremost authorities on Quranic exegesis, Islamic jurisprudence, and the causes of revelation.

The author presents a detailed account of how Abdullah ibn Abbas acquired his knowledge, emphasizing his tireless pursuit of learning even after the Prophet's passing. He would travel great distances to meet other Companions who had heard hadith directly from the Prophet, sometimes arriving at a Companion's door only to find them asleep, and waiting patiently until they woke so he could record their narrations. The book documents his scholarly methodology, his role as an advisor to the caliphs, his courage in speaking truth to those in power, and his dedication to preserving the pure teachings of Islam during a period of rapid expansion and political change.

The Urdu prose is clear and engaging, making this biography accessible to a wide range of readers from students at Islamic seminaries to general readers interested in the lives of the Sahabah. The book includes discussions of the major fatawa (legal opinions) issued by Abdullah ibn Abbas, his approach to interpreting the Quran, his role in key historical events during the caliphates of Abu Bakr, Umar, Uthman, and Ali, and the legacy he left through his students and his written contributions. This volume is a valuable addition to any Urdu Islamic biography collection and serves as an inspirational resource for students of Islamic knowledge.`,
    metaDescription: "Allama Ummat Sayedina Abdullah Bin Abbas is a detailed Urdu biography of the great Companion and Quranic scholar, known as the Scholar of the Nation."
  },
  {
    slug: "almond-oil-25-ml",
    description: `This 25ml bottle of pure almond oil is a versatile natural product valued in both traditional wellness practices and daily personal care routines. Extracted from high-quality almonds through a careful pressing process, this oil retains the natural nutrients, vitamins, and beneficial fatty acids that make almond oil a staple in households following the Prophetic tradition of using natural remedies. The oil is housed in a compact 25ml container that is ideal for personal use, travel, or keeping in a bag for on-the-go application. The small bottle size makes it convenient to carry during Hajj or Umrah trips, where travelers often seek lightweight personal care items that serve multiple purposes.

Pure almond oil has been used for centuries across the Muslim world as a nourishing treatment for skin and hair. When applied to the skin, it absorbs readily without leaving a heavy greasy residue, providing deep hydration that helps maintain the skin's natural moisture barrier. It is commonly used as a facial moisturizer, a body oil after bathing, a massage oil, and a treatment for dry and rough patches on elbows, knees, and heels. For hair care, a few drops massaged into the scalp and worked through the lengths of the hair can help reduce dryness, add natural shine, and support overall hair health. The light texture makes it suitable for use in warmer climates where heavier oils may feel uncomfortable.

This almond oil is packaged in a sturdy bottle with a secure cap that prevents leakage, an important feature for those who carry it in travel bags or purses. The 25ml quantity provides enough oil for several weeks of regular use depending on the application method. Whether used as part of a daily skincare routine, a hair conditioning treatment, or a natural massage oil, this compact bottle of almond oil offers a practical and multipurpose solution rooted in the tradition of using wholesome, natural products for personal wellbeing.`,
    metaDescription: "Pure almond oil in a compact 25ml bottle, ideal for skin hydration, hair care, and travel use during Hajj or Umrah trips as a multipurpose natural product."
  },
  {
    slug: "almond-oil-50-ml",
    description: `This 50ml bottle of pure almond oil provides a generous supply of one of the most versatile and widely used natural oils in traditional personal care. Almond oil has been prized across cultures and centuries for its nourishing properties, and its use is well documented in the Prophetic medicine tradition where natural, wholesome products are recommended for maintaining health and wellbeing. The larger 50ml size is suited for regular daily use at home, offering enough quantity for consistent application over an extended period without the need for frequent repurchase. The oil is extracted from premium almonds using methods that preserve its natural composition of vitamin E, essential fatty acids, and antioxidants.

In daily skincare, almond oil serves as an effective moisturizer for the face and body. Its lightweight consistency allows it to penetrate the skin quickly, delivering hydration to dry areas without clogging pores. Many users apply it after a shower to lock in moisture, use it as a gentle makeup remover, or dab it on cuticles and nail beds to prevent cracking and promote healthy nail growth. For hair, the oil can be warmed slightly and applied as a deep conditioning treatment before washing, or a small amount can be smoothed through the ends of the hair daily to reduce frizz and add a natural luster. The oil is also commonly used in infant massage, as its gentle formulation is considered safe and beneficial for delicate baby skin.

The 50ml bottle is designed with a practical closure mechanism that controls dispensing and minimizes spillage. The transparent or semi-transparent packaging allows users to monitor the remaining quantity. This oil is free from artificial additives, fragrances, and preservatives, making it suitable for individuals with sensitive skin who prefer pure, unprocessed personal care products. It serves as an essential household item for families who prioritize natural remedies and traditional wellness practices.`,
    metaDescription: "50ml bottle of pure almond oil for daily skin and hair care, featuring natural vitamin E and fatty acids, suitable for moisturizing and massage routines."
  },
  {
    slug: "amal-ki-qabooliyat",
    description: `Amal Ki Qabooliyat is a Urdu-language Islamic book that addresses a question of profound importance to every practicing Muslim: what makes our deeds acceptable to Allah? While many Muslims focus on the quantity and outward form of their worship, this book turns attention to the inner conditions and qualities that determine whether an act of worship, charity, or any good deed is actually accepted by the Creator. Drawing upon Quranic verses, hadith of the Prophet Muhammad, and the insights of classical Islamic scholars, the author explores the concept of qabooliyat (acceptance) in depth, explaining that a deed performed without sincerity, without adherence to the Sunnah, or without proper intention may appear righteous outwardly but carries no weight in the sight of Allah.

The book is organized into clearly structured chapters, each focusing on a specific condition for the acceptance of deeds. The first and most fundamental condition discussed is ikhlas (sincerity), the requirement that every act of worship must be performed solely for the pleasure of Allah and not for recognition from people, social status, or worldly gain. Subsequent chapters address the importance of following the Sunnah of the Prophet Muhammad in the manner of worship, the significance of consuming only halal earnings because acts of worship funded by haram income are rejected, the role of consistency in good deeds, the impact of arrogance and showmanship on the validity of worship, and the necessity of avoiding innovations (bidah) in religious practice.

The author supports each point with relevant evidence from the Quran and authentic hadith, often including stories from the lives of the Salaf (pious predecessors) that illustrate how the early Muslims were deeply conscious of whether their deeds were being accepted. The Urdu language used throughout is accessible to educated general readers while maintaining the scholarly rigor expected of Islamic literature. This book is particularly relevant for individuals who feel that despite performing many acts of worship, they are not experiencing spiritual growth, as it helps identify the internal shortcomings that may be undermining the value of their efforts.`,
    metaDescription: "Amal Ki Qabooliyat is a Urdu book explaining the conditions for acceptance of Islamic deeds, covering sincerity, Sunnah compliance, and halal earnings."
  },
  {
    slug: "amar-bil-maroof-wa-nahi-anil-munqir-ka-bayan",
    description: `Amar Bil Maroof Wa Nahi Anil Munkir Ka Bayan is a comprehensive Urdu-language work that examines one of the fundamental obligations in Islam: the duty to enjoin good and forbid evil. This principle, derived directly from the Quran and the Sunnah, is not merely a collective recommendation but an individual responsibility that applies to every Muslim according to their capacity and knowledge. The book provides a thorough explanation of the evidences for this obligation from the primary sources of Islam, including detailed analysis of relevant Quranic verses and hadith narrations, and explores how the early Muslim community understood and implemented this duty in practice.

The author delves into the various dimensions of amar bil maroof wa nahi anil munkir, addressing common questions and misconceptions that arise in contemporary Muslim societies. The book discusses the conditions under which this obligation applies, the levels of implementation ranging from changing evil with one's hand, to speaking against it with one's tongue, to at minimum hating it in one's heart, as outlined in the famous hadith of the Prophet Muhammad. It covers the etiquettes and wisdom required when advising others, the importance of knowledge before action so that one does not forbid something that is actually permissible, and the dangers of overstepping boundaries or using harshness that drives people further away from the deen.

Practical scenarios are discussed throughout the book, making the theoretical principles applicable to real-life situations. The author addresses issues such as how to advise family members, how to respond when witnessing wrongdoing in public spaces, how to balance this duty with maintaining good relationships, and what to do when the person being advised reacts negatively. The Urdu prose is structured and methodical, with clear chapter headings that allow readers to navigate to specific topics of interest. Islamic scholars, teachers, and community leaders will find this book a valuable reference for preparing sermons, counseling sessions, and educational material on this critical aspect of Islamic practice.`,
    metaDescription: "Amar Bil Maroof Wa Nahi Anil Munkir Ka Bayan is a Urdu book on the Islamic duty to enjoin good and forbid evil with Quranic and hadith evidence."
  },
  {
    slug: "ammaar-in-makkah",
    description: `Ammar in Makkah is a children's story book from the popular Islamic children's literature series that narrates historical events from early Islamic history through the perspective of young characters. This particular installment focuses on the experience of Muslims living in Makkah during the early years of Islam, a period marked by intense persecution, social boycott, and the testing of the believers' faith. The story introduces young readers to the harsh conditions that the first Muslims endured for the sake of their belief in one Allah and the message of Prophet Muhammad, making these historical realities accessible and understandable to children through age-appropriate storytelling.

The narrative follows the daily life of a young Muslim in Makkah, showing how the early believers maintained their prayers in secret, supported one another during times of hardship, and found strength in their faith despite facing opposition from the Quraysh. The book introduces children to important historical figures and events from the Makkan period, including the persecution of Bilal, the boycott of Banu Hashim in Shi'b Abi Talib, the migration to Abyssinia, and the eventual victory of the Muslims. Each event is presented in a way that emphasizes the moral lessons and spiritual values that children can apply to their own lives, such as patience during difficulties, trust in Allah's plan, the importance of standing up for what is right, and the value of community solidarity.

The book features illustrations that bring the story to life while maintaining sensitivity to Islamic guidelines regarding visual representation. The language is simple enough for independent reading by children in the middle primary grades, while also being suitable for reading aloud to younger children. Islamic school teachers can use this book as a supplementary resource for Seerah and Islamic history lessons, as it provides an engaging narrative approach to material that might otherwise feel dry or overwhelming in a textbook format. The physical production uses quality paper and sturdy binding suitable for classroom and library use.`,
    metaDescription: "Ammar in Makkah is a children's story book depicting the struggles of early Muslims in Makkah through engaging narrative and illustrations for young readers."
  },
  {
    slug: "amr-bin-al-aas-ra-the-conqueror-of-egypt",
    description: `Amr Bin Al-Aas (R.A) - The Conqueror of Egypt is a biographical work that chronicles the remarkable life of one of the most strategically gifted and politically astute Companions of the Prophet Muhammad. Amr ibn al-Aas was a latecomer to Islam who initially opposed the Prophet and the Muslim community, but after his conversion he went on to become one of the most effective military commanders and administrators in Islamic history. This book traces his journey from his early life in the Quraysh tribe of Makkah, through his initial hostility toward Islam, his eventual acceptance of the faith, and his subsequent contributions to the expansion and governance of the Muslim state.

The central focus of this biography is Amr ibn al-Aas's legendary military campaign to conquer Egypt, one of the most consequential events in early Islamic history. The book provides a detailed account of the strategic decisions, military engagements, and diplomatic negotiations that led to the successful incorporation of Egypt into the Islamic caliphate. Readers will learn about Amr's famous letter exchange with the Byzantine governor Muqawqis, the founding of the city of Fustat which later developed into modern Cairo, and his innovative approaches to governance that won the loyalty of the Egyptian population. The biography also covers his earlier role in the conquest of Palestine and his complex relationship with the caliphs, particularly his interactions with Umar ibn al-Khattab, who appointed him governor of Egypt but maintained close oversight of his administration.

The book does not shy away from the controversies surrounding Amr ibn al-Aas's career, including his role during the fitna (civil strife) that followed the assassination of Uthman ibn Affan and his involvement in the Battle of Siffin. These events are presented with scholarly objectivity, allowing readers to form a balanced understanding of this multifaceted historical figure. The biography draws upon classical Arabic sources including the works of Ibn Kathir, Al-Waqidi, and Ibn Hisham, presenting the material in a narrative style that is engaging for general readers while maintaining historical accuracy. This volume is an important addition to the library of anyone interested in the military, political, and administrative history of early Islam and the lives of the Companions who shaped the course of Muslim civilization.`,
    metaDescription: "Biography of Amr bin al-Aas (R.A), the Companion who conquered Egypt, covering his military campaigns, governance, and role in early Islamic history."
  },
  // === FROM BATCH2 index 0-6 (7 entries) ===
  {
    slug: "an-easy-guide-to-hajj-umrah-ziyaarah-pocket-size",
    description: `An Easy Guide to Hajj, Umrah and Ziyaarah in pocket size format is a compact yet comprehensive reference manual designed to be carried by pilgrims throughout their journey to the holy sites of Islam. The small form factor of this book is one of its most significant practical advantages, as pilgrims performing Hajj or Umrah need a guide that fits easily into a pocket, waist bag, or small backpack without adding noticeable weight or bulk. Every stage of the pilgrimage is covered in a clear, step-by-step format that allows pilgrims to follow along in real time as they perform each rite, from entering the state of ihram and reciting the talbiyah to performing tawaf, saee, standing at Arafat, pelting the jamarat, and the final farewell tawaf.

The guide covers all three types of pilgrimage: Hajj al-Tamattu, Hajj al-Qiran, and Hajj al-Ifrad, explaining the specific requirements and sequences for each. For Umrah, the book provides a straightforward walkthrough of the complete set of rituals from ihram to the final haircut or shaving. A dedicated section on Ziyaarah (visiting the Prophet's Mosque in Madinah) includes guidance on the etiquettes of visiting Masjid al-Nabawi, performing prayers in the Rawdah, and sending salutations upon the Prophet Muhammad at his blessed grave. Duas for each stage of the pilgrimage are provided in Arabic text along with transliteration and English translation, making it accessible for pilgrims who may not be fluent in Arabic.

The pocket-size edition includes practical information that goes beyond the purely ritual aspects, such as tips for navigating the massive crowds at the holy sites, health and hygiene advice for the pilgrimage environment, guidance on what to pack, and reminders about common mistakes that pilgrims make. Maps and diagrams of the Masjid al-Haram and the Masjid al-Nabawi help pilgrims orient themselves in these vast and often confusing spaces. The durable cover and compact binding are specifically designed to withstand the physical demands of the pilgrimage, including heat, humidity, frequent handling, and being carried in crowded conditions. This guide has earned a reputation as one of the most practical and user-friendly Hajj and Umrah manuals available in English, trusted by pilgrims, group leaders, and Islamic scholars alike.`,
    metaDescription: "Pocket-size English guide to Hajj, Umrah and Ziyaarah with step-by-step rituals, duas with transliteration, maps, and practical pilgrim tips."
  },
  {
    slug: "an-inspiration-to-the-world",
    description: `An Inspiration to the World is an Islamic book that presents the life and character of Prophet Muhammad as a source of guidance not only for Muslims but for all of humanity. The book is structured around key themes and episodes from the Prophet's life that demonstrate his qualities of mercy, justice, wisdom, patience, leadership, and compassion in ways that transcend religious boundaries. Each chapter focuses on a specific aspect of his character or a particular event that illustrates his approach to dealing with people, challenges, and crises, drawing lessons that remain profoundly relevant to contemporary readers regardless of their cultural or religious background.

The book explores how Prophet Muhammad transformed a society riddled with tribal warfare, exploitation of the weak, and moral decay into a community built on principles of equality, social justice, and personal accountability. It details his treatment of women, children, the elderly, orphans, the poor, prisoners of war, and people of other faiths, providing documented examples that challenge common misconceptions about his character. The author presents these accounts using primary Islamic sources while framing the discussion in a way that speaks to universal human values and concerns. Topics include the Prophet's approach to conflict resolution, his establishment of a constitutional framework for a multi-faith society in Madinah, his environmental ethics, his emphasis on education and knowledge, and his personal habits of simplicity and moderation.

The writing style is engaging and accessible, avoiding both academic dryness and devotional exaggeration. The book strikes a balance between presenting the Prophet as a historical figure whose actions can be studied and verified and as a spiritual guide whose example continues to inspire millions around the world. It includes references to the original sources for readers who wish to verify the accounts or explore them in greater depth. This book is well suited for dawah purposes, interfaith dialogue, educational institutions, and anyone seeking an authentic and balanced introduction to the life of the man who has been described as the most influential person in history.`,
    metaDescription: "An Inspiration to the World presents Prophet Muhammad's life and character through universal themes of justice, mercy, and leadership for all readers."
  },
  {
    slug: "an-introduction-of-science-of-hadith",
    description: `An Introduction to the Science of Hadith provides a foundational understanding of the systematic methodology that Muslim scholars developed over fourteen centuries to preserve, authenticate, and classify the sayings and actions of Prophet Muhammad. This science, known as Ulum al-Hadith or Mustalah al-Hadith, represents one of the most rigorous documentation and verification systems ever created for any body of literature in human history. The book introduces readers to the key concepts, terminology, and principles that underpin this discipline, making it accessible to students who are beginning their study of Islamic sciences as well as general readers who want to understand how the hadith literature was compiled and safeguarded.

The text covers the essential classifications of hadith, starting with the hierarchy of authenticity: sahih (authentic), hasan (good), and daif (weak), and explaining the precise criteria that scholars use to place each narration in its appropriate category. Readers learn about the conditions required for a hadith to be classified as sahih, including the unbroken chain of narrators (ittisal al-sanad), the integrity and accuracy of each narrator (adalah and dabt), and the absence of hidden defects in the narration (illah) or contradiction with more reliable narrations (shudhudh). The book also explains the various types of weak hadith and the degree to which each type may or may not be used as evidence.

Additional topics covered include the classification of narrators and their reliability ratings, the methodology of hadith criticism (jarh wa taidil), the different types of hadith collections and their organizational principles, the science of determining the causes of disagreement between narrators, and the rules governing the application of hadith evidence in Islamic law. The book provides examples from the major hadith collections including Sahih al-Bukhari, Sahih Muslim, Sunan Abu Dawud, Jami al-Tirmidhi, Sunan al-Nasai, and Sunan Ibn Majah to illustrate the practical application of the principles being discussed. This volume serves as an essential prerequisite for any student intending to pursue advanced study in hadith, Islamic jurisprudence, or Quranic exegesis, all of which rely heavily on properly authenticated hadith evidence.`,
    metaDescription: "An Introduction to the Science of Hadith covers hadith authentication methodology, narrator classification, and the principles of Ulum al-Hadith for students."
  },
  {
    slug: "an-nawawi-40-hadith-prophets-traditions-pocket-size",
    description: `An-Nawawi 40 Hadith: Prophet's Traditions in pocket size is a compact edition of the most widely studied collection of hadith in the Muslim world. Compiled by Imam Yahya ibn Sharaf al-Nawawi in the seventh century of Islam, this selection of forty-two hadith (commonly referred to as the "Forty Hadith of Nawawi") has been described by scholars as representing half of the entire religion, because these narrations collectively encompass the core principles of Islamic faith, worship, ethics, and social conduct. The pocket-size format makes this essential collection conveniently portable, allowing students, teachers, and general readers to carry it for daily revision, memorization practice, or quick reference.

Each hadith in this collection is presented with the complete chain of narrators leading back to the Prophet Muhammad, followed by the Arabic text of the narration and its English translation. The commentary accompanying each hadith explains unfamiliar terms, provides context for the narration, highlights the key lessons derived from it, and connects it to related Quranic verses and other hadith. The selection covers a comprehensive range of Islamic teachings, beginning with the famous hadith about intentions (actions are judged by intentions), followed by hadith on the pillars of Islam and Iman, the definition of ihsan, the halal and haram, the rights of Allah and the rights of His servants, and the signs of the Day of Judgment.

This pocket edition is particularly useful for students enrolled in Islamic studies programs who are required to memorize these hadith as part of their curriculum. The small size allows it to be carried in a pocket or bag for review during commutes, breaks, or between classes. It is also valuable for new Muslims who want a concise yet comprehensive introduction to the most important teachings of the Prophet, for Friday khateeb who need a quick reference for sermon preparation, and for parents who want to teach their children the foundational hadith of Islam. The durable cover and compact binding are designed for frequent handling and travel use.`,
    metaDescription: "Pocket-size edition of Imam Nawawi's famous 40 hadith collection with Arabic text, English translation, and commentary on essential Islamic teachings."
  },
  {
    slug: "anbiya-ki-duain",
    description: `Anbiya Ki Duain is a Urdu-language book that compiles the supplications made by the Prophets of Allah as recorded in the Quran and authentic hadith literature. The book presents each dua in its original Arabic form along with Urdu translation and transliteration, followed by a detailed discussion of the context in which the dua was made, the circumstances that led the Prophet to make this particular supplication, and the lessons and guidance that contemporary readers can derive from studying the prayers of Allah's chosen messengers. This collection covers duain from numerous prophets including Adam, Nuh, Ibrahim, Musa, Isa, Dawud, Sulaiman, Ayyub, Yunus, Zakariyya, Yahya, and Prophet Muhammad.

The book is organized prophet by prophet, allowing readers to develop a comprehensive understanding of each Prophet's relationship with Allah through their supplications. Each chapter begins with a brief introduction to the Prophet and the historical context of his mission, followed by the relevant Quranic verses and hadith narrations containing his duain. The author then provides a detailed commentary that explains the linguistic nuances of the Arabic text, the deeper spiritual meanings embedded in each prayer, and how the prayer reflects the Prophet's character, priorities, and trust in Allah. For instance, the dua of Prophet Ayyub during his prolonged illness reveals his extraordinary patience, the dua of Prophet Nuh after centuries of dawah demonstrates his unwavering commitment, and the dua of Prophet Musa when facing Pharaoh shows his reliance on Allah in moments of extreme danger.

Beyond mere compilation, the book offers practical guidance on how readers can incorporate these prophetic supplications into their own daily prayers. The author identifies specific duain that are relevant to common human experiences such as seeking knowledge, asking for protection from enemies, requesting forgiveness for sins, praying for righteous offspring, and asking for stability in faith. The Urdu prose is scholarly yet accessible, making the book suitable for readers at various levels of Islamic education. This volume serves as both a devotional resource for personal spiritual growth and an academic reference for students of tafseer and Islamic studies who want to understand how the Quran portrays the Prophets through their prayers.`,
    metaDescription: "Anbiya Ki Duain is a Urdu compilation of Prophetic supplications from the Quran with Arabic text, Urdu translation, context, and scholarly commentary."
  },
  {
    slug: "angel-jibraeel-returns-again",
    description: `Angel Jibra'eel Returns Again is a children's Islamic story book that brings to life one of the most significant events in the life of Prophet Muhammad: the visits of the Angel Jibraeel (Gabriel) to teach the Muslims about their faith. This story is rooted in the famous hadith known as the Hadith of Jibraeel, in which the angel appeared before the Prophet and his Companions in human form and asked fundamental questions about Islam, Iman, and Ihsan. The book adapts this profound theological narration into a format that children can understand and engage with, using storytelling techniques that capture their imagination while conveying accurate Islamic teachings.

The book narrates the dramatic encounter in a way that helps children visualize the scene: the mysterious stranger entering the gathering of the Companions, sitting close to the Prophet, asking his three questions, and then departing after receiving comprehensive answers. Through this narrative framework, the book introduces children to the five pillars of Islam (shahadah, salah, zakat, sawm, and Hajj), the six articles of faith (belief in Allah, His angels, His books, His messengers, the Day of Judgment, and divine decree), and the concept of ihsan (worshipping Allah as if you see Him, and knowing that He sees you). Each pillar and article is explained in simple language with examples that children can relate to their own experience.

The story also encourages children to think about important questions: What does it mean to be a Muslim? What should a Muslim believe? How should a Muslim worship? These are the very questions that the angel asked, and the book uses them as starting points for discussions that parents and teachers can continue with children long after the book is closed. The illustrations complement the narrative by depicting the gathering of the Companions and the atmosphere of the scene while maintaining respect for Islamic guidelines on visual representation. This book is well suited for Islamic school libraries, weekend school classes, and home reading, providing children with both an engaging story and foundational knowledge about the core concepts of their faith.`,
    metaDescription: "Angel Jibraeel Returns Again is a children's story book based on the Hadith of Jibraeel, teaching Islam, Iman, and Ihsan through engaging narrative."
  },
  {
    slug: "anokahy-mehmaan-new",
    description: `Anokahy Mehmaan (New Edition) is a children's Islamic story book that tells an engaging tale about hospitality, kindness, and the values that Islam teaches regarding the treatment of guests. The title, which translates to "A Unique Guest," suggests a story centered around an unexpected visitor and the lessons that unfold from this encounter. This new edition features refreshed content and improved production quality, making it an attractive addition to any child's Islamic book collection. The story is written in a style that captures children's attention with relatable characters, a clear narrative arc, and a meaningful moral conclusion that reinforces Islamic teachings.

Islamic stories for children play a crucial role in shaping their moral character and helping them understand how Islamic values apply in everyday situations. This book uses the framework of an entertaining story to teach children about the importance of honoring guests (karam al-dayf), a concept deeply rooted in the Prophetic tradition. The Prophet Muhammad emphasized that honoring guests is a duty and a sign of genuine faith, and this story brings that teaching to life through characters and situations that children can identify with. The narrative shows how the characters in the story respond to the arrival of a guest, the challenges they face in making the guest feel welcome, and the rewards that come from practicing genuine hospitality.

The book features colorful illustrations that enhance the storytelling experience and help young readers visualize the characters and settings. The language used is appropriate for children in the early to middle primary grades, making it suitable for both independent reading and read-aloud sessions with parents or teachers. Teachers at Islamic schools can use this book as a supplement to lessons on Islamic manners and akhlaq (character), as it provides a narrative context for discussing broader ethical principles. The new edition's improved printing quality, with sharper illustrations and more durable binding, ensures that this book can be enjoyed by multiple children over many years of use in homes, classrooms, and school libraries.`,
    metaDescription: "Anokahy Mehmaan new edition is a children's Islamic story book teaching hospitality and kindness through an engaging tale about welcoming a special guest."
  },
];

async function main() {
  let count = 0;
  for (const item of updates) {
    try {
      const descWords = item.description.split(/\s+/).length;
      const metaLen = item.metaDescription.length;
      console.log(`Processing: ${item.slug} | Desc words: ${descWords} | Meta chars: ${metaLen}`);
      if (descWords < 250) {
        console.log(`  WARNING: Description only ${descWords} words (need 250+)`);
      }
      if (metaLen < 130 || metaLen > 155) {
        console.log(`  WARNING: Meta description ${metaLen} chars (need 130-155)`);
      }
      await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      count++;
      console.log(`  OK`);
    } catch (e) {
      console.log('SKIP:', item.slug, e.message.substring(0, 80));
    }
  }
  console.log("Updated:", count, "/", updates.length);
}

main().then(() => prisma.$disconnect());
