const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const updates = [
  {
    slug: "darood-shareef-kay-masail",
    description: `Darood Shareef Kay Masail (Issues/Rulings Related to Darood Shareef) is a comprehensive Urdu book that addresses the Islamic legal and theological questions surrounding the recitation of Salawat/Durood (blessings upon Prophet Muhammad ﷺ) — one of the most beloved and widely practiced devotional acts in the Muslim ummah. While the virtue of sending blessings upon the Prophet (ﷺ) is universally acknowledged and the command to do so is explicitly stated in the Quran, many specific questions arise regarding the proper method, timing, conditions, and limits of this practice — questions that this book addresses with scholarly rigor, clarity, and reliance on authentic sources. The book fills a genuine need in Pakistani Muslim society, where the recitation of Darood Shareef is deeply embedded in daily religious practice but the detailed fiqh rulings governing it are often not well understood.

The book systematically covers the foundational matters — the Quranic verse commanding Salawat (Al-Ahzab 33:56), the hadith promising ten blessings for every Salawat sent, the hadith promising the closest position to the Prophet (ﷺ) on the Day of Judgment for the person who sends the most Salawat, and the hadith stating that a person's prayer is incomplete if they do not send Salawat upon the Prophet (ﷺ) in the tashahhud. From these foundations, the book addresses specific masail (rulings) that scholars have discussed throughout Islamic history: Is it permissible to recite Darood Shareef in a specific count (such as 100 or 1,000 times) with the intention of receiving particular benefits? What is the ruling on reciting Darood Shareef collectively in a group (jama'ah)? Is it permissible to compose new formulations of Salawat beyond those taught by the Prophet (ﷺ) and the companions? What is the ruling on reciting Darood Shareef before and after every action? What about the practice of reciting Darood Shareef and then blowing (dam) on water, food, or people for healing or blessings?

The book addresses each of these questions (and many more) by presenting the evidence from both sides of scholarly discussion — the proponents' evidence and arguments, the opponents' evidence and concerns, and the author's scholarly conclusion based on the strength of the evidence. This balanced, transparent approach allows readers to understand the reasoning behind each ruling rather than simply being told what to do or not do. The book also addresses contemporary issues related to Darood Shareef — including the use of digital counters and apps to track Salawat recitation, the practice of reciting Darood Shareef during religious gatherings (mawlid, urs, and other events), the practice of printing Darood Shareef on decorative items and commercial products, and the question of whether Darood Shareef can be recited in any language or only in Arabic. For Pakistani Muslims who recite Darood Shareef daily — whether the standard Salawat al-Ibrahimiyyah in prayer or additional formulations in their daily worship — this book provides the scholarly foundation that ensures their beloved practice is performed correctly, with proper understanding, and in accordance with the authentic teachings of Islam.`,
    metaDescription: "Darood Shareef Kay Masail — comprehensive Urdu book on Salawat rulings. Counted recitation, collective Darood, fiqh of blessings on Prophet ﷺ. Buy online."
  },
  {
    slug: "daroos-ul-lughatul-arabia-vol-2",
    description: `Daroos Ul Lughatul Arabia (Lessons in the Arabic Language) — Volume 2 is the second installment of a comprehensive, multi-volume Arabic language course written in Urdu for students pursuing advanced Islamic education at madrasahs, darul ulooms, and Islamic universities. This series is widely used across Pakistan's Islamic educational institutions as a core Arabic language curriculum that bridges the gap between basic Arabic literacy and the advanced linguistic proficiency needed to directly access classical Islamic texts — including the Quran, hadith collections, tafsir works, and fiqh manuals — in their original Arabic without reliance on translations. Volume 2 builds upon the foundation laid in Volume 1, advancing the student from elementary grammar and vocabulary to intermediate-level linguistic competency with a strong emphasis on the grammatical structures most frequently encountered in classical Islamic texts.

Volume 2 deepens the grammatical coverage introduced in the first volume — expanding the student's understanding of verb forms (awzan) beyond the basic past, present, and imperative to include the derived forms (Form II through Form X) that carry specific semantic nuances critical for understanding Quranic Arabic and classical prose. The concept of weak verbs (alf al-mu'tall) — verbs containing the letters waw, ya, or hamzah as radicals — receives detailed treatment, as these verbs require special conjugation rules and are extremely common in the Quran and hadith. Noun patterns (masdar, ism fa'il, ism maf'ul, ism zarah, ism makaaan, ism alah) are covered comprehensively, enabling students to recognize and understand the meanings of unfamiliar words by identifying their morphological patterns — a crucial skill for reading classical Arabic texts where vocabulary may not be found in modern dictionaries. Advanced grammar topics introduced in this volume include the various types of verbal sentences (jumla fi'liyyah), the rules governing the subject (fa'il) and object (maf'ul bihi), the different categories of adverbs (zarf), the demonstrative, relative, and interrogative pronouns and particles, and the conditional sentences (jumla shartiyyah) with their complex rules.

The vocabulary in Volume 2 shifts from everyday conversational words toward the specialized lexicon of Islamic scholarship — words related to theology (aqeedah), jurisprudence (fiqh), hadith terminology (mustalah al-hadith), Quranic exegesis (tafsir), and classical Arabic rhetoric (balagha). Each lesson introduces new vocabulary through Arabic reading passages that are specifically written or selected from classical sources to reinforce the grammatical concepts being taught. The reading passages become progressively longer and more complex throughout the volume, gradually building the student's stamina for reading extended Arabic texts — a skill essential for the hadith and tafsir study that follows this course in the madrasah curriculum. Translation exercises (both Arabic-to-Urdu and Urdu-to-Arabic) reinforce vocabulary retention and grammatical understanding. The book's price of Rs.3,300 reflects the comprehensive content and professional production quality that students and institutions expect from this essential educational resource.`,
    metaDescription: "Daroos Ul Lughatul Arabia Vol 2 — advanced Arabic grammar course for Islamic students. Verb forms, weak verbs, classical text vocabulary. Buy online."
  },
  {
    slug: "daroos-ul-lughatul-arabia-vol-3",
    description: `Daroos Ul Lughatul Arabia (Lessons in the Arabic Language) — Volume 3 is the advanced-level installment of this respected multi-volume Arabic language curriculum, representing the culmination of the linguistic preparation that enables students to directly engage with classical Islamic texts in their original Arabic. This volume is designed for students who have completed Volumes 1 and 2 and are preparing to transition into the higher-level Islamic sciences — tafsir, hadith, fiqh, usul al-fiqh, and balagha (rhetoric) — all of which require a sophisticated command of classical Arabic that goes far beyond basic comprehension. The Rs.4,250 price point reflects the advanced content, comprehensive scope, and premium production quality of this essential educational resource.

Volume 3 introduces the student to the most advanced grammatical and rhetorical concepts in Arabic that are essential for understanding classical Islamic texts. The coverage of Arabic rhetoric (balagha) — comprising three sub-sciences: ma'ani (the science of meanings, examining how sentence structure affects meaning), bayan (the science of elucidation, covering metaphor, simile, and metonymy), and badi' (the science of rhetorical embellishments, covering paradox, antithesis, and other literary devices) — represents a significant addition to the student's linguistic toolkit. Mastery of balagha is essential for understanding the inimitable nature (i'jaz) of the Quran, as the miraculous quality of the Quran's language is manifested primarily through its rhetorical excellence rather than its grammatical correctness alone. This volume's balagha section prepares students for the advanced tafsir studies where they will encounter detailed discussions of the Quran's rhetorical features.

The volume also covers advanced grammatical topics that students will encounter frequently in classical texts but are rarely treated comprehensively in introductory courses. These include: the detailed rules for nunation (tanween) and its disappearance in construct states, the complex interactions between demonstrative pronouns and relative clauses, the rules governing conjunctions (awatif) and their effect on grammatical case, the distinction between similar particles (huruf mutashabihat) that change meaning subtly, and the principles of syntactic analysis (i'rab al-jumal al-tawilah) as applied to extended passages from classical texts. The reading passages in Volume 3 are drawn from actual classical Islamic works — including excerpts from Ibn Kathir's Tafsir, Al-Bukhari's Sahih, Al-Ghazali's Ihya Ulum al-Din, and other foundational texts — providing students with authentic exposure to the linguistic style, vocabulary, and grammatical structures they will encounter in their advanced studies. The translation exercises require increasingly sophisticated Urdu that captures not just the literal meaning but the rhetorical nuances of the Arabic original. For Pakistani madrasah students preparing for the advanced stages of their Dars-e-Nizami curriculum, for university students of Arabic and Islamic studies, and for self-learners who aspire to read classical Islamic texts independently, Volume 3 of Daroos Ul Lughatul Arabia provides the advanced linguistic training needed to achieve that goal.`,
    metaDescription: "Daroos Ul Lughatul Arabia Vol 3 — advanced Arabic rhetoric and grammar. Balagha, classical text readings, syntactic analysis. Essential for Islamic scholars. Order online."
  },
  {
    slug: "dawa-e-shafi",
    description: `Dawa-e-Shafi (The Healing Remedy) is a well-known Urdu book on the subject of ruqyah (spiritual healing through Quranic recitation and prophetic supplications) and the Islamic approach to treating ailments that have a spiritual or unseen dimension — including the evil eye (nazar), black magic (sihr/jadoo), possession (mas), and other forms of supernatural affliction that are recognized within Islamic theology as genuine phenomena that can affect human beings. Written by a scholar with expertise in this sensitive area of Islamic knowledge, the book provides a balanced, evidence-based approach that avoids both the extreme of denying the existence of these phenomena (which contradicts clear Quranic and hadith evidence) and the extreme of attributing every illness or misfortune to supernatural causes (which is equally incorrect and can lead to harmful superstitious practices).

The book begins by establishing the Islamic theological framework for understanding spiritual ailments — citing the Quranic verses that explicitly mention magic (such as the story of Prophet Musa's encounter with the sorcerers of Pharaoh in Surah Ta-Ha, and the verse "And they followed [instead] what the devils had recited during the reign of Solomon" in Surah Al-Baqarah 2:102), the evil eye (the Prophet's ﷺ explicit confirmation of its reality and his prescribed remedies), and jinn possession (the Quranic description of jinn and the hadith literature documenting cases of possession during the Prophet's lifetime). This theological foundation is essential because it allows the reader to distinguish between genuine Islamic understanding and the superstitious, culturally-influenced practices that many people mistakenly believe are Islamic. The book emphasizes that while these phenomena are real, Islam provides clear, effective, and divinely sanctioned methods for protection from and treatment of spiritual ailments — methods that do not require the services of self-proclaimed spiritual healers, the payment of large sums of money, or the engagement in practices that violate Islamic law.

The treatment methods prescribed in Dawa-e-Shafi are drawn exclusively from the Quran and authentic Sunnah — including the recitation of Surah Al-Fatiha (known as the "cure" based on the hadith where the Prophet ﷺ instructed a companion to recite it for healing), Surah Al-Baqarah (the Prophet ﷺ said that reciting it drives away evil), Ayat-ul-Kursi (the Prophet ﷺ described it as the greatest verse of the Quran and a protection against evil), the last two verses of Surah Al-Baqarah (which the Prophet ﷺ said are sufficient for whoever recites them at night), Surah Al-Ikhlas, Al-Falaq, and An-Nas (the "protective surahs" that the Prophet ﷺ recommended reciting three times morning and evening), and specific du'as from the hadith for protection from the evil eye, magic, and other afflictions. The book provides practical guidance on how to perform ruqyah — including the conditions for a valid ruqyah (using only Quran and authentic du'a, understanding the meaning of what is recited, reciting with conviction in Allah's power to heal, and using clean water or olive oil as a medium). It also warns against common prohibited practices — including visiting fortune tellers, using amulets containing non-Quranic text, sacrificing animals for other than Allah, and paying so-called "peer" or "baba" for spiritual healing. For Pakistani Muslims who face these challenges and seek genuine Islamic solutions based on the Quran and Sunnah, Dawa-e-Shafi provides a trustworthy, practical, and spiritually sound guide that protects them from both harmful afflictions and harmful superstitions.`,
    metaDescription: "Dawa-e-Shafi — Islamic ruqyah and spiritual healing guide. Evil eye, black magic treatment with Quran and Sunnah. Authentic Urdu reference. Buy online."
  },
  {
    slug: "dawaat-e-deen-kasy-den",
    description: `Dawaat-e-Deen Kasy Den (How to Give Dawah — Invitation to Islam) is a practical, methodologically sound Urdu book that provides comprehensive guidance for Muslims who wish to share the message of Islam with others — whether with non-Muslims who have no knowledge of Islam, with Muslims who are lax in their practice, or with people who hold misconceptions about the religion. The word "dawah" (invitation) is one of the most important concepts in Islam — Allah describes the Muslim community as the best community "enjoining what is right and forbidding what is wrong and believing in Allah" (Aali Imran 3:110), and the Prophet (ﷺ) spent twenty-three years of his life engaged in dawah — making it the primary model for all Muslims who wish to fulfill this communal obligation. This book translates the broad concept of dawah into specific, actionable strategies, techniques, and principles that ordinary Muslims can implement in their daily lives without requiring specialized training or extraordinary circumstances.

The book begins with the theological foundation of dawah — explaining that dawah is not merely a recommended activity but a communal obligation (fard kifayah) that every Muslim must support, that the methodology of dawah is prescribed by Allah and the Prophet (ﷺ) and cannot be changed to suit personal preferences, and that the dawah worker's primary responsibility is to convey the message clearly and beautifully while leaving guidance to Allah alone. The book emphasizes the Quranic principle of dawah methodology: "Invite to the way of your Lord with wisdom and good instruction, and argue with them in a way that is best" (An-Nahl 16:125) — analyzing each component of this verse (wisdom, good instruction, best arguments) and providing practical guidance on how to implement each one in real-world dawah situations.

The book covers the essential knowledge that a dawah worker must possess — the fundamentals of Islamic belief, evidence for the truth of Islam, common misconceptions about Islam and how to address them, and the most effective ways to present Islam to different audiences. It provides specific guidance for different dawah contexts — dawah in the workplace, dawah to family members, dawah to neighbors and colleagues, dawah through social media, dawah through character and example (which the book identifies as the most powerful form of dawah), and dawah through distributing Islamic literature. The book also addresses the dawah worker's character and conduct — emphasizing that the dawah worker's behavior must be consistent with the message they are conveying, that they must possess patience (the Quran describes the Prophet ﷺ as being "patient over what they say"), that they must avoid argumentation and arrogance, and that they must maintain sincerity (ikhlas) by dawah for Allah's sake rather than for personal recognition or competition with other groups. For Pakistani Muslims who wish to fulfill their obligation of sharing Islam — whether with non-Muslim colleagues, secular Muslim friends, family members who have drifted from the faith, or through social media and community engagement — Dawaat-e-Deen Kasy Den provides the knowledge, methodology, and motivation needed to begin this noble work with confidence and wisdom.`,
    metaDescription: "Dawaat-e-Deen Kasy Den — practical Urdu guide on Islamic dawah methodology. Wisdom, character, workplace dawah, social media. Essential for every Muslim. Buy online."
  },
  {
    slug: "dawaat-e-deen-kha-di-jay",
    description: `Dawaat-e-Deen Kha Di Jay (The Dawah that Should Be Given) is a focused Urdu book that addresses the critical question of what content and message should actually be conveyed when a Muslim engages in dawah — the invitation to Islam. While many books on dawah focus on the methodology (how to give dawah), this book focuses on the substance (what to say), recognizing that the most polished delivery is meaningless if the content being delivered is incomplete, inaccurate, or presented in an order that confuses rather than enlightens the listener. The book argues that effective dawah requires a structured, prioritized approach to content — beginning with the most fundamental concepts and building progressively toward the more detailed aspects of Islamic belief and practice, following the pattern established by the Quran itself and the methodology of the Prophet (ﷺ) in calling people to Islam.

The book identifies the essential components of dawah content in order of priority. The first and most fundamental message is tawhid (the oneness of Allah) — the book argues, following the Quranic and Prophetic model, that dawah must begin by establishing who Allah is, what He has created and sustains, why He alone deserves worship, and the evidence for His existence that is observable in the natural world and in human consciousness. This is the message of every prophet in the Quran, who consistently began their dawah by saying: "O my people, worship Allah; you have no deity other than Him" (Al-A'raf 7:59). The second component is the message of the Prophet Muhammad (ﷺ) — establishing his prophethood through evidence, presenting his character as a proof of his truthfulness, and explaining his role as the final messenger who brings the complete and final version of Allah's guidance. The third component is the akhirah (the hereafter) — explaining the Islamic belief in life after death, the Day of Judgment, Paradise and Hell, and why belief in the hereafter is essential for moral behavior and spiritual motivation.

Beyond these three foundational pillars, the book addresses how to present Islamic practices (the five pillars, halal and haram, Islamic social ethics) in a dawah context — emphasizing that practices should be presented after the listener has accepted the theological foundations, not before. The book critiques the common mistake of beginning dawah with practical rulings (such as telling someone they must stop drinking alcohol or start praying) before establishing the belief system that makes these practices meaningful — arguing that this approach often produces resentment and rejection rather than acceptance. The book also addresses how to handle the most common questions and objections that arise during dawah discussions — including questions about the status of women in Islam, the concept of jihad, the punishment for apostasy, the relationship between Islam and other religions, and the perception that Islam is an "Arab religion." Each objection is addressed with evidence, logic, and the balanced, moderate approach characteristic of mainstream Islamic scholarship. For Pakistani Muslims who want their dawah efforts to be effective rather than counterproductive, this book provides the content framework that ensures the right message is delivered in the right order for maximum impact.`,
    metaDescription: "Dawaat-e-Deen Kha Di Jay — Urdu book on dawah content and message priority. Tawhid first, Prophet's proof, hereafter. Structured invitation to Islam. Buy online."
  },
  {
    slug: "dawaat-e-deen-kis-cheez-ki-tarf-di-jay",
    description: `Dawaat-e-Deen Kis Cheez Ki Tarf Di Jay (Toward What Should Dawah Be Directed?) is a thought-provoking Urdu book that addresses the crucial question of identifying the proper targets and priorities of dawah efforts — essentially asking: when a Muslim engages in inviting people to Islam, what exactly are they inviting them toward? This question is more nuanced than it appears at first glance, because different understandings of what constitutes "Islam" lead to very different dawah approaches, and the book argues that getting the target wrong can result in well-intentioned dawah efforts that actually misrepresent Islam or prioritize secondary matters at the expense of essential ones.

The book examines this question through the lens of the Quran and the Prophet's (ﷺ) practice, identifying the core message toward which all Prophetic dawah was directed: the worship of Allah alone without any partners (tawhid) and the rejection of all forms of shirk (associating partners with Allah). The book demonstrates through extensive Quranic evidence that every prophet — from Nuh to Ibrahim to Musa to Isa to Muhammad (ﷺ) — began their dawah by calling their people to tawhid and warning them against shirk. This Prophetic model establishes the priority: dawah should be directed first and foremost toward correct belief in Allah's oneness (aqeedah) and only subsequently toward correct practice (fiqh) and correct character (akhlaq). The book critiques the tendency in some dawah approaches to begin with behavioral modification (telling people to adopt Islamic dress, dietary habits, or prayer routines) before establishing the foundational belief that makes these behaviors meaningful — arguing that this approach, while well-intentioned, can lead to a superficial, legalistic understanding of Islam that lacks the spiritual depth that comes from genuine tawhid.

The book also addresses the question of whether dawah should be directed primarily toward non-Muslims or toward Muslims who are deficient in their practice — presenting evidence that both audiences are legitimate targets but require different approaches and emphases. For non-Muslims, dawah focuses on establishing the foundations (tawhid, prophethood, hereafter) and presenting Islam's intellectual and spiritual appeal. For deficient Muslims, dawah focuses on reminding them of what they already know but may have neglected, motivating them through encouragement and gentle admonition rather than condemnation, and helping them prioritize the most important aspects of their faith over the less important ones. The book identifies several common mistakes in dawah targeting — including the mistake of making dawah primarily about refuting other religions (which can come across as negative and aggressive rather than inviting and compassionate), the mistake of presenting Islam as a cultural identity rather than a universal message, and the mistake of overwhelming new Muslims or interested non-Muslims with too much information too quickly. For Pakistani Muslims engaged in dawah — whether formally or informally — this book provides the conceptual clarity needed to ensure their efforts are directed toward the right targets with the right priorities, maximizing the impact of their invitation to Islam.`,
    metaDescription: "Dawaat-e-Deen Kis Cheez Ki Tarf Di Jay — dawah priorities and targeting in Islam. Tawhid-first approach, non-Muslim vs Muslim dawah. Urdu scholarly guide. Buy online."
  },
  {
    slug: "dawaat-e-deen-kis-waqt-di-jay",
    description: `Dawaat-e-Deen Kis Waqt Di Jay (When Should Dawah Be Given?) is the third installment in a practical Urdu book series on Islamic dawah methodology, this volume focusing specifically on the temporal dimension of dawah — the timing, frequency, circumstances, and situational awareness that determines when dawah is most effective, when it is advisable, and when it may actually be counterproductive. The Prophet Muhammad (ﷺ) himself was acutely aware of the importance of timing in dawah — he chose specific moments for conveying certain messages, adjusted his approach based on the readiness of his audience, and instructed his companions to consider timing in their dawah efforts. This book extracts these Prophetic principles and presents them as a systematic guide for contemporary Muslims seeking to optimize the effectiveness of their dawah while avoiding the common mistakes of poorly timed or inappropriately delivered messages.

The book addresses multiple dimensions of dawah timing. The first dimension is the recipient's readiness — the book argues that effective dawah requires an assessment of where the recipient stands in terms of their awareness of and openness to Islamic knowledge. A person who has never been exposed to Islam requires a different approach and timing than a person who has studied Islam but has questions or objections. A person going through a personal crisis (illness, loss of a loved one, financial difficulty) may be more receptive to spiritual messages but also more emotionally fragile, requiring a gentler approach. A person in a position of authority or influence may require relationship-building before dawah is initiated. The second dimension is the environmental context — the book discusses the appropriateness of giving dawah in various settings (the workplace, social gatherings, family events, online platforms, public spaces) and at various times (during Ramadan when spirituality is elevated, during personal crises when receptivity may be high, during conflicts when emotions may impair rational discussion). The third dimension is the dawah worker's own state — the book emphasizes that the dawah worker must be spiritually prepared (possessing knowledge, sincerity, and good character), emotionally composed (not angry, frustrated, or impatient), and practically ready (having the time, resources, and energy to engage properly) before initiating a dawah conversation.

The book also provides specific guidance on timing within the dawah conversation itself — how to open the discussion, when to present evidence versus when to appeal to emotion and experience, when to push for commitment and when to allow space for reflection, when to address objections and when to defer them for a later discussion, and when to recognize that a conversation has reached its productive limit and should be concluded gracefully. The book addresses the common mistake of "dumping" excessive information on a person in a single conversation — arguing that effective dawah is a process, not an event, and that knowing when to stop is as important as knowing when to start. Special attention is given to the role of social media timing — including the best times to post dawah content, the importance of consistent presence rather than sporadic posting, and the unique challenges of timing online interactions where the recipient's context and emotional state are unknown. For Pakistani Muslims who want their dawah to be effective rather than merely well-intentioned, this book provides the temporal wisdom that ensures the right message is delivered at the right moment for maximum positive impact.`,
    metaDescription: "Dawaat-e-Deen Kis Waqt Di Jay — timing and circumstances for effective Islamic dawah. Recipient readiness, conversation pacing, social media. Urdu guide. Buy online."
  },
  {
    slug: "dawah-according-to-the-quran-and-the-sunnah",
    description: `Dawah According to the Quran and the Sunnah is an English-language comprehensive guide that provides a systematic, evidence-based methodology for inviting people to Islam, drawn exclusively from the primary sources of Islamic guidance — the Holy Quran and the authenticated Sunnah of Prophet Muhammad (ﷺ). In an era where various dawah movements, organizations, and individuals promote different methodologies — some prioritizing intellectual debate, others emphasizing emotional appeal, others focusing on social service, and still others promoting political activism — this book returns to the original sources to establish what the Quran and Sunnah actually prescribe as the correct approach, content, and priorities for Islamic dawah. The book serves as both a corrective to methodologies that deviate from the Prophetic model and a constructive guide for Muslims who wish to fulfill this important obligation in the manner most pleasing to Allah.

The book is structured around the core principles of Quranic and Prophetic dawah methodology. The first principle is wisdom (hikmah) — drawing on the Quranic instruction to "invite with wisdom" (An-Nahl 16:125) to demonstrate that effective dawah requires not only knowledge of Islamic teachings but also understanding of the audience's background, intellectual level, cultural context, and emotional state. The book analyzes specific examples from the Prophet's (ﷺ) life where he applied different approaches to different audiences — the intellectual approach used with the Christian delegation of Najran, the emotional approach used with the bedouin who needed simple guidance, the patient approach used with the slow-to-accept companions, and the firm approach used with those who knowingly rejected the truth after clear evidence. The second principle is good instruction (mau'izah hasanah) — the book explores how effective dawah combines intellectual content with moral and emotional appeal, using stories, parables, and the natural human inclination toward truth and justice to make the message resonate at both the intellectual and emotional levels.

The book provides a complete framework for dawah work — covering the knowledge a dawah worker needs (Aqeedah, evidence for Islam's truth, understanding of other belief systems), the character traits a dawah worker must cultivate (patience, wisdom, humility, sincerity, good character, consistency), the practical skills needed (listening skills, communication skills, critical thinking, answering objections, building relationships), and the ethical boundaries that must not be crossed (using dishonest arguments, misrepresenting others' beliefs, forcing or coercing, being disrespectful or insulting). The book addresses common contemporary dawah challenges — including dawah in secular environments, dawah to people of other faiths, dawah to Muslims who have drifted from the faith, dawah through social media and digital platforms, and dawah in contexts where Islam is misunderstood or actively misrepresented. Each challenge is met with specific Quranic and Prophetic guidance and practical strategies that the reader can implement immediately. For English-speaking Muslims in Pakistan and globally — including students, professionals, dawah workers, and community leaders — this book provides the comprehensive, source-based methodology needed to engage in effective, authentic, and impactful dawah that follows the example of the greatest dawah worker in human history: Prophet Muhammad (ﷺ).`,
    metaDescription: "Dawah According to Quran and Sunnah — comprehensive English dawah methodology. Wisdom, character, practical skills, Quranic framework. Buy online at Bab-ul-Fatah."
  },
  {
    slug: "dawat-e-deen-kon-dy",
    description: `Dawat-e-Deen Kon Dy (Who Should Give Dawah?) is the opening volume of a practical Urdu dawah series that addresses the most fundamental question in Islamic invitation work: who is qualified and obligated to engage in dawah? This question is critically important because the answer determines the scope of responsibility — does dawah apply only to scholars and religious professionals, or does every Muslim share in this obligation? The book examines the Quranic and hadith evidence comprehensively to establish that while dawah has certain specialized forms that require scholarly qualification (such as formal debates, issuing religious verdicts, and delivering khutbahs), the general obligation to share Islam's message and invite others toward good applies to every Muslim — regardless of their level of education, profession, social status, or linguistic ability.

The book presents the Quranic evidence for the universal obligation of dawah — including Allah's description of the believing community as "enjoining what is right and forbidding what is wrong" (Aali Imran 3:104 and 3:110), the command to "cooperate in righteousness and piety" (Al-Ma'idah 5:2), and the statement that "Let there be a group among you who call to good" (Aali Imran 3:104). Each verse is analyzed in its classical tafsir context to determine the scope and nature of the obligation it establishes. The hadith evidence includes the Prophet's (ﷺ) statement "Convey from me, even if it is one verse" — which establishes that even a person who knows only a single Quranic verse is obligated and qualified to share that verse with others who may not know it. The book also analyzes the hadith of the Prophet (ﷺ) regarding the individual responsibility of every Muslim to prevent wrongdoing when they witness it — first by hand (for those with authority), then by tongue (for those without authority but with knowledge), and then by heart (for those who lack both authority and knowledge, the minimum being to disapprove internally) — demonstrating that dawah operates at multiple levels accessible to every Muslim regardless of their circumstances.

The book then addresses the practical implications of this universal obligation for different categories of people. For scholars and religious leaders, the obligation is comprehensive and carries the highest responsibility — they must teach, preach, write, and engage in formal dawah activities. For professionals (doctors, engineers, teachers, businesspeople), dawah is primarily through character and example — demonstrating that Islam produces excellent, ethical, and compassionate individuals whose behavior itself becomes a compelling invitation. For students, dawah means sharing knowledge with classmates, participating in Islamic campus activities, and representing Islam positively through academic excellence and good conduct. For women, dawah within the family (raising children with Islamic values, advising family members, hosting Islamic study circles) is particularly emphasized. For elderly people, dawah through wisdom, life experience, and supplication (du'a) is their primary contribution. The book addresses common excuses people use to avoid dawah — "I don't know enough," "People will judge me for my own shortcomings," "It's not my personality," "I'll do it when I'm more religious" — and refutes each one with evidence and encouragement. For Pakistani Muslims who may have assumed that dawah is someone else's responsibility, this book delivers a powerful wake-up call that every Muslim is a dawah worker, and provides the practical guidance needed to begin fulfilling this obligation in whatever capacity Allah has enabled them.`,
    metaDescription: "Dawat-e-Deen Kon Dy — who is obligated for Islamic dawah? Every Muslim's responsibility. Scholars, professionals, women, students. Urdu guide. Buy online."
  }
];

async function main() {
  let updated = 0, failed = 0;
  for (const item of updates) {
    try {
      const result = await prisma.product.update({
        where: { slug: item.slug },
        data: { description: item.description, metaDescription: item.metaDescription }
      });
      console.log(`✅ Updated: ${result.title} (${result.slug})`);
      updated++;
    } catch (err) {
      console.log(`❌ Failed: ${item.slug} — ${err.message}`);
      failed++;
    }
  }
  console.log(`\nBatch R3J complete: ${updated} updated, ${failed} failed`);
}

main().then(() => prisma.$disconnect());
