const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const updates = [
  {
    slug: "the-islamic-law-of-succession",
    description: `The Islamic Law of Succession is an English-language book that provides a comprehensive and systematic treatment of the Islamic rules governing inheritance (mirath), one of the most technically precise and legally significant areas of Islamic jurisprudence. The Quranic verses on inheritance, found primarily in Surah An-Nisa, establish a detailed framework for the distribution of a deceased person's estate that is remarkable for its specificity and its comprehensive coverage of the various family relationships that create inheritance rights. This book unpacks the legal and mathematical dimensions of this framework, making it accessible to English-speaking readers who need to understand how Islamic inheritance law operates in theory and practice.

The book begins with the foundational principles that underlie the Islamic system of inheritance. The Quranic basis for the inheritance rules is established, showing how the specific shares assigned by Allah to various heirs reflect a balance between the principles of fairness, the preservation of family wealth within the extended family, and the protection of the rights of all legitimate heirs. The distinction between the fixed shares prescribed by the Quran (fara'id), the residual estate that passes to the male agnate relatives (asabah), and the potential for additional bequests through a will (wasiyyah) is explained in detail, with reference to the relevant Quranic verses and the established juristic principles that govern the interaction between these different categories of inheritance.

The core of the book consists of a detailed examination of each category of heir and the specific share that the Quran or the Sunnah assigns to them. The shares of the husband and wife, the shares of the father and mother, the shares of daughters and sons, the shares of grandparents, siblings, and more distant relatives are all discussed with reference to the textual evidences and the juristic reasoning that governs each case. The book pays particular attention to the complex scenarios that arise when multiple categories of heirs compete for shares of the same estate, introducing the concept of awl (proportional reduction) that ensures the estate is distributed fairly even when the total of the prescribed shares exceeds the value of the estate. The mathematical calculations involved in these distributions are explained step by step, with worked examples that demonstrate how the rules are applied in specific cases.

The book addresses several advanced topics that are essential for a complete understanding of Islamic inheritance law. These include the rules governing the inheritance of unborn children, the inheritance rights of children from different marriages, the treatment of debts and liabilities before the distribution of the estate, the rules for the inheritance of the missing person (mafqood), the distinction between the property that forms part of the estate and the property that passes outside the inheritance system, and the interaction between Islamic inheritance rules and the secular legal systems that operate in many Muslim-majority countries.

The practical orientation of the book makes it valuable for a range of readers. For Muslim families who want to ensure their estate plans conform to Islamic requirements, it provides clear guidance on how the distribution should be carried out. For legal professionals who work with Muslim clients on estate matters, it offers a reliable reference on the relevant Islamic legal principles. For students of Islamic jurisprudence, it provides a thorough treatment of an important area of fiqh that is frequently tested in academic examinations. The English language presentation makes this complex area of Islamic law accessible to readers who cannot access the original Arabic legal texts. The worked examples and clear explanations of the mathematical principles involved make it particularly useful for readers who need to apply the rules to actual cases.`,
    metaDescription: "A comprehensive English guide to Islamic inheritance law covering Quranic shares, juristic principles, estate calculations, and practical applications."
  },
  {
    slug: "the-jinn-and-human-sickness",
    description: `The Jinn and Human Sickness is an English-language book that addresses the Islamic understanding of the relationship between jinn (unseen beings created from smokeless fire) and certain types of physical and psychological illness that some people experience. This is a topic that generates considerable interest and concern within Muslim communities but is frequently discussed in ways that are either sensationalized, oversimplified, or disconnected from the authentic Islamic sources. This book takes a balanced and evidence-based approach, grounding its discussion in the Quran, the authentic hadith, and the established scholarly tradition while acknowledging the limitations of human understanding regarding the unseen world.

The book begins by establishing what Islam definitively teaches about the jinn, drawing upon the Quranic verses and hadith that describe their nature, their abilities, their relationship with human beings, and the boundaries that Allah has established between the two creations. The jinn are presented as beings who, like humans, possess free will and moral responsibility, and who therefore include among their number both righteous and wicked individuals. The Quranic and prophetic evidence for the reality of jinn possession and the harm that certain jinn can cause to human beings is examined, along with the evidence that such harm is not as common as popular belief sometimes suggests. The book is careful to distinguish between what is firmly established in the authentic sources, what is reported in weak or fabricated narrations, and what is popular folklore that has no basis in the Islamic texts.

The section on jinn-related sickness provides a detailed discussion of the types of conditions that may be related to jinn activity, including possession (mas), the evil eye (ayn), and magic (sihr). For each type, the book presents the relevant textual evidence, discusses the scholarly consensus and differences of opinion regarding its reality and prevalence, and provides guidance on how to distinguish between conditions that may have a spiritual cause and those that are purely medical or psychological in origin. The book strongly emphasizes that most illnesses have natural causes and should be treated through conventional medical means, and that resorting to spiritual treatment should follow rather than precede proper medical evaluation.

The treatment section of the book provides detailed guidance on the Islamic methods for dealing with jinn-related harm, all of which are drawn from the Quran and the authentic Sunnah. These include the recitation of specific Quranic verses, particularly Ayat al-Kursi, the last two surahs of the Quran (Al-Falaq and An-Nas), and Surah Al-Baqarah, the use of ruqyah (spiritual healing through Quranic recitation), the use of specific prophetic supplications, and the legal rulings regarding seeking the help of practitioners who claim to treat such conditions. The book provides clear criteria for distinguishing between legitimate practitioners of ruqyah and those who use methods that are contrary to Islamic teachings. The ethical guidelines for treating people who believe they are affected by jinn-related conditions are also discussed, emphasizing the importance of compassion, confidentiality, and adherence to Islamic principles throughout the treatment process. The book serves as a valuable reference for Muslims who want to understand this sensitive topic from an authentic Islamic perspective, and for healthcare professionals who encounter patients who attribute their symptoms to spiritual causes.`,
    metaDescription: "An evidence-based English book on jinn, possession, the evil eye, and spiritual healing, grounded in authentic Quranic and hadith sources."
  },
  {
    slug: "the-kindness-of-the-queen",
    description: `The Kindness of the Queen is a children's book that retells the Quranic story of Queen Bilqis (the Queen of Sheba) and Prophet Sulaiman (Solomon), bringing this remarkable narrative to life for young readers with an emphasis on the queen's wisdom, her capacity for reasoned judgment, and the transformative power of kindness and truth. The story of Bilqis and Sulaiman is one of the most detailed and dramatically rich narratives in the Quran, occupying a significant portion of Surah An-Naml, and it offers children a story with strong characters, high stakes, and a profoundly satisfying resolution.

The narrative begins by introducing Queen Bilqis as a wise and capable ruler who governs her kingdom of Sheba with intelligence and authority. The book portrays her as a model of female leadership and wisdom, showing how she carefully considers information, consults with her advisors, and makes decisions based on evidence and reason rather than impulse or emotion. When she receives Prophet Sulaiman's letter inviting her to submit to Allah, her response demonstrates the balanced approach that characterizes her throughout the story: she neither dismisses the message outright nor accepts it uncritically, but instead gathers information, consults her council, and prepares to meet Sulaiman to judge the matter for herself.

The encounter between Sulaiman and Bilqis provides the dramatic center of the book. Sulaiman's remarkable abilities, including his command over the jinn and his knowledge of the natural world, are presented in a way that captures children's imagination while maintaining the Quranic focus on these abilities as signs of Allah's power rather than as ends in themselves. The famous episode in which Sulaiman commands one of his jinn to bring Bilqis's throne before her arrival is narrated with suspense and wonder. Bilqis's test, in which she is presented with what appears to be a pool of water and raises her skirts before realizing it is a polished floor of glass, is presented as a lesson about the importance of looking carefully before reacting and about the difference between appearances and reality.

The book places special emphasis on the theme of kindness as suggested by its title. The kindness of Queen Bilqis is demonstrated through her fair governance, her concern for her people, her respectful treatment of Sulaiman's message, and her ultimate decision to submit to Allah. Sulaiman's kindness is shown in his patient and respectful treatment of the queen, his use of wisdom rather than force to convey his message, and his generosity toward her upon her acceptance of the truth. The story demonstrates that kindness, combined with wisdom and truth, is the most powerful form of leadership and persuasion.

The educational value of the book extends beyond the central story. The discussion questions and supplementary material included at the end help children connect the story to broader Islamic themes such as the importance of seeking knowledge, the value of female leadership and wisdom, the relationship between natural phenomena and divine power, and the principle that truth speaks for itself when given a fair hearing. The book is suitable for children aged approximately five to ten years, and it serves as both an engaging story and a meaningful educational resource about one of the Quran's most important narratives.`,
    metaDescription: "A children's book retelling the Quranic story of Queen Bilqis and Prophet Sulaiman, teaching wisdom, leadership, and the power of truth and kindness."
  },
  {
    slug: "the-last-messenger-of-allah",
    description: `The Last Messenger of Allah is an English-language book that presents a comprehensive study of Prophet Muhammad as the final messenger in the chain of prophethood, examining both the theological significance of his role as the Seal of the Prophets and the historical details of his life and mission. The book approaches its subject from the conviction that understanding the person and the mission of Prophet Muhammad is essential for anyone who wishes to understand Islam, as he is the living embodiment of the Quranic message and the perfect example of human life as Allah intended it to be lived.

The theological section of the book establishes the Islamic understanding of prophethood as a divine institution through which Allah has communicated His guidance to humanity throughout human history. The concept of the finality of prophethood (khatam al-nubuwwah) is discussed in detail, explaining why the need for successive prophets came to an end with Muhammad and how his message constitutes the complete and final form of divine guidance for all humanity until the end of time. The evidences for his prophethood are examined systematically, including the miraculous nature of the Quran, the prophecies he made that were subsequently fulfilled, his character and conduct as attested by both his followers and his opponents, the impact of his message on human civilization, and the absence of any rational explanation for his achievements other than divine support.

The biographical section provides a detailed account of the Prophet's life from his birth in Mecca through his childhood, youth, prophethood, migration to Madinah, the establishment of the Islamic state, the major battles and treaties, the conquest of Mecca, the Farewell Pilgrimage, and his illness and death. Each phase of his life is examined with attention to both the historical events and the spiritual and moral lessons that they contain. The book draws upon the major classical sources of sirah (prophetic biography), presenting the accounts in a clear chronological narrative that allows readers to follow the development of the prophetic mission from its humble beginnings to its triumphant establishment.

The section on the Prophet's character and conduct (his sunnah) provides a detailed examination of how he implemented the Quranic teachings in his personal life, his family relationships, his interactions with companions and opponents, and his conduct as a leader, judge, military commander, and head of state. Specific aspects of his character, including his humility, his generosity, his courage, his compassion, his sense of justice, and his simplicity, are illustrated through well-authenticated narrations that bring his personality to life for the reader. The book emphasizes that the Prophet's example is not limited to the formal acts of worship but extends to every aspect of human life, making him a relevant guide for Muslims in every time and place.

The book addresses the common misconceptions and misrepresentations of Prophet Muhammad that circulate in non-Muslim discourse, providing factual and evidence-based responses that allow readers to form an informed opinion about his character and mission. The English language presentation makes this comprehensive treatment of the Prophet's life and significance accessible to a wide audience, including Muslims who want to deepen their knowledge, non-Muslims who want to understand Islam through the life of its founder, and students of religion and history who want a reliable reference on this important historical figure.`,
    metaDescription: "A comprehensive English study of Prophet Muhammad as the final messenger, covering his prophethood, biography, character, and divine evidence."
  },
  {
    slug: "the-last-of-the-prophets",
    description: `The Last of the Prophets is an English-language book that focuses specifically on the doctrine of the finality of prophethood (khatam an-nubuwwah) in Islam, presenting the theological foundations, the historical context, and the contemporary relevance of this essential Islamic belief. While many books on Islamic theology mention the finality of prophethood as one among several articles of faith, this book dedicates its entire contents to a thorough examination of this doctrine, exploring its implications for Islamic theology, its role in Muslim identity, and its significance in the broader context of religious history.

The book begins by establishing the Quranic basis for the finality of prophethood, examining each verse that addresses this topic and providing detailed linguistic and contextual analysis that clarifies the meaning and scope of the Quranic statements. The verse in Surah Al-Ahzab in which Allah describes Muhammad as the Seal of the Prophets receives particularly extensive treatment, as this verse is the foundational text for the Islamic belief that no prophet will come after Muhammad. The various interpretations that have been offered for this verse by classical scholars are discussed, demonstrating the breadth of scholarly consensus on its meaning despite minor differences in emphasis or formulation.

The hadith evidence for the finality of prophethood is presented systematically, with each relevant narration examined for its authenticity, its chain of transmission, and its specific contribution to the overall understanding of the doctrine. The famous hadith in which the Prophet explicitly stated that there would be no prophet after him, the hadith in which he described himself as the seal of the prophets in a literal sense, and the various narrations in which he warned against the appearance of false claimants to prophethood in the later days are all discussed in detail. The book demonstrates that the evidence for the finality of prophethood in the hadith literature is both extensive and unambiguous, forming one of the most firmly established doctrines in all of Islamic belief.

The historical section of the book examines how the doctrine of the finality of prophethood functioned as a defining boundary of the Muslim community throughout Islamic history. The various movements and individuals who claimed or were claimed to have prophetic status after Muhammad are discussed, along with the responses of the mainstream Muslim scholarly community to these claims. The historical record demonstrates that the Muslim community has consistently and unanimously maintained the finality of prophethood as a non-negotiable tenet of Islamic faith, rejecting every claim to prophetic authority regardless of the prestige, influence, or apparent sanctity of the claimant.

The contemporary section addresses the modern context in which the doctrine of the finality of prophethood has become particularly significant. The book examines the theological arguments used by various groups that challenge or reinterpret the doctrine, and it provides detailed, evidence-based responses to these arguments. The relationship between the finality of prophethood and the completion and perfection of the religion of Islam is discussed, showing how the two concepts are logically interconnected. The book argues that the finality of prophethood is not merely a historical fact about the end of the line of prophets but a positive theological statement about the completeness, sufficiency, and timelessness of the guidance that Allah has provided through Muhammad and the Quran. The English language presentation makes this important theological discussion accessible to readers who need to understand both the doctrine itself and the arguments surrounding it in the contemporary religious landscape.`,
    metaDescription: "An English book on the Islamic doctrine of finality of prophethood, examining its Quranic basis, hadith evidence, and historical consensus."
  },
  {
    slug: "the-last-world",
    description: `The Last World is an English-language book that presents a comprehensive treatment of the Islamic understanding of the Hereafter (al-Akhirah), the eternal existence that follows the termination of worldly life. The Hereafter is one of the six articles of Islamic faith, and belief in its reality is repeatedly emphasized in the Quran as a central pillar of correct belief and a fundamental motivator for righteous conduct. This book provides a detailed and vivid description of what Islam teaches about the events and states that constitute the Last World, drawing upon the Quran, the authentic hadith, and the classical scholarly tradition to present a thorough and reliable account.

The book is organized in a sequence that follows the chronological order of events as described in the Islamic sources. It begins with the process of death and what Islam teaches happens to the soul and body at the moment of death and during the period in the grave (al-barzakh). The questioning in the grave by the two angels, Munkar and Nakeer, is described with reference to the relevant hadith, along with the states of the grave as a place of either bliss or punishment depending on the person's faith and deeds. The book addresses common questions about the experience of the grave, the nature of barzakh, and the relationship between the soul and the body during this intermediate period.

The major events that precede the Day of Judgment are covered in extensive detail. The blowing of the trumpet, the resurrection of all creatures, the gathering of creation for the accounting, and the presentation of the records of deeds are each treated in separate chapters that examine the relevant textual evidences and provide descriptive accounts based on the authentic narrations. The book then turns to the Day of Judgment itself, describing the conditions of that tremendous day, the intercession that the Prophet and others will be permitted to make, the weighing of deeds on the scales, and the crossing of the bridge over the Hellfire.

The descriptions of Paradise (Jannah) and Hellfire (Jahannam) are among the most extensive and detailed sections of the book. The Quran and hadith contain numerous descriptions of both destinations, using language that is both literal and metaphorical to convey realities that are beyond full human comprehension. The book presents these descriptions faithfully, covering the physical pleasures of Paradise including its gardens, rivers, palaces, and companionship, as well as the spiritual pleasures that the Quran describes as being even greater than the physical ones. Similarly, the descriptions of the Hellfire's punishments are presented from the primary sources, conveying the seriousness of the Quranic warnings without sensationalism or speculative elaboration.

The book also addresses the practical and spiritual implications of belief in the Hereafter. The final chapters discuss how the conscious awareness of the Last World should affect a Muslim's priorities, values, and behavior in this life. The principle that worldly life is a test whose results are realized in the Hereafter is explored in detail, showing how this belief provides both the motivation for righteous action and the patience to endure worldly difficulties. The relationship between hope in Allah's mercy and fear of His punishment is discussed as a balanced approach to spiritual life that neither leads to despair nor to complacency. The Last World is written in clear, accessible English that makes this important area of Islamic belief understandable for general readers while maintaining the scholarly rigor that the subject demands.`,
    metaDescription: "A comprehensive English book on the Islamic Hereafter covering death, the grave, the Day of Judgment, Paradise, and Hellfire with textual evidence."
  },
  {
    slug: "the-life-of-prophet-made-simple",
    description: `The Life of Prophet Made Simple is an English-language book that presents the biography of Prophet Muhammad in a format designed specifically for readers who want a clear, accessible, and straightforward account of the Prophet's life without the complexity and density that characterize many classical biographical works. The sirah (prophetic biography) is an enormous field of Islamic literature, and the major classical works such as those of Ibn Ishaq, Ibn Hisham, al-Waqidi, Ibn Sa'd, and Ibn Kathir run to many volumes of detailed, sometimes technical, Arabic prose. This book distills the essential content of these works into a single, well-organized volume that covers the complete life of the Prophet from birth to death.

The book follows a chronological structure that begins with the conditions of the Arabian Peninsula before the advent of Islam, providing the historical and cultural context that is necessary for understanding the significance of the Prophet's mission. The lineage of Prophet Muhammad, the events surrounding his birth, his childhood, his youth, and his pre-prophetic life as a merchant known for his honesty and integrity are covered in the opening chapters. The narrative then moves to the beginning of revelation, the first three years of secret preaching, the public proclamation of Islam, and the persecution that the early Muslims faced at the hands of the Quraysh.

The major events of the prophetic mission are covered in sufficient detail to be meaningful while avoiding the overwhelming level of detail found in comprehensive biographical works. The migration to Abyssinia, the conversion of Umar, the boycott of the Muslims, the Year of Sorrow, the Night Journey and Ascension, the migration to Madinah, the building of the mosque, the establishment of the brotherhood between the Ansar and Muhajirun, the major battles of Badr, Uhud, and the Trench, the Treaty of Hudaybiyyah, the conquest of Mecca, the Battle of Hunain, the Farewell Pilgrimage, and the Prophet's illness and death are all presented as distinct chapters or sections with clear headings that make the material easy to navigate.

The simplified format of the book does not mean that the content is simplistic or that important details have been omitted. The author has made careful decisions about what to include and what to condense, ensuring that the essential facts, the key lessons, and the most significant aspects of the Prophet's character and mission are all preserved. The book includes the major treaties and agreements that the Prophet made, the important delegations that visited him, and the key teachings and practices that he established. The language is straightforward English that avoids archaic or overly formal constructions, making the narrative flow naturally and readably.

This book is particularly suitable for new Muslims who are encountering the Prophet's biography for the first time, for young readers and students who need an introduction before progressing to more detailed works, for non-Muslims who want a reliable and readable account of the Prophet's life, and for anyone who wants a concise reference that covers the major events without requiring the time and effort needed to work through the massive classical biographical works. The Life of Prophet Made Simple can serve as a standalone introduction or as a stepping stone to more advanced study of the sirah, and its clear organization and indexing make it useful as a quick reference for specific events and topics.`,
    metaDescription: "A simplified English biography of Prophet Muhammad covering his complete life from birth to death in an accessible chronological format."
  },
  {
    slug: "the-life-of-the-last-prophet",
    description: `The Life of The Last Prophet is an English-language book that presents a detailed and engaging account of Prophet Muhammad's life, distinguishing itself from other seerah works through its narrative-driven approach that emphasizes the human story behind the historical events. While many biographies of the Prophet present his life primarily as a sequence of dates, battles, and legal rulings, this book focuses on the human dimensions of his experience, exploring his emotions, his relationships, his personal struggles, and the qualities of character that made him the most influential person in human history according to many assessments.

The book opens by painting a vivid picture of the world into which Muhammad was born, describing the social conditions, religious landscape, and cultural norms of sixth-century Arabia in a way that helps the reader understand both the challenges and the opportunities that the Prophet would face in his mission. The description of Mecca before Islam, with its tribal rivalries, its economic structures, its religious practices centered on the Kaaba, and its position as a major trade center, establishes the context within which the prophetic mission unfolded. The book then traces the Prophet's early life with particular attention to the formative experiences that shaped his character, including the death of his father before his birth, the death of his mother when he was six years old, his upbringing under his grandfather Abdul Muttalib and then his uncle Abu Talib, and his early career as a merchant.

The narrative of the prophetic mission is told with a focus on the drama and emotional intensity of the events. The experience of receiving the first revelation in the cave of Hira is described in a way that conveys the mixture of awe, fear, and bewilderment that the unlettered Muhammad must have felt. The reactions of various individuals to his message are explored with psychological insight, showing why some people were immediately drawn to Islam while others fiercely opposed it. The personal costs of the mission, including the persecution of his followers, the loss of loved ones, the assassination attempts, and the periods of acute danger, are treated with the sensitivity they deserve, showing the Prophet not as a distant historical figure but as a human being who experienced suffering and hardship in the service of his mission.

The book devotes significant attention to the Prophet's relationships, which are among the most instructive aspects of his biography. His marriages, each of which served a specific social, political, or educational purpose, are discussed individually and in the context of the circumstances that led to each one. His relationship with his wives, his children, his companions, and even his opponents is examined with nuance, showing how his dealings with different people revealed different aspects of his character. His treatment of the conquered Meccans after the conquest, when he had the power to exact revenge for years of persecution but instead chose forgiveness and reconciliation, is presented as one of the most remarkable examples of magnanimity in all of human history.

The writing style of the book is literary and engaging, with descriptive passages that create vivid images and emotional resonance that makes the historical narrative come alive. The book draws upon the major classical sources but presents the material in a modern narrative style that is accessible to contemporary English-speaking readers. This approach makes The Life of The Last Prophet suitable not only for Muslims who want to deepen their connection to the Prophet's story but also for general readers who appreciate well-written historical biography and are interested in understanding the life of the man who founded one of the world's major religions.`,
    metaDescription: "A narrative-driven English biography of Prophet Muhammad emphasizing the human dimensions of his life, relationships, and character."
  },
  {
    slug: "the-light-of-guidance",
    description: `The Light of Guidance is an English-language Islamic book that offers a collection of teachings, reflections, and practical guidance on various aspects of Islamic faith and practice, presented with the clarity and warmth that its title suggests. The metaphor of light is central to the Quran's self-description, as Allah describes the Quran itself as a light that has come down, and the Prophet as a lamp spreading light. This book takes that metaphor seriously, aiming to illuminate the path of Islam for readers who are seeking understanding, spiritual growth, and practical guidance in their religious lives.

The book is organized into thematic sections that cover the major areas of a Muslim's religious life. The section on faith and belief provides clear, concise explanations of the articles of iman, addressing common questions and misunderstandings about each pillar of faith. The discussion of tawheed goes beyond the basic definitions to explore how the awareness of Allah's oneness and presence can transform a person's daily experience, turning ordinary moments into opportunities for remembrance and gratitude. The chapter on the pillars of Islam similarly combines practical guidance on performing each pillar with a discussion of its spiritual dimensions and its purpose in the broader framework of a Muslim's relationship with Allah.

The section on the Quran addresses how Muslims can develop a meaningful relationship with the Book of Allah. The book provides guidance on establishing a regular Quran reading habit, understanding the basic principles of tafseer, memorizing Quranic verses, and reflecting on the meanings of what one reads. The discussion emphasizes that the Quran is not merely a text to be studied but a living guidance to be experienced, and it offers practical suggestions for moving from surface-level reading to genuine engagement with the Quranic message. The recommended daily reading schedules, the methods of review for those who have memorized portions of the Quran, and the etiquette of handling and reciting the Quran are all covered with practical specificity.

The section on the Prophet's guidance (the Sunnah) explores how the example of Prophet Muhammad provides practical direction for every area of a Muslim's life. The book discusses specific aspects of the Prophet's character and conduct that are particularly relevant to contemporary life, including his manner of speaking, his approach to disagreements, his treatment of family members, his business practices, and his approach to personal development. The principle of following the Sunnah is presented not as a burden of imitation but as an opportunity to benefit from the wisdom of the person whom Allah described as having the best character.

Additional sections address topics such as the development of good character traits, the management of spiritual challenges such as doubt and spiritual dryness, the etiquette of Islamic social interaction, the principles of Islamic finance as they apply to personal financial management, and the approach to contemporary issues from an Islamic perspective. Each topic is treated with clarity, warmth, and an emphasis on practical application rather than abstract theory. The writing style is accessible and engaging, making the book suitable for a wide range of readers from new Muslims seeking basic guidance to experienced practitioners looking for renewed inspiration and deeper understanding. The Light of Guidance serves as both a comprehensive introduction to Islamic knowledge and a source of ongoing spiritual nourishment.`,
    metaDescription: "An English Islamic book offering clear guidance on faith, Quran, Sunnah, character development, and spiritual growth with practical focus."
  },
  {
    slug: "the-little-learner-my-first-book-of-islamic-knowledge",
    description: `The Little Learner (My First Book of Islamic Knowledge) is a foundational English-language Islamic education book designed specifically for young children who are beginning their formal introduction to the basic teachings of Islam. The book recognizes that the first exposure a child has to religious knowledge has a lasting impact on their relationship with Islam, and it has been carefully crafted to make this first encounter positive, engaging, and developmentally appropriate. The content covers the essential building blocks of Islamic knowledge that every child should learn in their early years, presented in a format that supports both classroom instruction and home learning.

The book is organized into clearly defined sections that correspond to the major areas of basic Islamic knowledge. The section on Allah introduces young learners to the concept of God in Islam through simple, age-appropriate language that conveys the central attributes of Allah's oneness, His role as Creator, and His love for His creation. The language is carefully chosen to avoid abstract theological terminology while still communicating the essential meaning accurately. The section on the five pillars of Islam introduces each pillar with a simple explanation, an illustration, and a brief description of how it is performed. The shahadah, salah, zakat, sawm, and Hajj are each treated on a dedicated page or spread that provides enough information for a child to understand the basic concept without being overwhelmed by detail.

The section on Prophet Muhammad provides a gentle introduction to the life of the final messenger of Islam, focusing on the aspects of his character and mission that are most relevant and understandable for young children. His kindness to children, his love for his family, his honesty, and his care for animals are emphasized, giving children a positive and affectionate image of the Prophet that they can relate to and aspire to emulate. The section on the Quran introduces the concept of the Quran as Allah's book, explaining in simple terms what it is, how it was revealed, why it is important, and how Muslims show respect for it. Basic Quranic surahs such as Al-Fatiha, Al-Ikhlas, Al-Falaq, and An-Nas are included with their Arabic text, transliteration, and English translation, providing young learners with their first Quranic vocabulary.

The section on Islamic manners covers the basic etiquette that Islam teaches for daily life, including greeting others with salaam, saying Bismillah before eating, saying Alhamdulillah after eating, being kind to parents, respecting elders, being gentle with younger children, and keeping oneself clean. Each manner is presented with a simple explanation of why it is important and how to practice it, supported by a relevant hadith or Quranic reference presented in child-friendly language. The section on dua introduces a selection of simple daily supplications that children can learn and use, covering situations such as waking up, going to sleep, entering and leaving the mosque, and before and after eating.

The physical design of the book supports its educational purpose. The pages are printed on durable paper suitable for young children, the binding is sturdy, and the dimensions are appropriate for small hands. The layout uses large, clear text, ample white space, and engaging illustrations that capture children's attention and help them visualize the concepts being taught. Activities such as tracing, matching, and coloring are integrated into the content to reinforce learning through active engagement. The Little Learner is suitable for children aged approximately three to seven years, and it can be used by parents at home, in preschool and kindergarten Islamic programs, and in weekend school settings. It provides a solid foundation upon which more advanced Islamic education can be built in subsequent years.`,
    metaDescription: "A first Islamic knowledge book for young children covering Allah, the five pillars, Prophet Muhammad, Quran, daily manners, and basic duas with activities."
  }
];
async function main() {
  for (const item of updates) {
    await prisma.product.update({ where: { slug: item.slug }, data: { description: item.description, metaDescription: item.metaDescription } });
    console.log("Updated:", item.slug);
  }
  console.log("Done");
}
main().then(() => prisma.$disconnect());
